### ISSUE TITLE
Tooltips on Mac

### ISSUE THREAD

**Issue by ErikDeBruijn** [daid/LegacyCura#1]
I'll try to assist through teamviewer to point out when it works...

**Comment by daid** [comment]
Do the tooltips ever work on MacOS?
If not, it would be interesting to see if the "OnPopupDisplay" and "OnPopupHide" functions are called at all. They are in newui/configBase.py, and a simple print would show if those functions are called at all.

**Comment by ErikDeBruijn** [comment]
The bind function section is ran, the update too, but display and hide aren't run (at least, I don't see the results from the print statement in those functions...)

**Comment by daid** [comment]
Looks like the EVT_ENTER_WINDOW and EVT_LEAVE_WINDOW events don't work on text controls for MacOS (googling shows more people with the same problem)

I'll have to think up a way around that...

**Comment by daid** [comment]
I might have worked around this now. Let me know what the latest version does. It might still have a few issues with the popups hiding after showing, but they should popup now.

**Comment by RedwoodForest** [comment]
There are definitely issues with popups not hiding after showing. Once a popup is displayed it is not dismissed until a different popup is displayed (even if you go to another tab or even another program — I've got a popup displaying on top of Safari at the moment as I type this).

They do show though:).

**Comment by ErikDeBruijn** [comment]
Hi Daid, already an improvement.

I made a little screencast to understand how it behaves now:
http://youtu.be/JKCG4Bm3v5Y

It would be nice if the popup is hidden when you move or unfocus the entire window.

**Comment by daid** [comment]
Ah, damn. They also don't hide when moved over (which is something I did try to add). MacOS seems to be much more limited in which events are usable from controls. Time to put up the thinking hat again.

**Comment by daid** [comment]
While trying to use EVT_KILL_FOCUS I discovered something.
I made some changes and now MacOS popups might work, or might not work at all.

**Comment by ErikDeBruijn** [comment]
The Popups stopped working... so that's not it...

**Comment by daid** [comment]
I think my current solution should show the popups, at the bottom of the window. This is because the popup don't go away until you select something else. And if the popup was on top of another setting you cannot select that one.

It's not a perfect solution, but it's the best I could came up with right now.

**Comment by ErikDeBruijn** [comment]
It doesn't show the popup yet, but I may be testing the wrong version.
commit dd79a4c140dedddc64e196d644694814e128da00
Author: daid daid303@gmail.com
Date:   Fri Mar 16 15:25:40 2012 +0100

Running:  python skeinpypy.py in dir: SkeinPyPy/SkeinPyPy/ (NOT NewUI, I lost the python file there... so can't run it!)

**Comment by daid** [comment]
I renamed the SkeinPyPy_NewUI to SkeinPyPy today. So makes sense you can no longer find the NewUI.

Odd that it doesn't show the popup. I've asked the wxPython-Mac maillinglist for help, maybe they can figure it out...
