### ISSUE TITLE
FR: project planner: start next object outside/outline (and related bug)

### ISSUE THREAD

**Issue by jgeerds-zz** [daid/LegacyCura#100]
Please change the project planner gcode generation so the head doesn't move to the center of the next object, drops down (and leaves some plastic pile from dripping/waiting over the spot), and drags the plastic to the spot where the print starts. this is causing the bottom (in my case the front face) to have nasty scars.

This is kind of related to the cura default start code (since it mimics the exact same behavior), moving the head to the center and start there isn't nice.

Please jump to the beginning of the next print (ideally where the outline (if any) is, not the center of the object.

Bug report: when using the duplicate object function (placing i.e. 25 identical objects on the plate), the head moves at the exact same z-height where the last object ended, to the next position, and accidentally hitting/dragging/destroying/catching previously printed objects. please lower the bed to a safe z-height before jumping to the next spot.

**Comment by daid** [comment]
I've adjusted the next Z move so it no longer hits other objects (5mm clearance) in the development version.

Your other suggestion is a bit more complex, but I do like it.

**Comment by daid** [comment]
This should be fixed in the latest version of the nextobject.gcode and start.gcode.
