### ISSUE TITLE
Request: Change terminology in custom setup

### ISSUE THREAD

**Issue by ghost** [daid/LegacyCura#1001]
If you install Cura, you have the option to do a custom configuration. In the configuration menu there is a step (the last step) where you have to enter the data of your printer. This includes the Name, width, depth and height. Using the words "width", "depth" and "height" is thoroughly correct but eventually problematic for beginners - one could mix up width and depth. 

I'd humbly request to add which axis is meant. Something like this:
Machine width  X (mm)
Machine depth Y (mm)
Machine height Z (mm)

This little thing would make it way easier to setup. Sure, if one thinks about it for a short time the axis become clear. On the other hand it is one of the details that matter for usability.

Steps to reproduce: Install Cura (English Version), start for first time, select "Other", select "Custom". 
Alternative: Click on Expert tab in installed Cura, select "Run first wizard....", follow steps above.

I have to say: The software is pretty awesome already. I am used to the combination Slic3r / Printrun / Pronterface. Which is nice, but I really love all that visualization stuff. Like Overhangs/X-Rays and Layers. Will thoroughly put the software to the test. Keep the great work up!

If there already has been a similar issue request (I haven't found one), please post the link and then ignore this message.

Summary: The language used in the first run wizard of the English wizard contains words that do give the meaning but can potentially cause confusion about the axis.

**Comment by adeebshihadeh** [comment]
Should be simple enough to add. I'll work on it

**Comment by adeebshihadeh** [comment]
Done. I added it to my existing pull request. https://github.com/daid/Cura/pull/1125/commits
