### ISSUE TITLE
Diffrent gcode output at 14.07 and 14.09

### ISSUE THREAD

**Issue by harry32009** [daid/LegacyCura#1005]
CURA_PROFILE_STRING:eNrtWUtv20YQvhJCf8QcEzRWST3qOIIuSW1fmiKAXdTx
hViRK3Frkkssl5Yf0H/vtw9JpC0HSRq0eUgHOTs7Mzs7+83Mhyhnt1zFGReLTE/D
/iBYsjyPdSaSq5LXNUQvA8W1YokWsox5yWY5n56rhge1zEUa59ZB12Au4CPlZS30
7XQQBqW8u8t5XIs7jv1RUClR6riuOE+nw9AvNS8qrphuFJ9GRzukg+kO4XCXcLQR
znjacXwYBnVTVVLp6R+y5EGVMz2XqohZmvEaN5y+VqJY68Rpw/KY32jVuD2ps2Ap
Kh5rueRqesLymrcE8bXMmwLhjwMp73DhTPA89WpICis4YkoF/mqYR/3D8WOxueYj
4XCXcNQWznO5nB4d9cft53IpHoRhP2yLWSGbUk87qvaqfiP6teumEGWMxTXPEXNn
J5HFTJQLB4iuhSg6uUMIg7ZGJiuLt5nUWhYdAA0CC6owXopUZ/EcFhLZCsNAzv7m
CZAjyivjMJDXXOWsssFDgLy7MP3Fo7FR8ic4oK4zEojSotStjZooa67Dh4KbliCR
Mre58JgX7qnnbF0XqS+MKwHs5KLkyI/N59jLFqyyntxqnaSclwud+WiNt3mDyHxN
Rlbi7xOG21VcsBsr2YQ1hxQ4R1BemHGGAhVz7SHoKlYj8+21y48L3ebEZ9WG7QtB
31Z8eqpEupGwcoFGcLSpp9ia2uO3Zje3AGutWZmYwh9uN+7acnNOJRTLTX9wGRRF
hYZRyJT7UGcoywcpVWyOHDK1ECVubBBuBFanrlhiYAnfTjpjNX+Asa3cmFio2eZk
5egdXAF4O422m21LfxITyr6yW9WNVzSIqW293gD6SgnAJW5KW42m4SK/MVu/wdMq
s00zaevgDrLiZTwTut6lgCo0zfgaidFCJ5lJjVOr8gbpQ05RDYvps7yKev11lSXc
3DO+mR5ED0S3EP2E51O6v0jMG50OXvZOI7oc08k4DEOakEEdub4f8DL1em+jcERn
YQ/6dBES9DJZcLogdiPq3tuXIzKfCQEcpp6okKh8bAzh8ywynt+Zby/orvbb3e3A
PtDAZ35ylouEp8T0K7pP2e3KfGuOP6aNrXqT16wWCaHjaaCjfkW/G8SSa0IwyVs8
YUV/AZDQue+ShRWdoAdA3J7/cP3OjGIy52DPD2t36ImfXgQIp87QTTM3iFZFS7R0
Zy9aVomsddvKrOH1LegDnd3vZAArmvxZYmpZey2JpSndykaRXJYEXWrpkilv486A
9v4Ry/igq51ujug82uVp8Fmuwn8f1OkgIv+ZgFIoIOCa5Q2ve6dI4XqHzTAoGs2p
knhR9CMgpIcYDtcKFmm0FDojnXHCiCI5n6+r/L0p9AJDhS5+eW9iwqwi9IQag6i2
SpehD8EoXT5WQWeJxv2QTu7b433lDcyRax5HqblnNC6K3vnmat3P5GxpeqA5xVgO
ypQsS0m5wq0HdBzusLnjyql71ZTc0DaxnYBf0XHUNZt4RYrCokA2yAxnwn2Sq08/
hdiCiXJ71sH9buK26p2HH3XpuVC1/pau3X14tJRGk8U+oEgFeg9bcJIl/f7mN6oT
xXkJgEaH9M7r9Pt9M4Y23fAYr376Bv/s2eo+t21zZ+LWSUIrRL9UFtjOJvpEm9HT
h1i91PafrQk9E3NTu5Th6iT0c2TwCUw/cKc4ygHjvlOwSOPxAVJpZsSHjS20PE58
p2UEboH4UGPcznaTd6PhRvwLAyycykGnqDYjHU9v61LhbdBubA3/HPbHiGFMFwcD
tAXztbuiL6mp/JEMD7WOaBMNv+YluIFxu20xH7zUU+3nBaK1gRqqTKImCWD52Jfs
dkNJdjqtNa/QT2vX7I6ejmFnB3Xzebifz/v5/GPO58GPOJ/3pGRPSh6QkuH/SUqM
zWBPZPZE5vOJTG+CMSdxJ/PfS4D2YuWozWhPbb4qajP4ctRmz5L+M5Y0/KjZOULQ
3xFh+DhqOPy+Lr2nhntq+IAajr41amhshns6uaeTX5ZO+l+N2z85boTbXxfdj94d
JStpaSiOGZvwflJfTwM8gmszxx6XG8Lqms+M6yUq0146aZSyKV5D2DyAfWhINtIX
tMxgsKl0SyaKJteiyjftQtX93uQ8Q1LNaSa5oDcW5RZFxun5s/J5gJzoryk+NjcF
uA7vHzLGQCI=

here is the profile,i want to print a vase with 0.8mm shell thinkness use spiralize function,but the bottom solid fill was strange at version 14.09, it works fine in 14.07,why?  

14.07:

![image](https://cloud.githubusercontent.com/assets/5800992/4966512/3b1a957e-67cb-11e4-8af0-b7c75443fa88.png)

14.09

![image](https://cloud.githubusercontent.com/assets/5800992/4966293/8476e322-67bb-11e4-8b03-2ac7dad79740.png)

**Comment by nallath** [comment]
I don't see what's strange about it. Why do you think this is a strange result?

**Comment by InnovationSystemsAU** [comment]
It looks like you're using a raft in the top one. Also I can see some differences in extrusion widths there.
