### ISSUE TITLE
What plastic is the best for enclosures of low voltage electronica? 

### ISSUE THREAD

**Issue by Atlanta11** [daid/LegacyCura#1006]
Hello what plastic is the best for enclosures of low voltage electronica? 
Is this abs or pla or something else?

http://ec.europa.eu/enterprise/policies/european-standards/harmonised-standards/low-voltage/index_en.htm

**Comment by nallath** [comment]
Well, answering these is not really something about the software, but all right...

I have no idea what the CE rules are. But if you want something to last, PLA is not the material to use, because its bio degradable. Nylon, PETG, ABS or HIPS would probably be better.
