### ISSUE TITLE
(re) add option for infill pattern

### ISSUE THREAD

**Issue by simen** [daid/LegacyCura#1008]
I would like to be able to override the automatic infill pattern every now and then. Mostly I prefer the Lines-variety. I see that all the plumbing is in place to support such a parameter in CuraEngine. Is this an option that has been removed? Any hope for acceptance if I submit a pull request to this effect?

**Comment by nallath** [comment]
Daid is on a holiday for the next two weeks, so any pull requests will probably not be handled until he is back. But pull requests are always welcome though :)

Why would you want the lines infill pattern? The current square infill pattern is a lot stronger.

**Comment by daid** [comment]
This has been implemented for the PinkUnicorn version, and won't be backported to the "older" version . To prevent setting creep.
