### ISSUE TITLE
Project planner prefs are only becoming valid upon reopening the project planner

### ISSUE THREAD

**Issue by jgeerds-zz** [daid/LegacyCura#101]
Please make the project planner preferences valid as soon as the pref window is closed. right now, any changes don't reflect the yellow outline on the plate, and the project planner needs to be closed, and reopened, for the prefs to function.

FR: please add a z-height for the head dimensions, since I started to print completely fanless, and like to utilize the small&compact size of my print head.

**Comment by daid** [comment]
Not sure how you see the "z-height" as head dimension?

I can understand that a better way to describe the printer head is as a pyramid shape, instead of a box. However, the extra code complexity is not really worth it.

**Comment by daid** [comment]
Could you check if RC4 fixes this problem?
