### ISSUE TITLE
Requesting a "Creat G code" button

### ISSUE THREAD

**Issue by Lyonidaspay** [daid/LegacyCura#1014]
Dear Daid.

 1) I 'm always having problems with the auto calculation option that would calculate the path in every single change in the options like  infill, layer height, ,,,, 

```
I would like to have a button to do that, and not auto calculation ,

If possible :-)
```

2 ) I have a heated bed and when using it with 80 ° my prints are awesome,   but in the beginning the nozzle leaks a lot , because the extruder reaches 220 ° long before the bed, so It starts leaking and then when it autolevels, the amount of PLA sticks on the nozzle and burns, ( it puts some black burned plastic on the printed part ) 
   Also at the end of the print the nozzle keeps leaking witch empty the nozzle and it the next print I have some hot air coming from it , and I loose the 5th first lines of the brim, Sometimes I even get some drops of liquid plastic.
    so I had to change the Start and End G-Code  with that 

START 

M190 S80 ;Uncomment to add your own bed temperature line
M109 S190 ;Uncomment to add your own temperature line
G21        ;metric values
G90        ;absolute positioning
M82        ;set extruder to absolute mode
M107       ;start with the fan off
G28 X0 Y0  ;move X/Y to min endstops
G1 X40 Y40 F9000
M104 S220
M117 Homing Z axis
G28 Z0     ;move Z to min endstops
M117 Cleaning nozzel
G1 Z20.0 F{travel_speed} ;move the platform down 20mm
G92 E0                  ;zero the extruded length
M117 Extruding 25
G1 F200 E25             ;extrude 15mm of feed stock
G1 F200 E-1             ;Cut the filament
M117 More cleaning
G1 X60 Y20 E20 F2000
G92 E0                  ;zero the extruded length again
G1 F{travel_speed}
;Put printing message on LCD screen
M117 Printing        ....

END GCODE

M104 S100
M140 S0   ;heated bed heater off (if you have it)
M117 Cooling the extruder
M106 S255 ;Cooling the extr
G91       ;relative positioning
G1 E-2 F{travel_speed} ;retract the filament a bit before lifting the nozzle,
;to release some of the pressure
G1 Z+0.5 E-15 X-20 Y-20 F{travel_speed} ;move Z up a bit and retract filament even more
G28 X0 Y0                   ;move X/Y to min endstops, so the head is out of the way
M117 Cooling nozzel to 100°
M109 R100                    ;Wait for ext heater to cooldown
M117 Cooling nozzel to 100°
M104 S0
M107                        ;Turn off the fan again
M84                         ;steppers off
G90                         ;absolute positioning
;{profile_string}

And I don't get that issue any more .

But the problem is that I don't get the messages on the LCD screen, I only get the
   Homing Z axis and then 
Printing ...

Can you help me with that !

Sorry if the message is too long, I really hope that you read it ! ! 

Thank you

**Comment by nallath** [comment]
You can change the start-end g-code by yourself. Putting the heated bed at 80 degrees for PLA is far to hot btw. 

The auto calculate will not be removed.

**Comment by Lyonidaspay** [comment]
thank you !
