### ISSUE TITLE
No return to zero in Z axis for the next Object

### ISSUE THREAD

**Issue by Lyonidaspay** [daid/LegacyCura#1016]
Hello ! 

When printing multiple objects in cura 14.11 RC7 , ( One at a time ) I noticed that the nozzle don't goes back to the real Zero for the second part, it starts printing at about 0.5 mm from the bed witch weakens the first layer and makes it impossible to print ( it won't stick to the bed ) 

 so if possible I need a technique or a plugin to RE home the Z axis after each part, please.

thanks

**Comment by Lyonidaspay** [comment]
It would be a bit boring to stay next to the printer  and tweak the nozzle
like you said.

**Comment by Lyonidaspay** [comment]
Every first part is printed very well. The problem comes for the next ones.

**Comment by JustAnother1** [comment]
Can you take a look at your G-Code files ? The Lines with the Z in it?
After the first print it should return to the same Z hight it used for the first layer of the first print.

Can it be that this is a problem of your printer? Could there be backslash/lost steps on your Z Axis? Due to the weight of the bed moving up and moving down are very different loads for the stepper,..

**Comment by Lyonidaspay** [comment]
Thanks . But how to check for missing steps on the Z axis .
And i think it would be easy to put a G28 Z0 ( homing Z)  at the end of the
first part just after moving from the previous part , isn't it ?
I can do it myself by tweaking the G-code file but it would be a repeated
action every time.

A plug-in for that would be nice.

**Comment by JustAnother1** [comment]
You could create a g-Code file that moves Z up and down. If it looses steps on all down movements then after some up and down with the G-Code ending in Z0.2 the distance between the build platform and the nozzle should be more then 0.2 ANd the distance should become bigger with more ups and downs.

A "repeated start" -Gcode  as addition to the configurable Start end end Gcodes would also be a nice thing. @daid : Feature Request ?

**Comment by Lyonidaspay** [comment]
I didn't understand your last suggestion !! 
When moving from part to an other part in the ONE AT A TIME option , there is no end Gcode requested ! 
it only moves the Z axis to 0.3 mm by asking the G0 Z0.3

check this

last layer starts here from the previous part
TYPE:FILL
G1 F540 X128.351 Y72.718 E54.56362
G1 X128.156 Y72.405 E54.56610
G0 F9000 X127.829 Y68.383
G0 X126.264 Y66.853
G0 X124.085 Y66.724
G0 X122.309 Y66.558
G1 F540 X122.113 Y66.361 E54.56796
M107    ;      Turning the fan off
G92 E0  
G1 F2400 E-4.50000      ;pulling back some material 
G1 Z0.675                       ; moving the Z axis a bit down 
G0 F9000 X122.113 Y66.361 Z5.600
G0 X120.000 Y101.571          ; moving away from the prevous part 
;Layer count: 4
;LAYER:0
G0 X108.643 Y90.214 Z0.300      ; you can see here that the Z is trying to reach 0.3 mm
;TYPE:SKIRT
G1 Z0.300                                  ; here is the problem, it puts materiel in more than 0.3 mm
                                                   I need to put the G28 Z0 over here
G1 F2400 E0.00000                   ;   and the second parts is begining  . . . . 
G1 F1200 X141.357 Y90.214 E0.59229
G1 X141.357 Y122.928 E1.18458

**Comment by JustAnother1** [comment]
My suggestion was a G-Code file like this:

G28 Z0     ;move Z to min endstops
G1 F9000 Z5.600
G1 Z0.300
G1 Z5.600
G1 Z0.300
G1 Z5.600
G1 Z0.300
G1 Z5.600
G1 Z0.300
G1 Z5.600
G1 Z0.300

Then check if the nozzle is at Z0.3

**Comment by Lyonidaspay** [comment]
I just tried this znd I found that the Z axis missed a LOT of steppes when moving Up !
I repeated these steps a dozen time and always at the same height !!!!!

**Comment by Lyonidaspay** [comment]
I also found that one of the 6  M3 screw for coupling the stepper motor to the Z trapezoidal screw was a bit loose , after tightening it a no long have the missing steps, but Know it's a new problem ! ! !  !
At the top, when finishing the G-code the Z axis ( the bed) moves down as if it loses power ! ! 
It wasn't like that , I would hold it's position (Z axis) even when powering off the  Z stepper

**Comment by Dim3nsioneer** [comment]
@Lyonidaspay : Your problem sounds rather like a mechanical issue or an issue with the firmware than a software issue caused by Cura. Maybe some hardware- or firmware-related forum could help you finding the cause.

**Comment by Lyonidaspay** [comment]
Thanks ! But even if it's a mechanical issue, asking for a way to put the Z homing just after the first part seems to be a good way to solve any missing steps or any kind of problems when moving the bed up !

**Comment by Dim3nsioneer** [comment]
It wouldn't be a solution but just a work-around.

**Comment by JustAnother1** [comment]
Right now the user can provide a custom start and end g-code. So if  the user needs some special G-Codes at the begin or the end of a print she might also need some special G-Codes when printing two models in one go. So a custom restart.gcode is a valid feature request.

And yes in this situation it would allow a work around. That is not a bad thing.

**Comment by daid** [comment]
Sorry, if your Z axis is not running as it should, then you should fix that. I'm not adding something because your machine is not working properly.

**Comment by Lyonidaspay** [comment]
OK thanks ! and welcome back  Daid from your vacation
