### ISSUE TITLE
infill is solid

### ISSUE THREAD

**Issue by sage19175** [daid/LegacyCura#1018]
I'm about an hour into a large print and so far it has printed the whole this solid.....although i put 20% infill. I have in the settings 0.8mm top/bottom/sides thickness. so that's not the problem.
Is there a bug fix? I have Cura 14.09

**Comment by Lyonidaspay** [comment]
Try Cura 14.11.RC7 and check the path first  ! ! !

**Comment by daid** [comment]
Some more information would be helpful, as this never happens in normal operation. No bug is know that causes this.
