### ISSUE TITLE
Bug with proposed fix: On Windows 7 x64: Cura stops slicing after first slice, or does not slice a all after opening a file

### ISSUE THREAD

**Issue by daniel-blake** [daid/LegacyCura#1019]
**OS:** Windows 7 Ultimate X64
**Cura Versions:** 14.x

**Symptoms:**

On recent Cura versions (14.x), I repeatedly get the problem that Cura suddenly stopped slicing.
Often it slices once, and then slices no more. 
_(Below I explain what I found to be the source of problem I and propose a solution that worked for me)_

**On investigating the problem I found the following to be the source of the problem:**

Cura seems to look for CuraEngine.exe in the wrong place: To be precise, it looks for CuraEngine.exe in the directory where the last opened file is located. 
Occasionally it slices once (e.g. has the right path for the first slice), before it gets the wrong path for CuraEngine for the next slices.

In _sliceEngine.py_  / _getEngineFilename()_ the engine path is resolved by doing:
os.path.abspath(os.path.join(os.path.dirname(**file**),'../..','CuraEngine.exe')))
Unfortunately, **file** returns ar relative path: "Cura/util/sliceEngine.py", which is then effectively resolved to "<current working dir>\Cura\util....\CuraEngine.exe" by the rest of the code.
(Resolves effectively to <CWD>\CuraEngine.exe btw.)

The code works, because on the windows version, the current working directory (CWD) is Cura's main directory.
If somehow though, the CWD is changed, this code looks for CuraEngine.exe in that directory.
In my case, somehow after the "Open file" dialog closes, the CWD is changed to the directory of the opened file. Thus Cura looks for CuraEngine in the wrong place;

**My proposed solution:**
Use the inspect module to get the absolute path to the source of the main module. Base the location of CuraEngine on that.

In _Cura/util/sliceEngine.py:getEngineFilename()_, replace

```
if platform.system() == 'Windows':
    if version.isDevVersion() and os.path.exists('C:/Software/Cura_SteamEngine/_bin/Release/Cura_SteamEngine.exe'):
        return 'C:/Software/Cura_SteamEngine/_bin/Release/Cura_SteamEngine.exe'

    return os.path.abspath(os.path.join(os.path.dirname(__file__), '../..', 'CuraEngine.exe'))
```

by

```
if platform.system() == 'Windows':
    if version.isDevVersion() and os.path.exists('C:/Software/Cura_SteamEngine/_bin/Release/Cura_SteamEngine.exe'):
        return 'C:/Software/Cura_SteamEngine/_bin/Release/Cura_SteamEngine.exe'

    import inspect
    import __main__
    return os.path.abspath(os.path.join(inspect.getfile(__main__), '../..', 'CuraEngine.exe'))
```

While this does not address the source of the CWD changing (which may need further investigation), it effectively fixes the problem where CuraEngine.exe is not found IF the CWD changes.

//Edited because I posted instead of previewed earlier

**Comment by daid** [comment]
Mmm, odd, **file** seems to return the full path in my dev environement, but a relative path in the install environment. Good catch!
