### ISSUE TITLE
Cura with BFB 3D touch

### ISSUE THREAD

**Issue by Mario3D** [daid/LegacyCura#1021]
I try to use Cura on my 3D touch 
When i try to print the file the machine shows : Verify error File line :22
Do you know what it means and what I have to change

**Comment by daid** [comment]
Currently BFB Touch support is experimental. People are still figuring out how to get it to work reliably.

See:
http://umforum.ultimaker.com/index.php?/topic/3970-machine-settings-firmware-for-3d-touch/
