### ISSUE TITLE
Bug report: Cura support fails on angled overhang

### ISSUE THREAD

**Issue by dteal** [daid/LegacyCura#1022]
I'm generating support material in Cura for overhangs greater than 60 degrees using the default settings. I have a model with an overhang that juts out of the model; it immediately slopes up at 45 degrees on each side so that the bottom of the unsupported section is a horizontal 2D line. Support wasn't generated for this place for some reason.

Steps to reproduce:
1. Download the file at https://www.dropbox.com/s/xm1jczyef15eska/Ball%20Tube%20Part%20v2%20A.STL?dl=0.
2. Install Repetier-Host v1.0.6
3. Slice the STL file rotated 50 degrees about X, -1 degrees about Y, and 90 degrees about Z. Use support material and default settings.

I'm using the version of CuraEngine that ships with Repetier-Host v1.0.6.

**Comment by daid** [comment]
Because 45degree is less then 60?

And this is Cura's issue tracker, for issue with the Cura GUI. Better report Repetier issues to RepetierHost.

**Comment by dteal** [comment]
I suppose I should have clarified that it's a 90 degree overhang that slopes up... kind of like the top section of the St. Louis Arch.

I'll ask Repetier and see if it's a consistent error.
