### ISSUE TITLE
My model can't print as the first layer doesn't touch the bed. What can I do to make the print start lower?

### ISSUE THREAD

**Issue by a4jp-com** [daid/LegacyCura#1024]
My model can't print as the first layer doesn't touch the bed. What can I do to make the print start lower?

**Comment by Dim3nsioneer** [comment]
Adjust the end switch of your printer and perform a proper bed levelling. This has nothing to do with Cura except if you get empty layers in the layer preview.

**Comment by a4jp-com** [comment]
I did everything in Cura besides make the model so the problem is Cura related as far as I can see. I don't have the same problem in Slic3r, Printrun (Pronterface) or Kisslicer, just Cura.
