### ISSUE TITLE
Support Structures do not Print

### ISSUE THREAD

**Issue by badamec** [daid/LegacyCura#1026]
I am using CURA latest version on  a Printrbot Simple Metal. I have a STL file that needs support on small extensions.  When I look at the layer view on Cura it shows the support structures but when actual printing starts the skirts prints like it would be for supports but the supports never print.
Can you help?

**Comment by daid** [comment]
Cura has a tendency to remove tiny support structures. Currently the whole support generation code is being looked at, as there are many cases in which it won't work properly.

You could see if the XY support distance setting helps.
