### ISSUE TITLE
print problem help!

### ISSUE THREAD

**Issue by solemnyan** [daid/LegacyCura#1027]
Hi, Guys: 

I am new to 3-d printer, and I brought a makergear M2 . I am using cura-14.09 as my firmwares.
When i tried to printer and I got this. It stopped 
any ideas on how to work this out. 

![qq 20141130120229](https://cloud.githubusercontent.com/assets/10010999/5238456/fbb61862-786f-11e4-83b1-0a1fea7d1d1b.jpg)

Thanks a lot

**Comment by a4jp-com** [comment]
File > Preferences > Printing Window Type \* Pronterface UI

This might be better.

**Comment by daid** [comment]
Cura is not firmware. Firmware is what runs on your machine.

Cura tells you there that it connected to the machine and it's ready for printing input. Pressing print should start the print.

**Comment by a4jp-com** [comment]
Maybe the file you loaded was buggy.
