### ISSUE TITLE
Empty first layers generated for objects with pointy "legs"

### ISSUE THREAD

**Issue by vineoak** [daid/LegacyCura#1028]
I am not sure if it would be considered more a bug or a feature request. If I should also open a feature request with proposed solution just let me know. I was also not sure if I should report it here or under CuraEngine.

I am using `Cura 14.09` on `64-bit Windows 7` I can also reproduce it on a `64-bit Linux` installation.

I am using this `.stl` scaled 10 times in every dimension:
https://www.dropbox.com/s/q5vmoc4araonlx2/pointy_debug.stl?dl=1

First I try to generate layers with the default orientation the first toolpath moving to the beginning of the object is on layer 4:
https://www.dropbox.com/s/yoc5zmj12dnusx6/pointy_debug_orig_orientation.gcode?dl=1

If I use the "Lay flat" option then the first path is on layer 3:
https://www.dropbox.com/s/q5vmoc4araonlx2/pointy_debug.stl?dl=1

I have also tried to print it on `Ultimaker 2 (firm:14.09)`. And It does dispense filament for a few seconds before moving in place and starting to print just a bit too high for adhesion.
If I set `Cut off object bottom` under Advanced settings to at least 0.2mm then the toolpath is generated starting from the first layer and the print is also successful. If I set it to 0.1mm it will start the toolpath one layer closer to the glass but will not add the brim or skirt

If this is considered to be expected behaviour in Cura then fair enough - I'll just start a feature request to warn the user if first layers are empty.

**Comment by daid** [comment]
Currently this is expected behaviour from Cura. However, at some point in the future I want to auto detect this case and solve it automatically, so that the user has less to worry about.
