### ISSUE TITLE
OS X: cura still giving errors while launching

### ISSUE THREAD

**Issue by jgeerds-zz** [daid/LegacyCura#103]
I have made some progress, the key was to remove python 2.7 from my system (see http://stackoverflow.com/questions/3819449/how-to-uninstall-python-2-7-on-a-mac-os-x-10-6-4 - restart after uninstall) in order to move on. if you are trying to run cura/pronterface, do not install python 2.7 (10.6.x, IMO)

while pronterface starts up without any glitch, cura is still throwing some errors:

joe$ /Users/joe/Desktop/osx64-Cura-RC3/cura.sh ; exit;Traceback (most recent call last):
  File "/Users/joe/Desktop/osx64-Cura-RC3/Cura/cura.py", line 70, in <module>
    main()
  File "/Users/joe/Desktop/osx64-Cura-RC3/Cura/cura.py", line 67, in main
    mainWindow.main()
  File "/Users/joe/Downloads/osx64-Cura-RC3/Cura/gui/mainWindow.py", line 28, in main
  File "/Users/joe/Downloads/osx64-Cura-RC3/Cura/gui/simpleMode.py", line 21, in **init**
  File "/Users/joe/Downloads/osx64-Cura-RC3/Cura/gui/configBase.py", line 22, in **init**
  File "//usr/local/lib/wxPython-unicode-2.8.12.1/lib/python2.6/site-packages/wx-2.8-mac-unicode/wx/_windows.py", line 1750, in __init__
    _windows_.PopupWindow_swiginit(self,_windows_.new_PopupWindow(_args, *_kwargs))
NotImplementedError
logout

Note: first run with wizard works fine, the errors appear after the wizard has run, or did run previously.

**Comment by jgeerds-zz** [comment]
the solution was installing wxpython 2.9 (2.8 doesn't work with cura, maybe the readme should reflect that): http://sourceforge.net/projects/wxpython/files/wxPython/ while making sure to install the right wxpython (for the right python install 2.6 vs 2.7)

**Comment by jgeerds-zz** [comment]
it is also important to run python/cura as 32bit by setting the system default in terminal to
defaults write com.apple.versioner.python Prefer-32-Bit -bool yes

**Comment by jgeerds-zz** [comment]
I was wrong: wxpython2.9 crashes python really really badly, to the point that the system needs to be restarted:

Process:         Python [1015]
Path:            /System/Library/Frameworks/Python.framework/Versions/2.6/Resources/Python.app/Contents/MacOS/Python
Identifier:      org.python.python.app
Version:         2.6 (2.6)
Build Info:      python-440200~2
Code Type:       X86 (Native)
Parent Process:  bash [1010]

PlugIn Path:       /usr/local/lib/wxPython-2.9.3.1/lib/libwx_osx_carbonu-2.9.3.0.0.dylib
PlugIn Identifier: libwx_osx_carbonu-2.9.3.0.0.dylib
PlugIn Version:    ??? (???)

Date/Time:       2012-05-12 21:22:58.936 -0400
OS Version:      Mac OS X 10.6.8 (10K549)
Report Version:  6

Interval Since Last Report:          161617 sec
Crashes Since Last Report:           5
Per-App Interval Since Last Report:  7322 sec
Per-App Crashes Since Last Report:   4
Anonymous UUID:                      9723580D-ED06-4853-AED7-0D7074C734C7

Exception Type:  EXC_BAD_ACCESS (SIGBUS)
Exception Codes: KERN_PROTECTION_FAILURE at 0x0000000000000008
Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Thread 0 Crashed:  Dispatch queue: com.apple.main-thread
0   ...osx_carbonu-2.9.3.0.0.dylib  0x01aadf9d wxRegion::GetWXHRGN() const + 9
1   ...osx_carbonu-2.9.3.0.0.dylib  0x01b18a4a wxMacWindowClipper::wxMacWindowClipper(wxWindow const*) + 182
2   ...osx_carbonu-2.9.3.0.0.dylib  0x01b1a399 wxMacMLTEControl::SetSelection(long, long) + 35
3   ...osx_carbonu-2.9.3.0.0.dylib  0x022ad205 wxTextEntryBase::SelectAll() + 33
4   ...osx_carbonu-2.9.3.0.0.dylib  0x01c4c160 wxTextEntryBase::DoSetValue(wxString const&, int) + 52
5   ...osx_carbonu-2.9.3.0.0.dylib  0x022ad305 wxTextCtrlBase::SetValue(wxString const&) + 45
6   _core_.so                       0x0110d346 _wrap_TextEntryBase_SetValue + 206 (_core_wrap.cpp:55285)
7   org.python.python               0x0000c6e0 PyObject_Call + 101
8   org.python.python               0x0008c843 PyEval_EvalFrameEx + 21688
9   org.python.python               0x0008cf74 PyEval_EvalCodeEx + 1720
10  org.python.python               0x0008b5a1 PyEval_EvalFrameEx + 16918
11  org.python.python               0x0008cf74 PyEval_EvalCodeEx + 1720
12  org.python.python               0x0008b5a1 PyEval_EvalFrameEx + 16918
13  org.python.python               0x0008cf74 PyEval_EvalCodeEx + 1720
14  org.python.python               0x0008b5a1 PyEval_EvalFrameEx + 16918
15  org.python.python               0x0008cf74 PyEval_EvalCodeEx + 1720
16  org.python.python               0x0002ee0c PyClassMethod_New + 1823
17  org.python.python               0x0000c6e0 PyObject_Call + 101
18  org.python.python               0x0001c10d PyClass_New + 1603
19  org.python.python               0x0000c6e0 PyObject_Call + 101
20  org.python.python               0x00053d8a _PyType_Lookup + 5617
21  org.python.python               0x00055bc1 PyType_GenericAlloc + 3133
22  org.python.python               0x0000c6e0 PyObject_Call + 101
23  org.python.python               0x0008c812 PyEval_EvalFrameEx + 21639
24  org.python.python               0x0008cf74 PyEval_EvalCodeEx + 1720
25  org.python.python               0x0008b5a1 PyEval_EvalFrameEx + 16918
26  org.python.python               0x0008cf74 PyEval_EvalCodeEx + 1720
27  org.python.python               0x0008b5a1 PyEval_EvalFrameEx + 16918
28  org.python.python               0x0008cf74 PyEval_EvalCodeEx + 1720
29  org.python.python               0x0008d019 PyEval_EvalCode + 87
30  org.python.python               0x000a40af Py_CompileString + 111
31  org.python.python               0x000a415b PyRun_FileExFlags + 139
32  org.python.python               0x000a5e7e PyRun_SimpleFileExFlags + 814
33  org.python.python               0x000b315c Py_Main + 3074
34  org.python.python.app           0x00001eb5 start + 53

Thread 1:  Dispatch queue: com.apple.libdispatch-manager
0   libSystem.B.dylib               0x92b0f382 kevent + 10
1   libSystem.B.dylib               0x92b0fa9c _dispatch_mgr_invoke + 215
2   libSystem.B.dylib               0x92b0ef59 _dispatch_queue_invoke + 163
3   libSystem.B.dylib               0x92b0ecfe _dispatch_worker_thread2 + 240
4   libSystem.B.dylib               0x92b0e781 _pthread_wqthread + 390
5   libSystem.B.dylib               0x92b0e5c6 start_wqthread + 30

Thread 2:
0   libSystem.B.dylib               0x92b0e412 __workq_kernreturn + 10
1   libSystem.B.dylib               0x92b0e9a8 _pthread_wqthread + 941
2   libSystem.B.dylib               0x92b0e5c6 start_wqthread + 30

Thread 0 crashed with X86 Thread State (32-bit):
  eax: 0x00000000  ebx: 0x0110d286  ecx: 0x3876c910  edx: 0x00000000
  edi: 0xbfffd540  esi: 0x00919bfc  ebp: 0xbfffd4e8  esp: 0xbfffd4e8
   ss: 0x0000001f  efl: 0x00010282  eip: 0x01aadf9d   cs: 0x00000017
   ds: 0x0000001f   es: 0x0000001f   fs: 0x00000000   gs: 0x00000037
  cr2: 0x00000008

Binary Images:
    0x1000 -     0x1ff7  org.python.python.app 2.6 (2.6) <C77A9CF4-EE78-E858-EEF0-1C61E883DE39> /System/Library/Frameworks/Python.framework/Versions/2.6/Resources/Python.app/Contents/MacOS/Python
    0x5000 -    0xecfef  org.python.python 2.6.1 (2.6.1) <4FFD855C-1C5A-9206-A695-8C9904F1DA84> /System/Library/Frameworks/Python.framework/Versions/2.6/Python
  0x1f3000 -   0x1f5ff7  strop.so ??? (???) <D9F1E094-2CD0-0F74-89E9-6CC5490E9B91> /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload/strop.so
  0x1fa000 -   0x1faff7  _functools.so ??? (???) <F549CBD2-71D3-6F04-2116-1619752BA8AF> /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload/_functools.so
  0x480000 -   0x481ff7  _locale.so ??? (???) <E8A1359D-6929-DC03-B1CA-0A4E82AAFBA3> /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload/_locale.so
  0x485000 -   0x488ff7  operator.so ??? (???) <39BB4268-6378-7DE3-1464-F390708765ED> /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload/operator.so
  0x48d000 -   0x490ff7  _struct.so ??? (???) <7C65AA62-D975-3CEB-E813-F08C0EBB6749> /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload/_struct.so
  0x496000 -   0x498ff7  math.so ??? (???) <7B9D1E0E-E56B-E084-4523-D129F14516DC> /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload/math.so
  0x49d000 -   0x49fff7  zlib.so ??? (???) <593D2E76-57D7-F83E-CE04-1E39089DB56B> /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload/zlib.so
  0x4a3000 -   0x4a5fe7  binascii.so ??? (???) <3901C6C2-7927-23FC-AC5F-A6C78D60D454> /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload/binascii.so
  0x4a9000 -   0x4aaff7  time.so ??? (???) <A59E724C-6992-4320-B7D5-5474E1644952> /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload/time.so
  0x4b0000 -   0x4b2ff7  select.so ??? (???) <FFCE08C5-E232-877F-BF81-A74C81F758EF> /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload/select.so
  0x4b7000 -   0x4b8ff7  fcntl.so ??? (???) <29EB5E4D-502A-146B-AA3E-95DC012460AA> /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload/fcntl.so
  0x4fc000 -   0x4fdff7  cStringIO.so ??? (???) <93601259-55EC-FFCA-7DB8-FE5B85FBB2FE> /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload/cStringIO.so
  0x5a1000 -   0x5a2ff7  _random.so ??? (???) <47591645-2129-E65B-D55C-FB84F5790BEA> /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload/_random.so
  0x7c4000 -   0x7c6ff7  _collections.so ??? (???) <6EECAE26-D3C6-12CB-CE10-10F3DF43B756> /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload/_collections.so
  0x7cb000 -   0x7ccff7  icglue.so ??? (???) <D4FE84FC-AE89-34DC-4F78-E3A94DA324E3> /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload/icglue.so
  0x7d0000 -   0x7d3ff7  _Res.so ??? (???) <ED9399A4-809D-6CF8-C863-EC5894BE2A8D> /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload/_Res.so
  0x7d9000 -   0x7e0ff7  _File.so ??? (???) <EED1D2DB-71FB-661B-B593-413B8F3F6CDC> /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload/_File.so
  0x7e6000 -   0x7e7ff7  MacOS.so ??? (???) <99B57975-0767-E132-C9AA-1A03B830F98A> /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload/MacOS.so
  0x7ed000 -   0x7f1ff7  itertools.so ??? (???) <06ECFB9D-010B-7422-BE26-E19AC7A08F86> /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload/itertools.so
  0x7f8000 -   0x7fbff7  _dotblas.so ??? (???) <22EE39DF-8ADE-E3D4-513B-56DEF5C67445> /System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/numpy/core/_dotblas.so
 0x1000000 -  0x118afff +_core_.so ??? (???) /usr/local/lib/wxPython-2.9.3.1/lib/python2.6/site-packages/wx-2.9.3-osx_carbon/wx/_core_.so
 0x1842000 -  0x255e5ab +libwx_osx_carbonu-2.9.3.0.0.dylib ??? (???) /usr/local/lib/wxPython-2.9.3.1/lib/libwx_osx_carbonu-2.9.3.0.0.dylib
 0x2dc2000 -  0x2dce03f +libwx_osx_carbonu_gl-2.9.3.0.0.dylib ??? (???) /usr/local/lib/wxPython-2.9.3.1/lib/libwx_osx_carbonu_gl-2.9.3.0.0.dylib
 0x2ddf000 -  0x2deeff7  _ctypes.so ??? (???) <4590A4CC-FCA4-CE52-BD79-AD9418F917AD> /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload/_ctypes.so
 0x2df7000 -  0x2df9ff7  _compiled_base.so ??? (???) <9B71A0D7-8CE1-34CA-CF23-39AFE76DA804> /System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/numpy/lib/_compiled_base.so
 0x3900000 -  0x39f8fff +_windows_.so ??? (???) /usr/local/lib/wxPython-2.9.3.1/lib/python2.6/site-packages/wx-2.9.3-osx_carbon/wx/_windows_.so
 0x3fd6000 -  0x3fe2ff7  _sort.so ??? (???) <668A5C9F-8010-6116-D61D-C6681D82095B> /System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/numpy/core/_sort.so
 0x3fe6000 -  0x3ff1ff7  cPickle.so ??? (???) <ACB4C31D-67E4-8EAE-17F7-13C7393E8674> /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload/cPickle.so
 0x3ff7000 -  0x3ffaff7  lapack_lite.so ??? (???) <6B0A9764-9AE7-7663-EB28-A0526E4AE2AF> /System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/numpy/linalg/lapack_lite.so
 0x4840000 -  0x488bfe7  multiarray.so ??? (???) <50C2A00A-3580-6447-7996-D2D14F193B24> /System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/numpy/core/multiarray.so
 0x4899000 -  0x48c2ff7  umath.so ??? (???) <CA03C867-A230-6A4B-0780-5782457925E1> /System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/numpy/core/umath.so
 0x48cc000 -  0x48e2ff7  scalarmath.so ??? (???) <3E96A1D4-767B-288E-F2BC-7EE061980362> /System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/numpy/core/scalarmath.so
 0x48e6000 -  0x48efff7  fftpack_lite.so ??? (???) <04E48656-49F3-BD1C-BCE7-A6F30B07F063> /System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/numpy/fft/fftpack_lite.so
 0x48f3000 -  0x48f3ff7  _weakref.so ??? (???) <5CC08935-408D-F049-9010-801E98FA611A> /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload/_weakref.so
 0x48f7000 -  0x48f8ff7  termios.so ??? (???) <1432983B-8BB9-FF35-940E-9CA9B0228D1E> /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload/termios.so
 0x4a00000 -  0x4b06ff7 +_gdi_.so ??? (???) /usr/local/lib/wxPython-2.9.3.1/lib/python2.6/site-packages/wx-2.9.3-osx_carbon/wx/_gdi_.so
 0x5102000 -  0x525bff7 +_controls_.so ??? (???) /usr/local/lib/wxPython-2.9.3.1/lib/python2.6/site-packages/wx-2.9.3-osx_carbon/wx/_controls_.so
 0x57df000 -  0x58ecff7 +_misc_.so ??? (???) /usr/local/lib/wxPython-2.9.3.1/lib/python2.6/site-packages/wx-2.9.3-osx_carbon/wx/_misc_.so
 0x5de8000 -  0x5de9ff7  _fileio.so ??? (???) <50F9A8CD-659D-FBC6-E71B-FFDAEE7AFB78> /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload/_fileio.so
 0x5dee000 -  0x5defff7  _bytesio.so ??? (???) <90A72E61-894D-3853-B584-2618A17BE910> /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload/_bytesio.so
 0x5f00000 -  0x5f25fe7  mtrand.so ??? (???) <D3C90661-48DE-01D9-45DC-77F0998FB37F> /System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/numpy/random/mtrand.so
 0x6a80000 -  0x6a8cfff +_glcanvas.so ??? (???) /usr/local/lib/wxPython-2.9.3.1/lib/python2.6/site-packages/wx-2.9.3-osx_carbon/wx/_glcanvas.so
 0x6dbc000 -  0x6e74fff +_stc.so ??? (???) /usr/local/lib/wxPython-2.9.3.1/lib/python2.6/site-packages/wx-2.9.3-osx_carbon/wx/_stc.so
 0x71a4000 -  0x71befff +_wizard.so ??? (???) /usr/local/lib/wxPython-2.9.3.1/lib/python2.6/site-packages/wx-2.9.3-osx_carbon/wx/_wizard.so
0x3740e000 - 0x37432fe7  GLRendererFloat ??? (???) <F19DDBE8-1DF6-6618-F554-0E81ED85CE67> /System/Library/Frameworks/OpenGL.framework/Resources/GLRendererFloat.bundle/GLRendererFloat

**Comment by fuegas** [comment]
Two questions:
1. Which version of OSX do you run? (Snow Leopard, Lion?, 32bit, 64bit?)
2. Which version of python do you have installed (or more than one?)

**Comment by jgeerds-zz** [comment]
I run 10.6.8, python 2.6(.1), and wxpython 2.9.3.1 (see my other crash report further up), and uninstalled all other python versions.
