### ISSUE TITLE
Not printing support structure

### ISSUE THREAD

**Issue by CapnPatch** [daid/LegacyCura#1031]
Support (Lines) is visible on screen (using a Brim and asking for Support Everywhere) but no support is being printed, although the Brim is printed around where it would be laid down.  Have I got one of the settings wrong?

**Comment by BagelOrb** [comment]
It seems you have been printing a different file than the one shown on screen. Can you either confirm or deny that?

**Comment by CapnPatch** [comment]
Tim,this looks like an old enquiry.  I don't have any outstanding Cura
queries.

Tim Grollman
