### ISSUE TITLE
"Unknown error" occurs when slicing landscape model in full size

### ISSUE THREAD

**Issue by wittchenstein** [daid/LegacyCura#1035]
When preparing [this landscape](http://www.thingiverse.com/thing:27265) for printing, an error occurs with the below slice engine log. Has anyone stumbled upon this / a similar Problem and got a solution to it? 

---

Running: C:\Program Files\Cura_14.09\CuraEngine.exe -v -p -s initialSpeedupLayers=4 -s minimalFeedrate=10 -s preSwitchExtruderCode= -s supportXYDistance=700 -s insetXSpeed=25 -s retractionZHop=0 -s extruderOffset[3].X=0 -s extruderOffset[3].Y=0 -s gcodeFlavor=1 -s postSwitchExtruderCode= -s retractionSpeed=40 -s filamentFlow=100 -s infillOverlap=18 -s inset0Speed=15 -s coolHeadLift=0 -s extrusionWidth=600 -s upSkinCount=10000 -s initialLayerSpeed=10 -s minimalLayerTime=5 -s infillSpeed=42 -s supportExtruder=-1 -s fanSpeedMax=100 -s enableCombing=1 -s fanSpeedMin=100 -s supportZDistance=150 -s supportEverywhere=1 -s filamentDiameter=2850 -s initialLayerThickness=100 -s supportAngle=60 -s fanFullOnLayerNr=6 -s extruderOffset[1].X=18000 -s extruderOffset[1].Y=0 -s layerThickness=100 -s endCode=M25 ;Stop reading from this point on.
;CURA_PROFILE_STRING:eNrtWk1v20YQvRJGf8QeEzRWSUqKnQi8JLV9aYoAdtHEF2JFrsStSS6xu7QsG/rvfbtc0pQtt05jNF/UwQaHM7szb958GFZO10zGGePLTEf+KPBWNM9jnfHkomRKQfTSk0xLmmguypiVdJ6z6EzWzFMi52mc2wO2DRYcZ6SsVFyvo8D3vVJcX+csVvyaQWHiVZKXOlYVY2kUTt2jZkXFJNW1ZFEY+velYbRDON4lnHTCOUu3Dj7wPVVXlZA6Orpkcr3KmGRelVO9ELKIaZoxhUCj30XJWs04rWkesysta/vujdCZt+IVi7VYMRkd01yxniC+FHldsCiYekJcI+yMszx1asCGFgyepRy/NczD0eH0vtgEe0843iWc9IWLXKwM5CO/n7YG6ckdKS1EXepoMpr2pTZY9yp4uf2u4GWMh0uWR8H2m0QUc14uG2ZsW/BiCz04EfY1MlEZmTcXWotii0mBZ9nlxyue6ixewEJISygx/4slYBAvLxC9QCZzWlnXjdnUa5x0cQfT3vkNX90L3+OlJasDKMSzYtrvDJvnq1uqJkLkFgbHe448I3u0LY3U1cYFB29yXjIgY5AcO9GSVtEY3jRPLTo5K5c6c46awxY1nOqq8sDKWp/926e4oFdW0rm1gBRUZyY2K8wYRZHyhXb8a6pWA/ReETfYNBKLh0M0Cg67ItDrikUnkqedhJZL9IKXXUXF1tTefjDthFdrMFVpWibMhtLKr/tiIK0qLmluOoRzlBcVekYh0lYyl7zoY4oeIekCKFK55GU0Hblnq6IqmhhCjlvpnCq2xa5xT25MLMnAa6eP7sEkKLdtFB7cfXtrajqbfUm5NHmGdtgIVO10DWlUFALkKxBfSg7KxHVpq9H0XWAc0zYPD6vMu2bS10EcomJlPOda7VJADZqefAlwNNdJZuBp1Kq8BoKAFdWwjNrqSpgJMr6K9oM7ojVEPyF5Uo+WiUnQ7DTnCUsJ1a/JTUrXG/NTM/wyFbLZm72hiicEtaRxq3pNfjNIkIbhMMl7Y2hD/kSg0LnZnkUbcgx+QdwfLzj6vWn0xNyDd24UNJceu65IAE3aGDZdsmlvm6InWjV3L3tWiVC6b2Weceq74JVPTm92zpcNmf1Rohdaey0ITVOyFrUkYlUS6JKeLjHMMcf5r7rjHnvUvWNOwoC4zwxTQQLsS5rXTO2dwNv2DZ2j3mvNSCUAHiiFZOy9Oww7BSSI2FadIjvm0tbAlOEeXD3oNE32yYrrjOiMEbQkIhYL+HFIPvjko2/8QBchH375aA5CbyKsTBUaj7JK575z1iid31cJyHmAiibHN/1evnEG5sp2aJPUIBJMiwKxhuSoC/f2M7tmUlgjF1xKmpZr7jkOfZ8cje9YOEUyLgoERkxfJXAtufj0SwhdUl7aq7aDAXdrTWzmkQhSgOR0yYgoyW9vfyUqkYyVAD04IO+dzmg08oBRW3VHZUpO3rrUTMjpDq96sZh6Q1FKm6h3wcR/0MDqpZawtybkGV8YBpIMIRCunwOJgDziM5MMqULf2aId4DjaByRj3/8XY7sqNCxrS5MSNDn4h/ybAlhY/IxGs2m+MHzCrQy9nShRMJNCyxkJjFE0ll8/+6MpfJiSD/shKGt+7GbbOakrdyUF4q1HnTfskpWoEHPsLf3/MaiHSuMFvLWOmrFNuCICBHG+r+gatTp5+FClWYWuoJpCfPWwD7v7wAw9SCAmMx5At+XGszUeDi3+CVr85PNbfDMpzoJdJ4X/6Sj/y86dr32anD3Q3WanK7M+mVuMZYiW0HbYz5lAgb97AgX+k44ge9f+ze6/+DZ7Z/6jgl5wqfS3FPYTTd7wgdF75n/i9DU2wTCxh4n99BN7PEzsYWL/mBM7/BEn9rCmDGvKnTVl/CXXFGMTDqvNsNo8/WozGVabr2q1CZ9utRm2pP9tSxo/anZO4PR3tDA8bjUcf19BD6vhsBreWQ0n39pqaGzGwzo5rJNPu066r6H0v8XQCW//xdp8iWZLyUp6GpJhxiZslKjLyEMSmjZz5HjZLaxN85kzvUJl2qCTWkoLcUthkwCbaEg66QuyymDQVbpdJoo617zKu3Yh1WhvdpYBVHObARfrjWW5ZZE59OxZ+dwDJvpr8o8uTAG27v0NCie8Yw==
 -s minimalExtrusionBeforeRetraction=20 -s retractionMinimalDistance=1500 -s skirtMinLength=150000 -s objectSink=0 -s retractionAmount=4500 -s skirtLineCount=3 -s startCode= -s skirtDistance=3000 -s extruderOffset[2].Y=0 -s extruderOffset[2].X=0 -s printSpeed=25 -s fixHorrible=1 -s layer0extrusionWidth=600 -s moveSpeed=150 -s supportLineDistance=800 -s retractionAmountExtruderSwitch=16500 -s sparseInfillLineDistance=600 -s insetCount=1 -s downSkinCount=10000 -s multiVolumeOverlap=150 -g 49674 -m 1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0 -s posx=115000 -s posy=112500 $
Cura_SteamEngine version 14.09
Copyright (C) 2014 David Braam

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see http://www.gnu.org/licenses/.
Default config 'default.cfg' not used
Reading mesh from socket with 1192731 vertexes
Loaded from disk in 1.232s
Analyzing and optimizing model...
Face counts: 397577 -> 397577 100.0%
Vertex counts: 1192731 -> 198800 16.7%
Size: 200.028000 129.701000 11.312000
vMin: 14.986000 47.650000 0.000000
vMax: 215.014000 177.351000 11.312000
vMin: 0.000000 0.000000 -11.312000
vMax: 200.028000 129.701000 0.000000
Matrix: 1.000000 0.000000 0.000000
Matrix: 0.000000 1.000000 0.000000
Matrix: 0.000000 0.000000 1.000000
Optimize model 1.030s
Slicing model...
Layer count: 113

**Comment by daid** [comment]
I'll look into it. This is a bug in the engine, most likely in clipperlib.

**Comment by daid** [comment]
Found the problem. It's actually a out of memory error. Because some memory was not freed.

(Tech details. I assumed that std::vector<>.clear() freed the memory. However, it does not. So I need to be sure to actually destroy certain vectors so it no longer keeps loads of useless memory)

**Comment by daid** [comment]
Also, it happens specifically on this model because the normals of this model are flipped for every other triangle.

**Comment by daid** [comment]
Fixed in https://github.com/Ultimaker/CuraEngine/commit/edf2f897d10b3a6af889c0d3e81f6d15ff659981
