### ISSUE TITLE
simulate E-movement / prevent filament grinding

### ISSUE THREAD

**Issue by m-vo** [daid/LegacyCura#1036]
I'd love to be able to control the retraction settings in a way I can be (relativley) sure no grinding of the filament in the feeder occurs. The parameter that is critical for that is how often a certain small section of filament is moved forward and backward. 

I think it would be easy to analyze the filament movement from the generated gcode and give a quality feedback about possible grinding - a number that represents the amount of movement in a observing window when iterating the instructions or something. Even better if the Cura settings would then allow to tune for a critical upper bound, where the slicer puts in other solutions.

This would help printing objects where retraction is really useful/needed, but critical (due to small walls etc.). Unfortunately the result depends on how the slicing works (of course) and there is too few feedback if it would work.

**Comment by BagelOrb** [comment]
This seems like a viable solution (or at least a last resort fall back method).

I think the firmware is the correct place to implement such a feature. However, retractions themselves are also hardcoded into the gcode, instead of sending an abstract RETRACT gcode command...

**Comment by m-vo** [comment]
For an implementation in the firmware there should perhaps be a parameter like: "This is the maximum value for zig-zag-motion". Plus a strategy what to do when the maximum is reached (e.g. don't retract for the next some filament mm).

for  an 'in firmware'-implementation: 
(+) The actual flow and filament settings (that can even change during print) allow for a more precise measurement of the filament that gets moved through the feeder. Changing the filament during print can reset the current observer window.... and so on.
(-) I wonder if picking the right strategy when reaching the limit is crucial for a good result. If so there would be the need for further options -> complexity. Also prints would be less reproducible? 

I think if there would be a dimensionless value that can say something about the "how much for- and backward motion in a certain part of the filament" it would be enough to tune the retraction settings (only simulate...). Cura already makes assumptions about the length of the filament that will get used without knowing the presets in the printer. I think this granularity would be sufficient.

**Comment by BagelOrb** [comment]
@daid: where would you like to see this implemented? In the engine or in the firmware?

**Comment by BagelOrb** [comment]
A simple way to implement this in the engine: limit the retractions per extruded amount...
- Have two settings: retractionCountMax and extrusionAmountMin
- Implementation: keep track of the extrusion amount between each two consecutive retractions, and on requesting a retraction, check whether the last [retractionCountMax] extrusion amounts add up to more than extrusionAmountMin

**Comment by m-vo** [comment]
I think this will work as expected if the retraction length is quite short, but Ì feel otherwise the length must be somehow taken in account.

Grinding occurs if a certain piece of filament passes by the little 'feeder gear' for e.g. n = 5 times. If that number is reached retracts shouldn't be allowed until the filament has moved further. I would therefore do it like this:
- in the first instance assume the retraction length is fixed throughout the print
- have an observer window with the same 'length' of the retraction length
- may be implement it like this: have `n` slots, each time a retraction is requested do the following:
  - _prune the list for old entries (= remove entries that are no longer in the observer window)_
  - _if all `n` slots are full, reject request_
  - _else: add the current 'filament position' (absolute or relative) to an empty slot_  (with a queue data structure this removal at one side / adding at the other should be pretty lightweight)

![retract](https://cloud.githubusercontent.com/assets/5305677/7270844/60a4ea98-e8df-11e4-8d06-b78396c09073.png)
I quickly illustrated it: The black lines are the normal movement into the nozzle (going from left to right), the orange lines show the retractions - I stretched them out to be better visible. The blue dots show the current position of the observer window (I drew 3 example positions) where there might be the question: "Is another retraction allowed in this segment?". So if one look at the window there could be an easy way to determine if that part of filament can be stressed further. Clear what I mean?

**Comment by BagelOrb** [comment]
I think what you are saying comes down to the same thing, thanks for clarifying!

Difference is that I allow for the window to be of a different size (extrusionAmountMin) than the retraction length. Perhaps it isn't neccesary to have this extra setting.

There are two ways of implementing the window: keep track of the extruded amount between the past X retractions, or keep track of the number of retractions in the past X extruded amount.
Since there are less retractions than extruded segments, I think the first option is better.

**Comment by m-vo** [comment]
Ah thanks, now I think I got your version. Sounds legit - let me think about it :-)
