### ISSUE TITLE
can't se project

### ISSUE THREAD

**Issue by NillerBoy** [daid/LegacyCura#1041]
I have made panteon on 3dTin but i can't get it in Cura. I get the same message everytime: Warning object scaled down. I've tried on 2 computers but it don't work. i have also scaled it down but it did not help. Do you know why.

**Comment by daid** [comment]
The "warning object scaled down" means that Cura detected a very large object and scaled it down. Could mean a lot of things, including a corrupt file.
So most likely a 3dTin problem, and not a Cura problem. And with the supplied information that's all I can do.

**Comment by NillerBoy** [comment]
how can i make it so it's not corrupt.
