### ISSUE TITLE
Bed leveling wizard doesn't work with my machine.

### ISSUE THREAD

**Issue by a4jp-com** [daid/LegacyCura#1044]
The front 2 corners are good but the back center point doesn't work with my machine. I need the back 2 corners. 4 points altogether. How do I select this option? Please help so I can get the bed level.

**Comment by daid** [comment]
The bed leveling wizard is designed for the Ultimaker. And thus depends on if you have the heated bed enabled or not. If you have no heated bed enabled it will do 4 point leveling. With a heated bed it will do 3 point leveling.

**Comment by a4jp-com** [comment]
Can you add a setting for 4 point leveling in the settings area? I put in a heated bed but still have the four screws.
