### ISSUE TITLE
Same starting point at wall printing

### ISSUE THREAD

**Issue by Arrow111** [daid/LegacyCura#1045]
Hi,
What shall I configure in Cura 14.12.1 to avoid polymer artifact at 1 point? Cura do not have option to check it and have ramdom start points at all perimeters.
![pic7](https://cloud.githubusercontent.com/assets/3636519/5464419/794a79d8-85a1-11e4-82cb-81bc94bc4c81.JPG)

**Comment by daid** [comment]
Cura does not have an option like this. But I see some under-extrusion, uneven extrusion in your print. And the buildup on the "Z seam" as it's usually called, it mostly caused by a too high printing temperature.

**Comment by Arrow111** [comment]
dear daid thx for answer.Are you going to create such option in next versions?

**Comment by a4jp-com** [comment]
That's good to know. I had a similar problem before. I'll reduce my temperature a little bit.

**Comment by Arrow111** [comment]
Dear a4jp-com, are you printing ABS? if yes, what temeperature did you set up to avoid this artifact on 100%?
Actually when I am printing at 200mm/sec then I need high T as 260-268C, otherwise groover gear can not push filament and I am forced to reduce up to the 248C & the printing speed to 100-160mm/sec.

**Comment by a4jp-com** [comment]
I'm using PLA and the PLA I have needs a bit of heat to melt properly but here are a few setting that I use:

1st layer: Extruder 215 + Bed 66
Other layers: Extruder 198 + Bed 72

Diameter: 1.75mm
Extrusion multiplier: 0.99

Test G-code:

Start:
G1 Z0
G21                           ; Set units to mm
M140 S[first_layer_bed_temperature]                 ; Heat bed to 67 - doesn't wait - M140 S67 - great big - 0.2 0.4
G28                           ; Home all axes - move to origin X Y
M104 S[first_layer_temperature]               ; Set hotend temperature (nozzle) - M104 S[first_layer_temperature] - m104 doesnt wait - M104 S210 - great big - 0.2 0.4
M109 S[first_layer_temperature]               ; Wait for nozel temperature to be reached - m109 waits - M109 S210 - great big - 0.2 0.4
                                  ; M190 S67 ; Set bed temp to S67 and wait for bed temp to be reached - m190 waits
G1 Z6
G1 Y0 X80                ; Move away from the anchor was F3000
G1 Z6 F10                 ; Move platform down 6mm -maybe f doesn't work---g1 z6 f2000
G90                           ; Set absolute coordinates
G92 E0
M82                          ; Use absolute distances for extrusion
M106 S220               ; Fans on at this speed (must have S (speed) value - 255 is max)   ;M116 ; Wait
G1 Z0.05 E8 F4000      ; Move platform to position 0mm - put nozzle - 3mm before ; G1 F5000 E15 ; Extrude anchor blob
G1 Z2                        ; Move platform down 2mm - was f1000
G1 Y22 X80 E0 F0     ; Move away from the anchor was F3000
G1 Z0.05 E8 F3000      ; Move platform down 0mm
G1 Z[first_layer_height] E21 F4000    ; Move platform to the first layer again

End:
M104 S0               ; turn off temperature
M140 S0              ; bed temp (fast)
G28 X0 Y0            ; home X axis - added y - M206 Z-0.1 Glen z-height
G1 Z15 F0 E0       ; Z10 Moves platform down 10mm
M84                     ; disable motors

**Comment by Arrow111** [comment]
Thank you dear a4jp-com, I will test it when I will switch to PLA.
Truly,
Rob

**Comment by a4jp-com** [comment]
I will get my printer back from the maker in about a week. I can help with settings then if that is okay.

**Comment by Arrow111** [comment]
Dear  a4jp-com , would you be so kind to support?
https://github.com/daid/Cura/issues/1046

**Comment by a4jp-com** [comment]
Hi Arrow111, as soon as I get my printer back and flash the firmware I can try and help. Hopefully on the 24th or 25th.
