### ISSUE TITLE
Missing option - Random start points at all perimeters

### ISSUE THREAD

**Issue by Arrow111** [daid/LegacyCura#1046]
Dear Daid,are you going to create such option in next versions?
Thank you in advance for reply!
Truly,
Robert

**Comment by RaD** [comment]
I would like to see that option in the following versions of Cura. I think it is great idea to have start point at any place of any perimeter.

**Comment by Arrow111** [comment]
Dear Daid,  any comment?

**Comment by Arrow111** [comment]
Thank you dear Daid. I have got your message, you are not going to make cura more powerfull. I am very sorry.
