### ISSUE TITLE
Cant run from source

### ISSUE THREAD

**Issue by ghost** [daid/LegacyCura#1047]
I have tried to install Cura from scratch, but when I run sudo ./pacakage debian_amd64 the script returns Permission denied (public key) error and am unable to grab the Cura Engine in order to build the project.

**Comment by daid** [comment]
See:
https://github.com/daid/Cura/pull/1033

Currently this is needed for my release procedure. Sorry.

**Comment by ghost** [comment]
Theres no way for me to run the script then?

**Comment by daid** [comment]
Yes, but you need to make a few adjustments as shown in that pull request.

**Comment by ghost** [comment]
I made those changes but its still saying I have permission errors? Im using the https://github.com/Ultimaker/CuraEngine.git
