### ISSUE TITLE
object is alwayes at center after slice

### ISSUE THREAD

**Issue by yakirmalka** [daid/LegacyCura#1050]
hello,
i am using reprap prusa i3.
Repetier host soft and CURA slicer.
i am placing object in some corner or any place other then center,
after the slice the object is at the center (in perview mode and when its print).
i did try other slicer its working good.
is ther any setting who set the final object placment?
10x alot.

**Comment by daid** [comment]
Version of Cura?

**Comment by yakirmalka** [comment]
Version 3

**Comment by daid** [comment]
Oh, wait, I see you're using repetier host. It's a repetier bug. Not a Cura bug.

**Comment by yakirmalka** [comment]
10x alot :)
