### ISSUE TITLE
Is this my notebook's problem or which driver should I install ?

### ISSUE THREAD

**Issue by z666789** [daid/LegacyCura#1051]
![2014-12-21_21-46-15](https://cloud.githubusercontent.com/assets/9808170/5518300/dd355212-895a-11e4-91f7-1ac3f2b76e55.png)

**Comment by a4jp-com** [comment]
What is the problem?

**Comment by daid** [comment]
Video card drivers are missing or very old.

**Comment by z666789** [comment]
I can't see anything when the model finish reading

my notebook's video card is nvdia gt750m

I have updated to the newest driver
