### ISSUE TITLE
Quickprint setting "Fast Low quality"

### ISSUE THREAD

**Issue by lollp** [daid/LegacyCura#1061]
Hello,
if i select the quickprint setting "Fast low quality" the extruder motor havn't enough power to push the filament constant in the nozzle some layers fail because this (tested on two UM2). I think you have to set the layer high higher (0.25mm) or the nozzle temp. higher. Were can i change the quick print settings?

**Comment by daid** [comment]
The latest beta's of Cura have improved quickprint settings which give better results on the UM2:
http://software.ultimaker.com/Cura_closed_beta/
