### ISSUE TITLE
Problems with the Languages

### ISSUE THREAD

**Issue by b4zz4** [daid/LegacyCura#1065]
It does not detect all the languages when compiling it, only leaves to choose 4 of the 11 Languages

**Comment by daid** [comment]
Active languages are listed in Cura/util/resources.py

Only languages that have been verified by multiple parties are enabled by default for inclusion in releases.

**Comment by b4zz4** [comment]
El 07/01/15 a las 10:59, daid escibió:

> Active languages are listed in Cura/util/resources.py
> 
> Only languages that have been verified by multiple parties are enabled
> by default for inclusion in releases.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/daid/Cura/issues/1065#issuecomment-69024711.

ok, I complete almost all the translation into Spanish #1066

## 

http://ba.zza.pl
