### ISSUE TITLE
no control dashboard when printing via USB

### ISSUE THREAD

**Issue by jrdw** [daid/LegacyCura#1074]
With the latest Cura (14.12.1) there is no dashboard when printing with USB other than a small window saying "print or "cancel and showing temps . No Manual Control dashboard, no temp.curve, What was'nt downlaoded ?  Printer is Velleman K8200. Worked nice with earlier Cura versions.

**Comment by makevoid** [comment]
Go into 

```
File > Preferences
```

in

```
Print Window - Printing window type
```

select:

```
Pronterface UI
```

**Comment by jrdw** [comment]
Francesco Canessa schreef op 8-1-2015 om 10:36:

> Go into
> 
> |File > Preferences
> |
> 
> in
> 
> |Print Window - Printing window type
> |
> 
> select:
> 
> |Pronterface UI
> |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/daid/Cura/issues/1074#issuecomment-69155987.
> 
> Yes, of course, stupid me to miss it; thanks !

## 

Joost de Wijn
Berg en Dalseweg 80
NL6522BP Nijmegen
