### ISSUE TITLE
Strange shadow patterns for largish model

### ISSUE THREAD

**Issue by hallzhallz** [daid/LegacyCura#1075]
When I load this model ( http://www.thingiverse.com/thing:39675/#files ) there is a large triangle shadow shooting off the bed. If I load a simple model and then this model also at the same time then the shadow disappears completely (but this might just be to do with the multi-object printing?).

Skirt and support are disable so I am not sure what is going on, their should not be any shadows so to speak.

![first_load](https://cloud.githubusercontent.com/assets/10440379/5652809/73cf2fbc-9708-11e4-9ccd-725710b31849.png)
![load_behind_simple_object_on_bed](https://cloud.githubusercontent.com/assets/10440379/5652814/7f5c5760-9708-11e4-86ea-d0f89f846a5a.png)

![object_now_looks_ok](https://cloud.githubusercontent.com/assets/10440379/5652815/82dac9e4-9708-11e4-8464-087e76d05d69.png)

**Comment by daid** [comment]
At which size did you scale this model? (EDIT: Never mind, still had the UM2go selected)

EDIT2:
I'm not seeing this same thing happening. Did you scale or rotate the model in any way?

**Comment by hallzhallz** [comment]
Hi Daid,

I did not scale or rotate the model in any way. It is just how it appears when you first load it. I am using windows 7 with v14.12.1 but you have probably determined that from the screenshots.

It does not effect the printing in any way so maybe it is something to do with my system/drivers.

I'll try updating them my drivers and report back.

Cheers, David.

**Comment by daid** [comment]
Could be a driver thing, or a combined Cura bug and driver thing. As I'm not seeing this bug on my laptop.

**Comment by hallzhallz** [comment]
I tried updated drivers but it did not resolve the problem.

I am not sure that I said in the original descirption that the shadow appears when you click/select the object.

Given that it just seems to be on my machine and doesn't affect printing I will close the issue.

Thanks for taking a look. Cheers.
