### ISSUE TITLE
15.01RC7: Multiple objects

### ISSUE THREAD

**Issue by Dim3nsioneer** [daid/LegacyCura#1080]
When I load multiple objects into Cura (tested with a 1cm cube which I multiplied once), all objects are sliced but only one is saved into gcode.

**Comment by daid** [comment]
With or without plugins?

**Comment by Dim3nsioneer** [comment]
Both... and it's the same with Cura 14.12.1 on a different machine.
Uhhh... I forgot to mention that it is in 'one at a time' mode! And switching from all-at-once to one-at-a-time mode does (still) not properly work while objects are loaded. I had to clear everything and to reload for getting the correct slice.

**Comment by daid** [comment]
I cannot seem to reproduce this, it always slices correctly for me, even if I load files and switch modes.

What OS are you running on again? (OSX is giving me strange issues from time to time)

**Comment by Dim3nsioneer** [comment]
Win 8.0 and win8.1
You want me to slice a specific situation?

Von Samsung Mobile gesendet

-------- Ursprüngliche Nachricht --------
Von: daid notifications@github.com 
Datum:12.01.2015  07:26  (GMT+01:00) 
An: daid/Cura Cura@noreply.github.com 
Cc: Dim3nsioneer dim3nsioneer@gmx.ch 
Betreff: Re: [Cura] 15.01RC7: Multiple objects (#1080) 

I cannot seem to reproduce this, it always slices correctly for me, even if I load files and switch modes.

What OS are you running on again? (OSX is giving me strange issues from time to time)

**Comment by daid** [comment]
Are your machine settings default?

When I load my "20x20x10 cube" twice, I get 2 objects in the GCode.

**Comment by Dim3nsioneer** [comment]
Yes, I quickly setup a new UM2 machine. Doesn't work.
And I realised something else. Cura doesn't see the SDCard when plugged in (and Windows immediately opened an Explorer window). I had that one once in 2013 I think. Then it was possible to get rid of it by reinstalling Cura. That trick didn't work this time. All Cura versions are affected (back to something like 14.01). Any idea what might cause such an issue? Something with Python?

**Comment by Dim3nsioneer** [comment]
And I went back in Windows System Restore as far as I still have the data (I cleared it recently unfortunately). No effect.

**Comment by colorstone** [comment]
look this 
![qq 20150116002225](https://cloud.githubusercontent.com/assets/5824123/5761320/ae9bd894-9d15-11e4-8a3b-7bb26fa4c07b.jpg)

**Comment by colorstone** [comment]
what's all this ??

**Comment by daid** [comment]
A finger, a print, a few blobs, and some shadows.

**Comment by Dim3nsioneer** [comment]
Couldn't have written it more precise. Though, still don't see the connection to the topic of this issue. Maybe a misplacing by @colorstone ?

**Comment by colorstone** [comment]
This problem occurs in the 2th Shell Move to StartPoint (out shell StartPoint)
a little pla point has be Overflow

**Comment by colorstone** [comment]
fill density 30%  print speed 30  temperature 200

**Comment by colorstone** [comment]
a testmodel 
![qq 20150117020224](https://cloud.githubusercontent.com/assets/5824123/5781382/32611464-9ded-11e4-8792-c6d82366eda9.jpg)
![qq 20150117020346](https://cloud.githubusercontent.com/assets/5824123/5781392/421e60b4-9ded-11e4-9f44-8a1d7e0f225e.jpg)

**Comment by Dim3nsioneer** [comment]
@colorstone : As you don't seem to understand Daid's cynism and my message: please open a new issue if you have something to report and don't put your stuff into someone else's report which is about something completely else. Thank you.

**Comment by colorstone** [comment]
oh~ sorry, I don't know...
how to open a new issue? @Dim3nsioneer 
i can't click the submit new issue button

**Comment by Dim3nsioneer** [comment]
https://github.com/daid/Cura/issues/new

**Comment by Dim3nsioneer** [comment]
@daid : I had a closer look at the issue. It looks as if the gcode is generated and also displayed in the layer view of Cura as 'one-at-a-time' (as selected) but saved as 'all-at-once'.
Does that make any sense to you?

**Comment by daid** [comment]
That would make no sense at all... as what is shown in the layer view comes out of the engine, while it's generating the layers...

**Comment by Dim3nsioneer** [comment]
Mistery solved. It was my fault. I didn't realize that the layer numbering starts from 0 for each object. I must have missed this change as some time ago Cura started from 0 and increased the layer number throughout the different objects.
