### ISSUE TITLE
Print one at a time not working only prints all at ones

### ISSUE THREAD

**Issue by RENZIN** [daid/LegacyCura#1081]
I'm trying to print one at a time but it doesnt work Only prints all at ones.  Can anybody help me?

**Comment by Dim3nsioneer** [comment]
Clear the platform, switch to print-one-at-a-time and reload the objects. It seems the setting is a bit buggy. But I guess, @daid will anyway have a look at the setting due to some other issue ( #1080 ).

**Comment by daid** [comment]
What kind of printer are you using? You might need to setup the head size and gantry height in the machine settings. They are required for "one at a time" mode, and are only set by default on the Ultimakers.

**Comment by RENZIN** [comment]
I'm using the Ultimaker 2 with default settings.  What are the settings I need for the ultimaker to make the print one at a time function work?

**Comment by daid** [comment]
The settings are filled in by default for the Ultimaker2.

But the objects (all of them) need to be lower then 50mm, or else Cura will print all-at-once, because the objects will hit the gantry otherwise.

**Comment by RENZIN** [comment]
GOOD!!!  I finally did lower mm and now is working.   Thank you
