### ISSUE TITLE
Cura - display issues when small object is loaded

### ISSUE THREAD

**Issue by mrtnjcl** [daid/LegacyCura#1083]
Cura goes crazy when i try to load extremely small object (cube of 0.4x0.4x0.2). Please see the attached screenshot. The screen flickers when i try to pan around.

OS X 10.10.2, Cura 14.12.1.

![screenshot 2015-01-13 11 37 14](https://cloud.githubusercontent.com/assets/1102746/5719431/cd0e5774-9b18-11e4-848f-923238a4fa0c.png)

the problematic STL is here:
[https://www.dropbox.com/s/33jo8hef741eftu/Untitleda.stl?dl=0]

**Comment by daid** [comment]
Extremely small objects are scaled up, as Cura thinks you loaded something that was saved in meters instead of mm. (Nothing that small can be printed anyhow)
