### ISSUE TITLE
Issue with finding "X{machine_center_x}" in gcode

### ISSUE THREAD

**Issue by jpl4** [daid/LegacyCura#109]
I'm not sure what is causing my issue but my print head is running to the back of my platform just before print starts, seemingly disregarding the Y endstop. I'm on RC3, installed the bundled Marlin fw and running in expert mode. How is Cura calculating "{machine_center_}" in the gcode? Preferences are set correctly with machine dimensions at 205x205 so I'm not sure where else to look. Endstops are all set correctly as well. Any Idea? Changed the gcode back to G1 X100 Y100 F3500 G1 Z0.0 F400 for now.

**Comment by daid** [comment]
The {} tags are filled with the corresponding settings. So {machine_center_x} is the X center from the advanced tab. No idea why it wouldn't work, unless you modified the tag name by incident.
