### ISSUE TITLE
Model has a few blobs

### ISSUE THREAD

**Issue by colorstone** [daid/LegacyCura#1092]
This problem occurs in the 2th Shell Move to StartPoint (out shell StartPoint)
a little pla point has be Overflow
fill density 30% print speed 30 temperature 200

![qq 20150116002225](https://cloud.githubusercontent.com/assets/5824123/5782665/166509a4-9df8-11e4-9f7c-8c4b4c621760.jpg)
![qq 20150117020224](https://cloud.githubusercontent.com/assets/5824123/5782671/1c6ca366-9df8-11e4-87f5-d2609f3a5203.jpg)
![qq 20150117020346](https://cloud.githubusercontent.com/assets/5824123/5782675/24b72bea-9df8-11e4-8685-097e24f2c3bf.jpg)

**Comment by daid** [comment]
Which type of printer?

**Comment by colorstone** [comment]
delta  ZXY  All

**Comment by colorstone** [comment]
you can print it to check it   fill density 30% print speed 30 temperature 200

**Comment by colorstone** [comment]
I'm trying to use makerbot printer to test

**Comment by BagelOrb** [comment]
Please test this issue with a reliable printer. Try to test it with an Ultimaker! :D
