### ISSUE TITLE
Current OS X Cura 14.12.1 Image not recognized in OS

### ISSUE THREAD

**Issue by obja** [daid/LegacyCura#1094]
current version at https://ultimaker.com/en/software/download/15/Cura-14.12.1-MacOS.dmg when downloaded will not mount to install... have tried 10.8, 10.9, 10.10 on 3 different machines.

![screenshot 2015-01-16 13 53 54](https://cloud.githubusercontent.com/assets/305878/5787792/b31d485c-9dc5-11e4-9420-845ff4c08e87.png)

**Comment by daid** [comment]
Something seems to have corrupted that dmg. Not sure why.

The latest beta at:
http://software.ultimaker.com/Cura_closed_beta/
Works, and is nearing release, so is very stable.

**Comment by Arsey** [comment]
Try to download it here http://software.ultimaker.com/
Works for me.
