### ISSUE TITLE
Support is not generated for STL of a scythe.

### ISSUE THREAD

**Issue by Patola** [daid/LegacyCura#1101]
Support is not generated for that simpe scythe stl I am attaching.
I have tried changing nozzle size, layer height, support angle, distance X/Y to no avail.

I have noticed there are other bugs related to lack of support but I cannot distinguish if they are caused by the same problem, so I am opening this issue.

I have tested in in Cura 14.12 and 15.01-RC10 (from git).

scythe STL: https://drive.google.com/file/d/0B8WZj6JJHZDwVV9VYmpaNlFadmc/view?usp=sharing

![workspace 1_219](https://cloud.githubusercontent.com/assets/2991620/5825413/3cf610ae-a0d2-11e4-9eae-121417a4a9c6.png)

**Comment by daid** [comment]
Known problems, thin sections are not properly supported.
