### ISSUE TITLE
support structure starting in mid-air

### ISSUE THREAD

**Issue by worker72** [daid/LegacyCura#1107]
I have trouble printing an object which starts on 3 separate places on the printbed, joining higher up.  One of the bottom parts has such a low contact area with the bed that is breaks off before it is joined with the rest of the print.
I tried turning on support, but that particular part does not get any.

Then I tried turing on the brim, in combination with support. Strangely enough, a part of the support structure now starts in mid-air.
I incluse 2 picture: layer view (where the floating support structure is seen in the middle of the part), and the normal view of the part.

I can provide the STL file and the gcode file if useful, I don't know how to attach these.

![image](https://cloud.githubusercontent.com/assets/1201336/5933220/63c88e46-a6bd-11e4-8a91-d477717207f8.png)
![image](https://cloud.githubusercontent.com/assets/1201336/5933223/71d26d7c-a6bd-11e4-9c7e-7a71068fc688.png)

**Comment by daid** [comment]
Currently this is a know problem. With no real fix right now.
