### ISSUE TITLE
Request for file date stamping

### ISSUE THREAD

**Issue by emtemt** [daid/LegacyCura#111]
One thing I would find helpful specially when experimenting with settings would be a time and date stamp in the G code file.

Perhaps on the first line where you put ;TYPE:CUSTOM 16:04 17/5/2012 for example.

**Comment by jgeerds-zz** [comment]
The system file info (date/time created and date/time modified) isn't good enough?

**Comment by daid** [comment]
nope, the system file info gets lost when you copy the file, so that's not good enough. And it's easy to add some kind of tag for it in the start code. I'll do so soon.

**Comment by daid** [comment]
I've added a comment like this:
;Sliced at: Sun 20 May 2012 11:13:54

At the start of the file. I've also adjusted the export so it no longer removes lines that only have comments from the start/end code.

**Comment by emtemt** [comment]
Does not show up in Replicatorg Windows version.

On 19/05/2012 15:01, jgeerds wrote:

> The system file info (date/time created and date/time modified) isn't good enough?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/daid/Cura/issues/111#issuecomment-5801972

## 

Regards

Ian Eagland
Eagland Machine Tools Ltd
http://www.eagland.co.uk/

**Comment by daid** [comment]
Yup. Because this software is not ReplicatorG but Cura. And I've added it to the development version only, new Cura release will be out tomorrow.
