### ISSUE TITLE
infill % is of entire bed, not object/s themselves

### ISSUE THREAD

**Issue by fluxline** [daid/LegacyCura#1112]
have not really spent much time thinking about this, but infill is just a union of the object placed and a grid with a spacing tied to the % entered.  it is not calculated as a % of the object/s on the bed.  i can see where this would be difficult with multiple objects (maybe covered in the new version), but it is also the case for single objects.  

the one case where this would be a real issue would be multiple small pieces and tying to use a large infill, some have infill and some not.

**Comment by BagelOrb** [comment]
This is inherent to the infill pattern. For very small objects of pieces of objects they can fall on a position in the grid where there is no support or where there is support. These pieces are just smaller than the grid. Adjust the grid size or accept that small pieces can get no infill.
