### ISSUE TITLE
buggy output

### ISSUE THREAD

**Issue by TheTesla** [daid/LegacyCura#1118]
On my model there is something sliced wrong. On Cura "Layers" preview it is showing a part hanging in the air when using the slider on the right side. 

Cura 14.07, Windows 7 (64 bit)
![curabug2](https://cloud.githubusercontent.com/assets/2584345/6009906/972d572e-ab2e-11e4-8ff8-cce170ee9ba7.png)
![curabug](https://cloud.githubusercontent.com/assets/2584345/6009907/972e2a28-ab2e-11e4-872c-62ffbcd48004.png)

https://github.com/TheTesla/Entrobot42/blob/master/PLAbug.ini
https://github.com/TheTesla/Entrobot42/blob/master/FederungKette.stl
https://github.com/TheTesla/Entrobot42/blob/master/FederungKette.gcode
https://github.com/TheTesla/Entrobot42/blob/master/FederungKette.scad

**Comment by daid** [comment]
Sliced correctly in 15.01
http://software.ultimaker.com/

Note that the model has some duplicate faces in the STL, which is confusing Cura. 15.01 handles this a bit better.
