### ISSUE TITLE
settings for different qualities

### ISSUE THREAD

**Issue by Karijn** [daid/LegacyCura#112]
Hello daid,

I would like to add and modify the print qualities to cura.
My suggestion would be to use a combobox as quality chooser and select the current quality in the edit fields, so that we can use them as defaults. New user defined settings should be added to the combobox.

2nd whish use the last selected print quality as default for the next session.

**Comment by jgeerds-zz** [comment]
Have you tried switching to the expert mode? it gives you access to far more settings...

**Comment by Karijn** [comment]
Thats absolutely right.
I would like those settings to reflect the choosen print quality, and I would like to see my (modufied) qualities back in the combobox, so that I can easilly use them.

**Comment by daid** [comment]
Yes, there have been more requests for this. But I'm not sure yet on how to implement it.

**Comment by rooiejoris** [comment]
Maybe in normal mode a combo/field where you show the profile, together with a save profile button, maybe i should check some printer/lasercutter drivers how they do it. I think it is more or less simular...

**Comment by nallath** [comment]
Will be adressed in the GUI overhaul.
