### ISSUE TITLE
TweakAtZ Dobule G-Code BUG

### ISSUE THREAD

**Issue by kay54068** [daid/LegacyCura#1123]
Why TweakAtZ 4.0  create G-Code duplicate??

example:
![image](https://cloud.githubusercontent.com/assets/3054544/6042810/bec8f000-acc2-11e4-9d01-d0f40451ff9b.png)

**Comment by Dim3nsioneer** [comment]
A small bug in TweakAtZ 4.0. Just issued a pull request #1124 with a bugfix.
