### ISSUE TITLE
Non printing travel over "land" not "sea" option

### ISSUE THREAD

**Issue by DavidGoodenough** [daid/LegacyCura#113]
For those of us with ooze problems, it would help if there was an option which makes the head move over "land" and not "sea" when traveling from one place to another when not printing.  This will slow down the printing a bit, but it will stop little threads crossing the gaps.
By land I mean solid deposited plastic, by sea I mean open air, such as gaps in a given layer.
Obviously some gaps have no alternative route, but where there is a route over land, please provide an option to use it.

**Comment by daid** [comment]
It's a feature that's called "comb" and it's always enabled...
