### ISSUE TITLE
Support not going high enough

### ISSUE THREAD

**Issue by thorleifjacobsen** [daid/LegacyCura#1130]
--Info and data--
STL File: http://link.jepb.no/Zgpa
Cura Version: Latest

First layer: http://link.jepb.no/ZgMz
Second layer: http://link.jepb.no/Zgdp
Third layer: http://link.jepb.no/ZgBl
Fourth layer: http://link.jepb.no/ZfvA

(First 2 links shows advanced settings, second shows basic. expert settings are here: http://link.jepb.no/Zgcq

--Issue--
The support on this STL only prints 1 layer high. Should print 3 layers so it can properly support the item.

**Comment by BagelOrb** [comment]
Check out expert > open expert settings .. > Support > Distance Z
