### ISSUE TITLE
Layer view displays very wide lines

### ISSUE THREAD

**Issue by MechanizedMedic** [daid/LegacyCura#1135]
Same issue as reported in the forums here: http://umforum.ultimaker.com/index.php?/topic/9537-cura-tool-path-display-issue/

When viewing any model or G-code file the extrusion paths displayed are much wider than they should be. A few layers are still displayed correctly, but I could not find anything that would cause the layers to be differentiated like this.

![screenshot from 2015-02-11 11 16 46](https://cloud.githubusercontent.com/assets/9471777/6154357/fe2a749a-b1df-11e4-86de-47a27d753773.png)

**Comment by daid** [comment]
No clue. Which printer? Which configuration?
(The material flow setting causes this for example)

**Comment by MechanizedMedic** [comment]
It's for a PrintrBot Simple Makers Kit. The configuration is very standard fare, the only change is print dimensions. The first layer extrusion setting is set to 150% but the nozzle is .4 and flow is 100%.

It there anything that I can do to help debug this?

**Comment by daid** [comment]
Still not seeing the same results when I use those settings.

Can you send me a copy of the setting used, as well as your machine settings?
On windows you can find these as ini files in:
C:\Users[user].cura\15.01\

**Comment by MechanizedMedic** [comment]
Well, I just upgraded to 15.02.1 and the problem is now gone.
