### ISSUE TITLE
Exception while printing

### ISSUE THREAD

**Issue by kennedyshead** [daid/LegacyCura#1138]
Unexpected error while reading serial port: SerialException: 'device reports readiness to read but returned no data (device disconnected?)' @ machineCom.py:_readline:516
Changing monitoring state from 'Printing' to 'Error: SerialException: 'device reports re...'
Connection closed, closing down monitor

Gcode works fine in other software

**Comment by daid** [comment]
Sadly, this exception comes from the driver and there is nothing I can do about it.

**Comment by kennedyshead** [comment]
Oh I was not aware, well... I wonder what causing it :/ Will dig in FW

**Comment by daid** [comment]
Firmware won't help you here, it's the windows drivers that are messing things up.

**Comment by kennedyshead** [comment]
Aha Im on debian ;) ill try a later kernel
Den 14 feb 2015 12:36 skrev "daid" notifications@github.com:
