### ISSUE TITLE
Fan on during infill

### ISSUE THREAD

**Issue by destr0y3r2012** [daid/LegacyCura#114]
I have noticed that parts made with CURA are much weaker than the same parts made with KISSlicer. The reason, I've nailed down, is that KISSlicer turns off the fan when doing infill and only turns it on during perimeters. That way, the perimeters get cooled and thus look nice, and the infills stay warm and thus stick better. It's like the best of both worlds.

I would like to request that CURA gets this option because I would like to use CURA (and its comb feature) but for this small problem I am not getting good quality prints.

Thanks, and good job with the software so far Daid!

**Comment by daid** [comment]
Interesting, but it would turn the fan off during bridging, which is not a really good thing.

It you want to experiment with this, you can use the "replace.csv" in the start/end code tab to do this.
Enter:
;TYPE:FILL[TAB]M107[TAB];TYPE:FILL
;TYPE:WALL[TAB]M106 S255[TAB];TYPE:WALL

This will add fan enable/disable lines at the fill and perimeter sections.

(where you use the tab key for [TAB])

**Comment by destr0y3r2012** [comment]
well you could... turn the fan on for bridging and off for regular and sparse infill. Although, having the fan on for top surface infill would be good too. I'll try what you say and report back.

**Comment by thethereza** [comment]
Thanks for posting this, it seems to work great - the print feels much more solid than my previous prints.  I'm not sure what bridging is, so I can't comment on that.

**Comment by thethereza** [comment]
I have found out what briding is and yes, this ruins bridging.  It also ruins the first layer as it turns on the fan for the initial perimeter.  I'm not sure where you code ends and SF begins - is this stuff SF related or part of your code?

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
