### ISSUE TITLE
Can't see dimension and time of print

### ISSUE THREAD

**Issue by Simmonsstummer** [daid/LegacyCura#1140]
Hi, in the version 15.01 i can't see dimension in the resize button and the time of print.

**Comment by restinpieces** [comment]
Same for me. When I load something the text and the bar flickers between white and black. and after it finished calculating its gone. Also the text one the saved file name notification is invisible.

**Comment by daid** [comment]
No idea what's going on here. The rendering code hasn't been really touched at all. But more people are reporting it in 15.01 on the UM forums..

**Comment by stefilla** [comment]
I have installed the version 15.01 form mac and i can't see dimension in the resize button and the time of print. I  cant change the support type and platform. I try reinstall the old cura but there is the same problem.

**Comment by daid** [comment]
There is a 15.02.1 which fixes this issue now.

**Comment by stefilla** [comment]
Thank you, but I tried to install the upgrade version but I have the same problem on Mac OS system but on windows run well.

Stefania - 3D StudioLab

**Comment by vishnubob** [comment]
I still have this problem on OSX, running Cura 15.02.1.
