### ISSUE TITLE
64 bit Cura on a i686 box? 

### ISSUE THREAD

**Issue by BackEMF** [daid/LegacyCura#1141]
i686 is 32 bit or not? (Ubuntu 14.04 in this case)

when i click on OK to download a new Cura (15.01) it downloads the 64 bit version.
I think it is a bug, unless i686 is also happy with the 64 bit version.

**Comment by BackEMF** [comment]
I dug a little deeper
uname -a 
Linux rack 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:37:48 UTC 2015 i686 i686 i686 GNU/Linux
x86_64 ==> 64-bit kernel
i686   ==> 32-bit kernel

so it seems Cura doesn't detect the correct kernel, or it doesn't link to the correct download.

**Comment by daid** [comment]
The download page offers always the 64bit version (as 95% of the linux users have 64Bit systems)
You can download the 32bit version from:
http://software.ultimaker.com/
At the bottom.
