### ISSUE TITLE
15.01 - Some parts of model skipped

### ISSUE THREAD

**Issue by adeebshihadeh** [daid/LegacyCura#1142]
I'm slicing this but not all of the model comes out. Some of it is skipped. [Model](http://www.thingiverse.com/thing:215010/#files) in question
OS X: 10.10.3
![cura-sliced](https://cloud.githubusercontent.com/assets/8762862/6201520/f2c4cda4-b463-11e4-8c19-e18a59795779.png)
![cura_-_15_01](https://cloud.githubusercontent.com/assets/8762862/6201521/f42db23c-b463-11e4-9f94-34982290ce2d.png)

**Comment by daid** [comment]
Does the model show any red in xray view?

**Comment by adeebshihadeh** [comment]
No. 
![cura_-_15_01](https://cloud.githubusercontent.com/assets/8762862/6204616/b43455e8-b506-11e4-8f40-10ffa20fa287.png)

**Comment by BagelOrb** [comment]
What's skipped?
Are you talking about the thin walls?
Perhaps they are thinner than twice the nozzle size. In that case they cannot be printed because they are too thin.
