### ISSUE TITLE
Nozzle not heating on start - Cura 15.01 for Win 7 (32bit)

### ISSUE THREAD

**Issue by jdmech** [daid/LegacyCura#1148]
Ok maybe this is user error (and please point me to where I have overlooked something) but the bed appears to start heating while the extruder nozzle stays at level 0 deg/C. After the bed reaches it's target temp, THEN the nozzle starts heating up to the programmed target temp (200 deg/C) Is this a new feature? It did the same on my Windows 8.1 (64bit) machine with the previous version of Cura - 14.9. I saved the cgode if you would like to see it.

Thanks! - jdmech

My printer and setup:
Prusa I3 - Rework (home built)
w/ heated print bed. Borosilicate glass plate.
Ramps 1.4 board, Arduino 2650
Thermaltake 750watt power supply
Ulti-panel lcd controller
Marlin firmware
Cura - slicer/print software.

Plugin enabled: TweakAtZ.

![gcode issue](https://cloud.githubusercontent.com/assets/7757090/6223788/dedeb098-b625-11e4-9cb9-457a3f1e773f.PNG)

**Comment by daid** [comment]
It's a new, and intended, feature. If you want to do things differently, look at the start code, you can uncomment 2 lines there, if you add those, you can do everything in the order you want, and Cura won't add it's own temperature lines.

**Comment by jdmech** [comment]
Ah - Ok that's great - I'll stick with the intended feature. You guys are
doing a fantastic
job with developing and updating Cura.

Thanks for your help! - jdmech

Regards,

Jon Dawe (JD)
jdmech@gmail.com
