### ISSUE TITLE
cura 3 can`t slice

### ISSUE THREAD

**Issue by elrico1** [daid/LegacyCura#115]
yesterday it worked fantastic, 
today I started the slice, but the loading bar stays at 0.
nothing happens :(
what shall I do??

errread, errwrite)
File "c:/program Files (x86)/cura_RC3/python/lib/subprocess.py",line 893,in_execute_child
startupinfo)
UnicodeEncodeError: `ascii`codec can`t encode character u`/xfc` in position 503
31: ordinal not in range (128)

(pc, win7)

**Comment by daid** [comment]
Duplicate of #116
