### ISSUE TITLE
Tweak At Z4.0  & Cura 15.01 => double each line in gcode

### ISSUE THREAD

**Issue by Holzbalken** [daid/LegacyCura#1151]
When using Tweak AT Z4.0   ( for changing temperatur a Layer 2 ... ) the whole code get´s doubled. 
Each line of code is rewritten twice in the file. 
When using  2 instances of the tool, each code line is written 4 times in the gcode file. 

Right now, the tool is not usable in Cura 15.01 .

**Comment by daid** [comment]
Fix will be rolled out tomorrow.
