### ISSUE TITLE
Feature request: Option to change print ordering of infill vs. perimeter.

### ISSUE THREAD

**Issue by mosh1** [daid/LegacyCura#1159]
v15 changed the ordering from printing perimeters first to printing infill first. This can cause bad surface artifacts as the perimeter shrinks around the printed infill. An option to choose this order would resolve the issue.

More detailed info of surface quality issues: http://umforum.ultimaker.com/index.php?/topic/9771-1501-major-surface-quality-issues/

**Comment by mosh1** [comment]
I'd be happy to implement this change if someone can point me where to look in the slicer engine where this is implemented.

**Comment by daid** [comment]
https://github.com/Ultimaker/CuraEngine/blob/master/src/fffProcessor.h#L647
https://github.com/Ultimaker/CuraEngine/blob/master/src/fffProcessor.h#L681

Should help

**Comment by jmeosbn** [comment]
Hi, was this an intentional change? I was about to report this as a bug.

Additionally, I get traditional ordering (perimeter first) on the top and bottom shells, and the reverse for the infill layers between.

**Comment by mosh1** [comment]
According to the thread mentioned at top this was an intentional change.
