### ISSUE TITLE
cura 3 problem with slice

### ISSUE THREAD

**Issue by elrico1** [daid/LegacyCura#116]
Hi Daid

yesterday it worked fantastic,
today I started the slice, but the loading bar stays at 0.
nothing happens :(
what shall I do??

That`s how it looks:

errread, errwrite)
File "c:/program Files (x86)/cura_RC3/python/lib/subprocess.py",line 893,in_execute_child
startupinfo)
UnicodeEncodeError: asciicodec cant encode character u/xfc` in position 503
31: ordinal not in range (128)

(pc, win7)

**Comment by daid** [comment]
There is a problem with slicing model files that contain "none ascii" charaters, like charaters with accents. Or Russian characters. This problem also seem to be related to windows, as it works for linux.
