### ISSUE TITLE
15.02.01 - Export is missing layers

### ISSUE THREAD

**Issue by adeebshihadeh** [daid/LegacyCura#1166]
When I export the gcode for my model, it will come out missing every layer or so. Sometimes it comes out with only the first few layers exported then the rest blank and sometimes everything is fine. This has happened on multiple models. I fixed the models with netFabb to make sure it wasn't the models. 

Version: 15.02.01
OS: OS X 10.10.3

Model pictured: https://github.com/josefprusa/Prusa3-vanilla/blob/master/distribution/x-carriage.stl

![cura_-_15_02_1 before](https://cloud.githubusercontent.com/assets/8762862/6428745/1bfe8b44-bf61-11e4-8933-316d66222f7b.png)
![cura_-_15_02_1 after](https://cloud.githubusercontent.com/assets/8762862/6428746/1f8dd06c-bf61-11e4-8c0c-dbe7acfe88e9.png)
![cura_-_15_02_1](https://cloud.githubusercontent.com/assets/8762862/6428747/21d13936-bf61-11e4-8e7b-72ad36936899.png)

**Comment by daid** [comment]
Do you have the layer view open during gcode generation? Cause this messes with the layer view for some users (not sure why)

**Comment by adeebshihadeh** [comment]
No. It wasn't open.

**Comment by BagelOrb** [comment]
Is it a problem with the LayerView, or does the exported file actually miss the layers?

**Comment by adeebshihadeh** [comment]
It actually misses layers in the gcode.

**Comment by N720** [comment]
I am having a similar problem, and I believe I have traced it to a bug when switching between printers.  In my case it gives mesh-like prints when I switch from one printer to another (Printrbot Simple Metal, Printrbot Metal Plus, and Witbox 2).  My temporary work-around was to uninstall and re-install Cura.

**Comment by BagelOrb** [comment]
Another workaround would be to uninstall and install the Cura 2.1 beta ;)

2016-04-20 1:57 GMT+02:00 N720 notifications@github.com:

> I am having a similar problem, and I believe I have traced it to a bug
> when switching between printers. In my case it gives mesh-like prints when
> I switch from one printer to another (Printrbot Simple Metal, Printrbot
> Metal Plus, and Witbox 2). My temporary work-around was to uninstall and
> re-install Cura.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/daid/Cura/issues/1166#issuecomment-212177508

## 

Kind regards,

Tim Kuipers

Ultimaker BV

www.ultimaker.com
