### ISSUE TITLE
RC4: no retraction?

### ISSUE THREAD

**Issue by jgeerds-zz** [daid/LegacyCura#117]
I am slicing with daa2066a640ee174c535c05eee2efdf63544d8a2 (RC4), and the gcode doesn't include any retractions upon jump anymore? is retraction permanently disabled and replaced by dwindle? if yes, can you provide a bit more info about the dwindle parameters? if no, can I have the good old retraction back?

[profile]
filament_diameter = 2.9
machine_center_x = 100
machine_center_y = 100
wall_thickness = 1.5
flip_x = False
flip_y = False
flip_z = False
model_scale = 1
model_rotate_base = 0
layer_height = 0.2
solid_layer_thickness = 1
fill_density = 30
skirt_line_count = 3
skirt_gap = 6.0
print_speed = 100
print_temperature = 250
support = None
enable_raft = False
filament_density = .85
retraction_min_travel = 10
retraction_speed = 50
retraction_amount = 2.5
retraction_extra = 0.0
travel_speed = 300
max_z_speed = 15
bottom_layer_speed = 25
cool_min_layer_time = 8
extra_base_wall_thickness = 0.5
sequence = Infill > Loops > Perimeter
force_first_layer_sequence = True
cool_min_feedrate = 10
joris = False
raft_margin = 5
raft_base_material_amount = 100
raft_interface_material_amount = 100
infill_type = Grid Rectangular
solid_top = True
fill_overlap = 15
support_rate = 100
support_distance = 2
bridge_speed = 20
bridge_material_amount = 100
model_multiply_x = 1
model_multiply_y = 1
nozzle_size = 0.49
fan_enabled = True
fan_layer = 2
fan_speed = 100
bottom_thickness = 0
enable_skin = True
swap_xz = False
swap_yz = False
support_margin = 3.0
enable_dwindle = False
dwindle_pent_up_volume = 0.4
dwindle_slowdown_volume = 5.0

**Comment by daid** [comment]
Actually, I found out 2 days ago that my modified retraction doesn't always work, sometimes it doesn't retract while it should. Other then that, the addition of dwindle shouldn't effect the normal retraction.

**Comment by jgeerds-zz** [comment]
There is no retraction at all right now... Should I downgrade to an earlier version of cura? If yes, which was the one before dwell? Or is it a quick fix?

**Comment by jgeerds-zz** [comment]
After going back, and observing the printing a bit more, the inland retraction is gone, but the island jump/retraction is still working.

loosing the inland jump/retraction is causing really bad surface defects, much worse than the combing artifacts Gijs showed the other day. is it possible to re-enable inland jump/retraction again?

**Comment by thethereza** [comment]
I also noticed the same issue, as well as a problem with the sides of the print after retraction - though this might be a feed issue (?).  

http://imgur.com/RyrC9

After it retracts and returns the feed, the output of the head is weak and causes artifacts.  I tried this with a 0 prime and a .1mm prime after the retraction, but it had the same effect.  If you look at the top of the print, it looks good again -- I applied a lot of pressure to the filament going into the extruder (ultimaker) and it seemed to fix the problem.  Is this a software problem or an extruder issue?

**Comment by jgeerds-zz** [comment]
While we had an extensive discussion about inland retraction on the google group, I think there were enough voices in favor for an option to turn inland retraction on/off based on personal preferences.
I wouldn't mind if one of the preference panes has to get a bit larger to accommodate this.

**Comment by daid** [comment]
Open source software development is funny. Suddenly you get this vocal minority that thinks it can democratically decide on development. And people pressing their own opinion as the general consensus.

"I wouldn't mind if one of the preference panes has to get a bit larger to accommodate this. "
I do mind. I actually want to eliminate some settings that I have now.

**Comment by jgeerds-zz** [comment]
'"I wouldn't mind if one of the preference panes has to get a bit larger to accommodate this. "
I do mind. I actually want to eliminate some settings that I have now.'

your software, your call.

**Comment by daid** [comment]
I've added this feature to the expert menu. It's called "only retract on jump" which is enabled by default. If you disable it, it will always retract. Note that this means it will also retract during the short moves it does during infill, and when it's changing layers.
