### ISSUE TITLE
xura connection to melzi bard problem

### ISSUE THREAD

**Issue by zohargolan** [daid/LegacyCura#1171]
H,

I tried connecting to my melzi board using several versions of cura, and I cannot connect. I can connect fine with pronterface.

Please advise,
Zohar

**Comment by nallath** [comment]
The USB connection of Cura isn't really supported anymore. If you want to control your printer, use pronterface.

**Comment by daid** [comment]
Note, some people reported success when you manually configure the serial port instead of using auto detection (as it relaxes some timeouts then)
