### ISSUE TITLE
Save wrong Gcode for invalid model

### ISSUE THREAD

**Issue by frankvdh** [daid/LegacyCura#1172]
If you have an invalid (grey) model, the "Save GCode..." option is still accessible in the File menu. However, when it is clicked, Cura saves the PREVIOUS model's GCode with the current model's filename.

**Comment by daid** [comment]
Known issue, actually there for debugging reasons (you can save half the gcode when the engine crashed, which will black out the normal save button, but will allow you to save whatever is in the buffers with the file menu)
