### ISSUE TITLE
Can't print with USB

### ISSUE THREAD

**Issue by javikas** [daid/LegacyCura#1175]
Since I began using cura, I've never success to print with USB. It creates the g-code without problem, I use to save the g-code and to print it with Pronterface or via SD card.

If I try to print with USB it always starts the process, prints the outside paths and begins to print the part itself, but after 1 or 2 seconds, it stops. Actually it's not a question of time but geometry: If I print a single cube, it will always print the first layer of the first and second side, just two lines, after that printing will stop.

I get the same error with current version (15.02.1) and older versions, I can't remember which ones but I've updated 2 or 3 times at v14 before v15.

printer: Prusa i3 (RAMPS)
firmware: Marlin (current stable version)
OS: OX S 10.10.1

**Comment by nallath** [comment]
USB printing is not recieving any updates from us. Your best bet is to use pronterface. We know that it's not working as it should, but we dont have the resources to do it properly.
