### ISSUE TITLE
No structure under down curve on outside

### ISSUE THREAD

**Issue by the-edge01** [daid/LegacyCura#1177]
I am trying to print a piece that is curved down on the outside and there is no structure inserted under it.
Settings for supports:
![image](https://cloud.githubusercontent.com/assets/11380542/6547933/033033be-c5b6-11e4-9aac-527326738312.png)

The print at 60 degrees:
![image](https://cloud.githubusercontent.com/assets/11380542/6547919/bd9f55aa-c5b5-11e4-9e24-783789e8512d.png)

When I change the angle to 50, it fills out more, but not completely.
![image](https://cloud.githubusercontent.com/assets/11380542/6547991/f1f15306-c5b7-11e4-9574-065f38e88c29.png)

From what I understand, the angle is supposed to be for internal printing, this is on the very outside, so it first tries to print the lowest area which can not attach to anything and then proceeds to try to build on top of that until it makes the connection to the rest of the print.

**Comment by BagelOrb** [comment]
This problem is solved in the new Cura. You will have to be patient my friend :)
