### ISSUE TITLE
package.sh fails on fedora if user has no github private key

### ISSUE THREAD

**Issue by MattEttus** [daid/LegacyCura#1179]
When running package.sh on fedora, a key is required or github since the git@github.com urls are used instead of the https:// versions.  If the user does not have a github key, the script fails with a cryptic error message.  Since not all users are github-registered developers, they won't be able to install.

I can give you a patch if you need, but it is a simple search/replace on the urls.

**Comment by fhuberts** [comment]
I already have a PR open for this: https://github.com/daid/Cura/pull/1164
