### ISSUE TITLE
Feature Request: Warning for non manifold models

### ISSUE THREAD

**Issue by adeebshihadeh** [daid/LegacyCura#1180]
It would be nice to have a notification if a model was not manifold.

Some ideas:

Warning text - could also be in the form of a pop when the model is initially loaded
![cura_-_15_02_1](https://cloud.githubusercontent.com/assets/8762862/6569321/92e29822-c6a5-11e4-8db6-4ab0e7a88a68.png)

A different designated color for non manifold models
![cura_-_15_02_1 2](https://cloud.githubusercontent.com/assets/8762862/6569323/943bd8fa-c6a5-11e4-921e-2ae584440deb.png)

**Comment by BagelOrb** [comment]
I think a warning message is better than another color. In some cases we already use a different color for different models.

However, checking whether a model is manifold might be not as easy as it seems. The good news is that we have most of the machinery in place; we could quite simply make a plugin to do just that.

One problem is that the manifold checker works on 3D models, while the slicer works just on 2D slices. Nearly manifold models may be no problem at all for the slicer. Perhaps the warning might deter less advanced users.

It will be a while before we have this feature (if).

**Comment by adeebshihadeh** [comment]
What type of plugin would be used? As I understand it, there are only window and post processing.

**Comment by adeebshihadeh** [comment]
Another idea: Include an icon with a warning symbol next to the three buttons that show up when the model is clicked on.

**Comment by daid** [comment]
Problem here is that a lot of models are not strictly manifold, but slice just fine. So it would trick people in thinking in something is wrong, while actually nothing is really wrong. At which point people will just ignore the warning all the time, and not trigger on it when it's really needed.
