### ISSUE TITLE
Profile for Materia 101 wanted

### ISSUE THREAD

**Issue by kengdahl** [daid/LegacyCura#1183]
How do we go about creating a profile for The Arduino Materia 101 3D printer?

Kristoffer Engdahl
k.engdahl@arduino.cc

**Comment by adeebshihadeh** [comment]
Does the Materia use Marlin?

**Comment by daid** [comment]
Same route as everything else, simple file for here:
https://github.com/daid/Cura/tree/SteamEngine/resources/machine_profiles

**Comment by kengdahl** [comment]
@quillford Yes, the materia uses Marlin. 

@daid  Thank you :)
