### ISSUE TITLE
Feature Reauest: UI Plugins

### ISSUE THREAD

**Issue by adeebshihadeh** [daid/LegacyCura#1184]
Are there any plans for implementing a UI plugin system?

![image](https://cloud.githubusercontent.com/assets/8762862/6584813/ced7bb94-c765-11e4-9d1f-d985998f8c23.jpg)

**Comment by Dim3nsioneer** [comment]
Wait for plugable unicorn... ;-)

**Comment by adeebshihadeh** [comment]
Plugibale unicorn? Could you elaborate :)

**Comment by daid** [comment]
Will be a rewrite of the UI. We're working on it, it's 100% plugin based, so plugins can work on all areas, including the UI.

**Comment by adeebshihadeh** [comment]
Is there a beta or source somewhere or is it still very early?

**Comment by BagelOrb** [comment]
You will have to wait for a little bit for the sources to be available.
