### ISSUE TITLE
error slicer

### ISSUE THREAD

**Issue by lamerhouse** [daid/LegacyCura#1189]
I have a piece that is at the bottom than at the top should be open .. but when it generates the g-code them always closes version 15.2.1 attach files
![screenshot 2015-03-13 18 53 35](https://cloud.githubusercontent.com/assets/11464372/6644280/e4a4d1f6-c9b2-11e4-9931-8321739f3aac.png)
![screenshot 2015-03-13 18 53 43](https://cloud.githubusercontent.com/assets/11464372/6644281/e4c1afa6-c9b2-11e4-8fe0-38bd263110fc.png)

![y](https://cloud.githubusercontent.com/assets/11464372/6644218/7b2d6f76-c9b2-11e4-9ba2-05d9fcc62822.PNG)   rename PNG in ZIP contains file stl

**Comment by BagelOrb** [comment]
try expert settings > fix horrible > uncheck combine-everything type-A

**Comment by lamerhouse** [comment]
perfect tx

**Comment by daid** [comment]
Note, that means normals in your 3D model are actually flipped.
