### ISSUE TITLE
Feature Request: Continuous channel within infill to allow for easy filling of model with other materials

### ISSUE THREAD

**Issue by williammincy** [daid/LegacyCura#1190]
In order to get a greater strength or weight to a model the typical way to accomplish this is to increase the level of infill when printing. But there is another way to do this that conserves filament and can make for stronger models: Filling the model with another material such as sand or some other fluid that hardens. 

This technique is not new and can be found on a few blogs but what is missing is a feature/option within Cura that gives a continuous channel within the model's infill to make later filling more balanced. The goal is to get as much material spread throughout the model as evenly as possible. 

Having a continuous channel that makes its way through a print will allow a secondary material to flow into the print more reliably. It would also allow for the infill to be kept to a lower level but still be able to fill the print to increase its strength by adding another material to fill in the spaces within the model. It would also print much faster than a print having a higher infill.

I have been searching 3D applications and none that I've come across do this currently, and would be a killer feature for Cura, setting it even further apart from others that try to do what it does.

**Comment by BagelOrb** [comment]
Just for clarification: this issue is closed because it is already filed at CuraEngine.
