### ISSUE TITLE
Print missing Z axis hole.

### ISSUE THREAD

**Issue by mortnr** [daid/LegacyCura#1191]
I am fairly new to 3D printing, so this may be something obvious.  I drew a part on sketchup, checked it on netfab and imported it to cura.  In each case the model looked fine.  However when I printed it, the print out was missing a major element of the model - namely a hole that ran through the Z axis.  Any ideas where to look for the problem?
Thanks.
Nathan
![untitled](https://cloud.githubusercontent.com/assets/11476666/6652468/af628b20-caaa-11e4-8b2a-c66fc64be4be.jpg)

**Comment by Dim3nsioneer** [comment]
I recommend to check the layer view of Cura before printing (icon top right and then the last option).
Check the expert settings (menu expert); if any of the 'fix horrible' option is enabled, disable it. This usually solved that kind of problems.

btw: Shell thickness should be a multiple of 0.4mm for a standard UM2 hotend (1mm makes sense if you have a .5mm or 1mm nozzle).

**Comment by mortnr** [comment]
Thank you. Uncle king 'Fix horrible' solved the problem.
Best regards, Nathan
