### ISSUE TITLE
Unable to save gcode

### ISSUE THREAD

**Issue by cichym** [daid/LegacyCura#1192]
Unable to to save g code with cura 15.02.01
Cure doesn't seems to finish calculation, and it isn't possible to save the g code file.
Thank you.
Michal.

![przechwytywanie](https://cloud.githubusercontent.com/assets/11478070/6652925/177b2cd8-ca80-11e4-97f6-50dc073c5a29.PNG)

**Comment by Dim3nsioneer** [comment]
Any plugin activated? It might be a plugin which is stuck in an endless loop.

**Comment by guidoklauw** [comment]
Did you fix it? I'm having the same problem with Cura and it's not caused by any plugin...

**Comment by cichym** [comment]
Unfortunately,I didn't fix it. I am using older version...

**Comment by daid** [comment]
What does the log file say? (it's in your user directory)

**Comment by cichym** [comment]
That was a lesson for me. Problem was in filament diameter, I should use dot "2.96" , not comma "2,96".

Log file bellow:

Listening for engine communications on 49674
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Cura_15.02.1\python\lib\threading.py", line 552, in __bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Cura_15.02.1\python\lib\threading.py", line 505, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "Cura\util\sliceEngine.py", line 418, in _runEngine
    self._result.addReplaceTag('#F_WGHT#', math.floor(self._result.getFilamentWeight(0) \* 1000.0))
  File "Cura\util\sliceEngine.py", line 74, in getFilamentWeight
    radius = float(profile.getProfileSetting('filament_diameter')) / 2
ValueError: invalid literal for float(): 2,96

Closing down

**Comment by francoisba** [comment]
Hello,
I know it's closed, but I have the same problem.
As I'm already using dots, there might be another explanation.

Maybe for you who know this software, another clue : my model reminds grey on the platform, and the layers view displays only one layer (in this mode, my model disappears)

Thank you for your help,

Best regards
