### ISSUE TITLE
XY Compensation

### ISSUE THREAD

**Issue by miguelangellv** [daid/LegacyCura#1194]
My printer make the holes too small (I don't know why) but with Slic3r XY Compensation I solved it.

Would be posible add the feature to Cura?

**Comment by BagelOrb** [comment]
That would be fairly simple; just add a distance to all insets.
@Diad would we want an extra setting for that?

**Comment by BagelOrb** [comment]
Option has been implemented in CuraEngine. Not (yet?) present in front-end. Perhaps this is not an option which should be exposed to standard users.

**Comment by miguelangellv** [comment]
How configure this feature? Could I set it from .ini file?

**Comment by miguelangellv** [comment]
Any update?

**Comment by BagelOrb** [comment]
You can set it in fdmPrinter.json or via the new Cura interface.

**Comment by BagelOrb** [comment]
Or wait for the new Cura to be released ^^

**Comment by nallath** [comment]
Source of the beta version is already released. See https://github.com/Ultimaker/Uranium and https://github.com/Ultimaker/Cura

**Comment by miguelangellv** [comment]
Thanks :+1:

**Comment by BagelOrb** [comment]
setting name = xy_offset

**Comment by miguelangellv** [comment]
I try use the beta in Linux and it don't work the UI, the opengl crash.
CuraEngine by commands yes works. Can I  activate the xy_offset in the
15.02.1 version?

2015-05-13 9:38 GMT+02:00 Tim Kuipers notifications@github.com:

> setting name = xy_offset
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/daid/Cura/issues/1194#issuecomment-101551561.

## 

Miguel Ángel López

**Comment by BagelOrb** [comment]
No, the setting is only included in the new Cura.
Since the new Cura hasn't officially released yet I can imagine it's hard to get it working.
Perhaps you can submit a bug report for the OpenGL crash? : https://github.com/Ultimaker/Uranium/issues

**Comment by derekhe** [comment]
Why not implement this in this version?

**Comment by BagelOrb** [comment]
The current master and 15.06 branch are for the new Cura. XY compensation is already implemented in 'this version'.
