### ISSUE TITLE
Support material isn't generated for small parts.

### ISSUE THREAD

**Issue by Nandox7** [daid/LegacyCura#1197]
When trying to enable support material for smaller parts the software doesn't generate it.
I've tried several combinations in the settings but none seems to work.

Some examples:
![selection_001](https://cloud.githubusercontent.com/assets/117827/6803500/c905e298-d22f-11e4-9a75-b3185b65c60d.png)

![selection_002](https://cloud.githubusercontent.com/assets/117827/6803505/ce2d2e20-d22f-11e4-8289-31f5628104c2.png)

![selection_003](https://cloud.githubusercontent.com/assets/117827/6803508/d2bfbb1a-d22f-11e4-8f8c-9516f03827ff.png)

STL files used in the screenshots:
http://www.thingiverse.com/thing:654471
http://www.thingiverse.com/thing:673859

**Comment by Nandox7** [comment]
Actually is even worse, it is adding support in the last place I'd like to have it. :(

![selection_004](https://cloud.githubusercontent.com/assets/117827/6803903/94b43974-d232-11e4-8114-95799f3416d5.png)

**Comment by BagelOrb** [comment]
As for your last problem: select 'touching buildplate' instead of ' everywhere' in the support type.

As for the other problems: they have all been fixed in the (yet to come) new version of Cura.
