### ISSUE TITLE
cura 15.02.1 Failed to install firmware

### ISSUE THREAD

**Issue by mbueno0** [daid/LegacyCura#1199]
(SOLVED!)
After installing cura v15.02.1 on my computer, I then tried to update the firmware on my UM2, but received this error message:

```
      Failed to install firmware:
      This firmware is not compatible with this machine.
      Trying to install UM2 or UMO + firmware on an UMO?
```

I am running windows vista ultimate 64 bit.  
Prior to my attempt to install cura 15.02.1, version 14.09 of cura had been installed along with the 14.09 firmware (both of which installed fine).  I am using the same USB cable that I used to install cura 14.09 firmware in my attempt to install the 15.02.1 firmware.  I have also tried using different cables.

```
                   ***  ***  ***  Cancel that!  ***  ***  ***
```

I just had an idea and it worked, but I will leave this post here in case anyone else finds themselves in the same predicament.

While I was trying to install the 15.02.1 firmware, I had another arduino mega 2560 attached to a different USB port on my computer.  This must have confused the installer, because when I unplugged the 2560, the firmware update found the correct mega and the firmware installed just fine.

Thanks!

**Comment by daid** [comment]
Yes, having an Mega2560 Arduino attached will confuse Cura, as it cannot see the proper difference between an ArduinoMega2560, and UMO and an UM2. It actually assumed it was an UMO, whic uses an ArduinoMega2560 (hench the error)
