### ISSUE TITLE
Memory leak loading STL

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#12]
I got the following message when I loaded an STL (http://www.thingiverse.com/thing:8757 though I don't think it matters):

objc[76925]: Object 0x7fd1530debe0 of class NSConcreteMapTable autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug

The message only occurs the first time an STL is loaded after SkeinPyPy is launched. I've tried one other STL and it caused the issue as well.

I'm running a build from my fork (currently identical to your fork as of a day or two ago).

I'm running OS X 10.7.3.

If you need the version of any dependencies let me know.

**Comment by daid** [comment]
Not sure where it comes from, but it's something MacOS specific. The error comes from "objc" which is something apple uses a lot, and I didn't use at all.

Maybe it has to with the wxPython of the Mac?
