### ISSUE TITLE
Suggest Support be made by secondary extruder (tool)

### ISSUE THREAD

**Issue by Japica** [daid/LegacyCura#120]
Hi there, 
     I use Cura all the time, and I am currently using it for the Dual extruder capabilities. The only issue that I would love to see would be to add a button that allows the supports generated to be written for the second extruder. It should be simple enough, basically whatever support g-code is made, you would have the G-code for an extruder switch written in before every line of support gode generated. >

**Comment by daid** [comment]
I think you could already do this with the start_support.gcode and end_support.gcode sections, but I've never tried it yet. It would be a bit tricky to do. But better then nothing atm.

But, yes. A simple "use 2nd extruder for support" checkmark is one of the features I also wanted to add.

**Comment by Japica** [comment]
Ok sounds good Daid. I just thought I would bring it up. I got the thought when I was testing out 'Slicers' button for printing support with a second extruder. The only issue with their set up is, well, it dont work. lol. I will try some stat and end gcode stuff. Not sure what to put in them to get it to do that, but owell, cant be too bad? Just need a line to tell it to use T1 for all support code lines, and use the switch tool head code for each line.. hmmm.

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
