### ISSUE TITLE
No Chinese language option!

### ISSUE THREAD

**Issue by today4king** [daid/LegacyCura#1208]
I love cura ,advise all my friends to use it, but not everyone in china know english especially elders.
could i contribute language file?

**Comment by BagelOrb** [comment]
I don't think a language file from a user will make it to the standard installation. We have translators who do that for us. However, I don't know if we have any Chinese translators. Perhaps you could distribute your language files in China by making a forum post.

Note that the new Cura will require new translation files. Perhaps it would be a good idea to wait for the new Cura, before you start translating.
