### ISSUE TITLE
Feature Request : Add support for G10 / G11 Firmware Retract / Unretract

### ISSUE THREAD

**Issue by SystemsGuy** [daid/LegacyCura#1212]
Tuning Cura retraction on complex bowden systems is quite complex and can be quite cumbersome as changes to retraction parameters requires a reslice and reprint.  It would be nice if cura would allow the option of using firmware based retraction via G10/G11.

**Comment by Dim3nsioneer** [comment]
It already does. Switch the gcode flavor to 'Reprap volumetric'.
