### ISSUE TITLE
A pause button during print.

### ISSUE THREAD

**Issue by marcoleong** [daid/LegacyCura#122]
I'm looking for a button that I can **pause** the printing procedure during printing.
It is useful when I want to clean up internal of an object.

**Comment by daid** [comment]
Yes :-)

I've been experimenting with a print in a print in a print: http://www.thingiverse.com/thing:23589 which also required a pause. As I print with an UltiController, I did different changes, but I can see the use.

As you don't want to pause the printerhead above your print (makes it harder to clean, or to insert objects, also causes blobs) I want to implement that it retracts the filament a bit, moves the printer head away, waits until you press "continue" and then moves back to the old position and continues printing.

**Comment by daid** [comment]
I've added a basic pause button, which just halts the printing and continues when you press resume.

I've also added that if you insert an M0 or M1 into your GCode it will auto pause there, waiting for you to press resume.
