### ISSUE TITLE
cura 15.02.1 has no display any text elements in print window

### ISSUE THREAD

**Issue by litel** [daid/LegacyCura#1221]
![screen shot 2015-04-18 at 4 49 55 pm](https://cloud.githubusercontent.com/assets/2881934/7214742/b39e50dc-e5eb-11e4-9205-dc54c54d1136.jpg)

osx 10.10.3
cura 15.02.1

I guess is a font issue.
In windows, I try translate that texts ('scale' 'rotate' 'mirror' etc) form English to Chinese, Text does not show.
I guess add a font file to cura pyOpenGL text render part can fix this.

**Comment by daid** [comment]
I'm using depricated gluDrawChar functions to draw the text, which indeed is causing issues on various combinations of OS and hardware (some windows users are also reporting this)

Not working on a fix, as we will be repacing the whole UI in a few months, which no longer uses this old font rendering code.
