### ISSUE TITLE
Error generating support material

### ISSUE THREAD

**Issue by ggherbaz** [daid/LegacyCura#1225]
Please take a look at the attached picture, support material is omitted in inner parts and some are generated in midair.

Cura 15.02.1

Thanks,

Gerardo Gherbaz
![cura support material error](https://cloud.githubusercontent.com/assets/7378354/7303596/d17b0bae-e9bf-11e4-9e3d-6e7dbf21a822.jpg)

**Comment by daid** [comment]
Support material generation has been overhauled for the next major release.
