### ISSUE TITLE
feature request : Top/bottom layer with different shell amount

### ISSUE THREAD

**Issue by Chrisu02** [daid/LegacyCura#1228]
I would recommend a feature to change the amount of shells(perimeter) of the fist and especially the Last layer to only one Perimeter and the rest will be infill.

This would result in a very smooth and nice surface especially when printing parts with embossed or engraved letters while the part itself would not become that weak than printing the whole part only with one shell/perimeter.

**Comment by BagelOrb** [comment]
I don't think perimeters are less smooth.
Given that this feature would only work on the topmost layer, and not on the roof tops of lower parts, I think the applicability is negligible.
