### ISSUE TITLE
bus error

### ISSUE THREAD

**Issue by rooiejoris** [daid/LegacyCura#123]
not really repeatable, so i don't know if it is allowed for a bug report...

./cura.sh: line 25: 19404 Bus error               python ${SCRIPT_DIR}/Cura/cura.py

[mac osx]

**Comment by daid** [comment]
A bus error usually indicates a problem with your harddrive or other hardware... it's something MacOS is reporting even before any of my code is running.

If it happens again, run the command "dmesg" and dump the output here (it will be a lot of output). I might be able to tell you a bit more then.
