### ISSUE TITLE
Digital display says "bed heating" but no LED

### ISSUE THREAD

**Issue by srhanna** [daid/LegacyCura#1231]
The bed heater LED does not come on indicating that the FET is not getting turned on and when I measure the voltage between the D8 (black) and the red wire next to it, there is no voltage. So why does the system think the the bed is heating when it is clearly turned off? The nozzle fan FET also does not activate. The nozzle heater does though.

**Comment by daid** [comment]
Which machine?

**Comment by srhanna** [comment]
Reprap prusa i3 running an Arduino Mega 2560

**Comment by daid** [comment]
Can't help you with that. Sorry. (It has nothing to do with Cura, it's your firmware or electronics that has an issue. And I know the Ultimaker stuff on that area)
