### ISSUE TITLE
cura is makeing more travel line went printing

### ISSUE THREAD

**Issue by fredroz69** [daid/LegacyCura#1232]
when printing exstruder it moves the x axes to the end and steps the print
ran g code in buildlog to show travel
![travel g code](https://cloud.githubusercontent.com/assets/12009351/7410722/7810254e-ef29-11e4-8459-4d2db8ca6bd6.jpg)

**Comment by daid** [comment]
Too little info.

Printer unknown. Model unknown. Settings unknown.
