### ISSUE TITLE
install error message driver

### ISSUE THREAD

**Issue by leroy1313** [daid/LegacyCura#1234]
I have CreatBOT and whenever I install a new release such as the current release 6.3.3, I receive an error message that the driver SuWEI 3Dllc install failed. Does the machine need to be connect via the usb port when performing an install so that this message stops? Is it the reason why I can not get the CreatBot machine to be recognized by Windows 8.1??
Any feedback or help is greatly appreciated

**Comment by daid** [comment]
Complain at the actual software supplier. There is no Cura 6.3.3.
