### ISSUE TITLE
Heated bed GUI for ABS

### ISSUE THREAD

**Issue by MaurinElectroTextile** [daid/LegacyCura#124]
I'm using Heated bed for ABS printing
Could it be possible to add gui temperature control like you do for the head ?
M140 S...   ;set bed temperature
http://reprap.org/wiki/PCB_Heatbed_MK2

**Comment by daid** [comment]
Would be possible. I would want to add it in a way so that people without a heated bed don't see it. But there currently is no way to ask the machine if it has a heated bed.

**Comment by MaurinElectroTextile** [comment]
It can be a toggle in the preference pane!?

**Comment by MaurinElectroTextile** [comment]
Did you already think about a text field to allow live Gcode commands ?

**Comment by jenschr** [comment]
I'd love to have this one too. How about adding it under Advanced Settings?

**Comment by hugokernel** [comment]
Ideas :
- Add an input directly in print window to set the temperature heat bed like the head temperature input (eventually, a checkbox in preference panel to specify if a heated bed is present)
- Like MaurinElectroTextile idea, add an text field to allow live GCode commands in print window, when print start, eventually disable this input

**Comment by daid** [comment]
It just hit me, you don't need a checkbox for the heated bed. You know if there is a heated bed if you get a proper (none-zero) bed temperature back from the read temperature command.

**Comment by hugokernel** [comment]
> It just hit me, you don't need a checkbox for the heated bed. You know if there is a heated bed if you get a proper (none-zero) bed temperature back from the read temperature command.

Perfect ! ;)
