### ISSUE TITLE
Popup dialogs always open in the primary monitor on dual-monitor setups.

### ISSUE THREAD

**Issue by juj** [daid/LegacyCura#1246]
STR:
1. Running on a dual monitor setup on Windows, drag the Cura window to the secondary monitor on the desktop.
2. Open any popup dialog, e.g. press one of the buttons titled "..." for Advanced settings.

Observed: The popup dialog that appears will not appear on top of the Cura window on the secondary monitor, but instead it appears centered on the other (primary) monitor.

Expected: The popup dialog should appear on the same monitor where the Cura software is being displayed in.

**Comment by BagelOrb** [comment]
There's a new front-end interface for Cura comming soon. This will most probably not have the same issue.
