### ISSUE TITLE
Where do X & Y travel limit configurations live?

### ISSUE THREAD

**Issue by grantstevens** [daid/LegacyCura#1247]
I think I need to tweak the X & Y travel limits, because Cura's opinion of my Printrbot Simple Metal's travel limits seems to not agree with Printrbot's opionion.

For example, if I place a printable object at the extreme left of Cura's work space, the left edge of the print is 13-14 mm to the right of the extruder's location when it calibrates - and I can't print anything in those 13-14 mms.

At the right edge, we have the opposite problem: if I place a printable object within 13-14 mms of the right edge of Cura's work space, then when I print it, it passes Printrbot's physical limit and makes an awful ratcheting sound.

Same for Y axis.

Can these travel limits be configured?

**Comment by daid** [comment]
Cura assumes the firmware has the 0,0 point at the front left corner, this is configured in your printrbot firmware.
