### ISSUE TITLE
Printing stopped during middle of a print.

### ISSUE THREAD

**Issue by marcoleong** [daid/LegacyCura#125]
The situation is like this.
Cura-RC4 on Mac OS X, and using Ultimaker, I have flashed the firmware that come with Cura-RC4

I have met a problem after several (5~6) normal print with Quick mode in Cura.
Then, the problem comes, the printer always stop at certain point of a print, usually after it finished printing the wall on the 1st layer. That is so weird and I'm trying to restart the print. 
Then I close the **Printing monitor window** 
and press "print GCode" again. 
So I did a check on Cura, found out that the temperature of print head is already 185, while I set to 230 at first. 
I put the temperature in and trying to print again. And it stop at the same point. I close the **Printing monitor window** and in Terminal it shows this error :

``` shell
Serial<id=0x10c41b050, open=True>(port=u'/dev/tty.usbmodemfa121', baudrate=250000, bytesize=8, parity='N', stopbits=1, timeout=2, xonxoff=False, rtscts=False, dsrdtr=False)
Unknown M code:110
```

This problem happen again and again for every prints I try to do afterwards. Until, I found out a quick fix.
I have switched to normal mode and switch back to quick mode again. It Works !!

And now, the problem occurs again at Line: 33133/41036 so about 80% of the print.

Later, I found out a way to access the serial,
do something like screen /dev/tty.usbmodemfa121,There is a msg 

```
Printer stopped deu to errors. Fix the error and use M999 to restart!. (Temperature is reset. Set it before restarting)
                                   ok
```

How can I debug this problem and figure out whats wrong?

**Comment by daid** [comment]
The:

```
Serial<id=0x10c41b050, open=True>(port=u'/dev/tty.usbmodemfa121', baudrate=250000, bytesize=8, parity='N', stopbits=1, timeout=2, xonxoff=False, rtscts=False, dsrdtr=False)
Unknown M code:110
```

Is no error, you can ignore those, they are debug messages. The first shows that it opened the correct serial port at the correct settings. The 2nd is a message from the GCode previewer, which noticed an M110, but doesn't know how to handle it. Which is safe to ignore.

However, the "printer stopped" with the "M999" is a temperature sensor error message. The most likely cause is a bad connection of the temperature sensor or the temperature sensor board. A bad wire could cause a disconnect of the sensor for just a slight moment. Make sure the 2 small screws in the temperature sensor board are really tight.

Note for myself: Cura should report temperature sensor errors that trigger the M999 better.

**Comment by marcoleong** [comment]
okay, thank you for quick reply. I will check it out.
