### ISSUE TITLE
Y Motor doesn't move properly

### ISSUE THREAD

**Issue by christiancasey** [daid/LegacyCura#1250]
Sometimes it does, but then it seems to get stuck in one place. It just makes a lot of noise, but doesn't seem to move the belt at all. I've tried a number of things: retightening the belt, checking the connections, etc. Nothing seems to fix it.

**Comment by daid** [comment]
I recommend you contact your printer supplier. This issue tracker is for Cura software issues. (And this isn't a software issue)
