### ISSUE TITLE
All print speeds go very fast when using support type: touching buildplate

### ISSUE THREAD

**Issue by mrjohnc** [daid/LegacyCura#1251]
I'm using the latest version of Cura on a Mac, when I add support type: touching buildplate all seems normal but when I try to print all movement is very fast, I would guess 100mm/s including on the bottom layer.

**Comment by mrjohnc** [comment]
Also I think the layer height is wrong, looks like 0.1mm not 0.3mm except the first layer which appears to be correct

**Comment by BagelOrb** [comment]
Sounds like a uniquely weird problem. Good news is: the support system has been overhauled for the new Cura, so the problem most probably won't exist anymore in the new Cura.
