### ISSUE TITLE
model size  = memory limits ?

### ISSUE THREAD

**Issue by elipeo** [daid/LegacyCura#1256]
i'm trying to test slicing models for Building Xtreme 1000 machine (x 820 y 780 z 850).
The size of the model to slice is  x 407 y 407 z 805 : Cura

The model ( x 192.31 y 192.31 z 380.03 mm) is nicely sliced (layer 0.2) by Cura with .ini file for Big Dual Builder. The G-code file is +/- 263 Mo.
The model size is

**Comment by elipeo** [comment]
Sorry for double post:
Cura is computing the big model almost at the end and stopped - the computing bar window disappear.
So how to break this limit.

**Comment by daid** [comment]
Windows? On windows you hit some hard memory limits per process. If you are on Mac/Linux then these limits are not there and you can use up all the memory you want.

**Comment by elipeo** [comment]
yes windows 7 with 64 Gb ram (°**°) ... I've just installed Cura & tested the big file (****) hyper-prima, it works like a charm : thanks a lot {I didn't know those memory limits per process}

**Comment by elipeo** [comment]
on a Macbook pro with 8 gb ram.
