### ISSUE TITLE
No Support for small pieces (while standing) in new version?

### ISSUE THREAD

**Issue by HebiMiesch** [daid/LegacyCura#1259]
This "thing" has an height of 17mm and the big diameter is 16mm. As I noticed, the support doesn't work when the piece is standing. And in this case I need to place the piece standing, because of the printingquality. The same "disaster" in v.14.01. But in v.13.06.4 it works?! Thank god you can download the old program versions...
![15 04l](https://cloud.githubusercontent.com/assets/12649045/7869753/19cbb72e-0585-11e5-9627-6cddf1c33a63.jpg)
![15 04](https://cloud.githubusercontent.com/assets/12649045/7869605/1f67ed0c-0584-11e5-85cb-64dde6ea68b3.jpg)
![14 01](https://cloud.githubusercontent.com/assets/12649045/7869607/23f7731a-0584-11e5-8086-ac408f470da2.jpg)
![13 06 4](https://cloud.githubusercontent.com/assets/12649045/7869611/27217e14-0584-11e5-9712-66137c3c364b.jpg)

**Comment by daid** [comment]
Support has always been problematic. The next major release has completely new support code which fixes this issue.
