### ISSUE TITLE
Skirt is too fast

### ISSUE THREAD

**Issue by flouSH** [daid/LegacyCura#126]
"It looks like the skirt is added after the speed procedure. Odd that I never noticed this before."

Reminder for Daid ;)

--> Therefore it doesn't serve the purpose to slowly start the print and have some time to adjust Z-height if needed.

**Comment by daid** [comment]
Florian, do you remember where we had this discussion? Because I cannot remember the details of the problem, and I cannot see anything wrong with the skirt speed.

**Comment by flouSH** [comment]
It was after releasing RC4: https://groups.google.com/d/msg/ultimaker/IOzO0k-fza8/0NLgq_eSLKoJ

Two posts later you replied. I think I've never seen that behavior again in RC5 (I liked the RC versioning scheme ;)).

Feel free to close this, if you think you've fixed the underlying bug.

**Comment by daid** [comment]
I didn't touch anything related to this, but some changes might have fixed it... remains an odd one.

**Comment by flouSH** [comment]
Odd indeed. I will specifically watch closely for another time to see if I can get this bug back ;) Hopefully not!
