### ISSUE TITLE
15.04: normal view shows two holes, layers view doesn't see one of these holes

### ISSUE THREAD

**Issue by arekm** [daid/LegacyCura#1262]
http://ixion.pld-linux.org/~arekm/uchwyt-led.stl

when rendered in normal view in cura 15.04 shows two holes for screws but if you view in layers mode only one hole is shown. Printed element also has one hole.

**Comment by daid** [comment]
Most likely the model has incorrect normals. Play with the expert options "fix horrible" (A and B) which might give different results.

**Comment by arekm** [comment]
Model is broken but shouldn't cura provide consistent view of it? (If not then this can be closed :-) Or at least warn about it being broken.

**Comment by daid** [comment]
Warning is on our future feature list. But we can only show it like we show it right now.

(Pretty much boils down to "this shit is hard...")
