### ISSUE TITLE
Terrain surface

### ISSUE THREAD

**Issue by renatotonielli** [daid/LegacyCura#1266]
Hello,
work in a research institute would like to print the DTM (terrain model) of the seabed. When I try to transfer the file STL of bathymetry (even if converted to positive) Cure (ver15.04) reads the surface as support type.

![surface](https://cloud.githubusercontent.com/assets/12697165/7914362/c3af499c-0876-11e5-85cb-c47c7b33f19c.png)
Surface
![layer](https://cloud.githubusercontent.com/assets/12697165/7914361/c3aaf018-0876-11e5-93fe-c02de99874f5.png)
Layer

**Comment by daid** [comment]
That model is not a manifold solid, and thus the bed effort interpretation that Cura does then will result in the above.

Load an heightmap image into Cura to see how the model should look (Cura can load images)
