### ISSUE TITLE
Multiple Filament sizes

### ISSUE THREAD

**Issue by DanJones530** [daid/LegacyCura#1267]
I have a 3 head printer with two 1.75mm extruders and one 3mm extruder.  It seems to extrude the 3mm filament correctly when I type 3mm into the first Filament Diameter box, even though it is on my third extruder.  If I input the data correctly, it will attempt to push WAY to much of the 3mm filament.  I am using version 15.02.1.

**Comment by daid** [comment]
Sorry, this has been broken like, forever. We're working on a new shiny version of Cura in which we completely rework multiple extruders to allow different settings per extruder way more advanced then we allow right now.

**Comment by DanJones530** [comment]
Thank you!  I am looking forward to trying it.
