### ISSUE TITLE
Support doesn't support retraction

### ISSUE THREAD

**Issue by flouSH** [daid/LegacyCura#127]
Funny title... but that's how it is!

"There are retractions missing, and I'm well aware of it. I just patched the GCode preview to show moves with retraction before them in a different color, so I can debug this better."

Would help to get a cleaner print! Especially important if you're going to print the support with a second print head I guess!

**Comment by daid** [comment]
Should be fixed in the head version now. I changed the way I removed the inland retractions, which I think will work a lot better now.
