### ISSUE TITLE
shell thickness for support different than the printed object (feature request ?)

### ISSUE THREAD

**Issue by francoisba** [daid/LegacyCura#1274]
Hi,
I have noticed that in the 15.04 version (mac), updating shell thickness for the printed object, also impact the thickness of the support wall.

Is there any solution to set each thickness separately ?
That would save some material and a lot of time ! ;)

Thank you for your help,
Best regards

![thickness 1](https://cloud.githubusercontent.com/assets/12500049/8041228/fd39b2b0-0e16-11e5-8334-14e2e0263f66.png)
![thickness 2](https://cloud.githubusercontent.com/assets/12500049/8041229/fd3d08de-0e16-11e5-8587-1c1c5b5570ee.png)

**Comment by BagelOrb** [comment]
Will look into it tomorrow

**Comment by francoisba** [comment]
Whow ! Thank you for your responsiveness !
To be completely honest with you, I forgot to mention that at that moment, the «spiralize» option was checked..
Thank you for your help !
Best regards
