### ISSUE TITLE
No infill in 15.04 version ?

### ISSUE THREAD

**Issue by francoisba** [daid/LegacyCura#1275]
Hello,

After updating Cura to the 15.04 version, all my previous settings were gone.
(it would be a nice feature to retrieve print settings/preferences after updating)

So I went into the settings to reset my printing preferences, and I selected particularly in "black magic" the "spiralize the outer contour*" option.

From there, as described in the picture, I had no more infill, unless I put 100%.

Once this option unchecked, I returned on a traditional view, and the filling was again considered.
Is it me who misunderstood the use of this option or is it a small problem with the software?

(*I tried to translate from french)
![no infill ?](https://cloud.githubusercontent.com/assets/12500049/8043846/00ea2b26-0e29-11e5-950a-a30e02944818.png)

**Comment by BagelOrb** [comment]
I think you totally misunderstood The spiralize option. Spiralize is a printing mode which changes a lot of other settings. Its for printing a vase from a solid cylinder object for example.

**Comment by nallath** [comment]
Also, only the firmware of the UM2Go has been changed in 15.04

**Comment by francoisba** [comment]
Ok, thank you guys. I must admit Cura is totally new to me, and with features I didn't know with Makerware.. So I still have to discover !
Thank you for your help !
