### ISSUE TITLE
Cura 15.05.94 field values are reset when field is disabled from advanced preferences.

### ISSUE THREAD

**Issue by Sander-OS** [daid/LegacyCura#1278]
There is no way to store individual field settings in advanced mode and disable (hide) the field. Is there any way to store the machine quality, speed, etc.. settings ?

**Comment by nallath** [comment]
This is not cura 15.05.94, this repo is the legacy cura (< 15.04)
The repo for 15.05 and above can be found at https://github.com/Ultimaker/Cura
