### ISSUE TITLE
Temperature management

### ISSUE THREAD

**Issue by plgarcia** [daid/LegacyCura#1281]
When no temperature us managed in the start gcode cura add this 2 lines at start of the gcode, what is really fine.
M190 S50.000000
M109 S190.000000

My I suggest to change this to : 
M104 S190.000000
M190 S50.000000
M109 S190.000000

in order to start heating simultaneously bed and nozzle and gain time to print.

Here is what I put in the start gcode that works : 
M104 S{print_temperature} ; Uncomment to add your own temperature line
M190 S{print_bed_temperature} ; Uncomment to add your own bed temperature line
M109 S{print_temperature} ; Uncomment to add your own temperature line

And I moved this line after starting fan as my printer do have only one fan and I need to always cool down the hotend body if I do not want to nozzle  to be tapped.

**Comment by daid** [comment]
Actually, it was like that in earlier versions. However, quite a few machines have slow heating beds with fast heating hotends. Which means the hotend was sitting hot for a long time, causing plugs.

The default is the safe option (and also the option that works the best for the Ultimaker Original Plus)
