### ISSUE TITLE
Reset all printer settings in the incorrect close of cura.

### ISSUE THREAD

**Issue by AndreySkyFoxSidorov** [daid/LegacyCura#1283]
Reset all printer settings in the incorrect close of cura.
Platform: windows
Cura version 15.02.1

Steps:
1. Run Cura
2. Close cura on Ctrl+Alt+Del, Or kill process
3. Run Cura
4. The settings are reset and all data the printer is lost...

**Comment by daid** [comment]
Then don't do that.
