### ISSUE TITLE
Load profile from G-code - Does Not Work

### ISSUE THREAD

**Issue by AndreySkyFoxSidorov** [daid/LegacyCura#1284]
Load profile from G-code - Does Not Work
Platform: windows
Cura version 15.02.1

Steps:
1. Run Cura
2. open "Load profile from G-code" 
3. select G-code file
4. Error message: "This feature only works with GCode files made by Cura 12.07 or newer."
5. Profile not Load :-(

**Comment by milkok** [comment]
You can open your gcode file by UltraEdit,find the last line.Nomally,there's ';CURA_PROFILE_STRING:' at the head of the last line.

**Comment by daid** [comment]
This feature requires

```
;{profile_string}
```

At the end of your end.gcode, or else it won't work.
