### ISSUE TITLE
cura has a big space between

### ISSUE THREAD

**Issue by pedro123a** [daid/LegacyCura#1289]
im trying to print a dragon but is complicate because Cura has rare configuration is new for me.
the software give great space between of the body and the head,
![capture](https://cloud.githubusercontent.com/assets/12992277/8273635/5e5f13d2-182b-11e5-8553-564000bd6618.PNG)
![cura1407](https://cloud.githubusercontent.com/assets/12992277/8273636/5e6193f0-182b-11e5-9d35-36350a6464fa.PNG)
![cura15021](https://cloud.githubusercontent.com/assets/12992277/8273637/5e61bf74-182b-11e5-8e46-1c7daa0b6bb5.PNG)

**Comment by daid** [comment]
Most likely the model has some holes in it which confuse Cura. (or the rendering messed up, as this happens sometimes)

**Comment by BagelOrb** [comment]
Try out the x-ray view!
