### ISSUE TITLE
Will not print ???

### ISSUE THREAD

**Issue by rockendj** [daid/LegacyCura#1293]
I have a Reprap Prusa I3 After days putting it together installed software selected a print item then nothing, plate is heated & nozzle seems ok to any ideas ready to scrap it

**Comment by nallath** [comment]
Sorry, we're not a Prusa helpdesk. Try the RepRap IRC.

**Comment by rockendj** [comment]
thanks I clicked on help / report a problem & it took me here maybe that is the problem...

**Comment by daid** [comment]
This is the Cura software issue tracker.

Don't know where you bought your printer. But we're from Ultimaker. So we support our software and our printers. But we cannot support anything else.

**Comment by rockendj** [comment]
My Printer came with Cura Software & there is a setting for my printer I don't understand & since "report an issue" took me here I am very confused

**Comment by daid** [comment]
You'r printer supplier is what we call a "freeloader". Cura is available for free for everyone, they just ship it with the printer. Does not mean we (Cura developers) will support your printer.
