### ISSUE TITLE
how do i get my wahano i3 to print in the middle of the build table?

### ISSUE THREAD

**Issue by ROBERTBANGE54** [daid/LegacyCura#1297]

**Comment by nallath** [comment]
Move the model to the middle of the build plate with the mouse.

**Comment by ROBERTBANGE54** [comment]
I'll try that.

On Mon, Jun 29, 2015 at 10:09 AM, Jaime van Kessel wrote:

  Move the model to the center of the build plate with the mouse.
&mdash;
Reply to this email directly or view it on GitHub 
https://github.com/daid/Cura/issues/1297#issuecomment-116683955 . 
https://github.com/daid/Cura/issues/1297#issuecomment-116683955
  https://github.com/daid/Cura/issues/1297#issuecomment-116683955
