### ISSUE TITLE
I can't print from my computer using usb cord wahnao i3rinter.

### ISSUE THREAD

**Issue by ROBERTBANGE54** [daid/LegacyCura#1298]

**Comment by nallath** [comment]
Have you checked if it's a problem with the printer? Does it work with printrun?

**Comment by ROBERTBANGE54** [comment]
i don't know what print run is.

On Mon, Jun 29, 2015 at 10:10 AM, Jaime van Kessel wrote:

  Have you checked if it's a problem with the printer? Does it work with 
printrun?
&mdash;
Reply to this email directly or view it on GitHub 
https://github.com/daid/Cura/issues/1298#issuecomment-116685274 . 
https://github.com/daid/Cura/issues/1298#issuecomment-116685274
  https://github.com/daid/Cura/issues/1298#issuecomment-116685274

**Comment by nallath** [comment]
Check if this works http://www.pronterface.com/. Cura doesn't offer full usb printing support, especially not with rare / weird rep-rap clones. We have no way of testing this and even if we did, we simply don't have the time to do it.
