### ISSUE TITLE
Assertion slicing STL

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#13]
I got an assertion slicing http://www.thingiverse.com/thing:8757

File /Users/ljohnston/Development/3dPrinting/Thingiverse/CalibrationPyramid-8757/Hollow_Pyramid.stl is being chain exported.
Carve procedure took 2 seconds.
Preface procedure took 2 seconds.
Inset procedure took 7 seconds.
Fill procedure took 13 seconds.
Multiply procedure took 1 second.
Speed procedure took 1 second.
Raft procedure took 1 second.
Skirt procedure took 0 seconds.
Comb procedure took 1 second.
Cool procedure took 1 second.
Dimension procedure took 1 second.
Alteration procedure took 0 seconds.
The exported file is saved as /Users/ljohnston/Development/3dPrinting/Thingiverse/CalibrationPyramid-8757/Hollow_Pyramid_export.gcode
It took 31 seconds to export the file.
Traceback (most recent call last):
  File "/usr/local/lib/wxPython-2.9.3.1/lib/python2.7/site-packages/wx-2.9.3-osx_cocoa/wx/_core.py", line 16768, in <lambda>
    lambda event: event.callable(_event.args, *_event.kw) )
  File "/Applications/SkeinPyPy/SkeinPyPy/newui/sliceProgessPanel.py", line 88, in OnSliceDone
    self.sizer.Add(self.abortButton, 0)
  File "/usr/local/lib/wxPython-2.9.3.1/lib/python2.7/site-packages/wx-2.9.3-osx_cocoa/wx/_core.py", line 14461, in Add
    return _core_.Sizer_Add(_args, *_kwargs)
wx._core.PyAssertionError: C++ assertion "!sizer || m_containingSizer != sizer" failed at /BUILD/wxPython-src-2.9.3.1/src/common/wincmn.cpp(2282) in SetContainingSizer(): Adding a window to the same sizer twice?

It seems to be reproducible and occurs each time I slice the file.

Let me know what additional info you need and I'll get it for you.

**Comment by daid** [comment]
This must be a bug in the wxPython of MacOS. It's complaining that I added the same control to the sizer twice, but I removed the button from the sizer on line 77.

This bug also causes the layout problem from issue #14.

**Comment by daid** [comment]
I know testing not working fixes is annoying. But I might have fixed this. If you still get an assertion, then I'm at least a bit wiser.

**Comment by RedwoodForest** [comment]
More annoying or less annoying than trying to develop against an OS you don't have a test environment for?

I'll give it a try and let you know.

**Comment by RedwoodForest** [comment]
The assertion is now fixed. The buttons also appear in the correct location now.

Thanks!
