### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by jenschr** [daid/LegacyCura#131]
Got another strange memory error today. I'm once again slicing http://www.thingiverse.com/thing:24710 and now I got a brand new problem (dump below). I've cleaned the model up and scaled it in Rhino to be about 8x8 cm along x/y. I|m slicing at 0.1 mm layer height for about 1000+ layers. After about 12 minutes of going through the different procedures, the file failed to export.

C:\Users\gaming3\Dropbox\3d\thing.stl 0
Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Cura_RC3\python\lib\threading.py", line 552, in __bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Cura_RC3\Cura\gui\sliceProgessPanel.py", line 158, in run    self.gcode.load(self.filelist[0][:self.filelist[0].rfind('.')]+'_export.gcode')
  File "C:\Program Files (x86)\Cura_RC3\Cura\util\gcodeInterpreter.py", line 28, in load
    self._fileSize = os.stat(filename).st_size
WindowsError: [Error 2] Systemet finner ikke angitt fil: u'C:\Users\gaming3\Dropbox\3d\thing_export.gcode'

**Comment by daid** [comment]
The shown error is caused by another bug. That error happens if the slicer failed to generate a GCode file, in this cause a bug in Cura shows the above error, hiding the actual error. This bug is fixed in the development version.

Most likely you ran out of memory on the slice. Nothing I can do about that really.

**Comment by jenschr** [comment]
Ok. I only used about 1.5 gig at that moment. You sure there's no way to increase that?

**Comment by daid** [comment]
I think the limit is 2GB during slicing, which is a pretty hard limit imposed by PyPy. This limit is not used up by the GUI, which runs separately from slicing.

(If you run the MacOS version then there is no memory limit, other then the available memory in your system)

**Comment by jenschr** [comment]
I better get that OSX version up and running then :) Thanks Daid!
