### ISSUE TITLE
support surface

### ISSUE THREAD

**Issue by wqchan** [daid/LegacyCura#1311]
How to add support surface

**Comment by daid** [comment]
You cannot.

**Comment by BagelOrb** [comment]
Perhaps you should take a look at the new Cura. Ultimaker/Cura
Support surfaces will be possible in the next release.

**Comment by nallath** [comment]
They will definitely not be in the next release. Could be that a release after that has the feature.

**Comment by BagelOrb** [comment]
There is an ambiguity in your question. Do you mean that the user should be able to select which polygons should be supported, or that the support structure has roofs/top skin?
