### ISSUE TITLE
Cura doesn't print very last part of surface as shown picture

### ISSUE THREAD

**Issue by 3dprotech** [daid/LegacyCura#1314]
Dear,

Whenever print something that has flat surface, very last part of surface was not printed.
If I print 6 pieces at once, only very last one shows above symptom.
I need your support to resolve this issue.

Thank you for your help and contribution !!
![bug - cura](https://cloud.githubusercontent.com/assets/9882957/8764344/6365ce3c-2e0d-11e5-9746-077fe83dd7a8.jpg)

**Comment by Dim3nsioneer** [comment]
Is the missing part displayed in Cura's layer view? If you have troubles to see it there, you may check at http://gcode.ws or use Repetier host or any other gcode viewer.

**Comment by nophead** [comment]
If you are using Marlin firmware you probably need to put M400 at the start of your end gcode to wait for the buffered moves to finish before turning things off. Marlin buffers moves but executes any M codes following them immediately, i.e. out of order and that can cause problems like this.

**Comment by daid** [comment]
Yes, this isn't a Cura specific problem, it's a printer/setup specific problem. So closing it.

**Comment by 3dprotech** [comment]
Thanks for quick & kind support.
Youe solution works fine as attached image.
![img_2314](https://cloud.githubusercontent.com/assets/9882957/8799911/efab65be-2fe8-11e5-94d5-24aa6f6a1989.JPG)
