### ISSUE TITLE
Creatbot Cura 6.33 Mac 10.10.4

### ISSUE THREAD

**Issue by ruffster** [daid/LegacyCura#1318]
I was able to install on Mac Book Pro (16Gb ram) and Mac Pro (64Gbn ram - FirePro700 x 2 gpu).
It worked a for a short time, but all of a sudden I cannot change any user settings, like "Support type", "Default main extruder" etc.
Reinstalled and still does not work.
Rest PRAM
Repaired disk permissions.

**Comment by daid** [comment]
CreateBot simply leached of our software, we cannot and will not support their version.
