### ISSUE TITLE
Tools for rotating/scaling do not appear when model is selected

### ISSUE THREAD

**Issue by remy-spencer** [daid/LegacyCura#1320]
Build plate background does not load, and when rotate/scale is selected none of the tools appear (rgb circles for rotate, arrows for scale). Occurred on two computers running Win7.

![](https://ultimaker.com/photo/image/675x0/55b120c7239b7.jpg)

**Comment by nallath** [comment]
This is an cura 15.06 issue. Please post it at https://github.com/ultimaker/Cura/
