### ISSUE TITLE
'Print' Window fails to display controls

### ISSUE THREAD

**Issue by spareparts329** [daid/LegacyCura#1322]
The print window doesn't display correctly, unable to preheat or manually control the printer. Attempted to reinstall, which had no effect. ![cura print window fail](https://cloud.githubusercontent.com/assets/13531002/8922189/a5e6c904-3494-11e5-8091-5aaa58fc32dc.png)

**Comment by zaligi** [comment]
I have same issue, uninstalled and re-installed and no command line in print window.
I also just have the print to com port window and command box Gone...

**Comment by zaligi** [comment]
I'm using Windows 8

**Comment by daid** [comment]
Switch to pronterfaceUI in the preferences to get all the controls. This is a feature.
