### ISSUE TITLE
15.06.03 Raft Not Displaying in Layers View

### ISSUE THREAD

**Issue by Fuzionist1** [daid/LegacyCura#1324]
The raft is now displaying in Layers view.  Instead, the first layer shown is as if there was no raft at all. I have tried complex and completely basic models. 
![capture](https://cloud.githubusercontent.com/assets/13238025/9030167/167c600c-396d-11e5-9f1f-380e6877ca8b.PNG)

**Comment by BagelOrb** [comment]
In the old Cura the outputted gcode was parsed and lines were thus displayed. In the new Cura each feature (walls, infill, etc.) is sent from the backend separately and viewed separately.

The raft was probably forgotten. 

Moreover, the layerview is an indication as to what is exactly printed. The actual gcode may diverge from the view.

**Comment by BagelOrb** [comment]
Please submit this issue in the right repository:
https://github.com/Ultimaker/Cura
