### ISSUE TITLE
Different profile for ABS/PLA spool

### ISSUE THREAD

**Issue by hugokernel** [daid/LegacyCura#133]
Hi,

Actually, when i want to change PLA spool, I must change the filament diameter  and the default temperature in the main interface, I need to change the cost in the preferences.

I think it would be very nice to have a profile editor for ABS/PLA spool.

Example:

Brand: Ultimaker
- Diameter : 2.75mm
- Temperature : 210°C
- Cost per Kilo : xx€
- Cost per meter : xx€

In the main window, a form allow user to select a profile corresponding to the spool desired.

It becomes very easy to change the spool : diameter, default temperature and the price is automatically known by Cura.

**Comment by hugokernel** [comment]
New idea, add the heat bed temperature for current profile.

Brand: Ultimaker
- Diameter : 2.75mm
- Extruder head temperature : 210°C
- Heatbed temperature : 60°C
- Cost per Kilo : xx€
- Cost per meter : xx€

**Comment by RavinMaddHatter** [comment]
It would be nice if there where a way to load a filament profile on its own. If there was i would integrate it into UFID. Currently i have made one for slic3r but i would like to do this for cura as well.

https://github.com/camerin/UFIDS_pages/wiki

Note: the standard is evolving, we are currently testing it internally, and allowing others to use it as they would like
