### ISSUE TITLE
Cura 15.04 Dual Extrusion mis-align

### ISSUE THREAD

**Issue by XJoonK** [daid/LegacyCura#1339]
Every time I import two models (one for support) and select "Dual Extrusion Merge" there is always a slight mis-alignment with the two pieces, even though they were imported from the same file, and should be aligned.

I looked for this issue and did not see it addressed already.  I apologize if the answer is obvious, I am still a novice.

-XJoonK
![cura_bug](https://cloud.githubusercontent.com/assets/14810624/10056735/25b01e84-6202-11e5-9c01-001bd6f80aac.png)

**Comment by daid** [comment]
Then the origins of the export are not the same from AutoCAD. So this problem lays more with the AutoCAD exports then Cura.

**Comment by XJoonK** [comment]
Thank you for your response.  
If this is not a common problem, then I am inclined to agree that it is an AutoCAD export problem.  I will try exporting through Blender and see if the problem persists.

**Comment by XJoonK** [comment]
The problem occurs in MatterControl as well, so it is an AutoCAD problem.

**Comment by XJoonK** [comment]
So

**Comment by XJoonK** [comment]
So there is no way to manually align these?  It's a little frustrating.  

Am I seriously the only person experiencing this kind of issue?

**Comment by BagelOrb** [comment]
You are filing the bug in the repository of the old cura interface. Please file a new issue under Ultimaker/Cura

**Comment by nallath** [comment]
The new Cura doesn't have this feature either. It assumes your model is correctly aligned.

**Comment by XJoonK** [comment]
The issue was due to the original file having negative coordinates.  The pieces were shifting to make all  coordinates positive.  Thank you all for your help, the problem of 'use error' has been fixed for this issue.
