### ISSUE TITLE
Major change without major release bump

### ISSUE THREAD

**Issue by cederom** [daid/LegacyCura#1346]
I just wonder why major rework of code in Cura and CuraEngine is done in the middle of 15 not 16(alpha/rc1)? People that get 15 think they get stable release while recent 15 releases introduced major changes in the code and dramatic bugs amount due to code reorganization.. :-(

**Comment by nallath** [comment]
Because the numbers are year.month.version. The year didn't change.

**Comment by cederom** [comment]
ACK! :-)

**Comment by nallath** [comment]
You are right that we should have communicated this change much better though ;) But hindsight is 20/20.
