### ISSUE TITLE
Cura could not connect with Prusa i3 printer

### ISSUE THREAD

**Issue by Welshcoalboy72** [daid/LegacyCura#1351]
Sorry not used to this site. Hope this comes out correct. I recently built a HICTOP Prusa i3 3D printer. The build went very, very well, Everything worked straight away. But after about a fortnight I could not connect to the printer. The LCD screen is now blank as well and unresponsive. I tried a new USB cable and checked my connections and got no joy. I used Windows 10 right from the start, the board is either a RAMPS 1.3 or 1.4. The chip has ATMEGA 2560 printed on it. An help, suggests, guidance would be much appreciated.

**Comment by nallath** [comment]
Have you tried connecting with another usb print software package? It might still be your printer.

**Comment by Welshcoalboy72** [comment]
Thanks for your input nallath, yes I tried Pronterface but no joy. I am a newbie at this game, so any suggestions no matter how obvious to your self or others, would be followed up, and reported back.  Thanks again
