### ISSUE TITLE
Bottom layers speed ramps up, option to disable

### ISSUE THREAD

**Issue by thehans** [daid/LegacyCura#1356]
There is a setting for the "bottom layer speed", which helps with bed adhesion on the first layer.  But I noticed that if I have say 4 bottom layers, Cura seems to ramp up the speed gradually each layer from the bottom layer speed up to the regular speed.  I would prefer a way to disable this, so that only the 1st layer speed is slowed.  It makes prints with large footprints much slower the way it currently is.

**Comment by BagelOrb** [comment]
Note that this is the repo of the old Cura (versions <= 15.04). For the new Cura ( >= 15.06) look at https://github.com/Ultimaker/CuraEngine.

In the new Cura this can be tweaked by setting the Amount of Slower Layers.
