### ISSUE TITLE
Cura Source code and Python 3

### ISSUE THREAD

**Issue by miladelecancy** [daid/LegacyCura#1362]
hey every body.
i need the latest version of cura's Source Code. i mean the source code that is using python3 and pyqt5.
can anyone help me how to find that?

**Comment by BagelOrb** [comment]
Please take a look at https://github.com/Ultimaker/Cura and https://github.com/Ultimaker/Uranium (also https://github.com/Ultimaker/libArcus might be needed)

**Comment by miladelecancy** [comment]
hey BagelOrb , thanks for your fast reply.
yes it seem's good to me. i appreciate that.
