### ISSUE TITLE
I cannot type into the command line using the keyboard of my laptop?

### ISSUE THREAD

**Issue by christytrent** [daid/LegacyCura#1366]

**Comment by daid** [comment]
Not enough info. Cura has no commandline.

**Comment by BagelOrb** [comment]
This seems to me to be a problem of your commands line, your keyboard or your laptop.

**Comment by christytrent** [comment]
The keyboard works,  I can type with it for other things in cura such as temp changes. I also plugged an external keyboard into the laptop.that didn't work either. I updated the cura software thinking that would do it. But it did not.

**Comment by nallath** [comment]
But what command  do you mean? There is no command line in Cura.

**Comment by christytrent** [comment]
When I say command line I'm talking about the box you type commands into such as M500. I can click into the box and see the blinking cursor but it will not type. I used to be able to type. As I said in the above comment the keyboard works everywhere else.

**Comment by BagelOrb** [comment]
I think you are using other software than Cura. 
What does it say when you go to help > about... ?

If you _are_ using Cura, then where would you find such a box?

**Comment by christytrent** [comment]
![cura](https://cloud.githubusercontent.com/assets/15934783/11305220/a236820a-8f79-11e5-9f43-0500dc42b1b9.jpg)
This is the window I'm talking about. You type commands into this box such as M500 to save, etc. I can put the cursor into the box but it will not type. I can type temp changes etc. but it will not type into this box any more. It did previously. I'm am using the current version of Cura.

**Comment by daid** [comment]
There is a box below it where you can type.
