### ISSUE TITLE
dwindle enabled, float division by zero error

### ISSUE THREAD

**Issue by rooiejoris** [daid/LegacyCura#137]
not sure if it is because i changed the inland retraction, but when dwindle is enabled, i get a float division by zero error [when the dwindle values are 0, if i remember correctly

[hi daid, welcome back to NL, i saved some issues... : )

**Comment by daid** [comment]
Makes sense I think. Setting the dwindle values to 0 doesn't sound like proper use of the dwindle module.

**Comment by rooiejoris** [comment]
yes, it makes sense, but not user friendly to wait for a while and then an error shows up, it took me quite some time to figure it out
maybe make the minimum value 0.001 or give a real warning before... like the red colour if you choose a nozzle size of 3mm  [which i actually tested today... : )

**Comment by daid** [comment]
The validation of the normal settings is a lot better then those for the expert settings ;-) but I'll add basic validation to it, should be 2 lines of code.
