### ISSUE TITLE
Stringing because of a z-ramp instead of a straight downward movement

### ISSUE THREAD

**Issue by Martinello** [daid/LegacyCura#1371]
Hello
When switching on the z-hop feature Cura 15.04.3 OS X generates a ramp movement from the right building block to the left building block. 
Every time the print head reaches the edge of the left building block a small dip of plastic is wiped off on the edge resulting in stringing.

But when the head moves from the left building block to the right building block it makes a straight proper downward movement so no PLA could be wiped off.
No stringing on the right building block.

![stringing because of a z-ramp](https://cloud.githubusercontent.com/assets/16167114/11608651/acc183bc-9b6f-11e5-9c0c-d78ce9b73676.jpg)
I exaggerated the z-hop to 2.0mm to illustrate the z-hop more drastically.
I printed it with a z-hop of 0.5mm.

Here is the printed result:
![stringing because of a z-ramp printed](https://cloud.githubusercontent.com/assets/16167114/11608653/c6c1dffa-9b6f-11e5-8772-f92eb9ae09fc.JPG)

Any idea how I can force Cura to make a straight downward movement from right to left as it does from left to right?

Thanks,
Martin

**Comment by BagelOrb** [comment]
Is this a bug in wire printing?

Can you explain better what the problem is exactly? Perhaps a picture can
help a lot.
Op 5 dec. 2015 16:52 schreef "Martinello" notifications@github.com:

**Comment by BagelOrb** [comment]
Never mind my last comment

**Comment by Martinello** [comment]
I'm new to Cura and I think there is no way to to route it manually.

The head should move straight upwards, then travel 90 degrees to the next position and the 90 degrees straight downwards like it does when it moves from the left building block to the right one.

Generating a ramp is not what I understand about z-hopping, it starts stringing as it wipes the filament off when it moves over the edge of the left building block.

**Comment by Martinello** [comment]
Looked at the code.

Cura sets for the travel from right to left a Z value, so a ramp is generated, resulting in stringing:

![cura gcode travel right to left](https://cloud.githubusercontent.com/assets/16167114/11609636/45e35838-9b8c-11e5-98d2-e02a99bb63e7.jpg)

Deleting the Z value in line 120 makes everything fine (+197 other Z values in the code):

![cura gcode travel right to left z deleted](https://cloud.githubusercontent.com/assets/16167114/11609645/845bc0c8-9b8c-11e5-93f9-912c60e667b6.jpg)

For the travel from left to right, Cura sets no Z value, no ramp, no stringing:

![cura gcode travel left to right](https://cloud.githubusercontent.com/assets/16167114/11609650/911035e2-9b8c-11e5-87e5-bfe3556a041e.jpg)

I don't understand why Cura sets a Z value for the end point of the travel from right to left.

For this small test building block I have to delete manually 198 Z values, not very funny ...

Or can I switch off this behaviour somewhere in Cura?

**Comment by Ghostkeeper** [comment]
It looks like a bug indeed then. Cura has come a lot further in the meanwhile though. Perhaps you could try [the version 2 beta](http://software.ultimaker.com/Cura_closed_beta/15.10/Cura-1.99.0-dev.20151117-Darwin.dmg)?

**Comment by Martinello** [comment]
Solved my problem, thanks Ghostkeeper!

**Comment by BagelOrb** [comment]
How did you solve it?
Op 6 dec. 2015 17:34 schreef "Martinello" notifications@github.com:

**Comment by Martinello** [comment]
I'm using Cura 2 beta (1.99.0-dev.20151117) now.
It sets the z-hop in 90° angles, no ramps anymore.

I can't see the z-hop in Cura 2 beta even if set very large values for z-hop (display problem?) but in Repetier I can see them and the printer is moving so as well.

**Comment by BagelOrb** [comment]
OK thanks for the info. Indeed z hops aren't displayed in the new Cura. I
don't know if they ever will be.
Op 6 dec. 2015 18:32 schreef "Martinello" notifications@github.com:
