### ISSUE TITLE
Unable to select more than one model on build plate

### ISSUE THREAD

**Issue by Gav-Will** [daid/LegacyCura#1376]
I'm having issues with selecting other models when importing multiple stl files, only one can be selected and manipulated (moved, scaled, rotated etc.). Other models appear on the build plate but don't become active when selected.  
If loading files one at a time, the most recent model imported becomes active.
Issue only appears to be present in the stable releases, beta release (15.06.03) seems unaffected. 

Cura 15.04.3
Win 7 Enterprise 64bit
Intel Xeon 3.4GHz
16GB RAM
NVIDIA Quadro K2000

Thanks for any help....
Gav

**Comment by BagelOrb** [comment]
If 15.06 is unaffected that means that the next official release won't have the bug either - unless it has been reintroduced.
