### ISSUE TITLE
save as filename.g

### ISSUE THREAD

**Issue by rooiejoris** [daid/LegacyCura#138]
don't know if it is my problem, cura problem or marlin problem, but......
now i rename all files to 8.3 format, which means many times delete the '_export' and delete the 'code' [from 'gcode'] by hand
is it an option to also save a .g file...?!
so both, the _export.gcode and the .g file will be saved

i keep the .gcode file for previewing in cura or pleasant3d or quick preview in mac [space in finder], so the .g is really an extra file

**Comment by daid** [comment]
How about this, an preference option to put Cura into "SD card mode", which will replace the "print" button into an "copy to SD" button, which will also rename the file properly to 8.3 format.

(I personally just put all the files with _export.gcode on the SD card, which works, but shows up as ~1.gco, if the files show as directory, then you need to update your marlin version)

Also, for the batch run tool, this could be added, run a batch and then copy the batch to the SD card.

**Comment by rooiejoris** [comment]
sounds like a good plan...!
or if you option/ctrl click the print button, the sd copy option shows up, [and if in sd mode, the print option shows up]
with of course the changing captions for user friendliness...
