### ISSUE TITLE
Impresions double tete 

### ISSUE THREAD

**Issue by jbs37** [daid/LegacyCura#1384]
Bonjour a tous, 

Je suis nouveau dans le monde de la 3d. j'ai acheté une Bigfoot, avec double extrusion mais je n'arrive pas a en faire l'usage.

Je voudrais que la deuxième buse serve a imprimer les supports d'impressions mais je n'arrive pas a le programmer dans cura. 

Help me please ^^

**Comment by Ghostkeeper** [comment]
L'utilisation d'un deuxieme buse pour les supports n'est pas pris en charge avec cette version. Il est sur notre roadmap, mais je ne peux pas vous dire quand il est fait.

**Comment by jbs37** [comment]
Merci Ghostkeeper pour votre rapide retour,

Vous parlez de la version de cura ? si c'est le cas, je viens de la désinstaller car je me suis aperçus qu'il y avait une version beaucoup plus récente... J'espère que ce sera bon ^^

**Comment by Ghostkeeper** [comment]
To summarise for English readers: jbs37 asked whether he could print supports with a different nozzle with dual extrusion, which is not possible in this version. I suggest that this thread can be closed (but don't have the rights to do that myself).

**Comment by daid** [comment]
![image](https://cloud.githubusercontent.com/assets/964186/11934901/10191a32-a805-11e5-937c-298730781a03.png)
Actually, you can just select it just fine. But dual extrusion in this version of Cura is limited, no configuration for different materials are possible.

**Comment by Ghostkeeper** [comment]
Didn't know that. Sorry for the misinformation!
