### ISSUE TITLE
My bed is slightly to high.

### ISSUE THREAD

**Issue by a4jp-com** [daid/LegacyCura#1389]
What setting can I adjust to move the print nozzle a tiny bit closer to the bed? Is there a negative z-height setting somewhere?

**Comment by BagelOrb** [comment]
You should adjust your bed.

**Comment by a4jp-com** [comment]
I did and the nozzle is slightly touching the bed but when it prints it is slightly to high to stick. It is so close and sometimes does but when it slips all the PLA makes a stringy mess. Any ideas?

**Comment by a4jp-com** [comment]
The nozzle was touching all three points but I just realized my filament diameter was too large. I fixed it now. Sorry about that.
