### ISSUE TITLE
Buttons are incorrectly laid out after slicing STL

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#14]
Any time I slice an STL using the new SkeinPyPy interface, when the slice is complete the "Show Log" and "Show GCode" buttons are laid out incorrectly. Here's an image (see the buttons for the second slice): http://i1162.photobucket.com/albums/q531/lawrencejohnston/Github/SkeinPyPyBadButtons.png

Resizing the window fixes the issue.

**Comment by daid** [comment]
The "Layout" calls on line 89 and 90 should fix this, but those lines are never reached because of problem #13

**Comment by RedwoodForest** [comment]
With the fix to #13 this is also fixed.
