### ISSUE TITLE
Rendering of modified-position models.

### ISSUE THREAD

**Issue by rewolff** [daid/LegacyCura#140]
Hi

My friend wants to print  on plastic platform. So the default code to start printing at z=0 is not good. 

Adjusting the Z-limitswitch is also not an option. 

So we changed the start g-code to say:
G92 X0 Y0 Z-6 E0         ;reset software position to front/left/z=0.0

However, cura now renders the model below the "platform". My friend changed the -6 to +6 and burned a hole in his plastic platform... :-) 

So: when I modify "start.gcode" like this, the rendering is wrong.

**Comment by daid** [comment]
I'm sorry that you friend burned a hole in his platform. So the offset calculation of the G92 is the wrong way around in the preview. I've changed it and should work now.
