### ISSUE TITLE
Bug: Multiply Object

### ISSUE THREAD

**Issue by KellyLSB** [daid/LegacyCura#1408]
When multiplying an object there are a number of fun conditions.
If the value is exactly 8 duplicates it will generate 9.

**Comment by BagelOrb** [comment]
You had one to begin with. 1 original + 8 duplicates = 9 objects.

In that sense the name of the functionality - "multiply" - is not adequate...

**Comment by KellyLSB** [comment]
Try a value of <7 or >9 the behaviour works unexpectedly

**Comment by KellyLSB** [comment]
Also in that case change the name of the function.

**Comment by BagelOrb** [comment]
On my computer it works as I expect it. Perhaps you can be more clear as to what you did exactly, what you expected and what actually happened.

What do you suggest the name of the function should be?
