### ISSUE TITLE
"Spiralizing outer contour" infill Issues

### ISSUE THREAD

**Issue by mouseyjonny** [daid/LegacyCura#1409]
Without the "Spiralize the outer contour" option selected, infill is calculated correctly,
When selecting "Spiralize the outer contour" option, the Infil does not generate. (See two images) .

No other option has been touched between these 2 screenshots.

Cura version 15.04.4 64 bit.
OS Linux Mint 17.3 64 bit.

![](https://cloud.githubusercontent.com/assets/16179055/12625223/c1472a78-c52a-11e5-8856-e932763a106e.png)

![](https://cloud.githubusercontent.com/assets/16179055/12625226/c39f638a-c52a-11e5-8b17-54aef536f5dc.png)

**Comment by BagelOrb** [comment]
Its supposed to work like that. The spiralize option is specially created
for printing the outer wall only with minimal interruption by travel moves.
Op 28 jan. 2016 10:54 schreef "mouseyjonny" notifications@github.com:
