### ISSUE TITLE
Positioning of models in the build-space. 

### ISSUE THREAD

**Issue by rewolff** [daid/LegacyCura#141]
I would like a "late" positioning of the model in the build-space. This means that I can do this in "printrun". 

I would like two options: First: I just move the head to the position where I want my model. No zeroing of X and Y, only Z. 

Secondly I'd like to be able to enter the XYZ coordinates where the print origin should go. 

As models print "around" the centerpoint, and my firmware is compiled to ignore negative coordinates, I think printrun will have to add the origin of the build to each line that it sends to the machine.

**Comment by daid** [comment]
Simple solution for what you want would be to remove the homing start code, and set the printer center to 0,0. Then you can move to the start position yourself.

As this is quite an odd feature, and will be very confusing for new users, and it conflicts with how other features work. So I won't add it to Cura.
