### ISSUE TITLE
Feature request: Option to set different temperature for first layer 

### ISSUE THREAD

**Issue by M0ti0n** [daid/LegacyCura#1419]
This would really improve the adhesion of the print object to the bed without making whole object look bad later in the print and dimensions being inaccurate.

**Comment by nallath** [comment]
This is possible with the tweak at z plugin.

**Comment by M0ti0n** [comment]
Could you please tell me more or give a link to instructions?

**Comment by nallath** [comment]
Google is your friend :) https://github.com/Dim3nsioneer/Cura-Plugins

**Comment by M0ti0n** [comment]
Thank you very much. It works great.
