### ISSUE TITLE
Print Window Too Small/No Controls

### ISSUE THREAD

**Issue by msawberger** [daid/LegacyCura#1420]
![curanotworking](https://cloud.githubusercontent.com/assets/17539358/13386670/7bbfeb62-de74-11e5-9270-3a6007e28b73.jpg)

**Comment by msawberger** [comment]
I've tried redownloading the program and restarting my computer but nothing is working. This just started a couple minutes ago after finishing a different print.

**Comment by daid** [comment]
Looks as intended.

**Comment by msawberger** [comment]
Completely as intended without temperature controls, movement and extrude controls... Totally normal.

**Comment by daid** [comment]
Yes. Totally normal.

If you want those, you can select a different printer window in the preferences. (And tip if you file bugs. Tell what you are missing, let us not guess)
