### ISSUE TITLE
Excess slots in print

### ISSUE THREAD

**Issue by glen-cafferty** [daid/LegacyCura#1426]
I have a part that I made by merging several other parts in 123D Design. It looks OK in 123D and Meshmixer and on the print platform view in Cura. When  printing (and in the layer view) there are slots not shown on the other views of the model in the first and last few layers. These appear to be where parts were joined together in the design. Tried to attach the STL file but this site doesn't recognize that format. attached are screen shots, the problem is in the lower right of the image. Solutions please! 
![bottom bad layer](https://cloud.githubusercontent.com/assets/16311297/13559633/45ab5ece-e3cb-11e5-8f20-b00202f2a1f0.PNG)
![bad top layer](https://cloud.githubusercontent.com/assets/16311297/13559637/4b3b24aa-e3cb-11e5-9ae0-1a0d40c78576.PNG)

**Comment by daid** [comment]
How does the model look in X-Ray view? And red parts?

**Comment by glen-cafferty** [comment]
daid, 

None. It also looks good in 123D Design and Meshmixer. I'm redesigning the part, but would still like to know what the problem is. 

Glen 

----- Original Message -----

How does the model look in X-Ray view? Any red parts?

**Comment by BagelOrb** [comment]
Try fiddling around with the fir horrible settings in expert settings...

2016-03-09 4:52 GMT+01:00 glen-cafferty notifications@github.com:

> daid,
> 
> None. It also looks good in 123D Design and Meshmixer. I'm redesigning the
> part, but would still like to know what the problem is.
> 
> Glen
> 
> ----- Original Message -----
> 
> How does the model look in X-Ray view? Any red parts?
> 
> —
> Reply to this email directly or view it on GitHub .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/daid/Cura/issues/1426#issuecomment-194102736.

## 

Kind regards,

Tim Kuipers

Ultimaker BV

www.ultimaker.com

**Comment by glen-cafferty** [comment]
Tim, 

Thanks, that did it. 

Glen 

----- Original Message -----

Try fiddling around with the fir horrible settings in expert settings... 

2016-03-09 4:52 GMT+01:00 glen-cafferty notifications@github.com: 

> daid, 
> 
> None. It also looks good in 123D Design and Meshmixer. I'm redesigning the 
> part, but would still like to know what the problem is. 
> 
> Glen 
> 
> ----- Original Message ----- 
> 
> How does the model look in X-Ray view? Any red parts? 
> 
> — 
> Reply to this email directly or view it on GitHub . 
> 
> — 
> Reply to this email directly or view it on GitHub 
> https://github.com/daid/Cura/issues/1426#issuecomment-194102736. 

## 

Kind regards, 

Tim Kuipers 

Ultimaker BV 

www.ultimaker.com
