### ISSUE TITLE
Model position in gcode differs from shown

### ISSUE THREAD

**Issue by ohhmm** [daid/LegacyCura#1429]
This well seen for [flaring upper layers](https://drive.google.com/file/d/0B1uZun88ibskZzhQcHBnbi0yRGc/view?usp=sharing).
I guess the reason is in using base layer for figure projection perimenter retrieval to put it in the center.
This should be not perimeter of base layer but accumulative perimeter of projections of all layers.

**Comment by BagelOrb** [comment]
Can you elaborate?
Op 7 mrt. 2016 20:33 schreef "Sergei Krivonos" notifications@github.com:

**Comment by ohhmm** [comment]
filled its description

**Comment by BagelOrb** [comment]
If I slice this in Cura 15.04.4 and switch between normal and layer view I see the gcode at the same position as the model.

Please fill in a complete bug description. You supply far too less information.

**Comment by ohhmm** [comment]
Normal and Layer view in Cura shows everything well. But once I load the gcode into GCode simulator or Pronterface, I see it shifted and upper layers became out of borders.

**Comment by BagelOrb** [comment]
Sounds like a problem of Pronterface.. Try reporting a bug with them..
Op 8 mrt. 2016 16:06 schreef "Sergei Krivonos" notifications@github.com:

**Comment by iHateInventNames** [comment]
oh well, the problem in 3d printer persists

On Wed, Mar 9, 2016 at 10:17 AM, Tim Kuipers <notifications@github.com>
wrote:

> Sounds like a problem of Pronterface.. Try reporting a bug with them..
> Op 8 mrt. 2016 16:06 schreef "Sergei Krivonos" <notifications@github.com>:
>
> > Normal and Layer view in Cura shows everything well. But once I load the
> > gcode into GCode simulator or Pronterface, I see it shifted and upper
> > layers became out of borders.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/daid/Cura/issues/1429#issuecomment-193816597>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/daid/Cura/issues/1429#issuecomment-194177174>.
>



-- 

Sergei Krivonos
skype: sergio_krivonos

**Comment by BagelOrb** [comment]
What kind of printer do you have?
Op 9 mrt. 2016 17:17 schreef "Sergei Krivonos" notifications@github.com:

**Comment by ohhmm** [comment]
reported bug to GCode simulator

**Comment by ohhmm** [comment]
I have smartcore 3d printer. Has no problem while printing Cura latest
official release made gcode with printrun. But the Cura itself sends gcode
shifted to 3d printer
09.03.2016 19:17 пользователь "Tim Kuipers" notifications@github.com
написал:
