### ISSUE TITLE
Dual print alignment / graphics

### ISSUE THREAD

**Issue by BlueBot-xx** [daid/LegacyCura#143]
Hi

I thought I was having trouble with dual head prints not aligning properly when I load them into Cura. For example your Dual colour D&D Pillar

http://www.thingiverse.com/thing:23008

The shorter (red in your print) model sits on the printer bed, merging with the taller model that has the plinth. 

After slicing it however the gcode view is perfectly aligned. As such probably not a high priority.

Cheers 

Paul

**Comment by daid** [comment]
Yes, there are a few more issues with this and dual head printing. You will notice if you try slicing all the test cubes that they all slice fine, but don't always end up where the preview has shown them.
