### ISSUE TITLE
How to install on OpenSuse

### ISSUE THREAD

**Issue by alexpacini** [daid/LegacyCura#1432]
Hi,
I am trying to install the software on OpenSuse Leap42.1.
Unfortunately, the official package is only for Debian based systems and the unofficial OpenSuse build (OBS) has issues with the wxWidget version and it is not updated to the last version.
Is it possible to get instructions on how to build the package on OpenSuse?
Why the official version is distributed only as .deb?

Thanks,
Alex

**Comment by XiaoShiZi** [comment]
http://software.opensuse.org/package/Cura

Checked that site?
Greetz, Xiao Shi Zi
Op 14-mrt.-2016 17:39 schreef "Alex Pacini" notifications@github.com:

**Comment by alexpacini** [comment]
Yes, but the latest package available there (15.04) does not work on Leap 42.1

**Comment by daid** [comment]
> Why the official version is distributed only as .deb?

Because that's all we care about. We do not have the man power to support all Linux distros. So we have a debian package, and sources.

**Comment by alexpacini** [comment]
Why don't ufficially support a Docker image?

**Comment by daid** [comment]
effort.
