### ISSUE TITLE
Failed to save

### ISSUE THREAD

**Issue by alxbirdsall** [daid/LegacyCura#1434]
So after a couple weeks of using my Ultimaker 2+ and Cura. I have encountered my first problem. Suddenly every 3d model I try and save to SD in cura comes up with the message 'failed to save'. No explanation as to why. So now I am very stuck, couldn't find any answers online. I have tried uninstalling and reinstalling cura, and tried a variety of different SD cards.

**Comment by daid** [comment]
Does coping a file to the SD card work?
Which OS are you using?

**Comment by Ghostkeeper** [comment]
Also always make sure that the SD cards are not on "locked" :wink:

**Comment by mihaidimitras** [comment]
I have the same problem I checked the sd card is on unlock the same result 'failed to save'????

**Comment by Ghostkeeper** [comment]
Just to check, same question for you: Is it possible to copy files to the SD card via the normal file explorer?

**Comment by mihaidimitras** [comment]
No

**Comment by Ghostkeeper** [comment]
Then the problem lies not with Cura, but with the SD card or your computer. Perhaps the computer doesn't support the file format on the SD card? You might need to format it.

**Comment by mihaidimitras** [comment]
I think it could be related to admin permission.  Anyway thanks...
