### ISSUE TITLE
Cura not responding

### ISSUE THREAD

**Issue by simonhuiberts** [daid/LegacyCura#144]
If you have used a wrong scale Cura go's on the run and don't stop anymore. I have found only one way to end, and that's to remove Cura totaly from my pc and start installing again.

**Comment by daid** [comment]
You could also have adjusted the scale directly in the current_profile.ini, or moved the model aside so Cura could have no longer loaded it.

However, I do wonder what scale you gave in so it hangs, because I cannot seem to replicate it.

**Comment by simonhuiberts** [comment]
I have tried everything but new installation was the only solution. It started by puting in a smal scale and using a dot (.) in stead of a comma (,)

**Comment by daid** [comment]
I did find a bug that seems to happen if you insert some types of wrong data into the scale box. I've added a fix for it in the next version. However, it still did not hang for me.
