### ISSUE TITLE
unknown target CPU 'pentium4' when packaging win32 on mac

### ISSUE THREAD

**Issue by donaldding** [daid/LegacyCura#1441]
I try to packaging Cura , and I didn't change any Cura code.
 I work on Mac OS X 10.10.5.  
and I got the following output when packaging.
Can anyone help me?

> Extracting PortablePython_2.7.2.1.exe Cura-15.04.6-RC1-win32/python
> Extracting PortablePython_2.7.2.1.exe Cura-15.04.6-RC1-win32/python/Lib/site-packages/
> Extracting pyserial-2.5.win32.exe PURELIB
> Extracting PyOpenGL-3.0.1.win32.exe PURELIB
> Extracting numpy-1.6.2-win32-superpack-python2.7.exe numpy-1.6.2-sse2.exe
> Extracting numpy-1.6.2-sse2.exe PLATLIB
> Extracting VideoCapture-0.9-5.zip VideoCapture-0.9-5/Python27/DLLs/vidcap.pyd
> Extracting comtypes-0.6.2.win32.exe
> Extracting ejectmedia.zip Win32
> g++ -c -Wall -Wextra -Wold-style-cast -Woverloaded-virtual -std=c++11 -DVERSION=\"15.04.6-RC1\" -isystem libs -O3 -fomit-frame-pointer -march=pentium4 -flto src/bridge.cpp -o build/bridge.o
> error: unknown target CPU 'pentium4'
> make: **\* [build/bridge.o] Error 1`

**Comment by daid** [comment]
This is not supported.
