### ISSUE TITLE
gcode convertion failure

### ISSUE THREAD

**Issue by klooppjk** [daid/LegacyCura#1442]
I load an .obj file
preview is correct into cura
if i select "slice view" 
the hole in the midle disapears the problem exists when I print the object !
[bouchon_bas.zip](https://github.com/daid/Cura/files/189329/bouchon_bas.zip)

**Comment by klooppjk** [comment]
i have already  tried to uncheck the "fix horrible" it does not solve the issue

**Comment by daid** [comment]
Did you check the X-Ray view? If it shows any red parts, then there are errors in the model.

**Comment by klooppjk** [comment]
there are no "red parts", you can open the zip file I sent if you want.

**Comment by BagelOrb** [comment]
Try fiddling with the fix horrible settings under export settings.
Op 25 mrt. 2016 14:04 schreef "klooppjk" notifications@github.com:

**Comment by klooppjk** [comment]
Thanks for your help.
I have tried to check and uncheck "fix horrible" setting options without success. (i have tried ALL possibilities !)

**Comment by daid** [comment]
![image](https://cloud.githubusercontent.com/assets/964186/14100388/51f19e36-f58d-11e5-950e-96db2cc978c1.png)
There are a shitloads of holes in that model. Cura cannot make up information that is not there.
