### ISSUE TITLE
New to 3D

### ISSUE THREAD

**Issue by mflossem** [daid/LegacyCura#1450]
I was advised to try Cura as a means of familiarizing myself with 3D modeling.  I don't have a 3D printer and will most likely be sending stuff I make to Sculpteo or someone locally on 3D Hub.  Can I still use Cura?  I had to put something for a default printer in the setup, but I don't have one of my own right now.  Please advise as to how to continue if I don't have a dedicated printer.  I am totally new to 3D and am trying to teach myself using freeware online.  I have already tried (unsuccessfully) to send to Sculpteo this week and am back to square one trying to come up with a design that can be printed without being too thin.  Thanks~

**Comment by daid** [comment]
Cura does not do 3D modeling. It prepares your model for 3D printing on FDM based printers (and is mostly aimed towards printing on an Ultimaker)

Important features that you can look at are the X-Ray view (any area in red is a problem in your model which causes the software to be confused) and the layer view, which will show how it will be printed.
