### ISSUE TITLE
Can't select proper printer

### ISSUE THREAD

**Issue by edlubs** [daid/LegacyCura#1452]
Just downloaded the latest distrobution for 64 bit Ubuntu. I am not able to select my printer when choosing the other bubble. I can see that the list continues down, but I can't scroll or move the page at all. This is a problem especially since I have a XYZ Davinci 1.0 (probably near the bottom of the list.)

**Comment by daid** [comment]
The Davinci is not in the list. Pick one that is most simular to your machine and modify it to your needs.

The lenghty list not fitting on screen is only happening on linux. And with the 2.1 beta out, we're not planning to spend time on fixing this.
