### ISSUE TITLE
Slicing fails silently on 16.04 - new versions will not install

### ISSUE THREAD

**Issue by gazhay** [daid/LegacyCura#1455]
16.04 ships with a newer python3 than cura depends on so will not install.

On my existing install of cura no slicing works at all. I can load models but nothing happens. 
"Show Slice Engine Log...." does nothing.

**Comment by daid** [comment]
There is no 16.04 version of Cura.

**Comment by gazhay** [comment]
16.04 of Ubuntu, released yesterday, hence "ships with"

**Comment by daid** [comment]
I'm not a mind reader. Nowhere you tell you use linux, nowhere you tell you use ubuntu. Nowhere you tell which version of Cura you tried.

Pretty much no information is provided. So no help is provided.

**Comment by gazhay** [comment]
I appreciate it was a poor bug report. 

However, as I took the time to start a bug report (whilst still trying to solve it myself) you could have just asked for info rather than close it.

Sorry for wasting your time, good luck solving the issue, I've used Slic3r in the meantime.

**Comment by BagelOrb** [comment]
So what version of Cura are you trying?

Try the Cura 2.1 beta version!
Log bugs for that software under Ultimaker.Cura instead of daid/Cura

2016-04-23 11:40 GMT+02:00 GazHay notifications@github.com:

> I appreciate it was a poor bug report.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/daid/Cura/issues/1455#issuecomment-213703725

## 

Kind regards,

Tim Kuipers

Ultimaker BV

www.ultimaker.com

**Comment by gazhay** [comment]
I have logged in the correct repo now.

Fwiw I tried to install 2.1 Beta and 15.06.03, both fail as described on python.
If you force them to install they crash on start.
