### ISSUE TITLE
The "spiralize the outer contour" option generates a hollow model

### ISSUE THREAD

**Issue by yansiegers** [daid/LegacyCura#1456]
In the Expert Configs, underneath "Black Magic": When the "Spiralize the outer contour" option is checked, Cura does not generate any filling. It does not matter what the infilling percentage is set to.

Cura version 15.04.5

**Comment by Ghostkeeper** [comment]
This is intended. Spiralize Outer Contour _only_ draws the contour of the model. No infill. No support. Nothing. It's useful for printing things like vases and mugs.

**Comment by mrlunk** [comment]
How do I set the wall thickness for this ?
It is showing only 1 outer layer in CURA...

**Comment by BagelOrb** [comment]
Spiralize can only work with one contour. The whole idea is that you
gradually move up while printing. That only makes sense when the is a
single contour.

Op 25 mei 2017 22:25 schreef "mrlunk" <notifications@github.com>:

**Comment by kyrreaa** [comment]
But if you set external perimeter extrusion width you can control wall
thickness.
