### ISSUE TITLE
Layer thickness estimation from Gcode is "old". 

### ISSUE THREAD

**Issue by rewolff** [daid/LegacyCura#147]
Line 154 of  gcodeinterpreter.py in current cura reads: 

```
                if moveType == 'move' and oldPos.z != pos.z:
                    layerThickness = abs(oldPos.z - pos.z)
```

This is "oldfashioned" and might not work for properly-joris-ed prints. 
(I'm not sure what "layerthickness"  is used for in the rest of the code... It seems to work this way, so it's not critical...

(I'm reading the code to learn python and/or start working on fixing some things that are annoying me).

**Comment by daid** [comment]
Actually, this is intentionally, if it encounters jorised GCode it will use the old layer thickness. It's using the layer thickness to calculate the width of the printed line. So using the old layer thickness is no real issue.

**Comment by rewolff** [comment]
I don't understand. Normally a change in Z is the layer height.

Say I'm building a block: 

   G1 Z0
   G1 X0 Y0 
   ; layer 1
   G1 X10 Y0 Ex
   G1 X10 Y10 Ex
   G1 X0 Y10 Ex
   G1 X0 Y0 Ex
   G1 Z0.1  
   G1 X10 Y0 Ex
   G1 X10 Y10 Ex
   G1 X0 Y10 Ex
   G1 X0 Y0 Ex
   G1 Z0.2

so each time cur_z - old_z will be layer height. 

But when I joris this: 

   G1 Z0
   G1 X0 Y0 
   ; layer 1
   G1 X10 Y0 Z0.025Ex
   G1 X10 Y10 Z0.05 Ex
   G1 X0 Y10 Z0.075 Ex
   G1 X0 Y0 Z0.10 Ex
   ;
   G1 X10 Y0 Z0.125 Ex
   G1 X10 Y10 Z0.15 Ex
   G1 X0 Y10 Z0.175 Ex
   G1 X0 Y0 Z0.20 Ex
   ;

Now each time curz-oldz will be much smaller than the layer height

**Comment by rewolff** [comment]
What I meant with "old" is "from before the joris procedure changed things. 

This is, I THINK an example gcode where the calculation goes wrong. On the other hand, the preview might be right, as I'm now running to  the printer to start the print. Gotta go. :-) 
http://prive.bitwizard.nl/twister.gcode
(this is "manually" generated gcode, not from cura). 
(to load the gcode in cura, rename any stl file you have to twister.stl, rename the twister.gcode to twister_export.gcode and then load twister.stl into cura). 

[update: The Gcode file prints fine. Note that my "manual" code is lazy on the "joris". I just do it on one of the longer lines instead of completely continuous.... ]

**Comment by daid** [comment]
Actually, that's why there is the first condition in there. It only updates the layer height on moves, not on Z moves during printing. Which causes the Jorised GCode to preview correctly.

**Comment by rewolff** [comment]
Duh! Ok! I get it.

**Comment by daid** [comment]
I know my code has a serious lack of comments. So feel free to ask any questions about it :-)
