### ISSUE TITLE
Error by cura

### ISSUE THREAD

**Issue by ivma00** [daid/LegacyCura#1472]
Why?

![normal view mode](https://cloud.githubusercontent.com/assets/19412867/15330481/5001fb1a-1c5d-11e6-9c17-2d1e848c543e.jpg)
![layers view mode](https://cloud.githubusercontent.com/assets/19412867/15330488/549f2300-1c5d-11e6-880e-771cda31101c.jpg)

**Comment by BagelOrb** [comment]
The piece is too thin
Op 17 mei 2016 18:32 schreef "ivma00" notifications@github.com:

**Comment by ivma00** [comment]
Thank you, problem solved

Il 17/05/2016 19:05, Tim Kuipers ha scritto:
