### ISSUE TITLE
Keeps pushing down hard onto the deck

### ISSUE THREAD

**Issue by robmc63** [daid/LegacyCura#1476]
Each time I initiate a file to print the extruder complex dials down to the deck then keeps going pushing down the deck.  I have cleared the programs, shut down the program and restarted, unplugged the printer but it keeps doing it.  Any suggestions?

**Comment by daid** [comment]
Which printer?

**Comment by robmc63** [comment]
Play

**Comment by daid** [comment]
Ok. The "zero" position is a printer related activity. It seems your play decides that the bed is not where it actually is. Cura cannot help on this aspect unless the start.gcode is wrong (which is also printer specific). I recommend asking around on a Printrbot forums.
