### ISSUE TITLE
Weird addition definition in util3d. 

### ISSUE THREAD

**Issue by rewolff** [daid/LegacyCura#148]
The definitions in util3d allow vectors to be added. 

```
def __add__(self, v):
    return Vector3( self.x + v.x, self.y + v.y, self.z + v.z )
```

looks good.

However, 
    def **iadd**(self, v):
        self.x += v.x
        self.y += v.x
        self.z += v.x
        return self

looks weird. Of course the behaviour that this has can be intended. But it is very counter-intuitive. I would, using the Vector3 class expect 
    vectorOne  = vectorOne + vectorTwo
 and 
    vectorOne += vectorTwo 
to behave the same, but they don't. I'd be very surprised. 

Checking if maybe the "weird" behaviour was intended, I found 
  ./cura_sf/skeinforge_application/skeinforge_plugins/craft_plugins/limit.py
where on line 140
  self.oldLocation += relativeLocation
uses Vector3 **iadd** addition and expects the "expected" behaviour and not the implemented one. 

I expect copy-past-modify error in the implementation phase, right?

**Comment by daid** [comment]
http://docs.python.org/reference/datamodel.html
Documented at **iadd** "These methods should attempt to do the operation in-place (modifying self)"

As far as I can see this implementation is correct. **iadd** modified self, as expected by the += operator.

**Comment by rewolff** [comment]
Sorry. You're apparently a bit blind to the error in the code you
wrote yourself. As I am blind to spelling errors that I sometimes
make. I thought it would be obvious by quoting the code. 

Instead of adding X, Y and Z, it adds X, X and X to the three
coordinates.   [1, 2, 3] + [4, 5, 6]  should be [5,7,9](as __add__ would calculate), but not [5,6,7] as **iadd** calculates. 
(it adds only the "4" of the second vector).

**Comment by daid** [comment]
Ah, yes, I see. Stupid. And I indeed was blind do it.

It might be interesting to know that this 3D vector class is not used by the slicer, only by the GUI. Skeinforge has it's own class, which is slower for some uses (due to overloaded compare operators). Using my own 3D vector in the STL loading make STL loading about 70% faster. So the effect of this bug would have been limited to the GUI.
