### ISSUE TITLE
Feature Request   8.3 file name for SD files

### ISSUE THREAD

**Issue by emtemt** [daid/LegacyCura#149]
Printrun automatically shortens file names to 8.3 for SD upload.

Could an optional flag be added to Cura to force gcode file names to 8.3 so it is possible to write file direct to SD plugged into computer and not have to rename in explorer.

**Comment by daid** [comment]
The next version has an option to copy to SD after slicing, this option also has an optional setting to rename to 8.3 names while copying.

**Comment by emtemt** [comment]
Many thanks.

On 01/07/2012 19:54, daid wrote:

> The next version has an option to copy to SD after slicing, this option also has an optional setting to rename to 8.3 names while copying.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/daid/Cura/issues/149#issuecomment-6695969

## 

Regards

Ian Eagland
Eagland Machine Tools Ltd
http://www.eagland.co.uk/

**Comment by flouSH** [comment]
Is this also in combination with *.g instead of *.gcode?

There's really no need for .gcode - and it gives you more space on the Ulticontroller. That would be superb!

**Comment by daid** [comment]
It's placing the first 8 characters and then .g on the SD card. As using gcode as extension would make it a long filename, and thus you would get the ~1 again.

**Comment by flouSH** [comment]
Sweet! Good work!
