### ISSUE TITLE
Infill Density = 100%: Bottom Layers goes berserk

### ISSUE THREAD

**Issue by demisjohn** [daid/LegacyCura#1490]
Cure 2.1.1

If I set `Infill Density = 100%`, `Bottom Layers` gets set to `999999`.  Any value less than 100% and the value is normal.

![screen shot 2016-05-30 at 12 10 35 am](https://cloud.githubusercontent.com/assets/5370181/15769678/1fe37dd4-2912-11e6-94dc-bbf83d72d09c.png)

---

![screen shot 2016-05-30 at 12 10 43 am](https://cloud.githubusercontent.com/assets/5370181/15769679/243281be-2912-11e6-8871-e9a5a517823d.png)

**Comment by nallath** [comment]
This is by design. We fake 100 infill density by simply setting the number of bottom layers to a very high number. I do agree it's not the nicest solution, but if I recall correctly this made the engine faster.

**Comment by BagelOrb** [comment]
This also makes printing faster and more accurate, since no infill overlap
is applied.

**Comment by daid** [comment]
Note, old Cura (15.04 and older) did the same, but without showing you.
