### ISSUE TITLE
error while printing stops the process

### ISSUE THREAD

**Issue by jeetdeogun** [daid/LegacyCura#1492]
while printing from the software on my reprap 3d omni printer the printing stops during anytime of the process from 10-80 % and the error log has following errors
Communication timeout during printing, forcing a line
Send: M105 T0
Communication timeout during printing, forcing a line
Send: M105 T0
Communication timeout during printing, forcing a line
Send: M105 T0
Changing monitoring state from 'Printing' to 'Operational'
Send: M105 T0
Changing monitoring state from 'Operational' to 'Printing'
Send: N0M110_3
Send: N1M190 S70.000000_80
Send: N2M109 S210.000000_103
Send: N3G21_57
Communication timeout during printing, forcing a line
Send: M105 T0
Communication timeout during printing, forcing a line
Send: M105 T0
Communication timeout during printing, forcing a line
Send: M105 T0
Communication timeout during printing, forcing a line
Send: M105 T0
Communication timeout during printing, forcing a line
Send: M105 T0
Communication timeout during printing, forcing a line
Send: M105 T0
Communication timeout during printing, forcing a line
Send: M105 T0
Unexpected error while reading serial port: SerialException: 'call to ClearCommError failed' @ machineCom.py:_readline:516
Changing monitoring state from 'Printing' to 'Error: SerialException: 'call to ClearComm...'
Connection closed, closing down monitor

please help me solve the issue

**Comment by SamPayet** [comment]
Hi, today i get the very same issue... Do you fix it on your printer?

**Comment by daid** [comment]
The problem is with USB, not with the software.

**Comment by DonYum** [comment]
@daid why?

**Comment by daid** [comment]
Because "Unexpected error while reading serial port: SerialException: 'call to ClearCommError failed' @ machineCom.py:_readline:516"
Is straight from the USB serial driver, and I've tried everything I could to prevent this, and failed. I have a laptop that always has this error within 10 minutes.
