### ISSUE TITLE
Cura 15.4.6

### ISSUE THREAD

**Issue by Sangra69** [daid/LegacyCura#1497]
Ever since this crazy update this software has not be able to let me print. It keeps saving to an SD card file. I DON'T HAVE AN SD CARD SLOT ON MY PRINTER. I changed all the settings to turn off SD card support. All I want to do is access the UI printer interface to control the extruder. This software was fine before the new update. I am using a Robo3d R1.

**Comment by Sangra69** [comment]
It keeps on wanting to open .ini files as well. It won't let me do anything else. This software is crap now it seems.

**Comment by BagelOrb** [comment]
Maybe you should try out Cura 2.1
It's officially released now..

2016-06-09 22:07 GMT+02:00 Sangra69 notifications@github.com:

> It keeps on wanting to open .ini files as well. It won't let me do
> anything else. This software is crap now it seems.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/daid/Cura/issues/1497#issuecomment-225010730, or mute
> the thread
> https://github.com/notifications/unsubscribe/AIe9EbWV5bcll6lxjkSzvXbVRbAxq0kjks5qKHJqgaJpZM4IyWW1
> .

## 

Kind regards,

Tim Kuipers

Ultimaker BV

www.ultimaker.com

**Comment by daid** [comment]
Replace your machine with an Ultimaker 2+?

Or, did you try rebooting windows? Windows is extremely bad with USB serial port handling. Which is why Cura (and Ultimaker) prefers SD printing over USB printing.

**Comment by daid** [comment]
Note that there where limited changes in the 15.04.x releases, only small tweaks and profile updates for the Ultimaker2 line of printers. So I'm 100% convinced that it's not a change we made that is breaking your workflow.
