### ISSUE TITLE
How come there is never support material between 2 plastic layers?

### ISSUE THREAD

**Issue by tecnicolys** [daid/LegacyCura#1498]
Hello

Since I started using Cura every time I have a part that has some protruding tags, and these tags are positioned over some model geometry and not over the base plate, supporting material is never created. As you see the picture below, I would like to have some support material even on the area that is marked in green
.
![no support material](https://cloud.githubusercontent.com/assets/19819280/15967869/d2848420-2f29-11e6-9dd7-84fc820e528f.JPG)

Thank you

**Comment by BagelOrb** [comment]
Try Cura 2.1! Its support generation mechanism has totally been revised. In
the new Curaq you will have way less problems such as the above.

2016-06-10 16:39 GMT+02:00 tecnicolys notifications@github.com:

> Hello
> 
> Since I started using Cura every time I have a part that has some
> protruding tags, and these tags are positioned over some model geometry and
> not over the base plate, supporting material is never created. As you see
> the picture below, I would like to have some support material even on the
> area that is marked in green
> .
> [image: no support material]
> https://cloud.githubusercontent.com/assets/19819280/15967869/d2848420-2f29-11e6-9dd7-84fc820e528f.JPG
> 
> Thank you
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/daid/Cura/issues/1498, or mute the thread
> https://github.com/notifications/unsubscribe/AIe9EewGBUDLL5u7vHxje_4Jf2SJ4VBHks5qKXcdgaJpZM4IzA94
> .

## 

Kind regards,

Tim Kuipers

Ultimaker BV

www.ultimaker.com

**Comment by daid** [comment]
Could also that you have "touching buildplate" support selected.
