### ISSUE TITLE
PrintRun gives incorrect filament used statistics

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#15]
This may be a PrintRun issue, but since it occurs with SkeinPyPy generated GCode I thought I'd file it.

Whenever I print a file from PrintRun, when it's finished it prints "3.5 mm of filament used in this print" to the console. This is obviously wrong, since in the case of my last print the final value in the GCode file (before end.gcode) is E88.8039.

My wild guess is that it's taking the value from the "G1 F75 E3.5" in the start.gcode.

**Comment by daid** [comment]
As the plan is to replace PrintRun, I'm not going to fix the problem in PrintRun. But I have added a filament measurement to the GCode reading in SkeinPyPy.

It only shows on the console window right now, so not really finished yet. But better then nothing.

**Comment by RedwoodForest** [comment]
The console window is fine with me for now. But I don't see it for the slice I just tried:

File .../NotchTest_HalfHeight.stl is being chain exported.
Carve procedure took 0 seconds.
fill_overlap not found in profile, so using default: 15
support_rate not found in profile, so using default: 100
support_distance not found in profile, so using default: 0.5
Preface procedure took 1 second.
Inset procedure took 2 seconds.
Fill procedure took 5 seconds.
Multiply procedure took 1 second.
Speed procedure took 0 seconds.
Raft procedure took 1 second.
Skirt procedure took 0 seconds.
Comb procedure took 0 seconds.
Cool procedure took 1 second.
Dimension procedure took 0 seconds.
Alteration procedure took 0 seconds.
The exported file is saved as .../NotchTest_HalfHeight_export.gcode
It took 12 seconds to export the file.

**Comment by daid** [comment]
It's shown when you load the GCode into SkeinPyPy, not after finished slicing. Sorry about that confusion.

I'm working on updates to "streamline" the slicing workflow a bit more, if you still have the model open that just finished slicing I should load the GCode with it. Saves a button press :) The latest push also addeds a "mixed" view, where you can see the GCode path and the model at the same time.

**Comment by daid** [comment]
The printing interface in Cura RC1 gives an nice estimate of the filament used, in mm and in grams.

**Comment by RedwoodForest** [comment]
Thanks. I don't typically print from Cura, but it looks like I can open the print window and view the stats without connecting to the printer, so that's good enough for me.
