### ISSUE TITLE
FR: joris style vases/tubes with thick walls

### ISSUE THREAD

**Issue by jgeerds-zz** [daid/LegacyCura#150]
Joris is printing his objects with a single wall, and with a very big nozzle. normal UM users have a 0.4-0.5mm nozzle, and can't print a nice 1-1.5mm wall in one go. 2-4 walls are necessary.

when printing 2-4 walls, cura prints each loop in a different direction (while making the constant z-height adjustment), leaving a nasty z scar. the outer lop goes clock-wise, inner loop goes CCW, Z jumps back, outer loop goes CW again etc. each reverse in printing directions makes a bump forming the z scar. and I thought the point of Joris style is to avoid the z scar.

proposal: force each loop into the same direction, making it a bigger continues loop.

**Comment by daid** [comment]
The Joris feature is documented as "It is intended to be used with a single walled wall thickness"

There is no way to get rid of the seam if you print multiple wall lines. Because at the spot where the head moves inward to print the inner loops it will always leave a small seam.

**Comment by jgeerds-zz** [comment]
yes, I know it was initially used as a single wall solution. but why not try to make it a multi wall solution? if you make a continuous loop on the outside in one direction, and then have a tiny blip inside to make the next loop in the same direction does less damage (aka z scarring) then the outer loop in one direction, and the inner loop in the other direction, which leaves a very very pronounced z scar (looks like a trench).

**Comment by daid** [comment]
Because... well... skeinforge.

**Comment by jgeerds-zz** [comment]
well, it was worth a try... if a solution how to fix it comes automagically into your head, feel free to implement it.
what I don't understand is when I print a regular object the outer wall and the inner loops are printed in the same direction. but with Joris active, the direction changes with the outer/inner loop.

**Comment by rooiejoris** [comment]
> > normal UM users have a 0.4-0.5mm nozzle, and can't print a nice 1-1.5mm wall in one go

This is perfect possible, but you have to print slower, because you get more pressure in the nozzle...

**Comment by sequoia-hope** [comment]
I was thinking about this - what about 3 walls? One up, one in and back down, then one more in but back up. Then jump back out and repeat. But I guess the nozzle would run into the first perimeter when it hit the end of the second perimeter?

**Comment by daid** [comment]
yeah, the nozzle would hit the perimeter. So that won't be good. Another idea would be to only so the "z lift while move" on the last few cm of the layer. This would print the whole layer as normal, but on the last bit you already start going up. This removes the need to have a "stop & lift", but still keeps the rest of the layer printed as normal.

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
