### ISSUE TITLE
Holes are missing

### ISSUE THREAD

**Issue by tius2000** [daid/LegacyCura#1500]
Holes are visibile in normal view and x-ray, but missing in layers and gcode

[Uploading holes-missing.zip…]()

[ it seems that upload did not work, here is a link https://www.dropbox.com/s/xmxcfl10f45e7ej/holes-missing.zip?dl=0 ]

**Comment by Ghostkeeper** [comment]
Your model is broken. You can see in x-ray that there are extra walls inside the model. This could do strange things to a slicer. It assumes that the mesh separates the inside of the model from the outside, and thus that one of the sides of that extra wall has to be the outside of the model. And it all goes messy from there.

I suggest that you repair your model with a repair tool or using 3D modelling software.

**Comment by tius2000** [comment]
Dear @Ghostkeeper, thank you for your fast reply and suggestions! 

I repaired the model in Sketchup and I think all extra walls are gone now, it looks fine to me in x-ray: 
https://www.dropbox.com/s/hwkyunyp0ozy5f2/holes-missing-v2.dae?dl=0

However, the path still seems to be wrong - is the model still broken?

**Comment by BagelOrb** [comment]
Yes, some faces are inverted. No faces should look blue from the outside.

However, Cura can fix this: turn off "Union Overlapping Volumes"

Or just load the fixed stl: 
[Untitled-57607ebc2.zip](https://github.com/daid/Cura/files/315055/Untitled-57607ebc2.zip)
;)

**Comment by BagelOrb** [comment]
Note that it's a bad idea to make the holes in the bottom so big that they coincide with the edges. The first layer will now remove the edge between the hole and the outside because it's too thin.

**Comment by tius2000** [comment]
Dear @BagelOrb, thank you very much, it worked :+1:  

The option was named "Expert config > Combine everything (Type-A)" in my version of Cura (15.04.06)
