### ISSUE TITLE
Python File Location Mac OS

### ISSUE THREAD

**Issue by fergussonb** [daid/LegacyCura#1501]
I have changed some of the python files that run Cura on my PC and would now like to update these same files on my mac. On my PC they are stored in cura\Cura\util and cura\Cura\gui but I can't seem to find the file locations on my Mac. Can anyone point me to where they are located on Mac?

**Comment by daid** [comment]
On Mac they are "compiled" and stored in a zip. The Mac version is not that easy to modify due to this.

**Comment by fergussonb** [comment]
Where is the zip located?

**Comment by daid** [comment]
Somewhere in the app bundles resources.

**Comment by fergussonb** [comment]
thanks

**Comment by fergussonb** [comment]
Found it under resources/lib/python2.7 in the site-packages.zip. Thanks
