### ISSUE TITLE
Cura.py to exe

### ISSUE THREAD

**Issue by rahuldevikar761** [daid/LegacyCura#1503]
How did you manage to convert Cura.py to Cura.exe. I am working on windows 8 and everything works properly when I compile py file but I am not able to convert it to exe file. I tried py2exe and pyinstaller, but it seems get the exe file but it doesnot run the program.

**Comment by daid** [comment]
On Cura 15.04.x, I don't. Look at the package.sh script. For Cura 2.x, goto github.com/Ultimaker/Cura-build
