### ISSUE TITLE
Clicking ... for Brim options brings up Raft dialog.

### ISSUE THREAD

**Issue by ChinookTx** [daid/LegacyCura#1506]
In 15.04.6, clicking the ... button when the "Brim" option is selected in the drop down brings up the Raft options.  If I select something else, then go back to Brim, then the right options window shows up.

This is on the Mac version, haven't tried windows.

**Comment by ChinookTx** [comment]
Possibly a duplicate of #1210

**Comment by daid** [comment]
Due to the release of Cura 2.1, we're not longer maintaining the old UI.
