### ISSUE TITLE
Putting a large value into the layer selection field results in odd behavior

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#151]
Steps:
Load an STL.
Slice the STL (optional if it's already been sliced).
Switch to GCode viewing mode.
Put a value in the layer selection field that's known to be above the last layer of the model (e.g. 9999).

When I perform these steps the layer selection field displays the last layer of the model (in my case 623), but not all of the model's GCode is displayed (in my case it looks like 100-200 layers are displayed). Furthermore, I can't click the up button to display more of the missing part of the model, but if I click the _down_ button then _more_ of the model is displayed instead of less.

My reason for entering 9999 in the selection dialog in the first place is wanting to display the entire model regardless of how many layers it actually has. The behavior I would expect is that the layer selection field would display 623 (as it does now) but that the entire GCode model would display in the window.

**Comment by daid** [comment]
Can you tell me in which version this happens, on which OS? Because I do not see this behavior myself.

**Comment by RedwoodForest** [comment]
OS X 10.7; development branch from several days ago. I know it's been
present for several months though.

-Larry

On Jul 2, 2012, at 1:18 AM, daid
reply@reply.github.com
wrote:

**Comment by daid** [comment]
Then I'm putting this on OS X specific at the moment. As I cannot reproduce it in both Linux and Windows XP or Vista.

**Comment by RedwoodForest** [comment]
A bit more info on this one:

This happens any time you put in a layer number that's a above the current highest loaded layer number.

For example if I've just loaded an STL/GCode pair and am viewing the first layer (no higher layers viewed yet), if I switch to layer 10 it doesn't display up to layer 10. It may display a couple of additional layers, but not anywhere close to 10.

This is frustrating because it means to view an entire object you have to load it, view layer 1, and then click and hold the up button on the stepper until the entire thing is loaded. Only at that point can you jump around to view specific layers. If you skip directly to the top (or even the middle) it doesn't display correctly.

Another odd thing that may be of help. While the issue is currently manifesting (you're trying to look at a layer you haven't viewed yet but it's not displaying), if you zoom in and out of the viewing window it actually displays more layers over time (without changing the stepper controller)! Also, clicking the "down" button in the stepper control actually displays _more_ layers as well (until you've stepped down to a the point where the displayed layer matches the one in the stepper control, at which point it starts displaying fewer again).

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
