### ISSUE TITLE
223 mm is not Ultimaker 2 extended+ real width

### ISSUE THREAD

**Issue by Enno45** [daid/LegacyCura#1518]
I try to print a 3D Modell with the width of 220 mm and it doesnt work.

please, help.

**Comment by BagelOrb** [comment]
Perhaps the platform adhesion is the problem here. Try setting it to brim
and then decrease the brim line count.

Also try out cura 2!

Op 14 jul. 2016 16:21 schreef "Enno45" notifications@github.com:

**Comment by Enno45** [comment]
The Software did not allowed to print it.

**Comment by daid** [comment]
You'll have to set the skirt line count to 0, else the line around the print will go over the edge of the print area.
