### ISSUE TITLE
Bottom/Top thickness oddity when combined with Initial layer thickness

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#152]
I have Bottom/Top thickness set to 0.45 mm. I have Layer height set to 0.15 mm. I have Initial layer thickness set to 0.3 mm.

I would expect this to result in 2 full bottom layers (one of 0.3 mm and one of 0.15 mm, for a total of 0.45 mm), but it results in 3 (one of 0.3 mm, and two of 0.15 mm, for a total of 0.6 mm).

**Comment by daid** [comment]
This might feel a bit weird but I'll explain to you what happens.

The "initial layer thickness" is added as extra thickness for the first layer. The bottom/top thickness is used to calculate the amount of layers of the normal layer thickness are needed. The step that adds the full filled layers has no knowledge about the first layer or how thick it is. So it uses the same for all those layers.

So yes, it adds too many thick layers at the bottom. I know it. But it would require some serious skeinforge hacking to fix this. So I rather keep it as it is now.

**Comment by RedwoodForest** [comment]
Thanks for the explanation.

On Jul 2, 2012, at 1:17 AM, daid
reply@reply.github.com
wrote:
