### ISSUE TITLE
Packaging Cura 15.04.6 for MacOS

### ISSUE THREAD

**Issue by remelbourne** [daid/LegacyCura#1521]
I am trying to package Cura for my Mac which is running version 10.6.8. I have followed the required steps on the readme page and everything has worked fine up until I run the command "./package.sh"

I keep getting the following error message:

![screen shot 2016-07-19 at 2 06 24 pm](https://cloud.githubusercontent.com/assets/13418206/16949388/c8f268a0-4dba-11e6-9ac8-dcde7e810bbc.png)

I searched the problem online and some said the problem would be fixed by changing               -std=c++11 with -std=c++0x but that did not fix the problem.

My g++ version is:

![screen shot 2016-07-19 at 2 07 09 pm](https://cloud.githubusercontent.com/assets/13418206/16949484/5ecb819a-4dbb-11e6-9214-8b4500bf9114.png)

I am unable to update to a newer g++ version and I was wondering if that is the problem.

Any help would be much appreciated!

**Comment by Ghostkeeper** [comment]
I don't think GCC v4.2.1 has any C++11 support. It was released in July 2007, and the 11 stands for 2011.

Perhaps if you are unable to update to newer g++ versions, you could consider using Clang?

**Comment by daid** [comment]
Building for OSX is just a world of pain. You can thank Apple for that.

Note that we are no longer planning to update the 15.06 version of Cura, as we are switching to Cura 2 for all development.
