### ISSUE TITLE
Modifying GUI of Cura 

### ISSUE THREAD

**Issue by aquibjaved** [daid/LegacyCura#1524]
I am changing the GUI part of Cura, I want to make an extra border on the sides of the build volume and another one is I want put some logo instead of " Basic" Button. How can I do it?

**Comment by nallath** [comment]
There is no real easy answer to give here. I'd recommend taking a look at the source code and play around with it a bit.

Note that this cura is the old (and no longer supported version). These kind of GUI changes are easier to do in the new Cura.

**Comment by aquibjaved** [comment]
can you Please give me the link from where I can download and build the new cura. And also please let me know how can I change the GUI of new one.

**Comment by BagelOrb** [comment]
software.ultimaker.com

**Comment by daid** [comment]
There is no step-to-step guide for this. If you cannot figure it out on your own, you are most likely also not capable of doing anything else without our help. Which means we are doing your work for you. And I don't think we get paid for that.

**Comment by aquibjaved** [comment]
hmm, Alright thank you

**Comment by Ghostkeeper** [comment]
Take a look at https://github.com/Ultimaker/cura-build . It provides CMake scripts that should build Cura 2 for you from the ground up. There's often a few extra steps to take depending on your operating system and the libraries Cura depends on, but with a bit of trickery anyone should be able to get it working eventually.

**Comment by aquibjaved** [comment]
I am getting this error while building it. When I hit the command sudo make

CMakeFiles/Qt.dir/build.make:89: recipe for target 'Qt-prefix/src/Qt-stamp/Qt-download' failed
make[2]: **\* [Qt-prefix/src/Qt-stamp/Qt-download] Error 1
CMakeFiles/Makefile2:736: recipe for target 'CMakeFiles/Qt.dir/all' failed
make[1]: **\* [CMakeFiles/Qt.dir/all] Error 2
Makefile:105: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by Ghostkeeper** [comment]
That's a target to download one of the dependencies, the Qt GUI framework. Your snippet doesn't mention why the Qt-download target failed, but it might just be a lack of internet connection or a hiccup on Riverbank's servers.

~~At this point it's probably better to move any further problems with building Cura to the cura-build repository, as this all has little to do with Daid's Cura: https://github.com/Ultimaker/cura-build/issues~~
Nevermind, I see you made an issue there: https://github.com/Ultimaker/cura-build/issues/76
