### ISSUE TITLE
Typos in mainwindow.py. 

### ISSUE THREAD

**Issue by rewolff** [daid/LegacyCura#153]
There are two typos. One of a technical nature one of a language-nature. 
I'm going to see if I can add a patch. (but nothing here in this submit issue window).

**Comment by rewolff** [comment]
It'll have to be cut-paste then. 

F**\* the comment system displays it "weird". mail me if you don't manage to get the patch. 

Here is the patch:   http://prive.bitwizard.nl//home/wolff/3d/cura_typos.patch

index 036d574..4f2adcc 100644
--- a/Cura/gui/mainWindow.py
+++ b/Cura/gui/mainWindow.py
@@ -205,9 +205,9 @@ class mainWindow(configBase.configWindowBase):
                        loadButton2 = wx.Button(self, -1, 'Load Dual')
                        self.Bind(wx.EVT_BUTTON, lambda e: self._showModelLoadDialog(2), loadButton2)
                if extruderCount > 2:
-                       loadButton3 = wx.Button(self, -1, 'Load Tripple')
-                       loadButton3 = wx.Button(self, -1, 'Load Triple')
                      self.Bind(wx.EVT_BUTTON, lambda e: self._showModelLoadDialog(3), loadButton3)
-               if extruderCount > 2:
-               if extruderCount > 3:
                      loadButton4 = wx.Button(self, -1, 'Load Quad')
                      self.Bind(wx.EVT_BUTTON, lambda e: self._showModelLoadDialog(4), loadButton4)

**Comment by daid** [comment]
Guess that's where my dutch shows :P

As for "correctly" submitting patches. You should look into forking and sending pull requests:
https://help.github.com/articles/fork-a-repo
https://help.github.com/articles/using-pull-requests

This works really great, as you can just work on the code, and send in a patch when it's ready. Then I can review the patch, place comments on it, and automatically merge it into the main codebase. It will also properly track you as the owner of a change :-)
