### ISSUE TITLE
Failed print: twice. Acelleration?

### ISSUE THREAD

**Issue by rewolff** [daid/LegacyCura#154]
I have my biggest print yet fail at ALMOST the same spot twice.... 

What I THINK cura is doing wrong, is that after doing some repositioning, it just issues the command to switch to normal speed again while at the same time issuing a move: 

G1 X62.336 Y61.771 E13.0278                 ; previous area to be filled
G1 X62.059 Y62.059 F15000.0                 ; quickly move to new area. 
G1 X63.406 Y63.406 F6000.0 E13.0534 ; and perform an extruding move there. 

If I read http://reprap.org/wiki/G-code#G1:_Controlled_move correctly, you're telling it to linearly decelerate from 15000mm/min to 6000 mm/min DURING the extrusion move. 
(the example above is taken at random from somewhere in the middle of the print. So here the extrusion move is only 2mm long: too short to reach 15000mm/min or maybe not even 6000 mm/min. )

Yes this is the first "serious" print where I seriously upped the movement speed. On the other hand, shorter experiments have shown that my ultimaker can perfectly handle these speeds without missing steps. 

Of course lots of things influence whether it will actually reach a "too high" speed. There are also acceleration limits that would limit the speed that can be obtained. It could very well be the place in my model where for the first time a longer extruding move follows a repositioning. Most models I've printed were smaller. Probably most things people print are smaller. 

The only way this could really be a problem is if a long extrusion straight-line follows a fast move. The tendency to start in a corner with the fill also helps hiding this. 

Maybe I can filter the G-code to see if it helps.

**Comment by daid** [comment]
I don't think the Marlin firmware does this acceleration as described on the RepRap wiki. I'll see if I can do some tests to see what is really happening. A simple test of:

G1 X0 Y0 F9000
G1 X200 Y0 F9000
G1 X200 Y200 F100

Should show if the final move in the Y direction is still going fast at the start or that it's going at 100mm/min

**Comment by rewolff** [comment]
You're probably right. 

I've now built the object and it went fine. I think it was a bowden tube plug.
