### ISSUE TITLE
Issus running on x86_64 Linux

### ISSUE THREAD

**Issue by andreynech** [daid/LegacyCura#155]
The issue and partial fix is documented here: http://wiki.ultimaker.com/Installing_Cura_on_Linux#Running_on_64bit_platform

In essence, there are two problems - 32bit PyPy packaged in to download tgz bundle and serial connection issue. I was able to overcome PyPy issue by removing packaged PyPy and installing "native" 64 bit PyPy. However the connection issue remains even using recommended 115200 baud rate setting. pronterface.sh is saying:
Connecting...
 Traceback (most recent call last):
   File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14665, in <lambda>
     lambda event: event.callable(_event.args, *_event.kw) )
   File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_controls.py", line 1850, in AppendText
     return _controls_.TextCtrl_AppendText(_args, *_kwargs)
   File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
     return codecs.utf_8_decode(input, errors, True)
 UnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 0: invalid continuation byte

I am running Ubuntu 12.04 LTS on x86_64 with Cura RC4.

**Comment by daid** [comment]
FYI: About the baudrate issue (found on the wiki), that's fixed for the next version (will be released soon). Cura will install a 115200 baud firmware if you run linux, and auto-detect whatever baudrate the firmware using.

Not sure how to solve the pre-packaged pypy problem.
But the pronterface problem is possibly due to a misconfigured baudrate in pronterface. I think it's recieving data from the serial interface that it cannot decode into text and then throw that error. (I do not maintain pronterface, I just package it with Cura, and I'm pondering about removing it as the Cura printer interface is pretty stable and has almost enough features in the next release. Originally it was packaged with Cura because Cura lacked it's own printer interface)

**Comment by david-venancio** [comment]
Hi from france and sorry to bring this:

still unable to slice with this config (ubuntu 12 on amd 64).
when I press "slice to gcode", cura 12 gives me this :

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in **bootstrap_inner
    self.run()
  File "/home/dv/data/ultimaker/cura/Cura/gui/sliceProgessPanel.py", line 138, in run
    p = subprocess.Popen(self.cmdList[self.fileIdx], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

(btw thanks a lot for the new version ! the baudrate problem is gone.)

**Comment by daid** [comment]
Most likely it's the same error as above. Replace the pre-packaged pypy version with the one from https://bitbucket.org/pypy/pypy/downloads/pypy-1.9-linux64.tar.bz2

While I do test under linux, it's one of the hardest platforms to package for, as there are 10.000 different installations. It's also the group with the most hackers from who I assume then they can get it to work.

**Comment by david-venancio** [comment]
I was already using pypy 64 but don't worry I'v found that installing ia32-libs-multiarch and pypy 1.9 32bits did the trick !
I'm sliciiiiinnnng ! ;D

Thanks a lot for your answer anyway ! (last sentence motivated me) >D

**Comment by fileoffset** [comment]
Ubuntu 12.12 64bit. Clicking the Print button would do nothing. I traced it back to a python library conflict with the 'power' module. To fix: remove or rename the installed power module (.py and .pyc, you can easily find it with: python -v; import power) then just install the correct power module.

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)

**Comment by andreynech** [comment]
Cura-13.11.2-debian.deb still has connection issue on 
Linux ux32vd 3.11.0-13-generic #20-Ubuntu SMP Wed Oct 23 07:38:26 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
Distributor ID: Ubuntu
Description:    Ubuntu 13.10
Release:    13.10
Codename:   saucy

After connecting USB cable, syslog says:

Nov 25 20:41:21 ux32vd kernel: [ 4004.469850] usb 3-1: new full-speed USB device number 8 using xhci_hcd
Nov 25 20:41:21 ux32vd kernel: [ 4004.488632] usb 3-1: New USB device found, idVendor=2341, idProduct=0010
Nov 25 20:41:21 ux32vd kernel: [ 4004.488644] usb 3-1: New USB device strings: Mfr=1, Product=2, SerialNumber=220
Nov 25 20:41:21 ux32vd kernel: [ 4004.488650] usb 3-1: Product: Arduino Mega 2560
Nov 25 20:41:21 ux32vd kernel: [ 4004.488655] usb 3-1: Manufacturer: Arduino (www.arduino.cc)
Nov 25 20:41:21 ux32vd kernel: [ 4004.488660] usb 3-1: SerialNumber: 64935343333351401192
Nov 25 20:41:21 ux32vd kernel: [ 4004.489021] usb 3-1: ep 0x82 - rounding interval to 1024 microframes, ep desc says 2040 microframes
Nov 25 20:41:21 ux32vd kernel: [ 4004.489495] cdc_acm 3-1:1.0: ttyACM0: USB ACM device
Nov 25 20:41:21 ux32vd mtp-probe: checking bus 3, device 8: "/sys/devices/pci0000:00/0000:00:14.0/usb3/3-1"
Nov 25 20:41:21 ux32vd mtp-probe: bus: 3, device: 8 was not an MTP device

Running Cuda with different baudrates produce different variations of the following message:

Log: Changing monitoring state from 'Offline' to 'Opening serial port'
Log: Connecting to: /dev/ttyACM0
Log: Connected to: Serial<id=0x3da6650, open=True>(port='/dev/ttyACM0', baudrate=19200, bytesize=8, parity='N', stopbits=1, timeout=2, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Log: Changing monitoring state from 'Opening serial port' to 'Connecting'
Log: Recv: ??????n???O???}????{>~?(|?8????_?.????????????f???F???ALba???
Log: Recv: f?
Log: Send: M105
Log: Send: M105
Log: Send: M105
Log: Send: M105
Log: Send: M105
Log: Changing monitoring state from 'Connecting' to 'Closed'
Log: Connection closed, closing down monitor
Closing down

**Comment by daid** [comment]
250000 baud is a pyserial issue, not a Cura issue.

**Comment by andreynech** [comment]
> 250000 baud is a pyserial issue, not a Cura issue.

Please refer to the log I've pasted in my previous response:
Log: Connected to: Serial(port='/dev/ttyACM0', baudrate=19200

It does not work for me with any baudrate, including 250000 .

**Comment by daid** [comment]
Baudrates have to match on both sides, your firmware talks a certain baudrate, and I try different values in Cura till I find the one that matches the firmware. If you firmware is talking 250000 baud then connecting is currently impossible from linux.

**Comment by andreynech** [comment]
Thanks for the hint. I've made the firmware upgrade (with first run wizard) right after installing new Cura, so I am assuming that the printer (Ultimaker 1 in my case) is running with firmware packaged with Cura. I do not know however, which baudrate the firmware is talking. So the questions are: is there any way to find out which baudrate is the packaged firmware talking and if it is indeed talking 250000 only, where to get one with lower baudrate?

**Comment by andreynech** [comment]
Just as a note - I do not have access to the printer right now, but as I remember, it was working fine on Mac on 115200. So I assume that the firmware at least can talk 115200. However, setting 115200 manually on Linux wiht the same firmware still does not work. 

I was also trying to set baudrate to lower values on Linux (in configuration dialog) and it does not work either with similar output.

**Comment by daid** [comment]
Then the log when trying to connect with 115200 baud might provide an insight.

**Comment by andreynech** [comment]
The log I've posted recently is the one where baudrate was set to 19200 (not auto). I am sure that I've tried the 115200 also with the same result but can double check it later today.

**Comment by andreynech** [comment]
Just out of curiosity - am I the only one on this list who has problems on Linux x64? Does anybody else already tried this configuration and can confirm that it works?

**Comment by daid** [comment]
So far you're the only one that I know off. But the amount of Linux Cura users is lower then Windows/Mac users. And most linux users seem to solve their own problems without telling the solution to me (which is a bit annoying sometimes)

Also, I think some of the linux users that use Cura to slice are using Pronterface to print, as pronterface gives some more control then Cura's printing interface.

**Comment by jgrin** [comment]
sudo pip install pyserial --upgrade

fixes this for me. Auto baud rate is not working but setting to 250000 will work with an upgraded pyserial.
