### ISSUE TITLE
Cura not able to use Mac USB full size keyboard's numeric key pad

### ISSUE THREAD

**Issue by StephenInoue** [daid/LegacyCura#1559]
Noticed that when I go to scale a model or any other action where I would enter a numeric value in cura's icon's for scale, rotate, etc that you are unable to see the numbers I'm typing. 

Can you find a USB wired keyboard with numerica pad and verify that the Mac Cura client is able to use the numeric keypad?

This would be a really nice feature to have and I'm not sure why Cura isn't supporting it in the preview window area for numeric entry. Please note that the numeric keypad works fine in the left hand column for basic, advanced, plugins and G-code.

**Comment by BagelOrb** [comment]
Try Cura 2. Cura 1.15 is not being developed any more....

**Comment by StephenInoue** [comment]
BagelOrb - Thanks! The old Cura's check for update said I was up to date, but I totally missed version 2. Thanks!

**Comment by BagelOrb** [comment]
@daid People are still on the old Cura because they don't know about a new one. Isn't it easy to give the mthe update to download the new Cura?

**Comment by daid** [comment]
@BagelOrb when we did that we were suddenly faced with terabytes of data transfers from China...

**Comment by BagelOrb** [comment]
@daid WTF?!

So... is that a good or a bad thing?
Doesn't that mean that a lot of users in China are using Cura?
Or is there something shifty going on?

**Comment by daid** [comment]
@BagelOrb Don't know the details, ask Jasper.
