### ISSUE TITLE
reset scale and mirroring on loading of model. 

### ISSUE THREAD

**Issue by rewolff** [daid/LegacyCura#156]
We've talked about it before. I know how it works. And it bit me again..... 

Friday we spent five minutes wondering why we didn't see anything when we loaded a new model. Previous model had been scaled up 41 times to come up to reasonable size. So now the new model was way too large. (turns out we were watching a smooth surface)......

Yesterday we started printing the owen-bowden-clamp. Today I find out that the threads are all the wrong way around. I had left the Y-mirror on. 

So... I understand that sometimes leaving the settings the same when loading the next model is a good idea: It is definitively good that both my base and the cap got mirrored. Just one of them mirrored and they wouldn't be usable. I can understand someone making a set of objects at 1.25 scale, and then having one or a few of them too small will not be fun. 

On the other hand when starting a new "project", it makes sense to reset it. 

Would it be possible to provide me with a bigger warning if I'm going to do it wrong?

I'm thinking a popup when the scale is not at 1.0 and/or one of the mirroring buttons is activated. But I hate popups. 

So when in the load-model dialog. How about a "load model and reset scaling and mirroring" and a "load model and keep scaling and mirroring"?

**Comment by daid** [comment]
I've added a none-intrusive popup, one that you can ignore and hides itself after 5 seconds. It think this serves the goal, as it doesn't disrupt your workflow but still warns you.
