### ISSUE TITLE
Cura can't display the 3D model

### ISSUE THREAD

**Issue by Otivy** [daid/LegacyCura#158]
Cura can't display the 3D model..just a black screen!

**Comment by daid** [comment]
Which OS? What video card do you have? Do you have DirectX and your latest video card drivers installed?

**Comment by Otivy** [comment]
Win7..ATI Mobility Radeon HD 4330          ...i'm gonna try again....
thanks!!

**Comment by daid** [comment]
Any results on the test?

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
