### ISSUE TITLE
PrinterMonitor never picks up "start" line

### ISSUE THREAD

**Issue by huetsch** [daid/LegacyCura#159]
There is a chunk of code in gui/printWindow.py:

```
   if line.startswith("start"):
     self.machineConnected = True
     wx.CallAfter(self.UpdateButtonStates)
```

This code is responsible for setting machineConnected to true. Only after such a boolean is true are we presented with the option to print via an active button. This code is never being triggered for me, as line = self.machineCom.readline() seems to be picking up info from the machine a little late.

Here is some sample output:

mark@localhost:~/src/Cura/Cura$ ./cura.py -r /Users/mark/Downloads/foo_export.gcode
Connecting to: /dev/tty.usbmodem641
Serial<id=0x104ead1d0, open=True>(port='/dev/tty.usbmodem641', baudrate=250000, bytesize=8, parity='N', stopbits=1, timeout=2, xonxoff=False, rtscts=False, dsrdtr=False)
14:01:30 +0200 - 414408b2d0fed428b55445f48b01d00932a7a92c | Autho2 X78.74 Y78.74 Z533.33 EFree Memory: 4498  PlannerBufferBytes: 1232

echo:Using Default settings:

echo:Steps per unit:

echo:  M92 X78.74 Y78.74 Z533.33 Estart

echo: External Reset

Marlin: 1.0.0 RC2

echo: Last Updated: Marlin-Thu, 12 Apr 2012 14:01:30 +0200 - 414408b2d0fed428b55445f48b01d00932a7a92c | Author: Build-Me-Marlin

echo: Free Memory: 4498  PlannerBufferBytes: 1232

echo:Using Default settings:

echo:Steps per unit:

echo:  M92 X78.74 Y78.74 Z533.33 E865.89

echo:Maximum feedrates (mm/s):

echo:  M203 X250.00 Y250.00 Z5.00 E45.00

echo:Maximum Acceleration (mm/s2):

echo:  M201 X9000 Y9000 Z100 E10000

echo:Acceleration: S=acceleration, T=retract acceleration

echo:  M204 S3000.00 T3000.00

echo:Advanced variables: S=Min feedrate (mm/s), T=Min travel feedrate (mm/s), B=minimum segment time (ms), X=maximum xY jerk (mm/s),  Z=maximum Z jerk (mm/s)

echo:  M205 S0.00 T0.00 B20000 X20.00 Z0.40 E5.00

echo:PID settings:

echo:   M301 P22.20 I1.08 D114.00

echo:SD init fail

ok T:28.08 B:0.00 @:0

ok T:28.02 B:0.00 @:0

ok T:28.29 B:0.00 @:0

Loaded: /Users/mark/Downloads/foo_export.gcode (188681)

As you can see, the initial start is not being picked up, and is later being sent on the line:

echo:  M92 X78.74 Y78.74 Z533.33 Estart

Presumably this latter start is being sent in response to an external reset, since the next line is:

echo: External Reset

Any idea what's going on here?

**Comment by huetsch** [comment]
My hack around this was just the following line:

if line.startswith("start") or line.startswith("Marlin"):

**Comment by daid** [comment]
You could check if this problem still happens if you set a baudrate in the preferences? I think I might know what's happening, as the auto-baudrate detection looks for the "start" line, but then reconnects (which should reset the machine, but that might not happen under linux)

**Comment by daid** [comment]
And thanks for the detailed report :D that really helps!

**Comment by huetsch** [comment]
Wow, thanks for the speedy response! I just started a long print, so once that's done I'll check it out and get back to you.

**Comment by huetsch** [comment]
I just tried. You're right - setting the baud rate manually avoids this problem.

**Comment by daid** [comment]
I think my patch will fix this problem, I'm toggling DTR to reset the machine after I auto detect the baudrate, in theory this should always make the start message show up again.

**Comment by huetsch** [comment]
I tried your new code, unfortunately the problem is still the same:

mark@localhost:~/src/gitcura/Cura$ python cura.py -r /Users/mark/Desktop/foo.gcode
Connecting to: /dev/tty.usbmodem641
Serial<id=0x1040b1b50, open=True>(port='/dev/tty.usbmodem641', baudrate=250000, bytesize=8, parity='N', stopbits=1, timeout=2, xonxoff=False, rtscts=False, dsrdtr=False)
Unknown M code:302
Unknown M code:82
 1:30 +0200 - 414408b2d0fed428b55445f48b01d00932a7a92c | Author: B8.74 Y78.74 Z533.3?: Free Memory: 4498  PlannerBufferBytes: 1232

echo:Using Default settings:

echo:Steps per unit:

Loaded: /Users/mark/Desktop/foo.gcode (795)
echo:  M92 X78.74 Y78.74 Z533.3?start

echo: External Reset

Marlin: 1.0.0 RC2

echo: Last Updated: Marlin-Thu, 12 Apr 2012 14:01:30 +0200 - 414408b2d0fed428b55445f48b01d00932a7a92c | Author: Build-Me-Marlin

echo: Free Memory: 4498  PlannerBufferBytes: 1232

echo:Using Default settings:

echo:Steps per unit:

echo:  M92 X78.74 Y78.74 Z533.33 E865.89

echo:Maximum feedrates (mm/s):

echo:  M203 X250.00 Y250.00 Z5.00 E45.00

**Comment by daid** [comment]
Then I'll see if I can reproduce this on my own linux install.

**Comment by daid** [comment]
(Should be fixed on latest versions, no longer depends on the "start" line)
