### ISSUE TITLE
Jog during print. 

### ISSUE THREAD

**Issue by rewolff** [daid/LegacyCura#160]
Sometimes during a print, I find that the Z axis needs a bit of tuning. Maybe I'll move my Z limit switch a bit later on after seeing that indeed with that movement the prints are better. 

So in the jog menu, during the print, I hit: "Z +0.1" and watch what happens.... 

In my case the print just went crazy. The head moved all the way to Y+ and started bumping into the side. I think that there is some synchronization missing between the jog command and the print-datastream going to the printer.

**Comment by daid** [comment]
That's odd. The jog commands should be disabled during printing! As they are not compatible with the print commands.
Is this on Windows/Linux or MacOS?

(The only way to adjust the Z during printing is by moving the Z screw by hand, don't fear it, the machine can handle it fine)

**Comment by rewolff** [comment]
Yeah, that's what I'm doing now. It took me a while to figure out what way to turn it (by then the machine had shown me..)

I would like to be able to jog using the controls: Then I can remember: OK. "0.2mm does the trick". and then adjust in the software the next run.

**Comment by rewolff** [comment]
I forgot to answer your question about what OS I'm on. I use Linux. 

I do not agree with your statement: 
      (The only way to adjust the Z during printing is by moving the Z screw by 
      hand, don't fear it, the machine can handle it fine)

For one you can keep track of the last Z-coordinate seen. Add an offset to each before sending. Of course then you need some G-code parsing which is probably not necessary at all until now....
