### ISSUE TITLE
libz2 cannot open shared object

### ISSUE THREAD

**Issue by ranska** [daid/LegacyCura#161]
when i click on 'slice to gcode' i have thi message

/home/user/Cura/linux-Cura-12.07/pypy/bin/pypy: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory

i am on ubuntu 12.04 and libz2-1.0 and libz2-dev are installed

**Comment by daid** [comment]
You might be running the 64bit version of Ubuntu, and the shipped PyPy with Cura is 32bit. See: https://github.com/daid/Cura/issues/155
