### ISSUE TITLE
Strange GCode generation for perimeter-wt

### ISSUE THREAD

**Issue by jcosmo** [daid/LegacyCura#162]
I have just sliced the perimeter-wt.stl found as part of http://www.thingiverse.com/thing:5573

A screenshot of the generated GCode can be found: http://www.flickr.com/photos/jasoncosmo/7555480128/in/photostream

This probably isn't a Cura problem as such, but perhaps a problem with steinforge?

**Comment by daid** [comment]
The perimeter-tw.stl is not a valid STL file. The x-ray view shows this quite clearly.

**Comment by jcosmo** [comment]
Ah - my mistake, I need to learn to use the full capabilities of Cura,
should have picked this up myself.

On 13 July 2012 00:35, daid <
reply@reply.github.com

**Comment by daid** [comment]
No problem. Especially with calibration STLs you would expect them to be correct, but they sometimes are broken.
