### ISSUE TITLE
Feature request: reload button. 

### ISSUE THREAD

**Issue by rewolff** [daid/LegacyCura#163]
Both in the printer window and in the main window a "reload" button sometimes comes in handy. I sometimes work on changing the model or g-code, and then use the cura mainwindow to visualize my changes. Now I have to go "file->load model-><select model> <ok>". It would be much quicker to just hit a "reload" button. 

Similarly, if I see a print go wrong (e.g. print off the area where I want it to print) I'll quickly modify the g-code and want to reload it in the printer window. No such luck: quit printing window, hit print in the main window, and re-enter the temperature I want....

**Comment by daid** [comment]
I actually had the idea to re-load the model file if the write-timestamp changes. Quite a few programs do this, and makes for an easy workflow without extra buttons.

The Printer window actually has a "load GCode" button, but it's invisible :P

**Comment by hugokernel** [comment]
Great idea, like OpenScad.
