### ISSUE TITLE
Feature request: print button feedback. 

### ISSUE THREAD

**Issue by rewolff** [daid/LegacyCura#164]
When I hit "print" in the cura mainwindow, and a printer window is still open, it will not give  me any feedback. It will only refuse to start a new printer window. So it knows that the printer window cannot be started. 

I'd prefer a popup saying: "can't print because print window is already open" over "the print button is grayed out and unclickable" when the print window is active. 

On the other hand, if this can be realized, graying it out, and having one of those help-popups pop up if you hoover over the button would be even better, I think.... 

(It's more difficult than I think if the printwindow actually DOES get started, but crashes/exits before it shows any visible output on the screen. In that case the mainwindow process probably doesn't know in advance whether the printer window will work....).

**Comment by daid** [comment]
You're right with your first guess, it already detects the open print window. The idea was to signal the print window that it should load a new GCode file (if not already printing), however I did not get that to work yet.

**Comment by rewolff** [comment]
You cannot/should not reload during printing. But... Be careful with this...... 

I might be printing "version 1" of a model, and want to restart that jobs from the print window. While in the mean while I'm slicing "version 2" of the same model. So the fact that the printer window has already loaded the full file means that I can do this.... It would "magically" start printing version 2 of the model when it would automatically reload on timestamp change.....

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
