### ISSUE TITLE
pypy crashes when slicing. 

### ISSUE THREAD

**Issue by rewolff** [daid/LegacyCura#167]
I've been seeing "python" in TOP output, and wondering if it was using pypy as planned or not. Today I saw output: 'can't find pypy using python instead". Ah! so I installed pypy today. Now on the second slicing job.... pypy crashes :-( 

File /home/wolff/3d/gears/motorhouder.stl is being chain exported.
Carve procedure took 1 second.
Preface procedure took 1 second.
Inset procedure took 5 seconds.
Fill procedure took 14 seconds.
RPython traceback:
  File "jit_metainterp_optimizeopt_optimizer.c", line 5699, in get_constant_box__pypy_jit_metainterp_optimizeop
  File "jit_metainterp_optimizeopt_unroll.c", line 26632, in UnrollableOptimizer_ensure_imported
  File "jit_metainterp_optimizeopt_optimizer.c", line 5399, in OptValue_import_from
Fatal RPython error: AssertionError

Does this give any clues as to what's wrong? Or do you need my model?

[update: pypy is still compiling. Will close when tested]

**Comment by daid** [comment]
Depending on which version of pypy you are using this is known to happen. It has nothing to do with the model, it's bug in pypy. You might need to get the latest nightly from: http://buildbot.pypy.org/nightly/trunk/

**Comment by rewolff** [comment]
Ok. Verified. Recent PYPY fixes this. I didn't try upgrading to 1.9 (I was using 1.8 from Ubuntu), but went all the way to the most recent sources in the repository.

**Comment by daid** [comment]
Great :-)

Some background info, I actually reported this bug to the PyPy project, and they managed to fix it within 2 weeks. Which was really awesome, because it was very hard to reproduce this bug. Early versions of Cura had this exact problem for lots of people.
