### ISSUE TITLE
temperature setting is not used in slicing in projectplanner. 

### ISSUE THREAD

**Issue by rewolff** [daid/LegacyCura#169]
My printer is starting to be reliable enough to print a "plate" of tests.

So to see what temperature works best, I've designed a plate with 6 test objects which I want printed at 6 different temperatures. 

So I've created 6 profiles with different temperature settings. But after slicing the plate in the project planner (with 6 different slicing profiles for each of the objects), the gcode only contains one "set temperature to the lowest test-temp" command. That of course is the "currently active" profile-temp, as I created the profiles from highest to lowest. 

I'll add them manually this time, but it would be nice to have at least an indication WHAT settings from the profile are NOT taken into account when slicing in the project planner.....

**Comment by daid** [comment]
The temperature setting is really the only one with this problem (and the machine center, scale rotate and mirror settings, but those can be configured in the project planner itself)

What normally happens, is that the temperature is inserted before the start code, but the project planner only has 1 start code, so the temperature is inserted there. I'll set this as a bug, as it's really a bug that it is not using the correct temperature for the correct models. And I can fix it.

**Comment by lancepickens** [comment]
Hi, I think this bug may still be active. Imported test objects manually into project planner and attached a custom profile to each of them. For each object, settings such as temperature or fan (on/off) are changed. In the resulting gcode for the test object array temperature and also fan settings are only set once instead of per object.

**Comment by daid** [comment]
Might be a new bug, quite a few things changed in the 13.01 and 13.03 release.
