### ISSUE TITLE
Feature request: heated bed temperature control 

### ISSUE THREAD

**Issue by GlenMcDouall** [daid/LegacyCura#171]
i don't know how easy it would be to implement, but it would be great to have control of temperature for those of us with heated build platforms, specifically it would be brilliant if it was possible to set the temperature for the first layer separately to the bed temp for the rest of the build, currently i do this manually and its a pain, i think this is an option within skienforge? its been a long time since i looked at it thanks to Cura, Slic3r has the option to do this but i dont like its g-code generation. 

Thanks 

Glen

**Comment by daid** [comment]
There isn't currently a setting for Bed temperature control, however, there is a bed temperature control in the printing interface.
You could add a manual M140 or M190 in the start code to heat up your heated bed.

As for "per layer config", I have some ideas for that. There are more things you want to do at specific layers, like adding pauses (so you can insert objects), changing temperatures or other fancy stuff that I did not think about yet but other people will.

Currently you can "hack" this into the "replace.csv" by placing:
  ;LAYER:1[tab];LAYER:1[tab]M140 S80
Into the replace.csv of the start/end code tab (use the tab key for [tab]). This will put the temperate of the heated bed to 80C at the 2nd layer. (layers start to count at 0)

**Comment by daid** [comment]
Fixed in 12.10 release.
