### ISSUE TITLE
Stange GUI menu issue

### ISSUE THREAD

**Issue by ConcreteTurtle** [daid/LegacyCura#172]
When I first start Cura 12.07, whatever menu item I select first persists on the desktop. 
It remains after closing Cura and is always "on top" of all other Windows. It is not selectable.

I'm running Windows 7 Ultimate 64 bit.

This issue was not present in RC4.

**Comment by daid** [comment]
Odd.

Could you provide a screenshot? So I better understand what is happening?

**Comment by ConcreteTurtle** [comment]
I will do, it seems like it might have something to do with the chrome
browser, because closing it clears the menu box.

Will get you a screen shot asap,
Angus.

On Mon, Jul 16, 2012 at 5:51 PM, daid <
reply@reply.github.com

**Comment by ConcreteTurtle** [comment]
Hello again,

Here is a screenshot of the issue:
https://dl.dropbox.com/u/9746129/Cura%20Screenshot.png
I can confirm that it seems to be related to Chrome, as once that closed
the floating menu item disappears.

Angus

**Comment by daid** [comment]
Problem  is local to your machine. No idea what's causing the bug for you. But it's not something in the Cura code so I'm closing this.
