### ISSUE TITLE
Missing Source File Name Tag

### ISSUE THREAD

**Issue by Bertho** [daid/LegacyCura#173]
In the start up code section please include a tag for the source file name used.  That is a critical piece of information.

It would also be useful with a tag for the G-Code creation Date-Time (not printing date-time) =When was it sliced.
Thanks for all your great work!!
Bertho

**Comment by daid** [comment]
Cura 12.07 already does this:

```
;Sliced /home/daid/OpenSCAD/3mm test.stl at: Tue 17 Jul 2012 09:34:11
```

The first line of the default start code is:

```
;Sliced {filename} at: {day} {date} {time}
```

**Comment by Bertho** [comment]
Hi Daid,
You are right!
I looked at my G-Code and the file name & date are missing.  
Tracing back, I probably created a problem merging an old profile with the new one since the tags are missing in the saved profile.
I am sorry for the false alarm.
I am very happy to see those tags.
Take Care,
Bertho

-----Original Message-----

**Comment by daid** [comment]
No problem. I was wondering myself if those made it into the release or not :p
