### ISSUE TITLE
Feature request: support upto a certain layer. 

### ISSUE THREAD

**Issue by rewolff** [daid/LegacyCura#174]
I'm trying to build the venus-head that's on thingiverse somewhere. (the actual STL is somewhere else due to copyright reasons). 

The bottom isn't completely flat though. So it tries building over half the bottom layer "in thin air". Just a few lines of support would allow the whole thing to build just fine. 

Enabeling support will cause lots and lots of support to be generated for things that build just fine without it. 

Feature request: 

The "enable support" toggle goes away and is replaced by: "Support below layer X". X = 0 means no support. a humungous number means all the way. (1200 is my largest build so far). 

In this case I'd enable support up to layer 2 or 3 and then it would build just fine. 

(I'm trying to patch it up in freecad, but loading the mesh goes fine, but "converting to a solid" takes hours, and then fails. )

**Comment by daid** [comment]
Instead of support, you could try to see if a raft solves your problem?

**Comment by rewolff** [comment]
Yes, I already tried that. The object is then still positioned ABOVE the raft with a space in between. And as the footprint is small, the raft too is small. So part of the object extends beyond the raft as well. 

I've had a flash of inspiration just before dinner yesterday. I've written an STL filter that will project all points beyond a certain X, Y or Z value onto the X (or Y or Z) = that value plane. Simple! I have not recalculated the normals. And as Cura ignores the normals anyway that is not an issue. 

This leads to the following "feature" that might come in handy for others as well: Allow slicing of the object FROM and TO a certain level. This will allow people to for instance print the Eiffel tower in pieces, without having to slice the STL of the object. This is a nice "generic" feature that would be useful for more people. (Also for people with a titan that need a slightly larger object. :-) )

**Comment by rewolff** [comment]
The problem: http://www.thingiverse.com/thing:24188 (Scaled ad 20%: prints, scaled at 30% fails). 
The fix for me: http://www.thingiverse.com/thing:26980

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
