### ISSUE TITLE
main window does not dynamically size correctly

### ISSUE THREAD

**Issue by DavidGoodenough** [daid/LegacyCura#177]
The main Cura expert window defaults to a size which overflows my screen.  So I can not get (without moving the window) to the X to cancel slicing operations.  It will not allow me to reduce the width.  This also applies when I maximize the window, which should cause it to fill all of the available space on the screen (except the task bar), but it still overflows the screen.

For narrow screens, how about a preference which allowed the expert window to have a single column on the left hand section rather than the dual column currently used.

**Comment by daid** [comment]
Are you running Cura on a netbook or something? I've yet to see a screen that was too small not to fit.

Release 12.07 increased the size of the window a bit, to get a cleaner look. But if you want it to start out smaller, you can also hack line 38 of "gui/preview3D.py", which controls the minimal size of the 3D window.

**Comment by DavidGoodenough** [comment]
Content preview:  On Tuesday 17 Jul 2012, you wrote: > Are you running Cura
   on a netbook or something? I've yet to see a screen > that was too small not
    to fit. > > Release 12.07 increased the size of the window a bit, to get
   a cleaner > look. But if you want it to start out smaller, you can also hack
    line 38 > of "gui/preview3D.py", which controls the minimal size of the 3D
    window. > > --- > Reply to this email directly or view it on GitHub: > https://github.com/daid/Cura/issues/177#issuecomment-7036790
    I am running on a boring old VGA 1024x768 screen on Linux. If the window
   is aligned on the left side of the screen, I can see the minimize icon but
    not the maximize and close icons. [...] 

 Content analysis details:   (-2.9 points, 5.0 required)

  pts rule name              description

---

 -1.0 ALL_TRUSTED            Passed through trusted hosts only via SMTP
 -1.9 BAYES_00               BODY: Bayes spam probability is 0 to 1%
                             [score: 0.0000]

On Tuesday 17 Jul 2012, you wrote:

> Are you running Cura on a netbook or something? I've yet to see a screen
> that was too small not to fit.
> 
> Release 12.07 increased the size of the window a bit, to get a cleaner
> look. But if you want it to start out smaller, you can also hack line 38
> of "gui/preview3D.py", which controls the minimal size of the 3D window.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/daid/Cura/issues/177#issuecomment-7036790
> I am running on a boring old VGA 1024x768 screen on Linux.  If the window
> is aligned on the left side of the screen, I can see the minimize icon
> but not the maximize and close icons.

David

**Comment by daid** [comment]
Ah, that explains it. The layout under Linux and MacOS is larger then the same layout in Windows. (I do test for Linux on my work PC, but there I have a 1280x1024 monitor)

I'll have a look to see if I can pull some trickery to make it fit on smaller monitors. There is also a 35 pixel border in gui/configBase.py, removing that should also give you enough room.
