### ISSUE TITLE
Feature request: generic G-code. 

### ISSUE THREAD

**Issue by rewolff** [daid/LegacyCura#179]
When slicing to G-code, some things influence the slicing in an essential way. Infill percentage, slice height. 

Some however do NOT change the slicing in an essential way. Filament diameter, speed-while-extruding, speed-while-traveling, retraction. 

It would be nice if the normal "slice" operation does all the "essential" stuff. And a post-processing step does the non-essential stuff. This is an intermediate step for the eventual "goal situation" where the "send-stuff-to-the-printer" program can adjust all the non-essential parameters on the fly. As is now already the case for speed. 

The "file format" between the "essential" and the "non-essential" postprocessing step is what I call "generic G-code". For ease-of-implementing it would just emit G-code like now. But maybe based on 100mm/s print speed.

**Comment by daid** [comment]
Would be nice, but impossible with the current implementation.

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
