### ISSUE TITLE
FR: bridging

### ISSUE THREAD

**Issue by jgeerds-zz** [daid/LegacyCura#18]
If SF has a bridge plugin, please incorporate it into the advanced settings of SPP.

Why we need this:
My last object has 2 sections that would have needed slooooow printing and extra extrusion to make a proper bridge... instead, 150mm/s at 0.1mm was way too fast, and way to thin to make a bridge (with my current profile). so the results are a bit "unsatisfactory"

**Comment by frollard** [comment]
+1

Bridge is very helpful!

**Comment by daid** [comment]
And it's done. In the advanced config you can now set the bridge speed and bridge material amount.
