### ISSUE TITLE
Feature Request: "Brim"

### ISSUE THREAD

**Issue by daid** [daid/LegacyCura#180]
Brim is a new feature found in Slic3r, it puts extra outlines on the outside of the first layer to improve adhesion and reduce warping. It would be nice to add this to Cura as well.

**Comment by jgeerds-zz** [comment]
One work around would be setting the skirt distance to 0, and print as many skirts as possible... in the long run, if you allow negative distance for the skirt, it'll ensure that the skirt (brim) actually connects to the object, something like 0.25mm would probably do the trick.

**Comment by daid** [comment]
Actually, you need to set the skirt distance to -0.4 (I just tried, yes it makes Cura turn red, but it works). But then you still have the "skirt is convex" problem. And it only does a brim on the outside, not on internal corners. So if you have an hollow L shape, the internal corner might still curl upwards.

**Comment by mfeherpataky** [comment]
Hi guys. 

Sure skirt does work this way on some objects and given they are printed solo. It helps with some designs and to limited extent. Brim is a must now.

I love quality Cura generates at the speed it does. Before finding it  I was happy with slic3r - now it is hard to look at the awesome lines of Cura generated objects and needing to print with slic3r still, as it has brim and cura does not.

I tried also this http://www.thingiverse.com/thing:16728 - an openscad script generating a brim like structure. But it only works for objects with a closed outline.

**Comment by daid** [comment]
Sorry, I kinda forgot about this feature for a while (so much to do). It's back on my list now. (Thanks for the reminder!)

**Comment by FreezeS** [comment]
Sorry to be bugging you, but I subscribe to everything mfeherpataky said. Unfortunately for me, this is a dealbreaker with my printer's hotbed adesion :(

**Comment by daid** [comment]
Secret news! Cura 12.11 has brim, not really as option, but if you set the skirt distance to zero (0.0) and the amount of lines to 5 or 6, it will act as a brim. Some special code kicks in when you set the distance to zero which will make the skirt act as a brim.

I know this is not the clearest feature, so I'm leaving this request open, but it should no longer be a dealbreaker =)

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
