### ISSUE TITLE
Command line startup

### ISSUE THREAD

**Issue by servant74** [daid/LegacyCura#184]
I would like to pass an STL file as an argument to CURA during startup (running of cura.sh) in linux.

This would allow associating file extension of stl to cura so cura can be the 'default' to open stl files, without having to go through a selection menu's.

Enhancement request.

**Comment by daid** [comment]
Currently you can give an STL on the command line (if you start python directly, without the cura.sh), but this starts the slicing process, it does not open the STL inside of Cura as you want.

I do think this is a good idea, also for other OSes.

(Note: you can already drag&drop STL files into Cura)

**Comment by servant74** [comment]
Thanks for the quick response.  I would rather see a 'generic' or 'all user platform' solution in the long run, even if it was with a different script or using specific arguments (like -f or /f to indicate 'file' input).
