### ISSUE TITLE
some comments are not filled

### ISSUE THREAD

**Issue by rooiejoris** [daid/LegacyCura#187]
hi,

in the gcode i don't see the values, but i see this after slicing:

...
;Print time: #P_TIME#
;Filament used: #F_AMNT#m #F_WGHT#g
;Filament cost: #F_COST#
;...

cura 1207 on mac

**Comment by daid** [comment]
Are you slicing from the command line by any chance?

**Comment by rooiejoris** [comment]
Nope...

**Comment by daid** [comment]
Odd, normally these tags get replaced after slicing by Cura's main interface (which is why you will see the tags if you slice from the command line)

**Comment by daid** [comment]
Note, these tags only get replaced in the first 2048 bytes of the file, maybe you've made a ridiculously long start code?

**Comment by smorloc** [comment]
rooiejoris, were you doing a "batch run"?  In all versions of Cura up to and including 12.12, Cura does not replace those values for files produced through "batch run".

**Comment by rooiejoris** [comment]
> > Are you slicing from the command line by any chance?

I had the same problem again last week, but that was from command line...
is that still an issue...?!

@smorloc: I am not sure anymore about batch runs or not...

**Comment by nophead** [comment]
I get this problem slicing in the GUI with the lines from the default start.gcode.

;Generated with Cura_SteamEngine 13.06.4
;Sliced at: Sun 04 Aug 2013 17:47:34
;Basic settings: Layer height: 0.4 Walls: 1.2 Fill: 20
;Print time: #P_TIME#
;Filament used: #F_AMNT#m #F_WGHT#g
;Filament cost: #F_COST#
