### ISSUE TITLE
Spacing between lines in support structures

### ISSUE THREAD

**Issue by jenschr** [daid/LegacyCura#188]
In Cura - adding supports basically is a on/off thing and the supports are pretty much as I want them. There's one tiny tweak I'd love to have -> tweaking the distance between the lines as to make the supports even sparser. Is this easy to add?

**Comment by mikeq3** [comment]
I would also like to see this setting made adjustable in Cura. It is the interface layer density parameter in the raft module.

**Comment by Karijn** [comment]
I'm also really hoping for this feature

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
