### ISSUE TITLE
Copy To SD Card

### ISSUE THREAD

**Issue by emtemt** [daid/LegacyCura#191]
Hi

Small issue with similar file names. EG PCBmountMain and PCBmountAux.

If you copy to SD the first file ends up PCBmount.g. If you then copy to SD the second file it overwrites the first file. Could a duplicated truncated name be changed to say PCBmoun2.g?

Regards

**Comment by JelleB** [comment]
The usual solution was to include a tilde in the name and append an index number, so it would be PCBmou~2.g

**Comment by daid** [comment]
The problem would be when to know when to override and when not. What if you copy PCBmountMain twice?

The real solution will come in a firmware update (I hope, working on it)

**Comment by emtemt** [comment]
Is that a real problem? Highest number will be most recent version. Easy 
to delete earlier versions if you need the space on the SD.

On 14/08/2012 00:22, daid wrote:

> The problem would be when to know when to override and when not. What 
> if you copy PCBmountMain twice?
> 
> The real solution will come in a firmware update (I hope, working on it)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/daid/Cura/issues/191#issuecomment-7711618.

## 

Regards

Ian Eagland
Eagland Machine Tools Ltd
http://www.eagland.co.uk/

**Comment by daid** [comment]
Note that I added long filename support in Marlin, so if you run the latest Marlin development version you no longer need to use the short filename option.
