### ISSUE TITLE
Slicing failure (Win7, Cura 12.08, no nonASCII)

### ISSUE THREAD

**Issue by EFinley** [daid/LegacyCura#193]
I finally just got Cura to work (I'd been trying to use my Python 2.6, and 12.08 fails on it, that's a different issue), but am getting a "Something went wrong during slicing!" error when I try to generate GCode.

There are no non-ASCII characters in the file path, neither to Cura, Python, nor even the STL itself (I copied it to the Cura directory to make sure).

The log reads:

> Traceback (most recent call last):
>   File "app_main.py", line 51, in run_toplevel
>   File "C:\Python27\Cura_12.08\Cura\cura.py", line 19, in <module>
>     from util import sliceRun
>   File "C:\Python27\Cura_12.08\Cura\util\sliceRun.py", line 3, in <module>
>     import platform, os, subprocess, sys
>   File "C:\Python27\Lib\subprocess.py", line 418, in <module>
>     import msvcrt
>   File "C:\Python27\Cura_12.08\pypy\lib_pypy\msvcrt.py", line 10, in <module>
>     import ctypes
>   File "C:\Python27\Lib\ctypes__init__.py", line 461, in <module>
>     GetLastError = windll.kernel32.GetLastError
>   File "C:\Python27\Lib\ctypes__init__.py", line 378, in **getattr**
>     func = self.**getitem**(name)
>   File "C:\Python27\Lib\ctypes__init__.py", line 383, in **getitem**
>     func = self._FuncPtr((name_or_ordinal, self))
>   File "C:\Python27\Cura_12.08\pypy\lib_pypy_ctypes\function.py", line 250, in __init__
>     ptr = self._getfuncptr([], ctypes.c_int)
>   File "C:\Python27\Cura_12.08\pypy\lib_pypy_ctypes\function.py", line 437, in _getfuncptr
>     return cdll.getfunc(mangled_name,
> AttributeError: 'CDLL' object has no attribute 'getfunc'

**Comment by EFinley** [comment]
Further update:  It appeared at first that this was an artifact of maintaining the two Python installations and having to keep a single PYTHONPATH which referred to them both, since although at first when I installed 2.7 Cura worked without further package downloads, when I removed references to C:\Python26 from my PYTHONPATH, the same dependency issues (pyopenGL, wxPython, pyserial) came up again - obviously it had been looking at the wrong ones.

However, I've now fixed that, going so far as to remove Python 2.6 altogether.\*  And reinstalled those dependencies in their correct 2.7 versions.  Which gets Cura back to being willing to launch.

...and then giving me the same slicing error as above.  Looks like something is up with the pypy install, maybe?

I've also tried installing Cura 12.07 but the result is identical.
- Note - this Python 2.6/2.7 issue (which, looking at the closed issues here, it appears daid already has identified, something to do with named environment variables) is of more than trivial importance, because there's gotta be a lot of overlap between Blender users and Ultimaker owners - certainly much more than one would expect through random chance - and for those like myself who use Blender scripting, Blender 2.49b remains the release of choice... and it requires Python 2.6 exactly.  Not that, apparently, this would actually fix my problem here. :(  But it's still worth noting as being more impotant than it seems.

**Comment by EFinley** [comment]
Aha!  Issue solved.  The problem lies in the interaction between the "everything included" Windows installer, and preexisting Python installations, full stop.  It's looking at the wrong files, the non-PyPy ones, due presumably to the extant PYTHONPATH or just plain system path.

Having removed Python 2.7 as well as 2.6, then installed Cura 12.08 directly, it seems to be working fine.  I'll leave this open so that (a) daid can confirm that he's seen it and can at least consider dealing with the entanglements there (maybe even just have the cura.bat file set its own environment variables?), and (b) I can add any notes that come up when I try to put Python 2.6 back /on/ my system, so that Blender'll work too.

**Comment by daid** [comment]
Interresting, I have Python2.6 and Python2.7 and Python3.1 installed on my WinXP system which is not causing these kinds of problems. But I'll have some tests with the PYTHONPATH environment variable.

**Comment by EFinley** [comment]
Yeah, I've got 2.6 & 2.7 back up and running in conjunction with it just 
fine, so far.  I /think/ it may have to do with the (in retrospect 
foolish) decision to avoid cluttering my root directory by tucking Cura 
into a related already-in-root-directory-with-no-spaces directory... and 
choosing Python27 for that purpose.

At any rate, it's dealt with now, and overall I'm very happy with Cura - 
thank you!  I have a couple of feature requests I'll put up on the 
tracker when I get time, in particular the ability to put objects /not/ 
dead center (without having to use the Project Planner), but they're 
minor, and overall I'm really happy.

I do have one question, though, with regards to PrintRun.  I am testing 
a syringe extruder, and running up against "Head not at temperature" 
errors when I try to power the syringe through the Bowden tube.  Is 
there any way to disable this check?

Thanks,
- Eric F.

**Comment by daid** [comment]
You can move the object position with the machine center X and machine center Y settings.

If you want to disable the cold-extrusion prevention, there is an M code for it, I think it was M301, but you'll have to look at the Marlin documentation to be sure.

**Comment by EFinley** [comment]
Thanks - the former hadn't occurred to me.  I actually just went to your 
firmware builder and, indeed, the min-temperature is a setting there, so 
I just built a firmware for myself without it.  The M-code is probably a 
better long-term solution, but this works.

Cheers!
- E

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
