### ISSUE TITLE
Incorrect slicing

### ISSUE THREAD

**Issue by jenschr** [daid/LegacyCura#194]
I'm currently making some big extruded letters and I've found what must be a bug. The letter "b" has a rather long stretch, so to support the thin walls, I'm making a series of bridges over to the other parts of the model. In most cases, these will slice correctly, but sometimes, the slicer will think that it needs to add a solid layer where there should be none.

With "Expert Config -> Solid infill top" turned off, the slicer does not add a solid layer to the bottom of the model. You can easily see that the hex-patterend infill is not covered:
http://flashgamer.com/a/cura/cura_sliced_incorrect_top.jpg

The error then repeats further up in the model:
http://flashgamer.com/a/cura/cura_sliced_incorrect_tops_all.jpg

If I toggle "Expert Config -> Solid infill top" turned on, the bottom layers will be closed, but there will always be one layer that has a partial 100% infill somewhere towards the top of the model. Changing the geometry will just change where the bug occurs. The only way to not get the bug is to remove all the supporting bridges and that won't work for this model.

I have confirmed that the bug is the same in RC3, 12.07 and 12.08.

**Comment by daid** [comment]
Most likely it's a strange rounding bug, maybe your STL files contain too much detail and you should reduce the polygon count?

**Comment by jenschr** [comment]
It could be, but I've done some tests on this today. I generally export with 0.1 mm precision. This creates huge STL files, but curves are always smooth/round. Now I tried with 0.3 and 0.5mm precision. The model them showed artifacts, but the problem still remained.

Stupid me didn't include the link to the STL initially, so here you go:
http://flashgamer.com/a/cura/bb2.stl (0.1mm)
http://flashgamer.com/a/cura/bb5.stl (0.5mm)

Should be easy to confirm.

**Comment by daid** [comment]
I'm seeing the same issue for those models. Not sure what is causing it. You could try making the walls slightly thicker, the software has some difficulties with thin walls.

**Comment by jenschr** [comment]
Thicker walls seem to solve it, but KissSlicer managed it without a problem -> you can't be satisfied with that? ;-)

**Comment by daid** [comment]
Well, there is little I can do about it right now. The part of the code that does this is not made by me, very complex, and written in the 7th circle of hell.

**Comment by jenschr** [comment]
lol. yeah. I was afraid of that... Just wanted to check
