### ISSUE TITLE
Minimum material feed for retraction

### ISSUE THREAD

**Issue by Drachenkaetzchen** [daid/LegacyCura#196]
Sometimes, the same piece of filament gets retracted multiple times, which causes the filament to stuck. An option should be introduced where a user can force a minimum material feed before another retraction happens.

I hope this is clear - if not, I can write a verbose example of the problem.

**Comment by daid** [comment]
I understand the issue. I've also seen it happen on prints with lots of small parts and lots of retraction.

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
