### ISSUE TITLE
Projectplaner doesnt slice

### ISSUE THREAD

**Issue by Bito** [daid/LegacyCura#198]
Im using Cura 12.08 and always when i trie to slice something with the planner i get the following massage:

Traceback (most recent call last):
  File "F:\Ultimaker\Software\Cura_1208\Cura_12.08\Cura\gui\projectPlanner.p
y", line 592, in OnSlice
    action.sliceCmd = sliceRun.getSliceCommand(item.filename)
  File "F:\Ultimaker\Software\Cura_1208\Cura_12.08\Cura\util\sliceRun.py", l
ine 171, in getSliceCommand
    cmd = [pypyExe, mainScriptFile, '-p', profile.getGlobalProfileString(), '-s'
]
  File "F:\Ultimaker\Software\Cura_1208\Cura_12.08\Cura\util\profile.py", li
ne 257, in getGlobalProfileString
    ret = '\b'.join(p) + '\f' + '\b'.join(alt)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 761: ordina
l not in range(128)

**Comment by daid** [comment]
And normal slicing does work?

**Comment by Bito** [comment]
yeah, only the project planner doesnt work.

**Comment by Bito** [comment]
Any suggestions why there is this error message?

**Comment by daid** [comment]
The error is generated at the part which generates the "profile string" this is an encoded string which is passed between the GUI frontend and the backend slicing process.

For some reason it sees a "none ascii" character in the profile. Which I find odd, as this code is the same for normal slicing and project planner slicing.

**Comment by Bito** [comment]
Maybe i need to go back to version 12.07? Cause i need the planner for some overnight prints.

**Comment by Bito** [comment]
Tried Version 1208 on another notebook and got the same error message. Now i went back to version 1207 and project planner works. So it seems that there has been changed something between 1207 and 1208 that causes this error.

**Comment by daid** [comment]
The only change I know I did on the project planner is:
https://github.com/daid/Cura/commit/e4c6f0cb227ada8b9cd0e4fe1c13a6bfc18200b0

Are you using "per object profiles" or just putting in some objects and slice those with the profile you have in the main window?

**Comment by Bito** [comment]
Seems that my custom start.gcode causes these errors. when i use the default values the planner works well, when i use custom ones i get the error message.

Here is my custom start code:

;Sliced {filename} at: {day} {date} {time}
;Basic settings: Layer height: {layer_height} Walls: {wall_thickness} Fill: {fill_density}
;Print time: {print_time}
;Filament used: {filament_amount}m {filament_weight}g
;Filament cost: {filament_cost}
M92 E856.4668
G21        ;metric values
G90        ;absolute positioning
M107       ;start with the fan off
G28 X0 Y0  ;move X/Y to min endstops
G28 Z0     ;move Z to min endstops
G92 X0 Y0 Z0 E0         ;reset software position to front/left/z=0.0
G1 Z15.0 F{max_z_speed} ;move the platform down 15mm
G1 X{machine_center_x} Y{machine_center_y} F{travel_speed};go to the middle of the platform (disabled, as there is no need to go to the center)
G1 F{travel_speed}
G92 E0                  ;zero the extruded length
M109 S210         ;heat up to 210°C and wait until temp is reached
G1 F100 E5
G1 F200 E3.5
G92 E0                  ;zero the extruded length again                 ;zero the extruded length again

**Comment by daid** [comment]
"210°C" <- there. The ° is most likely the troublemaker. Looks like it doesn't accept "strange" characters in the start code, not even in the comments.

**Comment by Bito** [comment]
You are right, that was the problem. Thanks for your help!

**Comment by daid** [comment]
I'm reopening this, because I do think this is a bug and Cura should accept those characters. But I'm glad you can slice again :-)

I also find it very interresting that this bug does happen with the project planner but not with the normal slicing (I can reproduce it now)
