### ISSUE TITLE
Issue installing development version of Cura on Win7x64

### ISSUE THREAD

**Issue by theodeyle** [daid/LegacyCura#202]
I am installing the development version of cura as outlined in the wiki: 
Install Stable version, delete Cura folder, extract contents of development version into folder.

and I get the following error:

return _core_.GridBagSizer_Add(_args, *_kwargs) 
wx._core.PyAssertionError: C++ assertion "!CheckForIntersection(item)" failed at ....\src\common\gbsizer.cpp(225) in wxGridBagSizer::Add(): An item is already at that position

What am I doing incorrectly?

I have tried to clone the files straight from Git, but same result as above.

**Comment by theodeyle** [comment]
I took another look at the error. Looks as though it is an error when you first start the program and thus, the configuration wizard.

I took my preferences that I saved in the stable version and pasted them to the development version. It works.

**Comment by daid** [comment]
This indeed was a bug in the development version.
