### ISSUE TITLE
Stacking Printing windows might confuse 

### ISSUE THREAD

**Issue by peteruithoven** [daid/LegacyCura#205]
The Cura 12.08 version of Cura seems to stack the Printing windows. This might cause people to reprint the same gcode unintentionally. (What I just did) Some possible suggestions:
- Update the same window when there is new GCode
- Add some indication of which gcode it is, possibly by displaying a "generated at" time.
- Place new windows slightly lower and more to the right. 
- Add a clear "completed" message in the window.

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
