### ISSUE TITLE
Display Real World Dimensions

### ISSUE THREAD

**Issue by rmccaskill** [daid/LegacyCura#207]
Feature request:

When you load an STL into Cura, it would be great to have a place to see the real world dimensions (L x W x H) in cm of the piece.

This would be especially useful after using the 'model scale' functionality so that you know how big / small it will be after the scaling.

**Comment by daid** [comment]
Yes, would be useful. I'm going to redesign the 3D view a bit anyhow.

But note that the "floor" of the printer is a 10x10mm grid, so you can estimate sizes from there.

**Comment by rmccaskill** [comment]
Good point. 

I've had a few instances of people sending me 3D files to print. They're expecting them to be a certain size. I load them up in Cura and they're TINY! (or huge). They only way I've figured out is to import them into blender, switch blender into 'Metric', set the scale to 0.001 then resize the object and re-export. Seems to work.

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)

**Comment by rmccaskill** [comment]
Yes, correct! The real world dimensions are now displayed over the model when you are in 'scale' mode. You can also use scale mode to input exact real world dimensions.

It's excellent, thanks!
