### ISSUE TITLE
Display z coordinate in "Layer View"

### ISSUE THREAD

**Issue by polar223** [daid/LegacyCura#209]
I would be nice to have the z-coordinate information (numerically, not just the green bar) of the layer currently displayed in the Layer View.

**Comment by daid** [comment]
There is no green bar in Cura. The green bar is most likely from Pronterface, which is a different software package.

**Comment by polar223** [comment]
you are right of course :)

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
