### ISSUE TITLE
Mark actual Layer in Gcode

### ISSUE THREAD

**Issue by Bito** [daid/LegacyCura#21]
I have mentioned that there is some commentary in generated GCode i.e. ";TYPE:WALL-INNER". Would it be possible to mark the actual layer number i.e. "begin layer xx".

Thanks
Bito

**Comment by daid** [comment]
Yes. I was thinking about this myself as well.
The simple GCode comments serve multiple goals, first I added it to make the GCode preview easier to look at.
Secondly, they will serve a goal for a feature not yet made, which is advanced realtime-tuning.
Finally, they should make it easier to edit the GCode by hand.

Having layer comments would make the GCode preview easier to code (now it gets confused if you enable the "Joris" action)
It would make it possible to tune layers later on.
And finally it would make manual editing easier.

So I better get to work then!

**Comment by daid** [comment]
I've added ";LAYER:xxx" comments to the output gcode. Should make it possible to find the layer you are looking for.
It's also easy to parse from scripts.
