### ISSUE TITLE
Lots of useless moves  when printing a thin-walled box (cura 12.07)

### ISSUE THREAD

**Issue by MoonCactus** [daid/LegacyCura#210]
Got a big amount of useless moves on this print (1.2 mm walls, 0.2 mm thickness, 0.4 mm nozzle)

The head keeps on going forth and back along the walls, may be up to 20-50% of the print time.

You will find the STL, GCODE, cura INI file and openscad source here:
http://cpadi.com/static/bugreports/printing_cura_spurious_moves_12.07/

There is also a picture and a short video that let you see when the extruder is extruding or not (as usual, it also goes faster when not extruding)

This was running cura 12.07

**Comment by MoonCactus** [comment]
Update: may be "not a bug" (in which case, sorry for the post)

I suspect that the head just goes and drops a bit of plastic at each of the corners of the box since I added thin reinforcemet columns there. So it would be only a matter for me to set properly the wall thickness may be.

Still I would love not to see such as weird path on this object, because it seems as there are 2 consecutive passes for filling the corner columns where I would understrand 1 only.

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
