### ISSUE TITLE
Missing *.g filetype when opening profile from gcode

### ISSUE THREAD

**Issue by flouSH** [daid/LegacyCura#211]
In the latest Windows version (others as well I would assume) it's not possible to open *.g files from the filemanager menu when trying to extract a print profile from gcode.

--> Add *.g filetype or allow "All filetypes"

--> Please delete this, if already mentioned - didn't find anything on this in a quick search.

Cheers
Flo

**Comment by daid** [comment]
.g files are deprecated with the new Marlin firmware anyhow, because the firmware now supports long filenames.

**Comment by flouSH** [comment]
Ok! So we could close it - or do you want to fix it anyways?

**Comment by daid** [comment]
I might as well just add those few extra bytes of code ;-)
