### ISSUE TITLE
Support does not change

### ISSUE THREAD

**Issue by Mowi** [daid/LegacyCura#212]
No matter what support settings I use the support looks always the same. When I  change the "support type" and 'support material amount' and slice to gcode the preview looks the same as the previous. 
If I change "Support distance from object" I do see a change .

**Comment by daid** [comment]
"Support type" changes where support material is generated. "Support material amount" should make the lines thicker or thinner (but still the same paths)

**Comment by Mowi** [comment]
If I change the support material from 'everywhere' to 'outline only' it stays on the same spot.
It seems to me it will print way to much support, the raster is much tighter than I need, I'm afraid it will be a hassle to get it off. But I'll try it, maybe it is much easier than I imagine.

**Comment by daid** [comment]
It says "exterior only", which means it will only generate support that will hit the base platform. With "everywhere" it will also make support that hits other parts of the model. There is no setting to configure the spacing, but it should be quite easy to remove.

**Comment by Mowi** [comment]
I printed it with support material amount at 20 and I got a spongie like support, The high support was pretty easy to get of, it was about 8mm high. The low support of 1mm height is very hard to remove. All in all the part is usable so I will move on to other models waiting to be printed. They do not need support so I will take a break from experimenting with support untill next time I need it. Thanks for your help!

**Comment by mikeq3** [comment]
Actually on the regular skeinforge you can affect support material density in the raft module by adjusting 
Interface Infill Density (ratio). Even if you have the interface layer set to zero layers, the Interface Infill Density (ratio)
Will affect the support density.

**Comment by daid** [comment]
Which is as always the "True Skeinforge Way", a totally stupid way to adjust it. I know you can do it like that, but it doesn't make sense that 2 unrelated things change with 1 parameter. And adjusting the material amount for the support (default 50%) already makes for pretty good and easy removable support.
