### ISSUE TITLE
Travelpath optimization

### ISSUE THREAD

**Issue by Bito** [daid/LegacyCura#213]
As I already mentioned it this thread http://groups.google.com/group/ultimaker/browse_thread/thread/bb70e9345e33144/710868247ffd996f?lnk=gst&q=zig#710868247ffd996f there is still the problem of rough inner surfaces, caused by the incorrect travel path of the nozzle. Cura already detected the solid structures of the part and print these paths. Why cant this path be remembered and used to move from A to B?

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
