### ISSUE TITLE
End switch not supported in jog mode

### ISSUE THREAD

**Issue by tecnao** [daid/LegacyCura#215]
Hi, it seems that in the jog mode (after choosing "print Gcode") the switches aren't checked : if I manually switch on  any X or Y axis switch, the jog features is still functionnal in every direction. Too bad, I just wanted to check these switches using this simple feature.

**Comment by daid** [comment]
Actually, it's the firmware that is ignoring the endstops, not Cura itself. (Feature of Marlin, which is called "enable endstops only for homing")
The Ultimaker firmware I ship with Cura always checks the endstops and thus then this should work. However, not everyone is using an Ultimaker with Cura.

So, you can also use the M119 command in the terminal. This reports the status of your endstops, so hold down an endstops, give the M119, and you'll see if it's working and wired up correctly.
