### ISSUE TITLE
Wrong dimensions on reprap bar-clamp

### ISSUE THREAD

**Issue by darkomen** [daid/LegacyCura#218]
Hello,

When slicing the barclamp stl (http://asrob.uc3m.es/svn/ASROBrepo/3DP/Clon-wars/Prusa-iteration-2/Parts-stl/01-bar-clamp-x8.stl) The interior hole is considerable smaller than when slicing (and printing) with skeinfoge. In fact, with skeinforge it comes about 7.8 mm. With cura about 7.3 mm (diameter)

The real dimension of hole is 7.9 mm. Have someone the same problem?

**Comment by daid** [comment]
You'll most likely are using different settings in SF then Cura then. How are the outside dimensions?
(Cura is using the same engine as SF, so with the same settings the results should be the same)

**Comment by darkomen** [comment]
The outside dimensions are the same. Only I have problem with interior hole. I will modify the configuration until I get the same dimensions.
Please, can  you print one bar-clamp and check the dimension?

Regards,
Santiago.

**Comment by daid** [comment]
I'm printing in PLA, so even without printing, and accounting for shrinkage, I would say, the hole would be about 0.2mm smaller then in the 3D model. I did not check the dimensions of the 3D model itself.

Also, the mixed 3D view of Cura (showing sliced path inside of the 3D model) clearly shows the path it tries to print is correct.
