### ISSUE TITLE
Part orientation while slicing in Cura or project planner

### ISSUE THREAD

**Issue by at101** [daid/LegacyCura#221]
Loaded the model and used the swap XZ command and rotation to modify the slicing orientation of the part. The generated g-code does not follow from the updated model orientation - It is still using the original orientation that the model was brought in at. Is there some way to fix this? I was able to use project planner once or twice to use the updated orientation of the model but it still went back to slicing the model in its original orientation.

**Comment by daid** [comment]
Are you sure you re-sliced after you update the orientation? (I'm re-working the rotation/flipping code, as the swap XZ command is hardly userfriendly)

**Comment by at101** [comment]
Yes, I have tried this several times bringing in the model geometry to the work space and modify the orientation using the available commands:
Cura: Does not slice using the updated orientation - it always uses the original orientation of the model
ProjectPlanner : sliced in the updated orientation twice but then went back to slicing the model in the original orientation.

**Comment by daid** [comment]
Really odd. Can I ask which OS you are using?

I've never seen this happen myself, but that doesn't mean it cannot happen. If you are willing to try something, after slicing, with an orientation that did not work, try using the "load profile from GCode" option in the file menu. If this resets the orientation, then it really did not pass the orientation correctly to the slicer. If it does show the proper orientation then the slicer did something wrong. Gives me a better idea where to look for this bug.

**Comment by at101** [comment]
Using Windows 7 Home Premium running on a fujitsu laptop

I tried "load profile from GCode" - it doesn't do anything. I don't see anything being loaded. The sliced profile is different than the model.

**Comment by at101** [comment]
what i mean is the loaded model shows the orientation which i modified using Cura commands. The slicing got done using the unmodified version of the loaded model. There is a big mis-match.

**Comment by at101** [comment]
Ok so i go in Cura and hit "reset profile to default". then  Yes when i hit "load profile from g-code" it resets the orientation to the "modified orientation of the model".

**Comment by at101** [comment]
ok so here is some more info. I bring in the model, click and activate "swap yz" and also click and activate "swap xz". The g-code is sliced to the orientation of the model with only "swap yz" activated.

**Comment by daid** [comment]
Ah, ok, I never tried with both swaps enabled. Guess it can bug then, where the interface shows both swaps and the slicer only uses one.

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
