### ISSUE TITLE
When starting cura, 'unknown M code:101 and 103 repeats about a hundred times.

### ISSUE THREAD

**Issue by Aggresive** [daid/LegacyCura#222]
it then freezes for a few minutes, and i can then use the program.

see https://skydrive.live.com/redir?resid=6D437D834EE4EBE4!344 for screen shot

Don't know what to include settings-wise. If you need any information, let me know.

**Comment by daid** [comment]
It happens when you load an STL file which still has an [filename]_export.gcode from Skeinforge/RepG sitting next to it. After slicing once it should no longer happen.

I've updated the code to no longer emit the unknown message on M101 and M103, because the messages are causing the freezing.
