### ISSUE TITLE
Numpy

### ISSUE THREAD

**Issue by adloram** [daid/LegacyCura#223]
I can't get Cura starting because of Numpy that yesterday gave a problem during sudo easy_install numpy, and this morning hangs on "Reading http://numeric.scipy.org" and prints this after several minutes: error: Connection reset by peer.

What i can do to solve that problem?

**Comment by daid** [comment]
I do not know why it gives that error, I've had more reports from MacOS installs that NumPy was causing problems. But I do not have access to a mac yet. So I cannot test solutions.

Monday I will start my job at Ultimaker, and I will start on a proper Cura installer for MacOS. So once that installer is done these kind of installer issues should be gone.

**Comment by nicolas-thill** [comment]
'lo,

You can find pre-compiled numpy packages on SourceForge [1]. We used 'numpy-1.6.2-py2.7-python.org-macosx10.6.dmg' on Snow Leopard 10.6.8 yesterday night and Cura was working fine.
1. http://sourceforge.net/projects/numpy/files/NumPy/1.6.2/

## 

Nico

**Comment by Kentzo** [comment]
Please checkout fresh guide of how to setup dev env for Cura in Mac OS X.

**Comment by daid** [comment]
Release 12.11 should help in this, and the guide on how to setup Dev for MacOS X should solve the issues if it's there are problems with the 12.11 release.
