### ISSUE TITLE
Expert Mode

### ISSUE THREAD

**Issue by avalero** [daid/LegacyCura#224]
Cannot see the expert mode button on the interface in Linux 64 bit. Ubuntu 12.10

**Comment by daid** [comment]
Got a screenshot?

**Comment by avalero** [comment]
I have seen the problem.

The top menu does not appear. If I press alt-f the submenu file appears and
then I can move through all the options. Once the menu has appeared first
time it does not disappear, so now it works.

Alberto.

**Comment by daid** [comment]
Sounds like an odd layout problem (I've had a few more of these, but mostly on Windows and Mac), I'll see if I can install Ubuntu 12.10 somewhere. It was working fine on Ubuntu 10.10.

**Comment by daid** [comment]
(Should be fixed on latest versions)
