### ISSUE TITLE
Feature Request: Config different speeds

### ISSUE THREAD

**Issue by avalero** [daid/LegacyCura#225]
I have tried today Cura for the first time. And it is quite impressive.

It would be great to have the ability of config the speed of perimeters depending on its size. Like in Slic3r. For example

-Small perimeters.
-Perimeter
-Infill
-First layer
-Solid layers.

I do not know if this is possible using skeinforge.

**Comment by daid** [comment]
Has been requested before, it's mostly a UI issue, as I don't want to extra complicate things for less advanced users.

**Comment by cefiar** [comment]
I too would like this. Found that my Y belt bounces a bit (being replaced) but in the meantime I could slow down the speed of perimeters to reduce the effect of this issue on the outside of printed objects.

Just stick it in the expert options section (call it Speed), and use sensible defaults. If there's too many things in there, break the expert options into "Print" (all the existing options) and "Movement" tabs (Speed along with Bridge, Sequence and Joris).

Note: Worthwhile would be to have these all be able to take percentages of the default speed, and also to "show" the current default speed on that tab as well (not edit - they can go to the "Print Config" section if they want to change that).

**Comment by daid** [comment]
Percentages are stupid, especially for the wide range of speeds that the Ultimaker can work in. So it will NEVER EVER be percentages in configuration settings. I'm not even that happy that the current printing interface uses percentages.

I have some ideas on how to implement this, but I want to release 12.10 first.

**Comment by cefiar** [comment]
Fair enough, and I can understand you not wanting percentages. I only suggested it since it was already shown elsewhere in Cura.

Thanks for considering it.

**Comment by RedwoodForest** [comment]
I too would like the ability to, e.g., do infill at a faster speed than solid top/bottom layers.

**Comment by Feist92** [comment]
I agree you should use mm/s but please do ad this feature, its such a simple way of maintaining print quality while increasing print speed. Its not particularly hard for new guys to figure out, just have it in the expert or advanced tab but have the default speeds set the same

**Comment by daid** [comment]
Infill can be done at different speeds as of Cura 13.10
