### ISSUE TITLE
First layer is strange and overfilled

### ISSUE THREAD

**Issue by iggyfigs** [daid/LegacyCura#229]
Recently, after switching to Cura, I have been experiencing some major, print-breaking errors in the first layer of gcodes generated with Cura. There is no setting that I can find that controls the first layer's infill percentage or any other settings related to it. With Cura, prints start like this: http://i.imgur.com/mSyeN.jpg In Slic3r, with as many similar settings as possible, the first layer comes out like this http://i.imgur.com/45rIx.jpg

**Comment by daid** [comment]
What you are experiencing is a feature. Cura does the first layer a different thickness by default, it seems your bed is too high for that layer thickness in Cura and thus causes over-extrusion.
The first layer has a default thickness of 0.3, and is adjustable in the "Advanced settings" tab. If you set it to 0.0, then it will use the same layer thickness for all layers.

**Comment by iggyfigs** [comment]
Hi daid, and thanks for the quick response. I understand that this may be a
feature, but the problem is that when I raise my bed any higher, the nozzle
is so high up that the extrusion doesnt even make contact with the bed.
What's strange is I have only encountered this problem on one print, as
others with large area bottom layers seem to print fine. Are there any
specific settings I can change to reduce the impact of the extra extruded
filament? Perhaps turning the first layer height down?

**Comment by daid** [comment]
If you set the "first layer height" in the advanced tab to zero, then you will have what you want, because it will no longer extrude extra on the first layer.
