### ISSUE TITLE
Wrong number of arguments for OnHeatRun in First Run Wizard

### ISSUE THREAD

**Issue by ken-trent** [daid/LegacyCura#23]
Thanks for great software!  I'm new to my Ultimaker and excited to try using SkeinPyPy.  It looks so much easier than Skeinforge.

Running Beta4 I got an error message from the first run wizard that my heater and temp senser are not working.  I know they are working from using ReplicatorG.  The DOS box log shows the error message is likely a result of wrong number of arguments to OnHeatRun.  The log shows me using the wizard to update my firmware to the recommended version.

TypeError: OnHeatRun() takes exactly 2 arguments (1 given)

Thanks,
Ken

wizardDone not found in preferences, so using default: False
filament_diameter not found in profile, so using default: 2.89
steps_per_e not found in preferences, so using default: 865.888
Flashing 46952 bytes
Verifying 46952 bytes
Recv: start
Recv: echo: External Reset
Recv: Marlin: 1.0.0 RC2
Recv: echo: Last Updated: Marlin-Mon, 5 Mar 2012 09:56:50 -0800 - f3095493b06d52
a33ae77a0b8c1f92a22633261a | Author: Build-Me-Marlin
Recv: echo: Free Memory: 5631  PlannerBufferBytes: 1232
Recv: echo:Using Default settings:
Recv: echo:Steps per unit:
Recv: echo:  M92 X78.74 Y78.74 Z533.33 E865.89
Recv: echo:Maximum feedrates (mm/s):
Recv: echo:  M203 X250.00 Y250.00 Z5.00 E45.00
Recv: echo:Maximum Acceleration (mm/s2):
Recv: echo:  M201 X9000 Y9000 Z100 E10000
Recv: echo:Acceleration: S=acceleration, T=retract acceleration
Recv: echo:  M204 S3000.00 T3000.00
Recv: echo:Advanced variables: S=Min feedrate (mm/s), T=Min travel feedrate (mm/
s), B=minimum segment time (ms), X=maximum xY jerk (mm/s),  Z=maximum Z jerk (mm
/s)
Recv: echo:  M205 S0.00 T0.00 B20000 X20.00 Z0.40 E5.00
Recv: echo:PID settings:
Recv: echo:   M301 P22.20 I1.25 D99.00
Recv: ok
Recv: ok T:114.75 B:0.00 @:0
Recv: ok
Recv: ok T:110.17 B:0.00 @:0
Recv: ok
Exception in thread Thread-9:
Traceback (most recent call last):
  File "C:\Users\Lenae\Desktop\Ultimaker\SkeinPyPy\python\lib\threading.py", lin
e 552, in __bootstrap_inner
    self.run()
  File "C:\Users\Lenae\Desktop\Ultimaker\SkeinPyPy\python\lib\threading.py", lin
e 505, in run
    self.__target(_self.__args, *_self.__kwargs)
TypeError: OnHeatRun() takes exactly 2 arguments (1 given)

Recv: start
Recv: echo: External Reset
Recv: Marlin: 1.0.0 RC2
Recv: echo: Last Updated: Marlin-Mon, 5 Mar 2012 09:56:50 -0800 - f3095493b06d52
a33ae77a0b8c1f92a22633261a | Author: Build-Me-Marlin
Recv: echo: Free Memory: 5631  PlannerBufferBytes: 1232
Recv: echo:Using Default settings:
Recv: echo:Steps per unit:
Recv: echo:  M92 X78.74 Y78.74 Z533.33 E865.89
Recv: echo:Maximum feedrates (mm/s):
Recv: echo:  M203 X250.00 Y250.00 Z5.00 E45.00
Recv: echo:Maximum Acceleration (mm/s2):
Recv: echo:  M201 X9000 Y9000 Z100 E10000
Recv: echo:Acceleration: S=acceleration, T=retract acceleration
Recv: echo:  M204 S3000.00 T3000.00
Recv: echo:Advanced variables: S=Min feedrate (mm/s), T=Min travel feedrate (mm/
s), B=minimum segment time (ms), X=maximum xY jerk (mm/s),  Z=maximum Z jerk (mm
/s)
Recv: echo:  M205 S0.00 T0.00 B20000 X20.00 Z0.40 E5.00
Recv: echo:PID settings:
Recv: echo:   M301 P22.20 I1.25 D99.00
Recv:
Recv: ok
Recv: ok
Recv: ok
Recv: start
Recv: echo: External Reset
Recv: Marlin: 1.0.0 RC2
Recv: echo: Last Updated: Marlin-Mon, 5 Mar 2012 09:56:50 -0800 - f3095493b06d52
a33ae77a0b8c1f92a22633261a | Author: Build-Me-Marlin
Recv: echo: Free Memory: 5631  PlannerBufferBytes: 1232
Recv: echo:Using Default settings:
Recv: echo:Steps per unit:
Recv: echo:  M92 X78.74 Y78.74 Z533.33 E865.89
Recv: echo:Maximum feedrates (mm/s):
Recv: echo:  M203 X250.00 Y250.00 Z5.00 E45.00
Recv: echo:Maximum Acceleration (mm/s2):
Recv: echo:  M201 X9000 Y9000 Z100 E10000
Recv: echo:Acceleration: S=acceleration, T=retract acceleration
Recv: echo:  M204 S3000.00 T3000.00
Recv: echo:Advanced variables: S=Min feedrate (mm/s), T=Min travel feedrate (mm/
s), B=minimum segment time (ms), X=maximum xY jerk (mm/s),  Z=maximum Z jerk (mm
/s)
Recv: echo:  M205 S0.00 T0.00 B20000 X20.00 Z0.40 E5.00
Recv: echo:PID settings:
Recv: echo:   M301 P22.20 I1.25 D99.00
Recv: ok
Recv: ok
Recv: ok
Recv: ok
Recv: start
Recv: echo: External Reset
Recv: Marlin: 1.0.0 RC2
Recv: echo: Last Updated: Marlin-Mon, 5 Mar 2012 09:56:50 -0800 - f3095493b06d52
a33ae77a0b8c1f92a22633261a | Author: Build-Me-Marlin
Recv: echo: Free Memory: 5631  PlannerBufferBytes: 1232
Recv: echo:Using Default settings:
Recv: echo:Steps per unit:
Recv: echo:  M92 X78.74 Y78.74 Z533.33 E865.89
Recv: echo:Maximum feedrates (mm/s):
Recv: echo:  M203 X250.00 Y250.00 Z5.00 E45.00
Recv: echo:Maximum Acceleration (mm/s2):
Recv: echo:  M201 X9000 Y9000 Z100 E10000
Recv: echo:Acceleration: S=acceleration, T=retract acceleration
Recv: echo:  M204 S3000.00 T3000.00
Recv: echo:Advanced variables: S=Min feedrate (mm/s), T=Min travel feedrate (mm/
s), B=minimum segment time (ms), X=maximum xY jerk (mm/s),  Z=maximum Z jerk (mm
/s)
Recv: echo:  M205 S0.00 T0.00 B20000 X20.00 Z0.40 E5.00
Recv: echo:PID settings:
Recv: echo:   M301 P22.20 I1.25 D99.00
Recv: ok
Recv: ok
Recv: ok
Recv: ok
lastFile not found in preferences, so using default: None
layer_height not found in profile, so using default: 0.2
wall_thickness not found in profile, so using default: 0.8
solid_layer_thickness not found in profile, so using default: 0.6
fill_density not found in profile, so using default: 20
skirt_line_count not found in profile, so using default: 1
skirt_gap not found in profile, so using default: 6.0
print_speed not found in profile, so using default: 50
print_temperature not found in profile, so using default: 0
support not found in profile, so using default: None
filament_density not found in profile, so using default: 1.00
retraction_min_travel not found in profile, so using default: 5.0
retraction_speed not found in profile, so using default: 13.5
retraction_amount not found in profile, so using default: 0.0
retraction_extra not found in profile, so using default: 0.0
travel_speed not found in profile, so using default: 150
max_z_speed not found in profile, so using default: 1.0
bottom_layer_speed not found in profile, so using default: 25
cool_min_layer_time not found in profile, so using default: 10
model_scale not found in profile, so using default: 1.0
flip_x not found in profile, so using default: False
flip_y not found in profile, so using default: False
flip_z not found in profile, so using default: False
model_rotate_base not found in profile, so using default: 0
model_multiply_x not found in profile, so using default: 1
model_multiply_y not found in profile, so using default: 1

**Comment by daid** [comment]
Yes, I missed this bug while building Beta4. It's solved in the github version. Sorry about the problem :(
