### ISSUE TITLE
feature request: project planner print all parts at the same time.

### ISSUE THREAD

**Issue by avalero** [daid/LegacyCura#230]
When I make a project adding several STL it prints the whole part one after another... that makes impossible to print several high parts... whould it be possible to print the layers of every object all at the same time. As if it was a single STL.

**Comment by daid** [comment]
Already in Cura. It's called "print all at once", it's in the toolbar of the planner.

**Comment by avalero** [comment]
OK, unfortunately I do not see the toolbar, that's why I had not seen it. I
have to press Alt-F :)

**Comment by daid** [comment]
The toolbar bug might be something in Unity?
Small warning, the 12.08 release has a bug where it dives the head into the print after printing with the all-at-once project planner.

**Comment by avalero** [comment]
I use gnome-shell

and yes... I realized of the z=0... too late :) but it was not too bad my
buddasch stood well :D
