### ISSUE TITLE
Packaging Cura for Fedora

### ISSUE THREAD

**Issue by hroncok** [daid/LegacyCura#231]
Hi, I would like to package Cura for Fedora, I have a question...

Can I use upstream skeinforge and poind cura_sf to it, or your's different?

Thanks

**Comment by daid** [comment]
Mine is different, next to a bunch of bug fixes on SF50, I also made a lot of changes to add features. I also changed stuff to make it better integrated into Cura, so you cannot drop-in an SF version without changes. But I'm up-to-date with SF50.

**Comment by daid** [comment]
Note, if you create some kind of script to create a fedora package, then I could build packages for next releases.

**Comment by hroncok** [comment]
I see.

Well, I'll prefer to do it myself as I aim to include it in Fedora 3D print spin, but thanks for helping. If you could provide stable version tarball without any dependencies or binaries (printrun, pypy), it would be great, so I don't need to strip it.

**Comment by hroncok** [comment]
Also, it seems you store configaration in the program directory, any chance to store it in user's home dir? E.g. $HOME/.config/cura or something simillar?

**Comment by daid** [comment]
It should be quite easy to change that. I will also remove the pypy and printrun from the next linux package. Packaging pypy with it caused a lot of problems for 64bit users, and printrun is no longer needed in the next version.

I'm personally quite a fan of "self contained" packages, that store configuration and settings in the same location, so it's easy to remove, and you never get conflicts.
But that's not standard for Linux, and I'm working on making a proper installation for MacOS which has the same multi-user system. I think I will turn it into $HOME/.cura/[version]/ so you still can run different versions side-by-side without problems.

**Comment by daid** [comment]
Maybe you didn't notice already, so let me say something about the pypy dependency. Cura searches for PyPy at a few locations, it's own install directory, and in the $PATH environment variable. So you can install pypy system wide.

If it doesn't find pypy, it will use python to slice, which also works but is 4x slower.

**Comment by daid** [comment]
(I changed the location where it stores the ini files now in the HEAD version)

**Comment by hroncok** [comment]
Could you please provide a Linux tarball without pypy alongside with the current one? Thanks

**Comment by hroncok** [comment]
And another questions are:
- what is the license of the firmware? where are the sources?
- for what is ultimaker_platform.stl used and what is it's licnese?
- what is the license of the icons, is it AGPLv3 as the code?

**Comment by daid** [comment]
I'll add proper licensing and origons for those.

FYI: The firmware is also on github: https://github.com/Ultimaker/Marlin , the platform is a derivative from CC-by-NC lasercut drawings (I'll have to look up the link). The icons I see as part of the code, so I'll make clear that they are AGPLv3.

**Comment by hroncok** [comment]
> the platform is a derivative from CC-by-NC lasercut drawings

And for what purpose is the platform used? It is not just an example, because it is loaded in gui/util/opengl.py, but I cannot say from the code, what is this used for.

> The firmware is also on github: https://github.com/Ultimaker/Marlin

In that case, you'll need to include the source in the package, because the firmware is GNU GPLv3.

Could you please do something for me? Use this file (feel free to ave it to this repository): https://github.com/hroncok/RPMAdditionalSources/blob/master/cura-stripper.sh

Use it to generate a tarball for me and put it to your website. Thanks

**Comment by daid** [comment]
GPLv3 doesn't force you to include the source with the release. (Section 6-d would apply in this case)

**Comment by hroncok** [comment]
No, but you have to at least link it. It seems you've done that in 7fd1847.

Anyway, could you please provide the tarball I wanted? Later on, I will investigate, what should I do to include binary firmware.

**Comment by daid** [comment]
Removing the platform caused a bug if you selected the Ultimaker as machine (then the platform is used as preview to give a better sense of scale), I fixed that so you can properly leave it out.

Removing the firmwares would give the odd user experience of the software asking you if you want to upgrade your firmware and then it would say that it doesn't have a firmware for your machine.
Binary firmware might be a bit "against the spirit of open source", but for these binaries I know they work and are tested. With the buggy state of different versions of avr-gcc this isn't always warranted. And the firmware provides a safety role, a bug in there could damage the machine. So while I'm pretty pro-open-source, I'm also for binary firmwares in this case.

And then there is the case that you removed pypy. While pypy isn't strictly needed, without pypy you will get a bad user experience where the software is 4x slower.

PS. I do think it's important to have proper license and attribution everywhere. So I'm glad you are bringing this to my attention.

**Comment by hroncok** [comment]
> I fixed that so you can properly leave it out.

Thanks.

About the firmware. It would be great, if the app downloads it from GitHub (or from somewhere else) when user needs it, and store it to .cura in $HOME. Of course, this would be done only if there is no firmware in resources. That would mean:
- Still good user experience
- No problems with packaging

Could you program that into Cura? I could probably do that somehow, but I'm not familiar with your code so much.

> And then there is the case that you removed pypy.

I've removed it, because in Fedora, pypy is already packaged.

> Cura searches for PyPy at a few locations, it's own install directory, and in the $PATH environment variable. So you can install pypy system wide.

So it should use the system one.

**Comment by Kentzo** [comment]
Cannot we distribute pypy as pip package (via requirements)?

Best regards,

Ilya Kulakov
From my iPhone

14.01.2013, в 18:27, Miro Hrončok notifications@github.com написал(а):

**Comment by hroncok** [comment]
I don't know. From my point of view, feel free to distribute your current package as-is. And distribute my modified one alongside with it. You don't even have to promote or link it somewhere, as long as I know the location. It is just easier for me, if the tarball is from upstream website.

**Comment by Kentzo** [comment]
Ok, the answer to my question is that we cannot install it as pip package.

**Comment by hroncok** [comment]
There is a cura.sh script that check if everythin is installed. For example, if there is no PyOpenGL, there is following error:

Requires PyOpenGL
sudo easy_install-2.7 PyOpenGL

Why not do the same thing with PyPy?

Requires PyPy, use your's distribution tool to grab it, e.g.:
sudo apt-get install pypy # For Ubuntu or Debain
sudo yum install pypy # For Fedora

**Comment by daid** [comment]
I initially didn't do that because the pypy distributed with ubuntu was old and very buggy.

**Comment by Kentzo** [comment]
Maybe the installer should be smarter and offer a user to enable/disable support for system-wide pypy?

**Comment by hroncok** [comment]
To the firmware: It can be distributed in Fedora, but it has to be built from source. I'll create another package just for it.

**Comment by hroncok** [comment]
Hi again, could someone please check if the compiled firmware from this package is OK? I don't have an Ultimaker to test it myself and I don't want to distribute something perverted.

http://koji.fedoraproject.org/koji/taskinfo?taskID=5034266 (second link from the bottom), use `rpm2cpio ultimaker-marlin-firmware-12.12-0.3.RC1.fc19.noarch.rpm  | cpio --extract --make-directories –` to extract it on non RPM system. Or install it on Fedora and have a look to `/usr/share/ultimaker-marlin-firmware/ultimaker-marlin-firmware.hex`.

How it was done:
- Used sources from RC1 commit in https://github.com/Ultimaker/Marlin
- `mv Marlin src && mkdir lib && ino build -m mega`

Thanks a lot.

**Comment by hroncok** [comment]
Anyone?

**Comment by daid** [comment]
Well, you are asking currently mostly Windows and Mac users to do some terminal commands, on linux. And testing a firmware can take some time and in the worst case damage your machine.

I just did an update on the Ultimaker/Marlin sources to add a batch file which builds the firmware images I used (yes, it's Windows, but should be easy to base something bash off that)

I've been too busy with other things to give it a test. I hope I can soon.

**Comment by hroncok** [comment]
> Well, you are asking currently mostly Windows and Mac users to do some terminal commands, on linux.

Sorry for that: http://files.hroncok.cz/reprap/ultimaker-marlin-firmware.hex

> I just did an update on the Ultimaker/Marlin sources to add a batch file which builds the firmware images I used (yes, it's Windows, but should be easy to base something bash off that)

I'll look at that, thanks.

**Comment by hroncok** [comment]
Cura was finally approved as a Fedora package. Thanks for your help.

**Comment by Im-Hal-9K** [comment]
The issue here though is because it's a one off it doesn't update the same way that his does and it doesn't keep up with the changes. We just need to create a script so you can build a RPM file from your current code.

**Comment by hroncok** [comment]
Yes, that's basically what RPM packaging is about :)

**Comment by Im-Hal-9K** [comment]
I was under the impressions that RPM could be updated as a package. This is not correct?  

## 

Hal Gottfried
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by hroncok** [comment]
I have not idea what you are into right now.

The reason that Cura in Fedora is not updated is that it was still
failing for me in recent past.

**Comment by Im-Hal-9K** [comment]
Understood. I am just glad it is in there at all. It's a great package and I am happy to see a 3d spin !  

## 

Hal Gottfried
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
