### ISSUE TITLE
Feature request: better first layer adhesion

### ISSUE THREAD

**Issue by mfeherpataky** [daid/LegacyCura#232]
Instead calling a feature by its proper name - width-vs-thickness or better yet extrusion-width for first layer. Let's call it "better first layer adhesion", it is easier.

Few months back slic3r was shipped with the first layer width set to 200% as a default setting. It makes a perfect sense, as it gives some additional all-necessary grip to the printbed. 

How about Cura uses similar approach? In basic settings, there would be a tick-box with "better first layer adhesion", where in expert mode user could tinker around the actual settings, default setting being twice the standart width.

**Comment by daid** [comment]
Cura already does this, but not as a stupid ratio (ratios are stupid). It does this by making the first layer a different thickness, you can adjust this thickness in the advanced settings. A 0.3mm first layer gives good adhesion, makes the Z level less tricky, and makes it easier to remove objects from tape (if printed in PLA on tape)

**Comment by mfeherpataky** [comment]
Thank you for a super-fast response!

Yeah, I checked this one out. My question is - do you also extend the width of the bottom path and add more extrusion? This produces less x,y resolution but makes sure everything sticks to the printbed.

This is the only outstanding issue I find with Cura - adhesion to the printbed. 
I love the first purge of the extruder before the print begins - this is awesome!

**Comment by daid** [comment]
Ah, like that, no I don't. I see how that could improve the first layer, but the SF engine doesn't make this possible.

**Comment by mfeherpataky** [comment]
That is too bad. However I managed to get a good first layer with a height of 0.4mm. Thanks for the tip. Now waiting for brim and Cura slowly becomes my software of choice for slicing.

Thank you!

**Comment by daid** [comment]
The next version will create a brim if you set the skirt distance to zero ;-)

**Comment by mfeherpataky** [comment]
This is an awesome news! Thank you and I will report once the version is out.
