### ISSUE TITLE
Serial port opening fails when setting Serial port due to wrong var type

### ISSUE THREAD

**Issue by fax8** [daid/LegacyCura#234]
Hello, I'm using Cura 12.08 under Archlinux. I set the connections parameters in the configuration page and with the original code the connection failed. This seems to be due to the fact that _openPortWithBaudrate expect port to be a string but the type in the original code was unicode. 

Changing the code to 
self.serial = self._openPortWithBaudrate(str(port), baudrate) 
in machineCom.py line 118 seems to fix the issue

Hope this helps,

Fabio Varesano

**Comment by daid** [comment]
unicode objects are also strings, so maybe are dealing with an old version of pyserial?

**Comment by fax8** [comment]
System pyserial is python2-pyserial 2.6-2 .. not sure if there is one also shipping with Cura.

**Comment by daid** [comment]
Odd, I ship for windows with pyserial-2.5, could be a mistake in newer pyserial versions...
