### ISSUE TITLE
tcl errror

### ISSUE THREAD

**Issue by Lunavast** [daid/LegacyCura#236]
I have the following error.
Windows7 32bit.

On starting Printrun.bat, the message appears.

Unknown variable 'slicecommand'

When I tried to open SFACT Settings, I have the error below.

Entering skeinforge settings:  C:\Program Files\Cura_12.08\python\python.exe   s
keinforge/skeinforge_application/skeinforge.py
this should never happen, getDisplayedDialogFromConstructor in settings could no
t open
<**main**.SkeinforgeRepository instance at 0x019855F8>
Traceback (most recent call last):
  File "C:\Program Files\Cura_12.08\printrun\skeinforge\fabmetheus_utilities\set
tings.py", line 147, in getDisplayedDialogFromConstructor
    return RepositoryDialog( repository, Tkinter.Tk() )
  File "C:\Program Files\Cura_12.08\python\lib\lib-tk\Tkinter.py", line 1685, in
 **init**
    self.tk = _tkinter.create(screenName, baseName, className, interactive, want
objects, useTk, sync, use)
TclError: Can't find a usable init.tcl in the following directories:
    {C:/Program Files/Cura_12.08/python/lib/tcl8.5} {C:/Program Files/Cura_12.08
/lib/tcl8.5} {C:/Program Files/lib/tcl8.5} {C:/Program Files/Cura_12.08/library}
 {C:/Program Files/library} {C:/Program Files/tcl8.5.2/library} C:/tcl8.5.2/libr
ary

This probably means that Tcl wasn't installed properly.

Warning, displayedDialogFromConstructor in settings is none, so the window will
not be displayed.

**Comment by daid** [comment]
That's in PrintRun, PrintRun is no longed needed in the next version and won't be shipping with the next version.
