### ISSUE TITLE
Raising, not lowering, Bed at end of multi-print

### ISSUE THREAD

**Issue by bbum** [daid/LegacyCura#237]
I created a print with 4 copies of the same, relatively thin, object and let Cura auto-place them.   Using the "print all at the same time" option, I sliced and printed.

At the end of the print, the print bed rises instead of lowers.  This causes the print head to be dragged across the parts in a rather scary fashion.

Last bit of Gcode is below.   Obviously, the "G1 Z0.000000 F180.000000" is the problem (right?).   I don't believe I've done anything in Cura that would cause such a thing to be emitted (despite the CUSTOM indicator).

G1 X61.876 Y114.053 F3600.0 E97.6509
G1 X62.939 Y112.424 F9000.0
G1 X67.633 Y107.729 F3600.0 E97.7318
G92 E0
M107
;TYPE:CUSTOM
G1 Z0.000000 F180.000000
;End GCode
M104 S0                     ;extruder heater off
M140 S0                     ;heated bed heater off (if you have it)

G91                                    ;relative positioning
G1 E-1 F300                            ;retract the filament a bit before lifting the nozzle, to release some of the pressure
G1 Z+0.5 E-5 X-20 Y-20 F9000 ;move Z up a bit and retract filament even more
G28 X0 Y0                              ;move X/Y to min endstops, so the head is out of the way

M84                         ;steppers off
G90                         ;absolute positioning
;CURA_PROFILE_STRING:eNrdVU1v40YMvQpCfwSPu2jWkRx7m8TQpUWcS1MU2AJNchHGEmVPM5oRZkZ2bEP/vZyRZMvepN1FbzUQx6T48chHUgUXrERp05zTf4s6GY+ubwKpdjuBqeE7TKLRJChZtuIS04xMUaevSRxF58qtV26YEKld8exFojHkfB0UglfkMmfCYCtsh8KuE8yGkdmJtO2lUuUoUpMxgUncSVpZZjFdMEMYA8G2hGGFfLmylHUcGCV4nrbqIZ7PQcEJYo7ScNtiNi9c21T4WlQtyb9TLVmVXI2ioNKcWmQqxDz53IsWywo1s7XGZDwml7qqlLbJb0pigJItqIGaFbav9dDpPvOIUmu0mmWWK5mWXKYkrFEk09HJkzbxJDrVsrLFeqrFV/rplW2szjmeOr5e010nu6oWylpVdi1q1VRGppTwWLrW8ZJaHgUFo9i+qDz5Q9fYew9be9WXTd2Tbdk/GMu0HS0zoiyZfRE8wxz21AuyLLEBZm9hn7Nt474tKfYuYRPOfmaGZ2DQWi6X5hZ+dWig5ZdchnQ38CcNHdnsT4evgTkxfevTHQin0L87+sDloWcdl23SeccR1Abz1rHlrO11Uw5Umzb3cuCVKWOHXk5uwvtxDN1nRiumqaw1EzWa8P4mOjxhCxrY2iJUimASk1R2+BBHP/UGvpGw4XYFdoVAfIAqipDCX8NjBE+RC6/WCI+XT2AVEIWAMjdWVcYbPUcdBmf0/LXJzbiLQ4Z3B2Aw00gsgFGF3TB9xOcCFFpJeymwsJc7N3OEJobnmMYX5vvBuDVdVge8EswWSpeQq42EeFqWoc89SHnMvUOtvJcb6zqn2aHBWdqVyzMfRwT06syjM4SrsqT+QEHZgQrMXr4/CbAl4zIMZ0vlinUWJc9zgS7wSSkfcm78alwAM+4R9YkbkAqky0/OxxDttfwYzqiEx/35YW3g6VxHuzHfD5e58dWfqWj18n7N7mQO97/QTzdAE/jyRtGDVrmtotXTfpwe4kn0roO3y2FBf0cX+MAL2KoaVgQHuP3o6IzhGz40WdRAvj6deart7hPVdxVF/+Lsb167DP0GMlhwSwCJFQTBC3c8vEX7QrtwJFBWpHcGTXR5ZJKG3NAh9/P7YzSaEoYpPH4a00K4r7NuH5aorrqUjFreIzqgwTVKKJULe1zSfyzqvQW+ILQeKPU9d6Olattj37BtGD5cT96PaixW9KoynuHB0fna8s0rFEiaFLX4C7PDIX/w2+zG+5Vw+EfgTsJgKUaQUZ91unNw292RvGQCdt0Vhw0e1qNkL0QIEeCUOcVVFla+rdsuvBl1C/z/Ga/zoTqfg+8Yr5vomzryJr0e1L4jqzk73H3T/+Ox8qd62gf7G3HDTqw=

**Comment by daid** [comment]
Known bug, fixed for the next version. See issue #220

**Comment by bbum** [comment]
Thanks.
