### ISSUE TITLE
package.sh busted on osx64

### ISSUE THREAD

**Issue by bbum** [daid/LegacyCura#238]
Running package.sh errors attempting to copy the .sh scripts that no longer exist:

cp: scripts/osx64/*.sh: No such file or directory

**Comment by bbum** [comment]
diff --git a/package.sh b/package.sh
index 3cf71dc..3959118 100755
--- a/package.sh
+++ b/package.sh
@@ -181,7 +181,9 @@ echo $BUILD_NAME > ${TARGET_DIR}/Cura/version
 if [ $BUILD_TARGET = "win32" ]; then
     cp -a scripts/${BUILD_TARGET}/*.bat $TARGET_DIR/
 else
-    cp -a scripts/${BUILD_TARGET}/*.sh $TARGET_DIR/
-    if [ $BUILD_TARGET = "linux" ]; then
-       cp -a scripts/${BUILD_TARGET}/*.sh $TARGET_DIR/
-    fi
  fi
  
  #package the result

**Comment by bbum** [comment]
With the above patch, I end up with a double-clickable .app.  Still bounces over to the python icon thingy, but... an improvement.

**Comment by daid** [comment]
I was still working on it, it's much better now, it should build a working .app for MacOS 10.6 and 10.8
The .sh missing message can safely be ignored, it's just a warning.
