### ISSUE TITLE
Tooltips on Mac OS X make Support popup impossible to use

### ISSUE THREAD

**Issue by bbum** [daid/LegacyCura#239]
- go to "standard" mode
- click on "support type" popup

If the tooltip pops up, it does so over the list of support type options.   This renders it impossible to select a support type.

**Comment by daid** [comment]
Which version of MacOS, which build of wxPython?

Works fine with my 10.8 Mac with wxPython2.9-osx-2.9.4.0-cocoa-py2.7.dmg

**Comment by bbum** [comment]
Derp.   10.8.2 + wx 2.9.4.0 py2.7 Cocoa + Top-of-Tree Cura from a couple of days ago.

**Comment by daid** [comment]
Ahh, I see the problem now! Getting on it as soon as I get my mouse back...

**Comment by daid** [comment]
Note, I fixed this. Forgot to mention the issue number in the commit.
