### ISSUE TITLE
Raft

### ISSUE THREAD

**Issue by frollard** [daid/LegacyCura#24]
Greetings;

Loving what I'm seeing so far, but really need access to the Raft procedure in SF.  Without a heated bed or a beefy raft to hold down, builds are having huge problems staying put.  

If I recall the raft is already being called in the slicing process, but it doesn't output anything/just the skirt.

**Comment by daid** [comment]
Raft doesn't add the skirt, skirt does that :P but the raft procedure is needed for support, that's why it's always ran.

But you are 1 day late :P I added an option to enable raft yesterday in the github code. It's lacking some extra settings (it's only on/off right now)

You can, if you are feeling adventurous, install the development version: https://github.com/daid/SkeinPyPy/wiki/Installing-development-version

**Comment by daid** [comment]
Maybe a good question to ask you.

I've never used raft myself. So what settings are useful to configure for the raft? Right now the difference between no raft, and raft are that you get 1 base and 1 interface layer, with the default SF settings.

**Comment by frollard** [comment]
Default of 1 base and 1 interface are good as of our old repG experience.  It is nice to tweak that interface layer to say how sticky it will be, but the base layer should be REAL thick and goopy to glue down properly.  It should still be somewhat porous when completely done printing the raft that you can still see through the grid.

**Comment by daid** [comment]
Then there are 2 settings that are important I think:
-Base layer flowrate (high so you get a lot of material)
-Interface layer flowrate (low so you get little material)

Skeinforge has a silly amount of settings for the raft, and making sense of them is quite hard. But these 2 settings clearly control the amount of material extruded.

**Comment by frollard** [comment]
Indeed, I would REALLY recommend unlocking those values so they can be tweaked in the advanced menu.  Each machine is slightly different/pla vs abs vs nozzle size will make a difference. 
Another important number is how large the raft is outside the base of the model, larger = more stable.

Base layer is primarily good for gluing the model down and getting a level working surface
Interface is important so you can break the raft off after.

**Comment by daid** [comment]
Added settings for material amounts and amount of extra margin for the raft.
Guess that makes the ABS users happy :)
