### ISSUE TITLE
Cura should store preferences, etc. in the Apple recommended location

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#242]
Based on 09f404081ee2677ce688c5c73c055bdb7d9cdb62 it appears that Cura is storing its preferences on the Mac in a hidden folder in the user's Home folder (~/.Cura).

This is very Unix-like, but not very Mac-like. Based on Table 1-3 in http://developer.apple.com/library/ios/#documentation/FileManagement/Conceptual/FileSystemProgrammingGUide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW1 I believe the correct location is the Application Support folder in the user's Library folder as these seem like "app-created...configuration files...that are managed by the app".

The other option would be the Preferences folder, but this document seems to suggest that that should only be used via the preferences APIs, which you're not doing. This is however somewhat contradicted by the older document http://developer.apple.com/library/mac/#qa/qa1170/_index.html, which suggests that Java apps should use the Preferences folder even if they're using their own preferences format (note also the caveat about the Application Support directory). 

If @bbum has an opinion on this I'd take his advice over mine.

**Comment by daid** [comment]
I rather keep doing it as I do it now, less difference between the Mac and Linux version. Means less code, and less potential problems.
