### ISSUE TITLE
Cura does not fully support Retina resolution

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#243]
Cura text and graphics appear blocky and low-res on Retina MacBook Pros.

**Comment by daid** [comment]
Got a screenshot? Not sure if I can fix this, but also not sure if I understand the problem.

**Comment by RedwoodForest** [comment]
I will email one to you, as the image upload service I usually use seems to reduce the size of the image (~2k x ~1.5k pixels) making the difference not as obvious. 

In it you can compare Cura (top) with SourceTree (bottom). Particularly obvious is the difference in text crispness and diagonal lines on icons and such. It's very obvious which applications have been updated for Retina vs which have not, though I'll freely admit it's purely cosmetic:).

I wouldn't be surprised if it turns out to require an update to WxPython.
