### ISSUE TITLE
"Load model file" menu item does not have a keyboard shortcut on the Mac

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#247]
The "Load model file" menu item does not have a keyboard shortcut on the Mac. I'm tempted to say the shortcut should be "Command-O", as Command-O is the typical "open a new <common-thing>" shortcut (iTunes even uses it for "Add to Library"), but "Command-L" would be okay with me, too.

**Comment by daid** [comment]
Added CMD+L (CTRL+L for Win/Linux)
