### ISSUE TITLE
All settings descriptions changed color to light grey when I loaded a model

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#251]
I loaded a model using the "Load Model" button and all the descriptions of the settings changed color to light grey: http://i1162.photobucket.com/albums/q531/lawrencejohnston/ScreenShot2012-10-28at32104PM.png

I also just discovered that all menu items are now disabled except in the "Python" menu.

Cura 12.10 development built from source
OS X 10.8

**Comment by daid** [comment]
As far as I know this is fixed now.
