### ISSUE TITLE
Retraction not working in current 12.10 source

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#252]
I recently built from latest 12.10 source, and now retraction doesn't seem to be working. 

https://gist.github.com/9a9b94fe57db9ee8fe09 is the generated GCode for Part4 of http://www.thingiverse.com/thing:22018. It should be retracting once you get up to the pillars spaced several cm apart but it's not. 

You can load my profile from the GCode to confirm my retraction settings (5mm min travel, 55 mm/s speed, 4 mm distance).

OS X 10.8.

**Comment by daid** [comment]
It is, you just didn't enable retraction on the print settings tab.

**Comment by RedwoodForest** [comment]
Thanks Daid. I missed that somehow.
