### ISSUE TITLE
Origin Aleration

### ISSUE THREAD

**Issue by jhdes** [daid/LegacyCura#253]
I have a cartesio printer. Its coordinates are set up differently to the ones on cura.:-
Cura vs Cartesio
Y+     =     X-
Y-      =     X+
X+     =     Y+
X-      =     Y-
Z+     =      Z-
Z-      =      Z+

So when i send the code to the printer, set the head to the origin, the printer is trying to print away from the printer bed!
Is there a way of altering the X,Y,Z orientation/configuration?

**Comment by daid** [comment]
Nope, I recommend changing your firmware, would make it compatible with everything else.

**Comment by jhdes** [comment]
ok, thanks for the advice. How do  do that?

**Comment by daid** [comment]
No idea, the firmware is in your printer, not mine.
