### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by bkubicek** [daid/LegacyCura#254]
A text file export/import of a complete profile, including expert settings, and _everything_, also start end replace gecode, so profiles can be shared using email.
It would save people the need to do multiple screenshots when asking for help debugging there profile...

**Comment by daid** [comment]
Already in there, it's the "save/load" profile in the file menu.

**Comment by bkubicek** [comment]
I just tested it, the file is good, but at least the e_steps_per_mm are not exported/imported. the rest seems allright.

**Comment by daid** [comment]
That's correct, I do not see the steps-per-E as a profile setting, but as a machine preference setting.

**Comment by bkubicek** [comment]
I noted it, because nowadays :)  i sliced for two different printers using
the same computer/cura install. Also, its thinkable of having Dual
extruders with different e_steps and similar stuff. Maybe not a very
typical setup, I agree.

Bernhard
