### ISSUE TITLE
Detect when thermocouple is installed backwards

### ISSUE THREAD

**Issue by ryneches** [daid/LegacyCura#255]
During the machine checks, if the thermocouple is installed in reverse polarity, the temperature check never finishes. Reverse polarity is really easy to detect (the registered temperature goes down when the heater core is switched on). 

The temperature check should fail and tell you what you've done wrong.

**Comment by daid** [comment]
The temperature check will fail if you wired it wrong, it just takes a while.

**Comment by ryneches** [comment]
Yep. At the moment, it appears that three failure cases (reversed polarity, poor thermal contact and faulty connection) are handled the same code. This works, but more specificity would be nice. That's all.
