### ISSUE TITLE
Under OSX 10.8, wxPy2.8 is blech. wxPy2.9 is happy.

### ISSUE THREAD

**Issue by baudot** [daid/LegacyCura#256]
Following the MacOS install instructions, I was unable to get the recommended version of wxPython to work with cura. Downloading the more current 2.9.4.0 release solved the issue.

**Comment by daid** [comment]
The 12.10 release that will be out tomorrow will ship with wxPython 2.9.4.0, it will also feature a better installer, so no more terminal commands required.
