### ISSUE TITLE
cannot update Marlin firmware in cura

### ISSUE THREAD

**Issue by hermanwouters** [daid/LegacyCura#257]
I build a heated bed to my Ultimaker.

I updated the Marlin firmware with : thermistor 100K and downloaded the new build firmwere.

When I try to install the custome firmware in Cura with "expert" I get the following message:

 Failed findinge a machine for firmware upgrade. Is your machine connected to the PC ?

My machine is then still connected with the PC.

What can I do ?

**Comment by daid** [comment]
Cura is not finding the printer, make sure you wait a while after connecting the USB cable, as it takes a while for the printer to register.

**Comment by hermanwouters** [comment]
I discovered my problem. when I changed 250000 into 115200 it worked.

My heated bed is working now perfectly, thank you for the information about Ultimaker Prusa MK2 Heated bed solution in "headfuzz"
