### ISSUE TITLE
No option for relative extrusion

### ISSUE THREAD

**Issue by Intrinsically-Sublime** [daid/LegacyCura#258]
I am so sick of Slic3r I was going to set up Cura for Tantillus users but there is no option for Relative extrusion.

Before you say you should use absolute I have to say why would I want to make the Arduino do more work, make the code harder to read through and make it way harder to splice multiple files together. 

Relative is really the only form of extrusion that should be used. Absolute extrusion serves ZERO purpose.

**Comment by daid** [comment]
Relative extrusion adds rounding error on rounding error, that's why absolute extrusion is used. So that's not zero purpose. I do not know if the rounding error is serious or just a theory.

I do like the idea of using Cura for the Tantillus (which I find an interesting printer, and matches quite a bit with my unfinished TITAN design)

Relative E would make it easier to stitch and edit GCode. I rather not make it a setting (less is more) but we could change the default.

I also would have no problem with a single Cura version with both Ultimaker and Tantillus as options in the first run wizard. And thus improving Tantillus support. While we could also maintain different branches, but that would add extra work. So I rather keep the forks to the minimum.

**Comment by Intrinsically-Sublime** [comment]
Sorry I was not trying to be a jerk (very little sleep, new baby). I have heard the rumor about rounding errors and it was why I kept using Relative. I did not want part of the last extrusion in the next extrusions location. I always figured it was one of the things causing bumpy prints (adding the rounding to the next move). But when I spoke up about it I was told Relative adds the remainder to the next move too. This was back when I was using Teacup still but I would imagine that Marlin does the same thing so that would take us back to zero reason for Absolute. I have been using Marlin since I developed Tantillus and have not seen any issue with the Relative extrusion. Also I believe E-maker Huxley uses Relative by default too and it is known for high quality prints.

It does not need to be an option in the interface but if you could add it back to the config I would just manually change it from false to true for the Tantillus configs. If you would like to add Tantillus to the preconfigured settings too that would be great but not needed until I figure out some settings for Tantillus.

**Comment by daid** [comment]
Note if you just want a quick fix to test it out, all the SF settings are set from settings.py, so you could hack in there to test things.

**Comment by Intrinsically-Sublime** [comment]
So to be clear I can call anything that was available in SF50 from the settings.py? You have just removed them to make it easier to read and cleaner.

**Comment by daid** [comment]
Yes, all settings from SF50 are there, and a few I added. And all the mapping from Cura settings to SF settings is done there. As it's not always a 1:1 mapping.

**Comment by Intrinsically-Sublime** [comment]
I have been playing with Cura and found an issue with using Relative extrusion. The gcode viewer colors the lines based on the E value which results in a rainbow patterned part instead of colored rings with infill. How hard would it be to use the ;Infill and ;perimeter tags to select the color of each section of code?

**Comment by Intrinsically-Sublime** [comment]
So I have added relative extrusion radio button to the preferences panel and fixed the gcode viewer for relative extrusion.

The viewer issue was two things.
- The gcode interpreter was missing M82 M83 (absolute and relative extrusion) and it would only set the retract tags when set in full absolute or relative mode G91 G92.
- After getting the gcode interpreter to set the retract tags I found that in opengl.py it set the extrusion width using the E value but in relative it saw the un-retracts of 5mm as super wide paths.

I am sure there are betters ways of doing what I did as I am not a programmer. Here are my patches if you have any interest.

Relative switch https://github.com/Intrinsically-Sublime/Cura/commit/b230f1af99230222d42cef3d8dcef70329cf8294
Gcode viewer work around https://github.com/Intrinsically-Sublime/Cura/commit/d1a4714235ccb68ae764b9a2aee1686797c29683

I have marked it closed as I may be the only one interested.

**Comment by daid** [comment]
I'm planning to update the GCode review properly for relative extrusion, as I use some relative extrusion in the "pause at height" function.

After that, adding a relative option somewhere deep in the settings wouldn't be a huge problem.

**Comment by daid** [comment]
I've fixed the relative extrusion GCode viewer in the main branch, and I've edited the dimension plugin to export an M83 when relative is selected. But there is no setting which sets it in the mainline yet.

My changes for relative extrusion where quite simple ;-)
