### ISSUE TITLE
"Unknown M code:109" seen after slicing file

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#26]
The exported file is saved as [...]
It took 28 seconds to export the file.
661496
Unknown M code:109
Extruded a total of: 717 mm of filament
Estimated print duration: 28.31 minutes

---

I do have "M109 S200" in my start.gcode.

**Comment by daid** [comment]
It's just a warning from the GCode parser that it encountered an M code it doesn't know. I've added an ignore like for other M codes that are not needed for the parser.
