### ISSUE TITLE
Cura 12.11 for Windows doesn't do retraction (at least not in project "all at once" mode).

### ISSUE THREAD

**Issue by calinb7** [daid/LegacyCura#261]
I upgraded from Cura 12.08 to 12.11  to avoid the "crash code" at the end of projects using "print all at once" mode.  I imported my settings from the .ini file.  Sadly, the Windows 12.11 version is not doing retraction at all (using the same project setup that I used in 12.08 where retraction worked).  I've moved back to 12.08 but must remember to edit out the crash code after each run of Cura project to avoid breaking my fan duct again. :(

However, I do like the individual skirts that 12.11 provided in project print all at once mode.  Please retain them, Daid!

**Comment by daid** [comment]
Hint, look at the new "retraction enable" option. It's a new option so you don't have to modify your retraction settings itself to turn retraction on/off.

**Comment by calinb7** [comment]
Okay--that makes sense, Daid!  The "brim" feature is great too.  Best way I've found to print my ABS parts (thanks to a hint from Joergen)!

--- On Sat, 11/17/12, daid notifications@github.com wrote:
