### ISSUE TITLE
Love this slicer but confused with the print control

### ISSUE THREAD

**Issue by hexitex** [daid/LegacyCura#262]
First of all - this is an excellent bit of programming and design -well done! Coming from skienforge and pronterface this is like the jump from windows 3.1 to windows 7

Questions:

What does the Temp & Bed spinner actually do, they don't allow big values to be typed in and the bed spinner just rolls to about 40 then back to 0? Very confusing as to what they actually do.

Feature requests:

Can there be a button or menu option to bring up print control without having to slice a model first? Maybe I am missing something, but seems like an obvious thing for warming things up or printer testing.

The jog buttons are far too small, there is a lot of empty screen estate there, can these be made bigger? 1080p on a laptop makes them very hard to read.

A length added to extrude/retract would be nice as well.

**Comment by daid** [comment]
(As far as I know, this has been solved. And I'm redesigning the printer interface window)
