### ISSUE TITLE
Cancel print does not turn off heated bed/hot end

### ISSUE THREAD

**Issue by richardjm** [daid/LegacyCura#263]
When cancelling a print I normally turn off the heated bed and hot end so I can do a cleanup. However i can't find a way to turn off the heater manually, even after closing the program the heater is still trying to maintain a temperature.

v 12.11

**Comment by daid** [comment]
In my experience you do a cancel to restart, at which point leaving the heater on makes for a faster restart.

You should have been able to turn the heater off with the spinner on the temperature tab, but something is causing that spinner to misbehave and reset itself unless you use the up/down arrows.

**Comment by richardjm** [comment]
OK that may explain it - as moving from 220 to 0 via the spinnies is not something I'd even considered - thanks.

**Comment by richardjm** [comment]
However I think my comment about turning off heaters when closing the program is still valid as this is a potential fire hazard.

**Comment by daid** [comment]
Turning off the heaters when closing would be a good extra safety feature. I'll see what I can do.

**Comment by richardjm** [comment]
Awesomesauce :)
