### ISSUE TITLE
Issue with centring at the beginning of print

### ISSUE THREAD

**Issue by Piers-Walter** [daid/LegacyCura#268]
There is an issue when I start my print, that I line up my base to the correct height for the nozzle with the jog setting. I click print, it then centres itself, losing the z height. I would prefer it to work more like replicatorG with regards to manually setting the X,Y and Z co-ordinates. The cura software has now damaged my base, by scratching it and ripping up the heat-conducting tape. This could be fixed by adding a tick box saying either manually set X,Y and Z or manually.

**Comment by daid** [comment]
For repeatability it's better to setup your endstops correctly. But if you preferer the manual mode, just remove the G28 home commands from the start code.
