### ISSUE TITLE
Cura can't connect to sanguinololu running the latest Marlin firmware on OSX

### ISSUE THREAD

**Issue by wisewolf** [daid/LegacyCura#269]
When I try to connect it says "Machine state: closed"
and the machine log says:

Changing monitoring state from 'Offline' to 'Opening serial port'
Connecting to: /dev/tty.usbserial-A50175HN
Connected to: Serial<id=0x10531f050, open=True>(port=u'/dev/tty.usbserial-A50175HN', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=2, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from 'Opening serial port' to 'Connecting'
Send: M105
Send: M105
Send: M105
Changing monitoring state from 'Connecting' to 'Closed'
Connection closed, closing down monitor

But with pronterface, replicatorg an even with the serial monitor from Arduino IDE just works.

**Comment by Lucastar-1** [comment]
Similar on Windows XP for me. 

Works up to 12.08, then not on newer releases :(

**Comment by wisewolf** [comment]
I've just tried with Sprinter and the connection went well, even with AUTO settings :p
Now I will try upload Marlin with EEPROM support on

**Comment by daid** [comment]
Small warning. The "AUTO" serial port setting only works with an ArduinoMega2560 bootloader.

However, it seems you have configured the serial port, as it is sending M105 command, but it is never getting an answer to the M105 command, it's not getting any data. No idea why. (I only have Ultimaker hardware to test on)

**Comment by wisewolf** [comment]
It could be some timeout setting? Or Cura is giving up the connection too early? It takes at least 6 seconds until something show's up on the console of Pronterface (firmware, version, etc).
Where can I change the timeout value?

**Comment by wisewolf** [comment]
Ok, I've fixed it!
In machineCom.py, line 283 was looking like this:

self._serial = serial.Serial(self._port, self._baudrate, timeout=2, writeTimeout=10000)

I've changed the timeout value to 0.1 and solved the problem :)

Now looks like this:

self._serial = serial.Serial(self._port, self._baudrate, timeout=0.1, writeTimeout=10000)

**Comment by daid** [comment]
Odd, changing that timeout value should make it harder to connect, not easier...

**Comment by wisewolf** [comment]
Yep, but it worked. I guessed if it worked for 115200 baud rate, I should try or the other baud rate.
It's even stranger when I've tried to connect at 115200 it didn't worked, but now it just works.

**Comment by atelles** [comment]
I'm also facing the same problem connecting to a Solidoodle 2.

I found the file in: _Cura.app/Contents/Resources/Cura/util/machineCom.py_
But how do I test it after changing the timeout?

Do I have to install the complete Development environment as described on the home?

My connection log:

> Changing monitoring state from 'Offline' to 'Opening serial port'
> Connecting to: /dev/tty.usbserial-AH01AXER
> Connected to: Serial<id=0x109890310, open=True>(port='/dev/tty.usbserial-AH01AXER', baudrate=250000, > bytesize=8, parity='N', stopbits=1, timeout=2, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
> Changing monitoring state from 'Opening serial port' to 'Connecting'
> Send: M105
> Send: M105
> Send: M105
> Changing monitoring state from 'Connecting' to 'Closed'
> Connection closed, closing down monitor

**Comment by daid** [comment]
The timeout is 5 seconds, and I have no idea why it takes the Solidoodle so long to respond. I've added a small patch to the code which sets the timeout to 15 seconds if you have entered a fixed baudrate instead of auto-detect.

**Comment by atelles** [comment]
Thanks, but to test it I have to install the dev environment, right?

Will do it tonight.

**Comment by daid** [comment]
For the Mac version you need the dev-environment. (For windows you could hack some files, as the install is vastly different between windows/mac/linux)

**Comment by atelles** [comment]
The environment setup took way more time that I expected, but now I have a working environment.

Your fix worked just fine! I'm now able to connect to my printer.

Thanks!

**Comment by vittotto** [comment]
The Zip is damaged, I have the same problem, help D:

**Comment by guysoft** [comment]
Hey, 
Just tried @wisewolf solution and it worked for me too! Using Octoprint from today `2013-06-17` Marlin.
This was from a Raspberry PI, and not OS X. Therefore the problem is not OS X specific.
