### ISSUE TITLE
Failed to install Python

### ISSUE THREAD

**Issue by somerwil** [daid/LegacyCura#270]
Here's my initial problem, copy-pasted from the Ultimaker forum. I found a solution myself, please see below

Problem:

I wanted to try the new Cura release on my Mac but Python keeps me from making any progress...
I downloaded the newest Cura and opened it. It says Cura 12.10 needs Python 2.7 to run. After I click OK it start runing the Python installation wizard which is pretty nice. Everything works up, even up to the point where the wizards says installation complete/ succesful/ something like that with a big green V mark showing in the screen. 

The problem succenly shows up when I close the window. I get a new dialog bow showing "Failed to install python 2.7" with no further reference...

It's not Cura related but I can't run Cura without Python. Any suggestions?

Solution

The Cura installer just tries to install the 64 bit version of Python which appears to be too new for my pretty old machine (iMac running on Mac 10.5.8 - Leopard). After Googling some detail of the error message this showed up somewhere on the internet. When I had a look at the Python installer box it also showed 10.6+ for the OS while mine is just 10.5'ish (didn't know that up to 15 minutes ago, sorry for being a nOOb ).

Ideas for the Cura installer:
Perhaps the installer can check on 32/ 64 bit machines and install the right Python version with it. Another solution would be to get some messages on the screen to help people getting Python installed correctly.

**Comment by daid** [comment]
Cura is only supported on Mac 10.6 or later. I should make this more obvious.

(Most likely you can get it to run on older versions, but supporting 10.6, 10.7 and 10.8 was a hell already)

**Comment by somerwil** [comment]
Hallo David,

dat wist ik niet... Ik probeer het nu ook terug te vinden maar ik zie het
nergens staan :-).

Nadat ik Python erop heb gekregen loopt nu Pypy te 'huilen'. Het heeft me
ertoe gebracht om Snow Leopard (OS 10.6) aan te schaffen.

Ik ben erg benieuwd naar Cura. Op mijn Windows laptop heb ik het geprobeerd
maar daarop is de USB verbinding naar de Ultimaker met alle programma's
(RepG, Netfabb en Cura) ronduit beroerd. Waarschijnlijk iets met mijn
laptop aan de hand... Op de Mac had ik die problemen allemaal niet.

Cura biedt een hele berg nieuwe, interessante ontwikkelingen. Mijn
favoriete Netfabb blijft daarbij wat achter.

Gr,
Michael

2012/11/24 daid notifications@github.com
