### ISSUE TITLE
What happened to dwindle?

### ISSUE THREAD

**Issue by Megane008** [daid/LegacyCura#271]
Hello

I would like to ask what happened to dwindle tool or setting in Cura, in 12.10 I cant find it anymore. And when I print tube like objects I get big weld where semicircles of layers connect? Or is there some new tool which can fix this? 

Thanks for reply

**Comment by daid** [comment]
Dwindle caused more problems then it fixed, so I removed it. (it caused a lot of under-extrusion) The "weld" you see is called the Z-seam, it happens where the head is lifted, you can reduce it by lowering the printing temperature and increasing the Z speed. The "joris" setting also helps against this seam, but in a different way.
