### ISSUE TITLE
start.gcode instructs 'G1 Z15' after homing with 'G28 Z0' previous to printing

### ISSUE THREAD

**Issue by Itchetiky** [daid/LegacyCura#272]
After first launching and running a new install of Cura v12.11 for OSX, Cura moved Z axis above print bed a distance and started printing.

After a few false starts using Cura and comparing G-Code Cura generated with that of another G-Code generator, I found that in Cura's start.gcode that after the G28 Z0 line, Cura was then running a G1 Z15 line.

Commenting out the G1 Z15 line caused Cura to start printing at a normal bed height.

Suggest removing this line from start.gcode.

**Comment by daid** [comment]
The start code is designed so it lifts the printer head above the bed. And the moves diagonally to the first place on the print. This is intentional so you have less chance to scratch tape or carve a line in it with a badly calibrated bed. The disadvantage is that it needs to move diagonal with Z, which not all firmwares might support. And that if the first point lays outside the print area, it will stop moving down (I know for sure with Marlin, might be different with other firmwares)

**Comment by Itchetiky** [comment]
So then as I understand the sequence; all axis are homed (X, Y, Z, and E
set to a software home of zero), the Z axis is lifted 15mm to facilitate a
safe move to the start of the next object to be printed, the move to the
start happens, and then the printing process starts.

The issue I'm having, which very well could be firmware related, is that Z
never comes back down once its lifted. The G1 Z15 occurs, but a
corresponding G1 Z0 never happens. The extruder tip is left raised above
the print bed.

I get your last point though. Using the project tool I laid out three parts
to print. My change to start.gcode brought the Z-axis back down and the
first part printing (though some infill was missed). However once the first
print finished the Z axis lifted again to facilitate the relocate, but the
bed was not moved to the new spot and instead start at the starting
location of the first print, and the Z axis (thankfully) remained in the
air while the extruder extruded.

It sounds like Cura isn't the tool for this job? I really like it. I like
the continuity that comes from one tool.

**Comment by daid** [comment]
Sounds like you have a firmware or mechanical issue, as the next thing after the start code should be a G1 with X Y and Z, which should put the head at the right location.

**Comment by Itchetiky** [comment]
Thanks for your feedback Daid. I'll look there too.
