### ISSUE TITLE
crash while loading damaged stl

### ISSUE THREAD

**Issue by bkubicek** [daid/LegacyCura#273]
I just noted that if you load an binary stl where the numer of faces indicated in the header is larger than  the faces actually in the file, cura crashes. A EOF check might be quite easy to implement.

I found out while trying to write stl files from c++, meshlab worked, many oder tools crashed. It is fixed in my code, but it would make  cura a tiny bit  better if it  deals with damaged stls.

**Comment by daid** [comment]
Only the load thread should crash, which should result in a "nothing happens!?!" reaction from the user. Not very nice, but the GUI keeps running.

But the loader could use a simple improvement for this case.
