### ISSUE TITLE
Cura throws errors slicing models

### ISSUE THREAD

**Issue by sixvolts** [daid/LegacyCura#274]
I cannot slice any of the STLs from the following model with Cura 12.11:

http://www.thingiverse.com/thing:30163

Cura says "Something went wrong during slicing!" and the log file appears empty when you click "show log" after the error appears.

Slices properly in the ReplicatorG Ultimaker Edition 0034 for windows

**Comment by brunovk** [comment]
I have the same problem with an object drawn in sketchup V8 and exported to stl with plugin (the one from ultimaker website). 
When I imported the file in Netfabb there where some errormessages, so I used the free cloud application of netfabb to repair the stl file. 
Afterwards I did not get error messages when importing the object in Netfabb,replicatorG and Cura (I know this is a Cura forum, but I thought to also give the history of the stl file I work with).
After opening the stl file in Cura and "prepare Print" it worked for about 5 hours and then I get the same failure as sixvolts.
The size of my object is 15x15cm and contains hyperbolic spirals.
The strange thing is that the slicing step is completely done but it is in the "speed" step.
My pc has 2Gb of memory works with Windows7 basic.
I also tryed it on a faster pc with 4Gb and Windows 7 Premium but the result is the same only something faster, after 4 in stead of 5 hour.

This is the only text in the log file:
File C:!!Data!!Testen_en_eigen_bevindingen\Windmolen\WindmolenHyperbool011untitled_fixed.stl is being chain exported.
Carve procedure took 31 minutes 3 seconds.
Preface procedure took 3 minutes 23 seconds.
Inset procedure took 1 hour 6 minutes 55 seconds.
Fill procedure took 2 hours 55 minutes 59 seconds.

**Comment by sixvolts** [comment]
I should add, the error on the STLs I'm trying to slice happens nearly instantly, no progress bars occur

**Comment by daid** [comment]
For the robot arm, it seems that the ó in the paths is causing the error. Replacing that with a normal o fixes the "something went wrong during slicing" error.

For the "slicing stops midway", that's an out of memory error. Simply limits of the current slicer that are not easy to solve. (Even with unlimited memory in your system, Cura for windows is limited to using 2GB)

**Comment by brunovk** [comment]
Thank you for the response.
Is the size of the stl file something to be taken into acount for a succesful slicing or is it really model related?
(I don't know how slicing goes to work to determine how the model is build)

**Comment by daid** [comment]
It is model related. The larger the volume of the model, and the more polygons it has, the more memory it will use.

**Comment by sixvolts** [comment]
Thanks for looking into it daid. Much appreciated.

**Comment by daid** [comment]
Note, I've also fixed the issue with the filenames for the next release (As I did this in the train, I failed to include the proper issue number in the commit)
