### ISSUE TITLE
Cura ToT not launching on OS X

### ISSUE THREAD

**Issue by bbum** [daid/LegacyCura#276]
Just did a pull, package and tried to launch.  Didn't work.

bbiMac:Cura.app bbum$ Contents/MacOS/Cura 
Traceback (most recent call last):
  File "Contents/MacOS/../Resources/Cura/cura.py", line 18, in <module>
    from util import profile
  File "/Volumes/Cura - Ultimaker/Cura/Cura.app/Contents/Resources/Cura/util/**init**.py", line 7, in <module>
    import power
ImportError: No module named power

**Comment by Itchetiky** [comment]
I received this same error message. I haven't delved into it much other then to try and find the module, which hasn't been successful at this time.

**Comment by Itchetiky** [comment]
Would this have anything to do with the addition of checking for connection to A/C power? Looking at the repo there was work done to detect connection to A/C power, perhaps that function isn't tuned yet?

Anyways, grep'ing for "import power" returned the following lines, which I've commented out, and things seem to be running again.

$ grep -r "import power" *
./Cura/Cura/gui/printWindow.py:#from util import power
./Cura/Cura/util/**init**.py:#import power

I'm not versed enough in git to push it back up so I'll leave this as a work around until it gets looked at.

**Comment by daid** [comment]
You need to checkout the submodules of the git repository.

**Comment by bbum** [comment]
Heh -- you are using parts of PyObjC now.  I took over maintenance of that in ~1993 from Guido and passed it on to Ronald Oussoren (fantastic guy) a few years ago.   Small world. :)

**Comment by Kentzo** [comment]
@bbum Power should be installed via pip now. It's not a submodule anymore. Take a look at requirements_darwin.txt
