### ISSUE TITLE
Fails to connect with Repetier firmware

### ISSUE THREAD

**Issue by dmopalmer** [daid/LegacyCura#277]
Cura cannot connect to Repetier firmware.

(Specific configuration: Mac OS X 10.8.2, RAMBO controller, Repetier-Rambo firmware)

The Repetier firmware, when passed an M105 command, returns two lines like

ok 0
T:14 B:-51 @:0

In machineCom.py:358, it is expecting a respons with both 'ok' and 'T:' in the same line.  Not seeing any olne line with both, it considers the connection attempt to be a failure.

**Comment by 3ntrlab** [comment]
I am getting same problems with Repetier FW...

**Comment by hg42** [comment]
see also pull request #687 which solves the connection issue for me.

But see my other issue about Repetier...

**Comment by hg42** [comment]
see issue #688

**Comment by nallath** [comment]
Issue #688 mentioned a fix, please check if this solved it.

**Comment by dmopalmer** [comment]
Both the latest 14.01 public release and a complete build from the master branch still fail to talk to the Repetier firmware.

It hangs on trying to connect with "Detecting Baudrate".

(Unless I'm building wrong.  The build gives Cura-14.02-RC5-MacOS.dmg, even though it is now March: 14.03)

**Comment by nallath** [comment]
The build only states when it was released. As it is essentially still the version of february, but with bug fixes, the number has not changed.

Have you tried manually selecting the baudrate?

**Comment by hg42** [comment]
at some point I tried to use Repetier firmware, because it seemed to solve some of my problems (e.g. USB-communication problems), but after a short rendezvous I switched back to Marlin, because Reptier didn't work with Cura, either.
So, I'm sorry, I can't tell if Repetier works better with Cura now.

**Comment by dmopalmer** [comment]
Now it hangs on "Opening Serial Port".

Opening the terminal in screen(1), I seem to get a periodic (every few seconds) 0xff and 0xfe characters. 
% screen /dev/tty.usbmodemfa121 250000,cs8
 I don't know if it is supposed to do that, or if it indicates that the RAMBO board is in a binary communications protocol mode.

**Comment by dmopalmer** [comment]
The board I am using is a RAMBo, if that matters.

When I have the baud rate at 250000, Cura cannot communicate in either baud-rate auto detect or explicit baudrate mode.  Furthermore, trying to talk to it with screen at that baud gives 0xfe and 0xff garbage.

I set the baud rate on the RAMBo to 115200.  At that speed, Cura 14.01 can communicate if I explicitly give it the baud rate, but not auto detect.  Screen at that baud rate gives normal informative text.

Cura 14.02 as built by me never connects.  But it has enough other problems that non-functionality isn't necessarily related to that.  (e.g. the Print... dialog box is only a few buttons and blank spaces, instead of the multi-paned window that Cura 14.01 brings up.)

**Comment by hg42** [comment]
You can switch the printing window from Basic to pronterFaceUI in Menu/File/Preferences.

On linux I need at least python-serial (or pyserial) version 2.7 to connect with 250000 baud.

screen doesn't work here, like many other terminal programs.
I think they cannot set 250000 baud.
minicom, gtkterm, cu have only baudrates up to 115200,
moserial, putty don't offer 250000,
cuteterm doesn't display my arduino USB-serial, etc.

The only working terminal I found was that from pyserial:
miniterm.py /dev/ttyACM1 250000
connects to my printer. see also: http://pyserial.sourceforge.net/examples.html
As I already said above I need pyserial 2.7 on linux.
