### ISSUE TITLE
QUESTION ON GCODE INTERPRETATION

### ISSUE THREAD

**Issue by rodrigopw** [daid/LegacyCura#278]
Dear Daid, 

Im using the 12.11 now with a Leapfrog Creatr, Im trying to do the same thing as the BST and Uprint does from stratasys does.

There are small deiferences but this one IS BIG and IMPORTANT.
As you will see, im still working with dentures, each denture , has an ID number on the bottom.
Stratasys Soft, and Cura, interpretate the number and Infill in a different way.
In the pictures im may be clear, but is difficult to explain.

WE, CURA, start the 20 % infill AFTER THE TOP OF THE NUMBERS.
ans STRATASYS, start the 20% Infill AFTER THE 2  bottom Layers.

THS IS A LOT OF TIME AND MATERIAL DIFFERENCE.

Cura KEEPS Making solid until the END TOP OF  THE NUMBER

Startasys, keeps making the number BUT the infill is already 20 % after the bottom layers...
Then makes te SOLID CLOSURE ON TOP OF THE NUMBERS ONLY....

WE CURA, keep the solid untill the top of the number..

HOPE YOU UNDERSTAND...

Best regards.

Rodrigo. 

https://www.dropbox.com/home/Public/CURA%20REPORT

**Comment by daid** [comment]
First may I point out that there IS NO NEED TO SHOUT ON THE INTERNET. We can hear you fine without it.

I think I understand what you are trying to show (I cannot view your dropbox link, it's not linked right I think) it's not something I can change right now, it's a fundamental implementation of the Slicer I'm using.

**Comment by rodrigopw** [comment]
I didnt meant to shout, its for Pointing or underline things...

https://www.dropbox.com/sh/gt3ef08rs5mffiw/NH6tMTt1LM/CURA%20REPORT

Hope it works now...

Thanks for your help...didnt mean to bother..

Best regards.

Rodrigo

**Comment by daid** [comment]
Ah, yes, that's the "solid tops are extended beyond parts", I cannot fix it as it's a fundamental part of the software I imported. (Which nobody fully understands, changing it would require a re-write)

As for pointing out things, you can use the markup for that: http://daringfireball.net/projects/markdown/syntax
**highlight** <- done with double asterics around the word.

**Comment by rodrigopw** [comment]
Thanks a lot for your support...
Rodrigo
