### ISSUE TITLE
Feature request: drag and drop

### ISSUE THREAD

**Issue by jgeerds-zz** [daid/LegacyCura#279]
It would be great to get drag&drop support for STL files and similar, both into the main window and the project planner

**Comment by daid** [comment]
Work in windows and Linux. We're working on it for MacOS.

**Comment by daid** [comment]
Drag&drop seems to be bugged in MacOS. No idea why. Dropping on the dock icon works.

**Comment by Kentzo** [comment]
Seems to be fixed now.
