### ISSUE TITLE
Nozzle size gone in  Cura 3ded5575843

### ISSUE THREAD

**Issue by jgeerds-zz** [daid/LegacyCura#28]
The machine settings are missing the nozzle size at the moment, are are they elsewhere now?

**Comment by daid** [comment]
Yes, I moved it to the preferences. Figured it made sense that all "machine dimension" settings where located there. Maybe tne "machine settings" tab is a bit misnamed at the moment.

**Comment by jgeerds-zz** [comment]
I am no fan of having the nozzle size in the preferences, in regards to the advanced settings, where, if you want to move it, it should belong.

**Comment by daid** [comment]
I've moved it back. Preferences was indeed not the best place. I'm also not a huge fan of placing it in the expert config. (which contain settings that you won't change under normal conditions)
