### ISSUE TITLE
Erratic temperature setting behavior for print head and bed

### ISSUE THREAD

**Issue by cbonsig** [daid/LegacyCura#283]
The temperature entry fields behave strangely, refreshing to 0 immediately after entering desired values, making it unclear if the setting has taken effect.

In older releases, in Print mode, the user could set the head temperature or heated bed temperature (if available) by typing the desired temperature in the entry field boxes, or by clicking the adjacent up/down arrows. Then the graph would update with line corresponding to the set point for each, as well as the current temperature of each. I don't remember exactly the old behavior - did the set value remain in the field, or did it refresh with the current value? I seem to recall the latter. 

On Linux, with 12.10 or with the current Github code, the entry fields are virtually unusable. After (or while) entering a value, the field entry boxes do not display the entered value, or the current value. Rather, they show zeros or other irrelevant values. In another twist, if I use the arrows to set the desired temperature, the settings do take effect for the nozzle temperature and heated bed set points. The set line appears for the nozzle, but not for the heated bed. Weird.

I think https://github.com/daid/Cura/issues/262 mentions the same behavior.

**Comment by daid** [comment]
Known problem. Fixed this in commit 2081a9cc9a808f9fa0f53f89125ed1a0c297394d
