### ISSUE TITLE
Slicing fail with AutoCAD 2012 .stl / Win7 64bit

### ISSUE THREAD

**Issue by deathblade6666** [daid/LegacyCura#285]
Generate Gcode work good with example .stl coming with cura, but it won't run with imported .stl from ACAD 2012, I'm getting a "Something went wrong during slicing!" with empty log. 
But cura can display the 3d object and it seems to be ok !

**Comment by daid** [comment]
How large is the STL file? Or maybe the path or the filename contains none-ascii characters?, this is causing problems in the latest release.

Finally, if that's not it maybe you can email it to me? (I'll keep it confidential, and delete it after testing&bugfixing)

**Comment by deathblade6666** [comment]
Ye, issue has beed caused by none-ascii characters in a folder name.
Thank you, problem solved :)
