### ISSUE TITLE
Error: Batch Run Estimating Cost And Filament Used

### ISSUE THREAD

**Issue by Macgyverzboss** [daid/LegacyCura#286]
Using the Batch Run tool on the mac Cura does not report the filament used and cost. In the prepared 

Gcode using batch run reports:
;Print time: #P_TIME#
;Filament used: #F_AMNT#m #F_WGHT#g
;Filament cost: #F_COST#
Using the standard prepare print (one at a time) results:
;Print time:     0:20
;Filament used:     1.57m    11.30g
;Filament cost:     0.35

Using The same file it shows correctly when I use the regular prepare print option.  Have not tested this on the Windows version yet. 

Also another Error that may be just the Mac version of Cura is the alternative to Batch Run would be to load a single file, prepare print, then repeat process. After doing this five times the progress bar and status for each prepared print will go off screen after the sixth prepared print. There is no way to scroll up and down to see all of the prepared prints.  This is also for the scrolling of Left to Right when you try to click the X button to close a finished prepared print. 
![Screen Shot 2012-12-12 at 9 20 34 AM](https://f.cloud.github.com/assets/3026684/8533/155f10ee-4478-11e2-9402-01d16a51318f.png)
![Screen Shot 2012-12-12 at 9 21 06 AM](https://f.cloud.github.com/assets/3026684/8534/1d409ae4-4478-11e2-86db-c640100bbf17.png)

**Comment by daid** [comment]
It's a known issue to me. It's a few stupid design issues I made.

**Comment by smorloc** [comment]
I reported a duplicate issue #320 and fixed it.
