### ISSUE TITLE
Extruder E to A option

### ISSUE THREAD

**Issue by Feist92** [daid/LegacyCura#289]
Would it be posible to ad the option to use A instead of E to controll the extruder? It would make it much nicer to use with mach3. Also could you shorted or breakup the ;CURA_PROFILE_STRING:  at the end of the code as mach3 wont load the gcode with such a long string

**Comment by daid** [comment]
A lot of code depends on the E value, so changing it somewhere could cause havoc everywhere. The profile string at the end is important for debugging issues as well as the "load profile from GCode"  feature and that MACH3 doesn't like it is a bug in MACH3.

You could write a post-processing plugin which does what you want. But I'm not going to support this as options.
