### ISSUE TITLE
slicing error with bridge: complete layer is considered a bridge

### ISSUE THREAD

**Issue by jgeerds-zz** [daid/LegacyCura#29]
I was slicing a battery/remote holder, with 2 horizontal holes in the side walls, and a larger slot for the power switch (19mm wide) across a 2mm thick wall.

settings:
0.1mm, 150mm/s
infill > loops > perimeter
bridge speed: 10%
bridge material: 200%

problem:
instead of just bridging the area/section that needs to be bridged, it bridged the complete layer, and due to my 200% extrusion rate, ruined the complete print: d'oh

bug solution: cura should only bridge where necessary, not everywhere, in addition to printing the perimeters/loops at the same slow speed as the bridge infill (right now, I think they are printed at full speed, which doesn't work at high speeds)

secondary issue:
This bridging technique (squiggly short lines like solid infill) is somewhat new to me, I always thought a bridge is more like long slow extrusions pulling the filament from A to B. with my print order above, the bridge infill has no loop or perimeter to hold on to.

Suggested bugfix:
override bridge areas to loop>perimeter>infill, making sure loop and perimeter are the same speed as bridge infill.

**Comment by daid** [comment]
Impossible to fix for me. Maybe Slic3r does a better job. I've seen Skeinforge do really stupid things with bridges/infill, but the whole infill code is a mystery to me.

**Comment by jgeerds-zz** [comment]
well, it was worth a try.
