### ISSUE TITLE
Feature request: Wipe like in Kisslicer

### ISSUE THREAD

**Issue by Intrinsically-Sublime** [daid/LegacyCura#291]
I would like to request a Wipe feature like in Kisslicer. It only has one entry field (distance) and when you have it set above zero it will backtrack over a path after retraction to ensure ZERO strings or bumps.

In other words: Have it backtrack a set number of mm along its previous path after retraction and before a travel move (and lift if enabled).

**Comment by BagelOrb** [comment]
Cura 2.4 will have a Wall wipe feature
