### ISSUE TITLE
Elementary Python module import question.

### ISSUE THREAD

**Issue by Itchetiky** [daid/LegacyCura#292]
Hi Daid and everyone,

I know this is pretty basic stuff. Unfortunately I'm a learn by doing sort of person.

I did a recent clone of your repo and found upon executing ./cura.command that I received this error message:

```
$ ./cura.command
Traceback (most recent call last):
  File "./Cura/cura.py", line 15, in <module>
    from Cura.util import profile
ImportError: No module named Cura.util
```

I can cheat and work around this by using sed to delete all the occurrences of 'Cura.util' but that's not the right way of doing things.

Googling shows that the import should work just fine.

My OS flavor is OS X 10.8.2 using the included Pyton version 2.7.

Thank you for your help, or any help that you can offer.

**Comment by daid** [comment]
The cura.command is outdated. The full instructions to get Cura running in a dev-environment are in the README.md
But the easiest way to get Cura running on the Mac is by getting the release from http://software.ultimaker.com/
