### ISSUE TITLE
dae file scales wrongly

### ISSUE THREAD

**Issue by maxwest** [daid/LegacyCura#295]
Hi there,

I just testet out the Sketchup Import. It works like a breeze. 

With some architectural backround I would love to see one thing though. Currently when importing a Collada dae file from Sketchup it needs a scale factor of roughly 0.25 to see one meter in Sketchup as 1cm on the Ultimaker. 

It would be great to have rather "real" scale factors. E.g. to get it in Utlimaker as 1cm = 1m the scale factor should be 1:100 which would be 0.01.

Thanks for your great work.

maxwest

**Comment by daid** [comment]
Already fixed for the next release ;-) the 12.11 release is importing inches as mm, so you need to scale it up by 25.4 or if you designed in meters, a scale factor of 0.254

**Comment by maxwest** [comment]
cool, thx
