### ISSUE TITLE
Full Window (+) extended invisibly on Mac OSx

### ISSUE THREAD

**Issue by maxwest** [daid/LegacyCura#296]
Hi there,

since you answered so rapidly on my last issue, I will just continue for the wider good :-)

When on MacOSX 10.8 the window is extended to full size with the green (+), then "prepare print" is pressed the "preparing processing" line is added underneath to the window making it invisible to see. That is also true for every additional "prepare processing" line.

When I was beginner that was very difficult to figure. I still today (after 4 weeks experience) think it is crashed many times. 

The "prepare processing" line should rather be within the full screen window and therefor reduce the viewport of the other  stuff.  

That will make handling cura yet even simpler for beginners and amateurs.

Thx 

Max

**Comment by daid** [comment]
Which version? As I added a fix for this somewhere, but it might not work in every MacOS setup.

**Comment by maxwest** [comment]
cura 12.11 MacOSx

**Comment by daid** [comment]
Ok, will look into it.

**Comment by daid** [comment]
(Cura no longer works like this as of 13.06)
