### ISSUE TITLE
input fields should have a white background

### ISSUE THREAD

**Issue by ErikDeBruijn** [daid/LegacyCura#3]
Right now, on MacOSX the fields have a grey background.
http://img818.imageshack.us/img818/3250/screenshot20120311at601.png

**Comment by daid** [comment]
I just pushed a change to github which might solve this issue. I've noticed the dropdown combo in WindowXP style also did not have the correct color. (hopefully this takes less commits then the OpenGL issue)

**Comment by ErikDeBruijn** [comment]
Yes, that fixed it for MacOS X (in a single commit)!
(confirmed on Lion)
