### ISSUE TITLE
thin walls and numbers of outlines used (gaps between 2 perimeters)

### ISSUE THREAD

**Issue by jgeerds-zz** [daid/LegacyCura#30]
https://picasaweb.google.com/lh/photo/W0brohD6QMSl3oDEXfNgQTIYJXjTqlQYmaNWFtjfw8o

I was getting random, and hard to explain thicknesses for thin walls, so I made a quick rake (ranging from 0.5mm to 3.0mm in 0.1mm steps), so see what each slicer is actually doing.

results are in the chart/link above. long story short, neither slic3r nor cura are doing a particular good job slicing thin walled objects, but it this chart may help to pick a certain wall thickness that will produce no gap in between.

Either slicer was set to 1.6mm walls or 10 perimeters, to ensure it's all walls.

in the long run, it would be great if the slicers would have some form of "gap avoidance" and/or at least to use infill or an extra line+combed jump.

you can download the STL at http://nypano.com/clients/UM/rake.stl

**Comment by RedwoodForest** [comment]
I figured I'd chime in and say that as far as I'm concerned this is one of the biggest basic functionality issues remaining with Cura. Any time I slice an object with small walls I have to mess around with the wall thickness to get it to fill in the small gaps in a reasonably manner.

That said, I know you've mentioned that this is an issue with Skeinforge and not an easy fix, so I understand your reasons for not addressing it.

**Comment by jgeerds-zz** [comment]
Having thought about the issue a little bit, I think I might have a solution how to eliminate any gap, and increase the resolution for fine details:

within SF (outline.py, or however it's called), instead of taking the nozzle/extrusion diameter as a fixed and unchangeable parameter, how about the section, that determines how many outlines are printed, would be able to divide the extrusion width in half or 1/4?

taking the examples (the rake) above, cura would be able to handle everything down to 0.2mm width: a part is 5mm wide, and then thins down to 1mm, and then down to 0.5mm (i.e. the panel mount hole for a headphone jack). SF/cura would start with 2 outlines (to make a 1mm wall on each side) plus some regular infill (3mm wide), then make 2_0.5mm outlines to make the 1mm wide section, and when it encounters a modulus=0 situation (width <= nozzle/extrusion), it simply cuts the extrusion width in half and renders the 0.5mm wide section as 2_0.25mm, which would print just beautifully. in theory it should be possible to go to a quarter, but that is speculative, and would require some real-world testing, but I don't want to dismiss it.

by dividing previously un-dividable outlines into thinner outlines, any gap can be filled, and smaller and thinner details on the outsides can be printed.

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
