### ISSUE TITLE
Cura 12.12 print dialog fails to appear

### ISSUE THREAD

**Issue by sixvolts** [daid/LegacyCura#300]
I'm running Cura 12.12 on a machine that has also ran 12.10, 12.11, and 12.08. On the newest release, nothing happens when you click the print button after slicing. 

Is there an error log I can look at to find out what is going on?

**Comment by daid** [comment]
Windows? I released a fix for that as 12.12A, for linux, grap the latest git repos which most likely solves it.

**Comment by Intrinsically-Sublime** [comment]
I can confirm it fixed it on linux as well.
