### ISSUE TITLE
Project planner settings inacuracy

### ISSUE THREAD

**Issue by lobster2b** [daid/LegacyCura#303]
The default measurements does not fit correctly on the ultimaker.

The labels does not inform if the measurements are from the center of the hot end assembly (where the axes meet) or the hot end its self.

The gantry height is false, my machine can fit at most a 55mm unit underneath the gantry

If you could tell me where the measurements are to be taken, i could provide you with my measurements.

My utlimaker is post hot end v2 and pre extruder v2

**Comment by daid** [comment]
The measurements are from the tip of the nozzle, and the defaults assume that you have put the fan on the left side of the head (some people, including myself, have it on the right, which does not match the assembly instructions)

**Comment by lobster2b** [comment]
Thanks for the clarification.

My measurements are: 
X tow. home:77
X tow. end: 20
Y tow. home:20
Y tow. end: 37
Z: 55

I hope you double check the numbers and commit them into the next version of cura.
Tnx for your reply

**Comment by daid** [comment]
I'm only measuring 16-18mm in X towards end. And same for Y towards home. With a rotated heater block. As these 2 measurements are most critical for how many objects you can fit on the bed, I find it odd that you measure 20mm, as that's much more then I see.

The fan is a bit longer indeed,  but for the Y tow. end I only see 34mm (which adds up, as the head size is 50mm)

The gantry height is currently not used for anything and really a placeholder. But I'm measuring 60mm there.
