### ISSUE TITLE
updating the tool tips after a value has changed

### ISSUE THREAD

**Issue by Intrinsically-Sublime** [daid/LegacyCura#304]
First off I would like to thank you for making Cura I am loving what you have done and the hack-ability.

I am trying to get the current calculated path width to display in the tool tip of wall thickness with:

```
        c = configBase.SettingRow(left, "Wall thickness (mm)", 'wall_thickness', '0.8', 'Thickness of the.....  .....perimeter lines.\n\nThe resulting extrusion width is %.3fmm' % (profile.calculateEdgeWidth())
```

It gives the correct results when you first open cura but it does not update when you change the wall thickness. You then have to restart cura to get the new value.

Is there a way to update the results? I am not really a programmer but I can hack my way through most things so even a hint would really help.

**Comment by daid** [comment]
Changing this would require quite a few code changes, as currently the basic tooltip is stored at startup without the way to modify it. But the "validators" allow dynamic values, could be worked into there, but would still be a bit of work.

**Comment by Intrinsically-Sublime** [comment]
Thank you it was easy to create a new validator that shows any and all results I wanted.
