### ISSUE TITLE
Fan control option

### ISSUE THREAD

**Issue by Intrinsically-Sublime** [daid/LegacyCura#305]
I hacked in a bit of code to allow you to control the fans based on the extrusion type. 
- Perimeter
- Fill
- Bridges
- Support

Its the way it is in Kisslicer and I really liked the results it gave. If you would like to try it my hacks are available:
- Bridge layer comments https://github.com/Intrinsically-Sublime/Cura/commit/8d55eecb19fef342876a2bf2bbcd9cae6a4d38f7
- Add the fan control https://github.com/Intrinsically-Sublime/Cura/commit/2907f4c9b1972d50badc52638adc7d15fc2e6fa7
- Disable SF control entirely and use the radio button to control my code https://github.com/Intrinsically-Sublime/Cura/commit/60af050849b7afffde2b3ea28a55da2f88cb19a7

I am not sending a pull request as I'm pretty sure my code is a hack and could be much cleaner. I did this in gcode_small.py as it was already processing the gcode from SF. I figure if you would like to try it to see the results you may want code it somewhere else.

**Comment by daid** [comment]
Holy hacks :P this is hacky.

I'm still wondering, does the fan off during infill really improve print quality? Because as far as I have seen this didn't make much of a difference.

**Comment by Intrinsically-Sublime** [comment]
I do like my fans on 100% when printing the perimeters because it gives a better finish and is not needed for that purpose on the fill. Because it is not needed on the fill it is nice to have it a little quieter by having the fans off. But also I added perimeter speed control and as you know when you slow down for the perimeter you need a lower temp and the fan does this by cooling the extruded filament faster and allowing faster infill extrusions because the fan is not cooling it.

Also Tantillus has two 15cfm fans which make the cooling really powerful.
