### ISSUE TITLE
New way of calculating the extrusion width

### ISSUE THREAD

**Issue by Intrinsically-Sublime** [daid/LegacyCura#306]
After many discussions on the RepRap forums about the extrusion widths I decided to try out a new way of calculating the width. It has an input for the nozzle diameter and an input for the die swell. It the adds the die swell to the nozzle diameter and uses that as the the max extrusion width. It then calculates the max height based on 66% of the max extrusion. Then it takes the the max layer height and a min layer height of 80 micron and divides the the die swell linearly between them. This means at max layer height it prints a path as wide as the nozzle + the die swell and it gets closer to the nozzle diameter as it gets closer to 80 micron layer height. Below 80 micron it prints at the nozzle diameter. Above the max height it prints at the max width.

I also changed it to use a single shell thickness value to calculate the perimeter and solid layer count based on the newly calculated extrusion width. It then rounds them off to be as close to the desired value as possible.

Again I did not know if this was something you were interested in or my quality of coding so I will just letting you know in case you want to try it out and maybe implement some of them if you like them.
- All in one big commit. https://github.com/Intrinsically-Sublime/Cura/commit/e56455c8475ef49ad2f03ed66f09f675745404e8

I also have a few other different ways of doing things and changes in my fork if you would like to take a look:
- Non invasive method of setting a Z offset using G92
- Perimeter speed setting with a patch to keep the speed of bridge and bottom layers at the same speed as the infill.
- Bottom layer temperature control
- Bridge speed to mm/s

**Comment by daid** [comment]
I do find this "die swell" interesting, got any links to the forum discussion on it?

**Comment by Intrinsically-Sublime** [comment]
There is not one single discussion about it but rather it comes up a lot. Mostly because of how many slicers use ratios based on layer heights and it causes the extrusion widths to get screwed up if they adjust one setting. Like Slic3r uses 200% first layer width but that only works with the default layer height and at .1mm you end up trying to print with a .2 extrusion.

My math is based on my experiences printing with a bowden machine and the resulting calculated widths for layers under 0.25 are what I would use for Tantillus and my Prusa. The max widths and heights are based off of the basics of how Nophead prints. That is he calculates the maximum width and then makes sure not to have the layer height greater than 66% of the width. 

So now we have one formula that creates good values for layers below 0.25 and should work for the maximum calculated height. But in between is anyones guess as I don't print over 0.25mm.

For the calculation to work correctly I enter the drilled diameter of the hotend. This means for the J-heads I use on Tantillus I enter 0.03mm less than the rated size as Brian drills them with under size bits to ensure they are never over the rated size. I then have the die swell value set to 0.15 even though you can get more die swell but i find it makes holes smaller and corners blobby etc.
