### ISSUE TITLE
'ascii' codec can't encode character u'\xe4'

### ISSUE THREAD

**Issue by rtaker** [daid/LegacyCura#307]
Hi I just wanted to bring your attention this little error: 'ascii' codec can't encode character u'\xe4' ... it occured in cura 12.12A when I wanted to prepare a print of a stl-file located in a folder having a german character like "ä" (was easily resolved after changing the name of the folder) ... it is not a major issue, but if the fix is not too difficult to do maybe you can consider including it in future versions! thanks and keep up the great work!

**Comment by daid** [comment]
You don't want to know how many of these I've encountered already, and they are all caused by Skeinforge code. Will be working on a fix.

**Comment by daid** [comment]
Fixed it for the next version.
