### ISSUE TITLE
Cura on Debian Wheezy

### ISSUE THREAD

**Issue by Intrinsically-Sublime** [daid/LegacyCura#308]
I just got a new laptop and Installed the latest Debian Wheezy (testing) and Cura will not run. I installed all the dependencies it asked for during the first few attempts and now it says.

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "Cura/gui/sliceProgessPanel.py", line 172, in run
    p = sliceRun.startSliceCommandProcess(self.cmdList[self.fileIdx])
  File "Cura/util/sliceRun.py", line 196, in startSliceCommandProcess
    return subprocess.Popen(cmdList, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Do you have any idea why? Is it still a dependency issue?

**Comment by daid** [comment]
Possibly you have installed a 64bit only system, and by default I package Cura with 32bit pypy. Try replacing the pypy with the 64bit pypy from pypy.org.

(Note, I'm currently changing a lot in how the slicer and the GUI are interacting, so it's not always safe to use the mainline source tree right now)

**Comment by Intrinsically-Sublime** [comment]
Thank you I will try 64bit pypy. Also this was with the precompiled ones available from your download page.

**Comment by Intrinsically-Sublime** [comment]
That was it thank you for the quick response and the accuracy of it.

**Comment by HuoSen** [comment]
could you provide more information on how did you install pypy? i got it installed but the installer cant find it.
what installer have you used? or what dependencies? 
i've checked all dependencies but i still get errors, pypy says  
pypy: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by pypy)
pypy: /lib/x86_64-linux-gnu/libc.so.6: version`GLIBC_2.15' not found (required by pypy)

and cura installer crashes
