### ISSUE TITLE
slicing does not (really) start

### ISSUE THREAD

**Issue by albert123** [daid/LegacyCura#309]
I just installed Cura 12.12A on an older laptop (windows XP home edition 2002).
With the makerbot model loaded, I press prepare print.
Then cura "says" Starting......, but nothing happens.

Ideas???

**Comment by Intrinsically-Sublime** [comment]
This is what was happening to me when I tried running the release on a 64 bit version of Debian Linux. The solution for me was to download and replace pypy with the 64 bit version.
