### ISSUE TITLE
Entering Values difficult in V12.12A

### ISSUE THREAD

**Issue by dipicorg** [daid/LegacyCura#311]
When trying to enter/change the Values in some Fields, the Cursor moves back and forward. It's very difficult to enter correct Values this way. I believe, it's the Checkfunction which evaluates the entered Value, that makes this Moves.

**Comment by daid** [comment]
This seems to be limited to your install, do you have any special software or keyboard layout installed that could be interacting with it in some strange way?
(Also, nothing has changed there between 12.10 and 12.12)

**Comment by dipicorg** [comment]
The Problem dissapeared after uninstalling all older Versions of Cura (12.08/12.10/12.11)
I don't know what triggered this behaviour... sorry. It's working now without Issues. Thanx!
