### ISSUE TITLE
Bottom layer speed issue

### ISSUE THREAD

**Issue by volunteerlabrat** [daid/LegacyCura#313]
I have just given Cura a shot over Slic3r today as I was fed up with stringing using Slic3r. 

I am running Cura 12.12 on a x64 mac.

When lowering the bottom layer speed setting I get a reduction in fast moves, but the speed of perimeters and infill of the first layer remain the same as the rest of the print job.

My bottom layer speed has been set to 5 mm/s and the speed throughout the rest of the job to 15 mm/s.

All the best.
 David

**Comment by daid** [comment]
Most likely it's the cool settings (and especially the minimal feedrate) causing this, see the expert settings.
