### ISSUE TITLE
Can Cura import .OBJ files?

### ISSUE THREAD

**Issue by StanleyKnife** [daid/LegacyCura#319]
It seems that Cura can now handle OBJ files, but when imported they look weird and slice in a bizarre way. I'd suggest either fixing the import capability, or disabling it entirely.

It would be really useful to be able to do so, however. I make a lot of my work in Poser and Photoshop, neither of which export STL files, so it means using NetFabb or MeshLab to convert them first.

Love the new functionality and appearance, by the way. A huge step forward. The SD card handling is particularly neat!

**Comment by daid** [comment]
Could you send me an example obj file that doesn't work? There are a few variations in obj files so there could be a variation that is causing a bug.

**Comment by StanleyKnife** [comment]
Sure. How shall I send it? I can't attach a file to this post.

**Comment by daid** [comment]
You can mail it to daid303@gmail.com

**Comment by StanleyKnife** [comment]
On its way

**Comment by daid** [comment]
Ok, thanks for the file (nice model btw, mind if I print one for the office at Ultimaker?)

I think I've found the problem, working on a fix.

**Comment by StanleyKnife** [comment]
Of, of course - do as you like with it! It's just a Poser model. 

One thing about Poser is it doesn't output flat bases. Netfabb has a really useful slicing feature, which allows the user to divide a model and discard part of it along a set axis. This would be great in Cura!

Incidentally, are there retraction issues with the new build? I attach a model I'm printing at the moment.
