### ISSUE TITLE
cura black screen

### ISSUE THREAD

**Issue by Tasker** [daid/LegacyCura#321]
hi when loading a model i just get a black screen

system info;
windows 7 64-bit
dell inspiron_5720
intel core i7-3612QM 2.1GHz
6 gb ram
intel HD graphics 4000

graphics drivers and DirectX installed and up to date, all windows updates performed 

any advice?

thanks
Matt

**Comment by Intrinsically-Sublime** [comment]
Have you tried starting it from a terminal to see if it gives any data that may help diagnose the issue.

**Comment by Tasker** [comment]
i have now got the screen to go grey and the display does not resize when you size the window if this makes sense, it is no longer black, i re intsalled and got this
![cura](https://f.cloud.github.com/assets/3268762/67167/a82ce958-5eec-11e2-8b3e-baaf6ba58d35.jpg)

wouldnt know how to start from terminal?

thanks

**Comment by daid** [comment]
In the cura installation location there is a Cura.bat, if you run that you will see the terminal.

**Comment by Tasker** [comment]
thanks for your reply 
when i run the cura.bat file the window opens and closes so quickly i cand read it, im guessing that it should stay open?

**Comment by Tasker** [comment]
i run the cura.bat now and cura opens like this. the .bat window shows no text. thi is what i get;
![curabat](https://f.cloud.github.com/assets/3268762/67786/d45769f0-5f18-11e2-8b5e-c82b2aeecfd2.jpg)

**Comment by daid** [comment]
Could you check C:\Program Files (x86)\Cura_12.12A if there is an output.txt there, and if it contains info?

**Comment by Tasker** [comment]
there is a output.txt contains a tone of info i cant begin to understand, what am i looking for?

**Comment by Tasker** [comment]
this is the last section of information added to the file;
not sure if its any use to you.

OpenGL.error.Error: Attempt to retrieve context when no valid context
Traceback (most recent call last):
  File "Cura\gui\preview3d.py", line 504, in OnMouseMotion
    p0 = numpy.array(gluUnProject(e.GetX(), self.viewport[1] + self.viewport[3] - e.GetY(), 0, self.modelMatrix, self.projMatrix, self.viewport))
  File "C:\Program Files (x86)\Cura_12.12A\python\lib\OpenGL\latebind.py", line 61, in **call**
    return self.wrapperFunction( self.baseFunction, _args, *_named )
  File "C:\Program Files (x86)\Cura_12.12A\python\lib\OpenGL\GLU\projection.py", line 62, in gluUnProject
    raise ValueError( """Projection failed!""" )
ValueError: Projection failed!
Traceback (most recent call last):
  File "Cura\gui\preview3d.py", line 504, in OnMouseMotion
    p0 = numpy.array(gluUnProject(e.GetX(), self.viewport[1] + self.viewport[3] - e.GetY(), 0, self.modelMatrix, self.projMatrix, self.viewport))
  File "C:\Program Files (x86)\Cura_12.12A\python\lib\OpenGL\latebind.py", line 61, in **call**
    return self.wrapperFunction( self.baseFunction, _args, *_named )
  File "C:\Program Files (x86)\Cura_12.12A\python\lib\OpenGL\GLU\projection.py", line 62, in gluUnProject
    raise ValueError( """Projection failed!""" )
ValueError: Projection failed!
Traceback (most recent call last):
  File "Cura\gui\preview3d.py", line 504, in OnMouseMotion
    p0 = numpy.array(gluUnProject(e.GetX(), self.viewport[1] + self.viewport[3] - e.GetY(), 0, self.modelMatrix, self.projMatrix, self.viewport))
  File "C:\Program Files (x86)\Cura_12.12A\python\lib\OpenGL\latebind.py", line 61, in **call**
    return self.wrapperFunction( self.baseFunction, _args, *_named )
  File "C:\Program Files (x86)\Cura_12.12A\python\lib\OpenGL\GLU\projection.py", line 62, in gluUnProject
    raise ValueError( """Projection failed!""" )
ValueError: Projection failed!

**Comment by daid** [comment]
That is of use, but now I'm also interested in the first section of the file, as this error is the result of an other error that should have happened before that.

**Comment by Tasker** [comment]
have you got an email i can send the file too as its too big to paste in here?

**Comment by daid** [comment]
Sure, daid303@gmail.com

**Comment by Tasker** [comment]
sent

**Comment by daid** [comment]
received. Looks like something odd is going wrong when creating the OpenGL context. Not sure why, might be related to the intel graphical drivers

**Comment by Tasker** [comment]
my Intel graphic drivers are up to date, is there anything you can suggest i try?

**Comment by daid** [comment]
Could you email the output of dxdiag (windows key + R -> "dxdiag". Then use the "save all" button)

**Comment by Tasker** [comment]
sent

**Comment by Tasker** [comment]
just checking the file sent?

**Comment by daid** [comment]
Yes, got it. Didn't find the time to look at it earlier. Not noticing anything odd, except that I have almost the same card in my laptop, but the drivers used in mine are a slightly different one then in my card.

Still, the initial output.txt log is bothering me, what I'm seeing there indicates something goes wrong in gluUnproject, which is odd, as that should be a very simple function.
(It's very difficult to solve these kinds of issues without having a machine to reproduce it on, so I'm doing my best. And have an idea what I can change, but I cannot guarantee that I can solve it)

**Comment by adhesiu** [comment]
Hi, congratulations for the Cura interface!
I have the same problem than Tasker. In my laptop appears a black screen in the 3d preview (only black, no gray). In my desktop computer runs correct.

If it helps, to compare:

System info:

Acer Aspire 5741
Microsoft Windows 7 Home Premium (x64) Build 7601
Intel Core i3-330M (2133.3 MHz)
Acer Aspire 5741 (Intel HM55 (IbexPeak-M DH))
Intel Auburndale/Arrandale Processor - Integrated Graphics Controller [C2] [ACER]

Output.txt:

Traceback (most recent call last):
  File "Cura\gui\preview3d.py", line 504, in OnMouseMotion
    p0 = numpy.array(gluUnProject(e.GetX(), self.viewport[1] + self.viewport[3] - e.GetY(), 0, self.modelMatrix, self.projMatrix, self.viewport))
  File "C:\Program Files (x86)\Cura_12.12A\python\lib\OpenGL\latebind.py", line 61, in **call**
    return self.wrapperFunction( self.baseFunction, _args, *_named )
  File "C:\Program Files (x86)\Cura_12.12A\python\lib\OpenGL\GLU\projection.py", line 62, in gluUnProject
    raise ValueError( """Projection failed!""" )
ValueError: Projection failed!

(there are the same paragraph several times)

Thanks!

**Comment by Tasker** [comment]
Mine was originally black
I uninstalled 12.12a and tried 12.11, same screen so I went back to 12.12a and its now grey, I presume it's the same issue with graphics drivers?

**Comment by daid** [comment]
So far it indicates something goes wrong in the gluUnproject. So I'm going to replace that function with something else.

**Comment by adhesiu** [comment]
Updated opengl.py and preview3d.py. Execute cura, and the result is the starting logo of "Cura Loading...". Does not continue with the interface.

Output.txt:
IndentationError: expected an indented block
Generating comtypes.gen._683BF642_E9CA_4124_BE43_67065B2FA653_0_1_0
Generating comtypes.gen.TaskbarLib
Traceback (most recent call last):
  File "Cura\gui\preview3d.py", line 612, in OnPaint
    self.OnDraw()
  File "Cura\gui\preview3d.py", line 645, in OnDraw
    opengl.DrawMesh(obj.mesh)
  File "Cura\gui\util\opengl.py", line 328, in DrawMesh
    glVertexPointer(3, GL_FLOAT, 0, mesh.vertexes)
  File "C:\Program Files (x86)\Cura_12.12A\python\lib\OpenGL\latebind.py", line 45, in __call__
    return self._finalCall( _args, *_named )
  File "C:\Program Files (x86)\Cura_12.12A\python\lib\OpenGL\wrapper.py", line 724, in wrapperCall
    cArguments,
  File "C:\Program Files (x86)\Cura_12.12A\python\lib\OpenGL\arrays\arrayhelpers.py", line 153, in __call__
    contextdata.setValue( self.constant, pyArgs[self.pointerIndex] )
  File "C:\Program Files (x86)\Cura_12.12A\python\lib\OpenGL\contextdata.py", line 57, in setValue
    context = getContext( context )
  File "C:\Program Files (x86)\Cura_12.12A\python\lib\OpenGL\contextdata.py", line 40, in getContext
    """Attempt to retrieve context when no valid context"""
OpenGL.error.Error: Attempt to retrieve context when no valid context
Traceback (most recent call last):
  File "Cura\gui\preview3d.py", line 504, in OnMouseMotion
    p0 = numpy.array(gluUnProject(e.GetX(), self.viewport[1] + self.viewport[3] - e.GetY(), 0, self.modelMatrix, self.projMatrix, self.viewport))
  File "C:\Program Files (x86)\Cura_12.12A\python\lib\OpenGL\latebind.py", line 61, in **call**
    return self.wrapperFunction( self.baseFunction, _args, *_named )
  File "C:\Program Files (x86)\Cura_12.12A\python\lib\OpenGL\GLU\projection.py", line 62, in gluUnProject
    raise ValueError( """Projection failed!""" )
ValueError: Projection failed!
Traceback (most recent call last):
  File "C:\Program Files (x86)\Cura_12.12A\python\lib\site-packages\wx-2.8-msw-unicode\wx_core.py", line 14660, in <lambda>
    lambda event: event.callable(_event.args, *_event.kw) )
  File "Cura\gui\splashScreen.py", line 16, in DoCallback
    self.callback()
  File "Cura\gui\app.py", line 41, in afterSplashCallback
    from Cura.gui import mainWindow
  File "Cura\gui\mainWindow.py", line 12, in <module>
    from Cura.gui import preview3d
  File "Cura\gui\preview3d.py", line 12
    import OpenGL
         ^
IndentationError: expected an indented block

**Comment by daid** [comment]
Updating selective files will break stuff, but the indent error is most likely a copy/paste or saving error.

**Comment by Tasker** [comment]
sorry about my lack of knowledge on the subject... but what do i do with this replacement, i presume i copy it somwhere?   thanks :)!

**Comment by daid** [comment]
Because I changed not a tiny bit, but a lot of things, and things are a bit in a broken state right now, it's better to wait for a release. (Kinda sucks, I know)

**Comment by Tasker** [comment]
ok no worries, any idea when that will be?

thanks!

**Comment by daid** [comment]
Hopefully at the end of january

**Comment by Tasker** [comment]
WORKING!! just downloaded the software again and its not working, i presume you have updated it? i have not touched my computer since i last tried.

**Comment by daid** [comment]
Nope, not changed a thing in the released version.
