### ISSUE TITLE
not an issue but....

### ISSUE THREAD

**Issue by jfpion** [daid/LegacyCura#325]
I've got an old hp pavilion hdx9000 recently upgraded to ubuntu 12-10. 

i've downloaded the package for linux .

ok and now ?  tried to execute cura .sh but nothing happen 

how to install it ? i'm totally newby with ubuntu (and it's far from the windows click and use system )

thank you

**Comment by daid** [comment]
The linux install is hardly user-friendly. And without some proper linux experience is almost impossible to get running at the moment.

But you should run cura.sh in a terminal, then it should tell you what it's missing and what it needs to run.

**Comment by daid** [comment]
(And I do think "linux install currently is hard" is a real issue)

**Comment by jfpion** [comment]
OK I will try

I tried too to install pronterface on ubuntu but even the automatic script failed (said it can't create directory)

isn't it possible on linux to have simple installation file with all the package as for windows ? I know correct install is more logical and save hard disk room but now it is hardly a problem

thank you

**Comment by daid** [comment]
Problem with linux is that every distro has their own installation stuff, and even if you try to package everything with it, some stuff won't work because it's not in the expected paths.

There is also the issue that I have very few linux users. So putting a lot of effort into linux support does not feel like the best use of my time.

**Comment by jfpion** [comment]
OK i will try to make it work on my win 7, seems there is pb too (I will open an new thread )

**Comment by Intrinsically-Sublime** [comment]
It runs with ease on both Linux mint 12 (ubuntu 11 base) and debian 7 (wheezy)

Step 1 download Cura
Step 2 download Power and place in Cura directory
Step 3 open terminal an cd to the Cura directory
Step 4 open GUI file manager (Nautilus or files) to Cura directory
Step 5 open Power folder in Cura
Step 6 drag linux.py into the terminal window and release
Step 7 press enter in the terminal window
Step 8 drag common.py into terminal window and release
Step 9 press enter in the terminal window
Step 10 switch back to the Cura directory in the GUI
Step 11 drag Cura.sh into the terminal and release
Step 12 press enter in the terminal window

Now it should either run or give some feedback
If you are running 64bit you may need to replace the pypy folder in cura with the 64bit one from pypy's website.

If you get a message saying you are missing something you then open synaptic package manager and search for it and install it. Then go back into the terminal and try again. (note in terminal all you do is press the up arrow key to go through previously typed commands to avoid the extra work.

With the power folder in the Cura folder, Cura must be launched from the folder it is in either by clicking it in the file manager or using terminal and cd'ing to the directory before launching Cura.sh

**Comment by daid** [comment]
power can also be installed with pip, by "pip install power"

**Comment by Kentzo** [comment]
The recommended way to install requirements on Linux is to use `pip install -r requirements.txt`
To install power only you use `pip install -e git+git://github.com/GreatFruitOmsk/Power.git#egg=Power`
(Power is not published at pypi yet, because it depends on PyObjC 2.5 for Mac OS X)

**Comment by jfpion** [comment]
OK guys, you linux guru !
first what's power ? how to download it ?  (look like a philosophical questionning ;-)  )
what's pip ? how to install it

I try this : 
hp@HDX9000:~$ sudo pip install -e git+git://github.com/GreatFruitOmsk/Power.git#egg=Power
[sudo] password for hp: 
sudo: pip: command not found

so what's now ?

i just install synaptic (pas installé d'origine sur ubuntu 12-10 but no power or pip (lot of things for power management but i dont think that's that

I promise I will do a step by step install on ubuntu how to ! as soon as it works

**Comment by Kentzo** [comment]
`pip` is a tool to install and manage python packages: http://www.pip-installer.org/en/latest/
`power` is a python package we use to check whether your computer is connected to AC power source.

**Comment by jfpion** [comment]
first i had to install curl
sudo apt-get install curl
after that i did:
~$ curl http://python-distribute.org/distribute_setup.py | python which fail and so pip can't be installed
~$ curl https://raw.github.com/pypa/pip/master/contrib/get-pip.py | python failed with the same message:

hp@HDX9000:~$ python distribute_setup.py
Extracting in /tmp/tmpXzOxxG
Now working in /tmp/tmpXzOxxG/distribute-0.6.34
Installing Distribute
Before install bootstrap.
Scanning installed packages
No setuptools distribution found
running install
Checking .pth file support in /usr/local/lib/python2.7/dist-packages/
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

```
[Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/test-easy-install-4366.pth'
```

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

```
/usr/local/lib/python2.7/dist-packages/
```

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  http://packages.python.org/distribute/easy_install.html

Please make the appropriate changes for your system and try again.

Something went wrong during the installation.
See the error message above.

so I can't install power so i can't install cura so i'm stuck

is there a way to directly get the power files ?

(because I can't find it even in the package index in http://pypi.python.org
may be i've seen it without knowing it's it 

i've got (i don't know why python 2.7 and 3.2 installed may be it is the cause of the pb ?

**Comment by Kentzo** [comment]
You can obtain files here: https://github.com/Kentzo/Power/tree/master/power
But I don't know what you are going to do with them. You will have the same permission denied error once you try to install it, because seems your installation of python requires admin rights to install packages.

Try to install pip with sudo: `sudo python distribute_setup.py`

**Comment by jfpion** [comment]
Le 17/01/2013 19:21, Ilya Kulakov a écrit :

> You can obtain files here: 
> https://github.com/Kentzo/Power/tree/master/power
> But I don't know what you are going to do with them. You will have the 
> same permission denied error once you try to install it, because seems 
> your installation of python requires admin rights to install packages.
> 
> Try to install pip with sudo: |sudo python distribute_setup.py|
> 
> ---
> 
> Reply to this email directly or view it on GitHub 
> https://github.com/daid/Cura/issues/325#issuecomment-12381312.
> 
> already tried (in fact i start with that, that the only thing i know 
> about ubuntu !

## 

JF Pion

_*
__Print "_Bonne année 2013*"

IF "_La santé est bonne_" ALORS
     " _Continuer à profiter_"*
_"_Réaliser de beaux projets_"
Sinon
     "_Appeler SOS Médecins*"
Fin SI

While 2013 n'est pas fini
     "_Attendre 2014_"
WEND

(ninos)

Des montages électroniques pour le modélisme 
http://jean.francois.pion.free.fr
le site du vol électrique http://electrofly.free.fr/

**Comment by Intrinsically-Sublime** [comment]
Have you tried my method that involves zero installing. Just download power and use it like I explained above.

**Comment by jfpion** [comment]
Le 17/01/2013 22:27, Sublime a écrit :

> Have you tried my method that involves zero installing. Just download 
> power and use it like I explained above.
> 
> ---
> 
> Reply to this email directly or view it on GitHub 
> https://github.com/daid/Cura/issues/325#issuecomment-12392572.
> 
> not for now just got the link to download power directly

but I will (not tonight i'm working )

## 

JF Pion

_*
__Print "_Bonne année 2013*"

IF "_La santé est bonne_" ALORS
     " _Continuer à profiter_"*
_"_Réaliser de beaux projets_"
Sinon
     "_Appeler SOS Médecins*"
Fin SI

While 2013 n'est pas fini
     "_Attendre 2014_"
WEND

(ninos)

Des montages électroniques pour le modélisme 
http://jean.francois.pion.free.fr
le site du vol électrique http://electrofly.free.fr/

**Comment by jfpion** [comment]
doesnt work permission denied when draging linux.py in terminal, with sudo : command not found if i try to drag cura.sh in terminal it said no module named opengl require popengl suggest sudo easy_install-2.7 PyOpenGL but command not found 

I give up 

probably go back to win7 as it seems ubuntu is unusable for normal people ..:-/

**Comment by Intrinsically-Sublime** [comment]
All you need to do now is open synaptic and install pyopengl and you will be ready to go.

Also this is not a Ubuntu issue but rather a Cura issue not having all the requirements that is is supposed to be packed with as advertised.

**Comment by jfpion** [comment]
Le 18/01/2013 20:33, Sublime a écrit :

> All you need to do now is open synaptic and install pyopengl and you 
> will be ready to go.
> 
> Also this is not a Ubuntu issue but rather a Cura issue not having all 
> the requirements that is is supposed to be packed with as advertised.
> 
> OK will try but synaptic is not default installed and after installation 
> said it's not allowed to install package, must be a way to run it as 
> administrator but i don't know how

I will search !

## thank you

JF Pion

_*
__Print "_Bonne année 2013*"

IF "_La santé est bonne_" ALORS
     " _Continuer à profiter_"*
_"_Réaliser de beaux projets_"
Sinon
     "_Appeler SOS Médecins*"
Fin SI

While 2013 n'est pas fini
     "_Attendre 2014_"
WEND

(ninos)

Des montages électroniques pour le modélisme 
http://jean.francois.pion.free.fr
le site du vol électrique http://electrofly.free.fr/

**Comment by Intrinsically-Sublime** [comment]
To run things as admin from the command line (terminal) you put sudo before the command (means super user do). To run things from inside of the desktop as admin you can press ctrl+f2 and it will open a run dialog. You can then type in gksu and the command and it will be executed as admin (means Gnome keyring super user).

eg. "sudo apt-get install synaptic" installs synaptic from the command line
eg "gksu gedit" opens the Gnome text editor as admin inside the desktop

Hope this helps. If not let me know and I will try and help out.

**Comment by jfpion** [comment]
Le 20/01/2013 00:00, Sublime a écrit :

> To run things as admin from the command line (terminal) you put sudo 
> before the command (means super user do). To run things from inside of 
> the desktop as admin you can press ctrl+f2 and it will open a run 
> dialog. You can then type in gksu and the command and it will be 
> executed as admin (means Gnome keyring super user).
> 
> eg. "sudo apt-get install synaptic" installs synaptic from the command 
> line
> eg "gksu gedit" opens the Gnome text editor as admin inside the desktop
> 
> Hope this helps. If not let me know and I will try and help out.
> 
> I wil try, many thanks

## 

JF Pion

_*
__Print "_Bonne année 2013*"

IF "_La santé est bonne_" ALORS
     " _Continuer à profiter_"*
_"_Réaliser de beaux projets_"
Sinon
     "_Appeler SOS Médecins*"
Fin SI

While 2013 n'est pas fini
     "_Attendre 2014_"
WEND

(ninos)

Des montages électroniques pour le modélisme 
http://jean.francois.pion.free.fr
le site du vol électrique http://electrofly.free.fr/

**Comment by jfpion** [comment]
sorry still not working
hp@HDX9000:~$ cd Cura
hp@HDX9000:~/Cura$ '/home/hp/Cura/power/linux.py' 
bash: /home/hp/Cura/power/linux.py: Permission non accordée
hp@HDX9000:~/Cura$ sudo '/home/hp/Cura/power/linux.py' 
sudo: /home/hp/Cura/power/linux.py: command not found

i found pypy was not installed so i did , no change 
if i try to launch cura.sh I got:

hp@HDX9000:~/Cura$ '/home/hp/Cura/cura.sh' 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy
Requires numpy.
hp@HDX9000:~/Cura$ 

can't find numpy in synaptic

I clearly missed something but what

thank you

**Comment by Intrinsically-Sublime** [comment]
OK for the permission issues you will need to run them as sudo

For numpy in my synaptic it shows up as python-numpy
To ensure you have everything possible available in Synaptic you should click Settings/Repositories and then in the first tab make sure contrib and non-free are checked. Then in the updates tab you should have the recommended updates and security updates checked. The other one will give you more but could offer some things that could break your system. Then press the reload button in Synaptic before searching for anything you can not find.

**Comment by jfpion** [comment]
the sudo trick doesn't work etheir

hp@HDX9000:~/Cura$ sudo '/home/hp/Cura/power/linux.py'
sudo: /home/hp/Cura/power/linux.py: command not found

or i do it wrong ?

**Comment by Intrinsically-Sublime** [comment]
No that is fine. It just sets the relative path to the power modules. Now try running Cura.

**Comment by jfpion** [comment]
ok i will get numpy and try again
thank you

**Comment by jfpion** [comment]
ok it's working (just need to get python_numby, not pithon3_numby !)

anyway ther is still a pb :+1: 

I try to slice http://www.thingiverse.com/thing:5011

and i get an error something went wrong when slicing  and the log is :

Traceback (most recent call last):
  File "app_main.py", line 51, in run_toplevel
  File "/home/hp/Cura/pypy/lib-python/2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/hp/Cura/pypy/lib-python/2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/hp/Cura/Cura/cura.py", line 78, in <module>
    main()
  File "/home/hp/Cura/Cura/cura.py", line 67, in main
    sliceRun.runSlice(args)
  File "Cura/util/sliceRun.py", line 89, in runSlice
    skeinforge_craft.writeOutput(fileName)
  File "Cura/cura_sf/skeinforge_application/skeinforge_utilities/skeinforge_craft.py", line 133, in writeOutput
    return pluginModule.writeOutput(fileName, shouldAnalyze)
  File "/home/hp/Cura/Cura/cura_sf/skeinforge_application/skeinforge_plugins/craft_plugins/export.py", line 266, in writeOutput
    print('File ' + archive.getSummarizedFileName(fileName.encode('ascii', 'replace')) + ' is being chain exported.')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 10: ordinal not in range(128)

when i move the stl file from "Téléchargement" to home the slicing go nicely
I suppose it is a bug with the é letters

sorry but the automatic installation of ubuntu use the french words

**Comment by jfpion** [comment]
I will made the cura unbuntu's install guide for noobs as soon as i got some time

thank you a lot

**Comment by Intrinsically-Sublime** [comment]
I have received that message after playing with the git head version. To fix it delete everthing in the Cura folder except the power folder and download 12.12 Cura linux again from http://daid.github.com/Cura/ and put it in the same folder as the old one with the Power folder.

**Comment by jfpion** [comment]
ok 
I will do
but it is not a big pb as long as you know you need to use folder with non accentued characters

thank you
