### ISSUE TITLE
Feature request - speed compensation based on path complexity

### ISSUE THREAD

**Issue by melk-** [daid/LegacyCura#326]
A toggle that would allow an option to slice with speed control on outer perimeters and skin. The speed control would automatically adjust and slow down on complex moves or sharp changes in direction, then gradually speed up on less complex moves. This would improve quality in tight areas by simply slowing down and also reducing vibration. Because stl files seem to use line segments/triangles, the formula would have to revolve around the inflection between line sgments along the toolpath of each slice and possibly the length of each line.

**Comment by daid** [comment]
Firmware does this due to acceleration settings.
