### ISSUE TITLE
2nd Extruder

### ISSUE THREAD

**Issue by bsrhaann** [daid/LegacyCura#327]
Does Cura Support a second extruder for raft, support, and infill creation.  I would like to try and make a model on a PLA raft with ABS solid layers and perimeters, but infill the model with PLA.  Is this possible??

Brandon
Precision Design

**Comment by daid** [comment]
For support yes, infill and raft not.

**Comment by bsrhaann** [comment]
Daid,

Is it possible to add a plugin for infill and raft with 2nd extruder capabilities??

Thanks,

Brandon Shannon
PRECISION DESIGN
Cell – (269) 720-0384 
Office – (269) 389-0384
Fax - (877) 351-1683
Brandon@PrecisionDesignMI.com
www.PrecisionDesignMI.com

**Comment by Intrinsically-Sublime** [comment]
You should be able to use the replace function to replace the comment titles that indicate the path type with tool change commands. This would be far easier with Relative extrusion because you would not have to worry about the E value needing reset etc.

**Comment by daid** [comment]
The replace.csv way would be hard, as you also have to offset the paths for the printer head offset. A plugin should be possible, but requires quite a bit of work. Especially the infill is a tough one.

**Comment by daid** [comment]
Also, got some suggestions for dual extrusion in the mail, so adding them here:
- Ability to select primary extruder (or only extruder used) so you can have 1 head for PLA and 1 for ABS all the time
- Ability to configure a temperature per extruder
- Filament diameter per extruder

**Comment by bsrhaann** [comment]
Daid,

I am driven to get this completed.  I am confident that a Shelled ABS Part with PLA infill will be a real improvement.  You would have the surface properties of abs for wear and the support of the more stable (Less Warp) from its interior construction.  Now I think this would be easier with relative positioning since you would just have to input a G1 X78 Y2 Offset for my 2nd head position and a T1 S240 for head control at the beginning of each targeted section and inversely to switch back.  The question is to have the software recognize the Solid Layers at (top and bottom) and the perimeters which you have already commented out in the code so it should be possible but I am not a software programmer so I don’t know where to start.

Brandon Shannon
PRECISION DESIGN
Cell – (269) 720-0384 
Office – (269) 389-0384
Fax - (877) 351-1683
Brandon@PrecisionDesignMI.com
www.PrecisionDesignMI.com

**Comment by daid** [comment]
Relative position was proven to be unreliable for X/Y/Z a long time ago.

What you need is the tool offset in the firmware, so you can switch the tool and the firmware handles the offset. There is a marlin branch that can do this, but it's not in the mainline yet.

Detecting the difference between up/downskin (as the solid layers are called) and sparse infill in SF proved to be too difficult. So that will need a new slicer.
