### ISSUE TITLE
Glut error error on git head master 138af904488ae78cffa7869573227cc7667d0ffa

### ISSUE THREAD

**Issue by Intrinsically-Sublime** [daid/LegacyCura#328]
Git commit 138af904488ae78cffa7869573227cc7667d0ffa

I decided to try out the latest commits to see what you have changed and it fails to run past the Cura logo and exits. In terminal I get:

freeglut  ERROR:  Function <glutBitmapWidth> called without first calling 'glutInit'.

Debian 7.0 Wheezy 64bit with 64bit pypy

**Comment by daid** [comment]
Funny, works without the glutInit on windows and MacOS. But I added the call.

**Comment by daid** [comment]
Note, I've broken a lot of code in the latest bunch of commits. So the HEAD has quite a bit of broken functionality.

**Comment by jinnatar** [comment]
Looks like this issue resurfaced, according to bisect:
5ab7c7b0da24d32bcaa2d2ce8dc6f63fcdca31fe is the first bad commit
commit 5ab7c7b0da24d32bcaa2d2ce8dc6f63fcdca31fe
Author: daid303 daid303@gmail.com
Date:   Thu Jan 24 18:27:35 2013 +0100

```
Split off some code from preview3d.py, which is becoming way to large.
```

:040000 040000 799d4c7befa63b83adc3702413ee64f14306b0b4 380bcd12ccfe5287778a91dcaf61d816c7a18530 M  Cura

**Comment by daid** [comment]
Odd, as the glutInit is still there...

**Comment by jinnatar** [comment]
Seems my issue was caused by using whatever pip gave me when I installed pyOpenGL from there. Installing the distro repository packages for python-opengl & freeglut3 solved that issue.
