### ISSUE TITLE
add support for home.gcode (home plugin)

### ISSUE THREAD

**Issue by clemtaylor** [daid/LegacyCura#33]
I use the home plugin to issue per layer gcode (to trigger a camera exposure per layer). The home plugin can be enabled so all it does is insert the home.gcode file at the beginning of the layer, so it wouldn't cause problems for people that don't have a home.gcode.

**Comment by daid** [comment]
In the development version you can achieve the same effect with the "replace.csv".

If you put ";LAYER:[tab]Mxxx[tab];LAYER:" in the replace.cvs then you'll achieve the same result, without the home plugin, and it will also be a lot faster then using the home plugin.

Will this do for your cause? (the layer comments I added in the development version really make post-processing a lot easier :) )

**Comment by clemtaylor** [comment]
Sounds good to me! I'll give it a try.
