### ISSUE TITLE
Cura aborts slicing with error message: "something went wrong during slicing!"

### ISSUE THREAD

**Issue by Markzip** [daid/LegacyCura#331]
Hello,

when using STL files generated from Solidworks, in about 75% of all cases  (some of the exported files work) Cura will produce this error: "something went wrong during slicing!" as sson as one hits "prepare print".

If I use the same STL files in e.g. NetFabb, everthing works perfect.
Also an import/export of the file in Netfabb and re-using the exported file in Cura will not remove or change the problem. 
If the error occurs, the model also disappears from the Cura screen.

I tried all different export options in Solidworks, no change at all.
The STL files can also be easily imported to other CAD systems, only Cura seems to have some "digestion" problems.

I could send some sample STL files which consitently generate this error by email if I had an email adress...?

Thank you for your attention

regards
Markus

**Comment by daid** [comment]
Be sure that it's not the "path bug", where the is a none-ascii character in the path.

If that's not it, could you email me one of the STL files? (daid303@gmail.com)

**Comment by smorloc** [comment]
Markus, if you email me an STL file, I can look at it immediately.  My email is smorloc@gmail.com
