### ISSUE TITLE
project planer fails to load stl

### ISSUE THREAD

**Issue by clemtaylor** [daid/LegacyCura#336]
Tried to load http://www.thingiverse.com/thing:7572 into cura (138af904488ae78cffa7869573227cc7667d0ffa) and got this traceback:

Traceback (most recent call last):
  File "Cura/gui/util/toolbarUtil.py", line 201, in OnButton
    self.callback(event)
  File "Cura/gui/projectPlanner.py", line 441, in OnAddModel
    item = ProjectObject(self, filename)
  File "Cura/gui/projectPlanner.py", line 63, in **init**
    self.mesh.getMinimumZ()
AttributeError: 'stlModel' object has no attribute 'getMinimumZ'

**Comment by daid** [comment]
Which version of Cura?

**Comment by clemtaylor** [comment]
On Mon, Jan 21, 2013 at 5:48 AM, daid notifications@github.com wrote:

> Which version of Cura?

I put a git hash in the bug, this was my last fetch:
https://github.com/daid/Cura/commit/138af904488ae78cffa7869573227cc7667d0ffa

**Comment by daid** [comment]
I think one of my comment comments there says "Warning this commit breaks a lot of shit"
