### ISSUE TITLE
Serious skewing issue with project planner, version 12.11 and 12.12

### ISSUE THREAD

**Issue by hexitex** [daid/LegacyCura#340]
I have printed a few planned projects and stupid me did check the sizes of the parts as they are normally spot on with a scale of 1.0 in single slice mode. So 4 full plates later I have noticed that the generated stl from the project planner has decided to skew the new stl annoying and expensively  leaving me with a desk full of junk, gears are egg shaped, the same parts get smaller along both x and y axis. the single STLs came from the prusa github so I think they are sound enough. It's easy to confirm, just print a bed of flat circles replicated in project planner.

**Comment by daid** [comment]
I've printed a full bed of pulleys with the project planner, are you sure this is an effect of the project planner and not some kind of printer setting/Cura setting/project planner setting?

**Comment by hexitex** [comment]
Sorry I'll post some pictures of parts later, I am at work at the moment. But I did mean to mention that I mirror all my parts on the Y. Another thing that my be part of the problem it that seems to get progressively worse with each big slicing operation

**Comment by smorloc** [comment]
So, if you slice the same model more than once, on the later gcode files
the skewing is worse?  If so, can you send a set of gcode files from
back-to-back slicing?

I suspect that the problem is a loose pulley, belt or overheating
electronics.  I got crazy skewing for a period when the origami fan
deflector over the electronics board shifted.

**Comment by hexitex** [comment]
Oh dear, bit embarrassing. Seems that I selected the stls that were for empirial measures. This has an odd effect, see pictures.
![20130122_200430](https://f.cloud.github.com/assets/690181/87763/03535ac2-64d0-11e2-8974-2761d1c59fcc.jpg)
I apologise for any time wasted, the number of holes gave it away. One on the left was perfect, one on right was from the other folder that looked like lm8uu but had an e in it

**Comment by hexitex** [comment]
Left=right, right =left, pic was upside down
