### ISSUE TITLE
Varying infill density. (feature idea)

### ISSUE THREAD

**Issue by Intrinsically-Sublime** [daid/LegacyCura#343]
How hard would it be to make the infill a little smarter. By smarter I mean something like:

Automatically change to line infill if infill density is greater than X (maybe 60%). I could even implement this one.

Automatically insert 50% line infill under solid layers when infill density it below X (maybe the same value as for auto line infill). These 50% line infill layers should be somewhere around half of the solid layer thickness to maybe equal thickness. This would allow for thinner shell thickness over low infill on flat top items without broken threads. (P.s this is another feature that Kisslicer has)

**Comment by daid** [comment]
I think this feature is obsolete with the 13.06 release.
