### ISSUE TITLE
Feature Request for small objects

### ISSUE THREAD

**Issue by melk-** [daid/LegacyCura#344]
To prevent tiny detailed objects from overheating due to the nozzle being overhead at all times, It would be nice If Cura could automatically create a circular or square toolpath far enough away from the object so that the object has time to cool.

So the nozzle visits the tiny object for a few seconds, then goes over to a cura-generated bounding box so that the part has a chance to cool.

A hit and run tool path option would do the trick also by making the nozzle go beyond the part a certain distance then come back and lay down more filament, the keep going, and back again.

**Comment by Jaknil** [comment]
I have a recommendation for you melk:
I am not a cura developer but I think a good idea for you might be to print something else together with your small object. You can use project planner to dublicate or add other things to the plate. That way the nozzle will not just hang there and dribble while your layer cools.

**Comment by melk-** [comment]
Thanks Jaknil
