### ISSUE TITLE
Delta Printer Checkbox

### ISSUE THREAD

**Issue by lazerusrm** [daid/LegacyCura#346]
I LOVE Cura. Very much. unfortunately im having issues with the latest version since with a 

delta style printer, the center of the print bed is X0 Y0

Is there anyway to allow for a checkbox for delta style printer so we can print correctly? Pretty please!

:)

**Comment by daid** [comment]
Has been added for the next version ;-)

**Comment by lazerusrm** [comment]
Awesome. i look forward to it, since i can only print small parts now since
cura 5.11 :)  i patiently await.

On Sat, Jan 26, 2013 at 6:01 AM, daid notifications@github.com wrote:

> Has been added for the next version ;-)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/daid/Cura/issues/346#issuecomment-12735027.

## 

_Brad Dangerfield_*
Manager*_, Industrial Camera Systems_
Tel: (801) 900-3554

**Comment by Intrinsically-Sublime** [comment]
There is a bit of a hack work around for this here https://github.com/daid/Cura/issues/266
