### ISSUE TITLE
nozzle gets buried

### ISSUE THREAD

**Issue by melk-** [daid/LegacyCura#348]
when i print hollow the prints come out perfect, .2 layer height w/ .1 skin. 
If I want to print something with infill all I do it adjust the density, i printed 2 objects yesterday one at 100% infill and another at 15%, both were roughly 16mm high. Both objects buried the nozzle in filament. Looking at the wall of the 15% infill object, it got buried when it got to a layer that was solid (added for support when sliced). And for the 100% infill object, the nozzle was buried about .6mm by the time i cancelled it. 

What setting could be the issue? It's like solid layers put down too much filament. I'm printing in pla @ 195c bed @ 62c, 1.75mm dia. w/ .35mm nozzle.

thanks

**Comment by daid** [comment]
Could be that you have a wrong "steps per E" setting causing over-extrusion.

**Comment by melk-** [comment]
Could it be that I need to up my packing density in order to compensate for over flow? My e steps are correct, so I'm guessing that changing the packing density from 100 to 105 or 110 should show some results?

Also, I didn't use Cura to calculate my e steps, instead, I used that value that's in my firmware, which is correct. Is there something that happens within Cura that requires me to use Cura to calculate my e steps in order for that to work correctly?
