### ISSUE TITLE
bridge settings

### ISSUE THREAD

**Issue by jgeerds-zz** [daid/LegacyCura#35]
can you change the bridge settings to force the default order infill > perimeter?
can you change the bridge settings to honor the amount of outlines/perimeters/wall thickness (right now it just prints one outline)?

right now, the bridge settings use the same order as the profile, i.e. loop > perimeter > infill, but that doesn't work with a bridge, since the perimeter would be printer uselessly into midair, since no bridge infill the present where it could grab on.

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
