### ISSUE TITLE
Retraction disabled on Quickprint

### ISSUE THREAD

**Issue by StanleyKnife** [daid/LegacyCura#351]
I've been experimenting with slicing using Quickprint, and found severe retraction issues (see attached). When I switched to Full Settings I found all the settings made by Quickprint - and retraction was not checked.

Once I checked it everything worked fine.

Just thought you ought to know

![retraction](https://f.cloud.github.com/assets/3235450/111428/a67b689a-6af5-11e2-8435-480b442d38b7.jpg)

**Comment by daid** [comment]
Fixed in newer releases.
