### ISSUE TITLE
[Minor] Temperature not updating in the printing statistics screen during manual pre-heating

### ISSUE THREAD

**Issue by mvhooren** [daid/LegacyCura#353]
The temperature visible in the "Statistics" section of the printing screen does not update when I choose to manually pre-heat. (By setting the printing temperature to 0 in the Print Config tab and then setting an appropriate temperature under the temp tab of the printing screen.) The temperature value only starts to update after I press the print button.

The temperature chart does update itself, but I'm rather used to looking at the number under the statistics window. This used to work fine under Cura 12.08, which is what I was using until upgrading to 12.12.

A very minor issue, but I'd be pleased if it was fixed :)

**Comment by daid** [comment]
No longer an issue in 14.02 RC update, http://software.ultimaker.com/Cura_closed_beta/
