### ISSUE TITLE
project planner prints into thin air

### ISSUE THREAD

**Issue by 42loop** [daid/LegacyCura#356]
if I put objects of different height into the project planner, and check the 'print all at once' button, cura centers objects in Z dimension. if support is not enabled, the less tall object is printed into thin air.
![Screenshot from 2013-02-03 13:09:52](https://f.cloud.github.com/assets/1280023/121801/11cbbace-6dfc-11e2-8d25-1660f9eeada8.png)

**Comment by daid** [comment]
Which version does this?

**Comment by 42loop** [comment]
this is the current git version.

grtx

**Comment by daid** [comment]
Thanks. Note that the latest git is always a bit tricky, as I'm changing a lot of code to clean things up. It's awesome that people test and report issues, but if you want a stable version it's best to pick one of the releases.
