### ISSUE TITLE
Suggestion: Access to User settings from plugin code.

### ISSUE THREAD

**Issue by Jaknil** [daid/LegacyCura#357]
I am writing a plugin for Cura and it would really help to have access to the profile settings. Can you tell us how to decode the CURA_PROFILE_STRING line?

**Comment by Intrinsically-Sublime** [comment]
I am a little confused. There is already an option under file that says "load profile from gcode" that does what you want, no?

**Comment by daid** [comment]
Check the loadGlobalProfileFromString function in util/profile.py
