### ISSUE TITLE
Console access not available through Cura.bat in 12.12A - needed for Plugin debugging

### ISSUE THREAD

**Issue by Jaknil** [daid/LegacyCura#358]
Hi!

Is there a way in 12.12A to see the console output from python [print 'debug message'] commands like there was in 12.11. In Cura 12.10 it was accessed through the Cura.bat file and viewed in the dos-window.

**Comment by daid** [comment]
In the installation path of Cura there is a Cura.bat, if you run that you will see the debug window again.
If that didn't work, then the 12.12A version generates an output.txt (not sure if that change made it into the 12.12A release, I think it just does that up from 13.01)
