### ISSUE TITLE
Feature Request: Allow setting gcode output file name

### ISSUE THREAD

**Issue by vaporlock** [daid/LegacyCura#360]
Love Cura but it would be nice if we could change the gcode file name before it is generated. That would allow us to maintain multiple versions without having to go the file system to rename the previous version before hitting Prepare. The other slicers I've used (and most other apps) will at least let you know that you are about to overwrite an existing file.

**Comment by daid** [comment]
Duplicate, this request has come by multiple times. Search the other topics for the explanation why I currently won't honor this request.

**Comment by vaporlock** [comment]
Agreed. Once I looked at the other threads and thought about it you are correct. I'm actually trying to version my profiles, not the objects subject to those profiles.
