### ISSUE TITLE
Bed level wizard causes error

### ISSUE THREAD

**Issue by draixo** [daid/LegacyCura#361]
When starting the "bed levelling wizard", I got this problem and the software wont connect:

Log: Unexpected error while setting baudrate: 250000 IOError: '[Errno 22] Invalid argument' @ machineCom.py:_monitor:355

This problem exists in the christmas edition of the UM Cura software.

**Comment by daid** [comment]
Linux?

**Comment by draixo** [comment]
Linux idd.

Julius/ Mr. Seeker

**Comment by calinb7** [comment]
It's not just bed levelling that causes this problem.  Anything that requires re-running the wizard produces this problem.  For example, an end stop switch was activated on my machine.  After deactivation it, the wizard would still not proceed (perhaps this is another bug) and I had to kill the wizard.  Upon re-running it, the baud rate error occurred.

The wizard can be restarted successfully only after deleting the ~.cura subdirectory.  However, upon successful completion of the end stop check, the bug just pops up again for the next stage of the Wizard (bed levelling or perhaps printing the square, but I don't recall precisely which is the next stage that causes the glitch.

Ubuntu 12.04 LTS

-Cal

**Comment by daid** [comment]
There seems to be some problem with linux and the first run wizard and machine connections not closing properly (and because it's not properly closed, you cannot open a new connection). It's odd that there is no problem on windows or mac related to this.

**Comment by calinb7** [comment]
It's also odd that deleting the .cura subdirectory re-enables the connection.

--- On Mon, 3/18/13, daid notifications@github.com wrote:

**Comment by daid** [comment]
The newer Cura releases have some updates in regards to connections, I think this fixed the problem as it was not reported again.
