### ISSUE TITLE
When pypy refuses to run, Cura gives unhelpful error messages

### ISSUE THREAD

**Issue by transplier** [daid/LegacyCura#362]
I'm running Cura on an older machine without SSE2 (yes, yes, I know, but it's my shop PC). Whenever I try to slice, Cura just spits out:
"Something went wrong during slicing."
Looking at the log yields:
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

No further info is given. I traced the issue to pypy- it hasn't been built to deal with non-SSE2 machines. If I manually run pypy:
C:\Program Files\Cura_12.12A>pypy\pypy.exe
Old CPU with no SSE2 support, cannot continue.
You need to re-translate with '--jit-backend=x86-without-sse2'

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

C:\Program Files\Cura_12.12A>

Not sure what the resolution here should be, but an architecture check could be done and the user warned. At least the whole output from pypy (including stderr) should be presented in the log. As for me, I'm replacing pypy with a compatible version.

**Comment by daid** [comment]
The stderr was missing from the output, I've changed that. But other then that, not having a machine with SSE2 is extremely rare (you're the 2nd person in about a year time)

**Comment by transplier** [comment]
Cool, thanks. Yep, I agree SSE2 is almost a given these days. I'm using an older Athlon XP. Now with stderr included people at least have something to google.

As slight OT, I'm dreaming of a UI to select/download a version of pypy on the first run of Cura :) Maybe I'll hack something up later.
