### ISSUE TITLE
RepRap Pro Huxley moves in x Anis to far

### ISSUE THREAD

**Issue by DraycD** [daid/LegacyCura#363]
First Sorry for my Bad english,

I love the interface from cura and i like to use..
Everyting works fine, i can connect and the manual movement works good.
But when i send s print job ,the x axis move to the end (over the bed and more) 
( to left, away from endstop)

I trid to make the pront bed sizze smaller but it makes always the same,
The y axis and the z axis take an effect of the printer bed setting but the x axis not.

Please help me ;)

I use a imac with mac os 10.8.2 and a reprap pro huxley with marlin firmware and melzi electronics 1. gen.

**Comment by daid** [comment]
Most likely fixed on the 13.11 release or newer.
