### ISSUE TITLE
Dualtrusion: Bad dual STL slicing - Gcode shows shifted part along X axis

### ISSUE THREAD

**Issue by JennParis** [daid/LegacyCura#364]
2 STLs are loaded using "Load Dual", representing a 2 materials part.
![Cura-Slicing-2STL-1](https://f.cloud.github.com/assets/3597075/164781/3426de34-78e5-11e2-9c70-87fc5969f99e.JPG)

"Prepare print" generated the gcode, visualized here:
![Cura-Slicing-2STL-2](https://f.cloud.github.com/assets/3597075/164782/568b57fc-78e5-11e2-9418-b688cd8fe982.JPG)

There is a shift along X axis, and the brim is surrounding just one object.

Comment:
Project planner can be used to load 2 STLs, and assign different extruder to each of them, but the GUI does not offer positioning feature.
"Load Dual" feature in Project planner or passing objects/parts from main view's plater would be great. (Feature request)

**Comment by daid** [comment]
The 2nd extruder is offsetted in GCode by the extruder offset in the preferences, this is by design to get around the lack of extruder switching features in many main firmwares.

**Comment by JennParis** [comment]
Indeed. This is an usage mistake. Forgot to take this parameter in account.
