### ISSUE TITLE
Generating deb file for Ubuntu/Debian/Mint Linux

### ISSUE THREAD

**Issue by peteruithoven** [daid/LegacyCura#366]
I know David has bin thinking about it for a long time and I suggested creating a repository himself for just Cura (circumventing normal requirements for being added to exsisting repositories). 
But I've had some experience with Visicut and they publish a .deb file. (It even looks like nightlybuilds get generated on the fly after commits) 
These work great. You open it, you press _install_. If you already have the application _install_ is replaced with _upgrade_. 
I don't know how hard this is, but I just wanted to share the idea.

**Comment by daid** [comment]
Done
