### ISSUE TITLE
Print window does not draw a line for target temperature of heated bed

### ISSUE THREAD

**Issue by dwalton64** [daid/LegacyCura#367]
I noticed that Cura drew a line that represented the target temperature of the extruder but not the heated bed.  I looked at the code for the print window and saw code that was supposed to draw the line for the heated bed target temp.  I printed the target temps on the graph and the heated bed target temp was zero even though I knew it was set to 70.

I looked at the code in machineCom.py and think I found the problem on line 464 (in 12.12A).

``` python
self._bedTargetTemp = float(re.search('S([0-9]+)').group(1))

should be

self._bedTargetTemp = float(re.search('S([0-9]+)', cmd).group(1))
```

I made this change and the target temp for the heated bed was plotted.

Regards,

Drew

**Comment by daid** [comment]
Thanks!
