### ISSUE TITLE
Project Planner stops slice after first object

### ISSUE THREAD

**Issue by cb0** [daid/LegacyCura#368]
Hi,

I'm running CURA 12.11 because 12.12 instantly crashes after startup. However this is no problem with single prints.
When using the project planner, the GCode generation stops after the first object. I can see the following message appear in command line:

`Exception in thread Thread-2:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 530, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 483, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Applications/Curaold/Cura.app/Contents/Resources/Cura/gui/projectPlanner.py", line 978, in OnRun
    startGCode = profile.getAlterationFileContents('start.gcode')
  File "/Applications/Curaold/Cura.app/Contents/Resources/Cura/util/profile.py", line 534, in getAlterationFileContents
    return unicode(prefix + re.sub("(.)\{([^\}]*)\}", replaceTagMatch, alterationContents).rstrip() + '\n' + postfix).strip().encode('utf-8')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/Applications/Curaold/Cura.app/Contents/Resources/Cura/util/profile.py", line 430, in replaceTagMatch
    return pre + time.strftime('%d %b %Y')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)`

I've tried updating to python from 2.7.1 to 2.7.3 with no luck. 
I'm using a MacBook Pro, OS X 10.7.4 (Build 11E53). 

The GCode that was generated is not saved to the file that was previously selected. The file only contains:

```
;TYPE:CUSTOM
T0
```

I thought it might be related to the pathname in which I wanted to store the gcode. This pathname initially contained a 'Ä' (german umlaut). However after removing the umlaut, nothing changed.

It looks like he's try to open the start.gcode file. And for some reasons this fails. However with single prints, where (I suppose) the start.gcode is loaded too, it works.

Any thoughts what could causes this? I really would love to try the project planner.
Best greetings and thanks for your great work!

**Comment by daid** [comment]
The "UnicodeDecodeError" is caused by any "none ascii" (so anything not a-z, 0-9, and a few other characters) somewhere in the date/time representation, which happens if you have none-english language settings on your computer. The quickest fix would be to remove the {date} tag from the start code. (It's also fixed for the next release)

The 12.12 crash is caused by the way 12.12 was packaged. It's causing issues on some CPU types on MacOS.

**Comment by Kentzo** [comment]
@cb0 please take a look at the issue #350. I've uploaded a build that should address constant crashing issue.
Please test it and leave a comment.

**Comment by cb0** [comment]
@daid Thanks very much for the quick reply. Removing the {date} tag solved this issue. Now project planner works like charm :)
@Kentzo Also, THANKS. The version (12.12) you uploaded on 24.02.2013 in #350 works!! The only difference I see is that I can't set the position of parts in project planner. They are positioned automatic, which should be no problem. 

Now I can't wait to come home after work and start a big project ;)
Thanks for the great support!!
