### ISSUE TITLE
Print button does nothing on Cura 12.12 on linux

### ISSUE THREAD

**Issue by mikeq3** [daid/LegacyCura#369]
I load a model, slice it, and when I hit the print button nothing happens. I can connect to my printer in the first run wizard no problem. I tried getting the latest from github and it does the same thing. What am I missing here?

**Comment by daid** [comment]
It's seems something is going wrong with the power module. In Cura/gui/printWindow.py there is a power module imported and used. But this is causing issues, no idea about the underlaying cause, other people tracked this down)

**Comment by mikeq3** [comment]
I read something about that, but I didn't think it was the issue because I installed the power module directly from the correct web site. I will look into it some more and see what I can come up with.
Thanks,
Mike

**Comment by Kentzo** [comment]
@mikeq3 What's your system: win, mac or linux?

**Comment by mikeq3** [comment]
Linux, I checked with python -v -c 'import power' and it looks to be importing the correct power module. Not sure what the issue is.

**Comment by Kentzo** [comment]
@daid do we have logging facilities on Linux?

@mikeq3 could check syslog, maybe there are some messages regarding the issue?

**Comment by mikeq3** [comment]
Nothing in the syslog files. Also I run the cura.sh script in a terminal and I see no errors when I click the print button.

**Comment by Kentzo** [comment]
@mikeq3 How did you install power?

**Comment by Kentzo** [comment]
@mikeq3 please, try the following script and check whether it produces errors:

```
import power
p = power.PowerManagement()
p.get_providing_power_source_type()
p.get_low_battery_warning_level()
p.get_time_remaining_estimate()
```

**Comment by daid** [comment]
On Ubuntu 12.04

```
>>> import power
>>> p = power.PowerManagement()
>>> p.get_providing_power_source_type()
0
>>> p.get_low_battery_warning_level()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "power/linux.py", line 141, in get_low_battery_warning_level
    warnings.warn("Unable to calculate low battery level: {error}".format(str(e)))
KeyError: 'error'
>>> p.get_time_remaining_estimate()
-1.0
```

**Comment by Kentzo** [comment]
@daid indeed, there is an error in the method that processes exception. I'll fix it.

Could you take look why ZeroDivisionError is thrown at all?

**Comment by daid** [comment]
My /sys/class/power_supply is empty, so the all_energy_now array is empty, so it's sum is zero.
(It's on my server, which doesn't have battery supply)

**Comment by mikeq3** [comment]
I get this error on my linux box which is also a server and doesn't have a battery:
Traceback (most recent call last):
  File "./test.py", line 4, in <module>
    p.get_low_battery_warning_level()
  File "/usr/lib/python2.6/site-packages/Power-1.1-py2.6.egg/power/linux.py", line 141, in get_low_battery_warning_level
    warnings.warn("Unable to calculate low battery level: {error}".format(str(e)))
KeyError: 'error'

or if I run from the python prompt, I get the exact same output as daid.
I don't see that function being called in cura.

**Comment by Kentzo** [comment]
@mikeq3 I've fixed the bug but didn't push new version to PyPI yet.
You can try new version from the repo: https://github.com/GreatFruitOmsk/Power

**Comment by mikeq3** [comment]
Fixed.
Had to change:

SCRIPT_DIR=`dirname $0`
cd $SCRIPT_DIR

to

SCRIPT_DIR=`dirname $0`
export PYTHONPATH=$SCRIPT_DIR
cd $SCRIPT_DIR

in the cura.sh script.

Cura was getting module errors when trying to fork another subprocess for the print window.
