### ISSUE TITLE
package.sh does not run correctly when current directory is not script directory

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#37]
If I run package.sh from another working directory (specifying an absolute path or a path relative to the current directory) it starts downloading pypy to the current working directory instead of the Cura directory.

**Comment by RedwoodForest** [comment]
I fixed this in my fork by just changing to the script directory as one of the first actions in the script: https://github.com/lawrencejohnston/Cura/commit/a055b03422e972b285d65eeaf02cd9a6f3fe8084

I would issue a pull request but I'm not sure how to avoid making you pull all my merge commits (which just brought my fork in line with yours).

**Comment by daid** [comment]
Thx for the fix!
