### ISSUE TITLE
Support material starts in the air

### ISSUE THREAD

**Issue by loelkes** [daid/LegacyCura#373]
Hi,
with "Support type: Everywhere" i sometimes get a support structure that starts in the air (no contact with the build platform). It is not a Cura-preview bug.
Cura 12.12 on OSX 10.8.2.

The used file from the screenshot is RasPi_Case2_Bottom_Final.stl from http://www.thingiverse.com/thing:30572

![Bildschirmfoto 2013-03-08 um 16 15 28](https://f.cloud.github.com/assets/231909/236916/096170a6-8803-11e2-80d7-6538b689dfd0.png)

**Comment by mikeq3** [comment]
Why would you use support material on thing 30572?
