### ISSUE TITLE
Nothing happens when I click Print (Ubuntu 12.10, Cura, 12.12)

### ISSUE THREAD

**Issue by dylanwinn** [daid/LegacyCura#376]
When I push print, nothing at all happens. No windows open, no error messages are logged, nothing. The bed leveling wizard, however, works perfectly. I've checked file permissions, and tried setting the serial port settings to both auto and the actual port. I've successfully used Cura with this same printer under Windows, and with Pronterface under Linux.

**Comment by fgibaux** [comment]
Got the same problem, but was resolved last week in #369 
have you tried to upgrade lib power as said in last post ?

**Comment by dylanwinn** [comment]
Thanks, I was able to fix it just by changing Cura.sh as per https://github.com/daid/Cura/issues/369#issuecomment-14574669
