### ISSUE TITLE
Dual extrusion problems with cura 13.01

### ISSUE THREAD

**Issue by Tromaras** [daid/LegacyCura#379]
I wont use the beautiful option to maker support with the second extrude in my makerbot Replicator dual head. 
In cura 12.12 everything is good but I can't put the 0,0 in the middle of the bed. 
In cura 13.01 I have the middle in the bed but the it make the support with the first extruder and not with second. 
Please, help my (I can't undersantd very well how to aply this patch
https://github.com/daid/Cura/commit/4c5ff7f275f34318cce717b44059bca5f8dcf64a
on my installation of Cura.

**Comment by daid** [comment]
13.03 will be out tomorrow ;-)

**Comment by Tromaras** [comment]
WOw!
thanks

thomas
