### ISSUE TITLE
.gitignore does not ignore packages now that NewUI is no longer part of the name

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#38]
.gitignore does not ignore packages now that NewUI is no longer part of the name

**Comment by RedwoodForest** [comment]
Fixed in my fork: https://github.com/lawrencejohnston/Cura/commit/d3bfafb2bd6d92db4a7116fd17ab6b939b7bed40

**Comment by daid** [comment]
Thx for the fix!
