### ISSUE TITLE
Online documentation not up to date for Cura 13.03

### ISSUE THREAD

**Issue by gadgetfreak** [daid/LegacyCura#380]
In Cura 13.03, from menu Help->Documentation, a web page opens up at:

http://daid.github.com/Cura/

which says (a bit further down the page):

"Current release (12.08) features"

Is there updated documentation that has not been published?

Thanks for a great piece of software!

/Daniel

**Comment by daid** [comment]
The current documentation is horribly outdated for 13.03, while most of the settings are the same, the looks have changed quite a bit. (the 12.08 documentation worked pretty well on the 12.12 release) The ultimaker blog: blog.ultimaker.com has a nice screencast to show off some of the new features.
