### ISSUE TITLE
Preference window does not always show on MacOS

### ISSUE THREAD

**Issue by daid** [daid/LegacyCura#381]
http://umforum.ultimaker.com/index.php?/topic/1781-still-window-handling-problem-with-mac/

**Comment by Kentzo** [comment]
I think we should add some tracing when user opens or moves windows.

**Comment by illuminarti** [comment]
Sure. Let me know what you need me to do to help identify the problem.

**Comment by Kentzo** [comment]
@illuminarti do you still encounter the issue?

**Comment by daid** [comment]
As far as I know I manged to fix this issue.

**Comment by Kentzo** [comment]
@daid what was it?

**Comment by daid** [comment]
The wxPython version of Mac seems to have some problems with modal frames. I think I finally settled on a none-modal dialog box which worked.

**Comment by illuminarti** [comment]
Yes, this problem seems to be fixed in the 13.04 build of Cura, although as I've discussed with Daid separately, in the Steam Engine beta I sort of have the opposite problem - the Expert Settings window goes away when you close it, but the rest of the app doesn't seem to notice.

**Comment by Kentzo** [comment]
@daid Do you still plan to rewrite UI or it's not a priority now?

**Comment by daid** [comment]
It's not really a priority right now. The amount of issues is pretty low, and the amount of work required for a rewrite is pretty high.
