### ISSUE TITLE
'No module named Cura' on Ubuntu 12.10 .deb installation

### ISSUE THREAD

**Issue by phord** [daid/LegacyCura#383]
When I try to prepare a sample model I get an error that "Something went wrong during slicing!" and the log shows just one line:

```
/usr/bin/pypy: No module named Cura
```

I installed the .deb installer today from the site:
http://software.ultimaker.com/current/Cura-13.03-debian.deb

I do not see any version info in the GUI itself, but I suppose it is 13.03.

**Comment by phord** [comment]
I built Cura from source using 'package.sh debian &&  sudo dpkg -i ./scripts/linux/Cura-13.03-debian.deb' and it seems to slice ok now.  I do not know if the build process installed the missing module, or if the .deb I built is different from the one I downloaded somehow.

One other bit of info:  I installed the downloaded version using the default app (Ubuntu Software Center).  I believe it uses dpkg internally, but I'm not sure.  I installed my locally built version using dpkg, obviously.

**Comment by daid** [comment]
The problem has been identified, it's an issue with the .desktop file, the latest sources contain an update for it already and I will bring out an update. (It's the first time packing .deb files, so problems where bound to happen...)

**Comment by Tie-fighter** [comment]
Bug confirmed :/

**Comment by daid** [comment]
I currently assume commit 712afd55675d65047ca5396d51f62981926f2ebe fixes this issue.

**Comment by Tie-fighter** [comment]
Fix confirmed :)
