### ISSUE TITLE
GCode inverts base on this STL model

### ISSUE THREAD

**Issue by StanleyKnife** [daid/LegacyCura#384]
Here's a model I downloaded from Thingiverse. When I slice it, the base should be a flat with circular holes in - but instead the base is missing and the holes are solid (see grabs). Weird?
![ear01](https://f.cloud.github.com/assets/3235450/286389/4828be88-923b-11e2-9893-573539450e81.png)
![ear02](https://f.cloud.github.com/assets/3235450/286390/4aa9663a-923b-11e2-93f8-4dbe9c4e7c4e.png)

**Comment by daid** [comment]
Most likely it has intersecting polygons. Try running the file trough cloud.netfabb to see if that helps: http://cloud.netfabb.com/

**Comment by StanleyKnife** [comment]
Ah, OK - will do.

**Comment by mikeq3** [comment]
I've seen something similar on a model I sliced. It seems to be a gcode display issue. When I view the Goode in other viewers it looked ok. Also, it seemed to correct it self when I displayed more or less layers.
