### ISSUE TITLE
(Cura linux 13.03) Python fails to load module "Cura.util"

### ISSUE THREAD

**Issue by draixo** [daid/LegacyCura#387]
I got 2 errors with both builds:

.tar.gz edition:

Missing shell function that was in 12.02, causing Cura to crash on startup (ImportError: No module named Cura.util)

.deb edition:

When slicing, it will slice with the following error "/usr/bin/pypy: No module named Cura"

Also, on a sidenote: I would suggest changing the link location from "Computer aid" to "Electronics" (where stuff like eaglecad & arduino for example are located) or "Graphics" (where blender is). Now it seems Cura is actually used to diagnose ubuntu...

**Comment by daid** [comment]
Problem has been noticed and will be fixed soon, it's an issue with the .desktop file (which needs a path). I actually put it  in the category "accesories", but apparently your distro names this "computer aid", I'll see if I can find the same category as blender and put it in there.
