### ISSUE TITLE
Models not visible except with "Transparent" view

### ISSUE THREAD

**Issue by AVHon** [daid/LegacyCura#388]
I'm running Cura 13.03 on Ubuntu 12.04. Whenever I load a model, the 3D view does not change at all, and the model is completely invisible. The only way to see the model is to change 'View Model" to "Transparent". Changing the view to "X-Ray" fills the entire view screen with pure red, except the "Y" and "Z". All other view modes show an empty, gray screen with the colored "X", "Y", and "Z".

Screenshots:

When Cura is opened, before any model is loaded.
![cura_openglError_noModel](https://f.cloud.github.com/assets/3957499/295873/e45f8cca-94be-11e2-8696-746ee8c2b6a2.png)

A model (the RepRap Prusa x-carriage) has been loaded. All following screenshots show exactly the same view. Only the view mode is changed.

Normal:
![cura_openglError_normal](https://f.cloud.github.com/assets/3957499/295875/20bb3c28-94bf-11e2-90e3-8a57568ffa54.png)

Transparent:
![cura_openglError_transparent](https://f.cloud.github.com/assets/3957499/295876/28ae376e-94bf-11e2-8bcd-5d7f44947e00.png)

X-Ray:
![cura_openglError_x-ray](https://f.cloud.github.com/assets/3957499/295877/30b70d50-94bf-11e2-9518-d0bbfe0d56f5.png)

Overhang:
![cura_openglError_overhang](https://f.cloud.github.com/assets/3957499/295878/38e53722-94bf-11e2-821a-2cd3ed412b21.png)

Layers:
![cura_openglError_layers](https://f.cloud.github.com/assets/3957499/295879/44bca49a-94bf-11e2-8d04-0c8ab6e12c5f.png)

**Comment by daid** [comment]
Sounds like you have a buggy-opengl implementation. (which is not odd for linux)

**Comment by AVHon** [comment]
Does it have to do with the fact that I'm running OpenGL 1.2? Does Cura require a higher version of OpenGL?

**Comment by daid** [comment]
Could be, OpenGL compatibility is a bit of a minefield. I'm not sure which level I require right now. But future upgrade will most likely require shader support (as maintaining a large level of backwards compatibility is currently costing me a lot of speed in rendering)
