### ISSUE TITLE
Feature Request: "Dragging objects in Main window and Project Planner"

### ISSUE THREAD

**Issue by PaulDutch** [daid/LegacyCura#390]
In any developed 3D program you have the possibility to drag models along the bottom plane, making it easier to work with the software. Plus making it easier and more intuitive to arrange the build plate.
This feature I think is missing from Cura and could add so much value.

**Comment by daid** [comment]
Working in on it for the next big release, which will also feature the new slicing engine and lots of other updates. Hopefully ready before the Bay-Area Makerfair. (It will be a huge update)
