### ISSUE TITLE
Project Planner in current 13.03 release gives errors when loading or saving a project

### ISSUE THREAD

**Issue by mikeq3** [daid/LegacyCura#391]
Project Planner in the current 13.03 release gives errors when loading or saving a project file. Seems there are a lot of unfinished changes in projectPlanner.py. All attributes appear to be stripped from the item object but, the save and load  sections still expect them. Why would scale, rotate, FlipZ etc. be stripped from the items? Then every time you load a project you would have to redo those changes.

**Comment by daid** [comment]
Rotate/scale/mirroring is saved in a transformation matrix now, it allows freeform rotation and scaling in a much better way. (The bugged loading/saving is an oversight)

**Comment by mikeq3** [comment]
I took another look at the code and I see that you are using the matrix now and it is just missing from the load and save.

**Comment by daid** [comment]
Note that the project planner will be removed in a few months, as I'm merging it into the main interface. (It's happening on the SteamEngine branch)

**Comment by mikeq3** [comment]
Can you put in the changes for load and save for now so I can patch my version? I would imagine they are minor changes?

**Comment by daid** [comment]
fixed it in 318b898

**Comment by mikeq3** [comment]
Thanks, I really like this program. Nice work!

**Comment by mikeq3** [comment]
Forgot to close it
