### ISSUE TITLE
mainWindow has no normalSashPos on first run

### ISSUE THREAD

**Issue by wiegerhofstra** [daid/LegacyCura#392]
Using master branch on linux.

On first run you will get the error:

``` python
File "/usr/share/cura/Cura/gui/mainWindow.py", line 229, in __init__
    self.splitter.SplitVertically(self.leftPane, self.rightPane, self.normalSashPos)
AttributeError: 'mainWindow' object has no attribute 'normalSashPos'
```

A workaround is to set self.normalSashPos before it tries to load the preferences.

**Comment by daid** [comment]
Did you use commit 97716443eddaa816daef29b760a8907d90a090fd ?

**Comment by wiegerhofstra** [comment]
9771644 solved it, thanks.
