### ISSUE TITLE
Cura-BETA-13.03 command line version: 'ini-files' problem

### ISSUE THREAD

**Issue by NastyUser** [daid/LegacyCura#394]
Dear Daid,

First of all, Cura is by far the best slicer... but
I have been playing around with several versions of Cura – also with the latest beta-version 13.03. In the command-line version it is extremely fast vis-a-vis cfr. Cura-12.08.
 So, I have a few questions regarding …BETA-13.03 in the command line version ( the GUI doesn't work in Windows on MB files... ):
 Q1: Which *.ini files uses SteamEngine.exe and where are they located?
 Q2: in the BETA-version I noticed that there are a lot ( really a lot) of ‘double’ X-Y coordinates in every ‘wall-inner’ and ‘wall-outer’ set. How come?
 Q3: Also, the BETA-version ‘fills’ the model completely ( which was not asked for, see Q1…. ) only a bottom layer was asked / hoped for …..
 Q4: would be nice if there would be a 64bit version of …BETA-13.03 

PS. for example: Cura-12.08 could handle 'stairs like pieces'  in the model; is this also taken into account in the SteamEngine version... ? 

Could you comment on these questions?

best regards
van den rul Sylvain
Belgie

**Comment by daid** [comment]
The SteamEngine BETA is pretty much work in progress. My internal version has advanced a lot compared to the closed release. As the BETA was pretty much hacked together to work. It shouldn't do 100% infill, but this could depend on the model.

**Comment by NastyUser** [comment]
Daid,

I'm aware that the development is a 'nasty' piece of work, but you did it as for extremely well...
The 'fill / no-fill' and 'inward overhang' was done very nice in Cura 12-08 for the model concerned; also the ini-files were easy to use. So why not use the feature of 'external' ini-files in SteamEngine to verify the options? The BETA version can handle stl-files with larger amounts of triangles ( up to 6 M triangles) , which was not possible with Cura-12.08 ( < 1M triangles ). Also the dimension of the model can be > 200mm ( up to 450 mm!!).
So my suggestions:
1. provide external use of ini-files for the important options; display the ' internal defined' options...
2. maybe provide a stl test-file...
3. make slicing indepent of modelsize....
4. nowadays GB memory and diskspace are cheap and common, so a 64bit version would be very welcome --> Q3 maybe obsolete...

best regards,

**Comment by NastyUser** [comment]
Daid,I'm aware that the development is a 'nasty' piece of work, but you did it as for extremely well...
The 'fill / no-fill' and 'inward overhang' was done very nice in Cura 12-08 for the model concerned; also the ini-files were easy to use. So why not use the feature of 'external' ini-files in SteamEngine to verify the options? The BETA version can handle stl-files with larger amounts of triangles ( up to 6 M triangles) , which was not possible with Cura-12.08 ( < 1M triangles ). Also the dimension of the model can be > 200mm ( up to 450 mm!!).
So my suggestions:
1. provide external use of ini-files for the important options; display the ' internal defined' options...
2. maybe provide a stl test-file...
3. make slicing indepent of modelsize....
4. nowadays GB memory and diskspace are cheap and common, so a 64bit version would be very welcome --> Q3 maybe obsolete...best regards,
 Date: Wed, 3 Apr 2013 10:30:56 -0700

**Comment by daid** [comment]
1. For the simple reason of not wanting to add an ini-parser to the engine. The less C++ code the better.
2. We have a bunch of those at the engine code, and I got like 100 of them on my PC. I'm trying to print just about anything with my new engine these days.
3. Mostly a memory issue, so point 4 is important. (I could sacrifice speed for memory, but I rather do not)
4. A 64bit version will be compiled and added for the release, I can assure you.
