### ISSUE TITLE
Gcode generated as if comb is not functioning correctly

### ISSUE THREAD

**Issue by mikeq3** [daid/LegacyCura#395]
When I slice using Cura on a model with narrow slots, head travels are done down and almost around the slots but instead they are in the bottom outside the edges. When the same model is sliced in skeinforge 50 itself this behaviour is not observed. I tried to isolate the issue to a difference between skeinforge 50 and Cura_sf but, I  haven't had any success. Because the travel is in the slots they end up with plastic clogging them from ooze.

**Comment by mikeq3** [comment]
I checked and this happens with this model on Cura 12.08 and 12.12. I've been comparing the craft plugins between sk50 and Cura and I don't see how this is happening. I have some images to show the issue but, I'm not sure how to post them here.

**Comment by mikeq3** [comment]
when I disabled comb, I saw that the strange travel paths went away. Of course there were travel paths all over the place but not in the notches of the model. Just criss-crossing the model. I REVERSED the modification you put in from:
Jun 19 2012 commit: d59953be3ebf7049de6cdb074c9ae5687f7a7b33
Title: "Make comb use a larger distance between the outer edge and the move, this hopefully removes the ugly outsides on a print when combing."

That fixed the issue! The model was combed accurately after that change.

I would like to see the travel paths moved in more from the edges as that commit stated, but that change from June 19 2012 seems to negatively affect combing of narrow slots in a model.

**Comment by mikeq3** [comment]
I found that if I change this in comb.py:
if centerPerpendicular == None:
                centerPerpendicular = centerEnd
            elif centerEnd != None:
                centerPerpendicular = 0.5 \* (centerPerpendicular + centerEnd)
            between = None

To:
if centerPerpendicular == None:
                centerPerpendicular = centerEnd
            elif centerEnd != None:
                centerPerpendicular = 0.9 \* (centerPerpendicular + centerEnd)
            between = None

This will put the travel paths at the inner most edge of the perimeter walls. Where normally they are on the middle of the perimeter walls. Anything over 0.9 there will also cause the weird incorrect travel paths within the notches of my model.

Note: the above was successful only after reversing your commit from June 19 2012

**Comment by daid** [comment]
(Cura_sf is long dead, so this issue is no longer actual)
