### ISSUE TITLE
Cura 13.03/OSX fails to take into account bed temperature before starting to print

### ISSUE THREAD

**Issue by nodje** [daid/LegacyCura#396]
I can't get Cura to take into account heated bed temperature before a print start.

I have to prepare, print, then connect dialog pops up, then set temperature manually -- using the arrow because you cannot enter the figures manually -- wait for the bed and head to get to the right temperature before launching the print.

if I launch the print without setting the temperature, the Head will be heated before print start but not the bed.

**Comment by daid** [comment]
Can you check the resulting GCode? There should be an M190 at the start to heat up the bed.

**Comment by nodje** [comment]
M190 is not in the resulting GCode.

GCode starts with 
`;TYPE:CUSTOM
M109 S230.000000`

But no M190.
As a work around, I can put it manually in the start.gcode.
Would `M190 S115` would do?

Also, as said previously, setting the temperature manually is difficult because you cannot input the digit with the keyboard, you have to use the up arrow to get to the proper temperature. If you input digit with the keyb. it gets reseted to 0. That could be an Os X only pb.

**Comment by raulalma** [comment]
Same problem here...

**Comment by iheartmaths** [comment]
I have the same problem. There is no M190 term in the gcode when preparing a print in Cura 13.03 for OS X and so the bed doesn't heat.

**Comment by MrBalonio** [comment]
I am having the same issue.

**Comment by iheartmaths** [comment]
It's been fixed in the latest version I think.

**Comment by nallath** [comment]
Issue has been fixed.
