### ISSUE TITLE
Big part of wall not getting sliced that the CAD programs show and is there in design

### ISSUE THREAD

**Issue by diepchess** [daid/LegacyCura#400]
hi, 

With great pleasure i use CURA! Thanks for this big work of making it available. Usually one only hears people who complain and not all those who use it with great pleasure. For first time now i have an issue with it not printing a part of wall that is there. Already visible first layer in 

http://www.thingiverse.com/thing:71279.

I have taken photos of the problem and screenshots of how it should look like in OpenScad and in FreeCAD i also loaded the resulting STL which also shows the wall to be there whereas a triangle gets cut out by CURA.

What i tried modify in openscad is first print the central object from Jonas Kuehling and then the wall i added to it. Same problem then in CURA.

I have taken pictures and have the openscad and STL files, also at Thingiverse.
A big part of wall not getting drawn. The wall goes through another object and makes it more
solid. Both the openscad file as well as freecad opening the resulting STL, they both show the wall being there, yet as we can see at the first layer already it isn't there. I had it print also more layers previous time so it isn't a 0.1x mm issue.

The problem is there in printing first layer of what i just posted last night on thingiverse.

http://www.thingiverse.com/thing:71279

Trying to figure out how i can attach pictures here.

**Comment by diepchess** [comment]
put the photos also at thingiverse showing problem - maybe this old os/x laptop not new enough browser to attach pictures here.

**Comment by mikeq3** [comment]
I found some holes in the model. Try to run it through netfabb basic to fix them.

**Comment by daid** [comment]
Extra internal faces in the mesh are causing this.

**Comment by diepchess** [comment]
The open space gets created first by the solid structure. However AFTER that i create a closed solid polygon t hat should overrule this. That's what the CAD programs do. 

So it's a bug.
