### ISSUE TITLE
Two objects get centered and printed together (Cura 13.03)

### ISSUE THREAD

**Issue by mskoster** [daid/LegacyCura#403]
Two gears next to each other in dae-file appear as designed in Cura after Load Model. But after prepare phase both gears are centered, the smaller gear seems substracted from the other. 

Can't upload the files here on github, but they are available on request.

Regards,

Martin

**Comment by daid** [comment]
Could you email the dae file to daid303@gmail.com?  then I could take a look at it. (I won't share the files)

.dae is a complex file format, and I haven't implemented all features.

**Comment by mskoster** [comment]
Hi,

Sorry for the delay, was away for the last few days. Please find the file attached. There is nothing secret about it, so don't worry about sharing.

Regards,

Martin Koster

**Comment by daid** [comment]
Github doesn't support directly emailing attachments, so I got no files.

**Comment by mskoster** [comment]
Sent it to your Gmail last Wednesday, did you get it?

Regards,

Martin

**Comment by daid** [comment]
Yes, I got it. Sorry that I did not let you know.

I see the same problem but I haven't found the time to trace it down yet.

**Comment by mskoster** [comment]
No problems with that, time is a scarce resource... Just wanted to make sure that the file arrived. I worked around the problem so it is no big hurry anyway.

Regards,

Martin

**Comment by daid** [comment]
I think I fixed this a while ago. In the 13.11 release. Reopen if this is not the case.
