### ISSUE TITLE
"First time calibrate problem"

### ISSUE THREAD

**Issue by Bertho** [daid/LegacyCura#41]
Calibrating the extruder in Cura’s “first time setup” does not have any warnings for the head to be hot.  There is a test for heater and temp sensor and I clicked it OK when I saw it was heating up.

Also if the Initial setup is rerun and the tests are skipped to get to the extruder calibrator there again are no warnings about head temperature. 

Sending the M302 in Printrun allowed me finally to test the extruder and it  has been working fine the whole time so I was chasing a non-existing problem.

Of course I might have missed something obvious.
Bertho

**Comment by daid** [comment]
You missed the "extrude" button? Or the fact that the extrude button in the first run wizard sends an M302. Pretty much works as designed I think. But the wizard could use some updates to be more clear and contain pictures.

**Comment by daid** [comment]
There was a problem with the first time run wizard in RC2, but it's fixed in RC3.
