### ISSUE TITLE
Cura Stats url not working

### ISSUE THREAD

**Issue by alx** [daid/LegacyCura#410]
In the setup wizard, you can accept to send stats to Ultimaker, and the result is announced on http://wiki.ultimaker.com/Cura:stats but this url is not working.

Reading the code, the profile seems to send information http://platform.ultimaker.com/curastats/ but this url is not working either.

Could someone point to the correct url and modify it in the wizard?

Thanks :)

**Comment by nallath** [comment]
The statistics are not public yet. Something will be done with them in the future, but it's not a high priority at this moment.
