### ISSUE TITLE
dmg-Download on http://daid.github.io/Cura/ broken

### ISSUE THREAD

**Issue by mnagel** [daid/LegacyCura#411]
Hi there,

on http://daid.github.io/Cura/ there is a link to a dmg at: http://software.ultimaker.com/current/Cura-13.03-MacOS.dmg
but the link seems to be broken.

Can this be fixed?
Best Regards
Michael

**Comment by daid** [comment]
I'll fix it soon, for now goto software.ultimaker.com and download it from there

**Comment by mnagel** [comment]
thanks for the info. after some googling I found the 13.04 file.
nonetheless, that link should be fixed.
thanks for the fast reply and best regards
michael
