### ISSUE TITLE
Pause at end of layer

### ISSUE THREAD

**Issue by efoxo** [daid/LegacyCura#413]
It'd be really handy to have a 'pause at end of layer' button, which moved the print head to the home position once the current layer was complete. You could then reach in to clear imperfections, or check measurements etc. The current pause button leaves the head in the way and Pla/Abs continues to leak out in little blobs, which interfere with the next layer.

Apologies if I've posted this twice. New user, not sure what I'm doing etc!

**Comment by JohanBraeken** [comment]
Hi there,

I know this is an old request, but I just stumbled upon it.

You can use the "Pause at Z height" plugin in Cura.
http://wiki.ultimaker.com/CuraPlugin:_Pauseatz

It allows to pause at a certain layer or height, and you can specify a position where the printhead needs to be "parked".
This sounds to be exactly what you want.
