### ISSUE TITLE
Cura 13.04 Print dialog won't appear

### ISSUE THREAD

**Issue by Killer-Koch** [daid/LegacyCura#418]
Hi

Suddenly the print button won't work, since the Print window doesn't show..

I'm running Windows 7 x64 and Cura 13.04

The odd thing is that it just started doing this out of nowhere, haven't been printing for a few days, then today nothing happens when i press the print button, but it do print from the Ulticontroller though, and it also connects to the printer within the wizards..

Any solution to this?

Thanks in Advance

**Comment by Killer-Koch** [comment]
It seems it has something to do with how i load and place the STL on the plane..

**Comment by nallath** [comment]
More information is required; Other users with windows 7 have not encountered the same problem.
