### ISSUE TITLE
When clicking Install default Marlin firmware with no printer connected, app crashes

### ISSUE THREAD

**Issue by hroncok** [daid/LegacyCura#419]
Hi,
when I select **Install default Marlin firmware** under **Expert** menu and I don't have a printer connected, app crashes. Using Linux version 13.04.

Backtrace and other things can be found in [bz965162](https://bugzilla.redhat.com/show_bug.cgi?id=965162).

Thanks for any help.

**Comment by daid** [comment]
Oddly enough, I also noticed this on Ubuntu 12.10 a year ago. But I could not find any cause nor solution...

**Comment by nallath** [comment]
Could not reproduce.
