### ISSUE TITLE
Bed Center 0,0,0 Rostock Feature doesn't work in v13.05 closed beta

### ISSUE THREAD

**Issue by jimustanguitar** [daid/LegacyCura#421]
I've got a Rostock printer, and the newest beta of Cura doesn't place objects at the center of the bed anymore. When I visualize the GCode using a program like Repetier, most objects are outside of the printable area even though I have the Rostock option checked in the first run wizard. The previous (current release) version of Cura does this properly, but the new closed beta does not.

**Comment by daid** [comment]
Ah, easy fix. Will be in for the next version.

**Comment by jimustanguitar** [comment]
Awesome! Thanks.

I'd be happy to test this for you, but I have no clue how to use Git... Do you plan to post a new installer soon?

**Comment by daid** [comment]
Just posted it. So grab it!

**Comment by jimustanguitar** [comment]
Looks good now, thanks!

**Comment by daid** [comment]
You're welcome (note that the GCode preview doesn't account for this setting yet, which is just cosmetic)
