### ISSUE TITLE
Cura ignoring perimeter thickness when printing with supports.

### ISSUE THREAD

**Issue by gvJaime** [daid/LegacyCura#422]
When you make a gcode with supports, wall thickness is ignored, and the printer makes only one toolpath for the shells (duplicate perimeters options still works though).

The result of this is that the shell is too weak, and tends to curl into itself, or fall down a little, making the supported surface look worse (IMHO). Besides, the upper surface has mini holes, as a result of the infill not overlapping the perimeters properly.
I don't know if this is a bug or it is done on purpose, though.

This has only been tested when support is "Everywhere", and with "duplicated perimeters" checked. I don't know if this happen with "Exterior Only" option too.

**Comment by gvJaime** [comment]
Update: It happens when you have a bridge in the print too.

**Comment by daid** [comment]
Note, I assume this is with the Cura_SF engine. Which I'm dropping soon for my own C++ engine. There is a 13.05.1 experimental release at http://software.ultimaker.com/Cura_closed_beta/ with this new engine. This new engine does not have the "skin" (duplicate perimeters) option, but I do not think it will show this bug.
