### ISSUE TITLE
not able to launch cura 13.04 on mac os x 10.7.5

### ISSUE THREAD

**Issue by carlhenrikson** [daid/LegacyCura#423]
I am unable to launch Cura 13.04 on Mac Os X 10.7.5.

The first time I installed Cura (same version) ,it did run fine. After rebooting, Cura would not start again (takes forever to start, so I force close it. Reinstalling does not seem to help.

**Comment by daid** [comment]
You could try removing the .cura directory in your home directory.

Or, there is a 13.05.1 beta here: http://software.ultimaker.com/Cura_closed_beta/ It has a huge amount of improvements.
