### ISSUE TITLE
Cura 13.04 first layer problem?

### ISSUE THREAD

**Issue by viennamik** [daid/LegacyCura#424]
Hi Daid,
First i want to say you a big "THANK YOU" for this great software.
I get now my third 3D-pinter, and it works very well on all ;-)

Now to my problem:
I change the nozzle to 0.5mm diameter for bigger parts.
I see a big difference from the first layer filling to the second layer filling.
It looks like the "infill overlap" doesn`t work on layer one.
Could you please check this?

Thank you very much.
Best regards
Mike

**Comment by daid** [comment]
Mike,

The first layer is filled the same way as the rest of the layers. However, the first layer is put down thicker then the other layers (configurable). So that might be causing the difference.

**Comment by viennamik** [comment]
Daid,
Thank you for your help, i will test it with different first layer thickness.
BR Mike
