### ISSUE TITLE
How can I make a L10n and translation for Cura

### ISSUE THREAD

**Issue by tonghuix** [daid/LegacyCura#425]
Did you make Cura I18n internationalization?

I just want to know that how can I translate it?

**Comment by daid** [comment]
I currently haven't made Cura with translation in mind. But there are more and more questions about this. I've asked my manager at Ultimaker if I should dedicate time in this.

The majority of text can be found in the settings and the initial setup wizard. And I think there will be some translation difficulties.

I think the proper term would be I18n, not L10n, as L10n implies more then just translations. I have no plans to introduce Imperial measurements for example, which would be L10n.
