### ISSUE TITLE
print window do not appear

### ISSUE THREAD

**Issue by rafaelvidal** [daid/LegacyCura#426]
depending on the place i locate the stl file the print window do not appear when i click on the button

**Comment by daid** [comment]
Sounds like a path problem, any larger indication, spaces? none-ascii characters?

**Comment by rafaelvidal** [comment]
No. I changed the file location and  worked. 

Thank you very much 

daid notifications@github.com escreveu:

> Sounds like a path problem, any larger indication, spaces? none-ascii
> characters?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/daid/Cura/issues/426#issuecomment-18828438

## 

Rafael Vidal
Ortodontista CRO/RJ-30466

Doutorando em Ciência dos Materiais (IME) 
Mestre em Ciência dos Materiais (IME) 
Especialista em DTM & Dor Orofacial (OCEX) 

www.rafaelvidalortodontia.com
