### ISSUE TITLE
Cura 13.05.1 does not generate Gcode for Thin wall object

### ISSUE THREAD

**Issue by nncc** [daid/LegacyCura#427]
When slicing the 0.5mm thin wall object from the essential calibration set (http://www.thingiverse.com/thing:5573) the generated gcode looks like http://pastebin.com/6R7WDFf7 and contains now travel command at all.

**Comment by daid** [comment]
Yes. Due to how my new engine handles insets the "0.5mm thin-wall" file doesn't generate any GCode. This is also because the "0.5mm thin wall" is not 0.5mm at all, it's thinner, more like 0.25mm.

**Comment by derrickoswald** [comment]
This is unfortunate that the new engine doesn't gracefully handle these thin walled objects. Are you saying anything less than the printer nozzle diameter won't print?

**Comment by derrickoswald** [comment]
The problem goes away with wall thicknesses of 0.5 mm (with a 0.4 mm nozzle size). It actually generates very good geometry in these cases, but suffers from apparently random connections between LayerParts leading to unnecessary stringing.

**Comment by mikeq3** [comment]
Maybe it should behave as skeinforge and slice 0.25 walls at one nozzle thickness up to nozzle size.

**Comment by daid** [comment]
And disrespect the model outline? Never.
