### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by e-z-eric** [daid/LegacyCura#428]
The following link if broken:

https://github.com/Ultimaker/CuraEngine

Can you please fix link or provide me with another one? 

Thank you in advance.
- Eric

**Comment by daid** [comment]
It's not broken, it's currently a private repository. It will be made public once an official release with this engine has been made. If you want a fully working Cura, the "master" branch has the Cura version with the Skeinforge engine.

**Comment by e-z-eric** [comment]
Hi Daid,

Thanks for getting back to me so promptly. I am trying to slice and print an STL file using cmd line using OSX (The interface is rather pretty, however). I have looked through your code and attempted to slice using -s in the following manner:

/Applications/Cura/Cura.app/Contents/MacOS/Cura  -s /Volumes/users/local/Documents/DaftGuy/DaftGuy5stl.stl 

basically running your binary file and then calling "-s" to slice DaftGuy5stl.stl

I can getting an error returning:

Traceback (most recent call last):
  File "/Applications/Cura/Cura.app/Contents/Resources/**boot**.py", line 316, in <module>
    _run()
  File "/Applications/Cura/Cura.app/Contents/Resources/__boot__.py", line 311, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Applications/Cura/Cura.app/Contents/Resources/cura.py", line 80, in <module>
    main()
  File "/Applications/Cura/Cura.app/Contents/Resources/cura.py", line 67, in main
    sliceRun.runSlice(args)
AttributeError: 'module' object has no attribute 'runSlice'

I was unsuccessful in locating runSlice.

Is this a supported feature (being able to slice and print using cmd line)?

If not, do you have any suggestions with regards to slicers that are 
capable of running via command line (in a straightforward manner)? 
Where can I find information and instructions to do this? 

I was able to pull of the print dialog when using -r with a gcode file but a .STL file seems to not work. 

I look foward to hearing from you shortly and any input would be greatly appreciated.

Best,

Eric

**Comment by daid** [comment]
Sadly, I broke the commandline slicing in that version. I have a 13.05.2 beta version out, check somewhere in http://umforum.ultimaker.com/index.php?/topic/2008-looking-for-beta-testers/ for the link.
This version should have working commandline slicing.

Also, this new beta is powered by a new engine, this engine is C++ and works from the commandline.

**Comment by e-z-eric** [comment]
Hi Daid,

I ran the following commands in CMD LINE running 13.05.2 and got the following:

local$ /Applications/Cura/Cura.app/Contents/MacOS/Cura -s /Users/local/Documents/Documents/STL\'s/mug1.stl 
Traceback (most recent call last):
  File "/Applications/Cura/Cura.app/Contents/Resources/**boot**.py", line 316, in <module>
    _run()
  File "/Applications/Cura/Cura.app/Contents/Resources/__boot__.py", line 311, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Applications/Cura/Cura.app/Contents/Resources/cura.py", line 54, in <module>
    main()
  File "/Applications/Cura/Cura.app/Contents/Resources/cura.py", line 45, in main
    slicer = sliceEngine.Slicer()
TypeError: __init__() takes exactly 2 arguments (1 given)
2013-06-10 10:07:42.446 Cura[939:507] Cura Error
I'm a bit of a noob with all this and I'm not sure what the second argument should be.. 
So how could I slice and print within the command line? Any help would be greatly appreciated.
PS. I noticed that the slicing engine is waaayyy faster, very cool. 

Regards,
Eric

Date: Fri, 7 Jun 2013 01:31:54 -0700

**Comment by e-z-eric** [comment]
Hi Daid,

Just as an FYI, I've gotten this error multiple times:

Also, I've been unable to locate sliceEngine.Sliver let alone the util file that you're importing to Cura.py. 

Again, I'm trying to slice and printe via cmd line w/o the use of your UI.

Thanks,

Eric

From: e-z-eric@hotmail.com
To: reply@reply.github.com
Subject: RE: [Cura] Broken link (#428)
Date: Tue, 11 Jun 2013 16:56:21 -0400

Hi Daid,

I ran the following commands in CMD LINE running 13.05.2 and got the following:

local$ /Applications/Cura/Cura.app/Contents/MacOS/Cura -s /Users/local/Documents/Documents/STL\'s/mug1.stl 
Traceback (most recent call last):
  File "/Applications/Cura/Cura.app/Contents/Resources/**boot**.py", line 316, in <module>
    _run()
  File "/Applications/Cura/Cura.app/Contents/Resources/__boot__.py", line 311, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Applications/Cura/Cura.app/Contents/Resources/cura.py", line 54, in <module>
    main()
  File "/Applications/Cura/Cura.app/Contents/Resources/cura.py", line 45, in main
    slicer = sliceEngine.Slicer()
TypeError: __init__() takes exactly 2 arguments (1 given)
2013-06-10 10:07:42.446 Cura[939:507] Cura Error
I'm a bit of a noob with all this and I'm not sure what the second argument should be.. 
So how could I slice and print within the command line? Any help would be greatly appreciated.
PS. I noticed that the slicing engine is waaayyy faster, very cool. 

Regards,
Eric

Date: Fri, 7 Jun 2013 01:31:54 -0700
