### ISSUE TITLE
Steam-engine packaging issue on Debian testing

### ISSUE THREAD

**Issue by Intrinsically-Sublime** [daid/LegacyCura#430]
Whenever I try to build the Debian package with  sudo ./package.sh debian
 I get the following error.

Cloning into 'Power'...
remote: Counting objects: 239, done.
remote: Compressing objects: 100% (142/142), done.
remote: Total 239 (delta 115), reused 216 (delta 92)
Receiving objects: 100% (239/239), 116.74 KiB | 153 KiB/s, done.
Resolving deltas: 100% (115/115), done.
dpkg-deb: error: control directory has bad permissions 700 (must be >=0755 and <=0775)

I tried to compile the Steam-engine branch last week and it failed the same way but figured it was just not ready for testing.

Then I tried deleting the folder to start over. I then changed the permissions of the freshly extracted folder and all of its contents and when I try and package it I get.

fatal: destination path 'Power' already exists and is not an empty directory.
dpkg-deb: error: control directory has bad permissions 700 (must be >=0755 and <=0775)

**Comment by daid** [comment]
The packaging for the steamengine branch isn't complete. As the engine part is still closed off source right now.
I'm also working with a debian maintainer to improve debian compatibility and getting Cura in the repositories.
