### ISSUE TITLE
Build Size Limit?

### ISSUE THREAD

**Issue by iceman086** [daid/LegacyCura#433]
Does Cura have a size limit on its build area? I am looking at something that would be about 1200mm x 1200 mm x 1600mm build area and I just would like to know if that would be an issue for cura to handle a build area or objects of that size.

Thanks!

**Comment by daid** [comment]
The current released version will most likely run into some memory issues. I have a beta out on the Ultimaker forums with a new engine which uses a new engine and can slice really large objects just fine.

Cura is also used for the KamerMaker project, which has a build volume of 2000x2000x3000mm, but they use very thick layers and a huge nozzle, so the end result is about the same "scale" so to say.

**Comment by iceman086** [comment]
Thank you very much for the information. Currently I plan to use the Prusa
hot end while I get the machine up and running. Once testing is done I will
be moving to a larger diameter head/custom hot end to help with the larger
build volume.

The machines design is based off of the ultimaker so the mechanical
movements will be the same.
