### ISSUE TITLE
Models not visible except in "LAYER" view

### ISSUE THREAD

**Issue by carlj0nes** [daid/LegacyCura#437]
I'm running Cura 13.04 on windows 7 64bit. Whenever I load a model, the 3D view does not change at all, and the model is almost completely invisible.
I can only see anything once I change the view to 'LAYER'.
Once I prepare the file I can still only view the file in visual style 'LAYER'.

**Comment by XiaoShiZi** [comment]
In your instalation folder go to \Cura_13.04\Cura\gui\util
In the file opengl.py (edit with IDLE) 
Search for
batchSize = 999
and change to
batchSize = 99999 
or
batchSize = 999999
save and close
Restart your Cura13.04 and load a stl file. Now you should be able to see it.
Greetz Xiao Shi Zi.

**Comment by carlj0nes** [comment]
Thanks for the quick reply. I put a figure of 999999 and it works great.
