### ISSUE TITLE
On mac dont appear print button (ver. 13.06.2)

### ISSUE THREAD

**Issue by Marakesch** [daid/LegacyCura#439]
Had before version 13.04. Deleted it first, removing from application folder. After install version 13.06.2. Uploaded model, print button remain gray, no any bar showing the process of slicing. After 10 minutes, still gray, no any possibilities to press button.

**Comment by mloepfe** [comment]
If you run Cura directly from the source folder, make sure also to compile the CuraEngine and put the executable in the Cura top directory.

**Comment by daid** [comment]
If the button stays gray, without a progress bar under it, then the CuraEngine fails to startup properly.

I do have an 13.06.3 up as download now, it fixes some issues people where having.
