### ISSUE TITLE
Try to Open a Large STL file in Cura 13.04 and error message appears "python.exe has stopped working"

### ISSUE THREAD

**Issue by carlj0nes** [daid/LegacyCura#440]
The STL file is 404,579KB due to be a scaled down version of a job at work.
The error message doesn't always appears it. Sometimes when I load the file it starts to load and then just display's a message at the bottom of the screen saying failed to load.
The other times I attempt to open it comes up with the message "python.exe has stopped working" and " A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available.

**Comment by daid** [comment]
Cura cannot handle 400MB STL files. Don't think many programs can.

**Comment by carlj0nes** [comment]
What would you suggest the largest file size would be.

**Comment by daid** [comment]
Worst I've done is 1.5mil polygons. Not sure how large that STL is, 30MB or so I guess.

**Comment by carlj0nes** [comment]
Ok I will try and reduce the file to around that size and give it a go.
Thanks for your help and I will let you know what size it will do sometime tomorrow.
