### ISSUE TITLE
when slicing 3 models 

### ISSUE THREAD

**Issue by MrBalonio** [daid/LegacyCura#441]
If I slice more that 2 models in cura, it starts to print the first two and at about layer height 1.7mm it begins the third one, 
making a mess.

**Comment by daid** [comment]
Most likely a mechanical or endstop problem at your printer. Check the GCode and you'll see the 2nd object is started at the proper Z

**Comment by MrBalonio** [comment]
No it is not, i can send u the gcode file cura produced

The printer works fine with one or two models

Want the gcode file?

On Thursday, June 20, 2013, daid wrote:

> Most likely a mechanical or endstop problem at your printer. Check the
> GCode and you'll see the 2nd object is started at the proper Z
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/daid/Cura/issues/441#issuecomment-19737885
> .

## 

"Be like water making its way through cracks. Do not be assertive, but
adjust to the object, and you shall find a way around or through it. If
nothing within you stays rigid, outward things will disclose themselves.

Empty your mind, be formless. Shapeless, like water. If you put water into
a cup, it becomes the cup. You put water into a bottle and it becomes the
bottle. You put it in a teapot, it becomes the teapot. Now, water can flow
or it can crash. Be water, my friend."
- Bruce Lee

**Comment by daid** [comment]
Sure, send it.

**Comment by MrBalonio** [comment]
attached is the file, it has 3 objects, first 2 start printing and at about
layer 1.75 it starts the third one.

**Comment by daid** [comment]
You do understand that github does not support attachments?

**Comment by MrBalonio** [comment]
i'll upload the file to my github and link you from there,
