### ISSUE TITLE
troubles witt support

### ISSUE THREAD

**Issue by Fantiki7** [daid/LegacyCura#442]
Cura 13.05.2 , Expert settings - Support - Material amount
- field doesn't work...
  With any value - the same result (like "by default")

**Comment by daid** [comment]
Are you sure? Because I see instant difference in support structures. Support structures are outside of the model to keep stuff from sacking in. It's no the internal structure (that is called infill)

**Comment by Fantiki7** [comment]
sorry, i didn't realised how to use it properly,
i thought that it means varying distance between support lines, not extruding flow
but how to change support lines frequency?

**Comment by daid** [comment]
Currently you cannot. Support material will need a huge update, I'm not even a fan of the current lines implementation, I think support can be done with way less material.

**Comment by Fantiki7** [comment]
Thanx!!
