### ISSUE TITLE
Stick to "layer" in layers view ?

### ISSUE THREAD

**Issue by peteruithoven** [daid/LegacyCura#443]
When new gcode is generated the layers view needs to be rebuild, obviously, but would it be possible to remember the current layer/height and go there automatically?
At the moment when optimizing slicing I need to move to the layers I'm interested in everytime the gcode is regenerated.

**Comment by daid** [comment]
Yes, I also noticed this problem. But I haven't found a proper solution in the code for it yet. It's on my mind, and there will most likely popup a solution in my head at some point. (I also find it highly annoying, because when working on my engine code I need to view the paths a lot)

**Comment by nallath** [comment]
Latest release candidates have this functionality.
