### ISSUE TITLE
Using Cura with multiple (different) 3D-Printers

### ISSUE THREAD

**Issue by mloepfe** [daid/LegacyCura#444]
I'm using Cura with an Ultimaker and a RostockMax. But the basic printer setup can only set once and cannot be switch later. Would it be possible to add support for multiple printers? Btw ,I like the way it is solved im Repetier-Host/Slic3r. There you have separate profiles for printer, filament and the print.

My workaround is to use one Cura from the installed package and one from the source. This way I get two different base configs.

**Comment by daid** [comment]
If you use windows, you could use multiple installs, as they go into different paths with own config files. For Mac and Linux this is not an option.

I'm not a fan of the way Slic3r does this. It introduces a lot of complexity for the "basic" user (which are much more common). I do want to introduce improvements on this area, as multiple printer setups are not uncommon, but I haven't got the proper solution for it yet.

**Comment by designfactore** [comment]
Hey mloepfe,

Interesting post, are you saying that you've gotten Cura to actually completely substitute for Repetier/Slicer on your Rostock Max?  So far I can't connect to my Max through Cura, how did you get yours to?

**Comment by mloepfe** [comment]
Hi Daid
I don't connect directly to my Rostock. I save the gcode to a SD card and run it from there.. And I have the repetier firmware on the machine (not the merlin). But if you like I can try to make it work..

**Comment by daid** [comment]
People have been noticing some connection issues with hardware not based on Arduino. The idea was that you could configure the serial port in the preferences and then it would work, however, due to a bug this doesn't work properly yet.

**Comment by designfactore** [comment]
Hi,  thanks for the reply!  My Rostock is running on a RAMBo  board, shouldn't that work? I think it has Repetier firmware though,  is there some other firmware I need?

**Comment by daid** [comment]
Not sure if it will work with repetier, you might need sprinter or marlin. But changing firmware is at your own risk.

**Comment by mloepfe** [comment]
Hi Daid

I know studied the respective code in Cura and RepetierHost and experimented with my two printers and I think I understand the differences in the protocol implementations between Marlin and RepetierFW. My local Cura version is able to communicate this my RostockMax:-)

If you are interested I could contribute a (quick) patch. But what I would even more like is to help refactor the code around machineCom.py to make it more modular, extensible and robust.. Are you interested in such contribs?

**Comment by daid** [comment]
That would be awesome. Is it possible to have it compatible for both with some kind of auto-detection?

Is the GCode the same, and just the communication different? Or are there different M commands?

**Comment by mloepfe** [comment]
Great! I think most of the staff can be made compatible with some auto-detection. But of course it depends of the features you wanna use.. The G-Code is largely the same, as long as you only use standard code;-)) But there are differences.. My idea is to define an abstract interface for the machine which can be implemented differently for different flavours of machines. The generic base class will cover everything which is largely compatible or can be auto-detected.. Everything else can be implemeted specifically for a machine.. (e.g. HW test or bed-leveling, SD card support...)

I will write some lines or example code and then we can happily discuss it. But what do you think, should we probably have a first quick-win patch version which only supports Ultimaker/Marlin and RostockMax/Repetier?

**Comment by mloepfe** [comment]
After a lot of experimenting and writing a bunch of testroutines to experimentally find out how a specific firmware behaves, I made the minimal necessary modification to machineCom.py (quick win). I can now print with my Ultimaker(Merlin) and RostockMAX(Repetier) without any communication errors or resends.

How should I transfer the changes to you? As patches here in the comments? Or is there a better prefered way? It's not a lot of changes:-)

**Comment by daid** [comment]
If it's just a few changes you could just list them. As communication is quite a critical bit, I always like to fully understand what all the conditions are.

**Comment by mloepfe** [comment]
Yes you are absolutely right - communication is key and very critical.. So I first try to explain the problems I had to solve and the explain how I solved it by explaining each patch.

The first problem is, that repetier sends 'wait' lines every second if it is idle. because of this the find_baudrate does not work and in some situations the Stk500v2.recvMessage() hangs for ever.

The next problem is that each firmware does send the 'ok' differently. Merlin send them either after a reply or on the same line with the reply. Repetier send them alwas before a reply.

The third and biggest problem is the way the fw processes commands and much data the serial comm layer can buffer. Cura currenty just assumes that it's ok to send 4 commands in advance.. But sometimes thats to much.. Especially together with the next problem and the timing of the 'ok'.

The forth problem is that every 5 seconds cura is asking for the temperatures without any regard of dataflow - it just sends the command.

The sixt problem is the very different error handling of each fw. This issue is in normal operation not extremly importent and I have not yet addressed it in the current changes. Thats postponed for a next step:-)

So how I have solved the problems? I will explain each problem in a separate post. I don't like very large posts...

**Comment by mloepfe** [comment]
Problem 1: Both methods Stk500v2.recvMessage() and machineCom._readline() expect that either sooner or later a timeout happens or the correct character will arrive. But if you have a fw sending 'wait' every second and the wrong baudrate you receive just junk..

So there are two things to fix this problem. First the easy one. Choose a timeout which is lower than the 'wait' periodocity. Thats what I have done. The send thing would be to change the two above mentioned methods to implement an absolute timeout, not only the timeout for reading a single character. Second return if a invalid character arrives (one thats not allowed in the context). And third read a max amount of chars per line. All these things I have not implemented in Cura yet. But it works also very well without it - at least with Boards which are resettable per software..

Thats a trick I also use when we change the baudrate. It's not very easy to consume all garbage in a serial comm channel (from before with previous baudrate) when you don't know what should arrive.. Because of this I soft reset (close() then open()) the board and wait a second till it booted. This way we very effectively get rid of all garbage, sync the printer and even get the full boot messages which we could analyse in later stage.

**Comment by mloepfe** [comment]
Problem 2: This problem has different facettes. The easy one you just fixed with a patch from 11.July. The more seriose problem is the change in timing. Repetier send the 'ok' immediately after successfully read the command - before it starts executing it. This means the serial comm buffer gets filled more agressively - to agressively for repetier. Togeter with always 4 commands in advance sending policy the communication breaks. An other problem very related to this one is that during heating-up the extruder, every 5 seconds we send a M105 command.. These commands just overflow the comm buffer because the printer is waiting not processing the requests. So every time we receive a temperature reply I also reset the 5 second timeout variable to prevent this M105 sending.

**Comment by mloepfe** [comment]
Problem 3: Flow controll.. I have written a smal test routine to determine the serial communication buffer's size. For both my printers it's 127. But an other board with a Taecup variant on it uses 63. We need to know this size to have a stable fast communiction. So as a first step I propose to have a editable field in the preference pane with this buffer size initialized to 127. If a Cura user with a FW with only 63 bytes buffer he can change it. In a later phase I think we should add this automatic determination of this size.

So, the trick is simple. We don't send more than 127 bytes for un'ok'-ed commands. This means keep track of all commands sent but not got an ok for and the total bytes in all these commands.

To implement this properly we need the possibility to put back a command to the queue it the buffer has not enough space left for it. The standard Queue does not provide this functionality (as mich as I know) But the alternative collections.deque does. So changed to this one.

**Comment by mloepfe** [comment]
Problem 6: Each fw send completely different error or info messages and behaves very different on error conditions. For example what happens if you send an unknown command or a comment or a checksum without linenumber of not strictly incremtn linenumbers, etc. Understanding these replies is important for a very robust and easy to use system. So for a later phase I thing we should address it.. 

But for now, the only really important thing is how the fw handles communication errors.. (which do not happen anymore with this paches.. :-))) Luckily Marlin and Repetier both send first an 'Error', the a 'Resend' and last an 'ok'. To know that this extra ok gets sent is important for the flow controll.. So when you try to print with a fw which does not send ok's after a Resend, you get problems.. with the current patches. This also should be addressed in a next phase (probably with auto detection).

**Comment by mloepfe** [comment]
Problem 7: (sorry I forgot it in my first summary;-) All over the monitor() method there are 

`if '..' in line:` expressions. In nearly all cases the string to check against must be at the beginning of the line. So we should use line.startswith() instead. I had one problem and changed the relevant statement. During a print I types in the command `M115`and got the reply 

```
FIRMWARE_NAME:RepetierMAX0.80 FIRMWARE_URL:https://github.com/seemecnc/RepetierMAX PROTOCOL_VERSION:1.0 MACHINE_TYPE:RostockMAX EXTRUDER_COUNT:1 REPETIER_PROTOCOL:2
Printed filament:31.88 m
Printing time:0 days 5 hours 12 min
```

this immediately triggered the following code... ('hours' contains 'rs')

```
                elif "resend" in line.lower() or "rs" in line:
```

**Comment by mloepfe** [comment]
So here is the complete patch:

```
@@ -11,6 +11,7 @@ import traceback
 import threading
 import platform
 import Queue as queue
+import collections

 import serial

@@ -178,7 +179,7 @@ class MachineCom(object):
        self._bedTargetTemp = 0
        self._gcodeList = None
        self._gcodePos = 0
-       self._commandQueue = queue.Queue()
+       self._commandQueue = collections.deque()
        self._logQueue = queue.Queue(256)
        self._feedRateModifier = {}
        self._currentZ = -1
@@ -189,6 +190,14 @@ class MachineCom(object):
        self.thread = threading.Thread(target=self._monitor)
        self.thread.daemon = True
        self.thread.start()
+       
+       # three attributes use to control that the comm buffer on the printer side does not overflow
+       self._comm_buff_len = 127
+       self._unacked_len   = 0
+       self._unacked       = []

    def _changeState(self, newState):
        if self._state == newState:
@@ -316,6 +325,7 @@ class MachineCom(object):
            return
        self._log("Connected to: %s, starting monitor" % (self._serial))
        if self._baudrate == 0:
+           self._serial.timeout = 0.5 # shorter than the repetier 'wait' interval
            self._changeState(self.STATE_DETECT_BAUDRATE)
        else:
            self._changeState(self.STATE_CONNECTING)
@@ -355,7 +365,8 @@ class MachineCom(object):
                    t = time.time()
                    self._heatupWaitTimeLost = t - self._heatupWaitStartTime
                    self._heatupWaitStartTime = t
-           elif line.strip() != '' and line.strip() != 'ok' and not line.startswith('Resend:') and line != 'echo:Unknown command:""\n' and self.isOperational():
+               tempRequestTimeout = time.time() + 5
+           elif line.strip() != '' and line.strip() != 'wait' and not line.startswith('ok') and not line.startswith('Resend:') and line != 'echo:Unknown command:""\n' and self.isOperational():
                self._callback.mcMessage(line)

            if self._state == self.STATE_DETECT_BAUDRATE:
@@ -373,8 +384,11 @@ class MachineCom(object):
                    else:
                        baudrate = self._baudrateDetectList.pop(0)
                        try:
+                           self._serial.close()
                            self._serial.baudrate = baudrate
                            self._serial.timeout = 0.5
+                           self._serial.open()
+                           time.sleep(1)
                            self._log("Trying baudrate: %d" % (baudrate))
                            self._baudrateDetectRetry = 5
                            self._baudrateDetectTestOk = 0
@@ -405,7 +419,7 @@ class MachineCom(object):
                    self.close()
            elif self._state == self.STATE_OPERATIONAL:
                #Request the temperature on comm timeout (every 2 seconds) when we are not printing.
-               if line == '':
+               if line == '' or line[:4] == 'wait':
                    if self._extruderCount > 0:
                        self._temperatureRequestExtruder = (self._temperatureRequestExtruder + 1) % self._extruderCount
                        self._sendCommand("M105 T%d" % (self._temperatureRequestExtruder))
@@ -413,24 +427,52 @@ class MachineCom(object):
                        self._sendCommand("M105")
                    tempRequestTimeout = time.time() + 5
            elif self._state == self.STATE_PRINTING:
-               if line == '' and time.time() > timeout:
+               if line == 'wait':
+                   # repetier sends wait (every second) if it is idle and to recover if you missed an ok
+                   line = 'ok'
+                   self._unacked     = [0]
+                   self._unacked_len = 0
+               elif line == '' and time.time() > timeout:
                    self._log("Communication timeout during printing, forcing a line")
                    line = 'ok'
+                   self._unacked.insert(0, 0)
                #Even when printing request the temperature every 5 seconds.
                if time.time() > tempRequestTimeout:
                    if self._extruderCount > 0:
                        self._temperatureRequestExtruder = (self._temperatureRequestExtruder + 1) % self._extruderCount
-                       self._sendCommand("M105 T%d" % (self._temperatureRequestExtruder))
+                       self._commandQueue.append("M105 T%d" % (self._temperatureRequestExtruder))
                    else:
-                       self._sendCommand("M105")
+                       self._commandQueue.append("M105")
                    tempRequestTimeout = time.time() + 5
                if 'ok' in line:
+                   try:
+                       cmdlen = self._unacked.pop(0)
+                       self._unacked_len -= cmdlen
+                   except:
+                       self._log('*** Q under run!')
+                       self._unacked_len = 0
+                   self._log('*** q#=%d, qlen=%d'%(len(self._unacked), self._unacked_len))
                    timeout = time.time() + 5
-                   if not self._commandQueue.empty():
-                       self._sendCommand(self._commandQueue.get())
-                   else:
-                       self._sendNext()
-               elif "resend" in line.lower() or "rs" in line:
+                   try:
+                       while True:
+                           cmd = self._commandQueue.popleft()
+                           self._sendCommand(cmd)
+                   except queue.Full:
+                       # put back command - for which it has no space left in the comm buffer
+                       self._commandQueue.appendleft(cmd)
+                   except IndexError:
+                       # Queue is empty
+                       pass
+                   
+                   try:
+                       while True:
+                           self._sendNext()
+                   except queue.Full:
+                       pass
+               elif line.lower().startswith('resend') or line.startswith('rs'):
+                   self._unacked     = self._unacked[:1]
+                   self._unacked_len = self._unacked[0]
+                   self._log('*** q#=%d, qlen=%d'%(len(self._unacked), self._unacked_len))
                    try:
                        self._gcodePos = int(line.replace("N:"," ").replace("N"," ").replace(":"," ").split()[-1])
                    except:
@@ -481,6 +531,15 @@ class MachineCom(object):
    def _sendCommand(self, cmd):
        if self._serial is None:
            return
+
+       if self._state == self.STATE_PRINTING:
+           cmdlen = len(cmd) + 1
+           if (self._unacked_len + cmdlen) > self._comm_buff_len:
+               raise queue.Full()
+           self._unacked.append(cmdlen)
+           self._unacked_len += cmdlen
+           self._log('*** q#=%d, qlen=%d'%(len(self._unacked), self._unacked_len))
+       
        if 'M109' in cmd or 'M190' in cmd:
            self._heatupWaitStartTime = time.time()
        if 'M104' in cmd or 'M109' in cmd:
@@ -544,7 +603,7 @@ class MachineCom(object):
    def sendCommand(self, cmd):
        cmd = cmd.encode('ascii', 'replace')
        if self.isPrinting():
-           self._commandQueue.put(cmd)
+           self._commandQueue.append(cmd)
        elif self.isOperational():
            self._sendCommand(cmd)

@@ -557,8 +616,9 @@ class MachineCom(object):
        self._printSection = 'CUSTOM'
        self._changeState(self.STATE_PRINTING)
        self._printStartTime = time.time()
-       for i in xrange(0, 4):
-           self._sendNext()
+       self._unacked     = []
+       self._unacked_len = 0
+       self._sendNext()

    def cancelPrint(self):
        if self.isOperational():
```

**Comment by daid** [comment]
That's quite a patch. I delay merging a bit as I'm too close to a release to go for it right now. And I have another critical thing to fix.

As you might know we're release an new machine (Ultimaker2), and for that I want to make it easier to switch between multiple machines on a single installation. This will take some effort. After that I do want to patch up the USB communications to help out with the Repetier firmware problems.

I do see some fixes that might also might prevent another issue people are having. So that's good.

**Comment by daid** [comment]
As for switching between machines, I've been adding patches to switch easier between machine configurations. This won't switch profiles, just settings like machine size, heatedbed or not and serial settings.

Easy profile switchin is also on my radar, but so much to do, so little time.

**Comment by ubaldino** [comment]
What I did to connect to cure connect to different printers was disable any call to sendMessage () function of stk500v2 besides that you add the respective identifiers serial with example VCP which is used by printers that I use and so not only look USBSER in portlist function ()

and I work with all printers that have tried.
