### ISSUE TITLE
Cura 13.06.2 with delta printer has origin (0/0) of layer view not in the center

### ISSUE THREAD

**Issue by mloepfe** [daid/LegacyCura#446]
If I use Cura with my delta printer (RostockMax) and load an object it is nocely centered in the middle of the 'normal' stl view. If I switch to the layer view after slicing, the object shows up in the front left corner instead of centered.

**Comment by animacide** [comment]
I am using 13.06.5 for Mac and I am still seeing this exact issue with Cura configured for my Delta printer.  According to the commit, this should be fixed in 13.06.3, correct?

**Comment by nophead** [comment]
I opened issue #518 for the same reason.
