### ISSUE TITLE
The view of the object is not shown (opengl related error?)

### ISSUE THREAD

**Issue by dkbe1983** [daid/LegacyCura#450]
When I launch Version 13.06.2 for debian/ubuntu, the viewfinder or part of the program where the object supposed to be shown simply does not appear.

This is my error code followd by a segmentation fault:

``` python
Traceback (most recent call last):
  File "/usr/share/cura/Cura/gui/sceneView.py", line 414, in _onRunSlicer
    self._slicer.runSlicer(self._scene)
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 114, in runSlicer
    for k, v in self._engineSettings(extruderCount).iteritems():
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 247, in _engineSettings
    'startCode': profile.getAlterationFileContents('start.gcode', extruderCount),
  File "/usr/share/cura/Cura/util/profile.py", line 778, in getAlterationFileContents
    return unicode(prefix + re.sub("(.)\{([^\}]*)\}", replaceTagMatch, alterationContents).rstrip() + '\n' + postfix).strip().encode('utf-8') + '\n'
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/share/cura/Cura/util/profile.py", line 670, in replaceTagMatch
    return pre + time.strftime('%a').encode('utf-8', 'replace')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
Closing down
Segmentation fault
```

And when clicking "in" the non-existent viewfinder (sceneview?), I get the following error:

``` python
Traceback (most recent call last):
  File "/usr/share/cura/Cura/gui/util/openglGui.py", line 185, in _OnGuiMouseDown
    self.OnMouseDown(e)
  File "/usr/share/cura/Cura/gui/sceneView.py", line 582, in OnMouseDown
    self._mouseClick3DPos = self._mouse3Dpos
AttributeError: 'SceneView' object has no attribute '_mouse3Dpos'
```

My dmesg is showing the following error related to the problem:

```
[ 1970.690180] python[3742]: segfault at 800000030 ip 00007f316b19b365 sp 00007fff95c59910 error 4 in libGL.so.1.2.0[7f316b182000+5a000]
```

I'm running Linux mint 15 64bit (based on Ubuntu 13.04) with cinnamon.

Also: [Other people seem to be having the same issue:](https://groups.google.com/forum/#!topic/ultimaker/oCtrTPrPM0Q)

**Comment by plasmasolutions** [comment]
Same here, but different error message! I'm on Ubuntu64 13.04 and can't use cura anymore. The area with the viewport is completely empty. Error message:

neo@Tidus:/tmp/Cura$ cura
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 9: reading configurations from ~/.fonts.conf is deprecated.
Flashing 99978 bytes
Verifying 99978 bytes
Traceback (most recent call last):
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 169, in _watchProcess
    self._process = self._runSliceProcess(commandList)
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 301, in _runSliceProcess
    return subprocess.Popen(cmdList, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] Datei oder Verzeichnis nicht gefunden
Closing down

After digging a bit more and restarting I've got the same error as the threadstarter...maybe it was the first run wizard that caused the slightly different error at first.

**Comment by quikshot** [comment]
same here:
OS: Ubuntu 12.04 LTS 64 bits.
Cura version 13.06.3

I open cura from terminal:
-No model window. 

No traces until I try to load a model. Then:

Traceback (most recent call last):
  File "/usr/share/cura/Cura/gui/util/openglGui.py", line 185, in _OnGuiMouseDown
    self.OnMouseDown(e)
  File "/usr/share/cura/Cura/gui/sceneView.py", line 582, in OnMouseDown
    self._mouseClick3DPos = self._mouse3Dpos
AttributeError: 'SceneView' object has no attribute '_mouse3Dpos'

If I open cura with strace, I get, by only starting cura (no user action):

open("/usr/bin/cura", O_RDONLY)         = 3
fcntl(3, F_DUPFD, 10)                   = 10
close(3)                                = 0
fcntl(10, F_SETFD, FD_CLOEXEC)          = 0
rt_sigaction(SIGINT, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGINT, {0x40f100, ~[RTMIN RT_1], SA_RESTORER, 0x7f209b6924a0}, NULL, 8) = 0
rt_sigaction(SIGQUIT, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGQUIT, {SIG_DFL, ~[RTMIN RT_1], SA_RESTORER, 0x7f209b6924a0}, NULL, 8) = 0
rt_sigaction(SIGTERM, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGTERM, {SIG_DFL, ~[RTMIN RT_1], SA_RESTORER, 0x7f209b6924a0}, NULL, 8) = 0
read(10, "#!/bin/sh\nPYTHONPATH=$PYTHONPATH"..., 8192) = 89
read(10, "", 8192)                      = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f209bc119d0) = 32375
wait4(-1, 

dmesg output:
[2385735.258350] python[32104]: segfault at 50 ip 00007fbdaae50f38 sp 00007fff055023d0 error 4 in libGL.so.1.2[7fbdaae34000+5d000]

**Comment by daid** [comment]
Note, I just changed a small thing, if someone could give the git version a shot? I was asking for a 32bit depth buffer, but MacOS did not really like that, and it might be causing issues on Linux too.

**Comment by quikshot** [comment]
Cool, I checked it from the git version and, with this change, it works!;)

Thank you daid!

However, the slicing does not work. I understood it would slice the models continuously, but it doesn't.

This is what I get: (Shall I open another issue for this?

Log: Main window appears, but after loading a model, it does not slice it and the output is attached below:

$ cura 
Traceback (most recent call last):
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 169, in _watchProcess
    self._process = self._runSliceProcess(commandList)
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 302, in _runSliceProcess
    return subprocess.Popen(cmdList, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] El fitxer o directori no existeix  --> File/folder does not exist

**Comment by daid** [comment]
That error means it cannot find the CuraEngine file, it needs the executable from https://github.com/Ultimaker/CuraEngine

**Comment by quikshot** [comment]
Ok, sorry.
Git cloned CuraEngine, and rebuilt it. I copied the binary in:
CuraEngine$ sudo cp CuraEngine /usr/share/cura/

relaunched cura...
And everything works great... Thanks Daid!! AWESOME how fast it is!! :)

**Comment by plasmasolutions** [comment]
Yep this change and the CuraEngine solved it... damn this is fast! Congratulations David!
