### ISSUE TITLE
Ext ruder Retraction dos not work

### ISSUE THREAD

**Issue by gdwinslow** [daid/LegacyCura#451]
Cure VER: 13.06.3
It worked on previous Versions

Configuration file:
[profile]
layer_height = 0.1
wall_thickness = 0.9
retraction_enable = True
solid_layer_thickness = 0.6
fill_density = 40
nozzle_size = 0.5
print_speed = 55
print_temperature = 182
print_temperature2 = 0
print_temperature3 = 0
print_temperature4 = 0
print_bed_temperature = 65
support = Everywhere
platform_adhesion = None
support_dual_extrusion = False
filament_diameter = 1.64
filament_diameter2 = 0
filament_diameter3 = 0
filament_diameter4 = 0
filament_flow = 100.0
retraction_speed = 25.0
retraction_amount = 2.0
retraction_dual_amount = 16.5
bottom_thickness = 0.2
object_sink = 0.0
overlap_dual = 0.2
travel_speed = 160
bottom_layer_speed = 16
infill_speed = 0.0
cool_min_layer_time = 20
fan_enabled = False
skirt_line_count = 2
skirt_gap = 3.0
fan_layer = 1
fan_speed = 100
fan_speed_max = 100
cool_min_feedrate = 10
cool_head_lift = False
solid_top = True
solid_bottom = True
fill_overlap = 15
support_rate = 80
brim_line_count = 20
raft_margin = 5
raft_line_spacing = 1.0
raft_base_thickness = 0.3
raft_base_linewidth = 0.7
raft_interface_thickness = 0.2
raft_interface_linewidth = 0.2
fix_horrible_union_all_type_a = False
fix_horrible_union_all_type_b = False
fix_horrible_use_open_bits = False
fix_horrible_extensive_stitching = False
plugin_config = 
object_center_x = -1
object_center_y = -1

[alterations]
start.gcode = ;Sliced {filename} at: {day} {date} {time}
    ;Basic settings: Layer height: {layer_height} Walls: {wall_thickness} Fill: {fill_density}
    ;Print time: {print_time}
    ;Filament used: {filament_amount}m {filament_weight}g
    ;Filament cost: {filament_cost}
    G21        ;metric values
    G90        ;absolute positioning
    M107       ;start with the fan off
    G28 X0 Y0  ;move X/Y to min endstops
    G28 Z0     ;move Z to min endstops
    G1 Z15.0 F{max_z_speed} ;move the platform down 15mm
    G92 E0                  ;zero the extruded length
    G1 F200 E3              ;extrude 3mm of feed stock
    G92 E0                  ;zero the extruded length again
    G1 F{travel_speed}
    M117 Printing...
end.gcode = ;End GCode
    M104 S0                     ;extruder heater off
    M140 S0                     ;heated bed heater off (if you have it)
    G91                                    ;relative positioning
    G1 E-1 F300                            ;retract the filament a bit before lifting the nozzle, to release some of the pressure
    G1 Z+0.5 E-5 X-20 Y-20 F{travel_speed} ;move Z up a bit and retract filament even more
    G28 X0 Y0                              ;move X/Y to min endstops, so the head is out of the way
    M84                         ;steppers off
    G90                         ;absolute positioning
start2.gcode = ;Sliced at: {day} {date} {time}
    ;Basic settings: Layer height: {layer_height} Walls: {wall_thickness} Fill: {fill_density}
    ;Print time: {print_time}
    ;Filament used: {filament_amount}m {filament_weight}g
    ;Filament cost: {filament_cost}
    G21        ;metric values
    G90        ;absolute positioning
    M107       ;start with the fan off
    G28 X0 Y0  ;move X/Y to min endstops
    G28 Z0     ;move Z to min endstops
    G1 Z15.0 F{travel_speed} ;move the platform down 15mm
    T1
    G92 E0                  ;zero the extruded length
    G1 F200 E10             ;extrude 10mm of feed stock
    G92 E0                  ;zero the extruded length again
    G1 F200 E-{retraction_dual_amount}
    T0
    G92 E0                  ;zero the extruded length
    G1 F200 E10              ;extrude 10mm of feed stock
    G92 E0                  ;zero the extruded length again
    G1 F{travel_speed}
    M117 Printing...
end2.gcode = ;End GCode
    M104 T0 S0                     ;extruder heater off
    M104 T1 S0                     ;extruder heater off
    M140 S0                     ;heated bed heater off (if you have it)
    G91                                    ;relative positioning
    G1 E-1 F300                            ;retract the filament a bit before lifting the nozzle, to release some of the pressure
    G1 Z+0.5 E-5 X-20 Y-20 F{travel_speed} ;move Z up a bit and retract filament even more
    G28 X0 Y0                              ;move X/Y to min endstops, so the head is out of the way
    M84                         ;steppers off
    G90                         ;absolute positioning
support_start.gcode = 
support_end.gcode = 
cool_start.gcode = 
cool_end.gcode = 
replace.csv = 
nextobject.gcode = ;Move to next object on the platform. clear_z is the minimal z height we need to make sure we do not hit any objects.
    G92 E0
    G91                                    ;relative positioning
    G1 E-1 F300                            ;retract the filament a bit before lifting the nozzle, to release some of the pressure
    G1 Z+0.5 E-5 F{travel_speed}           ;move Z up a bit and retract filament even more
    G90                                    ;absolute positioning
    G1 Z{clear_z} F{max_z_speed}
    G92 E0
    G1 X{object_center_x} Y{object_center_y} F{travel_speed}
    G1 F200 E6
    G92 E0
switchextruder.gcode = ;Switch between the current extruder and the next extruder, when printing with multiple extruders.
    G92 E0
    G1 E-36 F5000
    G92 E0
    T{extruder}
    G1 X{new_x} Y{new_y} Z{new_z} F{travel_speed}
    G1 E36 F5000
    G92 E0

**Comment by daid** [comment]
Works on my printer? When are you expecting retraction and not seeing it?
