### ISSUE TITLE
Windows doen't find my ultimaker

### ISSUE THREAD

**Issue by dree33** [daid/LegacyCura#452]
Hi,

I build myself a Ultimaker the last couple of days but at the last moment it went wrong.
If I plug my usb cable into my computer I get the warning that windows does not recognize the usb device.
In the win7 device manager I see a “Unknown Device” under USB Controllers if I only use the USB connection, that goes away if I switch on the printer but windows can't install and cura still can't make contact and nothing else Arduino appears in the device manager.
I tried to renew the driver pointing to the drivers in the Cura map, no luck.
I tried to download other and more drivers from the Arduino site… no Luck.
I have a win7 64bit computer, I tried to install Cura and drivers on my other Win7 32 bit computer, same problem. I also tried older Cura versions, no luck.
Did I miss something?
I read a lot of forum here and other blogs, cannot find a solution, please help.

Groet Dree

**Comment by daid** [comment]
Could be something wrong with the Ultimaker electronics. You're better off contacting UM support in this case.

**Comment by dree33** [comment]
Ok, thanks.

Dree
