### ISSUE TITLE
Cut off object bottom fails for negative value

### ISSUE THREAD

**Issue by lampbus** [daid/LegacyCura#453]
Cut off object bottom fails for negative value.
I tried to put in a negative value to float my object above the platform, with support enabled...13.06.3...Error 'CuraEngine.exe has stopped working.

**Comment by lampbus** [comment]
I have just realised there is a separate repository (? I am new to github etc so learning) for the CuraEngine, but I don't know how parameters are passed - I supposed they are range checked in this part?
OTOH, a negative value could be useful, so would be in the .exe.

**Comment by daid** [comment]
I noticed the same today, by mistake. But if you want some sort of support under your printer you could use the raft.

I also see a use for printing an object on top of something else, so I do want this to work. And crashing engines are always bad.
