### ISSUE TITLE
support material isnt generated for 'corners'

### ISSUE THREAD

**Issue by lampbus** [daid/LegacyCura#454]
![cura1](https://f.cloud.github.com/assets/4792361/692963/5bce34ae-dc5f-11e2-97ae-c82a4892d83e.jpg)
I have a part that has facets meeting in space.  The facets are sloped steeper then the overhang angle (could we have a setting for the angle?), so do not generate support material, but do need support.

I have tried the same model in 13.03, and it (skeinforge?) generated towers at the end for this.

**Comment by lampbus** [comment]
This should be in the .exe repository? is there a way to copy / move this over?

**Comment by daid** [comment]
Just report it here, no problem. Support material needs more work, I'm not that happy about it. I tried to reproduce about the same as SF did. But SF does a few thing different. Not sure how it knows where to put those towers.

**Comment by unkledoc** [comment]
I have the same problem with cura 14.01. I am printing a spartan helmet, and the roster tails (front and back) does not get supported, and only some of the internal overhangs get supported.
![image](https://f.cloud.github.com/assets/6964193/2430234/b39a8570-acc5-11e3-9f7a-0bc51973a65b.png)
![image](https://f.cloud.github.com/assets/6964193/2430237/d243c9e6-acc5-11e3-826f-3fdf70c9c2a3.png)

**Comment by ghost** [comment]
I have these issues too in 14.07, it seems  like if it count the angle between two layers. But it fail generating towers for cantilever surfaces like fingers in human sculptures.
