### ISSUE TITLE
No main window after splash screen on Linux.

### ISSUE THREAD

**Issue by mikeq3** [daid/LegacyCura#455]
I got the first time config window on the very first run but after that no main window. Now on every run I just get the splash screen and then nothing. no errors when it is run in a terminal. I'm running Linux (not debian) and trying 13.06.2. I had no problems running 13.03.

**Comment by daid** [comment]
I think this is the same problem as other people are experiencing on Linux. Could you check if the latest git still has this issue?

**Comment by quikshot** [comment]
I think this is a duplicate of #450.

**Comment by mikeq3** [comment]
I tried the latest git and it works now thanks David. Saw your interview on 3D Hackers. Nice work.
