### ISSUE TITLE
Cura 13.06.3 (development version) in Linux, does not slice after loading a model

### ISSUE THREAD

**Issue by quikshot** [daid/LegacyCura#456]
OS: Ubuntu 12.04 LTS 64 bits
Cura: 13.06.3 git version.

After loading a model the model is not automatically sliced, nor I can slice it. 

I get the following output:

$ cura 
Traceback (most recent call last):
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 169, in _watchProcess
    self._process = self._runSliceProcess(commandList)
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 302, in _runSliceProcess
    return subprocess.Popen(cmdList, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] El fitxer o directori no existeix --> File/folder does not exist

I can test any change you propose.

BR,
Marc

**Comment by ad1217** [comment]
I am having the same problem, and would also be willing to test.

**Comment by quikshot** [comment]
As commented by Daid in #450, I did:

$ git clone https://github.com/Ultimaker/CuraEngine.git
$ cd CuraEngine
$ make
$ sudo cp CuraEngine /usr/share/cura/

$ cura
relaunch cura and everything is working great.
