### ISSUE TITLE
wxWindow::DoSetSize: Process /usr/bin/python2.7 was killed by signal 11 (SIGSEGV)

### ISSUE THREAD

**Issue by hroncok** [daid/LegacyCura#457]
Hi,
when running cura 13.06.3 on Linux, I get splash screen and wizard (if no ~/.cura exists) and then SIGSEGV. Reproducible always.

[Here](https://bugzilla.redhat.com/show_bug.cgi?id=977432) are some backtraces and similar stuff.

From what I tried to investigate, something in wx is trying to touch parent, but there's NULL.

Could you please give me a hand with what to investigate? Thanks.

**Comment by balwierz** [comment]
Same issue under Arch Linux.

**Comment by daid** [comment]
I've pushed a change into the git version yesterday, this changes the OpenGL depth buffer from 32 to 24 bit. The older versions used 24 bit, I changed it to 32bit for some tests but I forgot to change it back. On Linux this is causing crashes.

**Comment by hroncok** [comment]
So I should just apply 87a4ff5235e912305500bebec999865120bfcb06?

**Comment by daid** [comment]
Yes

**Comment by balwierz** [comment]
I think it is important to change the depth in Cura/gui/tools/superformula.py too. Otherwise superformula / supershaper is crashing too:

---

```
diff -r src.old/usr/share/cura/Cura/gui/tools/superformula.py src/usr/share/cura/Cura/gui/tools/superformula.py
104c104
<       attribList = (glcanvas.WX_GL_RGBA, glcanvas.WX_GL_DOUBLEBUFFER, glcanvas.WX_GL_DEPTH_SIZE, 32, glcanvas.WX_GL_STENCIL_SIZE, 8)
---
>       attribList = (glcanvas.WX_GL_RGBA, glcanvas.WX_GL_DOUBLEBUFFER, glcanvas.WX_GL_DEPTH_SIZE, 24, glcanvas.WX_GL_STENCIL_SIZE, 8)
471c471
<       attribList = (glcanvas.WX_GL_RGBA, glcanvas.WX_GL_DOUBLEBUFFER, glcanvas.WX_GL_DEPTH_SIZE, 32, glcanvas.WX_GL_STENCIL_SIZE, 8)
---
>       attribList = (glcanvas.WX_GL_RGBA, glcanvas.WX_GL_DOUBLEBUFFER, glcanvas.WX_GL_DEPTH_SIZE, 24, glcanvas.WX_GL_STENCIL_SIZE, 8)
```

**Comment by hroncok** [comment]
Changing the depth to 24 in both places prevents the SIGSEGV.
