### ISSUE TITLE
Selecting a previous model from the recent model files list causes gcode save issue

### ISSUE THREAD

**Issue by mikeq3** [daid/LegacyCura#458]
When selecting a previous model from the recent model files list,  gcode save dialog has a blank "Save In Folder" selection. No directory path is set.

**Comment by mikeq3** [comment]
I was wrong on this issue.  It happens most of the time after loading a model. Not just from MRU list. Also there is no .gcode extension on the filename saved. Commit 458 did not fix this.

**Comment by daid** [comment]
OS?

**Comment by mikeq3** [comment]
Linux
