### ISSUE TITLE
Some parameters are missing values in gcode output

### ISSUE THREAD

**Issue by mikeq3** [daid/LegacyCura#459]
These values are not set in the gcode output:
;Print time: {print_time}
;Filament used: {filament_amount}m {filament_weight}g
;Filament cost: {filament_cost}

Output looks like this:
;Print time: #P_TIME#
;Filament used: #F_AMNT#m #F_WGHT#g
;Filament cost: #F_COST#

**Comment by mpatoulachik** [comment]
This is a bit annoying when you open an old Gcode file you want to print and have no clue about how much filament you will need or how long it will take...

The code involved seems to be the "replaceGcodeTags" function, line 708 in profile.py
Not sure why it doesn't works though..

**Comment by PWrzesinski** [comment]
This is pretty anoying, as I'd like to use this values to plan the printing queue and filament usage. I'd really appreciate a fix for this.

**Comment by daid** [comment]
I am planning to fix this, but I'm very busy with a lot of things.

**Comment by daid** [comment]
Patch #632 fixed this for commandline slicing, not sure what the state of the tags is for GUI slicing.

**Comment by mpatoulachik** [comment]
This issue is still present in Cura 14.03

**Comment by dc42** [comment]
I too find that it is still present in Cura 14.03.

**Comment by miguelangellv** [comment]
Still present in Cura 14.07

**Comment by daid** [comment]
Sorry, status of this issue is "won't fix" right now. I'm making good progress with my total-rewrite of the Cura frontend. Which has a lot of architectural changes. Which makes stuff like this issue not something that is hacked on top, but part of the actual code architecture.
