### ISSUE TITLE
Add support for calculating filament cost to print statistics

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#46]
I would be interested in a displayed estimated cost with the other stats on the print screen. You'd presumably need to be able to set how much you paid for your filament somewhere in the preferences or something.

I'm requesting this more because I find the information interesting than because I have a great need for it. As it is I end up doing it in my head for most prints based on an estimated cost.

**Comment by daid** [comment]
Should be quite simple, I can just add a cost per weight or cost per length preference, and if that's filled in then you also get the cost stats.

**Comment by RedwoodForest** [comment]
Confirmed implemented. Thanks!
