### ISSUE TITLE
Feature Request Different layer temps

### ISSUE THREAD

**Issue by skywurz** [daid/LegacyCura#461]
I would like to request the addition of different layer temp. I like to start my abs prints cold and then set the bed temp higher as it takes forever to warm up i know people like to set temps cooler after the first layer for things like pla

**Comment by daid** [comment]
You could use the TweakAtZ plugin: http://wiki.ultimaker.com/CuraPlugin:_TweaktAtZ
Combined with http://wiki.ultimaker.com/CuraPlugin:_Bedtempatz

I am thinking about a different temperature for the first layer, as this seems to help a lot for PLA.

**Comment by skywurz** [comment]
i have tried to use those but end up with cura not exporting anything past the start code
