### ISSUE TITLE
Command line slicing fails with error

### ISSUE THREAD

**Issue by thinkyhead** [daid/LegacyCura#462]
When I try to slice from the command line I get the error below. After the error has been thrown, the file "/var/tmp/Cura_TmppqiPOo" does exist, so probably slicer.wait() is failing to wait for slicing to finish.

```
$ Cura -i mendel-abs.ini -s big-gear.stl 
Traceback (most recent call last):
[…]
"/.../Cura.app/Contents/Resources/cura.py", line 54, in main
    shutil.copyfile(slicer.getGCodeFilename(), args[0] + '.gcode')
  File "shutil.pyo", line 82, in copyfile
IOError: [Errno 2] No such file or directory: '/var/tmp/Cura_TmppqiPOo'
```

**Comment by daid** [comment]
Ah, yes, I broke this unintentionally when fixing issues with virus scanners. Pushed a fix into git, will be out soon.

**Comment by thinkyhead** [comment]
This now works in 13.06.5.

**Comment by rishabh2809** [comment]
I am still getting this error when using command line slicing. Any solution?
