### ISSUE TITLE
Unable to get a print window in current git version.

### ISSUE THREAD

**Issue by mikeq3** [daid/LegacyCura#466]
When selecting print from the File menu only a gcode save dialog is shown. No print window after that. Save toolpath on the 3D view is the same. No print window.

**Comment by daid** [comment]
Right mouse button on the save button allows you to popup the USB printing window. I change the behaviour of the "Print" file menu entry, because that indeed does not match expectations.

**Comment by mikeq3** [comment]
File->Print works now thx.
