### ISSUE TITLE
Last model loaded is not loaded when Cura starts up.

### ISSUE THREAD

**Issue by mikeq3** [daid/LegacyCura#467]
The last model loaded is not loaded when Cura starts up. The 3D view is blank no model is loaded. I checked the preferences.ini and lastfile is set correctly.

**Comment by mikeq3** [comment]
Forgot to mention, no python errors in the terminal window. So it looks like it doesn't even try to load a model on startup.

**Comment by daid** [comment]
This is intentional. People didn't like the last-model load. And with the option to load multiple files at once this did not feel right anymore.

**Comment by mikeq3** [comment]
Non-issue then.
