### ISSUE TITLE
Remove pypy from Debian build script

### ISSUE THREAD

**Issue by Thav** [daid/LegacyCura#468]
https://github.com/daid/Cura/blob/SteamEngine/scripts/linux/debian/DEBIAN/control

-Depends: python-wxgtk2.8, python-opengl, python-serial, python-numpy, pypy
+Depends: python-wxgtk2.8, python-opengl, python-serial, python-numpy

This was just too minor to make a fork. After this change, installing and running the created package appears to be fine.

**Comment by daid** [comment]
ah, yes, I already made this change on my virtual linux machine, but I forgot to push it.

**Comment by Thav** [comment]
Looks like this was fixed today.
