### ISSUE TITLE
Can't save GCode

### ISSUE THREAD

**Issue by Thav** [daid/LegacyCura#469]
After slicing a model, I attempt to save with File>Save GCode..., I get a popup "Failed to Save" and an error at the command line (<type 'exceptions.TypeError'>, TypeError('coercing to Unicode: need string or buffer, NoneType found',), <traceback object at 0x48a5d40>)

I see that that message pops up in sceneView.py as an exception in _copyFile, but I can't find where _copyFile is called to trace any further.

**Comment by daid** [comment]
Which version? How did you open the model?

**Comment by derpeter** [comment]
Same here with Cure 13.06.4 also same error when trying to print from cura (Ubuntu 13.04 64bit)
Opend the model via the open button. 

Traceback (most recent call last):
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 169, in _watchProcess
    self._process = self._runSliceProcess(commandList)
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 302, in _runSliceProcess
    return subprocess.Popen(cmdList, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
(<type 'exceptions.TypeError'>, TypeError('coercing to Unicode: need string or buffer, NoneType found',), <traceback object at 0x7f68d0047128>)
(<type 'exceptions.TypeError'>, TypeError('coercing to Unicode: need string or buffer, NoneType found',), <traceback object at 0x55020e0>)
(<type 'exceptions.TypeError'>, TypeError('coercing to Unicode: need string or buffer, NoneType found',), <traceback object at 0x551ac20>)
Traceback (most recent call last):
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 169, in _watchProcess
    self._process = self._runSliceProcess(commandList)
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 302, in _runSliceProcess
    return subprocess.Popen(cmdList, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
(<type 'exceptions.TypeError'>, TypeError('coercing to Unicode: need string or buffer, NoneType found',), <traceback object at 0x7f68d0030f80>)
Closing down

**Comment by daid** [comment]
The .4 release on Linux has an issue, it's missing the compiled CuraEngine. People have compiled it themselves from https://github.com/Ultimaker/CuraEngine and put it in the proper spot.

**Comment by derpeter** [comment]
Did the compiling but what is the "proper spot?" any hint would be very appreciated

**Comment by daid** [comment]
/usr/share/Cura/

**Comment by derpeter** [comment]
Ah i thought of /usr/bin/ ... wouldn't that make more sense as you can call it also standalone?

**Comment by daid** [comment]
It should look there also in the future, but doesn't yet.

**Comment by oni303** [comment]
fixed in .5
