### ISSUE TITLE
Adjust fan speed during cool

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#47]
I'd like the ability to adjust the fan speed during layers when cooling is active.

I replaced the stock fan duct on my machine with Owen's duct, which seems to put quite a bit more air on the piece, so I've been experimenting with running the fan at 50% speed, but I'd like to increase it during layers when cooling is active.

I'd be happy with either the ability to run it at full speed when cooling is active or to define a separate speed for the fan during cooling layers.

**Comment by daid** [comment]
Maybe a min/max fan speed like Slic3r has would do the trick? Min speed is used during "normal" layers, but when it slows down due to cooling, to speeds up the fan, the slow it goes the higher the fan speed?

**Comment by RedwoodForest** [comment]
Sounds good to me.
