### ISSUE TITLE
Option for changing mouse mode

### ISSUE THREAD

**Issue by korpx** [daid/LegacyCura#471]
Add preference option or ini setting for changing the mouse/navigation mode.

A bunch of other 3D-related software like OpenSCAD, Repetier Host etc rotates the view with left mouse button and it can be quite confusing not being able to set the same behaviour i Cura.

**Comment by daid** [comment]
Repetier host and OpenSCAD do not support selecting and moving objects in the 3D window. Cura does, which is something you want to do with the left mouse button. This feels natural, unless your mind is twisted by Blender, at which point you select with right mouse button, unless you are in a tool, then it's the left, and rotation happens with the middle mouse button.
Oh, and 3D studio max does it differently, and Maya also, and application X does it even different.

But, I won't be adding an configuration option. You'll learn to live with it, you'll get used to it.

**Comment by korpx** [comment]
While I respect your decision I thought I'd clarify a few things.

You can move objects just fine in Repetier host 3D view, with the right mouse button. Wether or not this feels natural is entirely a personal preference with the user. And yes, many applications does this differently, and every user is used to a certain user experience and way of doing things. That's why I thought I'd suggest making it optional.

Anyway, it's not like it's a critical issue. We'll learn to live with it. Thanks for your great work with Cura!

**Comment by daid** [comment]
Note that people are asking configuration settings for just about everything. If I went and implement those all I would lose where Cura stands for, the simplicity. So my general response is to deny people configuration settings. (extra settings also make it harder to track down bugs in some cases)
