### ISSUE TITLE
Cannot pan in (13.06.4 Ubuntu - 13.06.5 Mac)

### ISSUE THREAD

**Issue by sasha42** [daid/LegacyCura#472]
I cannot seem to pan around in this version of Cura. Nothing happens when I click and drag. I can only zoom in and out using the trackpad. A different user confirmed this to me over IRC aswel.

**Comment by lampbus** [comment]
I use <right> mouse button to rotate the view, and press <shift> too to pan (slide the view left/right/up/down). Is that what you need or is there another problem.

**Comment by sasha42** [comment]
Using the left or right button no longer works for me when I rotate the view.

**Comment by daid** [comment]
A few more people have reported this. I might have an idea what is causing it. Can I send you a test version soon?

**Comment by lerouxb** [comment]
I'm still getting this in 15.02.1 in OSX until I restart Cura. It just starts happening at random, sometimes it happens from the start so I end up launching Cura, closing it, launching again, then it suddenly works.

I can zoom in and out using my trackpad, but I can't rotate.

**Comment by daid** [comment]
Internally in wxPython the shift key on OSX gets "stuck" to "down" sometimes, which is causing this problem. We'll be dropping wxPython soon, so then this issue will be finally gone for good.
