### ISSUE TITLE
Cancel Print during warmup does not set target temp to 0

### ISSUE THREAD

**Issue by richardjm** [daid/LegacyCura#476]
If you are warming up and hit cancel print the temperature continues to rise until you close the printing window and reopen it.

Even though the "Temp" setting clearly states "0"

![warmup](https://f.cloud.github.com/assets/2081919/725674/1b2fefc2-e093-11e2-8c13-21b4eb54fe93.png)

**Comment by richardjm** [comment]
Also this may be related (rather than open a separate issue) - the jog controls don't seem to work after cancel print in this state - is it maybe because the printer is still trying heat up to temp?

**Comment by j0uni** [comment]
Also problem with the "console" - if you choose "Stop printing" it stops printing but heating continues. I think it should also cool down.

Also when choosing "auto home" and the heating is enabled it goes to home position and burns a nice hole into the acrylic building platform (if you leave it there).

**Comment by daid** [comment]
Yes, the printer goes into an heatup state (M109 command) which doesn't finish till the heating is done. Until the M109 is finished the command window cannot do anything else. I might fix this at some point, but right now I see it as annoying but not world shocking.

**Comment by j0uni** [comment]
True. 

What about auto home? It really burns a hole to the platform if you don't notice that heating is on. The nozzle is so close that it melts the platform. Atleast on my printer it did..

ps. Daid: nice of you that you really read these issues and respond (and so quickly!)

**Comment by daid** [comment]
auto home is also a command, I cannot do commands during the M109. It's even worse for M190, which is "wait till heated bed is heated up", that never finishes.
