### ISSUE TITLE
Temp button not using specified extruder temp for print

### ISSUE THREAD

**Issue by richardjm** [daid/LegacyCura#477]
There is a button beside the extruder temp that doesn't seem to use the temp setting for the print.

Also if there is one for the extruder why isn't there one for the bed?

![spuriousbutton](https://f.cloud.github.com/assets/2081919/725678/440c2644-e094-11e2-911d-1f16c9e50a5f.png)

**Comment by mikeq3** [comment]
That button is to allow you to quickly set a common nozzle temp for PLA. It is there for convenience if you want to preheat your nozzle. After you click print whatever you set for "Printing temperature" will be set as the nozzle temp. To preheat a different temp you would just use the up/down arrows on the temp select box or type it in and hit enter.

**Comment by richardjm** [comment]
I just thought it would make more sense to have buttons matching the values of the UI at the point at which the print was opened. When printing with ABS for example the button is nothing more than a distraction.
