### ISSUE TITLE
When not using an Ultimaker it's difficult to work out the "front" of the bed in the view

### ISSUE THREAD

**Issue by richardjm** [daid/LegacyCura#478]
If you're not using an ultimaker it's hard to tell where is the "front" of the print area is.

Perhaps there could either be a "reset" view" or some graphical element to help orient the printer area.

![whichway](https://f.cloud.github.com/assets/2081919/725685/ceaf1bda-e094-11e2-877d-6253f7318314.png)

**Comment by lampbus** [comment]
like a mark at x,y,z=0? do all printers home to the same corner?

**Comment by richardjm** [comment]
Certainly Rostock doesn't but I think it's fairly normal to have x,y,z = 0 at the front left of the print area.

**Comment by daid** [comment]
I'll add some indicator in the front left corner when you are not using an Ultimaker.

**Comment by nallath** [comment]
Also; The home (keyboard) button resets the view.
