### ISSUE TITLE
Feature: Center part in print area

### ISSUE THREAD

**Issue by richardjm** [daid/LegacyCura#479]
Would be nice if there was an easy way to right click a part and tell it to center on the print area.

I'm thinking of an extra option on the right-click menu of a part.

**Comment by ErikDeBruijn** [comment]
Thanks for the many suggestions. However, I don't really see why centering it with a single drag would be much harder than right-click + choosing center?

**Comment by richardjm** [comment]
I think it's because I don't know where the exact centre of the bed is in the diagram. I find myself deleting the part and re-adding to ensure it's in the centre.

**Comment by grimmy** [comment]
The delete and re-add works great, unless you split an object and are only trying to print one object from it.

**Comment by daid** [comment]
Should be simple to add in the right-mouse-context menu. Give me a minute ;-)
