### ISSUE TITLE
Extra wall thickness for bottom/top does not work

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#48]
Slicing http://www.thingiverse.com/thing:18479 

0.05mm layers
Extra wall thickness for bottom/top set to 0.1mm

Following is the first several lines of GCode (including my start.gcode). Note that the first layer starts at Z0.05.

;TYPE:CUSTOM
G21        ;metric values
G90        ;absolute positioning
G28 X0 Y0  ;move X/Y to min endstops
G28 Z0     ;move Z to min endstops
G92 X0 Y0 Z0 E0 ;reset software position to front/left/z=0.0
G1 Z5.0 F400
M109 S205  ;wait for temperature to be reached
G1 Z15.0
G92 E0         ;zero the extruded length
G1 F75 E5
G1 E3.5
G92 E0         ;zero the extruded length again
G1 X10.0 Y30.0 F9000
G1 Z1.0 F400
G90 ;set positioning to absolute
G21 ;set units to millimeters
M113 S1.0
M108 S25.0
;LAYER:0
;TYPE:SKIRT
G1 X70.1736 Y89.5242 Z0.05 F9000.0
G1 X72.3313 Y105.027 F1500.0 E0.04772
G1 X86.7567 Y121.7753 E0.11512
...snip till end of skirt...
G1 X79.1684 Y88.0597 E2.75125
G1 X79.6675 Y88.1602 E2.7528
;TYPE:WALL-INNER
G1 X80.412 Y88.5218 F9000.0
G1 X82.7545 Y88.1415 F4500.0
G1 X82.8603 Y87.8726 F1500.0 E2.75369
G1 X83.0767 Y87.6317 E2.75467

**Comment by RedwoodForest** [comment]
Mea Culpa; I set this when what I actually wanted was "Initial Layer Thickness".

**Comment by daid** [comment]
Can happen. But your actual issue is correct, the extra wall thickness on bottom doesn't work as you would expect, but it does do wonders for watertight vases ;-)
It only adds the extra wall thickness to every other layer. So layer 0,2,4 get extra thickness, but 1,3 don't. This is intentional, but not clear from the setting.
