### ISSUE TITLE
Monitor for new 3D design files written

### ISSUE THREAD

**Issue by ErikDeBruijn** [daid/LegacyCura#488]
If a native CAD tool saves a file, Cura could suggest opening it (non-blocking UI) or uploading it to Youmagine.
- [ ] Discover new files (fs monitoring, filter on known formats?)
- [ ] On clicking "Add", add newly written file to build plate.
- [ ] Possibility to Upload NATIVE files to Youmagine

**Comment by nallath** [comment]
Will be implemented with the GUI overhaul.
