### ISSUE TITLE
Cylindrical glitch

### ISSUE THREAD

**Issue by farrellt** [daid/LegacyCura#489]
New cura does not like to make perfect cylinders, especially those with wall thickness of the extruder head, or even double (ie. 0.4mm and 0.8mm). Should just do one full lap, move up layer height and then continue, however it either skips portions causing distortion or makes an infinite polygon or a birds nest pattern deposting small amounts at opposite sides. however cura 13.04 knows how to do this properly
![prob 2](https://f.cloud.github.com/assets/4944116/751278/48424c92-e4f0-11e2-8646-e7a09a89e784.jpg)
![prob 1](https://f.cloud.github.com/assets/4944116/751279/48781f5c-e4f0-11e2-8c54-bb9456268696.jpg)

**Comment by daid** [comment]
I disagreed with how Cura 13.04 handled thin objects, which it did not keep the extrusion inside the bounds of the object. (Pretty much ignoring your object and just do something in between of the lines)

The missing extrusion bits are simple rounding errors causing the engine to decide not to put material there.
