### ISSUE TITLE
Print window does not display correctly on Mac

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#49]
When the print window is opened on my Mac it is sized incorrectly and the statistics information is displayed on top of the buttons.

http://i1162.photobucket.com/albums/q531/lawrencejohnston/Github/PrintWindowBug.png

Additionally the window may be resized small enough that the temp control is hidden (off the window to the right).

**Comment by daid** [comment]
I love these little MacOS quirks :P

Small note of warning on the printing window, when you use it, do not use the main Cura window to load new STL files or flip/scale/move the model, as it will halt the printing while it's updating the 3D model (pretty serious bug)
