### ISSUE TITLE
Incorrect GCode (printing in mid-air) , 13.06.5

### ISSUE THREAD

**Issue by vnks** [daid/LegacyCura#491]
Slicing heartgear1.stl from http://www.thingiverse.com/thing:12208 produces GCode that attempts to print in mid-air. This is especially noticeable with low infill - 5 % infill, 0.2mm layer height, layer 84 starts printing in mid-air, with nothing underneath it.

![image](https://f.cloud.github.com/assets/3287175/755680/4dfa9e2e-e5bc-11e2-84ad-31971a94fb70.png)

**Comment by nallath** [comment]
Could not reproduce.
