### ISSUE TITLE
Cura 13.06.5 Does not slice my stl, no matter how simple it is.

### ISSUE THREAD

**Issue by felipepdoac** [daid/LegacyCura#492]
Hi,

I'm trying to do simple prints, I load the stl to Cura, the model goes from blue to green, however the status bar doesn't appear and the save / print icon remains inaccessible. What could be the issue?
![captura de tela 2013-07-06 as 23 10 49](https://f.cloud.github.com/assets/4955900/757273/bab887c8-e680-11e2-9f60-9bf718f3f00a.png)

**Comment by daid** [comment]
Could you check if the "show slice engine log" from the file menu shows any extra information? (A few people seem to have this bug, and I have no idea what is causing it)

**Comment by ghost** [comment]
in engine los not show anything... i have the same problem... i´m try delete the aplicatión and reinstall, but some times are ok, and other no

**Comment by ghost** [comment]
i´m use osx 10.8.4

**Comment by ounim** [comment]
I had the same issue and it cames from the first line of the start.gcode. I removed it and it worked fine.

There was a python error : 
Traceback (most recent call last):
  File "/usr/share/cura/Cura/gui/sceneView.py", line 420, in _onRunSlicer
    self._slicer.runSlicer(self._scene)
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 116, in runSlicer
    for k, v in self._engineSettings(extruderCount).iteritems():
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 259, in _engineSettings
    'startCode': profile.getAlterationFileContents('start.gcode', extruderCount),
  File "/usr/share/cura/Cura/util/profile.py", line 793, in getAlterationFileContents
    return unicode(prefix + re.sub("(.){([^}]*)}", replaceTagMatch, alterationContents).rstrip() + '\n' + postfix).strip().encode('utf-8') + '\n'
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/share/cura/Cura/util/profile.py", line 683, in replaceTagMatch
    return pre + time.strftime('%d %b %Y').encode('utf-8', 'replace')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5: ordinal not in range(128)

Does it help to solve the issue or do you need more information?

**Comment by daid** [comment]
yes, remove the {date} from the start code and it will work. It's an issue that has been plaguing me for a while now. I'll release a minor bugfix release soon.

**Comment by 614mediagroup** [comment]
I get the same on windows 7 and deleting the date in the gcode does not help.

**Comment by ghost** [comment]
In mac work deleting this..

Enviado desde mi iPhone

**Comment by smallmule** [comment]
I have solved

**Comment by Funkcikle** [comment]
good for you, care to share ?
