### ISSUE TITLE
Raft layer too small to build support structure

### ISSUE THREAD

**Issue by plaplapla** [daid/LegacyCura#493]
In Cura 13.06.4 windows,  if I set platform adhesion type to raft and set support to "touching buildplate" or "everywhere",  the support structure would be build from the 3rd layer(1st & 2nd layers are raft). However, the raft layer usually is not big enough for the support. So, the support could not stick on the build platform firmly.

**Comment by daid** [comment]
Yes, known problem, looking for the best way to fix it. Note that a brim is usually a better solution then a raft.

**Comment by loelkes** [comment]
Same problem with the skirt: it does not include the support material.

**Comment by daid** [comment]
Working on this combined with new support material, see a preview here: http://daid.eu/~daid/Cura-support2.png
