### ISSUE TITLE
Minium layer time impacts print time estimate in wrong direction

### ISSUE THREAD

**Issue by illuminarti** [daid/LegacyCura#496]
If you set the minimum layer time to zero, then the estimated print time is proportional to print speed, as expected.

If you then gradually increase the minimum layer time, and allow it to reslice, then at low minimum layer times the estimated print time doesn't change, as expected, since the layer times are already longer than that small, but non-zero minimum.

However, once you reach a minimum layer time at which the print would be slowed down, the reported print time in Cura starts to get smaller, rather than higher. With very high minimum layer times, you can get reported total print time down to just a minute or two, for multi-hour prints.

**Comment by CapnBry** [comment]
This is actually a bug for daid/CuraEngine. The bug is in gcodeExport.h:438

```
this->totalPrintTime = totalTime * factor;
```

The \* should be / as factor is the percentage (less than 1.0)

**Comment by daid** [comment]
Pushed the fix to the engine source code.
