### ISSUE TITLE
Sudden extruder reverse

### ISSUE THREAD

**Issue by NilsRoe** [daid/LegacyCura#497]
I was trying to print out an endstop and during the print, the extruder ran in reverse at its maximum speed and spat out the filament. It then ran forwards at maximum speed, for about the same time (a couple of seconds). It seems to be a repeatable bug, because it always happens at the layer in 3.2mm height. This is the first day I'm using Cura, though I have used other slicers before. 

I fired up another print, waited for the bug to happen, and it happened in 3.2mm height. I quickly grabbed the extruder's gear and held it until it went back to "normal" extrusion. It extruded quite an amount of material into the unfinished piece.

I don't know if this has been reported yet, but it seemed very weird to me. Curiously, Cura is the slicer, that has gotten the best results out of my printer so far, except for this bug. That pretty much ruins it :/

![ruined_endstop](https://f.cloud.github.com/assets/5000237/791561/91ccf100-eb49-11e2-8807-a5a6b00f73e8.jpg)

**Comment by ahmetcemturan** [comment]
You should post the gcode..

**Comment by ghost** [comment]
I've exported the Gcode and found no problems with it. I've changed the printer's firmware from Sprinter to Marlin and now it works a treat. It seems to be the "prevent lengthy extrusions" feature that solved the problem.

Here's the gcode nonetheless:
https://dl.dropboxusercontent.com/u/22548419/endstop.gcode

EDIT: Sorry that I didn't write this in the first place:

I'm using a RepRap Prusa Mendel, with RAMPS, formerly with Sprinter, now Marlin firmware. It has worked OK with other software before, but I'm still fine-tuning it.

**Comment by daid** [comment]
I've been testing with USB printing and SD printing a lot recently, especially on getting the reliability up. And this is actually related to an data transfer error. I've seen it happen with SD card printing when adding interference on the SD card connection cable.

Which cased G code commands to get messed up and read incorrectly. There is no error checking on SD card printing, which is the main cause for what I saw. Are you using SD card? Are you printing USB? Which host software did you use? Cura or PrintRun?

**Comment by ghost** [comment]
I'm printing in Cura, in USB mode. My SDRAMPS is still on its way here. The printer is connected to a powered USB hub which is then directly connected to my PC. I moved the furniture around in my room and had to use a hub plus a long cable to connect the printer to my PC again. I haven't tried using the shorter cable again.

**Comment by ghost** [comment]
I'm currently printing with the printer attached directly to my PC with a 1 meter cable. It seems the Arduino just didn't like the hub and the long cable. I'm getting no "Serial timeout" messages ATM, and no mis-prints due to serial communication errors.
