### ISSUE TITLE
Custom presets (& customizing quick print)

### ISSUE THREAD

**Issue by peteruithoven** [daid/LegacyCura#502]
Currently there is a seperate simple and advanced mode. As a advanced user I would like to use the quickprint types as a basis and then continue on that using the more advanced settings. Like I want a high quality print, but with a would like to use the raft and I want to cut off 0.2 mm from the bottom of the object. This would also allows people to learn from the settings behind the pre made quick print types.

What if instead of a few untransparent print types in quickprint we have a custom set of presets? So you start with the basic 3 (quality, normal and fast) but a user can also add to these, based on their tweaks in advanced settings? This might allow a user to load the pre made presets as inspiration. It allows someone like Joris to add his basic print vase mode, it allows others to add presets for tall thin objects etc etc. It allows a advanced user to more quickly switch between general print styles and only where needed tweak. It also allows people to alter these pre made presets with a slightly higher temperature for example. 

What I think is needed is a manageable list of presets that shows up in the File menu under "presets" and in the quick print mode interface. By manageable I mean you need a preferences window that allows you to edit this list (mainly rename and deletion). And something in the File menu like "Save as preset".

The title "presets" could also be something like "favorites", "print styles" etc.

( Might be a bit of a duplicate of issue #416 )

**Comment by peteruithoven** [comment]
And there is quite some overlap with the following issues:
issue #312 
issue #290 
issue #225 
issue #133 
issue #112 

But I hope I've made it slightly more concrete and practical than the above issues.

**Comment by coofercat** [comment]
As a way for the advanced options to "follow" the quickprint options, I'd suggest maybe the advanced mode could have some additional menu options:

"reset all settings to 'fast' quickprint"
"reset all settings to 'normal' quickprint"
"reset all settings to 'high quality' quickprint"

I wouldn't call this a perfect, or end-game solution, but it would be a helpful addition until we can figure out how the UI should hang all this stuff together properly.

**Comment by peteruithoven** [comment]
@coofercat, my idea is that these 3 static profiles are replaced by a list of dynamic profiles, that are prefiled by for example those 3. That makes the whole profile system much more flexible. 
But that lacks a kind of restore to defaults. So a couple of ideas:
- My first instinct was making these 3 fixed and adding clone functionality, so that people who want to change settings create a clone that they can always delete. But this is quite advanced for a beginner who just wants to tweak the temperature. 
- Adding a "restore to default" only to these 3 seems untransparent, a weird exception.  
- Adding a general restore to defaults would destroy all you settings so that probably not desirable. 
- Giving users a list of templates when they create a new profile also seems a bit much. 

So, I don't have a good solution yet, but there must be good ui design patterns for this use case.

**Comment by nallath** [comment]
We're working on an UI overhaul. Most of the issues you mention are handled in those changes.
