### ISSUE TITLE
Mac Version not working

### ISSUE THREAD

**Issue by bbum** [daid/LegacyCura#504]
10.8.4 + Cura 13.06.5.

Lots of stuff is flat out broken;  can load models, but there is no rotation or scaling options.   Save to gcode doesn't work.  Connecting to the ultimaker didn't work, either.

Only message on console:

7/20/13 3:54:44.097 PM Cura[7049]: GLUT Warning: glutInit being called a second time.

**Comment by ghost** [comment]
i have the same problem with 13.06.5

**Comment by nallath** [comment]
There have been some problems with OSX, which should be fixed now.
