### ISSUE TITLE
Printhead crashing in objects when returning home

### ISSUE THREAD

**Issue by mpatoulachik** [daid/LegacyCura#506]
Hi,
If you print several objects with different heights, the printhead will be raised some millimeters above the last object at the end of the print before returning "home" and cooling down.
The problem is that if the last object is not the tallest, the nozzle will not be high enough when the head will be "homed", crashing in the other objects that might be in the path between the last line of print and X0;Y0.
Example. if object 1 is 40mm tall and in the front of the platform and object 2 is 10mm tall and in the back, at the end of the print the nozzle will be at Z= 10+0,5 (clearance) and trying to travel over an object at z=40... The head will then miserably crash into object 1 on its way to the home position...

The solution could be:
- Make sure that Cura places and prints objects from shortest to tallest on the platform. That way the last one to be printed will always give clearance to all other objects.
  -After the last object, add a line of code that retracts to [Zmax of the tallest object] before inserting the regular "end.gcode"

I had the problem with my Ultimaker and Cura 13.06.4

**Comment by ErikDeBruijn** [comment]
Thanks for pointing this out.

I think that only homing X and Y should happen, after homing away from the
platform enough to leave a gap between it and the tallest object. And if Z
homes, rather let it home the printhead away from the platform (so platform
down, in our setup).

Met vriendelijke groeten / With kind regards,

Erik de Bruijn MSc.
Co-founder, Ultimaking LTD

2013/7/21 M.Patoulachik notifications@github.com

> Hi,
> If you print several objects with different heights, the printhead will be
> raised some millimeters above the last object at the end of the print
> before returning "home" and cooling down.
> The problem is that if the last object is not the tallest, the nozzle will
> not be high enough when the head will be "homed", crashing in the other
> objects that might be in the path between the last line of print and X0;Y0.
> Example. if object 1 is 40mm tall and in the front of the platform and
> object 2 is 10mm tall and in the back, at the end of the print the nozzle
> will be at Z= 10+0,5 (clearance) and trying to travel over an object at
> z=40... The head will then miserably crash into object 1 on its way to the
> home position...
> 
> The solution could be:
> - Make sure that Cura places and prints objects from shortest to
>   tallest on the platform. That way the last one to be printed will always
>   give clearance to all other objects. -After the last object, add a line of
>   code that retracts to [Zmax of the tallest object] before inserting the
>   regular "end.gcode"
> 
> I had the problem with my Ultimaker and Cura 13.06.4
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/daid/Cura/issues/506
> .

## 

Ultimaker - easy, open source 3D printing! http://www.ultimaker.com/
Follow us on Twitter http://twitter.com/ultimaker, Google+https://plus.google.com/u/0/b/105283675489513173942/105283675489513173942/posts
, Facebook http://www.facebook.com/Ultimaker

IMAGINE IT >> MAKE IT

**Comment by mpatoulachik** [comment]
Sorry if have been unclear, Z homing is not involved in that.

The problem comes actually from the X and Y homing at the end of a program where you print several separate objects with different height (former "project planner").
The head can be lower than some printed objects when X and Y are homed at the end of the program, thus the potential crash if a taller object is in the way.

At the end of the program (or better: each object), Z should be raised (read: "the platform should be lowered") so that the head can freely go above the tallest object before any x or y move is done.
Without that the regular "end.gcode" will potentially crash the head into things, depending on what you just printed.

Not sure if this can also happen between two objects and not only at the end of the program.

**Comment by ErikDeBruijn** [comment]
Should we introduce a MaximumZ variable that can be used in end.gcode?

Met vriendelijke groeten / With kind regards,

Erik de Bruijn MSc.
Co-founder, Ultimaking LTD

2013/7/21 M.Patoulachik notifications@github.com

> Sorry if have been unclear, Z homing is not involved in that.
> 
> The problem comes actually from the X and Y homing at the end of a program
> where you print several separate objects with different height (former
> "project planner").
> The head can be lower than some printed objects when X and Y are homed at
> the end of the program, thus the potential crash if a taller object is in
> the way.
> 
> At the end of the program (or better: each object), Z should be raised
> (read: "the platform should be lowered") so that the head can freely go
> above the tallest object before any x or y move is done.
> Without that the regular "end.gcode" will potentially crash the head into
> things, depending on what you just printed.
> 
> Not sure if this can also happen between two objects and not only at the
> end of the program.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/daid/Cura/issues/506#issuecomment-21317186
> .

## 

Ultimaker - easy, open source 3D printing! http://www.ultimaker.com/
Follow us on Twitter http://twitter.com/ultimaker, Google+https://plus.google.com/u/0/b/105283675489513173942/105283675489513173942/posts
, Facebook http://www.facebook.com/Ultimaker

IMAGINE IT >> MAKE IT

**Comment by daid** [comment]
Actually, this is a missed bug in the engine, as it does account for other objects when printing, but after the final object it fails to raise the Z to hove above all objects. Should be a simple fix.

**Comment by daid** [comment]
Note this is fixed in the beta versions at http://software.ultimaker.com/Cura_closed_beta/ as well as in the source repositories.
