### ISSUE TITLE
Cura 13.06.4 doesn't support plugin "BedTempAtZ"

### ISSUE THREAD

**Issue by Fantiki** [daid/LegacyCura#507]
When i apply this plugin, there is no any GCode outs :(
All that i have in GCode is:
;Generated with Cura_SteamEngine 13.06.4
;Sliced at: Sun 21 Jul 2013 20:30:38
;Basic settings: Layer height: 0.15 Walls: 0.6 Fill: 100
;Print time: #P_TIME#
;Filament used: #F_AMNT#m #F_WGHT#g
;Filament cost: #F_COST#
G21        ;metric values
G90        ;absolute positioning
M107       ;start with the fan off
G28 X0 Y0  ;move X/Y to min endstops
G28 Z0     ;move Z to min endstops

and that's all :)

**Comment by daid** [comment]
The bug is a combination of my new engine and a bug in the plugin. The plugin expects a ";TYPE" comment before the first G1 code. But my new engine did not emit that line. Causing issue.
