### ISSUE TITLE
in serialList() don't use /dev/tty.usb*

### ISSUE THREAD

**Issue by mloepfe** [daid/LegacyCura#508]
As much as I know and as the following quote states, we should not use /dev/tty.usb\* but only /dev/cu.usb*. They are both the same device but with different behaviour.

Regards Matthias

---

The idea is to supplement software in sharing a line between incoming and outgoing calls. The callin device (typically /dev/tty_) is used for incoming traffic. Any process trying to open it blocks within the open() call as long as DCD is not asserted by hardware (i.e. as long as the modem doesn't have a carrier). During this, the callout device (typically /dev/cu_ -- cu stands for "calling unit") can be freely used. Opening /dev/cu\* doesn't require DCD to be asserted and succeeds immediately. Once succeeded, the blocked open() on the callin device will be suspended, and cannot even complete when DCD is raised, until the cu device is closed again. That way, you can have a getty listening on /dev/tty_, and can still use /dev/cu_ without restrictions.

**Comment by daid** [comment]
I've removed the tty dev from the auto-detection list, but I've kept it in place for the manual selection list. In case there is some system that does not create the cu\* devices.

**Comment by mloepfe** [comment]
thanks, good decision!
