### ISSUE TITLE
crashing machineComm.monitor thread with bed leveling wizard

### ISSUE THREAD

**Issue by mloepfe** [daid/LegacyCura#509]
In the bed leveling wizard, when you clicked 'Connect to printer' and then click 'Finish' or 'Cancel' in a bad moment (mainly under the debugger:-) the monitor thread crashes because the callback object does not exist anymore..

This is not a real problem but just not proper.. The two following patches fix the problem.

regards Matthias

diff --git a/Cura/gui/configWizard.py b/Cura/gui/configWizard.py
index ddb07ba..f69e89d 100644
--- a/Cura/gui/configWizard.py
+++ b/Cura/gui/configWizard.py
@@ -794,6 +794,12 @@ class bedLevelWizardMain(InfoPage):
                self.Bind(wx.EVT_BUTTON, self.OnConnect, self.connectButton)
                self.Bind(wx.EVT_BUTTON, self.OnResume, self.resumeButton)
-       def **del**(self):
-               if self.comm is not None:
-                       self.comm.resetCallback()
-                       self.comm.close()
-                       self.comm = None
  +

diff --git a/Cura/util/machineCom.py b/Cura/util/machineCom.py
index 4bae4dc..a6be505 100644
--- a/Cura/util/machineCom.py
+++ b/Cura/util/machineCom.py
@@ -189,6 +189,9 @@ class MachineCom(object):
                self.thread = threading.Thread(target=self._monitor)
                self.thread.daemon = True
                self.thread.start()
+
-       def resetCallback(self):
- ```
            self._callback = MachineComPrintCallback()
  
  def _changeState(self, newState):
          if self._state == newState:
  ```
  
  @@ -468,12 +471,13 @@ class MachineCom(object):
  
  ```
  def close(self, isError = False):
          if self._serial != None:
  ```
-                       _serial = self._serial
-                       self._serial = None
                      self._serial.close()
                      if isError:
                              self._changeState(self.STATE_CLOSED_WITH_ERROR)
                      else:
                              self._changeState(self.STATE_CLOSED)
- ```
            self._serial = None
  
  def __del__(self):
          self.close()
  ```

**Comment by daid** [comment]
Github ate your patch file :(

**Comment by mloepfe** [comment]
Next try...

```
diff --git a/Cura/gui/configWizard.py b/Cura/gui/configWizard.py
index ddb07ba..9ee0ae2 100644
--- a/Cura/gui/configWizard.py
+++ b/Cura/gui/configWizard.py
@@ -794,6 +794,12 @@ class bedLevelWizardMain(InfoPage):
                self.Bind(wx.EVT_BUTTON, self.OnConnect, self.connectButton)
                self.Bind(wx.EVT_BUTTON, self.OnResume, self.resumeButton)

+       def __del__(self):
+               if self.comm is not None:
+                       self.comm.resetCallback()
+                       self.comm.close()
+                       self.comm = None
+
        def OnConnect(self, e = None):
                if self.comm is not None:
                        self.comm.close()
```

```
diff --git a/Cura/util/machineCom.py b/Cura/util/machineCom.py
index 4bae4dc..7190dcf 100644
--- a/Cura/util/machineCom.py
+++ b/Cura/util/machineCom.py
@@ -189,6 +189,9 @@ class MachineCom(object):
                self.thread = threading.Thread(target=self._monitor)
                self.thread.daemon = True
                self.thread.start()
+
+       def resetCallback(self):
+               self._callback = MachineComPrintCallback()

        def _changeState(self, newState):
                if self._state == newState:
@@ -468,12 +483,13 @@ class MachineCom(object):

        def close(self, isError = False):
                if self._serial != None:
+                       _serial = self._serial
+                       self._serial = None
                        self._serial.close()
                        if isError:
                                self._changeState(self.STATE_CLOSED_WITH_ERROR)
                        else:
                                self._changeState(self.STATE_CLOSED)
-               self._serial = None

        def __del__(self):
                self.close()
```

**Comment by mloepfe** [comment]
... oh sorry.. I made a copy paste misstake 

in the diff before the line

```
                        self._serial.close()
```

should of course read

```
                        _serial.close()
```
