### ISSUE TITLE
you have a couple bugs - easy to fix

### ISSUE THREAD

**Issue by thethereza** [daid/LegacyCura#51]
So I found two problems with your configurator linked to the same problem.

After install, you have no preferences file, and the value for steps_per_e is thus 0

the configurator uses this value for a number of functions which then fail..

this value is to determine the new value of steps per E by figuring out  a ratio where the 0 is multiplied, thus the output is always zero.  it's also used in determining how much to extrude in the first place by setting the steps per mm to the same zero value, thus not extruding.

i suppose the fix is to add a default profile.ini file with a sane value populated..

reza

**Comment by daid** [comment]
I suddenly realized the same myself. This explains all the "first run wizard calibration doesn't work" reports I've been getting (at other locations).

The fix is setting a default steps_per_e when you select the Ultimaker as machine in the first step ;-)
