### ISSUE TITLE
Cura 13.06.5 - Cannot connect to printer.

### ISSUE THREAD

**Issue by quikshot** [daid/LegacyCura#512]
In Linux, Ubuntu 12.04 64bits,

When going to print and trying to connect it fails.

Error from printer window:
Changing monitoring state from 'Offline' to 'Detecting serial port'
Serial port list: ['/dev/ttyACM0']
Connecting to: /dev/ttyACM0
Error while connecting to /dev/ttyACM0: 'Timeout'
Failed to open serial port (AUTO)
Changing monitoring state from 'Detecting serial port' to 'Error: Failed to autodetect...'

My printer is in /dev/ttyACM0 using an old Marlin custom version (made with the BuildMeMarlin from old daid builder) to have 230400 bps.

I can connect flawlessly from Pronterface.

Even if I set the bps in preferences, it does not connect.
I am in the dialout group, too.

Command line traces:
$ cura 
Traceback (most recent call last):
  File "/usr/share/cura/Cura/gui/util/openglGui.py", line 183, in _OnGuiMouseDown
    if self._container.OnMouseDown(e.GetX(), e.GetY(), e.GetButton()):
  File "/usr/share/cura/Cura/gui/util/openglGui.py", line 100, in OnMouseDown
    if ctrl.OnMouseDown(x, y, button):
  File "/usr/share/cura/Cura/gui/util/openglGui.py", line 530, in OnMouseDown
    self._callback(button)
  File "/usr/share/cura/Cura/gui/sceneView.py", line 171, in OnPrintButton
    self.showPrintWindow()
  File "/usr/share/cura/Cura/gui/sceneView.py", line 200, in showPrintWindow
    self._slicer.submitSliceInfoOnline()
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 317, in submitSliceInfoOnline
    'profile': profile.getGlobalProfileString(),
AttributeError: 'module' object has no attribute 'getGlobalProfileString'

**Comment by daid** [comment]
The failed to detect serial port is an auto-detection of port failure. This tries to detect an ATMega2560 bootloader, so this will not work on all electronics. Configuring the port in the preferences might help. Also make sure no other program is trying to use the serial port (this gives horrible results on linux)

**Comment by quikshot** [comment]
I am using the same workflow as in previous versions. I even forced the serial port and speed with not better results.
Any other program prone to open the port is working while using Cura.
Also, my electronics are an ATMega2560 and I haven't changed the bootloader (electronics v1.5.4).
