### ISSUE TITLE
Unchecking "solid infill on bottom" also suppresses bridging

### ISSUE THREAD

**Issue by mpatoulachik** [daid/LegacyCura#519]
Not using "solid infill on bottom" not only removes the solid infill against the printer bed but also removes it for all "ceilings" (where bridging happens).

I guess the engine does not see a difference between the bottom of the part or any ceiling, but i think this option should only affect the bottom of the part.

The print quality of these "ceilings" becomes quite bad because the machine tries to print the infill square pattern in mid-air, making a lot of spaghetti.

If this really is how it should behave, i suggest you rename the option to something more explicit.

**Comment by nallath** [comment]
This seems to be fixed in the latest version.
