### ISSUE TITLE
Missing retractions

### ISSUE THREAD

**Issue by nophead** [daid/LegacyCura#520]
With a simple object consisting of a base connecting two cylindrical towers it seems to not do retractions when travelling the length of the base but does on the higher layers when it is travelling between towers.

**Comment by nophead** [comment]
There is also a restart missing at the start and a retract missing at the end. Seems Cura views the default state of the extruder as primed, whereas Skeinforge viewed it as retracted, which is how I operate my machines as I don't want it oozing when not extruding.

**Comment by daid** [comment]
Cura always does combing, so if you are expecting retractions when the nozzle stays inside the model then yes, that's not happening.

Cura also assumes that the startcode left the head in a primed state and then the end code does the final retract.

**Comment by nophead** [comment]
Combing doesn't stop ooze so the extruder is short of plastic when it gets to its destination and therefore leaves a gap at the start of the outline it has just travelled to. Retracting on all moves works much better. Why would you not do it on all but the very short moves? It even works fine doing it on short moves as well but wastes a little time.

Yes not retracting at the end can be fixed by end.gcode and you may want to retract more than normal, by why not do the normal retract anyway?

Not un-retracting at the start causes the start of the skirt to not stick and then it comes loose and gets stuck to the model. I cant' fix that in start.gcode because the move to the skirt is after start.gcode.

**Comment by daid** [comment]
How well always retracting works depends on your hotend, bowden tube (or not), printing temperature and filament. For an Ultimaker it's much better to swing the head around at high speed then to retract, as the ultimaker needs quite a bit of retraction and that takes a while, causing blobs at the retraction spot.

**Comment by nophead** [comment]
It needs to an option then unless this is only for Ultimaker machines.

**Comment by daid** [comment]
Yes, it will be, I'm also added the minimal distance for retraction setting. (It's often asked for)

**Comment by nophead** [comment]
So will that also invoke an un-retract at the start? I prime and then retract in my start g-code, otherwise it will leave a trail to the skirt and the skirt will not stick because the extruder is not fully primed when it gets there.

**Comment by daid** [comment]
Added an option to disable the combing and thus enable always retraction:
https://github.com/daid/Cura/commit/b43cc3c7fd22b882022094131484c2759e38ee80

Also added an option to have a minimal amount of extrusion before allowing retraction (to avoid flatten the filament all the way till grinding)

I'm surprised your nozzle leaks so much between the home point and the start of the skirt. But I think you still could fix this in the start code by adding:

```
G92 E0
G1 E-4.5
```

This would move the filament back, and as soon as it starts printing it will push it forward. It might miss a piece of the skirt because of it (as the first point of the skirt will not have G1 E0) but it should solve your retraction at start issue for now. I'll also add an update that it inserts a "G1 E0 F{retract_speed}" before the first skirt (will be super easy)

**Comment by nophead** [comment]
I don't see why combing and retraction are mutually exclusive. I have both
enabled with Skienforge.

The nozzle doesn't leak at all on its way to the skirt with an  E-1 retract
after priming. When primed without a retract though it is up to extrusion
pressure so will be extruding at normal flow rate initially, so is bound to
lose a significant amount over what can be close to a 100mm move. G1 E0 at
the start of the skirt should fix it.

BTW, retract speed and restart speed should be different. Retract should be
as fast as the extruder can manage to get minimum extra plastic at the end
of a run. Restart speed should be just right so that at the time it has
finished and thus reached extrusion pressure the amount it has extruded
during that time is just enough to exit the nozzle and land on the layer
below. Too fast and it will not attach before it starts to move off. Too
slow and it will form a blob and then be under pressure when it starts to
move off.

**Comment by 3yourmind-zz** [comment]
The new version of Cura, 13.11 does not retract properly. I installed the old, 13.6 version and works perfectly! It retracts in all elements, when moving without printing. You can find the old version here: http://software.ultimaker.com/?show=all

**Comment by wdl1908** [comment]
A retract at the end should be added. I always have a blob on the model just before it moves the head up to end the print. I'm using 13.11

**Comment by daid** [comment]
Yes, fix for the "missing retraction at the end" will be released today.

**Comment by wdl1908** [comment]
Nice I installed 13.11.2 and it works perfectly. but now there is no retract between skirt and object.
