### ISSUE TITLE
Typing in the start and end gcode fields causes frequent crashes

### ISSUE THREAD

**Issue by nophead** [daid/LegacyCura#521]
It seems like every keystroke in the text field causes the engine to restart slicing. Often  is causes a Widows crash report but the main GUI carries on running. I assume that just the slicing or rendering thread crashes and then gets restarted. So it isn't a major problem, just a bit annoying.

Perhaps those fields should have an apply button. Or do they need to cause a re-slice at all since they only need to be used when actually printing or saving the gcode?

**Comment by daid** [comment]
The CuraEngine gets killed and restarted when you change a setting (including typing in the start/end-gcode) normally this shouldn't produce crash reports.

The engine might crash on some value you are entering, but that would be odd, the start/end code is just UTF-8 encoded strings that get put in front/behind.

**Comment by nophead** [comment]
Well it does frequently crash, even when typing a comment. One time I got
an error dialogue which looked to be from some rendering code. Most times
it just brings up the Windows crash dialogue that offers to open a debugger.

Maybe it crashes when the field is actually being modified by the GUI
thread and the engine reads it in another thread while the memory is being
changed so you get an un-terminated string or something. Have you got any
critical sections around string variables used by more than one thread?

**Comment by daid** [comment]
The engine runs in a seperate process, not a thread, and they do not interact with each other other then a stdout pipe. The engine is single threaded (just to avoid the whole race conditions problem). Python is thread safe by design (due to the PIL)
