### ISSUE TITLE
Cura rescales model silently (13.06.5)

### ISSUE THREAD

**Issue by j0uni** [daid/LegacyCura#524]
I've now failed many prints because Cura silently rescales my models. This is probably because they don't fit onto building platform.

However I strongly suggest not doing this because user cannot be aware of this happening. If Cura wants to rescale the model it should atleast inform the user or ask permission. Better not doing this at all, leave it to the user.

Really really frustrating feature. I don't want another step to remember when preparing a print.

See this video:http://www.youtube.com/watch?v=zd9JSZlZ4s4&feature=youtu.be

**Comment by j0uni** [comment]
Could the problem be in file https://github.com/daid/Cura/blob/SteamEngine/Cura/util/mesh.py at "def processMatrix(self):" ?

**Comment by daid** [comment]
If the print is bigger then 1.5x the build volume Cura sizes down the print to 1.5x the build volume. As the print is still too large you have to manual scale it anyhow. Some models are 100x to big and need to be scaled down to be viewed and selected. I'm not sure how this caused failed prints for you as the print is too big and will refuse to print till you scale it yourself.

Cura is not in the "annoy users with dialog boxes" business. I will add a notification so you know that this happened.

**Comment by j0uni** [comment]
The part itself isn't too large, but the model probably is. However i choose split and delete the parts I dont want to print. I like to export the whole drawing to Cura and then delete parts I dont want to print. That way all parts for certain project stay together. Maybe odd way to do things, but I'm sure someone will face the same.

Notification is enough to fix this. Thanks!

## 

"I sense a runner in the garden 
Although my judgements known to fail
Once built a steamboat in a meadow
Cos I'd forgotten how to sail" TTMOE

daid notifications@github.com kirjoitti 7.8.2013 kello 13.35:
