### ISSUE TITLE
Cura 13.06.5 crashing in ubuntu 13.04 64bits

### ISSUE THREAD

**Issue by sballano** [daid/LegacyCura#525]
I finished my ultimaker yesterday and used successfully the Cura software for a few prints, but inexplicably at some point it started crashing all the time. Just by opening it, it crashes in a few seconds, an "ubuntu crash report window" appears and even I still can use Cura, it does not slice the models any more.

I even had the Cura software long before my Ultimaker, and played with it without problems, but just the day I finish my printer it stops working!!

Anyway, this is the error I get in the console:

```
(python:5220): LIBDBUSMENU-GLIB-WARNING **: Translation has an invalid value 'I-->D' for default text direction.  Defaulting to left-to-right.
Traceback (most recent call last):
  File "/usr/share/cura/Cura/gui/sceneView.py", line 420, in _onRunSlicer
    self._slicer.runSlicer(self._scene)
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 116, in runSlicer
    for k, v in self._engineSettings(extruderCount).iteritems():
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 259, in _engineSettings
    'startCode': profile.getAlterationFileContents('start.gcode', extruderCount),
  File "/usr/share/cura/Cura/util/profile.py", line 793, in getAlterationFileContents
    return unicode(prefix + re.sub("(.)\{([^\}]*)\}", replaceTagMatch, alterationContents).rstrip() + '\n' + postfix).strip().encode('utf-8') + '\n'
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/share/cura/Cura/util/profile.py", line 685, in replaceTagMatch
    return pre + time.strftime('%a').encode('utf-8', 'replace')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
```

I tried to purge the Cura package and reinstall it, also removed the ~/.cura folder to clean all configurations. I even installed a previous version, any of that worked!

If more info is needed to solve this crash, I will be happy to provide everything I can.

Thanks!

**Comment by sballano** [comment]
So, this was fast :smile: 

I think I may have found what caused the problem. My local language is Spanish, yesterday was Tuesday -> "Martes" (abbreviated as "Mar") and today is Wednesday -> "Miércoles" (abbreviated as "Mié"). It seems that this "é" is giving python some troubles, I don't know much of python so I just replaced the 685 line in "/usr/share/cura/Cura/util/profile.py" with this:

```
return pre + '---'
```

Another workaround is not to print anything on Wednesday :laughing: but I hope you can solve this for future versions :-)

**Comment by daid** [comment]
Yes, pushed a fix today, will make a release soon. This bug has been a real pain it keeps popping up in one form or another. I removed the localization to work around it. Quick fix really, but the feature is not high priority.
