### ISSUE TITLE
Please help~~~I can't connect my Freaduino MEGA 2560 with Cura,as my Arduino compatible board used a ft232 chip

### ISSUE THREAD

**Issue by TokureSystem** [daid/LegacyCura#526]
I can't connect my arduino mega 2560 with Cura,because the arduino is ft232 chip,not the atmel 16u2...
can you help me?
![mega2560](https://f.cloud.github.com/assets/5093917/930055/6df8128a-ffff-11e2-9b8c-cb37ce36345e.jpg)

**Comment by daid** [comment]
That's not an Arduino. It's a cheap knockoff. Will most likely work if you configure the serial-port and baudrate in the preferences.

**Comment by TokureSystem** [comment]
I tried to configure the serial port and baudrate,but Cura still can't detect my board....Can you tell me which files I need to modify?So that I can use this board with the switching power supply.

**Comment by daid** [comment]
Did you put a firmware on the board?

**Comment by Charles-Beraldini-Alvarenga-py3cba** [comment]
Hi sjw107273131. 

I have a Freaduino Mega 2560 working very well now. Follow the steps below;
- Install the Arduino.
- Go to the Drivers folder and unpack the Older_Arduino_drivers in the driver folder.
- Connect the Freaduino and follow the driver installation by windows normally.
- After installation the driver, go to the device manager and unistall the USB Serial Converter and its driver too.
- Unplug the Freaduino and plug again in your PC USB connector.
- The installation will begin again. Stop the automatic installation by windows and do a manual installation. Update the driver and choose the folder driver in the Arduino folder to install the correct driver.
- Proceed the installation normally.
- The correct driver for the USB SERIAL CONVERTER is (FT232R USB UART) at end of installation.
- Configure the correct board and serial port at Arduino program. 
- Test the Freaduino by uploading the blink example.
- Enjoy Your Freaduino.

I just made these step above and my Freaduino is working good now.

**Comment by daid** [comment]
Assuming for now the problem is related to the configuration of the computer (drivers?) and not Cura. Closed until any indication that this is not the case.
