### ISSUE TITLE
Plugins Tab doesn't show on Mac OSX with Cura 13.06.5

### ISSUE THREAD

**Issue by GuyJanssen** [daid/LegacyCura#528]
The plugins Tab does show on Ubuntu but not on my iMac with OSX 10.8.4.

Any idea how to solve this??

Thanks for any tips in advance.
![nocuraplugintab](https://f.cloud.github.com/assets/5193536/935362/e3ee00f4-0080-11e3-9cfc-3f61fce2b83e.jpg)

**Comment by peteruithoven** [comment]
Same here. OS X 10.6.8 or OS X 10.8 & Cura 13.06.5. 
In Ubuntu it does show up.

**Comment by GuyJanssen** [comment]
Is someone from Ultimaker reading this ????

**Comment by ErikDeBruijn** [comment]
We are. But we're quite busy with lots of issues and improvements, this is
just one of them...

With kind regards,

Erik de Bruijn
Co-founder, Ultimaker BV
Op 22 aug. 2013 18:53 schreef "GuyJanssen" notifications@github.com het
volgende:

> Is someone from Ultimaker reading this ????
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/daid/Cura/issues/528#issuecomment-23105340
> .

## 

Ultimaker - easy, open source 3D printing! http://www.ultimaker.com/
Follow us on Twitter http://twitter.com/ultimaker, Google+https://plus.google.com/u/0/b/105283675489513173942/105283675489513173942/posts
, Facebook http://www.facebook.com/Ultimaker

IMAGINE IT >> MAKE IT

**Comment by GuyJanssen** [comment]
Thanks Eric, I am looking forward to the update. Any idea when it will arrive?

**Comment by daid** [comment]
Note, the plugin tab does not show because Cura for the Mac is not detecting the plugins, which is why the tab does not show up. A workaround is adding a directory "/.cura/plugins/" in your home directory and add the plugins there. Then they do show up.

**Comment by GuyJanssen** [comment]
thnx daid! When I try to download the plugin I get an upload page instead of the plugin-file!
I try to do the download from this url: http://wiki.ultimaker.com/CuraPlugin:_Pauseatz

**Comment by GuyJanssen** [comment]
My problem is nw solved; I copied it from Ubuntu to the Mac but the download link still comes up with the upload page.

**Comment by wkeenan** [comment]
Hi,

The command below, test on a Mac, will download all the plugins from the Ultimaker site into the ~/.cura/plugins folder; adjust as you see fit (e.g. download to tmp and copy only the ones you require to the plugins folder) or pick and choose from the list below.

curl -s http://wiki.ultimaker.com/images/| perl -ne '`curl -o ~/.cura/plugins/$1 http://wiki.ultimaker.com/images/$1` if /href="(.*.py)"/' 

The above will only work whilst Ultimaker allows the directory listing of /images.

curl -o ~/.cura/plugins/BedTempAtZ.py http://wiki.ultimaker.com/images/BedTempAtZ.py
curl -o ~/.cura/plugins/BorderControl.py http://wiki.ultimaker.com/images/BorderControl.py
curl -o ~/.cura/plugins/ChangeBedTemp.py http://wiki.ultimaker.com/images/ChangeBedTemp.py
curl -o ~/.cura/plugins/ChangeFilamentAtZ.py http://wiki.ultimaker.com/images/ChangeFilamentAtZ.py
curl -o ~/.cura/plugins/FilamentAtZ.py http://wiki.ultimaker.com/images/FilamentAtZ.py
curl -o ~/.cura/plugins/FlowThermostat.py http://wiki.ultimaker.com/images/FlowThermostat.py
curl -o ~/.cura/plugins/Hacky_dual.py http://wiki.ultimaker.com/images/Hacky_dual.py
curl -o ~/.cura/plugins/Printonobject.py http://wiki.ultimaker.com/images/Printonobject.py
curl -o ~/.cura/plugins/Testje.py http://wiki.ultimaker.com/images/Testje.py
curl -o ~/.cura/plugins/Wood.py http://wiki.ultimaker.com/images/Wood.py
curl -o ~/.cura/plugins/XYZshift.py http://wiki.ultimaker.com/images/XYZshift.py
curl -o ~/.cura/plugins/Zlift.py http://wiki.ultimaker.com/images/Zlift.py
