### ISSUE TITLE
Plugins seem not to work properly in 13.06.4

### ISSUE THREAD

**Issue by jobakie** [daid/LegacyCura#529]
Dear all,

first of all thanks to David for the great software CURA! It already did a very good job with my Ultimaker.

However now I have to print some models with different colors at different heights. But the plugins don't seem to work properly in the 13.06.4 version.

Here are some reproducable problems that I ran into:
1. "Pause at height" only works when I slice more or less directly after starting CURA. It does NOT work any more from the second generation of a gcode.
2. Other plugins like "Change Filament At Z" don't work.

Does anybody have an idea how to fix that issue?

Thanks,

Joachim

**Comment by daid** [comment]
Most plugins seem to fail because of a minor change in the GCode generator. You can try adding a `;TYPE:CUSTOM` in front of the start code to see if that helps with the plugins.
