### ISSUE TITLE
cura always printing the same object

### ISSUE THREAD

**Issue by lcbmagar** [daid/LegacyCura#530]
i first started printing with cura with the robot object. since then i tried print other things eg, portabee parts but the portabee printer is always printing the same robot object.
please help....

**Comment by daid** [comment]
Did you use the latest version? And on which OS?

**Comment by hg42** [comment]
may be you have left the printing window open while loading a new STL.
I think, you have to close it and start a new print from Cura.

@daid Instead, I would like the printing window to load the current gcode from Cura whenever it changes or at least whenever hitting the print button. Or it should close and reopen, when hitting "print" in Cura.

**Comment by hg42** [comment]
Ok, I see the printing window already reloads the gcode when hitting "print" in Cura, sorry I didn't notice it before.
Would be nice if the (source) file name would be visible in the printing window. Otherwise only some numbers change on the "Statistics" part.
