### ISSUE TITLE
youmagine-text.png is missing

### ISSUE THREAD

**Issue by hg42** [daid/LegacyCura#534]
When I start cura after installing from source I get an assertion and cura stops:

AssertionError: /usr/share/cura/Cura/resources/images/youmagine-text.png is not a file.

I don't find an image with that name in the sources.

**Comment by ad1217** [comment]
I also had this problem. As a temporary workaround, you can do:

```
sudo touch /usr/share/cura/Cura/resources/images/youmagine-text.png
```

This will allow it to launch, but it will give you another error because that is not really a png.

**Comment by hg42** [comment]
:-) yes, I copied the ultimaker robot as a fake, but I wanted to report it (I couldn't create a pull request because I don't have or know that image)

**Comment by daid** [comment]
The image is a placeholder. The whole YouMagine button is not final yet, and I dislike the current GFX that I have and the current place where it's in.

**Comment by hg42** [comment]
The image isn't really important to me, but without it, cura gets an assertion and stops, from a (linux) user's point of view it simply doesn't start (no messages, the assertion is only visible when you start it from a terminal). May be it's dependent on the python version or something. So some placeholder would be fine (but doesn't exist in the repo).

**Comment by daid** [comment]
Well, the repos is active development, so you can expect stuff to break.

**Comment by hg42** [comment]
seems to be solved...
