### ISSUE TITLE
Infill not aligned when shape changes with height

### ISSUE THREAD

**Issue by nophead** [daid/LegacyCura#535]
I like the new infill pattern as it creates stronger bonds between layers but that relies on it being in the same place on each layer. This simple example of slicing an L shape shows it gets miss-aligned creating a weak layer.

![l_shape](https://f.cloud.github.com/assets/566149/974885/ba8c143a-0666-11e3-8211-b26020acdb03.jpg)

![missalignedinfill](https://f.cloud.github.com/assets/566149/974883/af4bf860-0666-11e3-904a-1f21c5daf3e2.jpg)

I think the positions of the lines in the infill grid need to be fixed relative to the print bed, not aligned to features in each slice. I.e. have one global grid and clip it to the bounds of each island in the layer to find the infill pattern for that island.

**Comment by daid** [comment]
Yes, this will be changed when I find the time to do so.

**Comment by daid** [comment]
Is fixed in the code and betas at http://software.ultimaker.com/Cura_closed_beta/
