### ISSUE TITLE
Error: 'No Line Number'

### ISSUE THREAD

**Issue by hastern** [daid/LegacyCura#536]
Hope this isn't a duplicate, but I couldn't find a matching issue.

The Ultimaker I used repeatedly stopped after some time with the following Error:

Recv: Error:No Line Number N84202G1cksum, Last Line: 84201
Changing monitoring state from 'Printing' to 'Error: No Line Number N8420...'

It seems that Cura ignores packet resend instructions and just continues sending consequent packets.

Cura Version: 13.06.4
Windows 7

**Comment by daid** [comment]
I've updated the USB printing code a few releases ago, and as far as I know there is no problem with the resends anymore.
