### ISSUE TITLE
Copy and rotate buttons are hidden at default window size on Mac

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#54]
Another Mac display bug. With Cura at the default size (the size the window opens at) several of the controls under the preview window are hidden, including several of the copy buttons and the rotate control. Screenshot: http://i1162.photobucket.com/albums/q531/lawrencejohnston/Github/ButtonsHiddenBug.png

**Comment by fuegas** [comment]
We're looking at remodeling the gui with icons for various parts, this should make the toolbars smaller and show the hidden parts. As example, my current view looks like this: http://vuurtje.kassala.de/junk/cura_icons.png
Do note: this is experimental, none of these icons are decided to be used in releases. This is just a test to work with icons.

**Comment by daid** [comment]
Indeed, the icon buttons will solve a lot here. Space is a bit limited, as I'm trying to keep the interface usable on a netbook as well. MacOS also has the largest UI elements, it's about 20-30% larger the Windows in classic look (which has the smallest UI elements).

PyroMani is helping me develop/solve issues with MacOS btw.

**Comment by fuegas** [comment]
Sooo, here's a new mockup: http://vuurtje.kassala.de/junk/icons.png
How's this for icons for mirror and swap?

You can use 20d975004c4beac730d4512642fe8636b625e2ee for a demo.

**Comment by RedwoodForest** [comment]
Those are pretty reasonable. I'm not sure I'd be able to tell whether I wanted to swap XZ or YZ just from the icon, so it's good to have the letters on there too.

I think it's important to have tooltips describing each action, too (if you can figure out how to make them work on Mac:)). 

Glad to have somebody with a Mac helping out with the development.

**Comment by fuegas** [comment]
Tooltips are present, but not showing on the screenshot :)
When you hover over them you get tooltips: "Mirror X", "Mirror Y", "Mirror Z", "Swap XZ" and "Swap YZ"
My concern is whether the color/gray version stand out enough.
I'm glad to be of help :)

**Comment by daid** [comment]
I think the latest development version solves this now. When you have time, could you check it Lawrence?

**Comment by RedwoodForest** [comment]
With the latest build about half the rotation text box / up down control is hidden. It's much better than it was, though.

http://i1162.photobucket.com/albums/q531/lawrencejohnston/Github/HiddenControlBug2.png

**Comment by daid** [comment]
We've been looking to get those insane margins gone on MacOS. But we haven't be able to get MacOS to comply. The problem is caused by me moving the "scale up to printer size" button to the lower bar.

Under linux and windows it fits fine: http://daid2.mine.nu/~daid/Screenshot-Cura%20-%204d10199e7444e71bcec47c8ac5eba1d6b3279a82.png

**Comment by daid** [comment]
With the removal of multiply this should fit on MacOS now I think.
(I removed Multiply, because it caused lots of problems with dual extrusion, and the project planner is a better solution)

**Comment by RedwoodForest** [comment]
Yup, this is fixed now.
