### ISSUE TITLE
speed / feedrate, steps_per_e value for extra extruders

### ISSUE THREAD

**Issue by kymwatts** [daid/LegacyCura#542]
Hi there,

I couldnt find this as another issue/ feature.
could you add a second feedrate/speed per extra extuder?

for printing with pva, it would be nice to print at 15/mm/sec and with the pla @ 50 mm/sec.

also i have noticed that the pva doesnt run through the feeder at the same speed as pla , im thinking this is because the pva crushes easier than the pla.

please let me know if i can help further.

cheers
Kym

**Comment by kymwatts** [comment]
if you cant add this could you add a a tool change gcode chunk per extruder? then any seetings could be modified per head

**Comment by daid** [comment]
I have the plan to make just about all settings except layer-height configurable per extruder. But I need to think about how to put this in the UI without making a dragon.

**Comment by nallath** [comment]
Will be adressed in the GUI overhaul.
