### ISSUE TITLE
Fan speed algorithm is unrealistic

### ISSUE THREAD

**Issue by ambrop72** [daid/LegacyCura#543]
The current fan speed algorithm appears to be: if base layer time is above the min layer time, use the min fan speed; otherwise increase the fan speed linearly, with max fan speed used when the print is slowed down more than 200%.

I don't think this optimal. Consider that increasing the fan speed allows you to print at a higher speed; there may not be any need to slow down if the fan can be turned up enough. To this end, I propose that Cura do the same thing as Slic3r. That is, the user defines a "fan layer time" which corresponds to the fan being at min speed, and the existing min layer time corresponds to the fan being at max speed (fan layer time >= min layer time). Outside this layer time range the fan would run at min or max speed (so if a layer was slowed down it would always run at max speed).

**Comment by daid** [comment]
Interesting idea, sounds like a better implementation then what I have now. I'll put it on the feature request list.

**Comment by BagelOrb** [comment]
So what you are saying is:
- If layer takes [min layer time] run fan at max speed
- Scale fan speed linearly such that if a layer takes [fan layer time] it will run at min speed
- Extrapolate linear function for layers taking less and layers taking more than [fan layer time]

Is this correct?

**Comment by ambrop72** [comment]
@BagelOrb Not sure about that extrapolation part. I would do it like this (this is a bit more general than what I described at first).
- Turn on fan at minimum speed **MinFanSpeed** when the layer time is below **FanOnLayerTIme**.
- Start increasing the fan speed linearly when layer time is also below **FanInterpolationLayerTime**.
- Increase the fan speed up to **MaxFanSpeed** which is achieved when the layer time is **MinLayerTime**.

Note that when the layer time estimate is below MinLayerTime, the speed is (already) turned down so that effectively the layer time remains at MinLayerTime. The main point I'm raising in this issue is that it is not necessary to keep increasing the fan speed while also slowing down the layer. The point where the slowing-down starts should correspond to the point where the fan has reached the maximum speed, so we slow down _because_ we can't run the fan any faster.
