### ISSUE TITLE
Minimum layer time, and first layer

### ISSUE THREAD

**Issue by illuminarti** [daid/LegacyCura#545]
As discussed here:

https://groups.google.com/d/msg/ultimaker/IoyXwM7oO4k/W109sffhh-cJ

It seems that Cura 13.06.5 is deciding whether to apply a slow-down to the first layer based on what would be required at the normal print speed, not at the first layer speed. Furthermore, that speed then uses, if one is needed, is the adjusted normal speed, not the adjusted first-layer speed.  Hence the first layer can end up unexpectedly fast.

Also, in the course of testing this, it looked like the actual first layer print speed was being set 1mm/s slower than the requested first layer speed?

**Comment by daid** [comment]
The 1mm/s slower might be a rounding error. The other error, I think it was found and fixed a while ago. Where these tests done with the new support beta?
