### ISSUE TITLE
Super useful feature: Drag and drop GCODE files into Cura window to "Load profile from GCODE"

### ISSUE THREAD

**Issue by nhfoley** [daid/LegacyCura#549]
Dragging and dropping .STLs to load them into Cura is awesome.

It would be equally awesome (and easy to implement?) if dragging and dropping a .GCODE file had the same result as "Load profile form GCODE'". This would make quick switches between printer-specific profiles, material-specific profiles, and part-specific profiles much easier.

Also, while we're on the subject, it would be sweet if at some point in the future, you could save user-developed print profiles to the radio buttons of the "Quickprint" interface. That way I could save specific profiles based on machines and materials and quickly swap between them. 

Usability FTW!

**Comment by daid** [comment]
Quickprint profiles is on the wish list.

As for loading GCode profiles, the issue here is that Cura can also load GCode files to preview/print. So dropping a GCode file on Cura could mean 2 different things...

**Comment by hg42** [comment]
Reading this, I think, dropping a GCODE file on Cura should mean loading the GCODE (for print etc.) because this is more natural. Dropping a profile (ini) would be the natural way to load a profile, right?
Dropping a GCODE would also load the included profile, so it's more or less what nhfoley wants (just load an stl after that, replacing the GCODE object).

**Comment by nhfoley** [comment]
Sure, I guess that also works. But right now, dropping in a GCODE file does nothing, which is a missed opportunity.

**Comment by daid** [comment]
Thanks for the patch, guess this can be closed for now.

**Comment by hg42** [comment]
Note, the patch still doesn't load the profile from gcode (I think, I still didn't check), so may be it should stay open.

I also think about dropping ini files...

**Comment by hg42** [comment]
While working on the drop handler for profiles (*.ini), I wondered if loadGCodeFile should always load the profile from the gcode if included?
This would read the profile from the gcode, when it is loaded or dropped on the scene view.
What was the purpose of writing the profile into the gcode?
Should it be optional (via menu) or should loading gcode read the profile unconditionally?

**Comment by hg42** [comment]
I wonder what happens when loading/dropping partial profiles (including only some settings).

Then we could compose a printing profile by dropping several "feature" profiles onto Cura.

E.g. we could have a partial profile for "speed 150mm/s" and one for "use raft and support" etc.

**Comment by hg42** [comment]
looking at the code of loadProfile, the partial profiles should probably work.

I currently wonder what's the purpose/difference of sections 'profile' and  'alterations',...and when start2 or end2 would be used...

**Comment by hg42** [comment]
I tested the partial profiles and it works very well.

I use files like infill-100.ini

```
[profile]
fill_density = 100
```

or shell-1.0.ini

```
[profile]
wall_thickness = 1.0
solid_layer_thickness = 1.0
```

this is especially useful when a "feature" needs to change several settings, like shell-1.0 does.

**Comment by nhfoley** [comment]
That is an awesome upgrade, because now I can save printer-specific partial profiles, which establish correct extrusion rates, retraction rates, and travel speeds based on the best setup for the particular printer without overriding whatever values I happen to want for the speed and quality of the print.
