### ISSUE TITLE
Requesting Jitter

### ISSUE THREAD

**Issue by frollard** [daid/LegacyCura#55]
Hello again; 

When printing multi-walled no-fill simple objects like a cylinder or cone, the layer ends are all lining up causing what amount to a massive gap in the print.
I'm not using retract because there isn't a sufficient jump to require the retract, but when it gets to the end of a layer, in my case it has to cross 2 finished layers to get to the inside of the next layer.  That crossing coupled with bowden lag means I get a bump so large that it cleaves the hot plastic from the end of the extruder and leaves a nice wide gap.  My understanding is jitter is supposed to help with this by moving the joint every layer.

Thoughts?

**Comment by daid** [comment]
Maybe lowering your temperature and increasing the Z speed might help in this case.

I'm not a fan of the jitter setting. It an ugly workaround, not solving the real issue but just hiding it by spreading it all over the place. But is some cases it might be the only solution.

**Comment by frollard** [comment]
Agreed - not the best solution.  I'm finding if I lower my temperature I'm not getting good layer adhesion on very thin layers.  Is it a difficult change to add?  I don't recall it has any arguments to send, just on or off...

**Comment by daid** [comment]
It's "on/off" and "Jitter_Over_Perimeter_Width_ratio", which seems to control how far the next start point is moved away from the previous. (They LOVE their ratios in SF)

Note, if you just want to "play" with SF settings, the file "cura_sf/fabmetheus_utilities/settings.py" contains all the settings and how they are calculated and/or if defaults are used. It's not user friendly, but if you really really really want something bad, then you can adjust it there.

**Comment by GregFrost** [comment]
So is jitter on by default? I joris'ed a vase and it looked like it was doing some random travel moves along the perimeter at the end of each layer. This is a BadThing(tm) when using joris.

**Comment by daid** [comment]
Yeah, we've noticed those moves, I have no idea where they come from, Jitter is off, always.

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
