### ISSUE TITLE
Cura does not fully comb octopus printed at half size

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#550]
When slicing http://www.thingiverse.com/thing:8896 at half size with 3 perimeters Cura 13.06.05 does not comb when moving between the tiny bits of infill on the legs. See the jumps between the legs in the attached image.

![curanocomb](https://f.cloud.github.com/assets/1351139/1078091/ec5c4666-151a-11e3-9c18-8dde0d38c586.png)

**Comment by RedwoodForest** [comment]
I realized this is probably a feature of the engine. Should I move this issue to the engine repo?

**Comment by ErikDeBruijn** [comment]
If you could, that would be helpful. If you can close it here. Possibly the
issue is already listed there, but I don't know for sure. The bracelet
thin-wall jumps seem related, at least that's reported. But it might be a
separate issue.

Met vriendelijke groeten / With kind regards,

Erik de Bruijn MSc.
Co-founder, Ultimaker BV

2013/9/8 Lawrence Johnston notifications@github.com

> I realized this is probably a feature of the engine. Should I move this
> issue to the engine repo?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/daid/Cura/issues/550#issuecomment-24026458
> .

## 

Ultimaker - easy, open source 3D printing! http://www.ultimaker.com/
Follow us on Twitter http://twitter.com/ultimaker, Google+https://plus.google.com/u/0/b/105283675489513173942/105283675489513173942/posts
, Facebook http://www.facebook.com/Ultimaker

IMAGINE IT >> MAKE IT
