### ISSUE TITLE
Feature request: Disable CURA_PROFILE_STRING

### ISSUE THREAD

**Issue by TopherMan** [daid/LegacyCura#552]
Loving the new slicer, but one issue. I'm using Smoothie's built-in gcode player, and the length of the CURA_PROFILE_STRING line makes it choke, even though it's commented out. Any chance of a radio button that would remove that line? I occasionally forget to remove it manually, and it would be handy to have an option to remove it.

Thanks!

**Comment by daid** [comment]
I would file a bug at Smoothie's and have them fix their bug? I'm not a fan of workarounds because other people are making bugs.
