### ISSUE TITLE
Feature request / Question

### ISSUE THREAD

**Issue by 42loop** [daid/LegacyCura#555]
Using an octoprint printserver with most of my printers, so i made an 'upload to printserver' button in the gui. made a new preference 'printserver_ip_port' which gets read and written from the gui settings. however, if I try to access the new setting from the program instead of hardcoding the destination, i get

Error: "printserver_ip_port" not found in preferences
Error: "printserver_ip_port" not found in profile settings

if I add something like
        print(profile.getPreference('printserver_ip_port'))
        print(profile.getProfileSetting('printserver_ip_port'))

to the constructor in sceneView.py

what additional steps are required to create a new setting ? all other settings are accessible, just not the new one ;-|

any hint on this ?

**Comment by daid** [comment]
Got it working? I was on a 2 week vacation so did not had the time to respond.

The settings need to be defined in Cura/util/profile.py, here also the display name and tooltips and any type of validation is added. Adding the settings to the preference dialog should be easy after that, in Cura/gui/preferenceDialog.py
