### ISSUE TITLE
Cura/util/profile.py does not contain function getGlobalProfileString

### ISSUE THREAD

**Issue by rambo** [daid/LegacyCura#556]
This triggers exception when slicing, it's not related to the pypy or pyserial

  File "/usr/share/cura/Cura/util/sliceEngine.py", line 317, in submitSliceInfoOnline
    'profile': profile.getGlobalProfileString(),
AttributeError: 'module' object has no attribute 'getGlobalProfileString'

I checked the profile.py source and it indeed does not define this function anymore.

Unchecking "Send usage statistics" in preferences works around this issue since submitSliceInfoOnline will exit immediately if  profile.getPreference('submit_slice_information') does not return 'True'.

**Comment by rambo** [comment]
https://github.com/daid/Cura/commit/cee07ca2da941ff1de454a533a734dffec143035#L7L308 seems to be the culprit.

**Comment by daid** [comment]
Note that the error is only printed, the program other then the online submit function works fine.

**Comment by rambo** [comment]
I can't doublecheck it now but I _think_ the whole slicing-thing failed (could not save gcode for example), I had plenty of other problems too (Ubuntu 12.04 64bit) which I mostly solved one-by-one, the last issue that I decided to simply leave was that I could not talk with the Ultimaker, even after patching pyserial to allow nonstandard speeds (after which pronterface started working fine) _and_ changing the Marlin firmware to 115200 version. Decided to simply use the SD-card with that machine (on my Mac laptop the release version of Cura worked perfectly at 250000bps you will be happy to know).
