### ISSUE TITLE
Initial layer thickness for better sticking to heatbed

### ISSUE THREAD

**Issue by markycee** [daid/LegacyCura#559]
I made a Prusa i3 printer with a 0.5mm nozzle. I use 3mm (2.9mm meas.) filament. I want to make my inital layer stick more to my heated bed. I therefore adjusted the "Initial layer thickness" from 0.2 to 0.3mm to supposedly create a thicker bottom layer that would make it stick more to the bed. 

When checking the generated gcode, the Z value from the inital layer also changed from 0.2mm to 0.3mm. Also the E values seem to proportionally adjust. How would this make the first layer be closer to the bed and/or stick better?

Should it not be a lower value, based on calculation how heigh (layer height) the filament becomes at a certain tickness (wide) ?

Kind Greetings
MarkyCee

**Comment by daid** [comment]
It does exactly as advertised. It makes the first layer thicker. If you want the first layer to start closer to the bed, adjust the Z endstop?
