### ISSUE TITLE
Bridge layers are over extruding

### ISSUE THREAD

**Issue by jgeerds-zz** [daid/LegacyCura#56]
This is new in cura 507c932207dcc02c767df0198a8754e6003be066:
Bridge infill is overextruding material, by about 50% (best guess).
bridge speed is set to 25%, infill to 100% (out of 100mm/sec, 0.2mm, skin on)

is this a miscalculation between the bridge and the skin plugin (since I am now using both at the same time)?

**Comment by daid** [comment]
I think this bug happens because when you need to adjust the speed, you also need to adjust the "flowrate", which I do for other settings but might have forgotten for bridge speed. (SF is pretty backwards in that way...) I'll have a look.
