### ISSUE TITLE
ocass. scale on walls on small objects

### ISSUE THREAD

**Issue by martinatweiss** [daid/LegacyCura#562]
Hey Guys!
First of all thanks for the great software and support. we are using our Ultimaker and Cura everyday in our construction office and have around 800hrs on our ultimaker.

![ko-25_02](https://f.cloud.github.com/assets/5477271/1156461/07bfccd0-1f88-11e3-8eb8-f30840850450.JPG)

The Problem: 
There are small fish-scale on the walls. 
It occured 2 times in the past 2 years.
The STL is fine because its exported out of CreoElements.
The settings are fine because we printed another part with the same cura settings without having any problems like this!!!
We tested different layer heights having the same problem but only ON THIS part, when we try any other part the machine works fine!!!!

STL, g-code, jpg: https://www.dropbox.com/sh/xax16je9prb5t0x/5gdhgCh9q9

Thanks for your support, best regards from austria! :)

**Comment by martinatweiss** [comment]
Here is a part using the SAME printer setup / settings as above without having this problem on outer walls

![img_0167](https://f.cloud.github.com/assets/5477271/1156513/06049c9e-1f89-11e3-8b4a-eed4ddfc4412.JPG)

**Comment by daid** [comment]
Looks like belt vibration to me, not directly related to Cura.

**Comment by martinatweiss** [comment]
all 4 belts are tensioned ... and the problem happened only at this part, even with printing the part 90° degree angle or different layer heights the problem occured.

this print went of the machine today in the morning (19hrs) no problem
![img_0180](https://f.cloud.github.com/assets/5477271/1172900/78801d66-212d-11e3-8546-4ad87ac2573e.JPG)

**Comment by daid** [comment]
I highly recomment posting the photos and question on the ultimaker forums, there are a lot of experienced users there that know which things could cause this. I know belts is one of the possible causes, but I surely know less then the ultimaker community collective.
