### ISSUE TITLE
Cura will not launch

### ISSUE THREAD

**Issue by TopherMan** [daid/LegacyCura#566]
Just updated my git repo and built, and it seems that Cura will no longer launch. The last functional commit is 999bfc18ffa0d5277b53258850e45ba56b99f5bf, and all the more recent commits give the following error when run from command line:

``` python
Traceback (most recent call last):
  File "/usr/share/cura/cura.py", line 33, in <module>
    cura.main()
  File "/usr/share/cura/Cura/cura.py", line 31, in main
    profile.loadPreferences(profile.getPreferencePath())
  File "/usr/share/cura/Cura/util/profile.py", line 646, in loadPreferences
    setActiveMachine(int(getPreference('active_machine')))
ValueError: invalid literal for int() with base 10: ''
```

For reference, I'm using Ubuntu 13.04 64-bit.

**Comment by TopherMan** [comment]
So after a bit of messing around, I found that deleting the contents of my ~/.cura/13.06.5 fixed the problem. After that, Cura started with the first run wizard and worked fine.

It looks like in the old preferences.ini there was a line that said 

```
active_machine = 
```

But in the new preferences.ini the line read

```
active_machine = 0
```

I won't close the issue in case you want to add something to prevent this crash from happening.

**Comment by daid** [comment]
Happened by running different dev-versions. A few commits back the default for active_machine was "" while after adding the int() conversion the default was "0". But a invalid value handling won't hurt I think.
