### ISSUE TITLE
ascii/unicode issue when accents in path

### ISSUE THREAD

**Issue by alx** [daid/LegacyCura#57]
Hi,

We had an issue yesterday in Cura on Windows.

We were on a french system, and the download folder for STL was something like "c:..\Téléchargement\model.stl"

With this path, we had errors in main_window.py about ascii/unicode char.

It's just after we found the same error on Slic3r that I understood that it was something related to the path.

I'm not on a windows machine, so I can't give you the precise errors, but I can retrieve it tomorrow. And I'm not fluent enough in Python to patch Cura over this issue, and give a warning to the user.

Thanks,

Alex

**Comment by daid** [comment]
Simple fix, I had already changed the code for this, but I broke it... (oops)
