### ISSUE TITLE
Serial connect does not work with Gen7 board

### ISSUE THREAD

**Issue by Patola** [daid/LegacyCura#573]
This seems to be the same bug as pronterface/pronsole bug 401: https://github.com/kliment/Printrun/issues/401

I changed /usr/share/cura/Cura/util/machineCom.py and modified the two timeout values (Cura 13.06.5, Ubuntu 13.04 x64, timeout values 0.1 and 2 on lines 307 and 309, to 5) and the USB connection worked correctly. Without it, it never works and Cura can never print.

**Comment by daid** [comment]
The idea is that the auto-baudrate-detection is quick, so it also time out quick. With a configured baudrate the timeouts are longer. Did you try the Gen7 board without auto-baudrate-detection?

**Comment by daid** [comment]
The timeout values in the serial class do little, the actual connection timeout is defined at line 327.

The timeout in the serial class defined how quick the "M105" messages are send after each other, maybe the Gen7 bootloader stays in bootloader mode if it receives a M105 in the bootloader. Which would make it a pretty crappy bootloader.
