### ISSUE TITLE
SD card detection

### ISSUE THREAD

**Issue by ad1217** [daid/LegacyCura#576]
I am not sure if it is specific to Debian (I run Linux Mint), but SD card detection has not been working since the update to the new slicer.
![sdcardfailedtosave](https://f.cloud.github.com/assets/4205882/1233056/4b2e2c8a-2903-11e3-8e5e-18652724a940.png)
Also, the manual path selection was removed from preferences, so I cannot just set the path.

**Comment by ad1217** [comment]
I have figured out why: in a newer kernel update (though I cannot find which version), the mount point changed from /media/foo to /media/<username>/foo. The detection in Cura's code just checks for /media/*. If someone knows the version which changed this, I could add that as an exception.
At the moment, I have a rather hacky fix which should work, but is not the best it could be.

**Comment by daid** [comment]
SD card detection on linux is hacky at best, the Windows and Mac implementation is much smarter. The linux implementation should just look at mount-points, not just get all the /media/\* directories. And might even do something smart with other interfaces to look if it's an SD card.

(And I think it's the udev system that does these mounts. The kernel does not do the auto-mounting as far as I remember)

**Comment by ad1217** [comment]
That last part is true, I misread something. 
At the moment, I have just changed this:

```
for volume in glob.glob('/media/*'):
    drives.append((os.path.basename(volume), volume + '/', os.path.basename(volume)))
```

to this:

```
for volume in glob.glob('/media/*'):
    if os.path.ismount(volume):
        drives.append((os.path.basename(volume), volume + '/', os.path.basename(volume)))
    elif volume == '/media/'+os.getenv('USER'):
        for volume in glob.glob('/media/'+os.getenv('USER')+'/*'):
            if os.path.ismount(volume):
                drives.append((os.path.basename(volume), volume + '/', os.path.basename(volume)))
```

Which does work on my system, (and is slightly nicer than the old system, as it actually checks if the paths it finds are mounts,) but seems like it might be easily broken.

**Comment by daid** [comment]
That's an improvement, does not break any backwards compatibility, so I added it.

Note that not all features got as much love as I would wish on Linux. So if you have more issues let me know. Also, I added a patch to support 250000 baud if your pyserial does not support that. But I have no idea if it actually works (no testing machine available)
