### ISSUE TITLE
Include images from URL or C&P buffer to uploads to YouMagine

### ISSUE THREAD

**Issue by ErikDeBruijn** [daid/LegacyCura#577]
Having a nice image to go showcase your design is important.
- [ ] Also allow uploading images from URL instead of just from disk. I've got my images online in an album (auto backup from my phone).
- [ ] Similarly, adding an image from the copy-paste buffer could be a nice feature, so whatever you do in the right click menu allows you to add an image (Either Save as file, copy, or copy URL).
- [ ] Remind the user to include an image if he/she hasn't done this.

**Comment by nallath** [comment]
Not a priority right now. Also, for multiple feature requests, create multiple issues. See https://github.com/daid/Cura/wiki/Issue-policies
