### ISSUE TITLE
Language bugs

### ISSUE THREAD

**Issue by ErikDeBruijn** [daid/LegacyCura#578]
Tested with: 13.10 multi-language test release from 1st of october
from: http://software.ultimaker.com/Cura_closed_beta/
- [ ] Use the new branch lang_nl_corr1 that I just pushed to git@github.com:daid/Cura.git for lots of translation improvements.
- [ ] It started with German for me, should be English based on my systems' locale. Maybe ask the user to specify/change language at the beginning of the first run window?
- [ ] For Next, back, cancel in the wizard, translations aren't used.
- [ ] Changing the language through preferences did work. However it doesn't reload the GUI (best solution) or reload the program after asking (an alternative that is okay).
- [ ] The title of the "Machine settings" screen aren't translated.
- [ ] The strings in duplicate object aren't copied (see screenshot below)

Low priority:
- [ ]  Check all the behavior of , (comma) as decimal separator (also for displaying).
- [ ] "Note that enabling the brim or raft disables the skirt" -> maybe it's good to ensure that this option is visually turned off when you enable brim or raft.

Around line 1631 of the translation, there's a line that reads "Sla ook meteen het profiel op als [stl_file]_profile.ini wanneer je een "
"model slicet."
I don't know what that refers to.
- [ ] Msgid "Cool" kan soms om een werkwoord gaan (Koelen) of "Koel" (bijvoegelijk naamwoord). Dit is niet duidelijk voor vertalers.

**Comment by illuminarti** [comment]
I just tested this on my MacBook. I don't seem to be able to get the UI in English. It starts in German, even though the preference says 'English' when I open the preference pain. Switching back and forth between Dutch and German seems to work, but when I pick English, I get German again anyway.

Also, when opening the preferences pane, it (still) doesn't become visible until I click the application's icon in the dock. (If I use expose to 'show all windows' it doesn't display either - it's not that it's hidden behind anything, it's not visible at all until I click the icon).

**Comment by ErikDeBruijn** [comment]
Du hast recht, Simon. Sehr gut. :)

I think I made less accurate observations than you did. Daid: make sure you read Illuminarti's comment too!

**Comment by ErikDeBruijn** [comment]
These aren't translated either:
![screen shot 2013-10-03 at 6 04 13 pm](https://f.cloud.github.com/assets/191236/1262898/87ab3532-2c45-11e3-8c79-1faa28b0a50d.png)
I was using dutch translations b.t.w.

**Comment by ErikDeBruijn** [comment]
Some variables are in there twice with the exact same label (don't know whether it's language specific):
![screen shot 2013-10-05 at 1 43 56 pm](https://f.cloud.github.com/assets/191236/1274562/7d90f7b6-2db3-11e3-95f8-5267650ecb7b.png)

**Comment by nallath** [comment]
Translations are created by certain users. They aren't a priority. If there are faults in them, people are free to change them and submit them for review.
