### ISSUE TITLE
Gatekeeper Signed Application for Mac...

### ISSUE THREAD

**Issue by illuminarti** [daid/LegacyCura#580]
Please can the Mac Application be signed so that it can be opened by double-clicking without upsetting the GateKeeper feature in OS X Mountain Lion?

**Comment by daid** [comment]
Depends, what does it require to get the app signed? I looked at the OSX app-store requirements, and those where impossible for Cura.

**Comment by illuminarti** [comment]
Here's Apple's general guidance on the issue:

https://developer.apple.com/developer-id/

More specifically, this is about how to sign non-app-store applications:

https://developer.apple.com/library/mac/documentation/IDEs/Conceptual/AppDistributionGuide/DistributingApplicationsOutside/DistributingApplicationsOutside.html

**Comment by daid** [comment]
The whole guide is build around Xcode, which I am not using, because, you know, cross platform development.

**Comment by illuminarti** [comment]
Well, it's based around XCode because that's Apple's dev environment. But there are plenty of cross-platform apps that are properly signed, and don't make users jump through hoops to run them. A bit of googling shows that its possible to do it mostly outside of the XCode environment... for instance, this guy talks about using the command line to sign his packaged-up Flash applications - it doesn't get more non-XCode than that!! :-)

http://blog.rustymoyher.com/post/36142106531/signing-apps-without-xcode

It would seem that once the cert is in place on your system, probably all that is needed is a single command line to do the signing.

**Comment by daid** [comment]
Step 1: Sign up for the Mac Developer Program. $99 a year.
Wait, I suddenly have to pay to develop on Mac? I already payed a shitload of cash for a shitty machine.

You might not know this, but I really hate this Mac development. It's a hostile environment. People are saying that I need to get used to it. But it's not the silly shortcuts (yes, you can get used to that). It's updating my compiler without notification or asking, oops, this code that worked last week will no longer compile. It's trying "act like nothing happened" on a power failure, but bringing terminal windows back without setting back the environment variables (and thus fucking up my build, which goes unnoticed till you run it on a different machine with a different OS version), the sheer complexity to making sure the application still runs on MacOS 10.6, it's Apple not showing dev downloads that I need (while it does show the downloads on the same URL for another person)
I truly hate every single time I have to test Cura on MacOS. If you think Microsoft is bad, wait till Apple gets even more foothold. I hope there is a special place in hell for everyone who buys a Mac.

**Comment by illuminarti** [comment]
I think the reason you don't see the links is because you haven't paid the $99... :-)

**Comment by daid** [comment]
But there was no indication that I had too do that to get the files.

Anyhow, Ultimaker will be looking into fixing this.
