### ISSUE TITLE
Save Gcode / Print Button deactivated on 13.06.5

### ISSUE THREAD

**Issue by felipepac** [daid/LegacyCura#582]
![captura de tela 2013-10-05 as 12 40 19](https://f.cloud.github.com/assets/5616674/1274505/9b21c5b6-2daa-11e3-8101-abf16a4f662c.png)
Dear all,

I'm running Cura 13.06.5 on 2 different macs and the Save Gcode or print button is not active. I can load models and visualize them, but Cura does not seem to calculate the Gcode either. The progress bar never appears.

This happened out of sudden. I already reinstalled Cura, but it didn't make an effect.

Has anyone gone through this before? Is there any solution to this?

Thank you,

Felipe Curado

**Comment by daid** [comment]
Does it say anything in the slice-log?
