### ISSUE TITLE
Failed to save

### ISSUE THREAD

**Issue by totemstudio** [daid/LegacyCura#584]
Hi. When we Save the GCode we get the message "Failed to save" Not always but almost...

**Comment by daid** [comment]
More information would be useful.

**Comment by 3yourmind-zz** [comment]
I have exactly the same situation here. The save function does not activate. Closing, reseting, restarting, installing from scratch does NOT help. In the slice engine log there is not info.

**Comment by daid** [comment]
"Failed to save" and "button does not activate" are 2 unrelated issues. If the save button does not activate then the CuraEngine is not working, most likely because the process fails to start.

Basic information like, which version, downloaded from where, which OS you are using, are always useful.

**Comment by 3yourmind-zz** [comment]
Well the button is grey, which I understand is not active. When I try to save gcode from the Files menu, it tells me 'Failed to save'.
Cura has been downloaded from the official site: http://software.ultimaker.com/ - version: 13.06.5
I use Mac OS X v. 10.8.5.

**Comment by totemstudio** [comment]
Exactly the same happens to us. But it is working lately if I wait about 20 seconds after applying changes.

**Comment by hg42** [comment]
this sounds like you have a big or complicated part, which needs 20 sec to compile to gcode?

CuraEngine is ultra fast, which makes us wonder if it takes some time...
Perhaps there should be some kind of progress bar or some other indication (e.g. mouse pointer) when compilation needs more than a few seconds.
