### ISSUE TITLE
Raft+Support layer difference

### ISSUE THREAD

**Issue by 3Dlab** [daid/LegacyCura#586]
Dear GitHub! 

I realized a problem in CURA13.06.4 when you would like to use the raft plus Support the layers are mixed. The machine firstly make the raft layer after this it makes the first object layer and just after these two layer turn on the support. That's why the support doesn't stick on the blue tape.

I have a suggest for you. I realy miss the Extra length on start after retraction. Please if it possible put this function back into the new version of softvare. 

Thank you !

**Comment by daid** [comment]
Fixed in nearly ready 13.10 beta from http://software.ultimaker.com/Cura_closed_beta/
Which features all new support material implementation.
