### ISSUE TITLE
How to build exactly the same firmware as bundled with Cura 13.10

### ISSUE THREAD

**Issue by hroncok** [daid/LegacyCura#589]
Hi, me again. Fedora packaging. I cannot include prebuilded firmware and I have to build it from source.

Now I can build MarlinUltimaker-115200.hex and MarlinUltimaker-250000.hex just by building whats in repository on https://github.com/Ultimaker/Marlin and changing the baudrate in Configuration.h.

I'm not quite sure, how to build MarlinUltimaker-XXXXX-dual.hex though. What option should I change in Configuration.h to build it?

Also, MarlinUltimaker2.hex is just default config from https://github.com/Ultimaker/SecretMarlin, right?

**Comment by daid** [comment]
The UM2 is indeed from SecretMarlin.

The other files are build with the following batch file:
https://github.com/Ultimaker/Marlin/blob/Marlin_v1/Marlin/_do_make.bat

**Comment by hroncok** [comment]
Thanks

**Comment by hroncok** [comment]
Is Ultimaker2 also atmega2560?

**Comment by daid** [comment]
Yes. Same CPU as the Ultimaker-Original hardware.

**Comment by hroncok** [comment]
OK, thanks, you can close this.
