### ISSUE TITLE
First Run Wizard - Machine Log hides

### ISSUE THREAD

**Issue by JustAnother1** [daid/LegacyCura#592]
In stage "Ultimaker checkup" with an Ultimaker1 if the Communication check fails and I click on "Show error log" the "Machine log" Window opens directly behind the Wizard window. That is a good hiding place.

The scroll bars can not be used to move the text

The text can also not be selected or copied.

Problem was with Cura 13.10 on Linux

**Comment by nallath** [comment]
The scrollbars and selecting worked on my setup.
