### ISSUE TITLE
First Run Wizard - Connection failed

### ISSUE THREAD

**Issue by JustAnother1** [daid/LegacyCura#593]
With Cura 13.10 on Linux connecting to an Ultimaker 1 does not work in First Run Wizard.

The firmware update process in the Wizard worked. The Ultimaker also reacts audible to the communication test. The Machine Log also shows Data coming from the Ultimaker: 

![ultimaker_connect_problems](https://f.cloud.github.com/assets/695780/1377187/552574ea-3aa2-11e3-8c34-a349847bde50.png)

Bit the test fails with "No more baudrates to test, and no suitable baudrate found.""

**Comment by nallath** [comment]
Could not reproduce.
