### ISSUE TITLE
Print takes 45 minutes (when it doesn't)

### ISSUE THREAD

**Issue by j0uni** [daid/LegacyCura#594]
Cura 13.10

For many slicings the Cura says it takes 45 minutes to print (which is nonsense). See this video:

http://www.youtube.com/watch?v=dlcsxDKnwEo

The model is from Thingiverse called "Wide_Mouth_Fan_Duct_for_Ultimaker" but it happens on SOME other models as well. Not all! Could it be .STL specific problem?

**Comment by ahmetcemturan** [comment]
Could it be that your minimum Layer time dictates the duration?

**Comment by daid** [comment]
Nope, but bug happens when there is a layer without printing, then a division by zero happens somewhere in the print calculation, which somehow ends up as 45minutes print time. I have a fix in place for the next version which most likely be a next month release to fix some issues.
