### ISSUE TITLE
Gcode export contains previous model, not current one

### ISSUE THREAD

**Issue by jjg** [daid/LegacyCura#595]
After printing one model, I delete it from the build view and load another.  The new model shows up and looks correct, but when I export the gcode, the original model starts coming out of my printer.

I also noticed that when this happens, most views display the "new" model, but the "old" one is displayed in the "layers" view.

Here's a screencap:

https://vimeo.com/77627920

**Comment by jjg** [comment]
Looks like this happens even after restarting Cura...

**Comment by daid** [comment]
The model is gray, which means it's bigger then the build area, at which point Cura will not process it. Which is why it still shows the old model.
