### ISSUE TITLE
Print settings are not maintained for different machines.

### ISSUE THREAD

**Issue by whosawhatsis** [daid/LegacyCura#596]
I love that Cura can now save multiple machines and switch between them, but it's not very useful when you can't maintain separate settings for different machines. Settings like nozzle size, print speed, filament diameter, start/end gcode, etc. are machine-dependent, and will often not work when switching from one model of printer to another. These settings need to be maintained separately and switched out when switching machines in the machines menu.

**Comment by hg42** [comment]
I recently added dragndrop of setting-files.
You can create subsets of a configuration by copying the config file and
editing it.
If you drop this file on Cura, all settings inside the file will be loaded.
So it's up to your phantasy, what you can do with it.
Note, I'm not sure if this feature is in the released version, I didn't try
recently.

**Comment by nallath** [comment]
Such changing will be adressed in the GUI overhaul.
