### ISSUE TITLE
Calibration wizard, Filament diameter not reported to the main window

### ISSUE THREAD

**Issue by francoischasseur** [daid/LegacyCura#6]
## Environment :

Win 7 64bit
Source : Commit 351bb29ade
## Scenario :

Start SkeinPypy
Open ExpertMenu / rerun first time run wizard
Skip firmware upgrade
Skip Checks
Enter the filament diameter  ( put 3.00 instead of 2.89)
Click on next
Click on Finish 
## Expected result :

In the print config tab, the filament diameter should be 3.0
## Actual result :

The filament diameter did'nt change in the UI. You should restart the application to see the change.

**Comment by daid** [comment]
Ah, yes. Indeed.
This only happens if you re-run the wizard. Which is why I didn't notice it before.
Fixed in the source :) thanks for the report.
