### ISSUE TITLE
"Open plugin location" button doesn't open it...

### ISSUE THREAD

**Issue by ErikDeBruijn** [daid/LegacyCura#602]
On OS X the plugin location won't open. I'm using 10.7.5, but it could very well be that the bug isn't that specific.
- [ ] Create the ~/.cura/[version]/plugins/ directory if it doesn't exist so that it can reveal the directory.

**Comment by illuminarti** [comment]
Works ok for me on 10.9 with Cura 13.10: it opens a finder window to ~.cura/plugins which contains a couple of plugins I wrote and manually installed into that directly several months ago.

Those are the only available plugins I see listed in the UI, btw? Does Cura ship with other plugins these days? If so, they're missing for me.

**Comment by ErikDeBruijn** [comment]
I figured out the following: if your plugins dir doesn't exist, it won't open it (surprise ;)). From a programming perspective I understand it, but for a user they want the folder to open up (hence, if not existing, it should be created). Also, it should be nice if at least one plugin is already included. Obviously, that should be a stable/tested plugin. PauseAtZ is nice, but I think it only works with the UltiController/UM2. Through USB it is reported to fail.

**Comment by jgeerds-zz** [comment]
There are 2-3 fundamental mistakes with the plugin handling:
1. ~/.cura/ is a hidden directory: I thought that we all had learned 2 years that storing preferences and user accessible files in a hidden directory under OSX is wrong, very wrong.
2. the location of the plugins folder is where illuminarti said it is: ~/.cura/plugins/ (NOT ~/.cura/[version]/plugins/ as mentioned earlier)
3. opening the plugins folder doesn't work under OSX 10.9 (unless the user has created it previously)
4. why not simply store the plugins folder right next to cura in the applications folder? photoshop is doing just fine with this strategy for the last 20 years
5. why is this (the proper location of the plugins folder) not mentioned or even linked anywhere in the plugins pages in your software wiki?

please fix this mess
