### ISSUE TITLE
Z axis lift

### ISSUE THREAD

**Issue by curious3d** [daid/LegacyCura#605]
Currently cura creates layers in a way which they collide.
i.e. starts filling circle from the center, then when it finishes at corner, it MOVES

**Comment by curious3d** [comment]
all across the circle to continue on the 2nd side :/
it's especially annoing at high layer height items and over-extruded items like rafts. 
otherwise it seems neglegible , but it still deforms prints a little.

**Comment by curious3d** [comment]
http://i.imgur.com/ixrJoLi.jpg here is the pic of issue, smear is visible @ upper right corner. 
this is also related with overextrusion and die swell, but one sets both of those options in first place , so slicer certainly should not perform decision like that if overextrusion is already set. there is no die swell compensation setting in cura aswell.
simplest solution to work-around the issue is imho just adding 'z lift on predicted layer collision' and could be done in post-processing phase . (analysing each layer's tool movement and inject z lift commands to avoid collisions . 

Excuse me for fragmented post but edit and upload somehow doesn't work for me.

**Comment by daid** [comment]
I think you would be better off fixing the backlash in your machine then looking for a software solution, as I'm seeing some signs of backlash (front left corner clearly has infill going over the circle, which is impossible unless you set the infill-overlap to some insane value or have backlash), which is causing odd build-ups of material.

As for "die swell" you can compensate with the "flow %", or not trying to print way-too-thick layers (my opinion is that printing anything thicker then half the nozzle size is problematic, and will give incorrect/ugly results)

**Comment by curious3d** [comment]
as this is raft layer, infill overlap IS set to insane value.
i use also infill overlap to make layers bond stronger in parts which do require it because of structural reasons - with correct settings they get very good results, EXCEPT the fact cura just happily assumes current layer always has enough gap. 

actually flow values and layer height are typed in into cura settings in first place, so i see no reason why it should not also avoid colliding with layers which grow.

**Comment by daid** [comment]
Oh, this is the raft. The raft settings in Cura are pretty much untested and the defaults most likely need tweaking.

I never use a raft.

**Comment by Kenzu** [comment]
I would like z-lift feature to. I use it with KISSlicer. only 0.075mm, but that's all i need to get perfekt finish on top layers and to avoid hotend tip catch filament bend up's on 40-50degress overhangs. I agree that it should not be to compensate backlash or flowrate calibration errors. I use only 0.075mm to keep speed up and not make blobs on z-lift.
So as a feature or comment in gcode so i could write a plugin maybe.

**Comment by ccavanaugh** [comment]
Agreed, z-lift is desired for cosmetics only and avoiding the occasional layer collision caused by variation in filament diameter.

**Comment by pwnate** [comment]
z-lift would be extremely handy for dual extrusion to help prevent color mixing when the nozzle for one color wipes over filament of another color. It is very noticeable when printing in black and white, as I am.

**Comment by daid** [comment]
So, when to Z-lift? Only when retracting? And lift before or after retraction?

**Comment by pwnate** [comment]
Probably just when retracting. I can't think of a case where you would want z-lift without retraction.

Lift should be after retraction to prevent material from oozing as the nozzle moves up.

**Comment by ccavanaugh** [comment]
I agree with retraction before z-lift and it only needs to be performed at times of retraction only.  Best to keep it simple.

**Comment by daid** [comment]
I'll look into it. I've spend way too little time in Cura lately. So I'm trying to spend about 50% of my Ultimaker time on Cura now. I have some ideas on how to implement this. I'll keep you posted. First, I'm refactoring quite a bit of GUI code as it has become a mess.

**Comment by pwnate** [comment]
Awesome! Thanks.

**Comment by BagelOrb** [comment]
Z hop has been implemented
