### ISSUE TITLE
Extraneous retractions

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#607]
I'm seeing regular extraneous retractions when the travel is either entirely is over the model or it should be possible to comb.

See for example lines 89-93 of https://gist.github.com/lawrencejohnston/7f13b60f2c91dc7d3c7f (one of the pieces from http://www.thingiverse.com/thing:150754).

**Comment by daid** [comment]
There are sometimes extra retractions on layer changes, I've implemented a quick workaround for the next version to prevent this.

**Comment by RedwoodForest** [comment]
Thanks.
