### ISSUE TITLE
The .deb package at http://software.ultimaker.com/ is reported unsafe.

### ISSUE THREAD

**Issue by berkes** [daid/LegacyCura#608]
And gives a big, ugly warning. It warns against some actual issues:

```
Lintian check results for /home/ultimaker/Downloads/Cura-13.11-debian.deb:
E: cura: arch-independent-package-contains-binary-or-object usr/share/cura/CuraEngine
E: cura: control-file-has-bad-owner postinst daid/daid != root/root
```

A (Dutch) screenshot of the warning is attached:

![schermafdruk van 2013-11-08 12 19 26](https://f.cloud.github.com/assets/77059/1499927/b63e243e-4867-11e3-8dad-8f50f245a66e.png)

**Comment by daid** [comment]
(Love the horrible bad dutch translation)

I'll have a look into it.
