### ISSUE TITLE
Wrong number of solid top/bottom layers

### ISSUE THREAD

**Issue by illuminarti** [daid/LegacyCura#611]
As reported here: 

https://groups.google.com/d/msg/ultimaker/STDOxzLriJ0/C6u5pzOrNfMJ

There seems to be an off-by-one bug that adds an extra solid layer on the bottom of prints, in 13.11.

Also, as mentioned in the post... it seems (without looking at it, of course) like it wouldn't be hard to adjust the slicing, so that the extra thick first layer (if any) is sliced at the correct midpoint of the first layer and then higher up layers are adjusted in their slice height and print height, so that the object comes out the right height.  Currently, any extra 'first layer height' just gets added to the total height of the print.

**Comment by varalgit** [comment]
No, the total height is always correct, but the thickness of the solid bottom is not. If you specify a Top/Bottom Thickness of 0.6, and a layerheight of 0.1, then you get 6 solid bottom layers (7 in 13.11), even though the first layer is 0.3. The thicker first layer is incorporated correctly when the total number of layers is calculated.

**Comment by illuminarti** [comment]
Actually... it looks like it no longer just adds the extra height on, but it doesn't get it right, either. Slice a 15mm high block at 0.1mm layers, with no first layer adjustment, and you get 150 layers of 0.1mm, as expected, ending at z=15mm.

If you change first layer to be 0.3mm thick, you get a print with 149 layers, finishing at z=15.1mm.

**Comment by varalgit** [comment]
In 13.12, this issue has not been resolved yet. If I slice with Bottom thickness 0.8 and Layer height 0.2, I still get 5 solid layers

**Comment by mblaster** [comment]
Still present in 14.09. 

As a workaround you can set a slightly smaller value for the bottom/top thickness. A value of 0.59mm results in 2 solid layers at 0.3mm layer thickness, instead of three layers for 0.6mm.

Edit: The wrong calculation happens in Cura/util/profile.py at 

``` python
def calculateSolidLayerCount():
  layerHeight = getProfileSettingFloat('layer_height')
  solidThickness = getProfileSettingFloat('solid_layer_thickness')
  if layerHeight == 0.0:
    return 1
  return int(math.ceil(solidThickness / (layerHeight - 0.0001)))
```

without the -0.0001 the calculations are correct.

Edit2: Btw, CuraEngine crashes if the layer heigth is set to a negative value. The gui complains about it, but the value is still sent to the engine...

**Comment by nallath** [comment]
@mblaster could you create another ticket about this in the CuraEngine github? This is not a problem of the GUI, but of poor handling on the CuraEngine side.
