### ISSUE TITLE
getVersion fails if repository is checked out as a submodule

### ISSUE THREAD

**Issue by wrtlprnft** [daid/LegacyCura#612]
Hi,

I'm trying to use Cura from within a git submodule. In that case, .git is not a directory, but rather a plain text file containing a reference to the real git directory.

This is a problem because Cura tries to determine its version from .git/refs/heads/SteamEngine, which will fail. The actual error message is as follows:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14665, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/tmp/mendel-printer/3rdparty/Cura/Cura/gui/splashScreen.py", line 16, in DoCallback
    self.callback()
  File "/tmp/mendel-printer/3rdparty/Cura/Cura/gui/app.py", line 91, in afterSplashCallback
    self.mainWindow = mainWindow.mainWindow()
  File "/tmp/mendel-printer/3rdparty/Cura/Cura/gui/mainWindow.py", line 28, in __init__
    super(mainWindow, self).__init__(None, title='Cura - ' + version.getVersion())
  File "/tmp/mendel-printer/3rdparty/Cura/Cura/util/version.py", line 24, in getVersion
    f = open(gitPath + "/refs/heads/SteamEngine", "r")
IOError: [Errno 20] Not a directory: '/tmp/mendel-printer/3rdparty/Cura/.git/refs/heads/SteamEngine'
```

I suggest adding a check whether .git is actually a directory.

**Comment by daid** [comment]
Feel free to submit a patch.

(I tried git submodules once, I think the implementation of submodules in git does not add any value, so I'm not wasting my time in attempting to support it)

**Comment by wrtlprnft** [comment]
(I'm maintaining a git repository to keep all configuration files and custom models for my printer. I'm using submodules to keep track of the combination of the various tool revisions I was using to print a certain object)

Here's the requested patch:

```
diff --git a/Cura/util/version.py b/Cura/util/version.py
index 5121216..fb6d7e3 100644
--- a/Cura/util/version.py
+++ b/Cura/util/version.py
@@ -5,6 +5,7 @@ import os
 import sys
 import urllib2
 import platform
+import subprocess
 try:
    from xml.etree import cElementTree as ElementTree
 except:
@@ -13,15 +14,24 @@ except:
 from Cura.util import resources

 def getVersion(getGitVersion = True):
-   gitPath = os.path.abspath(os.path.join(os.path.split(os.path.abspath(__file__))[0], "../../.git"))
+   gitPath = os.path.abspath(os.path.join(os.path.split(os.path.abspath(__file__))[0], "../.."))
    if hasattr(sys, 'frozen'):
        versionFile = os.path.normpath(os.path.join(resources.resourceBasePath, "version"))
    else:
        versionFile = os.path.abspath(os.path.join(os.path.split(os.path.abspath(__file__))[0], "../version"))
-   if os.path.exists(gitPath):
+
+   if getGitVersion:
+       gitProcess = subprocess.Popen(args = "git show -s --pretty=format:%H", shell = True, cwd = gitPath, stdout = subprocess.PIPE);
+       (stdoutdata, stderrdata) = gitProcess.communicate()
+
+       if gitProcess.returncode == 0:
+           return stdoutdata
+
+   gitHeadFile = gitPath + "/.git/refs/heads/SteamEngine";
+   if os.path.isfile(gitHeadFile):
        if not getGitVersion:
            return "dev"
-       f = open(gitPath + "/refs/heads/SteamEngine", "r")
+       f = open(gitHeadFile, "r")
        version = f.readline()
        f.close()
        return version.strip()
```

This adds two changes (both would individually solve my problem):
- Instead of checking whether ../../.git exists, actually check whether ../../.git/refs/heads/SteamEngine exists and is a regular file.
- Before mucking with git internal files, try using the git executable to obtain the current revision. This has the advantage of actually yielding the current commit hash instead of just the current head of SteamEngine. These might differ if the current checkout is on another branch, or an old commit (tag or otherwise) has been checked out. I realize this will almost certainly fail on most windows installations due to git not being in %PATH%, however it should fail silently.

**Comment by daid** [comment]
Easy patch. Added a few small changes (removed the ';' here and there, and added "stderr = subprocess.PIPE" so the error output on windows did not end in the console)

**Comment by wrtlprnft** [comment]
Thanks for the quick commit. python is not my native language, as evident from this patch ;-)
