### ISSUE TITLE
Open Profile ini

### ISSUE THREAD

**Issue by spac3man** [daid/LegacyCura#614]
Hello

When I save a profile, it does not save the file with a .ini extension.  So when I try to open a profile, Cura does not list any files as it is looking for files ending in .ini.  If I rename the file with the .ini extension, then Cura sees the file and can open it.  I am currently using b683b7a38670784a21b197f1811610073b975e7d

**Comment by spac3man** [comment]
anyone?

**Comment by daid** [comment]
OS?

**Comment by spac3man** [comment]
linux 12.04LTS

**Comment by daid** [comment]
Ok, might have something to do with the way the file dialogs work on linux. I'll have a look at it.
