### ISSUE TITLE
Why does Cura not set fan speed to max on bridges??

### ISSUE THREAD

**Issue by Kenzu** [daid/LegacyCura#617]
Why does Cura not set fan speed to max on bridges??
It really helps alot with bridges.
And as z-lift, I would like this feature or as comment i gcode.

Thanks

**Comment by j0uni** [comment]
I agree. Plus I would like to set speed decreasing percentage when building a bridge. Speeding down increases the quality of the bridges a lot!

**Comment by nallath** [comment]
Please create multiple issues for multiple feature requests. See https://github.com/daid/Cura/wiki/Issue-policies.
