### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by hurzl** [daid/LegacyCura#618]
```
Traceback (most recent call last):
  File "Cura/Cura/Cura/util/sliceEngine.py", line 182, in _watchProcess
    self._process = self._runSliceProcess(commandList)
  File "Cura/Cura/Cura/util/sliceEngine.py", line 352, in _runSliceProcess
    return subprocess.Popen(cmdList, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, **kwargs)
  File "/usr/local/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by daid** [comment]
"CuraEngine not found".

**Comment by hurzl** [comment]
?

**Comment by daid** [comment]
I matched up the quality of my reply to the quality of your input.

**Comment by hurzl** [comment]
It matches the program's error message, too!

**Comment by Kenzu** [comment]
How about telling a little about your system? windows, linus, mac os and
version of cura and where and how you installed it?
Then maybe Daid could help you better ;-)

2013/11/21 hurzl notifications@github.com

> It matches the program's error message, too!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/daid/Cura/issues/618#issuecomment-28981119
> .

## 

Mvh Jesper Lindeberg

**Comment by hurzl** [comment]
I have already deciphered daid's answer. The program does not tell anything.

**Comment by daid** [comment]
Nope, but searching for the error, or just reading the Readme (which starts with the title "Read this, it's important!") would have given you the answer.

**Comment by hurzl** [comment]
An error message would take fewer lines in code than in the Readme

**Comment by pavanbaru** [comment]
How is this error fixed?how do i run subprocess command?

**Comment by pavanbaru** [comment]
I am new to writing scripts on Ubuntu, the same script works perfectly well on windows, but fails because of a similar error on Ubuntu.
