### ISSUE TITLE
Feature request/ideas.

### ISSUE THREAD

**Issue by loelkes** [daid/LegacyCura#619]
Hi,
i have some ideas:
- [x] Rename the machines. I have multiple Ultimakers and would like to give them names (Home, Office etc.).
- [x] Assign profiles to machines. In my case one machine has a heatbed. It would be nice if the loaded profile is only applied on the selected machine or machine in the profile settings.
- [x] Keyboard shortcut fot Expert Settings (Cmd-E on OSX?).
- [ ] ~~Disable the automatic slicing in the settings.~~

Greetings. Nice work btw.!

**Comment by loelkes** [comment]
Another one, maybe a little bit more complicated. If i have an L-shaped object it is impossible to put stuff in the free space. See the example Screenshot. This is not so important since i can combine the stl files in another software...
![bildschirmfoto 2013-11-21 um 19 00 05](https://f.cloud.github.com/assets/231909/1594197/e4c3a79c-52d6-11e3-92a0-4aee2ea04ace.png)

**Comment by daid** [comment]
The L shape is a difficult thing to implement, I've been talking about it with my co-worker. And we have some ideas, but it requires some major changes in the code.

Auto-slicing is not going to be disabled. I've had this discussion multiple times. It's here to stay, as far as I know all performance issues with this have been solved.

Machines can be renamed, if you edit the ini file (I was having issues with doing it in the GUI), if you goto you home directory and then to .Cura/13.11/ there is a preferences.ini file, in there the machine names are stored and you can change them.

More profiles and profiles per machine is something I do want to add, but requires some major changes in the underlaying code.

**Comment by loelkes** [comment]
Thank you!
