### ISSUE TITLE
Cura - stl

### ISSUE THREAD

**Issue by wagter** [daid/LegacyCura#62]
A have a problem with loading a .stl into Cura RC2
The message is:
for arg in seq:
TypeError: 'bool' object is not iterable
?

**Comment by daid** [comment]
Which STL file are you trying to load? Might be a problem with a certain STL file.

**Comment by wagter** [comment]
L.S.

I am trying to load a .stl files made by cadspan resurfacer.
The original 3d files are .skp (sketch-up 8 pro)

Met vriendelijke groet,

Pieter Wagter, architect bna
0344-570206

-----Oorspronkelijk bericht-----
Van: daid [mailto:reply@reply.github.com] 
Verzonden: woensdag 18 april 2012 10:53
Aan: wagter
Onderwerp: Re: [Cura] Cura - stl (#62)

Which STL file are you trying to load? Might be a problem with a certain STL file.

---

**Comment by daid** [comment]
I cannot seem to export with cadspan resurfacer, it's saying I need the pro version :( (not had I heard from it before).
There is also a free STL export plugin: http://www.guitar-list.com/download-software/convert-sketchup-skp-files-dxf-or-stl

Could you send me one of those STL files? (You can email me at daid303@gmail.com, I won't share the file with anyone else, and delete it after solving the bug)
