### ISSUE TITLE
Can't start Cura on 10.9

### ISSUE THREAD

**Issue by danilke** [daid/LegacyCura#620]
I have build latest Cura with python 2.7.6 and wxPython 2.9.5.0 using osx 10.9(xcode 5.02) and on start up it gives me Cura Error. 

 Can't understand the reason of failure. 
Console:
Cura[77049]: GLUT Warning: glutInit being called a second time.
 Cura[77049]: Cura Error
 com.apple.launchd.peruser.501[162]: (com.ultimaker.Cura-13.11.2.125520[77049]) Job appears to have crashed: Segmentation fault: 11
ReportCrash[77058]: Saved crash report for Cura[77049] version 13.11.2 (13.11.2) to /Users/danila/Library/Logs/DiagnosticReports/Cura_2013-11-22-125427_Danilas-MacBook-Pro-2.crash
22/11/13 12:54:27,797 UserNotificationCenter[77061]: **\* WARNING: Method userSpaceScaleFactor in class NSWindow is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 

Error log:
 https://gist.github.com/danilke/7598830

**Comment by daid** [comment]
Most likely wxWidgets is giving issues if you build it on 10.9, I'm building my releases on a 10.6 machines for this reason.

**Comment by danilke** [comment]
So to solve that I need to reinstall xcode to lower version or Mac OS to 10.6?

Thank you! I highly appreciate your work!
