### ISSUE TITLE
Start bed heating button from print window

### ISSUE THREAD

**Issue by fns** [daid/LegacyCura#621]
The top of my heated bed does not warm up properly while the thermometer measures the required temperature. Therefore I can't use wait for bed preheat (M190) command but instead I'm using pronterface to heat up the bed properly.
This entire workflow would be simplified if there would be a "heat up bed" button on the print window which would start the heating.

**Comment by daid** [comment]
As quick workaround, you could send a M140 S[your-temp] with the "term" tab in Cura to heatup the bed.

I'll keep this in mind, as I'm currently redesigning how the printing window is implemented.

**Comment by luotinen** [comment]
Heat nozzle and Heat bed quickbuttons (maybe live buttons with temperatures?) would be excellent and enable faster workflow. The buttons could look normal cool and off, red when heating up, green when ready and yellow when cooling down. When the nozzle has been ready for x minutes, but printing has not activated it should start  blinking red (to warn about jamming) and when 2*x has elapsed the nozzle and bed should automatically turn off as a safety precaution. The nozzle button should only appear in the Expert mode and the Bed button only if there is a bed.

**Comment by nallath** [comment]
The entire GUI will get an overhaul.
