### ISSUE TITLE
Support Structure Bug

### ISSUE THREAD

**Issue by plaplapla** [daid/LegacyCura#622]
![support bug](https://f.cloud.github.com/assets/4974333/1606864/cd6f1fc4-545f-11e3-8e26-d9a69435a97c.jpg)
[Cura 13.11.2] There is a gap between the support structure and the object in Z direction, even if I set Distance Z to 0.

**Comment by plaplapla** [comment]
This bug occurs if raft layer is selected.

**Comment by plaplapla** [comment]
This bug still exists in 13.12. :-(

**Comment by daid** [comment]
Added a fix for the next release.
