### ISSUE TITLE
Adhension layer doesn't work for some model

### ISSUE THREAD

**Issue by plaplapla** [daid/LegacyCura#623]
For this model
http://www.thingiverse.com/thing:43910

When support type set to none, the adhension layer, either raft or brim, didn't work for the cover part.
![adhension bug 2](https://f.cloud.github.com/assets/4974333/1606895/75281d6e-5461-11e3-9109-040361a0d444.jpg)
![adhension bug](https://f.cloud.github.com/assets/4974333/1606896/753ae30e-5461-11e3-996e-854d49dddd3c.jpg)

**Comment by daid** [comment]
Does the missing part has stuff printed on the first layer?

**Comment by plaplapla** [comment]
No, the cover part was printed in the air, and started at the 4th layer while layer thickness was 0.1mm.

**Comment by daid** [comment]
Then the cover is floating above the build platform, which is why there is no brim added. You could split the object into 2 parts (right mouse button, split), sink it into the platform, or add support to work around this.

**Comment by plaplapla** [comment]
Actually, they were already 2 part separately. Something may be wrong with this stl file.
![adhension bug 3](https://f.cloud.github.com/assets/4974333/1623078/1826b896-56af-11e3-9c24-e8466081678a.jpg)
