### ISSUE TITLE
feature request; configurable infill width in advanced settings

### ISSUE THREAD

**Issue by luminize** [daid/LegacyCura#626]
Hi,
I currently use slic3r, and I am very taken with the quality of cura. Building parts which are mechanically used I need to make sure my infill is strong. When printing the infill the layer does not adhere enough to the second layer below (the infill in same direction). This is the same in slic3r. What I can do in slic3r though is to increase the infill width resulting in more extruded volume. That way the extrusion reaches and adheres to the second layer below. Meaning better and stronger infill.
Is it possible in any way to have functionality like that?
Thanks,
Bas

**Comment by daid** [comment]
In all honesty, sounds more like you have a general extrusion problem. Unless I understand you wrong.

(Cura 13.11 had a problem where it could print a lot of infills in the same direction due to it incorrectly detecting bridges, Cura 13.11.2 fixed this problem)

**Comment by luminize** [comment]
I think you understand it wrong (I hope). I’m 99% sure (never say never) I have the right amount of E-steps for my extruder. I’m not into the exact mathematics of the way infill is calculated, but what I see is that there is a gap between the extrusion of the strands of even or odd layers. Suppose I have a 0.35 mm nozzle, I print with a 0.4 mm width, layer 0.15 mm high. Then there will not be enough volume (unless I’m wrong and the slicer calculates more volume is being extruded) to fill the gap (0.15 mm, with a certain length) between strands of the previous (perpendicular to current infill direction).

**Comment by daid** [comment]
The slicer calculates the amount of volume it needs to extrude to fill up the width and height of a line. If you see a "solid" layer in the Cura layer view, then it tries to extrude the right amount of plastic to fill up that whole area without holes. (so a 10x10mm layer of 0.1mm will have about 10x10x0.1 = 10mm3 plastic)

Cura does assume that 1.0 "E" value towards the firmware pushes 1.0mm of filament trough the nozzle. And there are quite a few debates about how to properly calculate/measure the E-Steps for this.

**Comment by luminize** [comment]
OK, that means that if I read it correctly that for an infill of (I take easy numbers for calculation purposes) 1 mm width, 10 mm long and 0.1 mm layer height it extrudes 1 mm3 (let’s keep it at the end result and avoid steps/mm discussions). Meaning that if there is a rectilinear infill of for example 20% the current layer extruded infill will sag until the previous layer in the same infill direction. Meaning that I think there is too little volume to make up the width of the infill of 1 mm. I extrude 0.4 mm width with a nozzle of 0.35 mm. That means the plastic will be extruded from the nozzle, instead of being pushed out of the nozzle. And the width of the infill should be smaller than desired.
