### ISSUE TITLE
Plastic drag compensation

### ISSUE THREAD

**Issue by blazingeclipse** [daid/LegacyCura#627]
This is a feature request that is somewhat difficult to describe, so it's picture time!

So lets say I want to print the following shape;
![image](https://f.cloud.github.com/assets/6029141/1615323/d4809d30-55f7-11e3-9218-c23318b3a66f.png)
Especially at very small scale (10-15mm range of total shape) this will cause problems when printing fast. Because the PLA has a somewhat difficult cooling trajectory, moving the head that is still extruding plastic will cause some very anoying deformations.

![image](https://f.cloud.github.com/assets/6029141/1615352/24bacfb4-55f8-11e3-910a-f8cfc0a27f7e.png)
Where the orange blob is the start point of that particullar layer.

I think that having an option to slow down such difficult corners will solve the problem. I have tried printing models with details like this at a slower speed which improved the quality. However, the small details are the bottleneck here. It isn't very efficient to slow down the entire print in order to improve a few detail rich areas.

Complex solution;
So, a corner should be approached at a lower different speed if the line after the corner is very short and also has a sharp corner following it (this is to prevent problems with circles).

Simple solution;
Max accelleration setting. I was kind of supprised that this setting isn't allready available in cura.

**Comment by GregFrost** [comment]
I would have thought that this sort of thing should be handled by acceleration settings in the firmware. Not the slicer.

**Comment by blazingeclipse** [comment]
Sure, its probably somewhere in the firmware. However, the effect that I mentioned above is also depending on temperature and type of filament (certain additives will increase this effect ). To me, this does not sound as something that firmware accounts for. 
I am not that familliar with the firmware, but im assuming that the firmware has a first order and second order speed (acceleration and increase of acceleration)it is very likely that these are global values and not very dependant on the situation, and so I propose a somewhat more dynamic approach. This effect is only noticable with very small details that have relative sharp corners (slots for m3 nuts for instance), so adjusting acceleration accross the entire print will slow things down considerably. 
I suppose you could have the firmware account for this, but the user would still have to provide some measure of how much compensation is required. This is where the slicer comes into play then.

**Comment by daid** [comment]
As said, acceleration is handled in firmware. So you'll have to change it there.

And filament only drags after the nozzle if you try to print too thick layers with a too small nozzle. Else it will squeeze on the previous layer, and won't go after the nozzle.
