### ISSUE TITLE
Maximum print height not limited (z-axis)

### ISSUE THREAD

**Issue by MarvinTimmers** [daid/LegacyCura#629]
The maximum height of the model is not limited. When i have a to large width or depth for my machine the model will turn out gray (as a sign that it is not printable). This does not show up for the height
![hight flaw](https://f.cloud.github.com/assets/6040957/1622146/c94dc746-569f-11e3-93b3-2449032c9f04.png)

**Comment by nallath** [comment]
Could not reproduce.
