### ISSUE TITLE
Black popup boxes

### ISSUE THREAD

**Issue by Intrinsically-Sublime** [daid/LegacyCura#630]
I decided to give Cura a try and found that all the popup dialog boxes on mouse over of the input fields all display as black boxes without any text.

Cura 13.11.2
Gnome Ubuntu 13.04 64bit
Default theme in Gnome 3 Ubuntu

I also tried an older version of Cura and have the same issue.

P.s. Ubuntu complained about the .deb package as being of "Bad Quality" whatever that means.

**Comment by daid** [comment]
This seems due to the default color scheme of Ubuntu. The default text color is black, as well as the default background color for tooltips.

(Most likely the text color in the popups need to be set to SYS_COLOUR_INFOTEXT, but I need to verify this)

**Comment by hg42** [comment]
I assume it's a matching pair of colors:
SYS_COLOUR_INFOTEXT Text colour for tooltip controls.
SYS_COLOUR_INFOBK   Background colour for tooltip controls.

**Comment by Intrinsically-Sublime** [comment]
Commenting out the popup background color line in ConfigBase.py works as a workaround by defaulting to the same background color as the rest of the interface. It would still be good to add the correct line to pull the correct text color from the OS.

**Comment by daid** [comment]
Seems to be fixed on all OSes on the dev version.

**Comment by Intrinsically-Sublime** [comment]
Confirmed fixed

**Comment by Intrinsically-Sublime** [comment]
I just downloaded 14.01 from the github releases section and this problem is back.
