### ISSUE TITLE
Fan Speed On Full Settings

### ISSUE THREAD

**Issue by combatraffi** [daid/LegacyCura#631]
When I sliced a part with the full menu enabled the fan speed resets to a random low value (generally between 1-5%) on every layer.  This happens even if I "Tune" the print to full fan speed. This is with the fan enabled in the cura menu.  Unsurprisingly this ruins prints.

**Comment by daid** [comment]
During the inital layers the fan is controlled by the "Fan full at height" setting in the expert settings.

Slower fans during the initial layers helps at the adhesion of the material to the bed. And on the UM2 the fans reflect of the bed to the hotend cooling the hotend, so the fans need to be a bit slower during the initial layers there.
