### ISSUE TITLE
CuraEngine crashes & Prime Tower Feature does not work

### ISSUE THREAD

**Issue by matbhe** [daid/LegacyCura#634]
Hi

In cura version 13.11.2 are some bugs concerning the prime tower feature.
If I try to print the file error.stl (axle of object vertically aligned, support with second extruder and prime tower feature enabled) then the cura engine crashes and the save button will be disabled (tested on OsX & Windows 7). 

Error.stl - https://www.dropbox.com/s/6rpuzqdwi3oaikt/error.stl

Note:
It is still possible to save the G-Code over the menu even if the save button is disabled. If I do that and then try to print the following problems will occur:
- Ultimaker (V1) runs into Endstops or
- Ultimaker Dual Extruder Head Offset is Jumping around -> The layer is anywhere. This will give some crazy patterns but It is impossible to print an object.

Thanks for fixing that ;-)

P.S.: It would also be nice if there will be added a "give some additional filament on extruder change" - feature. I've written a postprocessor plugin for that and It's very useful to compensate the filament which will be lost by dripping. Without that feature it will almost be impossible to print an object with a material ratio from 1:100 (1 part material a / 100 parts material b) per layer.

**Comment by daid** [comment]
There seems to be a bug in relation to support that can cause a crash in the engine. I've fixed it for the next version.

(Saving the gcode after a crash will produce incorrect GCode, as to expect)

**Comment by matbhe** [comment]
Perfect! You did it :-). Thanx!
