### ISSUE TITLE
Retraction not always triggered when moving between islands

### ISSUE THREAD

**Issue by illuminarti** [daid/LegacyCura#635]
I've been slicing the standard (and MAKE-beloved) lightbulb spiral in Cura 13.11.2. 0.8mm shell, zero infill, for UM2.

http://www.thingiverse.com/thing:12108

I turned retraction on, with a minimum travel of 1mm, and minimum extrusion of zero. So it should pretty much retract every time it moves between the 5 oval-shaped islands that make up the body of the print. 

However, at the bottom of the print, no retractions are inserted into the gcode when moving between islands. It's not until the distance being moved gets up to about 10mm that I start getting actual retractions included in the gcode.

**Comment by daid** [comment]
It seems some code is a bit aggressive on "moving the head inside the print" at which point retractions no longer happened on inter-island travels that where shorter then 10mm.

**Comment by daid** [comment]
(updated for next release)
