### ISSUE TITLE
Extruder switch doesn't set filament width on extruder switch

### ISSUE THREAD

**Issue by paenian** [daid/LegacyCura#636]
I have two extruders, one of which is 3mm filament and one is 1.75.

When printing, both extruders move at the 3mm rate - leading to severe under-extrusion for the 1.75mm extruder.  Changing the Diameter2 setting doesn't appear to have any effect.

**Comment by Dim3nsioneer** [comment]
It's also a pain with two 3mm extruders if one filament has e.g. 2.8mm diameter and the other one has 2.9mm.
I hope this issue of not-yet-implemented-diameter2 will be solved soon. It may be quite a piece of work, but I would be really greatful.

**Comment by nallath** [comment]
The GUI will get an overhaul, which will include better support for multiple nozzles.

**Comment by Dim3nsioneer** [comment]
As I understand it from Daid's comments in the Ultimaker forum it is rather an issue of the steam engine than of the GUI. If the issue is solved at the same time when the new GUI will be published, then it's fine with me, otherwise I ask you to reconsider the closing of this issue.

**Comment by nallath** [comment]
There is no exact date when the GUI overhaul is scheduled. With these changes, there will probably be some changes in how data is shared / handled between the GUI and the engine.
