### ISSUE TITLE
no gcode output

### ISSUE THREAD

**Issue by molmodel** [daid/LegacyCura#638]
Cura loads the .stl file (77mb) in ca. 30sec. but fails to write (or even give th
![screen shot 2013-12-05 at 12 40 03 pm](https://f.cloud.github.com/assets/2845392/1686301/1457a9b8-5de5-11e3-977f-1cf7973e713b.png)
e option to write) the gcode file.

**Comment by daid** [comment]
What does the slice log say? (it's in the file menu)

**Comment by XiaoShiZi** [comment]
As the model is gray I suppose it's to big for the print size of the chosen
machine.
Try to scale down the model till you have a yellow model.If you still have
the standard colours.

Greetz
Xiao Shi Zi

2013/12/6 daid notifications@github.com

**Comment by molmodel** [comment]
Hello Daid,

Here is the slice log:
Loading # from disk...
Reading mesh from binary blob with 4603266 vertexes
Loaded from disk in 0.295s
Analyzing and optimizing model...
Face counts: 1534422 -> 1534398 100.0%
Vertex counts: 4603266 -> 788496 17.1%
Optimize model 3.486s
Slicing model...
Cura_SteamEngine version 13.11
Layer count: 808

the image stayed 'grey'

by changing the support from Brim to Raft, the file loaded and sliced properly, - I think it was a matter of size...

As you can tell, I am still learning to use Cura properly, so I ask uninformed questions...
In this connection, I want to compliment you not only for composing such an elegantly serviceable and versatile program but also for being open to beginner's questions, which must be tedious at times. 
I am especially pleased by how Cura builds support columns for the underside of atoms (spheres) for my models - not perfect, but far better than printing without a support.

Here is a photo of my recent printing result: when I used "Raft" 
http://molecular-sculpture.com/WebSampler/U_Development/0084Ribosome.jpg
and, as a diversion, there are videos of the ribosome structure at:
http://molecular-sculpture.com/WebSampler/Sampler.html

Many thanks - best wishes for Christmas and the New Year
Edgar

---

On Fri, 12/6/13, daid notifications@github.com wrote:

 Subject: Re: [Cura] no gcode output (#638)
 To: "daid/Cura" Cura@noreply.github.com
 Cc: "molmodel" model_em@yahoo.com
 Date: Friday, December 6, 2013, 7:59 AM

 What does the slice log say? (it's
 in the file menu)

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by molmodel** [comment]
I think you are tight and so, thanks for your suggestion
I changed from "Brim" to "Raft" and the slicing proceeded smoothly.
Here is a photo of the result:
http://molecular-sculpture.com/WebSampler/U_Development/0084Ribosome.jpg

Thank you for being so helpful!

Edgar

http://molecular-sculpture.com

---

On Sat, 12/7/13, XiaoShiZi notifications@github.com wrote:

 Subject: Re: [Cura] no gcode output (#638)
 To: "daid/Cura" Cura@noreply.github.com
 Cc: "molmodel" model_em@yahoo.com
 Date: Saturday, December 7, 2013, 1:14 PM

 As the model is gray I suppose it's to
 big for the print size of the chosen

 machine.

 Try to scale down the model till you have a yellow model.If
 you still have

 the standard colours.

 Greetz

 Xiao Shi Zi

 2013/12/6 daid notifications@github.com

> What does the slice log say? (it's in the file
>  menu)
> 
> —
> 
> Reply to this email directly or view it on
>  GitHubhttps://github.com/daid/Cura/issues/638#issuecomment-30000065
> 
> .

 —
 Reply to this email directly or view
 it on GitHub.
