### ISSUE TITLE
--slice option of cura.py broken with recent commit(s)

### ISSUE THREAD

**Issue by Xendi** [daid/LegacyCura#639]
I had the below error occur this week when using Octoprint with Cura integration on raspberry pi, with the devel versions from Dec 3rd of both (see https://github.com/foosel/OctoPrint/issues/323). 

The error looks like:
pi@octopi ~/Cura $ python /usr/share/cura/cura.py -i /home/pi/printrbotjr.ini -s /home/pi/.octoprint/uploads/20mm-box.stl -o /home/pi/.octoprint/uploads/20mm-box.gcode
Traceback (most recent call last):
File "/usr/share/cura/cura.py", line 33, in 
cura.main()
File "/usr/share/cura/Cura/cura.py", line 55, in main
slicer.runSlicer(scene)
File "/usr/share/cura/Cura/util/sliceEngine.py", line 118, in runSlicer
if scene.checkPlatform(obj):
File "/usr/share/cura/Cura/util/objectScene.py", line 228, in checkPlatform
if not polygon.fullInside(area, self.machinePolygons[0]):
AttributeError: 'Scene' object has no attribute 'machinePolygons'

It looks like the cl option is not reading the machine size settings from the preferences.ini, which is not supplied to Octoprint currently. 

I did get cl slicing/Octoprint working just now with the Nov 22nd commit of Cura, so the change must be after that, but I'm not sufficiently familiar with the Cura code to fix it myself, sorry!

Thanks for all your work, Cura is amazing and is rapidly becoming my go-to GUI and slicer combo!

**Comment by daid** [comment]
Can you let me know if this change fixed it?

**Comment by Xendi** [comment]
Bingo! That fixed it, thanks :)

I now have Octoprint on Raspberry Pi with CuraEngine doing the slicing
onboard (relatively fast), which will be a big help getting 3D printer
novices going at the hackerspace. Cheers.
