### ISSUE TITLE
Leftover screen message on desktop

### ISSUE THREAD

**Issue by Bertho** [daid/LegacyCura#640]
Win-7 64bit.
After closing Cura 13-11 it leaves a message permanently on the desktop.  See sample below.  Sometimes other messages are left behind.  I have seen this on previous editions.

The only way I found to get rid of the message is to reboot or to change screen resolution.
Bertho
![desktop message-1](https://f.cloud.github.com/assets/1622231/1692589/8cbe1b72-5e7f-11e3-824e-d80764e3912c.png)

**Comment by daid** [comment]
I've also seen this happen, but I'm unsure how this happens, as I've not been able to reproduce it reliably. (I also find it odd that windows can have popups like that visible for programs that have long died)

**Comment by nallath** [comment]
This is not a bug created by cura, but a windows bug. This happens with quite a few applications.
