### ISSUE TITLE
UM2 - Bounding box and clip interference

### ISSUE THREAD

**Issue by illuminarti** [daid/LegacyCura#641]
As discussed on the UM forum:

http://umforum.ultimaker.com/index.php?/topic/3285-will-um2-print-this/?p=28070

Currently, when deciding the maximum size of object to slice for the UM2, Cura looks for the bounding box to fit either totally inside the clip area in X, or totally inside it in Y, and then allows the other dimension to go up to the edge of the bed. 

This makes it impossible to print objects like the one in the post which extend pretty much right up to the edge of the bed in both directions, while totally avoiding the corners where the clips are.

Can the collision detection be made more intelligent, so that it actually considers whether printed geometry might intersect the clip area, not just the scope of the bounding box?

**Comment by daid** [comment]
Already done for the next release ;-)
(The current clip implementation was a quick workaround to protect nozzles. The next release will feature better collision detection here)
