### ISSUE TITLE
GCODE output for RepRap (Marlin/Sprinter) Z movement problem

### ISSUE THREAD

**Issue by nowhereman999** [daid/LegacyCura#642]
I'm using a Rostock Max delta printer and the using Cura to generate GCODE flavor RepRap (Marlin/Sprinter) in version 13.11.2 on a MAC OS-X 10.9 (Mavericks) computer (I noticed this same problem on previous versions of Cura also).

I think the spiralize option may play a pert in this problem

The problem is after a few layers (I think it might be after it completes the Bottom layer thickness layer) Cura inserts Z incremental movements on almost every line of GCODE that it creates.  It is totally unusable as the extruder just keeps getting further and further from the print surface.

For example Cura produces the following unusable gcode:

;LAYER:3
M106 S109
G1 F2400 E4931.70333
G0 F3000 X-62.42 Y6.04 Z1.05
...
G1 X-58.82 Y-19.69 Z1.55 E4985.05419
G1 X-53.47 Y-31.52 Z1.56 E4986.61093
G1 X-52.87 Y-32.85 Z1.56 E4986.78498
G1 X-51.98 Y-33.93 Z1.56 E4986.95333
G1 X-43.51 Y-44.26 Z1.57 E4988.55369
G1 X-42.56 Y-45.41 Z1.57 E4988.73236
G1 X-41.42 Y-46.23 Z1.57 E4988.90138
G1 X-30.53 Y-54.04 Z1.58 E4990.50654
G1 X-29.36 Y-54.88 Z1.58 E4990.67903
G1 X-28.05 Y-55.37 E4990.84715
G1 X-15.54 Y-60.08 Z1.59 E4992.44930
G1 X-14.16 Y-60.61 Z1.59 E4992.62611
G1 X-12.31 Y-60.79 Z1.59 E4992.84962
G1 X-12.19 Y-60.83 E4992.86356
G1 X-12.14 Y-60.86 E4992.87191
G1 X-9.28 Y-61.85 Z1.60 E4993.23420
G1 X-9.27 Y-61.85 E4993.23599
G1 X-7.67 Y-62.13 Z1.60 E4993.43000
G1 X-7.58 Y-61.26 Z1.60 E4993.53549
G1 X2.01 Y-62.21 Z1.60 E4994.69124
G1 X16.62 Y-59.80 Z1.61 E4996.46525
G1 X18.04 Y-59.57 Z1.61 E4996.63756
G1 X19.32 Y-58.99 Z1.61 E4996.80592
G1 X31.52 Y-53.47 Z1.62 E4998.41109
G1 X32.84 Y-52.87 Z1.62 E4998.58515
...
;TYPE:WALL-OUTER
G1 F2280 X62.42 Y-6.04 Z7.17 E5032.97724
G1 X62.44 Y-5.88 Z7.26 E5032.99741
G1 X62.44 Y-5.81 Z7.30 E5033.00535
;LAYER:4
M106 S89
G0 F3000 X62.58 Y-5.79 Z1.30
;TYPE:WALL-OUTER
G1 F2700 X62.57 Y-5.72 Z1.30 E5033.01357
G1 X62.64 Y-2.49 Z1.36 E5033.40076
G1 X62.62 Y-2.38 Z1.36 E5033.41458
G1 X61.92 Y-9.39 Z1.49 E5034.25891
G1 X61.99 Y-9.20 Z1.49 E5034.28339
G1 X61.99 Y-9.16 Z1.49 E5034.28771
G1 X62.58 Y-5.79 Z1.55 E5034.69775
...

Notice how the Z height started Layer 3 with a height of 1.05 and in the middle of this 3rd layer the Z height is already 1.62 (It actually gets even higher 7.30mm beofet he end of Layer 3).  Then when it reaches Layer 4 in the code the Z height is set back down to where it should be at 1.30 (this example was created using a layer height of .25).  Then it goes up again for just about each line of gcode, and this continues...

I think the fix is to remove the Z positions on any line that starts with G1.

Thanks for some cool software, I'm surprised others haven't reported this problem before me.  I hope you can fix this problem soon.

Thanks,
Nowhereman

**Comment by daid** [comment]
> I think the fix is to remove the Z positions on any line that starts with G1.

Now that's just silly, as G1 is a move, which means it will never move in height.
I think this is a bug related to spiralize, which needs to increase the Z every move, as that's the function of spiralize, can you share the model and exact settings you used?

**Comment by nowhereman999** [comment]
Your code uses G0 to move the Z position to change the height, as you can see in the code on my first post.  That was why I recommended to fix the problem was to remove the Z positions on the G1 lines.

Cheers

**Comment by daid** [comment]
G1 are printing moves, the only way Cura adds Z moves in G1 moves if you enable spiralize. Which is why I asked for the exact settings.

Removing Z moves on G1 would totally defeat the spiralize function, and that's exactly what would happen if you would disable spiralize. "Fixing" a problem by totally destroying a function is not a fix at all.

**Comment by nowhereman999** [comment]
Hi daid,

From the http://reprap.org/wiki - 
"G0: Rapid move
Support  FiveD   Teacup  Sprinter    Marlin  Repetier
                  ???               yes     yes    yes   yes
Example: G0 X12
In this case move rapidly to X = 12 mm. In fact, the RepRap firmware uses exactly the same code for rapid as it uses for controlled moves (see G1 below), as - for the RepRap machine - this is just as efficient as not doing so. (The distinction comes from some old machine tools that used to move faster if the axes were not driven in a straight line. For them G0 allowed any movement in space to get to the destination as fast as possible.)

G1: Controlled move ..."

I took the output from Cura and ran it through a little program I wrote that removed the Z movements on the G1 lines and it printed a nice bowl for me.  Maybe I'm missing something here?

![vlcsnap-2013-12-10-16h57m44s145](https://f.cloud.github.com/assets/4142371/1719029/50276fbe-61e6-11e3-9eeb-1b0df7da5dc6.png)

**Comment by daid** [comment]
You're missing my request, 3th time is the charm?

"can you share the model and exact settings you used?"

Oddly enough you would think RepRap users would be smart enough to see that simple request from me. Then again, stubbornness is also big in the RepRap crowd.

As for missing my other point. Spirailize, or "the act of increasing the Z while printing the contour", will, by definition, increase the Z while printing. Your idea for the "fix" is like removing extrusion all together to fix over-extrusion.

(Not to mention that "removing Z on G1 moves" totally misses the point on how the CuraEngine works, which only generates GCode as really final step. It never "modifies" GCode, it only outputs it as final step)

**Comment by nowhereman999** [comment]
Hi daid,

Your first reply back was to call my suggestion silly.  Thanks.

Then you say RepRap users should be be smart enough to see a simple request.  And that we are stubborn, Thanks again.

This doesn't make me want to work with you to fix the trouble.  Maybe I'm not home yet and can't send you the G-Code, maybe I don't have it anymore, maybe I erased Cura because the author thinks everyone is an idiot...

I didn't mean for your program to generate the code then fix it later, I meant that it needs to end up with it a certain way.

The model was created by my son from this website http://shapeshifter.io/
I have the .stl file if you need it but I don't know how to attach files here other then pictures.

Here is the settings from the end of the G-Code file.
;CURA_PROFILE_STRING:eNrtV01v20YQvRJGf8QcUzRWSUqy4gi8JLXTQ1IEsIvYvhArciRtTXKJ3aVl2dB/78wuRVG2HCRtLgXqgyUOZ2bn482bVSHWqNMlysXSJuEgHgcrURSpXcrstkJjkmgQBhqtFpmVqkqxErMCk0vdYGBUIfO0cB52BnEwl+Qhx8pIu07iMKjUw0OBqZEPSEeMg1rLyqamRsyT0fbRYlmjFrbRmMTxAWmchM+Fw0PCUSecYb7neBIHpqlrpW3yh6owqAth50qXqciXaCg/L2510rwRRYr3Vjfu3Ttll8FK1phatUKdnIvCYKDUA+W2lFjkrYTyFyXS8bmkT0ua0eBk8lzMGT0TDg8JR33hvFCrJArH/ba0xQz3myVK1VQ2GQ32dF1W7avoZP9dKauUHu6woJj33mSqnMlq4Tu/byHLvTJxi2fKWlX2UBEOhoGa/YUZNV5WtwlHqu5QF6J2ATH2An9ym8w43HrxCPNSgpOsHMD880kYZEoVLvAWibJEKk8wF1u05i1cbyX1tJAVUjKc/LAVLURN9fXft+kUWC3sMonGHCi7mjd0ZjcnYyfzIQx7D2kp7pOT8S6mOQkJfC4iJ1yioJmRc9ufIavq/qPP20tcrm2lKJwOm07uPe+E92uCjLGiynjSJp38oS9m/VpqUfA8ujNmWpb9wlCRtZhTMYReyCoZ+yenYGqRMQwcLbB0Jgw+6fNOziYrmVMhORonp7FEPRfZvlH89GXfkhnlPl0qrSV1M20qh21mqTXNouim7mWd2UEdClDVWKUzac0hBYI0k9gdZW2lzZact1eri4YKQ9UiKC6SV0UdHQ228M6Qk0jvk+PoiWhNop+oDdoOFpnKMZleFDLDHIR9C4+5WG/4v0X6YBBvjqbvhJEZGLSWzjZv4SMjHDwKyaTokfcGvlC6pPO4T+AbOCekkLjPyuT6MxMk8Dn0rqVQf+h5SzRABcq9oScezxmbsida+bMXPatMGdu34mfy+ik6DeHi8SAvb2D6Z0UE4+ytApHnsFaNBrWqgHShpwuMDHYXnnbuvtXVMzcf4jcwhaUqEahoIO7RHH2KRhToJB6EIUx/R2F9BAomMb0LR3ARx9s3jvRy1Ec+u0kM0y9CWqCdQl0StrVcoO0cRCc9HT60F5RxERP67igeMqHOau4+3ImiodA+RHAzhvPhkEMDJhHwuzXAKm8x5UMM2zRYjzxXoObzXbScNrSJH316MwJwj8QRTJdQKqu0CRxS4/+h+gOgOvr3UPWIv4wOeYr/kavwR8xPBO3flC4qmhCwhSqVcPtGzGitNRahVtRRImZCCI/SZKvgkAYraZeMeaBtynh1ML0K4Tpk77QC4erXa46J9ioQ4A1tTeOUbsI2BFa6ea5CYxONByGcP/ZvGJvWgI/cXgQh5zyjcVkeXXap7f9NL1a8DPgUtoyrvDdYpzGchQdsHlB79VY1B3/B4NjOYxrns2jfbNoqQhSWJVUD+CIBlE92+/2ngFgIWe3OOn48fB3cHF2G35T0XGpj/0tp7zeeKKWx4LBPUISSuEcsEFQFH9//BibTiBVT9QQ+tzqDwYA5tmPDM+r6h/f01a+ES0e1Bwu3LZLbB/TBwPY20XfajF4+xOnljn92JvBKznl2YUmpg7Q/UwVfwPQTdxppHHgJ9QeWynh2TKXk5fN1YwetFict0wqgSxbFRzOGbnFx3VnD76/XDCw6FenSCIbXMbXezSUtRUN042b4F7p3UwxjuDqmDXzN/w5P9A00dXukoEZtI+qiwTusaMtp7FPMV5N6iX5eU7QuUL7WgzSgCFht7Cux7pbrQafGYk18ajzZnb4cw0EG7S73/RtlJ9xdCPzPjj0lJ+lpaCT+y3CQmTvy4Cb9rIVgt/79/M/Qrmg4XH5Zo7Wr5hatXGvXU5J00tewWpJBN2yO5cumsLIuuonVZtCOt4fZ8ATOx2EYboWXj1vFDStcPdKPg/R+A9fuC11GbtyXh82zSWd3T7z9DSkbqQU=

**Comment by daid** [comment]
I do no think everyone is an idiot. (There is a huge difference between being silly and an idiot), there is also a difference between "everyone", and a specific person who acts as if he knows everything but clearly misses information.

I do think that if I point out 3 times that "spiralize" will move the Z during printing because that's the function of spiralize. And then you still suggest that I remove the Z moves that you are clearly missing a point.
After all, getting rid of the those Z moves would be as simple as disabling the spiralize option. (You know, spiralize causes Z moves during printing, disabling spiralize = no Z moves. Huray!)

The problem is specific to your settings and model. With the same settings on a different model I get correct Z moves. So if you could email me the model (daid303@gmail.com) then I can look into why it goes wrong with this model.

**Comment by daid** [comment]
Found the problem and fixed it for the next release (thanks for mailing the model, really helped)

**Comment by nowhereman999** [comment]
I&#39;m glad to hear you were able to fix the problem. 

Thx for a great app. 

Cheers,
Nowhereman.
