### ISSUE TITLE
Ubuntu Save to Gcode Drive type

### ISSUE THREAD

**Issue by hisashime** [daid/LegacyCura#643]
Hi,
Cura is not recognizing Ubuntu ext4 drives. When saving to gcode it provides only NTFS drives and there is also no option to choose folder to save to.

Thanks for the great Cura.
![screenshot from 2013-12-07 07 47 24](https://f.cloud.github.com/assets/3079446/1697078/3ed2c5e6-5ed1-11e3-8a82-7850f18b00d9.png)

**Comment by daid** [comment]
Cura on linux has some issues in detecting SD cards and it's incorrectly detecting your windows drive as an SD card. I recommend disabling the SD card auto-detection in the preferences menu, then the SD button turns into a normal save button.

(You can also right click on the save button to get the option to save with a path)

**Comment by hisashime** [comment]
Thanks a million.
