### ISSUE TITLE
Z axis lift in the end of GCode is broke calibrate of Z axis

### ISSUE THREAD

**Issue by Stalker-X** [daid/LegacyCura#646]
Hello!
I'm using Hyxley 3d printer. And I want to start slice whis the Cura.
But I have some problem. In the end of printing calibrate of Z axis is brokening.
As it turns out, because in the end of  GCode Cura include Z axis lift, but Hyxley have a slow Z axis. The end of GCode looks like:
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////
G0 F7800 X65.75 Y65.88 Z15.00
;End GCode
M104 S0                     ;extruder heater off
M140 S0                     ;heated bed heater off (if you have it)
G28 X0 Y0                              ;move X/Y to min endstops, so the head is out of the way
M84                         ;steppers off
////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Z15.00 is lifting axis, but the printer does not have time to do it.
I had such a problem in SLIC3R, but in the slic3r was written off this option on slow z axes.
How can I disable this option from Cura?
I liked the Cura, but every time when I printing, I must manually delete Z15.00 from the GCode. And if I forget to do this, the calibrate of axis z again broken.
Thanks.

**Comment by daid** [comment]
Limit the Z speed in your firmware. All Z moves in Cura are done at travel speed, with the assumption that your firmware will limit the Z speed. Which is a good idea anyhow to setup proper.
