### ISSUE TITLE
Spiralize Horizontal surfaces

### ISSUE THREAD

**Issue by dominicdoty** [daid/LegacyCura#647]
I attempted to use spiralize to print a hollow model with an enclosed top, and the results were extremely good, except for horizontal or near horizontal surfaces which were left partially filled or completely unfilled.  I think it would be a great feature to allow spiralize to fill in these horizontal surfaces for creating quick printing, good looking, and string-less hollow models.

**Comment by BagelOrb** [comment]
Horizontal regions will fal down and cause angle fluff
