### ISSUE TITLE
Functionality Enhancement (Series or Parallel)

### ISSUE THREAD

**Issue by combatraffi** [daid/LegacyCura#648]
I would love to have a simple check box in the quick print that would allow different parts on the build platform to be built in series or in parallel.  It would give way more control over the build platform and would not add significant complexity to the beginner user.  It could also help with reduction of stringing between components.  I think the major challenge from a coding standpoint would be the boundary between parts for components built in series would be different than for those built in parallel but that really could help you get the most out of your build volume.

**Comment by daid** [comment]
You can already do this, if you want to build prints in series you need to enter you correct head size (and gantry height) in the machine settings.

(For Ultimakers these are filled in by default)

Printing in series is done if all the objects are below the gantry height, else printing in parallels is done.

The next release contains a few enhancements on this area.
