### ISSUE TITLE
Bridge settings in Cura 13.11.2

### ISSUE THREAD

**Issue by omloml** [daid/LegacyCura#649]
Hi,
I am new to GitHub and to Cura. Switched from Slic3r and am quite pleased with it. However, I am using some experimental filament and having trouble bridging gaps.  I can't seem to find any bridge settings in the control panels for expert or advanced.  

My question is: Is there some way to control the speed and flow of the print nozzle at this crucial time during the printing process?

**Comment by daid** [comment]
Currently there is not, bridges are printed at the same settings, except for the direction of the lines (which is auto-detected as bridge)

**Comment by RedwoodForest** [comment]
I would like bridge settings back too. Especially when printing infill faster than perimeters it's often too fast for good bridging.

**Comment by ahmetcemturan** [comment]
Bridging is definitely a weakpoint in Cura atm..

**Comment by RedwoodForest** [comment]
Why was this closed? These settings still aren't available last I checked.

**Comment by nallath** [comment]
True, but the issue asked a question; is it possible to modify the bridge settings. The short answer is no. 
As stated in our (new) issue policies (https://github.com/daid/Cura/wiki/Issue-policies), we want new issues created for every question. This includes asking for features in a information request.

**Comment by RedwoodForest** [comment]
Reopened as #765
