### ISSUE TITLE
Fill density 0% still makes fill?

### ISSUE THREAD

**Issue by Mowi** [daid/LegacyCura#650]
I sliced a dual color Julia vase. Although I put the fill density to 0% cura still generates infill in half of the areas. why is that?

![infill](https://f.cloud.github.com/assets/2234302/1700312/2b9a1e64-6009-11e3-91c3-2e7a0ad27132.JPG)

**Comment by daid** [comment]
those are up/down skins to support the tops/bottoms of the parts. Different colored parts are seen as different things that need to be sealed up.
