### ISSUE TITLE
Feature request: an option for parallel-line pattern support which used in previous version

### ISSUE THREAD

**Issue by plaplapla** [daid/LegacyCura#651]
The grid-line pattern support in new version Cura works not very well for complete flat part over the support. Could you add an option for the parallel-line pattern support, and adjustability for pitch of the lines in both grid and parallel line support.

**Comment by daid** [comment]
The grid is adjustable, "Fill amount" in the expert settings adjusts this.

The line pattern left more bad areas at a flat parts then the grid, so I see no reason to return it.
