### ISSUE TITLE
deterministic cancel during print

### ISSUE THREAD

**Issue by TheTesla** [daid/LegacyCura#652]
On some parts, Cura stops printing at a special line. Printing two times the same, it is the same position.

It depends on the printed part and the print attributes. It is independend from speed settings in the print dialog. 

Cura 13.11.2 on Windows 7, 64 bit, Printer: Luna mendel v0.20

verify it:
https://github.com/TheTesla/Kettenantrieb/blob/master/Kettenrad.stl
https://github.com/TheTesla/Kettenantrieb/blob/master/bug.ini

**Comment by daid** [comment]
Did Cura stop or did your firmware stop?

**Comment by TheTesla** [comment]
Maybe. If The firmware can also be the problem, I will check it later.

Am 11.12.2013 14:28, schrieb daid:
