### ISSUE TITLE
no relevant gcode generated

### ISSUE THREAD

**Issue by mkubik** [daid/LegacyCura#654]
Try to generate gcode for Clips.stl in http://www.thingiverse.com/thing:52769
Similar to Cam_Followers.stl all the thin, vertical surfaces are not generated in gcode.

**Comment by daid** [comment]
Cura has issues with slicing very thing things, with RepRap settings (0.5mm nozzle, 1.0 shell thickness) these indeed slice "wrong" because they are so thin. If you put it to UM settings (0.4mm nozzle, 0.8 shell thickness) then they slice right.

Known problem, but no fix in sight.
