### ISSUE TITLE
 .8 mm walls

### ISSUE THREAD

**Issue by blazingeclipse** [daid/LegacyCura#656]
![cura 13 11a](https://f.cloud.github.com/assets/6029141/1714908/631b5630-61aa-11e3-9d41-4a7d438cad12.jpg)

There seems to be a strange overshoot when printing walls .8mm thick with a .4mm nozzle. This was not an issue with versions before 13.11.2. The issue only occurs when  printing walls of .2x nozzle width.

![cura 13 11b](https://f.cloud.github.com/assets/6029141/1714921/94a45602-61aa-11e3-8ad0-7253d2a843c6.jpg)

**Comment by daid** [comment]
13.11 tries to move the nozzle inside of the print before traveling, looks quite a bit like this. But it should check if the final position is actually is in the print, not sure why that fails.

Got a link to the model?

**Comment by blazingeclipse** [comment]
![imag0403](https://f.cloud.github.com/assets/6029141/1722451/ddfae4e0-6242-11e3-918e-059c3157cbc6.jpg)
I dont have acces to the model right now, but I do have a picture of what the result looks like. The flaw is on both the inside and the outside of the wall (as can be seen in the G-code as well). I'll get you the model ASAP, but please note that this isn't the only model where this effect has occured. Cups with 2 walls have the same issue.

**Comment by daid** [comment]
Just noticed the problem on another model I have. Found the issue and fixing it right now.
