### ISSUE TITLE
MacOS: missing proper .app

### ISSUE THREAD

**Issue by yzorgone** [daid/LegacyCura#66]
how does one get that app to run? i really want to try this since i only can test with RepG.
(im on Mac os 10.6.8)

i mean thers no App file wich i would doubleclick and then atleast something would happen on my screen...
Do i have to compile that thing anyhow so that it gets to start and bring me a Window?

any help apreciated
thx in advance

**Comment by fuegas** [comment]
Steps you should take to start Cura on Mac:
1. Make sure PyOpenGL is installed
   - Use `sudo easy_install PyOpenGL` to install
2. Make sure PySerial is installed
   - Use `sudo easy_install pyserial` to install
3. Make sure wxPython is installed (Make sure you have the **Cocoa/64-bit variant, developement releases**)
   - Download from `http://www.wxpython.org/download.php`
   - Direct link: `http://downloads.sourceforge.net/wxpython/wxPython2.9-osx-2.9.3.1-cocoa-py2.7.dmg`
4. Set program starter to main directory
   - From main directory `cp scripts/osx64/cura.sh .`
   - Set execute rights `chmod u+x cura.sh`
5. Start Cura by running `./cura.sh`

**Comment by yzorgone** [comment]
Hi Ferdi

Is that supposed to be the normal installing process for this software?!?
becaus im more of a user rather than a Hacker. Normally I just drag
the apps from a .dmg to the App folder you know.

i may need someone to do this for me.. i hope there are some guys at
school that understand your description better than me.
Terminal is dangerous and 3D Printing is not worth losing my HD.

But thanks anyway.
Greetings
Yvo W.

2012/4/19 Ferdi
reply@reply.github.com:

**Comment by fuegas** [comment]
That is the current (development) procedure unfortunately...
I'm looking into making .app for Cura, but that isn't ready yet.

**Comment by daid** [comment]
Sadly, the MacOS version is currently quite hard to get running. And so far most Mac users have been running the Windows version in Parallels.

It is possible to get running as Pyro explained. However, I've seen a case where the above did not work.

A Cura.app is on our radar, but we haven't got it to work yet. But we have been moving pretty fast, a month ago the MacOS version was still crashing a lot.

**Comment by yzorgone** [comment]
Awesome. i definitively go for it when that has been solved.

2012/4/19 daid <
reply@reply.github.com

**Comment by jgeerds-zz** [comment]
a working app for OS X would be great, since I also have not been able to get cura working under 10.6.8 (problems with different python installs (2.6/2.7), 32 vs 64bit etc etc). Kliment has claimed that SF can't be compiled under OS X, but his printrun (http://koti.kapsi.fi/%7Ekliment/printrun/) works (almost) fantastic. when you are working on an OS X app version, please consider drag&drop capabilities (at least the dock icon and finder file association).

**Comment by yzorgone** [comment]
I can do most of the steps but  fail the last step all the time.

Set program starter to main directory

```
From main directory cp scripts/osx64/cura.sh .
Set execute rights chmod u+x cura.sh
```

Start Cura by running ./cura.sh 

---

heres what my terminal says:
Yvos-Macbookpro:~ yvowaldmeier$ chmod u+x cura.sh
chmod: cura.sh: No such file or directory
Yvos-Macbookpro:~ yvowaldmeier$ ./cura.sh
-bash: ./cura.sh: No such file or directory
Yvos-Macbookpro:~ yvowaldmeier$

**Comment by fuegas** [comment]
Where did you copy the cura.sh to?

> From main directory cp scripts/osx64/cura.sh .

This should force the shell script to be moved to the main dir of Cura.
I'm a bit curious to the terminal lines before what you posted.

**Comment by yzorgone** [comment]
i didnt copy cura.sh anywhere..

**Comment by fuegas** [comment]
Why do you expect it to work if you skip a step from the guide I wrote?
It clearly states:

> Set program starter to main directory
> From main directory cp scripts/osx64/cura.sh .
> Set execute rights chmod u+x cura.sh

If you don't copy cura.sh, you cannot set its permissions or run it...

**Comment by yzorgone** [comment]
I just never did a "Set starter to main directory"...
i dont know how to do this.

**Comment by fuegas** [comment]
I advise you to use RC3 then :)
The RC releases have the files at the right location, so you only need to run ./cura.sh

**Comment by RedwoodForest** [comment]
There's an .app in the latest version. Should this be marked as fixed?

**Comment by daid** [comment]
It can be marked as fixed. But, "proper" is not really the kind of .app we have right now. We are working on a proper .app, that much I can tell you :-)
