### ISSUE TITLE
wrong print speed brim

### ISSUE THREAD

**Issue by TheTesla** [daid/LegacyCura#660]
If I select brim as Platform adhesion type, the bottom layer print speed is always used for structures are not on bottom layer, but starting at bottom layer. The normal print speed is only used for structures overhanging.

Cura 13.11.2, Windows 7 prof. 64 bit, Luna mendel v0.20 marlin firmware

**Comment by daid** [comment]
I'm not sure if I understand you correctly, can you explain a bit better, maybe with an example, which speeds you configured and which speeds you expect where?

**Comment by TheTesla** [comment]
If parts start on the bottom and brim is plattform adhesion type, so the bottom layers are printed with bottom layer speed. After that parts are high enough, it should switch to "print speed". But the parts are printed "bottom layer speed", which is wrong. The parts not starting at the bottom are printed with "print speed", whick is right.

Am 13.12.2013 15:14, schrieb daid:

**Comment by daid** [comment]
Still not sure if I understand you. But, as this is related to printing speed, are you sure it's not the minimal layer-time kicking in?

**Comment by TheTesla** [comment]
Oh yes, this is possible.

Am 13.12.2013 16:02, schrieb daid:
