### ISSUE TITLE
Waiting for reaching temperature 

### ISSUE THREAD

**Issue by phoenixcatdog** [daid/LegacyCura#661]
There is a problem with Cura when I set my printrbot to print, it is very normal to realize that the print is going to go wrong so you click the "cancel print" while the heatbed is heating and Cura does not respond. It could take half an hour or more to respond.

If it crashes, like it could you could not reconnect as it says "connection closed". Meanwhile you can use Pronterface to connect and you see that the temperature is rising so in fact the print has not been canceled.

It looks like cura gives the order "reach this temperature" an then the printer is completely autistic while doing what was told to do, not responding to any command.

Suggested behavior: Please split big temperature changes in small increments commands in order to cancel printing fast. Instead of having to reach, I don't know 110 degrees, it could be sliced in commands "please reach 30 degrees", then "reach 40 degrees", and so on, so you only have to wait for this small increment.

**Comment by daid** [comment]
The problem is in the M109 and M190 commands, which are send to the firmware and cannot be aborted.

**Comment by peteruithoven** [comment]
You can't abort this by sending another command right away (instead of waiting for the ok and then sending the next command)?

**Comment by daid** [comment]
Nope, as the new command won't be processed until the M109/M190 is finished. A solution would be to handle the M109/M190 in the host instead of the firmware. And send a M104/M140 instead.

**Comment by peteruithoven** [comment]
Interesting, that's good to know. Octoprint and Doodle3D suffer the same issue. 

If I'd like to see this in the firmware, where would I post the issue? https://github.com/ErikZalm/Marlin/issues ?

**Comment by ahmetcemturan** [comment]
It could take half an hour or more to respond.????
Assume You cancelled the print, it will take half an hour again with your corrected print...  Just wait until it heats up and cancels the print.   Then You can run Your new G-Code with the already heated printbed.  You dont have to wait that long...

**Comment by peteruithoven** [comment]
@daid, Joris came up with the fact that the Ulticontroller can tweak the setting while it's heating... When you for example start a print (which includes a heat to 220 gcode) you can change the target temperature to something else while it's heating. How come the controller can override the heating command?

**Comment by daid** [comment]
Because the controller is still running, but the GCode parser is not.

**Comment by rooiejoris** [comment]
Maybe not for Cura interesting, but for the ulti controller it would also be nice to be able to stop during a heatup/m109 command. Maybe set the target temp to current temp at that moment, or is it easier to stop in a different way...?!
