### ISSUE TITLE
YouMagine window/dialog cannot be closed

### ISSUE THREAD

**Issue by hroncok** [daid/LegacyCura#663]
Steps to reproduce:
1. Remove ~/.cura
2. Share something on YouMagine
3. Do not add the token and try to close the window

Actual result: Nothing happens

Desired result: The dialog is closed

Can reproduce with current SteamEngine branch as well as with 13.11.2 and 13.10.

**Comment by daid** [comment]
Mac/Windows/Linux?

**Comment by hroncok** [comment]
Sorry, Linux.

**Comment by daid** [comment]
Might be a linux specific problem, and could be related to #662, as I could not reproduce it on windows.

**Comment by nallath** [comment]
This was fixed by me some time ago.
