### ISSUE TITLE
Cura stops printing randomly mostly on first layer, but mostly not with smaller objects

### ISSUE THREAD

**Issue by ooxtcoo** [daid/LegacyCura#664]
since 2 days, cura randomly stop printing.
the hotend and hotbend is still on, when i press "pause" and then "resume" it runs
for just a second and again stops.

but before, i printed many hours with it without problems.

when i load object into cura, save it as gcode and load gcode into pronterface, it 
prints without any problem till end.

the mistery is, now its doing the same with my windows 7 mashine...
no matter if i use windows xp on my laptop or the windows 7 mashine... it always stops printing...

first i tought my controller board is demaged, i thinked its a stepper motor driver problem, but with pronterface all is working, even very big objects prints till end.
and in cura manual control is also working... i can drive any axis for many minutes
without problem in cuda, but like i written, when it prints the first layer, it always
stop, but not always on same position.

i checked my printer and there seems to be no problem with the printer itself.

and it doing this only since the last 2 days.

this are the last errors from output.txt

> > Loading # from disk...
> > Reading mesh from binary blob with 16308 vertexes
> > Loaded from disk in 0.016s
> > Analyzing and optimizing model...
> > Face counts: 5436 -> 5402 99.4%
> > Vertex counts: 16308 -> 2669 16.4%
> > Optimize model 0.016s
> > Slicing model...
> > Sliced model in 0.062s
> > Generating support map...
> > Generating layer parts...
> > Generated layer parts in 0.031s
> > Generated inset in 0.188s
> > Generated up/down skin in 0.578s
> > Loading # from disk...
> > Reading mesh from binary blob with 6456 vertexes
> > Loaded from disk in -0.000s
> > Analyzing and optimizing model...
> > Face counts: 2152 -> 2152 100.0%
> > Vertex counts: 6456 -> 984 15.2%
> > Optimize model -0.000s
> > Slicing model...
> > Sliced model in 0.031s
> > Generating support map...
> > Generating layer parts...
> > Generated layer parts in 0.016s
> > Generated inset in 0.078s
> > Generated up/down skin in 0.312s
> > Loading # from disk...
> > Reading mesh from binary blob with 780 vertexes
> > Loaded from disk in -0.000s
> > Analyzing and optimizing model...
> > Loading # from disk...
> > Reading mesh from binary blob with 2304 vertexes
> > Loaded from disk in -0.000s
> > Analyzing and optimizing model...
> > Face counts: 768 -> 756 98.4%
> > Vertex counts: 2304 -> 372 16.1%
> > Optimize model -0.000s
> > Slicing model...
> > Sliced model in 0.032s
> > Generating support map...
> > Generating layer parts...
> > Generated layer parts in 0.015s
> > Generated inset in 0.110s
> > Loading # from disk...
> > Reading mesh from binary blob with 2304 vertexes
> > Loaded from disk in -0.000s
> > Analyzing and optimizing model...
> > Face counts: 768 -> 756 98.4%
> > Vertex counts: 2304 -> 372 16.1%
> > Optimize model -0.000s
> > Slicing model...
> > Sliced model in 0.032s
> > Generating support map...
> > Generating layer parts...
> > Generated layer parts in 0.015s
> > Generated inset in 0.078s
> > Generated up/down skin in 0.235s
> > Traceback (most recent call last):
> >   File "Cura\gui\sceneView.py", line 504, in _onRunSlicer
> >     self._slicer.runSlicer(self._scene)
> >   File "Cura\util\sliceEngine.py", line 124, in runSlicer
> >     for k, v in self._engineSettings(extruderCount).iteritems():
> >   File "Cura\util\sliceEngine.py", line 292, in _engineSettings
> >     settings['fanFullOnLayerNr'] = (fanFullHeight - settings['initialLayerThickness'] - 1) / settings['layerThickness'] + 1
> > ZeroDivisionError: integer division or modulo by zero
> > Loading # from disk...
> > Reading mesh from binary blob with 1272 vertexes
> > Loaded from disk in 0.000s
> > Analyzing and optimizing model...
> > Face counts: 424 -> 424 100.0%
> > Vertex counts: 1272 -> 208 16.4%
> > Optimize model 0.015s
> > Slicing model...
> > Sliced model in 0.047s
> > Generating support map...
> > Generating layer parts...
> > Generated layer parts in 0.016s
> > Generated inset in 0.109s
> > Generated up/down skin in 0.344s
> > Closing down
> > Closing down
> > Exception in thread Thread-5:
> > Traceback (most recent call last):
> >  File "C:\Programme\Cura_13.11.2\python\lib\threading.py", line 552, in __bootstrap_inner
> >    self.run()
> >  File "C:\Programme\Cura_13.11.2\python\lib\threading.py", line 505, in run
> >    self.__target(_self.__args, *_self.__kwargs)
> >  File "Cura\util\machineCom.py", line 354, in _monitor
> >    self._bedTemp = float(re.search("[0-9.]*", line.split(' B:')[1]).group(0))
> > ValueError: could not convert string to float:
> > 
> > Exception in thread Thread-7:
> > Traceback (most recent call last):
> >  File "C:\Programme\Cura_13.11.2\python\lib\threading.py", line 552, in __bootstrap_inner
> >    self.run()
> >  File "C:\Programme\Cura_13.11.2\python\lib\threading.py", line 505, in run
> >    self.__target(_self.__args, *_self.__kwargs)
> >  File "Cura\util\machineCom.py", line 354, in _monitor
> >    self._bedTemp = float(re.search("[0-9.]*", line.split(' B:')[1]).group(0))
> > ValueError: could not convert string to float:
> > 
> > Exception in thread Thread-8:
> > Traceback (most recent call last):
> >  File "C:\Programme\Cura_13.11.2\python\lib\threading.py", line 552, in __bootstrap_inner
> >    self.run()
> >  File "C:\Programme\Cura_13.11.2\python\lib\threading.py", line 505, in run
> >    self.__target(_self.__args, *_self.__kwargs)
> >  File "Cura\util\machineCom.py", line 354, in _monitor
> >    self._bedTemp = float(re.search("[0-9.]*", line.split(' B:')[1]).group(0))
> > ValueError: could not convert string to float:
> > 
> > Exception in thread Thread-11:
> > Traceback (most recent call last):
> >  File "C:\Programme\Cura_13.11.2\python\lib\threading.py", line 552, in __bootstrap_inner
> >    self.run()
> >  File "C:\Programme\Cura_13.11.2\python\lib\threading.py", line 505, in run
> >    self.__target(_self.__args, *_self.__kwargs)
> >  File "Cura\util\machineCom.py", line 354, in _monitor
> >    self._bedTemp = float(re.search("[0-9.]*", line.split(' B:')[1]).group(0))
> > ValueError: could not convert string to float:
> > 
> > Closing down

**Comment by ooxtcoo** [comment]
today i thinked i solved the problem... 
i completly erased all plugins, profiles, settings and deinstalled cura and then reinstalled all again...

it printed some layers and again stopped...

after that i tryed again and it again stopped on first layer directly...  :o(

the error log:

> > Recv: ok
> > Send: N93G1 X147.45 Y71.58 E1.51942_74
> > Recv: ok
> > Send: N94G1 X147.49 Y71.66 E1.52070_71
> > Recv: ok
> > Send: N95G1 X148.63 Y74.05 E1.56078_77
> > Recv: ok
> > Send: N96G1 X148.66 Y74.12 E1.56203_67
> > Recv: ok
> > Send: N97G1 X148.70 Y74.21 E1.56348_75
> > Recv: ok
> > Send: N98G1 X148.70 Y74.22 E1.56357_73
> > Recv: ok
> > Send: N99G1 X149.72 Y76.68 E1.60388_64
> > Recv: ok
> > Send: N100G1 X149.75 Y76.75 E1.60516_123
> > Recv: ok
> > Send: N101G1 X150.64 Y79.30 E1.64606_122
> > Recv: ok
> > Send: N102G1 X150.67 Y79.38 E1.64733_117
> > Recv: ok
> > Send: N103G1 X151.44 Y81.97 E1.68823_116
> > Recv: ok
> > Send: N104G1 X151.46 Y82.06 E1.68953_124
> > Recv: ok
> > Send: N105G1 X152.09 Y84.69 E1.73048_115
> > Recv: ok
> > Send: N106G1 X152.10 Y84.77 E1.73177_122
> > Recv: ok
> > Send: N107G1 X152.59 Y87.43 E1.77267_116
> > Recv: ok
> > Send: N108G1 X152.61 Y87.51 E1.77395_127
> > Recv: ok
> > Send: N109G1 X152.96 Y90.19 E1.81486_112
> > Recv: ok
> > Send: N110G1 X152.97 Y90.27 E1.81614_125
> > Recv: ok
> > Send: M105 T0
> > Send: N111G1 X153.17 Y92.92 E1.85626_124
> > Recv: ok
> > Send: N112G1 X153.18 Y93.00 E1.85756_124
> > Recv: ok
> > Send: N113G1 X153.25 Y95.70 E1.89849_127
> > Recv: ok
> > Send: N114G1 X153.25 Y95.79 E1.89977_125
> > Recv: ok
> > Send: N115G1 X153.17 Y98.54 E1.94148_119
> > Recv: ok T:186.3 /190.0 B:70.0 /70.0 @:65
> > Send: N116G1 X153.17 Y98.63 E1.94276_126
> > Recv: ok
> > Send: N117G1 X152.96 Y101.32 E1.98367_79
> > Recv: ok
> > Send: N118G1 X152.95 Y101.41 E1.98498_64
> > Recv: ok
> > Send: N119G1 X152.59 Y104.09 E2.02591_64
> > Recv: ok
> > Send: N120G1 X152.58 Y104.17 E2.02720_76
> > Recv: Error:checksum mismatch, Last Line:116
> > Recv: Resend:117
> > Recv: ok
> > Send: N117G1 X152.96 Y101.32 E1.98367_79
> > Recv: ok
> > Send: N118G1 X152.95 Y101.41 E1.98498_64
> > Recv: ok
> > Send: N119G1 X152.59 Y104.09 E2.02591_64
> > Recv: ok
> > Send: N120G1 X152.58 Y104.17 E2.02720_76
> > Recv: ok
> > Send: N121G1 X152.08 Y106.83 E2.06810_79
> > Recv: ok
> > Send: N122G1 X152.06 Y106.91 E2.06937_69
> > Recv: ok
> > Send: N123G1 X151.43 Y109.54 E2.11030_72
> > Recv: ok
> > Send: N124G1 X151.41 Y109.62 E2.11160_76
> > Recv: ok
> > Send: N125G1 X150.64 Y112.21 E2.15251_67
> > Recv: ok
> > Send: N126G1 X150.61 Y112.29 E2.15377_72
> > Recv: ok
> > Send: N127G1 X149.73 Y114.79 E2.19392_70
> > Recv: ok
> > Send: N128G1 X149.69 Y114.87 E2.19527_75
> > Recv: ok
> > Send: N129G1 X149.66 Y114.96 E2.19672_70
> > Recv: ok
> > Send: N130G1 X148.64 Y117.41 E2.23692_67
> > Recv: ok
> > Send: N131G1 X148.60 Y117.49 E2.23821_72
> > Recv: ok
> > Send: N132G1 X147.44 Y119.93 E2.27914_72
> > Recv: ok
> > Send: N133G1 X147.40 Y120.01 E2.28045_78
> > Recv: ok
> > Send: N134G1 X146.11 Y122.38 E2.32135_73
> > Recv: ok
> > Send: N135G1 X146.07 Y122.45 E2.32263_69
> > Recv: ok
> > Send: N136G1 X144.65 Y124.76 E2.36355_70
> > Recv: ok
> > Send: N137G1 X144.60 Y124.83 E2.36483_68
> > Recv: ok
> > Send: N138G1 X143.07 Y127.05 E2.40577_75
> > Recv: ok
> > Send: N139G1 X143.02 Y127.12 E2.40706_77
> > Recv: ok
> > Send: N140G1 X141.37 Y129.26 E2.44797_66
> > Recv: ok
> > Send: N141G1 X141.32 Y129.33 E2.44925_69
> > Recv: ok
> > Send: N142G1 X139.56 Y131.38 E2.49017_76
> > Recv: ok
> > Send: N143G1 X139.51 Y131.44 E2.49143_65
> > Recv: ok
> > Send: N144G1 X137.64 Y133.41 E2.53236_67
> > Recv: ok
> > Send: N145G1 X137.58 Y133.47 E2.53366_79
> > Recv: ok
> > Send: N146G1 X135.62 Y135.32 E2.57459_76
> > Recv: ok
> > Send: N147G1 X135.56 Y135.38 E2.57588_77
> > Recv: ok
> > Send: N148G1 X133.50 Y137.13 E2.61679_65
> > Recv: ok
> > Send: N149G1 X133.43 Y137.19 E2.61809_65
> > Recv: ok
> > Send: N150G1 X131.29 Y138.83 E2.65900_71
> > Recv: ok
> > Send: N151G1 X131.22 Y138.88 E2.66029_71
> > Recv: ok
> > Send: N152G1 X128.99 Y140.41 E2.70122_75
> > Recv: ok
> > Send: N153G1 X128.92 Y140.46 E2.70250_64
> > Recv: ok
> > Send: N154G1 X126.61 Y141.87 E2.74342_79
> > Recv: ok
> > Send: N155G1 X126.54 Y141.91 E2.74469_65
> > Recv: ok
> > Send: N156G1 X124.16 Y143.19 E2.78560_64
> > Recv: ok
> > Send: N157G1 X124.09 Y143.23 E2.78688_67
> > Recv: ok
> > Send: N158G1 X121.70 Y144.37 E2.82696_79
> > Recv: ok
> > Send: N159G1 X121.62 Y144.41 E2.82821_78
> > Recv: ok
> > Send: N160G1 X121.54 Y144.44 E2.82966_70
> > Recv: ok
> > Send: N161G1 X121.53 Y144.44 E2.82975_66
> > Recv: ok
> > Send: N162G1 X119.07 Y145.46 E2.87006_64
> > Recv: ok
> > Send: N163G1 X118.99 Y145.49 E2.87134_72
> > Recv: ok
> > Send: N164G1 X116.44 Y146.39 E2.91224_64
> > Recv: ok
> > Send: N165G1 X116.36 Y146.42 E2.91352_72
> > Recv: ok
> > Send: N166G1 X113.77 Y147.18 E2.95444_65
> > Recv: ok
> > Send: N167G1 X113.69 Y147.20 E2.95574_70
> > Recv: ok
> > Send: N168G1 X111.06 Y147.83 E2.99666_71
> > Recv: ok
> > Send: N169G1 X110.97 Y147.85 E2.99795_68
> > Recv: ok
> > Send: N170G1 X108.32 Y148.34 E3.03883_69
> > Recv: ok
> > Send: N171G1 X108.24 Y148.35 E3.04009_79
> > Recv: ok
> > Send: N172G1 X108.18 Y148.36 E3.04088_73
> > Recv: ok
> > Send: N173G1 X108.25 Y149.11 E3.05234_70
> > Recv: ok
> > Send: N174G1 X108.25 Y149.40 E3.05663_67
> > Recv: ok
> > Send: N175G1 X108.15 Y150.55 E3.07413_74
> > Recv: ok
> > Send: N176G1 X108.10 Y150.83 E3.07846_75
> > Recv: ok
> > Send: N177G1 X107.80 Y151.94 E3.09595_70
> > Recv: ok
> > Send: N178G1 X107.70 Y152.21 E3.10024_76
> > Recv: ok
> > Send: N179G1 X107.22 Y153.26 E3.11771_74
> > Recv: ok
> > Send: N180G1 X107.07 Y153.50 E3.12199_73
> > Recv: ok
> > Send: N181G1 X106.41 Y154.45 E3.13950_68
> > Recv: ok
> > Send: M105 T0
> > Send: N182G1 X106.23 Y154.66 E3.14378_69
> > Recv: ok T:182.4 /190.0 B:-22.0 /70.0 @:117
> > Changing monitoring state from 'Printing' to 'Paused'
> > Changing monitoring state from 'Paused' to 'Printing'
> > Send: N183G1 X105.41 Y155.48 E3.16128_75
> > Send: N184G1 X105.19 Y155.66 E3.16556_64
> > Send: N185G1 X104.25 Y156.33 E3.18304_67
> > Send: N186G1 X104.00 Y156.47 E3.18737_64
> > Send: N187G1 X102.95 Y156.96 E3.20488_75
> > Send: N188G1 X102.69 Y157.06 E3.20913_64
> > Changing monitoring state from 'Printing' to 'Paused'
> > Changing monitoring state from 'Paused' to 'Printing'
> > Send: N189G1 X101.57 Y157.35 E3.22665_67
> > Send: N190G1 X101.29 Y157.40 E3.23098_69
> > Send: N191G1 X100.14 Y157.50 E3.24845_69
> > Send: N192G1 X99.86 Y157.50 E3.25271_112
> > Send: N193G1 X98.71 Y157.40 E3.27019_119
> > Send: N194G1 X98.43 Y157.35 E3.27452_120
> > Changing monitoring state from 'Printing' to 'Paused'
> > Changing monitoring state from 'Paused' to 'Printing'
> > Send: N195G1 X97.31 Y157.06 E3.29203_127
> > Send: N196G1 X97.05 Y156.96 E3.29629_127
> > Send: N197G1 X96.00 Y156.47 E3.31379_127
> > Send: N198G1 X95.75 Y156.33 E3.31812_116
> > Send: N199G1 X94.81 Y155.66 E3.33560_118
> > Send: N200G1 X94.59 Y155.48 E3.33989_119
> > Changing monitoring state from 'Printing' to 'Paused'
> > Changing monitoring state from 'Paused' to 'Printing'
> > Send: N201G1 X93.77 Y154.66 E3.35738_114
> > Send: N202G1 X93.59 Y154.45 E3.36167_115
> > Send: N203G1 X92.93 Y153.50 E3.37917_120
> > Send: N204G1 X92.78 Y153.26 E3.38346_122
> > Send: N205G1 X92.30 Y152.21 E3.40092_116
> > Send: N206G1 X92.20 Y151.94 E3.40522_117
> > Changing monitoring state from 'Printing' to 'Paused'
> > Changing monitoring state from 'Paused' to 'Printing'
> > Send: N207G1 X91.90 Y150.83 E3.42271_120
> > Send: N208G1 X91.85 Y150.55 E3.42703_120
> > Send: N209G1 X91.75 Y149.40 E3.44454_125
> > Send: N210G1 X91.75 Y149.11 E3.44882_118
> > Send: N211G1 X91.81 Y148.36 E3.46030_123
> > Send: N212G1 X91.66 Y148.34 E3.46271_116
> > Changing monitoring state from 'Printing' to 'Paused'
> > Changing monitoring state from 'Paused' to 'Printing'
> > Send: N213G1 X91.57 Y148.32 E3.46400_113
> > Send: N214G1 X88.92 Y147.83 E3.50490_124
> > Send: N215G1 X88.83 Y147.81 E3.50617_114
> > Send: N216G1 X86.21 Y147.18 E3.54710_117
> > Send: N217G1 X86.12 Y147.15 E3.54840_115
> > Send: N218G1 X83.53 Y146.38 E3.58931_121

**Comment by ooxtcoo** [comment]
maybe now i have a idea what happend...

dose cuda stop printing when the temp sensor of the headed bed shows wrong temp for short time?
and pronterface not?

cause with pronterface i can see, that it seems my thermistor cable is broken and sometimes for
short time, it displays -42 dagrees celsius.

maybe thats the problem...
i replace the cable tomorow, i hope that is the problem..

cause everything other i have already tryed (including firmware reflash).

**Comment by hg42** [comment]
@ooxtcoo: did you fix your problem or does it still exist?

I seem to have a similar problem, if not the same.
I am running Cura on Linux (at 115200 baud).

Today I pulled the current Cura code from github.

I wanted to print a part with about 2300 lines per layer.
The print then stopped at about the middle of the second layer.
More correctly it didn't really stop, but paused some seconds (burning a hole into the part) and then printed a line of filament, paused again and so on. I finally canceled the print.

RepetierHost can print the part from saved gcode (but I didn't finish the print due to a mechanical problem, the print went to about 10 layers without a problem).

I already had a somehow similar problem earlier in September:
issue #551 "Print window is crashing in the middle of all prints",
which I worked around by disabling all log prints and which was finally fixed by daid by limiting the number of lines in the log window.

In current Cura printWindow.py was replaced by printWindow2.py, which has borrowed the fixed part of code (in function _addTermLog) from printWindow.py.

So, currently I have no clue what could cause the problem.

I made some tests:
In September I managed to simulate a print by removing the power and by disabling both temperatures. So I could increase the print speed from 150 to 5000 which reduces testing time to seconds instead of minutes or hours.
Now, I repeated the simulation with my current problem.
The number of lines printed until the slow down depends on the printing speed, but it's not linear dependency.
Faster speed gives fewer lines.

By the way, Cura always gave me a few errors in the log window, checksums etc. so there may be an additional problem here. But before the update I could print large parts without noticable flaws.

That's all for now, I'll try other tests if I find some time in Christmas preparations.

**Comment by ooxtcoo** [comment]
yes, i fixed it ;)

by watching the graph window with the hotend and heatbed temps, i found that for very short time,
my temp sensor read -43 dagrees celcius, because one wire was broken but still had contact and only
on one position it had no contact for short time.
this cause cura to pause and pause again and again...

**Comment by ooxtcoo** [comment]
but you can say... if it one time goto pause because of this error, it seems it dont clear a flag, because
even when temps back to normal, when i press resume, it starts one line and again pause..
so if you fix the cable while its running, you need to restart the whole print, because after 1 break it always
auto pause itself after one line..

i programming also some tools (but more with cracking/unlocking phones), and it looks like there should be a flag reset after pressing resume.
it looks like, some error flag is triggered and when pressing resume, the flag is not reset and thats why it
stops again.

thats why i like open source software, if something is not working, we can look at it ourself..

**Comment by hg42** [comment]
ok, so it's a different problem than mine.

In my case the printing window never goes into pause mode. Instead it waits some seconds and then prints the next line.

**Comment by hg42** [comment]
I moved my problem to a new issue, so I think this one can be closed.
