### ISSUE TITLE
Unable to load a STL file into CURA

### ISSUE THREAD

**Issue by geofftrott** [daid/LegacyCura#665]
The part in the file is  a very simple model  for my Ultimaker 2 which I am just getting going.  The STL originated in Alibre or what is now called Geomagic, http://www.alibre.com/

**Comment by maybites** [comment]
I can confirm the same issue in Cura 13.12 with STL's exported from blender 2.69. The STL's work fine in cura 13.11.2

**Comment by nallath** [comment]
If there is a problem with a specific model, please link to the model. See https://github.com/daid/Cura/wiki/Issue-policies
