### ISSUE TITLE
Feature request: Key up/down/left/right doesn't work in layers-view

### ISSUE THREAD

**Issue by j0uni** [daid/LegacyCura#669]
The keypad-feature is great. Hopefully it will work someday in the layers-window. Now it doesn't. 

Mac 10.8.5. Cura 13.12.

**Comment by daid** [comment]
Right now the keys change the layers, so there are some conflicts there, not sure how to solve it yet.

**Comment by nallath** [comment]
Shift keypress changes the layers, keys change the viewpoint.
