### ISSUE TITLE
13.12 broken on Linux

### ISSUE THREAD

**Issue by mkubik** [daid/LegacyCura#670]
After install (clean or upgrade, doesn't matter) I get this on the command line:

mk@w500:~/Downloads$ cura
Traceback (most recent call last):
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 202, in _watchProcess
    self._process = self._runSliceProcess(commandList)
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 372, in _runSliceProcess
    return subprocess.Popen(cmdList, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

No slicing occurs and consequently, no gcode can be saved.
Went back to 13.11.2.

I checked /usr/lib/python2.7/subprocess.py and it's not marked executable. I made it executable but that didn't help.

**Comment by wdl1908** [comment]
Cura-13.12-debian.deb

The CuraEngine is compiled for 64 bit and can't be executed on 32 bit systems.

$ file /usr/share/cura/CuraEngine 
/usr/share/cura/CuraEngine: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.24, BuildID[sha1]=0x7f2828a960992c9fde0531043ff75efacb2c0dac, not stripped

Please distribute a 32 bit compiled version.

**Comment by mkubik** [comment]
Hm, apparently, there's no precompiled 32-bit version. If this was changed with 13-12, why is it not renamed to Cura-13.12-x64-debian.deb? The previous version also didn't have 32bit or 64bit in its name, therefore, please either fix the naming or re-compile in 32-bit.

**Comment by daid** [comment]
Noted. We used a new machine to build this Cura release. Which is what is causing the problem.

We're going to automate the builds to prevent this problem from now on.

**Comment by mkubik** [comment]
Thanks!
