### ISSUE TITLE
Use lower density for support not touching model

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#672]
From https://groups.google.com/forum/#!topic/ultimaker/zNY9tBQWnQ0

One wish in regards to this - it is no reason to have the support the same density all the way through. Since one can easily bridge 10mm - why not make the support less dense until you reach 6-8 layers before the part that is to be supported? That would save tons of time and filament. Kisslicer does something like this.

**Comment by pwnate** [comment]
I was thinking of this for dual extrusion with dissolvable support. Right now if you want something fully supported with dissolvable support you have to have 100% support for the entire thing, which is obviously a huge waste of material.

**Comment by nallath** [comment]
Better support material is definately on the roadmap. However; we will be focussing on a complete GUI (and architecture overhaul). The first bits of that can be seen in the PinkUnicorn branch (with a awesome new splashscreen!)
