### ISSUE TITLE
Checksum Mismatch in Cura

### ISSUE THREAD

**Issue by kaushikwavhal** [daid/LegacyCura#674]
I am getting a checksum mismatch error in my prints and my prints stop suddenly halfway. What might be the problem?

**Comment by daid** [comment]
checksum mismatches are corrected (I should supress that message)

A sudden stop is odd, does the printing dialog go into an error state?

**Comment by kaushikwavhal** [comment]
This are some last lines from the error log/Machine log window

Send: N247G1 X139.93 Y67.51 E6.64102_112
Recv: ok
Send: N248G1 X140.64 Y68.66 E6.66016_116
Recv: ok
Send: N249G1 X140.97 Y69.31 E6.67035*122
Recv: Error:checksum misoatch, Last Line: 245
Changing monitoring state from 'Printing' to 'Error: checksum misoatch, L...'
Recv: Resend: 246
Recv: ok
Recv: Error:No Line Number with checksum, Last Line: 245

**Comment by daid** [comment]
Yes, noticed the problem and fixed it. There is a typo or communication error in "checksum mismatch" (misoatch). I've made the "going into error state" less agressive so it continues even with an error like that.

**Comment by daid** [comment]
Planning a new release very soon. As I also need to release a new firmware for the Ultimaker2

**Comment by kaushikwavhal** [comment]
Great

**Comment by hg42** [comment]
please see also pull request #698
