### ISSUE TITLE
showing current printing height in gcode view (also fixes printWindow communication)

### ISSUE THREAD

**Issue by hg42** [daid/LegacyCura#679]
I have some tested patches in my queue, which I want to add as combined pull request when my current Mercurial patches are accepted.

The printing position is shown in gcode view by setting the layer range to the current layer. In other views the yellow plane is shown (which didn't work here on linux).

To make this possible, the patches also fix the communication between printWindow and sceneView which didn't work at least here on linux, because stdout is buffered.

Daid, how should I handle multiple dependent patches? should I create a single pull request or is it better to create multiple requests (which seem to include all dependent requests, too)?
I am asking because waiting for each single patch to be accepted appears to be a little bit slow...

**Comment by hg42** [comment]
to accelerate this "issue" I already created some dependent pull requests...

**Comment by hg42** [comment]
btw. I notice I seem to be the only one using branch names for pull requests.
May be I shouldn't use them?

**Comment by daid** [comment]
Not sure what the proper way is to handle them in git. Currently development on Cura is not complex and big enough to setup complex rules for pull requests, so even multiple changes in a single pull is quite fine. I can always revert stuff I do not like.

I'll have to double check if the re-opening of stdout is not a problem on Windows and MacOS, but the rest of the patches I have no problem with.

**Comment by hg42** [comment]
did the yellow plane work for you on any OS before using my patches? for me on linux it did not. If other OSs worked before, you could unbuffer stdout in linux only.

I originally searched for making python stdout unbuffered like $stdout.sync=1 does in ruby. The reopening was the only suggested simple solution for this. Another suggested way was to flush after each print (I can provide this as a working patch too). stdout-print could also be encapsulated by a function or may be a class to flush after every call.

But I assume (without verification), that this kind of reopen doesn't happen on low level system level but on python-lib level because the same low level fileno is used. E.g. I am quite sure it's never closed this way. Perhaps some pythonists could check this?

**Comment by daid** [comment]
The plane worked on MacOS before the patch. But the patch didn't seem to break anything else so that's good.
