### ISSUE TITLE
solid layer covers holes

### ISSUE THREAD

**Issue by Huwyler** [daid/LegacyCura#682]
I have a model which is something like a cup with holes in the bottom. Cura puts correctly creates the top layers of the bottom of the cup, but then puts two solid layers on top of them, covering the holes. See the picture.

![image](https://f.cloud.github.com/assets/4663494/1845891/becb3d66-75ae-11e3-90b2-3cd591a3ea7e.png)

**Comment by daid** [comment]
Can you share the 3D model and settings used? (tool->copy profile to clipboard, paste it)

**Comment by Huwyler** [comment]
Of course.... shouldn't be worth mentioning... sorry!

CURA_PROFILE_STRING:eNrtV8Fu20YQvRJCP2KOKRqzS0qKkwi8JLV9SYIAdlHH
F2JFDsWtSS6xXFqWBP17Z3dJibLlJmlyKWAdJPFxZnZm9s1bsuArVHGOYpHriPnB
1Fvyooh1LpLbCpsm8k89hVrxRAtZxVjxeYHRlWrRa2Qh0riwAfb2zH/lZYJCpFg1
Qq+iCfMquV4XGDdijXR/PPVqJSodNzViGk1Zd6mxrFFx3SqMwvAIGkZHwPExcLID
55geBD5lXtPWtVQ6+iQr9OqC60yqMuZpjg2V6ODOJk5bXsR4r1Vr772TOveWosZY
yyWq6JwXDQ6A+E4WbYkRtVHKNVWcCyzSzoy6wkuknFJBv5rcA/80fAybMh+B42Pg
ZAhmhVxGAWM+G26Y6/HkAcpL2VY6mvjTIWqL7W4Frw7vlaKK6eIOC8r64E4iy7mo
Fo4Thx6iPOgeJRF6c6m1LA8IE3py/jcmRAhR3RorT96hKnhtM3KsdGt35QRTY9RF
cgR0N4g1orLsc9fGLJGysOl3TBW0P1Mv4z2Z047Nt4L2uxAVUkW2Ax204HU0pjju
qq+qwGqh8y4TEyxradXdHLkFumwZ21/FJb+3yC6tjFAiJ5GmA3PkNFYi0x1v3Jxp
WQ/HzhXvEFtw1zJDvZ68Fneh9+D9iujTaF4lZhZPd/h6CBv7WihemIl1WcyVKIft
oVYrnlFDuFqIijpqr6xBU/PEMCLwO5s5b/Bgx8cD3LgsRUrNNOlYnAYXVcYTfECT
BzeHnmaO7uNcKiVoT+O2sjQ3Srai4eR9o542me+mdGhD+ckaq3gudHPMgMhtZO6O
itZCJ7kp25nVRUt9oWYRHxfRi6IORn7P8wRNDfF9dBI8gFYE/ULboLS/SGSK0eyy
EAmmwPVb2KR8tTXfGunHEHk7mr3jjUigQa1p7eYtfDAsB0dEcikG+r6Fv6hcstkc
avwWzokpBA91m0J/NgoKZh2612msW/S8Ex2gBqXO0YmQU49tOYCWbu3FwCuRjR56
mWuK+jF4w+Byc1S4tzD7syKpsf5aAk9TWMlWgVxWQLYwsAVDDBOOvdmF+9ZQj8Jc
hAF0nxmJrqJm3/GixWZ0Qdn2d/icxrLVCLWk5hGxaDNGlMBpb2D3FJZC56BzBNID
kFk2ovCv4ZrBF2bC0wzD9e9fTFKkDIBV2tDYN9bohnU5GKObRyajiwBugqnP4Hwz
1Mpt52EW7c86SE2lwbQsye1NCGe7Ovaf2RqVtF5Wv1PqsJM8s9B5yBicjR94dIYw
LkuqDYyuASWX3H7/IsAXXFR2qcNqiJStBrul1GEoib18gSAr+PD+D2gShVhR34NT
+NzZ+L4/8qhN/TydVSlcvKe/ZnsmcHkkrUExZpJo3JTdrI/BhD3pYO1SS8W9C7wQ
meEW5FQDCP2raXgA3/CZKaTdImE5YBQ15OyEmjJm7CvO9hh2VOunjgOpGCVIFDDc
zmwHjYV7PHtpOEWrIokyNLJEs4mWNoq6TPNgKfYbnW2UwxSuT0Kirfk6TrgbaOtu
SU4t7zPaZYN3WEEpTdj9CPxrUU+Nx0vK1iZqDk4QDUiiSJf7kq9Go4+vJ09HbTTW
NPGN3eHBSD+2PDrjnh3s8Fmtf4JaT35crZ3oXwXHIoX/KRR7PkK+coRcPSFos8ul
eSQy6xjXkFSgV9UfOXYCdvzYCdhPPXfsWieb469HW6qafVPVmVCN/j/V/bPO2/CJ
A/eKfeeZa3yC53P6+Zz+wXO6e88dvlztwP3zoXsFPzCyyMBCIalggn7S3FEEO+1n
HQt3jwFOA+aolzQgtsKkVcr2syes6bbdVUJ26EtY5uSwGzir9mVbaFEXu6lVjd+N
uCPa+BWcTxljPXi16Q23xuB6Q6/J8f0Wvtg/9FByY/+st4+m3YR7GO0fJVaE2Q==

And here's the stl:
https://drive.google.com/file/d/0B7gVPXiIml19MXRzcjZVQnBxcUU/edit?usp=sharing

**Comment by Huwyler** [comment]
sorry for closing it.

**Comment by daid** [comment]
Issue is fixed in 14.02RC http://software.ultimaker.com/Cura_closed_beta/
