### ISSUE TITLE
Abort Filament Retraction Bug

### ISSUE THREAD

**Issue by combatraffi** [daid/LegacyCura#684]
Sometimes when I abort a print the machine retracts the filament through the bowden tube.  Sometimes its only a little once or twice it has happened where it pulled it all the way out of the tube...  This does not happen on every abort, maybe 1 in 3.  Cura 13.12 UM2 

Thanks

**Comment by daid** [comment]
Yes, the UM2 13.12 firmware has a bug like this. I've an updated test version at https://groups.google.com/forum/#!topic/ultimaker/tDKAHxe8rI0 that fixes it, which will be released shortly.
