### ISSUE TITLE
brim fills up holes

### ISSUE THREAD

**Issue by Huwyler** [daid/LegacyCura#685]
Small holes are "stuffed" by a brim. I think they shouldn't. Maybe on "inner" perimeters the brim should be avoided if the perimeter is less than xxx mm long.

![image](https://f.cloud.github.com/assets/4663494/1846388/a0024d4a-75f2-11e3-872f-3bf7d5534d8a.png)

CURA_PROFILE_STRING:eNrtV1Fv2zYQfhWM/Yh77LBGo2S7aWvopV2Sl7YokAxL
8yLQ0sniIokCRcWxDf/3HUnJlhNnbde+DIgfbPN4d7w7fvedVPAVqjhHsch1xPxg
6i15UcQ6F8lthU0T+aeeQq14ooWsYqz4vMDoSrXoNbIQaVxYB3t95r/yMkEuUqwa
oVfRhHmVXK8LjBuxRtofT71aiUrHTY2YRlPWLTWWNSquW4VRGB6RhtER4fiYcLIT
zjE9cHzKvKata6l09ElW6NUF15lUZczTHBtKMXqnRNnrxGnLixjvtWrdntS5txQ1
xlouUUXnvGhwIIjvZNGWGFEZpVxTxrnAIu3UqCq8RIopFfSryTzwT8PHYpPmI+H4
mHAyFGaFXEYBYz4bXpir8eSBlJeyrXQ08adDqU222wpeHe6VooppcYcFRX2wk8hy
LqqFw8ShhSgPqkdBhN5cai3LA8CEnpz/jQkBQlS3RsuTd6gKXtuIHCrd2V06wdQo
dZ4cAN0GoUZUFn1ubdQSKQsbfodUQfcz9TLegznt0Hwr6L4LUSFlZCvQiRa8jsbk
x636rAqsFjrvIjHOspZO3fWRO6CLlrH9Ki75vZXswspISuAk0HTCHDm1lch0hxvX
Z1rWw7ZzyTuJTbgrmYFeD14rd673wvsVwafRvEpML57u5Ouh2OjXQvHCdKyLYk5t
MSwPlVrxjArC1UJUVFG7sgpNzRODiMDvdOa8wYMbHw/kxmQpUiqmCcfKqXFRZTzB
BzB5sDm0NH10H+dSKUF3GreVhblhshU1J+8L9bTKfNelQx2KT9ZYxXOhm2MKBG5D
c3eUtBY6yU3aTq0uWqoLFYvwuIheFHUw8nucJ2hyiO+jk+CBaEWiX+galPYXiUwx
ml0WIsEUuH4Lm5SvtuZbI/0YIG9Hs3e8EQk0qDWd3byFDwbl4IBIJsWA37fwF6VL
OptDjt/COSGFxEPeJtefDYOCOYf2Oo51h553pANUoNQZOhJy7LEtB6KlO3sxsEpk
o4dWZk1ePwZvGFxujhL3FmZ/VkQ11l5L4GkKK9kqkMsKSBcGumCAYdyxNzt33+rq
kZuLMIDuMyPSVVTsO1602IwuKNp+h8+pLVuNUEsqHgGLLmNEAZz2CvZOYSl0DjpH
ID4AmWUjcv8arhl8YcY99TBc//7FBEXMAFilDbV9Y5VuWBeDUbp5pDK6COAmmPoM
zjdDrtx2FubQftZBajINpmVJZm9CONvlsf/M1qiktbL8nVKFHeWZg85DxuBs/MCi
U4RxWVJuYHgNKLjk9vsPAb7gorJHHWZDoGw12CulCkNJ6OULBFnBh/d/QJMoxIrq
HpzC507H9/2RR2Xq++msSuHiPf011zOByyNhDZIxnUTtpuxlfQwm7EkDq5daKO5N
4IXIDLYgpxxA6F9NwQP4hs9MId0WEcsBoqggZydUlDFjXzG2Y9hBre86DsRiFCBB
wGA7sxU0Gu7x7KXBFJ2KRMrQyBLNJVrYKKoy9YOF2G802yiGKVyfhARb83UccDfQ
1t2RnEreR7SLBu+wglIat/sW+NeknmqPlxStDdQMThANSIJIF/uSr0ajj68nT3tt
NNbU8Y294UFLP9Y82uOebezwma1/AltPfpytHelfBcc8hf/JFXseIV8ZIVdPENrs
cmkeicw5xjQkFuhZ9UfGTsCOj52A/dS5Y8862Rx/PdpS1uybss6EavT/Ke+fNW/D
JwbuFfvOmWtsguc5/Tynf3BOd++5w5ernXD/fOhewQ+UrGSgoZBYMEE/ae7Ig+32
sw6Fu8cAxwFz1EtqEJth0ipl69kD1lTb3ipJdtKXsMzJYNdwlu3LttCiLnZdqxq/
a3EHtPErOJ8yxnrh1aZX3BqF6w29Jsf3W/hi/9BDyY39s94+6nbj7qG3fwCy1oTT

The stl:
https://drive.google.com/file/d/0B7gVPXiIml19MXRzcjZVQnBxcUU/edit?usp=sharing

**Comment by daid** [comment]
Good idea, isn't that complex to add.
