### ISSUE TITLE
Repetier print stops early

### ISSUE THREAD

**Issue by hg42** [daid/LegacyCura#688]
After solving the connection issue (Repetier sends "wait" when idle) I got additional problems with Repetier, so the print stops early.

My current problem:

Cura skipped a line number, but Repetier wants them in seqeuence, resulting in Resend messages.
E.g. Cura sends lines 1,2,3,5,6,7,... (missing 4), which causes Repetier to want line 4, sending "Resend:4" messages, but Cura doesn't respond to this. Looks like line 4 doesn't exist.

There are certainly more differences between Repetier and Marlin.
E.g. Repetier Error messages don't start with "Error:",
"ok" comes as "ok <line_number>" (no problem but ignored), etc.

Currently, I am not sure if Repetier is really better than Marlin, so may be it's not worth to fix Repetier communication.
Some things seem to be cleaner, but I am missing the recent M666 command of Marlin, which is very convenient to calibrate Delta towers (end switch height) without using the screws.

**Comment by daid** [comment]
Defenitly worthwhile to know how Repetier communicates. "Resend:4" should result in a resend with N4 line after that. But "Resend:4 error" will not work.

(Note that there is some buffering and so you will most likely see a few extra messages before the resend, like this: 1,2,3,-,5,6,7,8,4)

**Comment by daid** [comment]
I've updated some of the USB communication code to also fix some issues I was seeing with an ARM based printer. These changes might help with the Repetier communication.
