### ISSUE TITLE
Minor: shell thickness unexected impact with multiple objects on bed (v. 13.11.2)

### ISSUE THREAD

**Issue by MoonCactus** [daid/LegacyCura#689]
Could not test with newest version (b/c linux 32 bit)

According to the shell thickness, Cura probably considers that my object is bigger! There is room for 3 copies on the bed. With a shell thickness of 0.36 (I know, weird value!), the objects are printed one after each other. But when I set the shell thickness to 1.36 for example Cura wants to print them all in parallel. With bigger values it comes back as separate prints, weird!

I have posted a ~1MB archive that includes the STL and the two g-code files (for the profiles): http://some.bitzof.me/cura_13_11_2_shellthicknessimpact_bug.tgz
I'll keep them there for a while

**Comment by daid** [comment]
Most likely what is happening, the shell-thickness changes the width of the skirt lines, which causes the "head" area to become slightly bigger and so your "current" configuration of objects suddenly slightly overlaps. Which causes the "print order" detection to fail and if that fails it does an "all at once" print.
If you would move 1 objects a tiny bit after selecting 0.36 it will most likely push all the objects slightly apart and print "one at a time" again

13.12 uses slightly more fuzzy collision code which is less likely to show this issue. 14.01 will feature manual switching between the two modes.

**Comment by MoonCactus** [comment]
I would agree but I remember that even bigger shell thickness values sometimes sent it back to the expected "separated" behavior.
Also, why would the skirt lines depend on shell thickness in the first place?
Cura may trigger a new auto placement of the objects on the platform automatically after the shell thickness changes if and only if the user did not move any of them manually.
No biggie anyway and +1 how reactive you are! :)

**Comment by daid** [comment]
The line-width depends on the shell-thickness, as the line-width is kept the same for all lines (improves quality) the skirt lines also change width.
