### ISSUE TITLE
Cura 13.12 support not generated (screencapture)

### ISSUE THREAD

**Issue by ryl3nz** [daid/LegacyCura#691]
![prob normal](https://f.cloud.github.com/assets/6337983/1857741/09498c46-777e-11e3-91d5-078b126eccfa.png)

![prob](https://f.cloud.github.com/assets/6337983/1857742/0fc9af42-777e-11e3-8f60-df77525d6e92.png)

Big:
Top diameter 50
Pole diameter 10

Small:
Top diameter 13.5
Pole diameter 10.5

Why support isnt generated for the smaller object? I tried similar small object with slic3r and it didnt generate the support too.

**Comment by daid** [comment]
Because support smaller then a certain amount is not generated. this is intentional, as the support would be too close to the model or too small to print properly without breaking.

**Comment by ryl3nz** [comment]
Ic..thanks:)
