### ISSUE TITLE
Locate Problem  Cura 13.12 or Opencad

### ISSUE THREAD

**Issue by jimweirwolf** [daid/LegacyCura#692]
Openscad produced "stl" slices in Cura 13.12 with some holes filled in.  If I change ti Cura 13.06 then slices and prints as I expect.

How do I check if it's a Cura13.12 or and Openscad "feature"?

**Comment by daid** [comment]
It's a combination. OpenSCAD produces files with wrong face normals. Cura 13.12 has "Fix horrible type A" in the expert options enabled by default, this causes this problem.

I should detect if you have an OpenSCAD model and then override this option, as it is never needed for OpenSCAD models.

**Comment by jimweirwolf** [comment]
Disabled "Fix type A" and resiilced.  Prints as I expected.. Thanks.  Should I leave option deselected?  Most files I use are produced using Openscad, or just disable the option if problem shows up?

Thanks for help

**Comment by daid** [comment]
If you are using OpenSCAD you can leave the option disabled. The option is to fix self-intersecting models. Which OpenSCAD cannot produce.
