### ISSUE TITLE
Fix quickprint settings

### ISSUE THREAD

**Issue by illuminarti** [daid/LegacyCura#694]
The quickprint settings seem to be far from optimal - especially for the UM2. 

For a start, it looks like none of the quickprint settings have retraction enabled, which just seems bizarre to me.

Secondly, the Fast mode has a shell thickness of 1mm, which increases the effective nozzle diameter to 0.5mm, and at its 0.2mm layer height, and 60mm/s speed, that equates to 6mm³/s which seems like it might be a bit on the high side for some folks - at least at the default temperature setting, on a UM2?

(Aside: it might be worth thinking about how to implement a 'print this hotter than usual' option, now that the temp control itself is on the printer, not in Cura, so these fastprint settings lose control over temperature).

Tbh, for the UM2, the 'normal' setting of 0.1mm layers should be pretty good; I'm not sure that for most things it's necessary to go much down below 0.1mm layers; perhaps the high quality setting should be 0.1mm layers at 30mm/s, and the normal one 0.15 at 50, or something like that. 

Finally, I still don't like naming these settings in terms of 'quality'; none of the options need be 'low quality' at all - they're fast print, standard print, and slow, fine detail. Too many users get the idea from these settings that anything over 0.1mm means 'low quality' (i.e., crap) and so avoid it, when in fact it's perfectly fine for many applications.

**Comment by daid** [comment]
Release of today has retraction enabled, so that's 1 fix. (Stupid oversight from me)
But they really need to be re-viewed, if you have "full" suggestions I wouldn't mind putting them in. But 0.1mm layers is pretty much our "normal" prints that we show everywhere, so that's why it's the normal setting.

I think your idea for the naming is indeed better.

**Comment by illuminarti** [comment]
Thanks, for the quick fix!! 

I generally use 0.1mm for everything on the UM2 - to be honest, with the results I've gotten, I'm not sure I'd ever feel compelled to go thinner than that (on a UM2). So I wonder if it's too much finesse to have that in the simple settings; if you really need a .06 layer for a model, you probably need to be tweaking things a bit more than quickprint allows for anyway.

So my thought was to have the best setting be 0.1mm, and slow (30mm/s at 0.1 was roughly I used for all my recent showpiece prints); then perhaps have the normal setting be also 0.1mm and a bit faster - or perhaps slightly thicker if we want more of a speed gain. And then the fastest setting be 0.2mm layers, and maybe higher speed again. But the biggest challenge for the UM2 would seem to be the need to increase the temp to print faster.

Do you have a sense of what a practical mm³/sec limit is for the UM2? George's testing of free-air extrusion suggested that the reliable throughput was a bit lower than for the UM1, and there have been some people reporting extruder clicking with the current 'fast' settings.

Would you have any objections to me opening a forum thread and crowdsourcing some settings for the three 'speeds' for UM1 and UM2 (I presume they can be different between the two machines?) Not that you have to use them, but it might be a nice way to get some community involvement in the process.

**Comment by hg42** [comment]
wouldn't it be better to have a file (profile) that defines the quick print, which would be loaded when using quick print?
This way everyone could configure it's own quick print profile.

Then immediately multiple quick print profiles come to mind for different situations, e.g.
- fine = high quality (slow, small layers etc.)
- draft = fast, rough (high speeds, thicker layer)
- use ABS
- use PLA

which would lead to a hierarchy of files:
- basic settings
  - ABS
    - fine
    - draft
  - PLA
    - fine
    - draft

I currently do these kinds of configurations via dropping partial profiles on cura.
E.g. I first drop a "material" profile, then a "quality" profile, then a "speed" profile onto cura

**Comment by illuminarti** [comment]
I think that the management on profiles in general could certainly be improved: for instance it would be good if you could easily see what was in the 'QuickPrint' settings, and then modify them as a starting point for further learning.  Being able to add your own settings would be great.

But I think that's a separate issue to some extent from the basic one of making sure that the quickprint settings work well for the newbie audience.  Increasingly, new users are trying them, and not getting very good results and quickly becoming disappointed with their shiny, expensive, new printer.

**Comment by nallath** [comment]
It almost sounds like a mantra; but this is going to be adressed in the GUI overhaul.
