### ISSUE TITLE
cura armhf

### ISSUE THREAD

**Issue by marvinstuart** [daid/LegacyCura#696]
About two months ago I was able to install cura on a armhf , I am running armv7 now I can install has there been changes , 

When I do below 
sudo dpkg -i ./scripts/linux/Cura*.deb

I get an error re the not for armhf

**Comment by daid** [comment]
You'll have to change the architecture in the DEBIAN/Control file, it used to be "all" which was wrong for the package I release (Ubuntu was complaining about it)
