### ISSUE TITLE
Minor: Skirt also inside ring-shaped objects

### ISSUE THREAD

**Issue by mpatoulachik** [daid/LegacyCura#697]
When printing object with hollow or ring-shaped bottom layer, Cura prints a skirt outside the object but also inside the "ring".

The aim with the skirt (if I get it right) is to prime the nozzle and give some possibility to adjust manually Z-height. This inside part of the skirt is not necessary, it just consumes time and filament.

**Comment by daid** [comment]
The skirt code is also used for the brim, and you do want brim on the inside to keep the object on the platform. Note, the latest code ignores very small inner skirts, so it won't fill up holes with a full brim which is then impossible to remove.
