### ISSUE TITLE
Feature: permanent warning icon when a plugin is in use

### ISSUE THREAD

**Issue by MoonCactus** [daid/LegacyCura#700]
Ir happens to me regularly when I use a plugin such as wood that I leave it activated. When I start Cura days later I completely forget about it and I do not go and check the plugin tab, and that ruins the print...
It would be nice to have a warning icon near the youmagine icon (eg.) that indicates that a plugin is currently being applied

**Comment by daid** [comment]
Nice idea. Shouldn't be too difficult, but I do need a nice icon for it... but maybe I can re-use the older "gears" icon that is no longer used...

**Comment by MoonCactus** [comment]
An icon of a plug would make it clearer probably, but I agree the gear would be enough, esp. if it features a hint box indicating the currently active plugins imho.

**Comment by nallath** [comment]
This will be adressed in the GUI overhaul.
