### ISSUE TITLE
Gaps in models when slicing

### ISSUE THREAD

**Issue by gkeeley** [daid/LegacyCura#701]
When slicing models above a certain size gaps show in the slicer layers preview. Is the model going to print correctly or will it stop printing when it encounters the gaps??

**Comment by daid** [comment]
It will print what it shows in the layer view. Most likely the model contains some kind of gaps and Cura cannot properly decide what is in/out on every layer causing the gaps.

The X-Ray view helps in this case, as it shows holes in red with some rendering tricks.
