### ISSUE TITLE
Start/End gcode does not change with selected machine after adding a MakerBot machine in Cura 14.01

### ISSUE THREAD

**Issue by YoChu** [daid/LegacyCura#702]
Hi Daid, I noticed that after adding a MakerBot machine through the first run wizard, its Start/End gcode would not change when selecting back to an Ultimaker or RepRap machine. Reseting the profile to default or going through the first run wizard does not change it either. The only way to change it was to load a profile from gcode or ini file, or by editing it manually. 

I'm running the OSX version, and even after replacing with a clean copy of Cura 14.01 from my Applications folder, it loads up the MakerBot gcode.

**Comment by daid** [comment]
The prefereces are stored in ~/.cura so even a reinstall will keep the same preferences.

The Start/end GCode is currently shared between all machines. I'm planning to change this and have a profile per machine. (Reset profile to default should work in getting the default back, but I do not think it will load the Makerbot specific seettings)

**Comment by randomev** [comment]
We have this same issue, we have 3 different printers each connected with a Doodle3D box and would like to have a machine specific start- and end-codes. Now we need to manually edit some parts of end and start codes when we print with different printers.

Also same thing with filament width - we have different filaments in each machine so for now we need to manually change them and remember which machine has which filament. It would be great if filament type could be also machine specific thing.

**Comment by nallath** [comment]
These issues will be adressed with the GUI overhaul.

**Comment by daid** [comment]
(And fixed in the 14.02-RC? http://software.ultimaker.com/Cura_closed_beta/ )
