### ISSUE TITLE
Printing window's Term tab text almost unreadable on OS X

### ISSUE THREAD

**Issue by fns** [daid/LegacyCura#703]
![screen shot 2014-01-15 at 09 07 26](https://f.cloud.github.com/assets/105880/1918401/ce9f2732-7dbc-11e3-85e9-f126e51ba74f.png)

**Comment by hyuntoe** [comment]
mine, too.

**Comment by perlguy99** [comment]
Mine was too. I've attached a screenshot.

Also, where did the controls go for the machine?  I don't see anything where I can control the X, Y, Z axis' via the computer.

![cura_14 03_screen](https://f.cloud.github.com/assets/878935/2455126/5a6e6fb8-aef8-11e3-818e-f59933194281.png)

**Comment by hyuntoe** [comment]
connect the printer to pc,
load a model file,
click print button at the upper left corner of right side panel(3D view) 
[load] [print] [blah]
..
a new control panel will be appear.
.
see the right-side panel,
.
at the first tab, you can set the temp. ( nozzle and heat-bed )
at the second tab, you can move the printer's head ( x y z )
at the third tab, you can control the speed of printing ( I don't use )
at the fourth tab, you can send g-code to printer directly.
.

나의 iPhone에서 보냄
1. 3. 19. 오전 8:53 Brent Michalski notifications@github.com 작성:

**Comment by perlguy99** [comment]
I see the new panel that pops up, however - it is not readable and there are no tabs.

See the attached screenshot...

![cura_screenshot2](https://f.cloud.github.com/assets/878935/2479145/5f69a840-b090-11e3-87b1-79c629538cf4.png)

**Comment by daid** [comment]
You can select a more advanced window from the preferences, as noted in the "new in this version" popup.
