### ISSUE TITLE
Strange head travel in gcode output when slicing certain models using Cura 14.01

### ISSUE THREAD

**Issue by mikeq3** [daid/LegacyCura#704]
I checked the models for errors, holes etc. and there are none. When the model is sliced it has a large head travel on the first layer right in the middle of printing the model. I found that if I move the model on the platform only a little from it's default position (say 10mm) the problem may go away when it is resliced.

Below I included two examples of the gcode with only the first layer to save space.
I highlighted the line that is in error.
Here is the gcode output with this error:

;Generated with Cura_SteamEngine 13.12
;Sliced at: Wed 15-01-2014 09:32:58
;Basic settings: Layer height: 0.2 Walls: 0.8 Fill: 20
;Print time: 5 minutes
;Filament used: 0.14 meter 1 gram
;Filament cost:     0.06
G21        ;metric values
G90        ;absolute positioning
M107       ;start with the fan off
M109 S230 B235 F0.1 ;AutoTemp set
G28 X0 Y0  ;move X/Y to min endstops
G28 Z0     ;move Z to min endstops
G92 X0 Y0 Z0 E0         ;reset software position to front/left/z=0.0
G1 Z50.0 F1800 ;move the platform down 50mm
G92 E0                  ;zero the extruded length
G1 F200 E3              ;extrude 3mm of feed stock
G92 E0                  ;zero the extruded length again
G1 F9000
G1 X95 Y104 F9000

;Layer count: 20
;LAYER:0
M107
G0 F3600 X85.90 Y85.90 Z0.28
;TYPE:SKIRT
G1 F1200 E0.00000
G1 X119.10 Y85.90 E0.56295
G1 X119.10 Y119.10 E1.12590
G1 X85.90 Y119.10 E1.68885
G1 X85.90 Y85.90 E2.25180
G0 F3600 X86.30 Y86.30
G1 F1200 X118.70 Y86.30 E2.80119
G1 X118.70 Y118.70 E3.35057
G1 X86.30 Y118.70 E3.89996
G1 X86.30 Y86.30 E4.44934
G1 F1200 E-0.05066
G0 F3600 X93.10 Y93.10
;TYPE:WALL-INNER
G1 F1200 E4.44934
G1 X111.90 Y93.10 E4.76812
G1 X111.90 Y111.90 E5.08690
G1 X93.10 Y111.90 E5.40568
G1 X93.10 Y93.10 E5.72446
G0 F3600 X98.66 Y98.42
G1 F1200 X98.18 Y98.93 E5.73622
G1 X97.77 Y99.51 E5.74833
G1 X97.43 Y100.13 E5.76027
G1 X97.17 Y100.77 E5.77203
G1 X97.00 Y101.46 E5.78407
G1 X96.91 Y102.14 E5.79569
G1 X96.90 Y102.50 E5.80178
G1 X96.91 Y102.85 E5.80772
G1 X97.00 Y103.55 E5.81967
G1 X97.17 Y104.23 E5.83162
G1 X97.43 Y104.88 E5.84339
G1 X97.60 Y105.21 E5.84967
G1 X97.97 Y105.79 E5.86142
G1 X98.42 Y106.33 E5.87336
G1 X98.93 Y106.81 E5.88528
G1 X99.50 Y107.23 E5.89721
G1 X100.12 Y107.57 E5.90915
G1 X100.76 Y107.82 E5.92092
G1 X101.12 Y107.93 E5.92720
G1 X101.79 Y108.06 E5.93880
G1 X102.50 Y108.10 E5.95088
G1 X102.86 Y108.09 E5.95699
G1 X103.55 Y108.00 E5.96876
G1 X104.23 Y107.83 E5.98070
G1 X104.88 Y107.57 E5.99247
G1 X105.21 Y107.40 E5.99875
G1 X105.79 Y107.03 E6.01050
G1 X106.33 Y106.58 E6.02244
G1 X106.81 Y106.07 E6.03436
G1 X1.50 E6.04629 <<--------------------------offending gcode------
G1 X107.57 Y104.88 E6.05823
G1 X107.82 Y104.24 E6.06999
G1 X107.93 Y103.88 E6.07627
G1 X108.06 Y103.21 E6.08788
G1 X108.10 Y102.48 E6.10030
G1 X108.06 Y101.80 E6.11192
G1 X108.00 Y101.43 E6.11819
G1 X107.82 Y100.76 E6.12998
G1 X107.56 Y100.11 E6.14188
G1 X107.23 Y99.50 E6.15365
G1 X107.03 Y99.20 E6.15975
G1 X106.58 Y98.66 E6.17169
G1 X106.07 Y98.18 E6.18345
G1 X105.49 Y97.77 E6.19555
G1 X104.87 Y97.43 E6.20750
G1 X104.23 Y97.17 E6.21926
G1 X103.54 Y97.00 E6.23130
G1 X102.86 Y96.91 E6.24292
G1 X102.48 Y96.90 E6.24937
G1 X101.80 Y96.94 E6.26099
G1 X101.43 Y97.00 E6.26726
G1 X100.76 Y97.18 E6.27905
G1 X100.11 Y97.44 E6.29096
G1 X99.50 Y97.77 E6.30273
G1 X99.20 Y97.97 E6.30882
G1 X98.66 Y98.42 E6.32076
G0 F3600 X98.93 Y98.72
;TYPE:WALL-OUTER

Another example:

;Generated with Cura_SteamEngine 13.12
;Sliced at: Wed 15-01-2014 09:51:30
;Basic settings: Layer height: 0.2 Walls: 0.8 Fill: 20
;Print time: 5 minutes
;Filament used: 0.13 meter 1 gram
;Filament cost:     0.06
G21        ;metric values
G90        ;absolute positioning
M107       ;start with the fan off
M109 S230 B235 F0.1 ;AutoTemp set
G28 X0 Y0  ;move X/Y to min endstops
G28 Z0     ;move Z to min endstops
G92 X0 Y0 Z0 E0         ;reset software position to front/left/z=0.0
G1 Z50.0 F1800 ;move the platform down 50mm
G92 E0                  ;zero the extruded length
G1 F200 E3              ;extrude 3mm of feed stock
G92 E0                  ;zero the extruded length again
G1 F9000
G1 X95 Y104 F9000

;Layer count: 10
;LAYER:0
M107
G0 F3600 X72.97 Y102.50 Z0.28
;TYPE:SKIRT
G1 F1200 E0.00000
G1 X102.50 Y72.97 E0.70822
G1 X132.03 Y102.50 E1.41644
G1 X102.50 Y132.03 E2.12467
G1 X72.97 Y102.50 E2.83289
G0 F3600 X73.53 Y102.50
G1 F1200 X102.50 Y73.53 E3.52754
G1 X131.47 Y102.50 E4.22219
G1 X102.50 Y131.47 E4.91684
G1 X73.53 Y102.50 E5.61149
G0 F3600 X97.75 Y102.50
G1 F1200 X97.92 Y103.73 E5.63249
G1 X98.39 Y104.87 E5.65352
G1 X99.14 Y105.86 E5.67451
G1 X100.13 Y106.61 E5.69551
G1 X101.27 Y107.08 E5.71654
G1 X102.50 Y107.25 E5.73754
G1 X103.73 Y107.08 E5.75854
G1 X104.87 Y106.61 E5.77958
G1 X105.86 Y105.86 E5.80057
G1 X106.61 Y104.87 E5.82157
G1 X107.08 Y103.73 E5.84260
G1 X107.25 Y102.50 E5.86360
G1 X107.08 Y101.27 E5.88460
G1 X106.61 Y100.13 E5.90564
G1 X105.86 Y99.14 E5.92663
G1 X104.87 Y98.39 E5.94762
G1 X103.73 Y97.92 E5.96866
G1 X102.50 Y97.75 E5.98966
G1 X101.27 Y97.92 E6.01066
G1 X100.13 Y98.39 E6.03169
G1 X99.14 Y99.14 E6.05269
G1 X98.39 Y100.13 E6.07368
G1 X97.92 Y101.27 E6.09472
G1 X97.75 Y102.50 E6.11572
G0 F3600 X98.16 Y102.50
G1 F1200 X98.30 Y103.62 E6.13487
G1 X98.74 Y104.67 E6.15420
G1 X99.43 Y105.57 E6.17339
G1 X100.33 Y106.26 E6.19258
G1 X101.38 Y106.70 E6.21191
G1 X102.50 Y106.84 E6.23106
G1 X103.62 Y106.70 E6.25021
G1 X104.67 Y106.26 E6.26954
G1 X105.57 Y105.57 E6.28873
G1 X106.26 Y104.67 E6.30792
G1 X106.70 Y32725 <<------------------offending gcode-----
G1 X106.84 Y102.50 E6.34640
G1 X106.70 Y101.38 E6.36556
G1 X106.26 Y100.33 E6.38488
G1 X105.57 Y99.43 E6.40407
G1 X104.67 Y98.74 E6.42327
G1 X103.62 Y98.30 E6.44259
G1 X102.50 Y98.16 E6.46175
G1 X101.38 Y98.30 E6.48090
G1 X100.33 Y98.74 E6.50022
G1 X99.43 Y99.43 E6.51942
G1 X98.74 Y100.33 E6.53861
G1 X98.30 Y101.38 E6.55793
G1 X98.16 Y102.50 E6.57709
G1 F1200 E2.07709
G0 F3600 X90.89 Y102.50
;TYPE:WALL-INNER

**Comment by daid** [comment]
G1 X1.50 E6.04629 <<--------------------------offending gcode------

I think you might have some other problem, memory corruption or bad SD card/hard disk. Because the above line is impossible to generate from Cura. X and Y are always written as 1 thing. So a line with just an X is impossible.

Also, the engine is deterministic, which means the same input twice will produce the same output. If reslicing fixes the problem I would start looking at the hardware.

**Comment by mikeq3** [comment]
I'm not using an SD card. I have to move the model a few mm on the platform and then when it reslices it is most times fixed. Every time the model is loaded it always slices with this error. It is consistent. It will always give the same slice error. So it can't be random corruption. It happens with more then one model as well. I'm running on Linux. I just loaded the model again and the same exact error. I can send you the model.

**Comment by mikeq3** [comment]
Actually, I just checked and even when I thought there was no error, there still was. It was just getting ignored. Here is the line after I move the model a few mm on the platform and the gcode render looks good. The gcode still has an error at the same line but it doesn't show in the layers view and the model prints ok.
I guess it just ignores what's after the first E code.
G1 X98.55 Y103.83 E6.98.89 Y103.21 E6.05823

**Comment by mikeq3** [comment]
I wanted to isolate the issue so I ran ./cura.py -s 20mm4mmhigh10mmHole.stl' -o /tmp/20mm4mmhigh10mmHole.gcode and I had the slice errors. Then I ran ./CuraEngine -o /tmp/20mm4mmhigh10mmHole.gcode 20mm4mmhigh10mmHole.stl  and there were no errors.
So I think it is a buffer issue writing the gcode. Something in the python code.

**Comment by mikeq3** [comment]
Ok, I narrowed it down and it was caused by a line in Cura/cura.py. The line calls profile.replaceGCodeTagsFromSlicer(slicer.getGCodeFilename(), slicer)

This replaces tags in the gcode with slice information. The routine was reading in 2048 bytes of the gcode file modifying it and writing it back. The problem is after the data is modified it will most likely be more then 2048 bytes. This caused some lines in the file to be partially overwritten. I wanted to keep this routine because I like having the material and print time info in the gcode file if it's saved so I modified it in profile.py as follows. I have never set up to contribute changes so I will just show the updated function here:
def replaceGCodeTagsFromSlicer(filename, slicerInt):
    f = open(filename, 'r+')
    tmp_fname = filename + "_tmp"
    o = open(tmp_fname, 'w')
    for data in f:
        data = data.replace('#P_TIME#', slicerInt.getPrintTime())
        data = data.replace('#F_AMNT#', slicerInt.getFilamentAmount())
        data = data.replace('#F_WGHT#', ('%8.2f' % (float(slicerInt.getFilamentWeight()) \* 1000))[-8:])
        cost = slicerInt.getFilamentCost()
        if cost is None:
            cost = 'Unknown'
        data = data.replace('#F_COST#', ('%8s' % (cost.split(' ')[0]))[-8:])
        o.write(data)  
    f.close()
    o.close()

```
try:
    shutil.copyfile(tmp_fname, filename)
except OSError:
    pass
try:
    os.remove(tmp_fname)
except OSError:
    pass
```

Note: The routine replaceGCodeTags has a similar issue and it looks like it is used for batch mode.
I modified it as well.

**Comment by hg42** [comment]
I would like to make this a bit more generic.
Only one replace (using rexexp),
using associative array or
eventually allowing expressions,
creating values outside the loop,
etc.

May be initializing the temperatures should also go to start and end code? I have my temperatures at zero and set them in start and end code myself, and this could be simplified by replacing variables. The algorithm is dependent on which one is faster.

I hope to find time this weekend...

**Comment by hg42** [comment]
After my communication changes I get only one error line when printing with normal speeds.
This is reproducable.
And I think it's the issue described here.
Thanks, mikeq3.
Btw. nice debugging...

**Comment by hg42** [comment]
hmm, I looked at the code and noticed that in replaceGCodeTags the code looks like this:

```
data = data.replace('#P_TIME#', ('%5d:%02d' % (int(gcodeInt.totalMoveTimeMinute / 60), int(gcodeInt.totalMoveTimeMinute % 60)))[-8:])
data = data.replace('#F_AMNT#', ('%8.2f' % (gcodeInt.extrusionAmount / 1000))[-8:])
data = data.replace('#F_WGHT#', ('%8.2f' % (gcodeInt.calculateWeight() * 1000))[-8:])
```

where each replaces 8 chars by exactly 8 chars (see the formats) unless the values would not be bigger than the format. So reading and writing are both 2048 bytes and should not alter anything.

Whereas in replaceGCodeTagsFromSlicer the same lines are:

```
data = data.replace('#P_TIME#', slicerInt.getPrintTime())
data = data.replace('#F_AMNT#', slicerInt.getFilamentAmount())
data = data.replace('#F_WGHT#', ('%8.2f' % (float(slicerInt.getFilamentWeight()) * 1000))[-8:])
```

which for the first two lines results in different replacement sizes (the formats in getPrintTime and getFilamentAmount are %d minutes, %d hours %d minutes, %0.2f meter %0.0f gram).
So the replacement size always increases and the file content will be damaged.

My (untested) fix would be to read the complete file via

```
data = f.read()
```

and truncate the file after writing back:

```
f.seek(0)
f.write(data)
f.truncate()    # truncates to current position
f.close()
```

now I think, this cannot be the reason for my damaged line(s), at least I see

```
;Print time: #P_TIME#
;Filament used: #F_AMNT#m #F_WGHT#g
;Filament cost: #F_COST#
```

in a saved gcode file, which means it doesn't replace any of the above...

So I'll investigate further.
I currently don't know which function is called on which occasion.

**Comment by mikeq3** [comment]
My solution reads and writes a line at a time. It may not be as fast or elegant but it does not require a lot of memory and works. I tested it with some large files and there does not seem to be any added delay.
 replaceGCodeTags is only used in batch mode. replaceGCodeTagsFromSlicer is used when using the -s option on the command line. I also added replaceGCodeTagsFromSlicer around line 58 of sceneView.py so Goode saved from the GUI will also have the tags replaced in it.

**Comment by daid** [comment]
The "replaceGCodeTagsFromSlicer" was contributed, and I failed to notice the bug in it. Which is odd.

The function "replaceGCodeTags" contains the proper implementation which reads the 2k block, replaces the data, but keeps the length in tact, and writes it back.

The batchRun tool is no longer used. So the call from there to the older function does not do anything.

I disagree with #709, for the reason mentioned above, using a lot of memory.

However, this function will be removed. It's an odd place to do this in the python code, and it's prone to bugs en errors. The Engine contains a function do replace tags in the start code at the end:
https://github.com/Ultimaker/CuraEngine/blob/master/gcodeExport.cpp#L45
Which is a saner thing to do as the Engine as all the information needed to write the info.

(I'm also going to re-design how the Engine and Python interface, so that will change quite a bit)
