### ISSUE TITLE
Wipe/Prime tower and ooze shield overlapping infill

### ISSUE THREAD

**Issue by pwnate** [daid/LegacyCura#705]
Cura is generating overlapping infill for both the wipe/prime tower and the ooze shield. The generated gcode calls for infill from both the left and right extruder during each layer.

Using Cura 14.01 on a mac and an imported .amf file with two colors.

**Comment by daid** [comment]
This was actually intentional. As the extruder was not really going yet when starting the wipe tower putting down 2 "sparse" layers instead of 1 full did not cause problems for my machine. Same goes for the ooze-shield, it's putting down 2 lines top of each other to generate a strong wall.

**Comment by pwnate** [comment]
It's causing too much extrusion on the wipe tower for me. Is it supposed to be 50% extrusion for each extruder? From my generated gcode it's 100% infill, but I couldn't tell if the amount of material for each extruder is halved or not.

I've noticed on my machine (Rep2X) that upon restart of the inactive extruder there's actually a decent amount of additional material. That could be part of my problem. It would be nice to be able to have the restart distance separate from the retract distance.

**Comment by 3ntrlab** [comment]
On very tall builds the wipe tower needs to be wider (= huge waste of plastic).
Couldn't be possible to print an empty polygonal (hex) tube ?

Best Regards
Davide Ardizzoia
