### ISSUE TITLE
Use "inverted" combing for bottom and top layers to avoid visible artefacts

### ISSUE THREAD

**Issue by MoonCactus** [daid/LegacyCura#710]
Could the head avoid interiors that are going to be filled on the first layer, just as for the top layers?
Crossing the outer surfaces because of combing usually leaves heterogeneous "transverse" lines on the outer of the print.

**Comment by BagelOrb** [comment]
What do you mean by 'inverted combing'?

What do you specifically propose?

I would say that it is maybe a good idea to only allow combing over the infill area, cause everything else might result in scars.

**Comment by MoonCactus** [comment]
Sorry for the late reply... now, my suggestion was so old that I do not remember exactly what I had in mind! Anyhow, you got the idea, the goal really was to make it prettier by reducing or not leaving scars on any visible top and bottom surfaces.
E.g. may be the head could move along the perimeters to avoid criss-crossing the infill lines (actually temporarily disabling combing). I can't make it as clear as I thought anymore...
