### ISSUE TITLE
Object is closed on top in gcode, while the STL is open

### ISSUE THREAD

**Issue by drayde** [daid/LegacyCura#711]
I have a STL of a pen cap (basically a pipe which is closed on one side). When I generate gcode for it, the open side (which is on top) is closed as well. 
This happens in version 13.12, but also happens in 14.1

I can provide the stl if you need it

![image](https://f.cloud.github.com/assets/640901/1966893/acd04098-82ce-11e3-8d94-8d878ec96c05.png)
![image](https://f.cloud.github.com/assets/640901/1966900/b7dceb62-82ce-11e3-8634-352eb68b1198.png)

**Comment by daid** [comment]
It's a bug in Cura related to the expert setting Fix Horrible Type A in combination with high polygon models. I have a fix and a work-around is disabling the type A fix horrible.

**Comment by drayde** [comment]
You are right! Just tested it with disabling type A fix horrible, works nicely.
Thanks for the quick response!
Andreas

**Comment by tabakhase** [comment]
@daid this is totally off-topic but i can´t find another way to contact you, please have a look here: 
https://gist.github.com/tabakhase/fd1be8826785fdfe6de4 - feel free to eradicate this comment afterwards if possible.
thank you

**Comment by daid** [comment]
@tabakhase Feel free to take over the project and the code. I had some ideas about trying to add first-person EVA. Which would be pretty cool. But I never got around to do it. Consider all the code MIT license (which is the most none-restrictive license that I know), I can add this if you want. Didn't think the code was that special :-)
I can also be contacted at daid303@gmail.com or on the name Daid on the KSP forums.
