### ISSUE TITLE
Feature request: multiple extruder nozzle sizes

### ISSUE THREAD

**Issue by rizmarino** [daid/LegacyCura#716]
Hi, 
I don't knows whether anyone else thinks this would be a good feature to have but being able to set different nozzle diameters for multiple extruders would be really handy. For example you could use a 0.4 nozzle for perimeters and 0.6 for infill, this would help speed up printing times too.

Any thoughts?

Thanks

**Comment by 3ntrlab** [comment]
Very interested.  :-)

**Comment by daid** [comment]
I've been thinking about how to solve this in the GUI, that's the main issue. Engine wise it just requires moving things around a bit but it can be done.

**Comment by rizmarino** [comment]
Maybe adding the nozzle size option for additional hotends could be added to printer preferences where the X and Y offsets are instead of the main GUI? Just an idea. The way I see it is if someone is trying to print with multiple hotends they're more than likely going to be a more advanced user anyway and would probably know their way around Cura.

**Comment by RoboKaren** [comment]
RizMarino's suggestion is excellent! Yes, please do add the nozzle size option. I think  the Advanced window where the second nozzle size would shows up (just as the 2nd extruder temp shows up automagically when 2 extruders) is also another option. 

Either way is fine, but please do add this!

**Comment by nallath** [comment]
We're in the process of overhauling the GUI side of python and this is one of the things that the change / re-factor will make possible.
