### ISSUE TITLE
unknown reason for pause

### ISSUE THREAD

**Issue by grimm18** [daid/LegacyCura#717]
got a portabee with a gen6 printboard.

I recently started to pause mid print, and often.

wiped computer and re installed windows and problem remains.

got lots of cpu and mem and hdd space so that is no issue.

is it common for boards to fail in the gen6 stuff?

**Comment by nallath** [comment]
We have no experience with portabee, so can't answer this. Cura is probably unable to detect the board.

**Comment by grimm18** [comment]
I found the issue.
sorry for delay to post,

the issue fell on the driver. (usb to serial) the latency timer is set to 16, this must be changed to 32.
