### ISSUE TITLE
Add line wrap to the field labels for the parameters of enabled plugins

### ISSUE THREAD

**Issue by MoonCactus** [daid/LegacyCura#718]
The labels before the fields for plugin parameters do not go to line. When the text is long, the field is pushed right out of view (past the border). Happens with the latest wood plugin, e.g.

The solution right now is either to move the separation further to the right, or to use very short labels. The latter option may not allow clear description of the parameters, it would be better if the labels got line-wrapped before the fields and the fields are always shown.

**Comment by nallath** [comment]
The entire GUI will be redesigned, so this will no longer be an issue.
