### ISSUE TITLE
Windows RC_2 download graphics trouble

### ISSUE THREAD

**Issue by bkubicek** [daid/LegacyCura#72]
Hi!
I tried the current windows rc_2 download today, and had tremendous troubles with win7 x64. The 3d window repeatedly froze after e.g. a maximize click. Sometimes it even started flashing.
I have no real clue what could be going on..
greetings,
 bernhard

**Comment by daid** [comment]
What kind of video card do you have? I'm seeing the same problem on my Vista laptop with an ATI Mobility 1270.

The only solution I have right now is not to run it full screen, and resize the window slightly when it happens. Could you check if that works around your problem? then we know if we have the same problem.

**Comment by bkubicek** [comment]
lenovo thinkpad x200. I think Intel video driver. I will try as soon as I have some minutes to spare.

**Comment by tachyio** [comment]
I get issues with previewing the GCode within the viewer, after several layers the display of the GCode patterns goes bonkers, issue is resolved if I step-backwards again to earlier layers. I think it's related.

Windows 7 64 bit, Cura RC 2, ATI Radeon 5800 HD Mobility (Apple iMac)

**Comment by daid** [comment]
tachyio: That's not good. I've changed the GCode viewer quite a bit for RC3, so when that's released it might work better (or worse)

**Comment by daid** [comment]
I've done an update in RC4 which solved this problem on my laptop, if you have time could you check if it also solves it for you?

**Comment by tachyio** [comment]
I've downgraded to RC2 in the meantime due to motor control problems in RC3. In the pre-printing phase, the steppers move the z-tray upwards so slowly that the extruder head empties its contents before printing starts. So Layer 0 is not printed. I'll try RC4 tomorrow, when we've got no jobs coming through.

**Comment by tachyio** [comment]
Hi Daid, sorry for the late reply, issue appears resolved, no funny bugs. However, I don't see an animation of how its going to print it, though I do see the layers coming up, as I scroll through the layer numbers.

**Comment by tachyio** [comment]
Oops nope, bug remains for some models. But overall a lot better for most.

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
