### ISSUE TITLE
Cura 14.01 closes up internal holes

### ISSUE THREAD

**Issue by 3D-Darryl** [daid/LegacyCura#720]
Trying to print a Mendel-90 "x_idler_bracket.stl" from Github.  There is supposed to be a cavity in the top under an overhang.  The normal view shows no cavity while the xray view shows it.  All combinations of  "Fix horrible" fill in the cavity.  Using "support everywhere" supports the overhang but still no cavity.

**Comment by daid** [comment]
This is actually a bug in OpenSCAD. You need to disable "Fix Horrible Type A" to work around it.

What happens is that OpenSCAD exports internal cavities that are not connected to the outside with the wrong normals. Cura uses these normals to detect what is inside and outside of the model. (When Type A is enabled)

**Comment by 3D-Darryl** [comment]
I tried various combinations of Fix Horrible, including all unchecked, but
it always fills in the hole.

**Comment by daid** [comment]
Can you try the version from http://software.ultimaker.com/Cura_closed_beta/
14.01 contains a small bug related to high polygon models that sometimes can cause this.

(It works on my machine with the latest dev version)
