### ISSUE TITLE
Camera ON can't turn off

### ISSUE THREAD

**Issue by Ozista** [daid/LegacyCura#721]
Thank you for providing this great software but does the camera need to be on? I could not find the setting as yet and I am not a good looking to show my face in my notebooks built in camera. :-)

Regards

**Comment by daid** [comment]
Right now there is no way to disable this feature during USB printing. But I'm working on USB printing code right now, and this problem has been reported quite often so I will keep it in mind.

(The problem is actually much deeper, where the camera interface refuses to close when I do not use it)

**Comment by Ozista** [comment]
Thank you Daid, You are doing a great deed.

Cheers
Istvan

On Mon, Feb 3, 2014 at 9:42 PM, daid notifications@github.com wrote:

> Right now there is no way to disable this feature during USB printing. But
> I'm working on USB printing code right now, and this problem has been
> reported quite often so I will keep it in mind.
> 
> (The problem is actually much deeper, where the camera interface refuses
> to close when I do not use it)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/daid/Cura/issues/721#issuecomment-33940261
> .

## 

Istvan Toth

Ph.:      +61 2 9415 8142
Mobile: +61 4 0724 6296
Email: antopi.hu@gmail.com antopi.hu@gmail.com

**Comment by Ozista** [comment]
Dear David,

Please allow me to get your attention about Cura. 13.12

I have a part in STL which have an embedded "CUSTOM" statement ( I do not
know why) which pauses the printer at 25th layer, behind (X max Y max) the
work piece.  When I attempt to resume, the process trips out from
connection between my PC and the printer.  After reconnecting, the print is
starting from the beginning of the work.

I have tried to delete that part of the G-code but my MS Note's (text file)
would not be accepted again in Cura.
I am attaching the G-code unedited if you are interested to look at.

Thank you again

Istvan Toth

---------- Forwarded message ----------
From: Toth Antopi antopi.hu@gmail.com
Date: Mon, Feb 3, 2014 at 11:17 PM
Subject: Re: [Cura] Camera ON can't turn off (#721)
To: daid/Cura <
reply@reply.github.com


Thank you Daid, You are doing a great deed.

Cheers
Istvan

On Mon, Feb 3, 2014 at 9:42 PM, daid notifications@github.com wrote:

> Right now there is no way to disable this feature during USB printing. But
> I'm working on USB printing code right now, and this problem has been
> reported quite often so I will keep it in mind.
> 
> (The problem is actually much deeper, where the camera interface refuses
> to close when I do not use it)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/daid/Cura/issues/721#issuecomment-33940261
> .

## 

Istvan Toth

Ph.:      +61 2 9415 8142
Mobile: +61 4 0724 6296
Email: antopi.hu@gmail.com antopi.hu@gmail.com

## 

Istvan Toth

Ph.:      +61 2 9415 8142
Mobile: +61 4 0724 6296
Email: antopi.hu@gmail.com antopi.hu@gmail.com

**Comment by nallath** [comment]
@Ozista; Please make a new issue if you have an unrelated problem.
