### ISSUE TITLE
Wipe&prime 

### ISSUE THREAD

**Issue by 3ntrlab** [daid/LegacyCura#725]
I am starting to use extensively Cura 14 with two and three-nozzle configurations, and have found several strange behaviour.

First: I consistently get the base of wipe and prime tower being one layer "later" on print, therefore adhesion to plate is poor.

Second: no raft for wipe and prime tower. Am I missing something ?

Great software, anyway.

Best Regards
Davide Ardizzoia

**Comment by daid** [comment]
The lack of the raft is most likely causing your missed layers. I get better results with brim then raft, so I do recommend brim (which is put around the wipetower) I've also fixed the raft code to include the wipetower.

**Comment by 3ntrlab** [comment]
Hello Daid, I have settled into using raft when printing with polyamide. 
But I am going to re-consider my habits and try brim with Cura :-)
As soon as the new release (with "rafted" wipetower) will be out, I will be happy to try it, too.

Thank you,
Davide Ardizzoia

**Comment by daid** [comment]
Got a release candidate out at http://software.ultimaker.com/Cura_closed_beta/
