### ISSUE TITLE
Bottom layer speed ignored

### ISSUE THREAD

**Issue by Johann1** [daid/LegacyCura#728]
Cura 14.01 - Windows

Bottom layer speed set to 20mm/s, Infill 120.0 mm/s (adv)
Initial layer thickness 0.3mm (adv)
Shell thickness 1mm (basic)
Bottom/Top thickness 2mm (basic)
Print speed 30mm/s (basic)

Bottom layer is printed with 120.0 mm/s on printbed
and not with 20mm/s.

**Comment by daid** [comment]
Bug with current releases, already fixed for the next version. Current released versions calculate a factor between the print speed and bottom speed, and use that to correct the bottom layer speeds. But with a different infill speed this goes wrong. So you're not getting 120mm/s, but 20/30*120=80mm/s

**Comment by Johann1** [comment]
Many thanks for quick answer :)
