### ISSUE TITLE
feature request: support of Arduino-Due

### ISSUE THREAD

**Issue by ebo** [daid/LegacyCura#731]
Is anyone supporting, or have plans to support, the new Arduino-Due?  I am experimenting with setting up an UDOO for 3D printing, CNC, etc., and am currently looking at the new support in Repetier-Firmware, but neither RepetierHost nor Printrun/Pronterface are working for me yet on an off the shelf Arduino-Due (I am starting to expect a hardware issue...).

FYI, sing usbview the device shows up as:

Arduino Due
Manufacturer: Arduino LLC
Speed: 480Mb/s (high)
USB Version:  2.00
Device Class: 00(>ifc )
Device Subclass: 00
Device Protocol: 00
Maximum Default Endpoint Size: 64
Number of Configurations: 1
Vendor Id: 2341
Product Id: 003e
Revision Number:  1.00

So the computer sees the Due.  As a note, I am using a on a Gentoo Linux-3.10.25 box...

  Thanks and best regards,

  EBo --

**Comment by daid** [comment]
Cura's only hardware related feature is firmware upload. You need to look at Marlin.
