### ISSUE TITLE
cura extrudes one side bridges inside infill 

### ISSUE THREAD

**Issue by curiouspl2** [daid/LegacyCura#733]
in case of very sparse infill and some object inside it cura gets a problem.
it tries to 'start' the object by making short bridges from edges of walls at high speed
but this obviously fails, especially those bridges are one-ended (start from wall but end in void) . 

result is ugly blob with tendency to curl up and finally collide with head and ruin whole print.
here is visual example :
imgur.com/a/CAl2k

in general the 'growing up' support seems good strategy, just reducing speed to about 30% helps a bit (though it still curls up, it curls up bit less and collision is less painfull)
so for starter perhaps just some option to reduce speed of such structures would be great. 

imho bit better strategy would be to also extend 'blind' lines to form full bridge , and in case certain threshold is breached extra 'helper support' infill could be assembled. notice that after just few layers of such 'full' support next layers would get firm base to rely on and could actually stop extending to full lenght, utilizing just current 'growing' strategy.

**Comment by curiouspl2** [comment]
http://imgur.com/a/CAl2k for easier clicking

**Comment by nallath** [comment]
I dont quite understand the issue. I've never encountered it on a Ultimaker.

**Comment by curiouspl2** [comment]
look at pictures. here you can see it also on a preview :
http://imgur.com/a/XOiGx
on layer 71 you can see only infill
on layer 72 you can see bridges which try to 'pad' for forthcoming layers, 
but they do not anchor to infill walls but are printed in thin air. 

it is not ultimaker specific bug, it is generally bad approach to slicing such features.

i do not understand why you did close this bug - in many cases it causes damage to printer!

**Comment by nallath** [comment]
The anchoring is dependant on the wall overlap; On my ultimaker these features are anchored. 

How would this damage your machine?

**Comment by curiouspl2** [comment]
does your ultimaker extend those features to the walls? please explain me more - is it some firmware option? 

either way gcode is parsed by plain i3 as set in settings and wall overlap does not have effect on the anchoring of those features at all - as you can see on the pictures with preview - they remain suspended with nothing underneath them, so there is just nothing they can anchor to!

damage to machine is done because in case they cross infill line , unanchored ends curl up - as on first pics i've posted. this curling builds up and finally collides with print head or it's heat shield. 
hitting at high speed can merely break PEEK insulator or extruder, not to mention bending heat shield.

**Comment by curiouspl2** [comment]
![screenshot from 2014-03-05 21 53 21](https://f.cloud.github.com/assets/6697487/2353398/43a62660-a5a0-11e3-8aab-ad74a565df9c.jpg)

i've cropped the feature i am talking about , it is pale green in the center . notice it has nothing it could anchor to underneath - no perimeter, no support... well absolutely nothing. threads are going from left to right back and forth, so first thread is laid on top of upper perimeter, next one and subsequent ones fall down, then last one is laid on lower perimeter. 

IMO in such case it should just extend to nearest perimeter to make sure it's anchored, or bridge direction should be rotated 90 degrees (so it connects top and bottom perimeter)

**Comment by curiouspl2** [comment]
![screenshot from 2014-03-07 03 37 53](https://f.cloud.github.com/assets/6697487/2353446/a1845eae-a5a1-11e3-83f6-10e06da8cead.png)

here is another example from same print, where you can have even less doubts what the problem is. notice just one edge of this bridge is actually touching any perimeter.

**Comment by daid** [comment]
Actually, due to the 0.6mm top/bottom thickness that it generally lays down, the first layers are a bit messy, but after a few layers it "corrects" itself. This is intended behavior. As it's quite possible to print like this.

**Comment by curiouspl2** [comment]
couldn't this behaviour be changed? it assumes extrudate will always fall down, but this is just counting on luck. 

also bridging speed in such cases is too high, like bridging speed in general and one cannot change it. 
here is slic3r vs cura case :
http://imgur.com/a/ozNIJ

cura print is the one which did not finished - head crashed into curled up bridges. 
as one can see , slic3r prints same object just fine, with just one bridge thread failed (not visible on pic) 

simplest workaround coming to my mind would be to just extend such bridge features to nearest perimeter , as just one layer will be printed like that amount of plastic increasing would be quite small. for safety reasons i would leave it on by default in 'advanced' tab.

**Comment by nallath** [comment]
Damaging it? That has more to do with poor hardware design. Yes, the software should prevent certain odd behaviour, but the responsibility of it not breaking is on the side of the hardware. If a bit of curled PLA can break your printer, I would look into modifying your printer first.

**Comment by curiouspl2** [comment]
a lot of curled ABS, especially from large surface layer, distributed evenly (because of infill) causes a lot of damage. it's enough to stop and jam printer . 

afaik most reprap hardware have no means of 'safety' - no additional endstops, head crash or fire detection - by design - because of diy and price concerns users actually enjoy - software being fairly free of potentially dangerous behaviour plays important role here IMHO. 

i've already hit at least several prints with which cura behaviour caused print to merely not complete due to head crashing the print - skipped steps due to collision is enough stopper. 

my hot end is all metal, so is already over-the standard, and uses commonly available extruder design (collaborative wade, which has hot end mount like standard wade) 

behaviour is obviously nonsense and waste of plastic aswell, so i totally don't see point of blaming hardware, especially that any 'upgrade' will not really make prints sliced that way complete, look good and using optimal amount of plastic, while they are perfect killers for hot ends and extruder mounts because of way they hit the head repetadely over curled features even when printing fairly simple parts. 

if there is any problem in fixing the bug, i propose at least temporary workaround by warning in infill box to warn users that using infill below 20% can be dangerous due to bug in infill code.
