### ISSUE TITLE
head moves down the print - serious bug. 

### ISSUE THREAD

**Issue by curiouspl2** [daid/LegacyCura#734]
in about half the print out of sudden head moves DOWN. 
13.11-2 was free of this issue.
i've tried to slice this :
http://www.thingiverse.com/thing:159454/#files

i can upload gcode somewhere upon request

**Comment by daid** [comment]
In version? Which way of printing? (USB, SD) Which settings?

**Comment by curiouspl2** [comment]
cura_14.02-RC1-debian_i386.deb

printing from sd card, 
;CURA_PROFILE_STRING:eNrtV0tz2zYQvnI0/RF77CNmQT0cJxpe0tq+JJ3M2J06vnAgcimiJgkOCOo5+u9dgA9RDzdJk0tnrIMkLHYXux++3SVTvkYVJCjmifaZ6106S56mgU5E+JRjWfqjn5k7ZpeOQq14qIXMA8z5LEX/XlXolDIVUZBaL4dG5CoW5CrCvBR67XvMyeVmk2JQig36tddCiVwHZYEY+cOrZqkxK1BxXSlSO5UNzwlH54TjTjjD6MhtWRWFVNr/Q+boFCnXsVRZwKMES8qxFjc6QVTxNMCVVpXdeyd14ixFgYGWS1T+DU9L7AmChUyrDH1v4ki5oXwTgWnUqBEmPEMKKRL0q8l86F5dnYpNlifC0TnhuC+MU7kkqJnL+jdWAzw+kvJMVrn2x+6kL7XJNlve5eFeJvKAFgtMfe9wJ5TZTOTzmhSHFiI7QI+CGPY1ElkYmTOTWsusRyLmjhw5+xtDIojIn6ySXKBKeWGDNHSdOHU4TYbepOepJmXDLeaI3NKxgWJC6xI16+/TetWsR8wJpUxtwg25Bd3oxIl5y/+oKYAnQQxJRY6EgcWsEc154Y8omnrV4pBiPtdJE6hxFlcUVFd/9QFNMoztV0HGV1bShRWTlNiMprCsMEFOlShi3TCtLk1N8PYqtcamllg8GkQNWVu663WB/q0SUSfh+ZwK/rKrmsCa1qfv7VZr4mSpeR6a8n7dyTd9sdEvhOKpaQJ1oDMlsj6CdBmKx4QZV3ORE+h2ZRXKgoeGZp7b6Mx4iUec2cuNyVJEhLcJx8qpGaCKeXhoNDze7FsOCagV0VQpQdceVLmtHdMkCaeAt1g+rzLrSr+vQ/HJAvNgJnR5ToEqxnTOBSWthQ4Tk3atVqQV4UJgEaPnflsjIZrog5V/4R2J1iT6gS5AaXceygj96V0qQoyA67ewjfh6Z7410o9h+W4wfcdLEQLVg6ZTy7fw3pQA1Cwlk7Q3NHbwFyVKOtvDwbGDG+IIiftDgFx/NP0YzDm013Ts+tCbpocBQRPVhnVPq5vRLuuJlvXZ855VKEvdtzJr8vrBe8Pgbnt2DOxg+mdOncvaawk8imAtKwVymQPpQk8XDCWMO/amc/elrk7c3A49aD5T6uGKwF7wtMJycEvRtjt8RjVbaYRCEnhEKbqMAQXwulWwdwpLoRPQCQI1C5BxPCD3V/DA4BMz7qnA4eHXTyYoahuAeVRSTyit0iNrYjBKjycqg1sPHr2Jy+Bm2++zu8bCHNqOTohMpt4ky8jszRCuuzz2n+kGlbRWdhxEhHDdD81BN0PG4Hp0ZNEowijLKDcwTQ8ouPDp6w8BPucit0cdZkOkrDTYKyWEISP28jmCzOH9b79DGSrEnHD3XsPHRsd13YFDMLX1dJ1HcPsb/TXXM4a7M2H1kjGVROWm7GV98MbsWQOrF1kq7k3gRxEbbkFCOYDQPxnAPfiCz1Qh3Ra1lANGESDXFwTKiLHPGNuZXVOtrToO1L8oQKKA4XZsETQa9bPeK8MpOhWpHUMpMzSXaGmjCGWqB0uxX2jwUQwTeLgYEm3N13nCPUJVNEdygryNqIsGF5hDJo3bfQn8a1LPlccritYGaqYqiBIkUaSJfcnXg8GHq/HzXkuNBVV8aW+4V9Knmmdr3LGFPXzp1t+hW4+/vVvXTf/eO+dp+J9csZcR8pkRcv9MQ5veLc3DkDnHmA6pC7Rd9VvGjsfOjx2Pfde5Y8+62J5/29pR1uyLso6FKvX/Ke/vNW+Hzwzce/aVM9fYeC9z+mVOf+Ocbt5w+y9XnXD/fFi/nx8oWUlPQyF1wRDdsFyQB1vt1w0Lu8eAugfMUC+pQGyGYaWUxbMlrEHb3ipJOukrWCZk0BWc7fZZlWpRpF3VqtJtSrwm2ugSbiaMsVZ4v20Vd0bhYUsvyMFqB5/sH3ooebR/NruTajfujr39A8Zbo3A=

not seeing this behaviour with RC5 so i hope it's fixed.
