### ISSUE TITLE
Printrbot Simple settings

### ISSUE THREAD

**Issue by NetForces** [daid/LegacyCura#735]
The Printrbot.ini provided is not tuned for the Printrbot Simple. I would recommend adding a new profile in the distribution with the following:

> [machine]
> machine_name = PrintrBot_Simple
> machine_type = RepRap
> machine_width = 100
> machine_depth = 100
> machine_height = 100
> machine_center_is_zero = False
> has_heated_bed = False
> gcode_flavor = RepRap (Marlin/Sprinter)
> extruder_amount = 1
> 
> [profile]
> filament_diameter = 1.75
> nozzle_size = 0.4
> layer_height = 0.2
> fill_density = 10
> print_speed = 60
> print_temperature = 200
> travel_speed = 150

**Comment by daid** [comment]
Done!

**Comment by daid** [comment]
This is why I added those simple ini files for default startup settings, makes it easy to add new machines like this one. I simply do not have the time to go after every single machine to figure out the best start settings. :-) So thanks!
