### ISSUE TITLE
Support for Tool change code, just like start/end codes

### ISSUE THREAD

**Issue by Kenzu** [daid/LegacyCura#739]
Hey

I would like support for custom tool change codes.

Thanks

**Comment by daid** [comment]
In the future I will.

**Comment by Kenzu** [comment]
Why is this closed? It's not completed yet.

**Comment by nallath** [comment]
See; https://github.com/daid/Cura/wiki/Issue-policies

**Comment by Kenzu** [comment]
Is this the reason " Feature is already on roadmap (or is placed on the
roadmap due to request)." For closing then?
Den 04/03/2014 13.02 skrev "nallath" notifications@github.com:

**Comment by nallath** [comment]
Daid said;

> In the future I will.

**Comment by Kenzu** [comment]
okay... Anyway, nice to see a cleanup of issues :-)
