### ISSUE TITLE
Setting up a makerbot profile screws up start&end.gcode for Ultimaker profiles

### ISSUE THREAD

**Issue by mpatoulachik** [daid/LegacyCura#740]
There seems to be a flaw in the logic that puts start.gcode and end.gcode for different machine profiles.

I created a machine profile for a makerbot-like and this also replaced start.gcode and end.gcode in my Ultimaker profile.
Nothing could get these back to the default Ultimaker start and end. I had to copy/paste them from an older cura version. Re-running the "first run wizzard" did nothing.
Creating a new Ultimaker profile didn't help either...
This happened with Cura 14.01 on Win 7 x64

**Comment by mpatoulachik** [comment]
Just noticed that it also overwrites filament diameter for the ultimaker profile

**Comment by daid** [comment]
This is fixed in the 14.02, release canidates can be found at http://software.ultimaker.com/Cura_closed_beta/
