### ISSUE TITLE
Recalculating toolpath during scaling entry jams Cura

### ISSUE THREAD

**Issue by luotinen** [daid/LegacyCura#750]
I suggest waiting for a small delay since the last keypress (1000 milliseconds?) before recalculating the toolpath automatically.

When I have a large model and attempt to rescale it this is what happens:
1.00
1.0 (I delete a zero)
waiting...
waiting...
waiting...
1. (I delete a zero)
more waiting...
even more waiting...
waiting, waiting, waiting...
1.2 (I added a two)
and waiting...
waiting...
waiting...
1.25 (added a five for 125%)
finally - some waiting...
waiting...
waiting...
done!

If there was a small delay before recalculating the above would look like
1.00
1.0 (I delete a zero)
1. (I delete a zero)
1.2 (I added a two)
1.25 (added a five for 125%)
finally - some waiting...
waiting...
waiting...
done!

**Comment by daid** [comment]
There is a delay between the change and the toolpath calculation. The problem is that the model is scaled, which triggers a new boundary box calculation. Which can be a bit slow with very high poly models.

**Comment by luotinen** [comment]
To maximize usability with high precision models, I suggest: boundary box approximation using scaling factors until the toolpath is calculated at which time the actual new boundary box should be calculated. See example below:

Model size is 20 x 30 x 40. User rescales by +50 % to 1.50x and new model size is estimated at 1.50_20 x 1.50_30 x 1.50*40 = 30 x 45 x 60. When toolpath calculation is triggered, the actual bounding box is calculated (e.g. 30.01 x 44.98 x 60.00).

I noticed this same problem changing almost any setting => instant freeze on high precision models.

Alternatively you could add an option "Disable automatic recalculation" and have the user manually trigger toolpath calculation.

**Comment by daid** [comment]
The boundary box has nothing to do with the toolpath, but with positioning and checking if it fits on the platform.

**Comment by daid** [comment]
Which version are you using btw? And on which OS?
