### ISSUE TITLE
Rearrange items on platform

### ISSUE THREAD

**Issue by luotinen** [daid/LegacyCura#751]
Sometimes the items are suffled around on the platform and the only way to rearrange them is to add some new item and then delete it. Could you add a Rearrange option?

Once this happened when I added something big and most of my stuff were arranged outside the printable area. Even deleting the offending item did not help.

Sometimes you may accidentally (or deliberately) move an item and want to rearrange automatically.

**Comment by daid** [comment]
You can drag around the objects with the mouse, allowing you to manual arrange.
