### ISSUE TITLE
To max does not respect skirt setting in flat models

### ISSUE THREAD

**Issue by luotinen** [daid/LegacyCura#752]
The To max upscaling scales the model too big to be printed and does not respect the skirt setting. 

To verify: select a flat model. If you skirt setting is set to 1 or higher Cura will maximize the model to unprintable big. If you set skirt setting manually to 0 Cura will still maximize the model to unprintable big (!).

I suggest that if skirt has been set, then maximize skirt and if not, then maximize model to printable area. You could add in the tooltip that the model size can still be increased by rotating the model (usually 45 degrees) and by disabling skirt.

Or just have another maximize button which sets skirt to 0 and rotates the model (only around z-axis) to find the maximum possible size.

**Comment by nallath** [comment]
Verified the bug.

**Comment by luotinen** [comment]
Issue resolved in 14.03.
