### ISSUE TITLE
Printer controls cannot be accessed when the tray is empty

### ISSUE THREAD

**Issue by luotinen** [daid/LegacyCura#753]
When the tray is empty the print button is greyed out and Cura prevents filament change, bed levelling, nozzle cleaning and maintenance and many other features which do not require actual model to be printed. 

I suggest that the user is allowed to enter the print-dialog with printer controls, but the actual "Print" button is greyed out until there is something to print. Or provide another way to access the controls.

**Comment by daid** [comment]
This is actually by design. Why need to access the controls if you have nothing to print?

**Comment by imitation** [comment]
A way to jog an axis or heat up the hotend for a filament swap would be nice. Agreed, the simple print dialog doesn't need to be accessible when there's nothing to print, but when the user selects the full pronterface-style interface, it should be accessible without having to load any stl or gcode.
