### ISSUE TITLE
More Wizards and Tools

### ISSUE THREAD

**Issue by luotinen** [daid/LegacyCura#755]
The wizards are useful and signifcantly lower the pain of using the Ultimaker via Cura.

More ideas for wizards:
- troubleshooting wizards if Ultimaker 1 or 2 is stated (underextrusion, leaking, skew, connecting, motors, temperature..)
- split the current wizards into problem specific tools (the wizards will stay and new tools appear: Communication, End Stops, Temperature, Align corners, Print outer limits..)
- nozzle heat optimizer (to select the lowest usable temperature)
- printing speed optimizer (to select the highest usable speed)
- bed warp analyzer (3x3, 4x4 or 5x5 grid using the nozzle)

**Comment by nallath** [comment]
Most of these issues will be covered by the GUI overhaul.
