### ISSUE TITLE
Up/down keys no more change "current layer view" in layer display

### ISSUE THREAD

**Issue by MoonCactus** [daid/LegacyCura#758]
They now only rotate the view, whatever the view mode. Checking specific layers with hundreds of them is impossible with the mouse (also I used to toggle forth/back with up/down keys for problematic layers).

How: switch to layer view mode, click the vertical scroller, press up/down. 

There could be specific keys otherwise, like page up/page down (also attributed to view angle right now)

Happens with both with 14.02-RC2 and with latest from git @ 20140303-100059

**Comment by daid** [comment]
This has been changed to shift+up/down in 14.02
