### ISSUE TITLE
Start GCode isn't added at the start

### ISSUE THREAD

**Issue by Diaoul** [daid/LegacyCura#759]
The start GCode is added **after** some other GCode generated by Cura. In my case I'd like to start the hotend FAN before the hotend actually starts heating.
Here is an example of GCode generated by Cura:

```
;Generated with Cura_SteamEngine 13.12
M140 S70.000000
M109 T0 S240.000000
T0
M190 S70.000000
;Sliced at: Mon 03-03-2014 19:30:55
;Basic settings: Layer height: 0.3 Walls: 1 Fill: 30
;Print time: #P_TIME#
;Filament used: #F_AMNT#m #F_WGHT#g
;Filament cost: #F_COST#
;M190 S70 ;Uncomment to add your own bed temperature line
;M109 S240 ;Uncomment to add your own temperature line
G21        ;metric values
G90        ;absolute positioning
M107       ;start with the fan off

M42 P8 S255  ;start the hotend fan
```

**Comment by daid** [comment]
;M190 S{print_bed_temperature} ;Uncomment to add your own bed temperature line
;M109 S{print_temperature} ;Uncomment to add your own temperature line

**Comment by Diaoul** [comment]
That's a bit hacky. I mean, start code is supposed to be at the start or just name it something else and provide a way to edit the real start code.

**Comment by daid** [comment]
I did, but you did not even try. Or search, as this has been answered before. (uncommenting those lines will remove the automated lines)

**Comment by Diaoul** [comment]
I'm not saying it doesn't work, it does work so thanks for the workaround. I did search the issues before posting but didn't find any relevant issue titles about this.

All I'm saying is that when editing start.gcode one can expect it to be before anything else, not after some code.
The same way we currently have start.gcode and end.gcode, maybe add an intermediate.gcode with post-initialization stuff?

**Comment by Diaoul** [comment]
Or add all content to start.gcode so that nothing needs to be done before it.

**Comment by nallath** [comment]
The very nature of the start-code is hacky. Normal users will probably never modify the code in the first place. 
There can be a init code, but there are simply too few people that requested the feature for it to be 'worth' the development time required to implement it.

**Comment by Diaoul** [comment]
OK I can understand that, thanks.
