### ISSUE TITLE
Request for the ability to define temperature in Cura for use in start.gcode without auto preheat

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#76]
I would like to be able to define my temperature in Cura ("print_temperture") and use that value to preheat the nozzle in my start.gcode (via {print_temperture}) without Cura inserting another preheat before start.gcode is run.

My use case is that I want to home the nozzle and position it above the print head before preheating.

**Comment by daid** [comment]
I've updated the auto generation of the M109. It now checks if there is a {print_temperature} in your start code, if there is, then it will not insert it's own pre-heat setting.

**Comment by RedwoodForest** [comment]
Great solution. Thanks.
