### ISSUE TITLE
Indentation error on Debian builds

### ISSUE THREAD

**Issue by TopherMan** [daid/LegacyCura#763]
Building from source, Cura currently gives the following error on Debian_amd64 builds (and I suspect would also give the error on i386 builds):

``` python
  File "/usr/share/cura/cura.py", line 29
    exit(1)
          ^
IndentationError: unindent does not match any outer indentation level
```

It appears to have been introduced with commit 7320b68 and replacing the four spaces before "exit(1)" in scripts/linux/cura.py with a tab fixes the issue on Ubuntu 13.10 (64 bit).

**Comment by nallath** [comment]
That will teach me to double check changes. Fix will be up soon.

**Comment by TopherMan** [comment]
Perfect, thanks! I guess that's the mixed blessing of open source development.
