### ISSUE TITLE
Solid layer fill ends in the air instead of at loop boundries

### ISSUE THREAD

**Issue by mikeq3** [daid/LegacyCura#764]
When the solid layer fill is put down in certain instances it ends in mid air instead of at a loop.
This is the layer before the solid layer fill in Cura:
![beforesoldcura](https://f.cloud.github.com/assets/1508594/2334686/8b637438-a47b-11e3-9eae-31999b34a85e.png)
This is the first solid layer fill in Cura:
![aftersolidcura](https://f.cloud.github.com/assets/1508594/2334738/ec9fbf86-a47b-11e3-9f19-958c54ed5309.png)
This is the layer before the solid fill layer in Skeinforge:
![beforesolid](https://f.cloud.github.com/assets/1508594/2334751/1ac5b8de-a47c-11e3-8624-d32bd1e929c2.png)
This is the first solid layer fill in Skeinforge:
![aftersolid](https://f.cloud.github.com/assets/1508594/2334761/3a478002-a47c-11e3-9954-2e96dd425bdb.png)

This can cause the solid layer to droop and result in a weak solid layer of poor binding at the junction of the layers above. Also I have seen small gaps appear.

Mike

**Comment by GregFrost** [comment]
What is the model you are slicing? Is there a ridge around the inner edge of the rim? This may mean that the inner part is infill, not solid which is why the solid part stops short of the inner edge.

**Comment by mikeq3** [comment]
After the solid layers that section continues up. But regardless you cannot lay down fill stopping in mid air. If I had specified 10% fill it would have been even worse. Fill should be put down from edge to edge until those edges change. If I was using 5 or 10% infill the fill would be like bridging and would only work if it went from edge to edge and not end in mid air.

**Comment by mikeq3** [comment]
This is the model I sliced: https://www.youmagine.com/documents/1933/download 
I've seen this happen slicing other models as well.

**Comment by daid** [comment]
This is intended behavior in Cura. You might not like it. But I do. Skeinforge "lets just fill up the whole layer" behavior is wrong IMHO.

**Comment by mikeq3** [comment]
I can accept that but, can you have a loop printed at that position to have a border that the solid fill lines can attach to on the other end? Right now they end in the air in most places in sparse infill.
If you are looking ahead to determine this behavior, can you print a loop in the position of the future wall for the fill lines to attach?

**Comment by GregFrost** [comment]
I agree that filling the whole layer like skeinforge does is a bad thing, but changing direction in mid air is also wrong. Ideally it would go at least as far as it needs to to land on an infill line on the layer below. Might be hard to implement, but it would be a better slicer if it did that. Consider the case where there is no infill. Then you would need to bride all the way to the other side, or it simply won't work.

**Comment by mikeq3** [comment]
That is my point. Filling the whole layer is the only way to bridge for the solid fill layers when fill is set to a low percentage. Even at 20% it's a bit unreliable unless the layer is spanned.
