### ISSUE TITLE
Cant rotate object to 52 degrees

### ISSUE THREAD

**Issue by RobGannon** [daid/LegacyCura#766]
I have a large model that I'm trying to print. The only way it will fit on my bed is if it is at 52 degrees rotation. I could do this with version 12 of Cura and I can do it in Slicer but I cant do it in Version 14 of Cura because it only lets you drag in 15 degree increments.

**Comment by nallath** [comment]
Holding shift while rotating lets you rotate in 1 degree increments.

**Comment by RobGannon** [comment]
Thanks for that.
