### ISSUE TITLE
First layer extrusion width

### ISSUE THREAD

**Issue by whosawhatsis** [daid/LegacyCura#769]
I'm trying to convert from Slic3r to Cura. One big thing that's holding me back is the frequency with which thin parts break loose from the platform when using Cura, even when using a brim.

In Slic3r, I always set my first layer thickness to the maximum for my nozzle, and set the first layer extrusion width to 250%. This results in big thick tracks of plastic on the first layer that adhere really well. I know that Cura can set the height of the first layer, but it doesn't change the extrusion width, so the result is tracks with a very low width/thickness ratio, which is really bad for adhesion, and any slight dip in the platform will result in plastic that is not compressed at all. I'm tempted to go the other direction with Cura, to make the first layer height very small to increase the width/thickness ratio for better adhesion, but of course this will make the machine overly sensitive to platform height and tramming. Any way we can get an option to increase the first layer extrusion width in Cura?

**Comment by daid** [comment]
Cura only support thicker first layers, if you want more extrusion on the first layer you can change the home position of the bed to be a bit closer. As Cura does increase the extrusion to compensate for the thicker layer.
I'm against a extrusion multiplier for the first layer. Sorry.

(250% extrusion is a bit ridiculous btw)

**Comment by whosawhatsis** [comment]
@daid, you're misunderstanding what I'm saying. The layer doesn't just attempt to pack more extrusion into the same space. It is sliced with wider lines so that the plastic spreads out to adhere to the platform better.

This is the bottom of the same model printed with CuraEngine (left) and Slic3r (right). I used MatterControl to convert my profile, so the rest of the settings are as identical as they can be.

![2014-03-07 13 27 06](https://f.cloud.github.com/assets/319404/2362540/87b6dc56-a63f-11e3-8475-e4e00c80fe11.jpg)

The slic3r version has fewer lines, spaced farther apart, with the correct amount of material to fill the extra space. This provides a huge improvement in reliability of the parts sticking to the platform.

**Comment by alexborro** [comment]
This feature will be really welcome!!

I have a 0.4mm nozzle and set the Slic3r/Cura extrusion width to 0.4mm.. In Slic3r I set the first layer extrusion width to 0.8mm.. As OP said, this procedure makes a HUGE difference on first layer adhesion. 
Bear in mind this is not related to plastic over-extrude... it is just a matter of increasing the trace width on first layer.
Please daid, think about it..

Cheers.

Alex.

**Comment by brucehvn** [comment]
I agree with the OP on this.  I just got my printer up and running and have been printing calibration objects with slic3r and had them all turn out really good with good adhesion to the bed.  Tonight I tried to print the precision-block.stl with Cura and I had to kill it after the first layer.  0.3mm is just too thin for good adhesion and we don't have a setting to set the number of perimeters.  My settings in slic3r are using .2mm layer height, .4mm layer width, first layer .4mm height, and first layer thickness .8mm (200% default).  This has really worked well for everything I've printed so far.  I really want to use Cura, however, as I think overall it will give better print quality.

**Comment by alana314** [comment]
I would like this as well, Cura is amazing at slicing but most of my prints keep becoming detached from my bed with my printrbot. I would like the 200% extrusion width for the first layer like slic3r.

**Comment by whosawhatsis** [comment]
@daid, any chance you'd be willing to take another look at this? I understand your position that overextruding the first layer (with the usual line spacing) is a dumb idea, but that's not what we're suggesting, and the feature we're all asking for works beautifully in Slic3r.

**Comment by daid** [comment]
https://github.com/Ultimaker/CuraEngine/blob/master/src/settings.h#L123

**Comment by whosawhatsis** [comment]
@daid Cool! Is that working in the current release? Any way to access it (perhaps by manually editing the profile, since there doesn't appear to be any interface for it) so that I can try it out?

**Comment by daid** [comment]
You'll have to manually edit the util/sliceEngine.py file to modify this setting right now.

**Comment by alana314** [comment]
I see "Initial layer line width (%)" now in advanced settings. Setting that to 200% makes my prints stick. Thank you!!

**Comment by ghost** [comment]
Please implement this in 15.06.03!

**Comment by brunetton** [comment]
Hi all
I really need this option too. Is it implemented in 2.4 series ? I do not see this in advanced :(

Thanks

**Comment by BagelOrb** [comment]
Nope it's not implemented for Cura 2 yet.

**Comment by brunetton** [comment]
Thanks for your answer

**Comment by Avoxis** [comment]
So, do i get that right?
This function was implemented in an earlier version of cura but now disappeared again? Wheres the sense behind this?
I really want to use this feature and changing "Top/Bottom Line Width" isnt really a solution because i want the Top Line to be just normal...

**Comment by brunetton** [comment]
As far as I know, there's no ideal solution. I'm using Slic3r personally.
It's true that in an ideal world, we shouldn't need to change the first
layer height. But in practice, I can't print without tricking on it.
Maybe could it be implemented as a plugin ? I personally do not have the
time for that.

**Comment by nallath** [comment]
This is legacy cura. Cura 2.x is the successor of this version.

**Comment by BagelOrb** [comment]
Initial layer line width was removed because we introduced having different
line widths for the different print features (i.e. walls, infill,
top/bottom skin, etc.)

See https://github.com/Ultimaker/Cura/issues/184

**Comment by whosawhatsis** [comment]
@BagelOrb That doesn't solve the problem though, because first layer extrusion width is a platform adhesion setting, and the ideal value is far too large to use for any other part of the print. Think of it as the first layer of a raft, but in this case, the raft doesn't need to be removed because it is part of the print. Also, the top/bottom line width setting does not affect perimeters, skirt, etc, which is necessary to use this to enhance platform adhesion.

**Comment by BagelOrb** [comment]
No I was merely explaining the cause of it's removal.
