### ISSUE TITLE
Nothing happen after click print

### ISSUE THREAD

**Issue by antlvk** [daid/LegacyCura#772]
Load model 
click print
printing module load
slicing
done slicing
print button undim
nothing happen....

printing on Repreppro Ormerod

**Comment by nallath** [comment]
We're going to need a bit more information than what you've provided. Did you use USB printing? What OS did you use? Have you been able to use USB printing before?

**Comment by antlvk** [comment]
Using USB as com5. Arduino Duet. Windows 8.1.

**Comment by nallath** [comment]
The USB printing is not getting as much love as it used to get, as most printers have a controller of some sorts. In almost all cases, these result in far superior quality anyway. 

Have you been able to get it to work with other software?

**Comment by antlvk** [comment]
Pronterface works perfectly. just not as easy to use as Cura

**Comment by nallath** [comment]
I don't have acces to a Ormerod, so it will be almost impossible to validate/test/fix this.
