### ISSUE TITLE
Print button does nothing and save GCode says Failed to Save

### ISSUE THREAD

**Issue by Prof62** [daid/LegacyCura#775]
I am running version 14.01 on a macbook and two hours ago it was working perfectly. I exited the application, restarted it and now the print option is enabled but does nothing and Save Gcode gives a "Failed to Save" popup.

The slice engine log reports that the models are being sliced correctly giving file sizes, layer counts, etc. yet save and print do not work and the slice view shows one (empty) layer.

This happens with all models, even ones that were working yesterday.

None of the solutions I've come across so far have made any difference (removing the {day} tag from the start GCode, rebooting the machine, deleting and reinstalling the application, etc.)

As far as I know nothing has changed on my machine so I'm stumped.

Does anyone know how to get around this problem?

**Comment by Prof62** [comment]
I've discovered that the same issue occurs on both my MacBook and windows 64 bit laptop and seems to be triggered by exiting the application and then going back in. Possibly as a result of reloading the profile (could it be getting corrupted somehow?)

Completely deleting the windows version and reinstalling it fixed the windows version (until the time I closed the application...) but I haven't been able to find all of the settings on the mac version so that remains dead.

Since the board is not flooded with these I suspect something about my configuration may be a factor - I've got the application configured for a RepRapPro Tricolour which has three nozzles. Possibly the third nozzle is the problem since support for more than dual extruders feels a bit undeveloped.

**Comment by Prof62** [comment]
UPDATE!!!

Changing the extruder count from 3 to 2 in the machine settings fixed the problem on my work machine (windows). Looks like there is a definite bug in the code that handles the settings for multiple extruders.

I won't be able to test the Mac version until I get home this evening but it looks promising.

**Comment by daid** [comment]
Cannot seem to reproduce this with the latest RC from http://software.ultimaker.com/Cura_closed_beta/

But, more then 2 extruders hasn't seen much testing lately. So please report any problems you find!

**Comment by Prof62** [comment]
Thanks, I'll do that.

I've been though exactly the same sequence here with the RC and can't reproduce it either so it looks like one of the changes from 14.01 to 14.03 has sorted the problem.

Is RC6 stable enough to install or am I better off waiting for an official release?

**Comment by daid** [comment]
RC6 contains 1 known bug, where the slicing fails sometimes. Triggering a re-slice with slightly adjusted position works around. Not ideal, but I haven't found the cause yet. Other then that, it's stable.

**Comment by Prof62** [comment]
Problem has been resolved in RC6 and later.
