### ISSUE TITLE
Project Planner crashes head into printed objects

### ISSUE THREAD

**Issue by illuminarti** [daid/LegacyCura#777]
As most recently pointed out by a user on the forum in this thread:

http://umforum.ultimaker.com/index.php?/topic/4724-did-cura-kill-my-fan/

Cura doesn't correctly account for the height of already printed objects when moving between objects in a multi-object one-at-a-time print.

As shown in this arrangement generated in 14.02-RC5 on a Mac; after printing the medium height block (middle column, 2nd row from the back) the head then moves to the front right corner of the buildplate, taking it right through the middle of the taller block already printed. 

![2014-03-09_11-49-25](https://f.cloud.github.com/assets/1836568/2368499/fa2a6d3e-a7ac-11e3-94ea-a6ba87d3b2ab.png)

![2014-03-09_11-48-54](https://f.cloud.github.com/assets/1836568/2368502/0f855c3e-a7ad-11e3-9736-4a5828e580dd.png)

The head needs to move above the highest object already printed during the moves, in order to avoid a crash.

**Comment by daid** [comment]
Fixed for next release.
