### ISSUE TITLE
Model file drag & drop disables plugins

### ISSUE THREAD

**Issue by KP721** [daid/LegacyCura#778]
Win 7 64bit
Cura 14.01

With plugins enabled, dropping a model file onto the program window causes all the plugins to be disabled. File->Load & File->Recent work OK.

Others have reported this behavior in this forum thread: http://forums.reprap.org/read.php?340,301181,322270#msg-322270

**Comment by nallath** [comment]
Have you tried this with the latest version (14.02 RC2)? It can be found at http://software.ultimaker.com/Cura_closed_beta/

**Comment by KP721** [comment]
It's 'fixed' in 14.03 RC7, the window is no longer a drop target.
