### ISSUE TITLE
Lines wrap in the Start/End-GCode window with no indication

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#78]
The Start/End GCode editor wraps lines longer than a certain length with no visible indication that it is doing so.

This seems undesirable to me since newlines are significant in GCode.

I would prefer either to not wrap lines (require scrolling left to right) or to place some sort of indentation + visible marker on wrapped lines.

I realize this may not be trivial to implement (especially the latter suggested solution), but I thought I'd throw it out there.

**Comment by daid** [comment]
I have a "wx.TE_DONTWRAP" in the editor style, which would not allow the GCode editor window to wrap lines. Which is also doesn't do for Windows and Linux. However, MacOS is kinda picky about it I guess.

But good to know the bug is there.

**Comment by daid** [comment]
I've updated the GCode editor with a different version that support syntax checking and highlighting. So this problem might be fixed now (or made much worse :P)

**Comment by RedwoodForest** [comment]
This is fixed. I will be filing some other issues against the editor though:).
