### ISSUE TITLE
Ooze shield overlapping support

### ISSUE THREAD

**Issue by pwnate** [daid/LegacyCura#784]
When I generate support the ooze shield ignores it and the two overlap. I am using two extruders; the first extruder builds the object and the second extruder generates the dissolvable support.
![cura - support ooze shield overlap](https://f.cloud.github.com/assets/2687850/2429284/8e72b5fa-ac76-11e3-9152-48b44f2a508a.png)

**Comment by daid** [comment]
I fail to see how this is an issue?
