### ISSUE TITLE
missing support material 

### ISSUE THREAD

**Issue by limitedslip** [daid/LegacyCura#787]
when i try to print with any cura v14 it puts support material on the inside of the part where needed but not on the outside of the part where there is a ledge that hangs over.  if i run the part threw cura v12.12a it prints great.  here is the file.  http://www.thingiverse.com/thing:275383  other than this cura is awsome. Thanks!

**Comment by nallath** [comment]
Do you have a screenshot of the wrong results?

**Comment by daid** [comment]
The support material generation is known to miss parts.

I'm closing this not because it's not an issue, but because there is no quick fix. It will require a total re-write of the support material code.
