### ISSUE TITLE
14.03: no UI for manual extruder movement

### ISSUE THREAD

**Issue by carbogit** [daid/LegacyCura#788]
Both the new Basic UI and the subset of Pronterface that are used in 14.03 do not provide an option to manually heat the hotend and move the extruder. That makes it impossible to change filament.

Basic UI: Hitting print starts heating bed and hotend, but 'cancel print' does not abort the heating.

**Comment by daid** [comment]
Aborting heating is impossible due to firmware limitations.

I'll gladly accept patches on the PronterfaceUI for heating/cooldown.
