### ISSUE TITLE
Cant control Temperature anymore

### ISSUE THREAD

**Issue by Pharaohabq** [daid/LegacyCura#791]
Controlling temperature in Cura has always been iffy. The new version 14.03 I tried out today, but now the job tab and temp tabs are just plain missing. (basic interface) I understand the need to simplify, but sacrificing function is not the way to do it.  Could you please put back in these functions, or enable temp control on the slicer interface?  I love How Cura Prints, but we need this function.

**Comment by daid** [comment]
There is a pronterface UI, it can be selected from the preferences. This has more features then the basic one (however, it does not have a heatup/cooldown feature right now)

This new interface is controlled by plugins and can be customized this way.

**Comment by Pharaohabq** [comment]
Right, I meant Pronterface when I said "Slicer" in my earlier post.   In anycase, it would be great to be able to control temperature directly as it's often nice not to have to cool things off then warm up again between prints.  The Pronterface does give better control over the Axis, but I'm unsure why Temp Control was left out. Unless, that is it hasn't been implemented yet...

**Comment by RichCattell** [comment]
Love the new Pronterface UI, but temp controls would be very useful. Also is it possible to add the Extrude/Reverse controls from the real Pronterface? Currently i use these controls in Pronterface to feed filament through the bowden tube into the hotend and to ensure that it is extruding correctly before starting a print. It you could add these then Cura could do everything.. no need for Pronterface anymore ;-)

**Comment by nallath** [comment]
It's not very likely that we will find the time to give it the love it deserves. There are some people already working on plugins to improve this interface. 
Most of our time is spent on creating a complete new interface, which might (or might not, sorry) make all of the USB stuff we have now obsolete.

**Comment by Dim3nsioneer** [comment]
@nallath and @daid : Is it maybe possible for you at this time to be already a bit specific about the planned USB changes? Are you working on USB communication changes or is the plugin-printer-dialog likely to disappear again with the new GUI? Can you give some kind of very, very rough timeline when the new GUI will be finished, not in a sense of a date - on which everybody will then expect it and complain if it becomes later - but in a sense like e.g. "there is no way it will be finished before October this year" or "don't expect it this year"? Just to get an impression which effort for improving the plugin print dialog now makes sense and which effort doesn't.
