### ISSUE TITLE
14.03 - delta stalls on small radii

### ISSUE THREAD

**Issue by ghost** [daid/LegacyCura#795]
Repetier firmware running on a delta: Buffer appears to underflow on small radii, causing nozzle to sit too long, decreasing overall print quality. Just verified that issue does not occur with 13.12.

**Comment by daid** [comment]
Most likely the same problem as: http://umforum.ultimaker.com/index.php?/topic/4842-1403-print-speed-error/

I fixed some code to fix: http://umforum.ultimaker.com/index.php?/topic/4601-cura-toleranceaccuracy/
Which caused this problem to pop up and go unnoticed before release.

**Comment by daid** [comment]
Assuming this is fixed in the latest RC
http://software.ultimaker.com/Cura_closed_beta/
