### ISSUE TITLE
Generating support Issue with free standing threaded objects. Cura 14.03

### ISSUE THREAD

**Issue by Opticalworm** [daid/LegacyCura#797]
Hello guys, 
recently I've been trying to print a part for a friend which have features that are threaded protruding from one of the sides. the thread comes out at 90 degree angle(see image). I was using Cura's default settings but with support enable. It will correctly add the support for the same part as long as the protruding part isn't threaded.

In the end I manage to print the part for my friend by setting Cura support threshold to 30 degree. That, unfortunately, forced everything in the model to be supported when I didn't need it to.

I've attached a couple of images and two test models that are virtually identical apart from one that doesn't have the thread.

![cure_model](https://f.cloud.github.com/assets/2886937/2494002/1a57f95a-b2b1-11e3-9e21-3702eb03856a.png)
![cure_gcode](https://f.cloud.github.com/assets/2886937/2494003/1b2c1cbc-b2b1-11e3-9c27-02be8fad4032.png)

you can file the test model here:
https://www.dropbox.com/sh/ylfqcsgcrh2s2it/BXYgZkxEdY

**Comment by daid** [comment]
I know the support generation code sucks right now. There are tons of issues like this.

I'm closing this, not because I do not acknowledge this issue. But because I have a huge internal issue about support material.
