### ISSUE TITLE
Integration of raft surface

### ISSUE THREAD

**Issue by Gregwar** [daid/LegacyCura#798]
I'm opening this issue to discuss the parameters for the raft surface when it will be integrated

I've done a lot of tests, using Ultimaker2 and PLA and this is my config:

```
raftBaseThickness = 300
raftBaseLinewidth = 1000
raftLineSpacing = 3000
raftBaseSpeed = 8

raftInterfaceThickness = 270
raftInterfaceLinewidth = 400
raftInterfaceLineSpacing = 1000

raftSurfaceThickness = 270
raftSurfaceLinewidth = 300
raftSurfaceLineSpacing = 275
raftSurfaceLayers = 2
raftSurfaceSpeed = 50
raftAirGap = 220

raftFanSpeed = 100

skirtDistance = 4000
skirtLineCount = 1
```

The raft base is thick and slow, this ensure the safety of the begining of the print.

The surface uses 300 of width and 275 of spacing, this makes the lines overlaps a little and the raft surface is then solid enough, avoiding it to break during unrafting

Adding the skirt helps, I don't know exactly how but it really does. Maybe it's just a problem of time (it would just delay the begining of the model over the surface), maybe it helps begining the extrusion on the actual layer.

If someone can do some tests and tell me how it works, I'm really interested!

With anchor line enable, this makes the print really safe. However, this uses more plastic and time, but I'm also experiencing a Makerbot Replicator2 sometime, and it's quite similar.

**Comment by daid** [comment]
What I was thinking, now we have 2 surface layers. Both are done in the same direction, wouldn't it be better to cross-hatch those at 90 deg angles?

I have made some slight tweaks to the settings, but that's mostly so I have less configuration settings in the GUI.

**Comment by Gregwar** [comment]
I didn't tried to 90° the two surface layer, I guess it should work too

**Comment by daid** [comment]
Done in the latest versions.
