### ISSUE TITLE
14.03 Issue with curved sections causing massive overextrusion

### ISSUE THREAD

**Issue by diderogit** [daid/LegacyCura#799]
When printing object with curved section, the speed slow down a lot on these curved part but with an extrusion speed too high causing overextrusion and bad result.
See photos, one is with Cura 14.02 and the bad one is with Cura 14.03:
![cura142](https://f.cloud.github.com/assets/7047260/2499502/61c856e4-b357-11e3-8718-1267d3f93515.jpg)
![cura143](https://f.cloud.github.com/assets/7047260/2499501/61c7cada-b357-11e3-994e-1ed15f1a127f.jpg)

Note : The bad appearance part was sanded a bit, so actually, it is worse than what can be seen on the photo.

**Comment by ianlee74** [comment]
I'm having the same problem but it doesn't seem to be limited to just the curved areas.  See discussion and  pics in this thread:

https://groups.google.com/forum/#!topic/deltabot/60IhJ_4Tf6E

![wp_20140530_001](https://cloud.githubusercontent.com/assets/1014801/3139837/02ac797e-e8f4-11e3-9b4c-2642319905ff.jpg)
![wp_20140530_003](https://cloud.githubusercontent.com/assets/1014801/3139839/18802016-e8f4-11e3-8632-45f493f47e1b.jpg)
![wp_20140530_004](https://cloud.githubusercontent.com/assets/1014801/3139840/22fd2250-e8f4-11e3-8997-205c66705de7.jpg)

(left is sliced with Slic3r, right with Cura 14.03)

**Comment by daid** [comment]
Should be fixed in the latest RC:
http://software.ultimaker.com/Cura_closed_beta/

(Cura was generating very verbose GCode)
