### ISSUE TITLE
request: Cura for armhf

### ISSUE THREAD

**Issue by RFranta** [daid/LegacyCura#800]
Hello,

I was able to install previous versions of Cura on my debian armhf device, but
the latest debian versions seems to be only for amd64 and i386, so download for ulitimaker webpage or install from github source doesn't work. Is there any other how to install latest version on debian armhf? Thank you

**Comment by daid** [comment]
You'll have to build it from source yourself. See the package.sh script how the i386 and amd64 versions are build. Should provide you with enough pointers to build an ARM version.
