### ISSUE TITLE
CuraEngine with Printrun (pronterface)

### ISSUE THREAD

**Issue by RFranta** [daid/LegacyCura#801]
Hello,
I would like to use Cura slicing engine in Printrun, I was succesfull with slic3r,
configuration looks like this:
slicecommand: slic3r.pl $s --load config.ini --output $o
sliceoptscommand: slic3r.pl --load config.ini --ignore-nonexistent-config

Can somebody help me with configuration for pronterface?

RFranta

**Comment by daid** [comment]
You can call the Cura python GUI for commandline slicing (see "python -m Cura.cura -h" for details)
For directly calling the CuraEngine, I rather referer to the source, as it's a bit more complex.
