### ISSUE TITLE
Slicing not completing if Tweak Plugin used 14.03

### ISSUE THREAD

**Issue by emtemt** [daid/LegacyCura#803]
Slicing a model (Windows 7) the processing bar goes solid white and stay there. No job time or material used or opportunity to save to SD.
Using 14.01 on the same PC the job time and material used displays work as expected.
Advice on forum indicated Plugin was the problem.
Removing plugin solved the problem
So I copied the plugin from 14.01 into 14.03 to try.
I now have the problem back. So the identical plugin works in 14.01 but not 14.03 so I am guessing 14.03 is the problem rather than the plugin.

**Comment by daid** [comment]
Which settings are used for the plugin? As the supplied plugin works for me when I try some different values.

**Comment by emtemt** [comment]
Hi

Problem must have related to model file in some way. Unfortunately it was a part under development and the original stl was overwritten. I did the same test this morning ready to send files to Stefan with the latest STL and it worked perfectly.
