### ISSUE TITLE
Print Settings gone in 14.03

### ISSUE THREAD

**Issue by bsprung** [daid/LegacyCura#806]
I just updated 14.01 to 14.03 and the print menu that controls temp, speed, and extrusions manually is gone.  The only features in the print menu now are print, cancel, and connect.  Is there a way to turn the full print menu with the tabs back on?

Thank you,

Brad

**Comment by nallath** [comment]
The one with the tabs is gone. You can change the rest with plugins. These can be found in the preferences.
