### ISSUE TITLE
Rectangular fill spacing below 25% is incorrect.

### ISSUE THREAD

**Issue by gkbeer** [daid/LegacyCura#807]
When decreasing fill from 25% to 24% the jump in spacing is greater than it should reasonably be. In general fill spacing below 25% are not being accurately created.

**Comment by Dim3nsioneer** [comment]
You just found the step where Cura changes from one infill type to the other. Below 25%, Cura draws lines in two directions on each layer, from 25% up it draws only lines in one direction per layer crosswise from layer to layer. Thus you get this jump in spacing.

**Comment by gkbeer** [comment]
If I understand this... 24% is a true volume-metric fill, and because <25% triggers bill in both directions, the spacing has to double. 

Therefor:
50% yields a fill of 1 line in 2 compared to a solid fill.
33.3% = 1 in 3
25% = 1 in 4
24% = ~1 in 10 but every layer gets hatching in both directions. 

I'd really like to be able to choose some of the other ratios that are between 1 in 4 and 1 in 10. 

Is there a setting I'm missing, that will allow that?

**Comment by Dim3nsioneer** [comment]
I would say 20% = 2 in 10 = 1 in 5 in terms of material amount.

**Comment by gkbeer** [comment]
To undensify this issue - Forget actual volume of material in the fill.  I really would like to have some way to make infill with a spacing in the range of between 1 in 4 to 1 in 10, when compared to solid fill. There are parts of a size where spacings of 1 in 4 are a higher density that I wish, and 1 in 10 are too wide to properly support the top surfaces. At present there seems to be no way to have cura generate spacings of 1 in 5,6,7,8 or 9.

**Comment by daid** [comment]
Will come later, not now.
