### ISSUE TITLE
Keyboard shortcut needed for inc and dec tool path layer in Layers view

### ISSUE THREAD

**Issue by garycmartin** [daid/LegacyCura#814]
With many layers it can be tricky to drag the slider a single layer at a time when you want to carefully check that a part is sliced correctly. Having keyboard shortcuts to increment and decrement the currently displayed tool path layer would be very handy (perhaps something like the '[' and ']' keys).

**Comment by TopherMan** [comment]
Shift + Up and Shift + Down is what you're looking for, I think.

**Comment by garycmartin** [comment]
Oh fantastic thanks, that works great! I couldn't find it in the docs/release notes, knew should have looked at the source before I posted :)
