### ISSUE TITLE
Edge detection does not recalculate when cut-off object is is used

### ISSUE THREAD

**Issue by MarvinTimmers** [daid/LegacyCura#816]
Hi Daid,

I think ran into a bug (i think), I want to make a print from a jpeg picture, I used cut-off bottom to remove the background. Now the effective part of my print is laying well in the printable area. I use Cura 14.03 for mac. 
Maybe this can be fixed in the future.

Regards,

Maaavin

![screen shot 2014-04-10 at 18 02 02](https://cloud.githubusercontent.com/assets/6040957/2670129/c4da4e8e-c0c9-11e3-9e03-dfd1288ff899.png)

**Comment by daid** [comment]
Won't fix, this would be very complex to do.
