### ISSUE TITLE
ConfigParser.NoSectionError: No section: 'alterations'

### ISSUE THREAD

**Issue by berkes** [daid/LegacyCura#82]
A clean install of HEAD (at 4a57502535bb7f7c29a39f5ff52cef4f1ff258af) , wizard skipped. 

On creation of Gcode, cura fails with:

```
Traceback (most recent call last):
  File "/home/ultimaker/bin/Cura/Cura/gui/simpleMode.py", line 170, in OnSlice
    oldProfile = profile.getGlobalProfileString()
  File "/home/ultimaker/bin/Cura/Cura/util/profile.py", line 182, in getGlobalProfileString
    for key in globalProfileParser.options('alterations'):
  File "/usr/lib/python2.7/ConfigParser.py", line 271, in options
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'alterations'
```

I assume there should be an additional line in the preferneces.ini.

**Comment by daid** [comment]
This problem happened if you had a fresh install and never modified any of the start/end gcode.

**Comment by berkes** [comment]
Is there anything you want me to put in a pull-request? A revised set of start-end gcodes for example?

**Comment by daid** [comment]
if you have better ideas for start/end code, then I'm all open for it. These are just slightly modified SF defaults.

**Comment by berkes** [comment]
I don't have any particular changes in mind. Just minor changes so that this issue is fixed would be enough IMHO.
