### ISSUE TITLE
z park position not taking cut-off into account

### ISSUE THREAD

**Issue by Dim3nsioneer** [daid/LegacyCura#820]
Hi Daid and Nallath

It's a minor thing, but maybe you can fix it on the fly at some point...
If a cut off is applied to the model, Cura ignores this when finishing the print and moves to a z position which on top of the model without cut off. E.g. if you specify a cut off of 100mm (to e.g. test how the very top of your print comes out) and let's say the remaining print has a height of 15mm, then Cura writes a G0 command going to a height of about 120mm after the print.

**Comment by daid** [comment]
Fixed!
