### ISSUE TITLE
Failed to copy CuraEngine.exe in package.sh

### ISSUE THREAD

**Issue by xiuxiu** [daid/LegacyCura#823]
Hi,

When I run package.sh under WIndows, I got the following error message:
g++ build/bridge.o build/comb.o build/gcodeExport.o build/infill.o build/inset.o
 build/layerPart.o build/main.o build/optimizedModel.o build/pathOrderOptimizer.
o build/polygonOptimizer.o build/raft.o build/settings.o build/skin.o build/skir
t.o build/slicer.o build/support.o build/timeEstimate.o build/modelFile/modelFil
e.o build/utils/gettime.o build/utils/logoutput.o build/utils/socket.o -o build/
CuraEngine.exe -Lbuild/ -lclipper -Wl,--large-address-aware -lm -lwsock32
mingw32-make: Leaving directory 'c:/Users/luoton/workspace/Cura-SteamEngine/Cura
Engine'
cp: cannot stat `CuraEngine/CuraEngine.exe': No such file or directory

I found CuraEngine.exe in the "CuraEngine/build/" folder not "CuraEngine/".  Is there any update needed here? Or I just missed something.

**Comment by abser** [comment]
Yes, I need to change it to 
cp CuraEngine/build/CuraEngine scripts/darwin/dist/Cura.app/Contents/Resources/CuraEngine

Otherwise it will not work.

For windows also need same change on line 319
 cp CuraEngine/bulid/CuraEngine.exe $TARGET_DIR

**Comment by daid** [comment]
The CuraEngine build environment has been changed, and the package.sh has not been updated to reflect this. This will happen soon.
