### ISSUE TITLE
Allow firmware retraction and Volumetric E units to be used with start.gcode.

### ISSUE THREAD

**Issue by whosawhatsis** [daid/LegacyCura#825]
The mainline Marlin version now supports Firmware retraction (using M207/M208 for configuration) and volumetric E units (using M200 for configuration), but the only way to enable these feature in Cura is by switching to the UltiGCode flavor, which disables the start codes needed to configure these and other parameters needed for printing with non-Ultimaker-2 printers. I'd like to request an option to have the start/end codes and the fwretract/volumetric extrusion options available at the same time.

**Comment by Dim3nsioneer** [comment]
Maybe it could be called something like 'UltiGCode light' flavour and be implemented as such?

**Comment by daid** [comment]
Actually, I rather call it a "RepRap (Volumetric)" option.

I'll just add that option right now, which sets the engine go firmware based retraction and mm^3 extrusion. But leaves all the configuration options intact.

**Comment by whosawhatsis** [comment]
Awesome. That sounds perfect, thanks @daid.

**Comment by daid** [comment]
Fixed in the latest RC at:
http://software.ultimaker.com/Cura_closed_beta/
