### ISSUE TITLE
Cura for ubuntu 14.04

### ISSUE THREAD

**Issue by zzeroo** [daid/LegacyCura#826]
Hi, my system is a Ubuntu 14.04 64bit one. If I build cura from source like explained in cura's README everything looks fine, the *.deb is build correctly. But if I start cura then I got this error:

```
cura
load preferences from /home/smueller/.cura/14.04-RC1/preferences.ini
Traceback (most recent call last):
  File "/usr/share/cura/cura.py", line 34, in <module>
    cura.main()
  File "/usr/share/cura/Cura/cura.py", line 80, in main
    from Cura.gui import app
  File "/usr/share/cura/Cura/gui/app.py", line 17, in <module>
    class CuraApp(wx.App):
AttributeError: 'module' object has no attribute 'App'
```

I need some hint where to start. I'm a C developer with Ruby experiences, but Python is not my daily driver ;)

**Comment by daid** [comment]
Ubuntu fucked up the python-wxgtk2.8 installation, causing "import wx" to fail as a proper import.

See: http://umforum.ultimaker.com/index.php?/topic/4905-cura-1403-crashing-on-kubuntu/
