### ISSUE TITLE
"Could not create more than X items" typo

### ISSUE THREAD

**Issue by whosawhatsis** [daid/LegacyCura#829]
The message "Could not create more than X items" shown when trying to multiply an object to get more copies than will fit on the platform has a typo. "Than" is misspelled as "then".

![screen shot 2014-04-26 at 11 21 52 am](https://cloud.githubusercontent.com/assets/319404/2809448/ad614dfe-cd6f-11e3-8236-a00f3293aec0.png)

**Comment by daid** [comment]
I wouldn't be shocked if there are 100's more like this  =)
