### ISSUE TITLE
Extruder gear diameter setup

### ISSUE THREAD

**Issue by HKoelman** [daid/LegacyCura#83]
I intend to use an alternative extruder, with a 20 mm drving gear, see http://www.thingiverse.com/thing:15897
However, this diameter is significantly lager than the standard one, and I assume this should be taken into account when generating Gcode. Could it be an option to confgure the extruder diameter somewhere in Cura?

**Comment by daid** [comment]
The only info you need is the instruction that says "With skeinforge >40 set M92 to about 315."
This 315 is the steps_per_e value, you can enter it in the preferences. Or you can add the M92 E315 in your start code.

The machine just needs to know how many step motor steps you need per 1mm of raw filament. That's what the M92 Exxx represents. If you change the bolt, you need a different amount of steps, simple as that.
