### ISSUE TITLE
100% infill

### ISSUE THREAD

**Issue by jenschr** [daid/LegacyCura#830]
Cura is currently under-calculating 100% infills. If printing with a transparent material, it is quite visible when compared to other slicers.

Example image here:
![cura_underextrusion_at_100_percent](https://cloud.githubusercontent.com/assets/550202/2826279/50f9e3ac-cf6b-11e3-81c8-4c45eb82ad61.png)
This was printed using Colorfabb XT, but the problem is also visible when using translucent PLA's from other vendors.

Settings used:
Cura: 14.1 / 14.3
Print speed: 25-50mm/sec
Infill speed: same as print speed
Fill density: 100%
Layer height: 0.2mm

This has been correct in former versions, but it must have been quite some time back. More details & discussion here: http://umforum.ultimaker.com/index.php?/topic/5498-100-infill/

**Comment by daid** [comment]
(Dealing with this on the forums)
