### ISSUE TITLE
no tag substitution in start.gcode

### ISSUE THREAD

**Issue by christarento** [daid/LegacyCura#831]
replaceGCodeTags seems to not be called.

```
;Print time: {print_time}
;Filament used: {filament_amount}m {filament_weight}g
;Filament cost: {filament_cost}
```

become

```
;Print time: #P_TIME#
;Filament used: #F_AMNT#m #F_WGHT#g
;Filament cost: #F_COST#
```

**Comment by daid** [comment]
Duplicate.

**Comment by christarento** [comment]
All other issues related to this problem are marked as closed.
Unfortunately, the problem still occurs in the last version 14.03.

You remove the call to replaceGCodeTags here : https://github.com/daid/Cura/commit/d47c7647daa9c8ca352967d8c5176d1a1dbeab71#diff-adc7639034316e55a3890d9aef2fc886

**Comment by hoppinghippos** [comment]
This issue still occurs in version 14.07. Is there any way to fix it?
