### ISSUE TITLE
Support overhangs

### ISSUE THREAD

**Issue by dtwrv6** [daid/LegacyCura#833]
Support for mid-part holes extend beyond part, but have no support below, and they curl / fold when printing in nylon.  See attached photo and ini file.  
![overhang](https://cloud.githubusercontent.com/assets/6277094/2927947/613f911e-d775-11e3-8119-85889fd50b28.jpg)

**Comment by daid** [comment]
Known problem, there is no fix for this right now. (There are a few other open support issues which cover this)
