### ISSUE TITLE
Double layer thickness for infill, etc.

### ISSUE THREAD

**Issue by yOyOeK1** [daid/LegacyCura#834]
idea for "fake quality improvement" 
I think it is possible to implement

http://yoyo.ghost.pl/Tmp/path3960.png

idea for solving created problems.
- print prime shell in first place ( then it will be possible to make more then one sub layer )

benefits of that solution are grate! 
- almost same speed of printing
- double or triple or quadruple (depends of sub layers count) visual quality

**Comment by Dim3nsioneer** [comment]
I remember @Daid having written about tests of such a principle in the Ultimaker forum.

**Comment by BagelOrb** [comment]
What you are requesting is a double layerThickness for the infill etc. except for the outer perimeter.
A lot of problems may appear.

**Comment by daid** [comment]
What has been implemented, for the PU release, is doing the sparse infill at thicker layers. Not the inner perimeters nor the skins.
