### ISSUE TITLE
Unsupported supports

### ISSUE THREAD

**Issue by mangtronix** [daid/LegacyCura#835]
For some models I get supports generated that are hanging in space.

![screen shot 2014-05-12 at 2 25 14 pm](https://cloud.githubusercontent.com/assets/35246/2944702/f686ca3a-d9d7-11e3-9cc5-8800d17bd24f.png)

STL file is available on Thingiverse: http://www.thingiverse.com/download:544104

**Comment by mangtronix** [comment]
Using Cura 14.03 on OSX Mavericks.

![screen shot 2014-05-12 at 2 25 42 pm](https://cloud.githubusercontent.com/assets/35246/2944729/738a4598-d9d8-11e3-95cd-43d49f67348b.png)

**Comment by loelkes** [comment]
I have the same issue. Cura 14.03 on Windows 7.
Support type is 'Touching buildplate'.

![cura1](https://cloud.githubusercontent.com/assets/231909/3093316/41f02798-e5b1-11e3-9fce-e341952df381.jpg)
![cura2](https://cloud.githubusercontent.com/assets/231909/3093315/41efe972-e5b1-11e3-8e42-40d18e2d3e59.jpg)
![cura3](https://cloud.githubusercontent.com/assets/231909/3093317/420172b4-e5b1-11e3-97a4-11cd95b0873c.jpg)

**Comment by mangtronix** [comment]
Awesome!
