### ISSUE TITLE
toolhead offset settings shown/not shown erroneously

### ISSUE THREAD

**Issue by whosawhatsis** [daid/LegacyCura#839]
When you open the "Machine settings" window, the toolhead offset settings are shown if you are currently using a machine with multiple extruders, and not shown if you are using a machine with single extruders. The is determined by which machine setting is selected in the "Machine" menu. If you use the tabs in the "Machine settings" window to try to edit settings for a machine other than the one that is currently selected, the visibility of these fields does not change. So if you have a single-extruder machine currently selected but want to modify the settings for a different machine that has multiple extruders, those settings won't be available, and likewise if you have a dual extruder machine selected from the menu but want to modify settings for a different machine that only has one extruder, you will see these settings even though they do not apply to the machine you are editing.

I hope I explained that adequately. It's a confusing issue that had me pretty vexed for a few minutes as I was trying to set up multiple machine types on a new machine. As a side note, there doesn't appear to be any way to import/export machine settings, only profile settings. Is this the case? What does it take to get a predefined machine profile added to the "Other Machine Information" page in the configuration wizard?

Tested in 14.03 for Mac.

**Comment by daid** [comment]
Currently you cannot import/export machine configurations yet.

If you want your machine added to the "other machines" page, that's easy. Quickest way is with a pull request like this one:
https://github.com/daid/Cura/pull/837
But I also accept the required ini file in the mail.

**Comment by daid** [comment]
Note, with the latest change, you still have to re-open the preference dialog after changing the amount of extruders. But fixing that is a much bigger problem.

**Comment by whosawhatsis** [comment]
Thanks, I'll do that.
