### ISSUE TITLE
Support stops being generated in some areas

### ISSUE THREAD

**Issue by amrbekhit** [daid/LegacyCura#840]
Hello,

I have a model of a card holder (STL can be downloaded here: http://helmpcb.com/misc/Card%20Holder.stl), that I printed in the past using Cura 14.03 adding support "Everywhere" and the support was generated fine (the support should be generated underneath the two small shelves on either side of the holder).

I've since changed a few settings in my printer (nozzle changed from 0.4 to 0.5, filament changed and recalibrated), and I've now come back to print the object and support is only being generated underneath one of the shelves.

Here are screenshots of all my settings:
http://i50.photobucket.com/albums/f337/TheHoplite/settings01.png
http://i50.photobucket.com/albums/f337/TheHoplite/settings02.png

Unfortunately, I don't have the last known working settings.

Any thoughts?

**Comment by amrbekhit** [comment]
Just an update - I've tried this same model in Cura 14.06 and I'm still facing the same problem.

**Comment by daid** [comment]
Note that support is crappy, and a lot of parameters actually effect it. The nozzle size could have effected the working support. You could play with the XY distance expert setting too see if that helps. But I cannot guarantee a lot about support (other then it being crappy)
