### ISSUE TITLE
Bad layer rendering

### ISSUE THREAD

**Issue by mwlang** [daid/LegacyCura#841]
Using latest Mac version of Cura, 14.03, I am having an issue with printing a model I've created in Blender 2.69 and exported as STL.  Basically, there's supposed to be a hole on the model/enclosure where a power cable goes, but the face is printing solid even though you can clearly see the hole in Cura's rendering onscreen.  Switching to Layers view shows the hole is not calculated and thus not printed.

I thought perhaps the STL model was exporting corruptly as I've printed several other models with no issues, so I recreated everything from scratch in Blender and tried again to same end results.

Rendered:
![enclosure_rendered](https://cloud.githubusercontent.com/assets/18387/2985796/dbe5df40-dc3e-11e3-9792-8d48bf3ad25b.png)

Layer 1:
![enclosure_layer1](https://cloud.githubusercontent.com/assets/18387/2985799/e6312d88-dc3e-11e3-94fa-a806a7a66b30.png)

Layer 2:
![enclosure_layer2](https://cloud.githubusercontent.com/assets/18387/2985801/ec14842a-dc3e-11e3-989e-680104b9d1eb.png)

Layer 12:
![enclosure_layer12](https://cloud.githubusercontent.com/assets/18387/2985804/f1b6396e-dc3e-11e3-9199-2a5f37f19ad1.png)

Blender rendering:
![enclosure_blender](https://cloud.githubusercontent.com/assets/18387/2985867/617cf92c-dc3f-11e3-887d-f6e63c99d97e.png)

All edges/faces of the model have been verified that there are no non-manifold edges/faces.

**Comment by JohanBraeken** [comment]
Hi,

You might want to play with the "Fix Horrible" settings in Expert mode. (Default is Type-A.)
(In the menu: "Expert", "Open expert settings", or CTRL+E)

Basically some holes are fixed automatically and this is not always what is intended.
