### ISSUE TITLE
No 3D render after Clear Platform on Ubuntu 14

### ISSUE THREAD

**Issue by RaD** [daid/LegacyCura#843]
To reproduce this problem I start Cura and add a model. The model is rendered well. Then choose File->Clear Platform. Platform becames empty. Adding any model to a platform starts the slicing process but the platform stays empty.

**Comment by daid** [comment]
Which view mode are you in? There is a bug that the layer view doesn't get properly refreshed in some situations.

**Comment by RaD** [comment]
Just update a local repo and rebuild package. Now it works fine.
