### ISSUE TITLE
Cura is dwarfing my prints

### ISSUE THREAD

**Issue by Mararuo** [daid/LegacyCura#845]
Hi, 

I have been printing for a while, and have never seen a slicer change the geometry of an object so that it does not match in any way the g-code depicted. I assume you know the Ultimaker robot pretty well, when I tried printing it, it came out a dwarf. What happened? What am I missing? already tried printing it from Cura 13.12, 14.01 and 14.03 from my Macbook. 
The slicing log looked clean. 
The firmware is the newest and I really am clueless as to what happened. 
![2014-05-19 22 01 30](https://cloud.githubusercontent.com/assets/7646698/3029799/3c79fcc6-e039-11e3-81de-566319b2cd1f.jpg)

**Comment by Dim3nsioneer** [comment]
What does the layer view show? Correct or incorrect height?
These are the common things to check with this effect on an Ultimaker:
- Is the last jumper of the z stepper jumper block NOT set (1/8 step)?
- Do you have any M92 command somewhere in the start.gcode or end.gcode which sets a wrong value for steps/mm on the z axis (should be 200*8/3 for the standard Ultimaker z thread)
- Do you have any z related hardware other than standard (different stepper drivers, different lead screw for z, ...)? Then settings maybe should be different than standard.
- Cross-check: Load known working settings from an older gcode file into Cura.

**Comment by Mararuo** [comment]
WOW,
Thanks for the amazingly fast response.
The layer view portrays the correct layer height, if not I would not have
been that surprised with the result.
There is no M92 command in the start or the end gcode.
The only hardware that is not standard is the hotend, an E3d with am001's
design from thingiverse, but this could not be the source of the issue. How
do I set the last jumper of the extruder stepper to 1/8 ? I am not very
savvy about this.
I have tried to upload some old but working gcode but cannot put it to work
in 14.03, the code is prior 12.07. I think it still was 12.06 back then.

Thanks again!

2014-05-20 18:30 GMT+02:00 Dim3nsioneer notifications@github.com:

**Comment by Dim3nsioneer** [comment]
Check this picture: http://wiki.ultimaker.com/images/thumb/El1.5.4-PCB.jpg/800px-El1.5.4-PCB.jpg
On the very right of the pcb you have the z stepper (upper row, btw: I wrote extruder instead of z axis above, sorry, I corrected it). There you can see that the third jumper is on the 'open' position.

**Comment by Mararuo** [comment]
Hey there,

Now I know which part you mean. Still the resolution of the picture is not
high enough to see in which direction the jumpers are directed. But I can
send you a picture of my PCB so that you can see by yourself how my jumpers
are oriented. The slightly flatter parts of the switches are pointing
toward the plugs of the stepper motors.

2014-05-20 19:34 GMT+02:00 Dim3nsioneer notifications@github.com:

**Comment by Dim3nsioneer** [comment]
@Mararuo 
About the picture: I think you may try to zoom in with your browser zoom; it's then visible quite well. It doesn't matter in which direction the jumper is oriented. The important thing is that the jumber does not connect the two pins.
Are you subscribed to the Ultimaker forum? If not I recommend you subscribe to the forum for future use. There you can upload pictures and you have a huge number of motivated UM users to help you with your issue(s). And it's not only Cura related; you will get information about nearly everything which has something to do with Ultimakers... :-)

**Comment by Mararuo** [comment]
Thanks for everything,
I am actually subscribed, I just have not used the forum in a while. I
think I will be participating a lot more since I have my own machines now
:)
I just took the last tab from in front the z Stepper and checked the
orientation. The orientations was right but the stepper was set to 1/16 th,
so with the last tab gone the stepper is set at 1/8 and the test print I
made is the right size. Again, thank you for your support. See you around!
Best regards,

Mararuo

2014-05-20 22:33 GMT+02:00 Dim3nsioneer notifications@github.com:

**Comment by daid** [comment]
Thanks for the assist Dim3nsioneer :-)
