### ISSUE TITLE
Print window layout is messed

### ISSUE THREAD

**Issue by trikko** [daid/LegacyCura#846]
On ubuntu 14.04 + Cura 14.03  print window is messed up:
- Temperature data are covered by buttons
- If my laptop is running on battery, warning message is shown white on grey.
- Widgets are not well placed :)

![curabug](https://cloud.githubusercontent.com/assets/647157/3046296/4fe209e0-e127-11e3-9f0a-b6066568ab03.png)

**Comment by getSurreal** [comment]
Same issue on OSX

**Comment by daid** [comment]
Duplicate of #818
