### ISSUE TITLE
Sailfish shake motors

### ISSUE THREAD

**Issue by villamany** [daid/LegacyCura#848]
Hi, thanks for the great job. 

Cura not seems to work very well with sailfish 7.6, accelerations cause the printer to shake too in certain parts. 
For example, in this one: http://www.thingiverse.com/download:139973 I have tried several slicers and Cura gives the worst performance printing with the same parameters.

**Comment by daid** [comment]
Too little information to really do something about it. Only got Marlin based printers here.
