### ISSUE TITLE
Fill issue.

### ISSUE THREAD

**Issue by Zikoel** [daid/LegacyCura#849]
Hi,

I don't know if it is an error of Cura or CuraEngine. I have compiled actual versione on my mac and I have this error whet change fill from 25% to 26%... I have capture some images.
![fill_24](https://cloud.githubusercontent.com/assets/6044789/3080548/1ae2efc8-e4b2-11e3-8c99-7f0abad73c1e.png)
![fill_25](https://cloud.githubusercontent.com/assets/6044789/3080549/1ae4f8ae-e4b2-11e3-8420-bf86123b7129.png)
![fill_26](https://cloud.githubusercontent.com/assets/6044789/3080550/1ae78fce-e4b2-11e3-9653-c6f93c2d719d.png)

Suggestion?

**Comment by daid** [comment]
The fill goes from cross-hatching to in 1 direction per layer between 25 and 26%.
