### ISSUE TITLE
Extrusion rate is incorrect when minimum feed rate is active

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#85]
There's a chance I've missed something here, so please let me know if I've missed something.

I created a simple small pyramid (http://www.thingiverse.com/thing:22340) to test different combinations of cool/temp/fan/minimum feed rate in an attempt to improve how tiny points print on my Ultimaker (i.e. in an attempt to avoid them coming out as large blobs of melted plastic).

I then generated GCode using several different settings for minimum layer time in Cura, and looking at the GCode I noticed something odd.

Once the minimum feed rate is reached the absolute amount of plastic extruded for a line changes depending on the min layer time setting. This seems wrong because regardless of the speed the same absolute amount of plastic should be extruded for a given line of the print, right?

Here are excerpts from some of my tests (full Gcode for both versions is at https://gist.github.com/bec59186bda4762486b2).

For both of these tests the minimum feedrate was set to 5mm/sec.

With cool set to 10 seconds the first layer to hit the minimum feed rate is layer 6. The extrusion amounts are nearly identical up until this point. Here's an except from layer 5 showing this:

;LAYER:5 (10 second cool)
;TYPE:WALL-INNER
G1 X98.512 Y98.512 Z0.95 F9000.0
G1 X101.488 Y98.512 F311.4831 E0.0272
G1 X101.488 Y101.488 E0.0544
G1 X98.512 Y101.488 E0.0817
G1 X98.512 Y98.512 E0.1089

;LAYER:5 (5 second cool)
;TYPE:WALL-INNER
G1 X98.512 Y98.512 Z0.95 F9000.0
G1 X101.488 Y98.512 F625.0678 E0.0272
G1 X101.488 Y101.488 E0.0545
G1 X98.512 Y101.488 E0.0817
G1 X98.512 Y98.512 E0.1089

But then on layer 6, suddenly things change and the extrusion amounts are very different:

;LAYER:6 (10 second cool)
;TYPE:WALL-INNER
G1 X98.587 Y98.587 Z1.1 F9000.0
G1 X101.413 Y98.587 F300.0 E0.0254
G1 X101.413 Y101.413 E0.0508
G1 X98.587 Y101.413 E0.0763
G1 X98.587 Y98.587 E0.1017

;LAYER:6 (5 second cool)
;TYPE:WALL-INNER
G1 X98.587 Y98.587 Z1.1 F9000.0
G1 X101.413 Y98.587 F592.3874 E0.0259
G1 X101.413 Y101.413 E0.0517
G1 X98.587 Y101.413 E0.0776
G1 X98.587 Y98.587 E0.1034

You can see that in this section the difference increases steadily to 0.0017mm by the end of the excerpt.

**Comment by daid** [comment]
It's Skeinforge, it has horrible rounding errors. I think it has to do with the way it internally stores the flowrate.

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
