### ISSUE TITLE
LCD display not functioning

### ISSUE THREAD

**Issue by ghost** [daid/LegacyCura#854]
The first time I open the JIFENG X Series 3D Printer, the LCD display was working well. After a while of preparing the printing procedure between the machine and CURA, it was totally off but the LCD light is still there. What seems to be the problem and how to solve this issue? Please help, Thanks

**Comment by daid** [comment]
Take it up with the producer of the JIFENG X Series 3D Printer. Printer problem, not a Cura problem.

**Comment by ghost** [comment]
daid, thank u for your reply, I appreciate it much. I just thought that it might be related to Cura.
