### ISSUE TITLE
Odd visualization when not starting at Z0

### ISSUE THREAD

**Issue by korpx** [daid/LegacyCura#857]
Cura 14.03 introduced an odd visualization in Layer view if you start your print at something else than Z0.

(I do not have home switches on my machine, and starts all prints with the extruder at Z120. start.gcode contains; G92 X0 Y0 Z120 E0)

This was sort of ok in earlier versions. Cura displayed the object in Layer view at Z-120, which is understandable as the renderer probably is not aware of what's in the start.gcode, but in 14.03 some of the perimeters of the object is placed at Z0 and the rest of it at Z-120.

![cura1403viz](https://cloud.githubusercontent.com/assets/1850308/3136160/3d4b3c48-e83e-11e3-8d5a-be309df5ec2d.jpg)

**Comment by korpx** [comment]
Let me add that the resulting gcode seems fine. It's the visualization that gets it wrong.

**Comment by daid** [comment]
This is fixed in the latest RC:
http://software.ultimaker.com/Cura_closed_beta/
