### ISSUE TITLE
No retraction on skirts

### ISSUE THREAD

**Issue by getSurreal** [daid/LegacyCura#858]
When printing with multiple parts the skirt outlines each individual part instead of one skirt for everything which is ok, but when it moves between object skirts it does not retract which leaves strings across the bed before the actual objects get started printing.

(Retraction is enabled and works when printing the actual objects)

Cura 14.03
OSX 10.9.3

**Comment by daid** [comment]
This is intentional, as this makes the skirt stick easier to the bed. If you retract the skirt gets pulled of the bed easier.

**Comment by getSurreal** [comment]
In that case it should be one continuous skirt

On 6/4/2014 6:40 AM, daid wrote:

> This is intentional, as this makes the skirt stick easier to the bed. 
> If you retract the skirt gets pulled of the bed easier.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/daid/Cura/issues/858#issuecomment-45080272.

---

This email is free from viruses and malware because avast! Antivirus protection is active.
http://www.avast.com

**Comment by Dim3nsioneer** [comment]
@getSurreal : Depending on your model you might make the skirt continuous by increasing the skirt distance in the expert settings.

**Comment by getSurreal** [comment]
@Dim3nsioneer:  Thanks for the suggestion.  The particular model that 
was giving me trouble was with several pieces that start small and have 
a lot of overhang in each direction thus preventing me from getting them 
close enough to each other to have one skirt. Increasing the skirt 
distance might solve it, but the bed is nearly full so maybe not.

On 6/5/2014 12:59 AM, Dim3nsioneer wrote:

> @getSurreal https://github.com/getSurreal : Depending on your model 
> you might make the skirt continuous by increasing the skirt distance 
> in the expert settings.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/daid/Cura/issues/858#issuecomment-45183612.

---

This email is free from viruses and malware because avast! Antivirus protection is active.
http://www.avast.com
