### ISSUE TITLE
Cosmetic dialog bug

### ISSUE THREAD

**Issue by StanleyKnife** [daid/LegacyCura#859]
I know this is only a minor matter, but thought I'd bring it to your attention:

![curaprinting](https://cloud.githubusercontent.com/assets/3235450/3145418/1c754226-ea36-11e3-802e-451d9ed7214e.jpeg)

**Comment by daid** [comment]
Should be worked around in the latest RC: (there are a few other reports on this same issue)
http://software.ultimaker.com/Cura_closed_beta/

**Comment by StanleyKnife** [comment]
Thank you!
