### ISSUE TITLE
problem to duplicate multiple objects in the Mac OSX version

### ISSUE THREAD

**Issue by airod101** [daid/LegacyCura#864]
because the version of OSX is limited compared to that of windows. In the Mac version is not possible to multiply the objects. There will be a new version that will fix this problem?

**Comment by getSurreal** [comment]
duplicate works on OSX for me with 14.03

On 6/6/2014 9:44 AM, airod101 wrote:

> because the version of OSX is limited compared to that of windows. In 
> the Mac version is not possible to multiply the objects. There will be 
> a new version that will fix this problem?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/daid/Cura/issues/864.

---

This email is free from viruses and malware because avast! Antivirus protection is active.
http://www.avast.com

**Comment by airod101** [comment]
Even with the version of OSX CURA 14:03 to the problem remains. You can not place more than 2 or more than 3 items. Each object has a gray rectangle as long as the area while in the Windows version you can place multiple objects to fill the floor and does not have the gray rectangle as the OSX version. In the version of windows you see the design of the printer witbox, which appears in the npn osx version. Someone has my same problem? I am attaching screenshots OSX AND WINDOWS No sense having to install parallers and windows. thanks

![screenshot 2014-06-10 09 32 07](https://cloud.githubusercontent.com/assets/7816512/3226712/ddbd831c-f071-11e3-84a8-a1d1134aeef3.png)
![screenshot 2014-06-10 09 29 37](https://cloud.githubusercontent.com/assets/7816512/3226711/ddba8c70-f071-11e3-97f8-bf9a8bb68ca7.png)
