### ISSUE TITLE
SD ini fail, nozzle holding temperature

### ISSUE THREAD

**Issue by kellsteinman** [daid/LegacyCura#865]
1.   I have a reoccurring "sd ini fail" which requires ejecting then reloading sd card in my Felix 3.0 printer.  Can you resolve this issue please ?
2.  I am not able to set holding temperatures in Cura which results in blocking nozzles. During a 3 hour print there was quite a delay in the support filament being reqd. as I had it set on "touching bedplate" and "brim".  The result was that the hips filament had been sitting @ 240 deg. for considerable time and it deteriorated.  How do I set a value to say 200 deg holding for the second nozzle?

**Comment by daid** [comment]
1) No. As we are not the Felix support department. Contact Felix.
2) Currently a lower temperature for unused heaters it not supported in Cura. This might be implemented in the future.

(Closing this issue due to 2 points in 1 issue, which is not a proper way to report issues)
