### ISSUE TITLE
problem to duplicate multiple objects in the Mac OSX version

### ISSUE THREAD

**Issue by airod101** [daid/LegacyCura#866]
Even with the version of MAC OSX  CURA 14:03 to the problem remains. You can not place more than 2 or more than 3 items. Each object has a gray rectangle as long as the area while in the Windows version you can place multiple objects to fill the floor and does not have the gray rectangle as the MAC OSX version. In the version of windows you see the design of the printer witbox, which does not appears in the MAC OSX  version. Someone has my same problem? I am attaching screenshots MAC OSX  AND WINDOWS No sense having to install parallers and windows. thanks Riccardo

![](https://cloud.githubusercontent.com/assets/7816512/3226712/ddbd831c-f071-11e3-84a8-a1d1134aeef3.png)

![](https://cloud.githubusercontent.com/assets/7816512/3226711/ddba8c70-f071-11e3-97f8-bf9a8bb68ca7.png)

**Comment by daid** [comment]
Most likely a witbox-configuration issue. Contact witbox support.
