### ISSUE TITLE
Server and HTTP API for Cura

### ISSUE THREAD

**Issue by jonnor** [daid/LegacyCura#867]
Greeting from Bitraf hackerspace in Oslo. I'm working on exposing our 3d-printers in such a way that users do not have to have all the 3d software on their machine (just a web-browser). Also experiementing with integrating 3d printers into larger digital fabrication pipelines. I'm using Octoprint on RPi for printer control, and would like to use Cura for slicing (on dedicated server).

I've started a prototype for a server which provides a HTTP restful API for Cura. Right now is is just calling cura --slice, but eventually I'd probably move to using a set of CuraEngine instances as workers. Code here: https://github.com/jonnor/Cura/tree/cura-server

Do you think this code fits as a part of Cura (separate executable), or should it be a separate project? Do you think it makes sense to use the engine-communication code found in Cura, or should one just talk to the engine socket directly?. Can I rely on this protocol to be faily stable, and is there any documentation for it?

**Comment by jonnor** [comment]
I decided to put it in a repo of its own: https://github.com/jonnor/CuraServer. The other questions are still standing.

**Comment by daid** [comment]
I think this should be a separate project. And might have some overlap with OctoPrint? (And a few other projects that are spawning right now)
