### ISSUE TITLE
Not retracting when moving from support

### ISSUE THREAD

**Issue by sahlin** [daid/LegacyCura#868]
Hello. Thank you for a great product.

Having some trouble with the support sticking to the object. Narrowed it down to maybe the slicer not retracting when moving from the support part.

Like this:

G1 F3000 X142.38 Y66.01 E4750.25857
G10
G0 F9000 X129.30 Y53.01
;TYPE:SUPPORT
G11
G1 F3000 X129.30 Y41.69 E4751.39057
G0 F9000 X129.30 Y41.85
G0 X126.64 Y41.85
...
Support, support, support
...
G0 X99.97 Y41.85
G0 X99.97 Y41.69
G1 F3000 X99.97 Y53.01 E4763.39257
;LAYER:45
G0 F9000 X99.97 Y54.25 Z12.66

Maybe it is because of the layer change is done at the end of the support?

Sahlin

**Comment by BagelOrb** [comment]
I suppose the problem is solved by now?
