### ISSUE TITLE
cura don't run in eclipse

### ISSUE THREAD

**Issue by sjavacat** [daid/LegacyCura#874]
printWindow.py no startPrintInterface function(method),some function(method) is duplicate

**Comment by nallath** [comment]
Uhm. What?

**Comment by sjavacat** [comment]
I  use Eclipse to run Cura source code, but he has a lot of mistakes, for example, the file cura.py, printWindow.startPrintInterface (options.printfile) of this sentence is wrong, the startPrintInterface is not found in the 
PrintWindow

```
                                                                                                        to nallath
```

**Comment by nallath** [comment]
I wouldn't know. We use pycharm for the development. Eclipse is a pretty rubbish IDE in my opinion, especially for python.
