### ISSUE TITLE
a letter to nallath

### ISSUE THREAD

**Issue by sjavacat** [daid/LegacyCura#876]
Your source code I cannot run, he seemed to need to configure some things, such as the third party modules.

What IDE are you  use to develope the cura?

Can you give me one Cura source program can run in IDE,or the third party modules ,such as PyOpenGL>=3.0.2
numpy>=1.6.2
pyserial>=2.6
power>=1.2
setuptools>=0.6.34
 and so on.

My email is 1746265859@qq.com,thank you very much!

**Comment by daid** [comment]
Cura is ran in python and we're using PyCharm.
