### ISSUE TITLE
Pause slice engine

### ISSUE THREAD

**Issue by CharlotteJansen** [daid/LegacyCura#877]
With the new slicing engine slicing superfast, the 'slicebutton' has been removed. When slicing big objects (where it still takes a while to slice) I miss the option to pause the engine untill i'm satisfied with the position, scale, settings, etc.

**Comment by daid** [comment]
http://umforum.ultimaker.com/index.php?/topic/6164-um2-cura-simple-suggestions-and-bugs-v1461/?p=56654

**Comment by CharlotteJansen** [comment]
Well ok :)
