### ISSUE TITLE
webGL crash

### ISSUE THREAD

**Issue by fluxline** [daid/LegacyCura#879]
While printing using the pronterface UI on windows, there was a crash in webGL on chrome browser raising a notification dialog from the graphics driver.  Something must have reset when dismissing the dialog and it caused Cura to crash, including the current pronterface and print stopped.  

know this is not an issue with Cura, can't be responsible for everything. But if possible, it might be nice to remove the dependency of the copy of python running pronterface from the one running cura.  even if the cura window is closed, pronterface is killed.

**Comment by daid** [comment]
They are 2 different applications, running in 2 different processes. If they manage to crash each-other then that's OS or driver related. Nothing I can do there.

**Comment by fluxline** [comment]
cura, browser, driver bringing each down ... clear. but it would be nice if the cura slicing engine window was closed during a print that pronterface would continue driving the print.  just a thought.

**Comment by daid** [comment]
Cura pre 14.03 did run the 2nd window in a 2nd process, caused all kinds of other problems on the code architecture.

**Comment by fluxline** [comment]
ok. thanks for the response.
