### ISSUE TITLE
Extrusion Width, CURA 14.07

### ISSUE THREAD

**Issue by umdpru** [daid/LegacyCura#887]
hello, 

This is my first issue post ever on GitHub so excuse me if it's somewhat amateurish. 

I downloaded and tried Cura 14.07 today (upgraded from 14.06). Setting first layer extrusion with [sic] to 200% resulted in the lines being much further apart but no additional extrusion to fill the gaps. This resulted in lines much further apart but gaps between the lines. The same part printed with CURA 14.06 results in an evenly filled first layer but with the smaller extrusion width. 

Like many other Slic3r converts, I really like the speed and efficiency of CURA but really need to have a wider first layer extrusion for bed adhesion.

**Comment by daid** [comment]
Your extruder most likely cannot keep up with the amount of material you are asking. The GCode preview of Cura calculates extrusion withs back from E values and shows the proper widths.
