### ISSUE TITLE
Still printing after was canceld

### ISSUE THREAD

**Issue by Killerregenwurm** [daid/LegacyCura#891]
///////////////////////////////////////////////
=> moved to https://github.com/Ultimaker/Ultimaker2Marlin/issues/38
///////////////////////////////////////////////
Hey guys,

I just recognize that Cura 14.07 (latest official Version and Firmware update) has some problems if the job was canceled.

I just pressed cancel for a job with very long edges. I know that the printing will stop if the printing Que of 20 "walks" is finished.
My problem is that during the "cancel is in progress" screen the nozzle is already cooling down and feeder is pushing also.
I used ABS and the temperature was very fast too low for printing but the Que wasn't empty and the feeder did not stop pushing.

I can think the best solution is to wait until the Que is empty before the nozzle is turned off. Or maybe it is also possible to stop the feeder if the job was canceled.

Greetings
Killerregenwurm

**Comment by Killerregenwurm** [comment]
just recognize that is is a firmware issue and not a cura one... damn sorry I try to correct this.

**Comment by whosawhatsis** [comment]
This could be fixed by adding an M400 to the cancel sequence.
