### ISSUE TITLE
Where is the entry of Cura open source code for Win7?

### ISSUE THREAD

**Issue by smallmule** [daid/LegacyCura#892]
Hi, I have downloaded the Cura source code of the latest version. Meanwhile, I have installed the software python2.7 and wxPython3.0-win32-3.0.0.0-py27 to develop Cura. I can't find the entry of the source code. Thank you!

**Comment by nallath** [comment]
I'm not sure what you mean by 'entry of the source code'.

**Comment by NoviceAt3DPrinting** [comment]
Whether you mean "Main program" of Cura?
