### ISSUE TITLE
Feature Request - UM1 3 point bed leveling without heated bed

### ISSUE THREAD

**Issue by Antiklesys** [daid/LegacyCura#898]
Would it be possible to have a check-box in the Cura first start wizard to select 3 point bed leveling system?
I understand this option auto enables if there's a heated bed, but would it be possible to have it also for 3 point beds on UM without a heated bed?

It would also be handy to have an option to choose whether the 2 points are on the front or the back of the machine, so that the levelling could be more accurate.

**Comment by daid** [comment]
I understand why you would want this. But, the bed-leveling wizard is made to support the normal Ultimaker cases. With everything else I cannot really guarantee anything.
I also do not want to add extra complexity to this dialog which could confuse new users (stuff is complex enough as it is)
