### ISSUE TITLE
skeinpypy is 'paving over' holes

### ISSUE THREAD

**Issue by jgeerds-zz** [daid/LegacyCura#9]
This is very similar to a slic3r bug: https://github.com/alexrj/Slic3r/issues/233 but I had this problem with spp b3... unfortunately I can't share the STL publicly.

**Comment by daid** [comment]
I took a quick peek at the STL yesterday (No worries, I won't share it, I don't even know what it is :P)

I noticed 2 things. First, SkeinPyPy crashed on the original file. Which is a bug in Skeinforge. Would be interesting to  fix.
Secondly, the model has a LOT of detail, much more then needed. Dunno if you can tune down the export details a bit, maybe it's paving over the holes because the "lines" of the circles are so small that it misses them.

**Comment by jgeerds-zz** [comment]
cloudnetfabb did "repair" the STL, and reduced it from 1800kb to 385kb, which means that it has either a lot less complexity, or a whole lot redundant data was removed. it is not a very high res model in my opinion, and it's a straight export from Alibre Design, which had sliced well before. The main issue with the "paving over" happens with the "repaired" file, where slic3r is successfully producing proper gcode, while SPP fills the holes.

**Comment by daid** [comment]
Most likely, cloudnetfabb changed the file from ascii to binary STL.

Another odd thing is, it slices fine at 50% scale. Skeinforge does report a few "errors", but in it's usually meaningless way that you still don't know what's wrong. I'm working on showing these errors in the 3D model view so you can see where the error is in your model.

The crash with the unfixed model is also not good. Smells like another bug in Skeinforge.

**Comment by jgeerds-zz** [comment]
If you think it's fixable, that would be great, but I would focus on the release first, and then fix this bug (in the mean time, slic3r does the job)

**Comment by tachyio** [comment]
Hmm I got this paving over problem today, when trying to print a bracelet I made at: http://www.thingiverse.com/thing:22787

Exported from Solidworks 2010 straight into an STL, I think it's binary. Anyway it was just a single layer, which I could peel off later.

I told Cura to print at 0.1mm layer height, with 0% fill.

**Comment by daid** [comment]
I think what happens is that the slice is made exactly on the same height as the vertexes, but because of some rounding errors it thinks there is no polygon there and thus makes a filled area instead of a hole. Slightly reducing the detail on the bracelet might help.

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
