### ISSUE TITLE
Start/End GCode editor allows for way too much horizontal scrolling

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#90]
The Start/End GCode editor allows for _way_ too much horizontal scrolling.

If the width of the editor window is X, then the amount of horizontal scrolling required to view the rightmost text in my start.gcode is something like 1.3X, but the editor allows for scrolling to something like 5X. It appears that it allows this much horizontal scrolling even for a file with no text in it at all.

It would ideally let you scroll horizontally only enough to view the rightmost edge of the text. 

It works correctly for vertical scrolling.

**Comment by daid** [comment]
Note, this is the same on Windows and Linux.

Not sure why the text editor does this. But it's better then line warping :)
