### ISSUE TITLE
[Zmorph3D] does not heat

### ISSUE THREAD

**Issue by cederom** [daid/LegacyCura#900]
I will mark Zmorph3D relates issues here to be solved, probably by myself, just to remember :-) Maybe you can add Zmorph3D issue label Daid? :-)

Setting desired temperature in the box has no influence on the printer behavior...

**Comment by nallath** [comment]
The 'proper' (if there is such a thing) to do this would be to create a fork and post your issues there. You will need to fork anyway in order to get your code merged.

**Comment by cederom** [comment]
ACK! Thanks for the hint! :-)
