### ISSUE TITLE
Feature request: option to disable fan during raft

### ISSUE THREAD

**Issue by Niksko** [daid/LegacyCura#906]
Would it be possible to add this option? Even disabling the fan in the main settings seems to be overrided by the raft. In addition it would also be nice to have the fan enabled but to disable it during the raft.

I often have issues with prints delaminating from the heated bed due to receiving cooling at such a low z height during raft printing. This defeats one of the purposes of printing a raft ie. bed adhesion.

**Comment by nallath** [comment]
Already implemented; PauseAtZ plugin has this functionality.

**Comment by daid** [comment]
Actually nallath, I think this is a bug somewhere, as the fan should be off during the raft...

**Comment by Niksko** [comment]
At the very least, the raft should obey the "enable cooling fan" checkbox. However I still think it would be useful to be able to disable the fan only during printing of the raft.

I should be more specific and say that the fan turns on while printing the interface layer(s) of the raft, and then turns off when printing the solid top layer. Even if this doesn't cause delamination from the bed, it usually causes the interface layer to not adhere properly to the bottom-most layer.

**Comment by rabe-** [comment]
in my case this leads me not be able to use rafts at all, since the fan this close to the bed causes my extruder to cool down to about 160°C, the heater is just not up to it^^

**Comment by mayhemer** [comment]
Any update on this issue?

**Comment by nicolinux** [comment]
Same here. Just wanted to print with colorFabb XT and don't need the fan full on this early (when using raft).

**Comment by mayhemer** [comment]
You can manually edit Cura 14.xx/Cura/util/sliceEngine.py and modify the following hard-coded line:

  settings['raftFanSpeed'] = 100

to something like 

  settings['raftFanSpeed'] = 0

Confirmed it work, no fan during raft.

**Comment by daid** [comment]
Latest beta from http://software.ultimaker.com/Cura_closed_beta/ also has the fan disabled. And a few more raft settings.

I cannot think of a reason why the fan should be on during the raft...
