### ISSUE TITLE
feature request: inches to mm and mm to inches scaling shortcuts

### ISSUE THREAD

**Issue by grimmy** [daid/LegacyCura#910]
It would be nice if the scaling UI had a short cut for setting the scaling factor to 0.254 and 25.4 although the later would rarely if ever be used.  So that people don't arbitrarily scale objects that have the wrong units

**Comment by daid** [comment]
No.

The 3D print world settled on mm as units. For good reasons. All software I have encountered can nicely export as mm. We share files in mm. 99.9% of the files online are in mm.

About 1.5% of the countries in the world use Imperial. The rest uses Metric:
http://3.bp.blogspot.com/-jdQMXJksLas/UOlwfEsPy4I/AAAAAAAABuA/1fq8QO113rE/s1600/800px-Metric_system_adoption_map.png

Everything in Cura is in metric units. The RepRap project (which can be seen as the origin of the 3D printer revolution right now) has been using metric units from the start.

Not adding a button for the 1.5% / 0.1%.

If you want to use barbaric units (as we call them in the office) you better remember the 25.4x

**Comment by grimmy** [comment]
Alrighty. I simple ran into one of those files and thought it might be nice
for people that don't know the conversiknnoff the top of their head...

**Comment by daid** [comment]
Warn the creator I would say.

**Comment by grimmy** [comment]
Already did :-)

**Comment by nallath** [comment]
The problem with this is if that it's easy to convert, there is no incentive to change. Its annoying for you on a personal level, but you're doing it for the greater good ;) 
To brighten your day a bit; http://s3.amazonaws.com/theoatmeal-img/comics/senior_year/science.png
