### ISSUE TITLE
Error opening Cura

### ISSUE THREAD

**Issue by don302** [daid/LegacyCura#911]
Ultimaker original newly built . Is operational. Preferences and Machine settings open, then freeze up. will not close without Quitting Cura.
The main screen is transparent; just showing desktop window.
There is no error message.
This is when using my main desktop computer.  Windows 7, pro.

Using an old laptop with windows Vista, I get the following error message : 
3D windows error
"exception access violation writing Ox08CD35CO
@sceneView.py-init3D View:905
@sceneView.pg:OnPaint:1007
@openingIGuiPaint:227 "
                 Can you help ?                      Don Smith.

**Comment by daid** [comment]
Most likely you haven't installed proper video-card drivers. Cura is using OpenGL, and the default crappy-video card drivers that windows comes with can display images, but pretty much fail at anything else.

**Comment by irminsul79** [comment]
i have a similar problem with a Lenovo T430U using Thinkpad USB Dockingstation.
the Software does start, but the screen where I would expact the model to be shown remains with whatever was there (on scrren) when the software startet. so remains of another windows (e.g. outlook or any other) are there where there should be the model.

is there any work around or additional information about the cause of this?!

**Comment by daid** [comment]
irminsul79, that's a driver issue for sure. Cura uses OpenGL. And that needs proper OpenGL drivers.

**Comment by mad12823** [comment]
I have a similar problem with a dell precision 7710.
The Software does start.
cura.exe has stop working
a problem caused the program to stop working correctly.

**Comment by BagelOrb** [comment]
Try Cura 2, it's way better than Cura 1.15

**Comment by Ghostkeeper** [comment]
Remember to update your video drivers, or applications will start crashing eventually.
