### ISSUE TITLE
How to merge my algorithm into the original Cura

### ISSUE THREAD

**Issue by NoviceAt3DPrinting** [daid/LegacyCura#912]
Dear,
    I have an novel algorithm in generation of support structure.
However, I have no idea how to merge my program into the original Cura.
Whether the kernel module of Cura is provided for verifying the proposed approach?
Thank you for your help.

**Comment by nallath** [comment]
I don't quite understand what you mean; but the generation of the support is done in the cura engine, which is a different project.
