### ISSUE TITLE
Print heading over holes even with combing enabled

### ISSUE THREAD

**Issue by jsquaredz** [daid/LegacyCura#913]
The tool path seems to still head over holes creating stringing even with combing enabled and retraction on.   

Here is the STL file I sliced in Cura 14.7

http://1drv.ms/1nygbS6

Here is the Gcode I got out of Cura
http://1drv.ms/WJqPvt

**Comment by daid** [comment]
I cannot seem to download those files.

**Comment by jsquaredz** [comment]
Sorry. Try again.  I remade the links above.

**Comment by nallath** [comment]
Still doesn't work.

**Comment by jsquaredz** [comment]
I am sorry.  Onedrive seems to have eaten my entire 3D modeling folder.  Will close this since the file seems to be vaporized.
