### ISSUE TITLE
line of code causes my threaded rod to jam. (z travel too fast)

### ISSUE THREAD

**Issue by rabe-** [daid/LegacyCura#915]
the gcode generated starts like this: 

;Layer count: 112
;LAYER:0
M107
G0 F9000 X25.25 Y82.83 Z0.20
;TYPE:SKIRT

and the "F9000" causes the problem. can it be changed so there is an option to limit Z travel speed? seperately from general travel speed.

**Comment by daid** [comment]
Limit the speed in your firmware.
