### ISSUE TITLE
Request: Honeycomb

### ISSUE THREAD

**Issue by rabe-** [daid/LegacyCura#916]
I know that it slows down printing, and the material is strong enough whith rectangular.. but:
-  it looks very awesome when printing transparent pla,
-  and some geometric shapes dont like rectangular. (seting an odd angle helps a bit though)

**Comment by nallath** [comment]
This discussion has been held multiple times already. This will not be implemented unless someone -proves- that it's better than the current infill system. We have a lot of work to do, so no time to implement features that make things 'pretty' in a very specific case.

**Comment by Klikini** [comment]
I also want this feature... is anyone willing to port the Slic3r method to Cura as a plugin?

**Comment by a4jp-com** [comment]
I use the honeycomb fill for attaching bolts to models in Slic3r. It is very useful. Bolts perfectly fit in the holes.

**Comment by Dim3nsioneer** [comment]
@Klikini : Are you aware that Cura plugins are postprocessors? Would be quite a task to produce a different infill pattern in a Cura plugin...

**Comment by Klikini** [comment]
@Dim3nsioneer No, I'm still very new to 3D printing/Cura. I guess that wouldn't work then, it would have to be ported into the Cura engine then I suppose.
