### ISSUE TITLE
cut off and max dimensions

### ISSUE THREAD

**Issue by MarcusWolschon** [daid/LegacyCura#918]
When an object is larger then the print volume but the "cut off object bottom (mm)" setting reduces it to a height that does fit,
Cura 14.07 still refuses to slice it.

PS:
help->about doesn't show what version number of Cura you are running and on the MacOS version this really should be Cura->about instead of help->about

**Comment by nallath** [comment]
The title bar of Cura shows the version number. Why should this be different on a MacOS? We prefer to have it look the same over all platforms as much as possible.

**Comment by daid** [comment]
Also the cutoff problem is a "won't fix", that's a bigger problem then you would imagine.

**Comment by MarcusWolschon** [comment]
You have it show the menu above the window, do you?
You have these X, - and + bubbles on the window frame?
So clearly you're contradicting yourself.
Either make the MacOS software behave like a MacOS software is supposed to
behave
or "make it look the same over all platforms as much as possible".
