### ISSUE TITLE
Feature Request: Support structure similar to 25% infill (with custom spacing maybe)

### ISSUE THREAD

**Issue by rabe-** [daid/LegacyCura#920]
i ran out of filament and had a big topless object with the infill exposed the other day.. 
i just took a close look, and the structure was both quite solid but also easy to pry away by hand, leaving next to no residue. 

imho that would make a great and quite universal support structure, because the grid is small enough to support even small things at bad angles, while still being able to remove it from them without damage. the implemented "box" support" is great, but often too strong, and the lines have the problem of being one angle only.

**Comment by nallath** [comment]
I believe we tried this, but it didn't work that well...

**Comment by Nandox7** [comment]
Someone sent me a pic of the type of support that S3D does for the parts.
Seems it gets super easy to remove it and it won't consume much filament.

![support_structure](https://cloud.githubusercontent.com/assets/117827/6802200/4a9ec52c-d226-11e4-8ac9-013a5eebec82.jpg)

This would be great to have in Cura. I often have lots of problem removing the support from smaller parts.

**Comment by BagelOrb** [comment]
Hello Nandox7, I am happy to hear that you will probably like the new support structure we ALREADY IMPLEMENTED! :D
It's called ZigZag and it's contained in the new Cura which hasn't come out yet.

PS: I think your post should have been a separate issue, since S3D support is not similar to the Cura infill.

**Comment by Nandox7** [comment]
That is great, thanks for the heads up.
Seems I have to checkout the code and check. :)

I can create a separate post  to request simillar support structure, but doesn't that new ZigZag will be
similar? I'm assuming from the name.

**Comment by BagelOrb** [comment]
No a new issue won't be needed as ZigZag is indeed very similar. The code is in the PinkUnicorn branch. 

I am closing this issue, since the original issue didn't work well according to nallath and Nandox7's issue is already implemented.

**Comment by Nandox7** [comment]
Cool. I've tried to compile PinkUnicorn but it's giving me errors.
Either way I suppose Cura UI is not yet updated to use it right?

**Comment by BagelOrb** [comment]
Nope, you would have to use it via the terminal/cmd. Also you would need libArcus (Ultimaker repo).

**Comment by Nandox7** [comment]
That lib I already have along with the Protobuf.
In the mean timeI managed to sort it out, it depends on the Makefile that is in use. 
(it fails when it needs to compile advancedSupport.cpp due to an error in the code of the import halfEdgeMesh.h)

I'll look into the cmd line option to see if I can run some tests.

**Comment by BagelOrb** [comment]
You need to use Cmake and the Cmakelists.txt. This in turn generates the correct Makefile...

**Comment by BagelOrb** [comment]
./CuraEngine -v -s filamentFlow=100 -s layerThickness=100 -s initialLayerThickness=300 -s supportZDistanceBottom=150 -s supportZDistanceTop=150 -s supportBottomStairDistance=500 -s initialSpeedupLayers=4 -s minimalFeedrate=10 -s preSwitchExtruderCode= -s insetXSpeed=30 -s retractionZHop=0 -s extruderOffset3.X=0 -s extruderOffset3.Y=0 -s gcodeFlavor=GCODE_FLAVOR_ULTIGCODE -s postSwitchExtruderCode= -s retractionSpeed=40 -s retractionPrimeSpeed=30 -s infillOverlap=15 -s inset0Speed=20 -s coolHeadLift=0 -s extrusionWidth=400 -s upSkinCount=6 -s initialLayerSpeed=20 -s minimalLayerTime=120 -s infillSpeed=40 -s fanSpeedMax=100 -s enableCombing=1 -s fanSpeedMin=100 -s supportXYDistance=700 -s supportExtruder=-1 -s supportType=ZIGZAG -s supportZDistance=150 -s supportOnBuildplateOnly=0 -s supportAngle=60 -s supportJoinDistance=600 -s supportSpeed=20 -s supportConnectZigZags=1 -s supportAreaSmoothing=600 -s supportMinimalAreaSqrt=1000 -s supportTowerDiameter=2000 -s supportTowerRoofAngle=65 -s filamentDiameter=1128 -s fanFullOnLayerNr=2 -s extruderOffset1.X=18000 -s extruderOffset1.Y=0 -s endCode=M25 -s minimalExtrusionBeforeRetraction=20 -s retractionMinimalDistance=1500 -s retractionAmount=4500 -s retractionPrimeAmount=4500 -s skinSpeed=25 -s skinPattern=SKIN_LINES -s startCode=";FLAVOR:UltiGCode
;TIME:14228901
;MATERIAL:3058
;MATERIAL2:0" -s skirtDistance=0 -s skirtMinLength=150000 -s skirtLineCount=10 -s skirtSpeed=30 -s extruderOffset2.Y=0 -s extruderOffset2.X=0 -s fixHorrible=1 -s layer0extrusionWidth=400 -s moveSpeed=150 -s supportLineDistance=2666 -s retractionAmountExtruderSwitch=16500 -s sparseInfillLineDistance=2000 -s insetCount=2 -s downSkinCount=6 -s multiVolumeOverlap=150 -s position.X=115000 -s position.Y=112500 -s position.Z=0 -s infillPattern=INFILL_ZIGZAG -s extruderNr=0 -s avoidOverlappingPerimeters=1 -s neith=0 -o "test.gcode" "test.stl"

**Comment by Nandox7** [comment]
Thank you, that is perfect.
Gave it a try using the testModel.stl but it seems to be going a bit nuts.

![selection_005](https://cloud.githubusercontent.com/assets/117827/6846091/39a9f69a-d3b3-11e4-970b-bcfa6dfddb5c.png)

**Comment by BagelOrb** [comment]
try to view it in another viewer.
For example http://chilipeppr.com/tinyg

**Comment by BagelOrb** [comment]
Oh dear it seems a major bug has been introduced! Those weird lines aren't supposed to be there! Let me fix that.

**Comment by BagelOrb** [comment]
Sorry! wrong settings! :S
Here you go:
./CuraEngine -v -s filamentFlow=100 -s layerThickness=100 -s initialLayerThickness=300 -s supportZDistanceBottom=150 -s supportZDistanceTop=150 -s supportBottomStairDistance=500 -s initialSpeedupLayers=4 -s minimalFeedrate=10 -s preSwitchExtruderCode= -s insetXSpeed=30 -s retractionZHop=0 -s extruderOffset3.X=0 -s extruderOffset3.Y=0 -s gcodeFlavor=GCODE_FLAVOR_ULTIGCODE -s postSwitchExtruderCode= -s retractionSpeed=40 -s retractionPrimeSpeed=30 -s infillOverlap=15 -s inset0Speed=20 -s coolHeadLift=0 -s extrusionWidth=400 -s upSkinCount=6 -s initialLayerSpeed=20 -s minimalLayerTime=5 -s infillSpeed=40 -s fanSpeedMax=100 -s enableCombing=1 -s fanSpeedMin=100 -s supportXYDistance=700 -s supportExtruder=-1 -s supportType=ZIGZAG -s supportZDistance=150 -s supportOnBuildplateOnly=0 -s supportAngle=60 -s supportJoinDistance=600 -s supportSpeed=20 -s supportConnectZigZags=1 -s supportAreaSmoothing=600 -s supportMinimalAreaSqrt=1000 -s supportTowerDiameter=2000 -s supportTowerRoofAngle=65 -s filamentDiameter=1128 -s fanFullOnLayerNr=2 -s extruderOffset1.X=18000 -s extruderOffset1.Y=0 -s endCode=M25 -s minimalExtrusionBeforeRetraction=20 -s retractionMinimalDistance=1500 -s retractionAmount=4500 -s retractionPrimeAmount=0 -s skinSpeed=25 -s skinPattern=SKIN_LINES -s startCode=";FLAVOR:UltiGCode
;TIME:14228901
;MATERIAL:3058
;MATERIAL2:0" -s skirtDistance=0 -s skirtMinLength=150000 -s skirtLineCount=10 -s skirtSpeed=30 -s extruderOffset2.Y=0 -s extruderOffset2.X=0 -s fixHorrible=1 -s layer0extrusionWidth=400 -s moveSpeed=150 -s supportLineDistance=2666 -s retractionAmountExtruderSwitch=16500 -s sparseInfillLineDistance=2000 -s insetCount=2 -s downSkinCount=6 -s multiVolumeOverlap=150 -s position.X=115000 -s position.Y=112500 -s position.Z=0 -s infillPattern=INFILL_ZIGZAG -s extruderNr=0 -s avoidOverlappingPerimeters=1 -s neith=0 -o "test.gcode" "test.stl"

**Comment by Nandox7** [comment]
Thanks! Looking good now.
Will support for this engine will be added in Cura's PinkUnicorn branch?

**Comment by BagelOrb** [comment]
The new Cura will have the CuraEngine from the PinkUnicorn branch as the backend.
