### ISSUE TITLE
Feature Request: Remember print position of previously printed object 

### ISSUE THREAD

**Issue by mmemetea** [daid/LegacyCura#921]
That would prevent having to clean the bed (annoying especially when using hairspray) and allow for optimization of the printable surface when printing objects not all together.
By default, Cura would leave the footprint of the previous parts, until dismissed by the user (with the option "Delete all objects" for example).

**Comment by daid** [comment]
I can see your use-case, but I will not implement it. Sorry.

**Comment by mmemetea** [comment]
Thanks for the feedback. I can understand that the feature request are flooding.
Keep up the awesome work anyway... Michaël.
