### ISSUE TITLE
Firmware install: mendel based:  Add support for 1284p 

### ISSUE THREAD

**Issue by ghost** [daid/LegacyCura#923]
Sanguinololu, Gen7, OpenHardware.co.za controllers etc - several machines use the Gen7 bootloader on a ATmega 1284p
When trying to flash Hex using Cura it fails with unrecognised signature:

Protocol: stk500v2
Upload speed: 115200

**Comment by daid** [comment]
Code is only tested on the ATMega2560. (As all the machines I have access to are build on that) Feel free to patch the code at Cura/avr_isp which is the bootloader communication implementation.

Note that I highly recommend against using Gen7 electronics. Due to this:
https://github.com/ErikZalm/Marlin/blob/Marlin_v1/Marlin/pins.h#L209
Which greatly increases the chance for this to happen:
http://www.soliforum.com/topic/6608/beware-your-3d-printer-they-can-cause-fires/

**Comment by Traumflug** [comment]
> Due to this: https://github.com/ErikZalm/Marlin/blob/Marlin_v1/Marlin/pins.h#L209

This just demonstrates how outdated Marlin is. This behaviour was changed, uhm, I think three years ago.

And your offense against non-ATmega2560s nicely demonstrates how Cura apparently tries to meet this outdatedness. We have plenty of CPUs these days: ATmega328, ATmega644, ATmega1284, ATmega2560, ARM Cortex-M0, ARM Cortex-M3, ARM Cortex-M4, the latter three in various flavours.

**Comment by daid** [comment]
Marlin needs contributions for just about anything that's not Ultimaker, as the main developers have Ultimakers. Hardly makes it outdated.

We have plenty of CPUs. But I don't have them. Simple difference. (Hardly would call it an offence. But feel free to ignore me and my software)

**Comment by Traumflug** [comment]
> We have plenty of CPUs. But I don't have them.

And this makes you feel like blasting away any request to support such hardware by simply closing (and hiding) it on the spot? I mean, it's your project, not mine, but I'm pretty sure offending possible contributors isn't exactly the best way to receive these missing patches.

Regarding the original request: the only noticeable difference between Gen7 bootloader (_not_ Gen7 hardware, Gen7 bootloader and Gen7 hardware are two entirely different things) and other bootloaders is, the Gen7 one waits 3 to 4 seconds for a programmer after reset, before jumping to the real firmware, to support hardware without auto-reset / needing manual reset. And being impatient at startup, like sending M105 every second to see when the firmware responds, causes this bootloader to wait forever.

And before you ask: Gen7 hardware does support auto-reset. :-)

**Comment by ghost** [comment]
"Code is only tested on the ATMega2560."   Well thats why I offered you the relevant info so that I can test it.  I ship ATmega 1284ps with my printer kits because it works (in no small part to the awesome and open always happy to take advise and listen to his community which is Traumflug's Gen 7 but besides the point:  As Traumflug says "I mean, it's your project, not mine, but I'm pretty sure offending possible contributors isn't exactly the best way to receive these missing patches."

This is exactly how I now feel  - like an idiot spent a weekend building Cura profiles for our part of the community - thinking how great I could promote Cura as an alternative to pronterface - especially since it has build in .hex upload (replacing my https://github.com/openhardwarecoza/OPHW-SW-AVRLoader project that accompanies pronterface, etc with an all in one would have been great) 

Moreover, who cares about Marlin - or am I mistaken that this is CURA's ISSUE PAGE here??? - I have no intention of using ever installing Marlin on any controller I own!  Between Teacup's speed and  Repetier's well commented feature set I'm set.  Plus I take responsibility for the Hex files I supply my customer - which doesnt explain why a simple request for a additional signature is such a big deal?  But fine I guess when open source developers get a paycheck the community always come second.

Thank you but I am proceeding to delete all Cura content! I will use something else, something open, something true, something built by a community minded community of like minded individuals.

**Comment by daid** [comment]
Do whatever you wish. Just note that I work on this issue tracker on a certain way. https://github.com/daid/Cura/wiki/Issue-policies
Which means that feature requests that I will not implement will get closed. I'm just a single person, I get about 20 requests per week. Got other stuff to do then argue about support for hardware&software I do not have access to. And I have trouble enough to get the issue tracking in manageable forms.

Not to mention you pretty much come barge in here say "this won't work, fix for me!" and are surprised that I'm not going to honor that request.
