### ISSUE TITLE
No profile stored in gcode

### ISSUE THREAD

**Issue by D-Byte** [daid/LegacyCura#925]
In Cura 14.07 the profile settings are not stored in the gcode. This was always a handy feature that i used a lot. Is it broke or is it predicated?

**Comment by daid** [comment]
Which settings are you refering to exactly? The PROFILE_STRING or something else?

**Comment by D-Byte** [comment]
the ;CURA_PROFILE_STRING: in the gcode the string you can load by "load profile from GCode..."

**Comment by daid** [comment]
It was messing with the BitsForBytes machines (causing firmware crashes for them).

To get that line, you need to have ";{profile_string}" at the end of you end GCode.
