### ISSUE TITLE
Its always the first time

### ISSUE THREAD

**Issue by erikstiff** [daid/LegacyCura#930]
After the last update every time i close and open cura...Its like the first time i running the software..it ask me to configure my machine...It also bugs out more often than the previous version..I'm a noob in 3d printing...but I love to learn and this as been a good experience..

**Comment by daid** [comment]
MacOS or Windows?

**Comment by erikstiff** [comment]
I use both systems, but in this case I'm referring to windows.

**Comment by daid** [comment]
On some installs (both MacOS and Windows) the settings are not properly stored.

They are unrelated problems (on Mac and Windows) but they act the same. I tried a workaround in a test version at:
http://software.ultimaker.com/Cura_closed_beta/

But I haven't had reports back if it solves the problem. If you could test it, that would be great.
