### ISSUE TITLE
Slightly Improved Pronterface GUI

### ISSUE THREAD

**Issue by InnovationSystemsAU** [daid/LegacyCura#931]
Hi Guys,

I slightly improved the stock Pronterface GUI just so it makes a little more sense. I have some young kids using the machine and they always get a bit confused with the direction stuff is going. It's a simple change and slots right in with no other mods. Would be cool to see it on the next release.

![image](https://cloud.githubusercontent.com/assets/6505805/3874596/d6c2df46-2143-11e4-93ab-91a38ded97b1.png)

**Comment by daid** [comment]
Cool. Thanks. I'll put it in the next version.
