### ISSUE TITLE
Pink Unicorn GUI broken on Linux

### ISSUE THREAD

**Issue by martinxyz** [daid/LegacyCura#933]
The master branch works well on Linux (debian testing), but the pink unicorn GUI is unusable:

https://www.youtube.com/watch?v=uoz2YNTEBl0

Any ideas? I tried installing only python-wxgtk3.0 or only python-wxgtk2.8, both with the same result as in the video. (I also removed both packages, to confirm that it stops running.)

I wanted to test and attempt some hacks to the latest CuraEngine (which seems to be the pink branch) but this forces me to update the Cura GUI as well.

**Comment by daid** [comment]
Actually, the latest PinkUnicorn GUI is at https://github.com/daid/Cura2 not in the branch.

**Comment by daid** [comment]
Note that I'm working on that code, refactoring a lot of code, some parts are broken. I'm re-organizing things to support more advanced features and cleaning up old hacked together code. This means it could break at any moment in time.

**Comment by martinxyz** [comment]
Thanks! With the right repository it works (and looks great). I can find my way around breakage to some extent. I only want to be able to play around with the latest development, I don't expect it to be bug-free :-)

**Comment by martinxyz** [comment]
I guess the real problem was that it looked as if this was the latest active development version. Are you planning to continue work on the PinkUnicorn branch in this original Cura repo? If not, maybe the branch should be renamed to _obsolete, or deleted.

**Comment by daid** [comment]
No, that branch needs to be deleted, but I didn't get around to do it yet.

**Comment by jonnor** [comment]
@daid is https://github.com/daid/Cura2 still the current GUI for PinkUnicode branch? I do not see any activity since November.

**Comment by BagelOrb** [comment]
No it is not...
