### ISSUE TITLE
To little support structure for object

### ISSUE THREAD

**Issue by bottenberg** [daid/LegacyCura#935]
When selecting support structure to be printed only a very tiny bit will be supported. This way this object can't be printed. It needs full support.

![curasupportstructure](https://cloud.githubusercontent.com/assets/7294241/3911156/a99f8578-231e-11e4-85e6-4d5443939250.png)

**Comment by daid** [comment]
Play with the support overhang angle in the expert settings.

(There are many problems with the support code, we know this, but no fix is in sight right now)

**Comment by bottenberg** [comment]
Dankjewel voor je reactie. Het is me nu eindelijk gelukt om dit te printen.

2014-08-13 21:26 GMT+02:00 daid notifications@github.com:
