### ISSUE TITLE
Feature Request: Change Infill Flowrate over layer or height

### ISSUE THREAD

**Issue by SturmGhost** [daid/LegacyCura#939]
Would be nice to have an option for changing the Infill flowrate (not the over all flowrate) over the layer (height) to tweak some infill errors on some parts.

**Comment by daid** [comment]
If you have infill flow problems, then I'm pretty sure you have over-all flow problems.

**Comment by InnovationSystemsAU** [comment]
That said, you can achieve a better top finish often if you can cut the flow back to say 98-99%. That reduces the dag buildup on the overlaps of the perimeters.

**Comment by gharris012** [comment]
I have first-layer problems (warped bed, womp), so I made a plugin to change the flow-rate on specific print types (based on the "TYPE:" comments). I have it set to pick up SKIN, but you should be able to change it pretty easily to work with FILL.
https://github.com/gharris012/FlowTweak
