### ISSUE TITLE
printed differently than normal preview

### ISSUE THREAD

**Issue by cher3d** [daid/LegacyCura#941]
the object printed differently than was given in the normal preview. Interestingly enough, the layers preview was consistent with what ended up being printed. It was missing parts of the last few layers, but not others, despite the fact that they started at the same level.

**Comment by daid** [comment]
This happens if there are holes in the model. Check the the XRay view to identify the troubled areas.

**Comment by cher3d** [comment]
the x-ray view is fine. when printed larger the discrepancy went away: just a deficiency of cura not knowing printer limitations I guess.
