### ISSUE TITLE
Unicode Character Problem

### ISSUE THREAD

**Issue by ghost** [daid/LegacyCura#942]
Hi;

I'm trying to translate the Cura to my language (Turkish). Turkish requires some unicode characters such as öçşü etc...

When I convert the string "Load" into "Yükle" the program stalls on the splash screen. I guess it doesn't accepts unicode characters. Is there any way around this?

Thanks.

**Comment by hanxiaomax** [comment]
Try `u"Yükle"`  and `#coding=utf-8`at the begin of the file

But it is not a good way to translate to your language by modifying the source code,
You should use `.pot` file in `resources\locale` to create a new translate project.

**Comment by ghost** [comment]
Thaks for the reply;

At first my plan was exacly to create a new translation file. But i couldn't find a way to see the effect of changes in the actual program.

So if we say I want to create a new translate project, what should be the procedure for that?

**_Edit**_

I think I just found the way. First I must edit the source code and add&activate another language. Than I must create a new file for that language (in case 'tr' for Turkish). Than I have to edit the .po to .mo by Poedit language editing software. Thats all...

Sory for interrupting you with my noob questions. Thanks for your time. :)
