### ISSUE TITLE
Top infill uses infill speed instead of printing speed

### ISSUE THREAD

**Issue by MarkEstefanos** [daid/LegacyCura#944]
If I set my printing speed to 20mm/s and my infill to 130mm/s, I would expect infill to be 130mm/s but the top and bottom surfaces as defined by "bottom/top thickness" to print at 20mm/s. That is not the case, the top and bottom layers print at the infill speed.

**Comment by daid** [comment]
Top&bottoms are considered as infill.

**Comment by MarkEstefanos** [comment]
But surely you see the benefit of being able to print the top and bottoms at a different speed than the interior?

**Comment by daid** [comment]
Yes, I see the benefit, however, due to how the code is structured, the distinction between "sparse infill" and "top/bottom infill" is lost before speeds and a few other settings are applied. As they are combined into a single "infill" section which is printed at once.
