### ISSUE TITLE
Changing start/end GCode in editor causes error and changes are often not saved

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#95]
When I change the start/end GCode in the editor an error is displayed in the Console and the changes are often not saved. This may be related to the new editor.

Here's the error. A separate message is displayed for each character I type in the editor:
May  6 13:20:50 lj_laptop python[14917] <Error>: CGContextRestoreGState: invalid context 0x0
May  6 13:20:51 lj_laptop python[14917] <Error>: CGContextRestoreGState: invalid context 0x0
May  6 13:20:51 lj_laptop python[14917] <Error>: CGContextRestoreGState: invalid context 0x0

**Comment by daid** [comment]
I think it's another one in a long line of wxWidget bugs for MacOS. I've changed it so MacOS uses the old text editor again, so lines will wrap again, but that's better then not saving data.

**Comment by fuegas** [comment]
> CGContextRestoreGState: invalid context 0x0

This is being thrown by wxWidgets when you clear all characters on a line. 
It is an annoying message, but not harmful. Neither can we fix this in Cura.

**Comment by RedwoodForest** [comment]
Okay, good to know the message wasn't related to the lack of saving.

I do see the message every single time I enter or delete a character, though, not just when a the last character in a line is removed.

I'm assuming your commit fixed the saving issue. If so, thanks!

**Comment by fuegas** [comment]
Yeah, after further investigation I noticed that as well.
However, I do not know a fix for the message :(

The commit fixes the saving issue indeed.
