### ISSUE TITLE
Poor Top Surface Finish Problem

### ISSUE THREAD

**Issue by InnovationSystemsAU** [daid/LegacyCura#956]
Geday,

I've been having some issues with getting really good top surfaces on parts using Cura. I'd rather stick with Cura because everything else is better and I enjoy not having hundreds of options to mess up.

The issue I'm having right now is I cannot get a really smooth top surface. It appears on the top layer, it over extrudes a bit, and it ends up with a rough, gooey looking surface. I have tried a number of things, including reducing temp, reducing speed and tweaking the flow rate, but I can either get the rough top surface or a wispy under extruded top surface.

When I was seeking the perfect print with Slic3r, one thing I did that did increase the top finish dramatically was to increase the extrusion width of the top layer. This really helped to make it flat and visually appealing. Can we perhaps add this setting to the expert settings?

This would also go a ways to overcoming the occasional issue with under extruded top surfaces as well as the "warts" that some people are experiencing because a wider extrusion tends to break less and fill those in a bit better.

I'll add some photos when I have a chance.

**Comment by daid** [comment]
Most likely you are seeing what we're calling "warts" right now. It seems to be the result of a combined number of effects, but the easiest solution is to improve the amount of cooling on your machine.
A thicker top/bottom thickness also helps.

**Comment by InnovationSystemsAU** [comment]
Thanks for the tips. I've managed to improve it by making the top/bottom layers thicker. This isn't an issue due to solid surfaces over infill though. I'm doing more testing but it may be due to a math error.

**Comment by InnovationSystemsAU** [comment]
I've done a bit more testing, including with 14.09 and it does seem to be affected by a math issue, unless I'm insane. I use a Printrbot plus, so having ACME leadscrews, the layer heights are a bit wacky. I find working out multiples of the layer heights for the top/bottom thickness seems to improve the top surface and the base. 

Is it possible to change the thickness setting of both to an independent "number of layers" setting, that can be settable for the top/bottom?

e.g. I can get a good base finish with only 3 solid layers, but I need 4-5 on the top.

This would also speed up a lot of prints, particularly large ones and reduce warping. Right now I have to have a hugely thick base to get a good top surface finish, which just invites warping and other issues.

**Comment by daid** [comment]
In my pink-unicorn codebase you can set individual amounts of layers for top/bottom. But that isn't released yet.

**Comment by InnovationSystemsAU** [comment]
Fantastic. Looking forward to it!
