### ISSUE TITLE
Call and run issues of Cura program

### ISSUE THREAD

**Issue by sjavacat** [daid/LegacyCura#959]
cura without .exe executable program, but with batch file(.bat) to invok .py file
so i want to konw if it can be invoked the .py to use the command line? just like slic3r
（slic3r.pl --load config.ini --layer-height 0.25 file.stl）---（https://github.com/alexrj/Slic3r）

the replicatorg invoke the skeinforge, using the following configuration parameter:
（ static String[] baseArguments = {
        "C:/Python27/python.exe",
        "-u",
        "skeinforge.py",
        "-p",
        "G:/eclipse/workspaces/skeinforge50/skeinforge-50/skeinforge_application/prefs/Replicator 2 slicing defaults" };
 ）

how it can be invoked the cura by using the command line or external program ?
what about the configuration parameter? 
Looking forward to your reply. Thank you very much.

**Comment by daid** [comment]
https://github.com/daid/Cura/blob/SteamEngine/Cura/cura.py#L19
Cura can be ran from the commandline.
