### ISSUE TITLE
Use git submodules instead of scripted clone in packages.sh

### ISSUE THREAD

**Issue by amedranogil** [daid/LegacyCura#962]
more of a suggestion than a bug.

There are several advantages using [submodules](http://git-scm.com/book/en/Git-Tools-Submodules), consider for example creating a package of an existing tag, using the current implementation the package will always use the head of the dependencies (namely CuraEngine and Power); whilst if using submodules the correct commit (or tag) fit for building each tag will be used.

Also consider as for the [latest master head of CuraEngine](https://github.com/Ultimaker/CuraEngine/commit/b3b79f42d567a77bdca6556d7e94064c22498be8) happens not to compile, making any attempt to generate a package for Cura frontend impossible (even out of tags, which should always work).

Of course using submodules means that they have to be kept updated in this repository; yet IMHO it is a grantee of the integrity of this project's build.

**Comment by daid** [comment]
Submodules add more problems then they solve. I tried them at the start, and I didn't like them one bit. I think they are git's retarded little brother.

While you assume the code should always build, there is no place where I give this guarantee. Actually, the only guarantee that I give is that the packages I build for software.ultimaker.com work. And I can break the code on any branch at any time.

As for the CuraEngine not building, that seems to depend on the compiler. Most likely an easy fix. And most likely something I will encounter when I do a build on MacOS (as that compiler is picky as hell)
