### ISSUE TITLE
missing holes 

### ISSUE THREAD

**Issue by jaaklab** [daid/LegacyCura#966]
hi ,
as you can see on the pictures,
cura seams to fail during slicing, like forgetting some details in the shape
it's supposed to be a servo mount but cura filled up the servo hole
![curanormal](https://cloud.githubusercontent.com/assets/6085302/4475599/3063b3c0-496e-11e4-9db0-d850347add2a.png)
![curalayer](https://cloud.githubusercontent.com/assets/6085302/4475600/30658164-496e-11e4-9711-29065bc0369d.png)

so i can't print anything till printed parts are not complete
do you have any idea to solve that
ps: excuse my poor english
thank u all

**Comment by daid** [comment]
Try disabling "fix horrible type A" in the expert settings.
(This happens if the tool you used to generate the model generates wrong normals, causing Cura to fix the model in the wrong way with type A enabled)

**Comment by jaaklab** [comment]
wow great, you saved my poor geek life
thanks so much!
