### ISSUE TITLE
Cura 14.07 doesn't recognize 14.09 update(?)

### ISSUE THREAD

**Issue by luotinen** [daid/LegacyCura#969]
Cura 14.07 doesn't find the 14.09 update and states:
"You are running the latest version of Cura!"

However, the latest version is 14.09:
http://software.ultimaker.com/

Steps to reproduce:
1. Open Cura 14.07
2. Help -> Check for update...

**Comment by daid** [comment]
Yes, I always delay this update a few days or 2 weeks, just to make sure there isn't a huge problem with the release.
