### ISSUE TITLE
<feature request> Optimized printing speed with variable layer thickness

### ISSUE THREAD

**Issue by tachyio** [daid/LegacyCura#97]
Hi Guys,

I was just thinking that printing could be faster if vertical sections were printed at thicker layers, since it would be unoticeable. And upskins and downskins can be printed at the small 0.1mm layer thicknesses.

This way the printing speed could be varied throughout the print to save time.

I'm no expert though, so maybe it's impossible? I don't know :-)

**Comment by daid** [comment]
Actually, if you print at thicker layers that is very noticeable, even on vertical walls. Because you get a lot thicker layer bumps.

As for the possible, yes, would be possible. But realistically, no. It would be a lot of work to make code that figures out which lines can be higher and which not.

**Comment by tachyio** [comment]
Hmm or could we print a fine layer thickness for the outer wall, then do a thick layer thickness for the infill? So the Ultimaker would print say 3-layers of 0.1mm outer wall, then proceed to fill the inside with a 0.3mm grid pattern.

**Comment by daid** [comment]
That's exactly what the "skin" setting does, only with 2 layers of outer walls ;-)

**Comment by tachyio** [comment]
Ah right :)
