### ISSUE TITLE
Batch mode

### ISSUE THREAD

**Issue by luotinen** [daid/LegacyCura#970]
Feature request: either GUI or CLI batch mode. We are doing a scientific research where we replicate a lot of joint surfaces into concrete using 3D printed molds. We have the STL files ready for slicing, so a CLI implementation could look like this.

"run_Cura_batch.bat":
cura.exe file_to_slice.stl --profile profile_to_use.ini file_to_write.gcode
cura.exe file_to_slice2.stl --profile profile_to_use.ini file_to_write2.gcode
cura.exe file_to_slice3.stl --profile profile_to_use.ini file_to_write3.gcode
...
cura.exe file_to_slice#.stl --profile profile_to_use.ini file_to_write#.gcode

Currently we are doing this manually using the GUI, but it eats up surprisingly lot of time. We could even run multiple instances if we have sufficient memory for sort of paraller CPU processing..

**Comment by JustAnother1** [comment]
You can call CuraEngine directly. CuraEngine is command line already and Cura is "only" the nice gui for CuraEngine. You can find it here: https://github.com/Ultimaker/CuraEngine

**Comment by luotinen** [comment]
Hey! That looks like a working solution. :)

"usage: CuraEngine [-h] [-v] [-m 3x3matrix] [-c <config file>] [-s <settingkey>=<value>] -o <output.gcode> <model.stl>"

Many of these are self-explaining, but what are:
1. -h => ???
2. -v => verbose, giving more detailed output
3. -m 3x3matrix => ???
4. -c <config file> => config.ini file containing slicing settings
5. -s <settingkey>=<value> => override of individual settings, e.g. layer_height = 0.050
6. -o <output.gcode> => name of output file
7. <model.stl> => name of input file

**Comment by luotinen** [comment]
:D The protective parse scripts are rather aggressive. Let me try that again.
![potentially_dangerous_file](https://cloud.githubusercontent.com/assets/6695329/4538061/4c67b9f2-4de9-11e4-8cbd-58b6369f055d.JPG)

**Comment by daid** [comment]
It's easier to call Cura.py instead of CuraEngine.exe (as the engine needs different setting paremeters)

So you want to run "python -m Cura.cura -h" to get the list of options you can give to that. I think it was "-s" to slice a file directly without showing any GUI.
