### ISSUE TITLE
Option to disable automatic bounding box calculation and updating

### ISSUE THREAD

**Issue by luotinen** [daid/LegacyCura#971]
When handling normal size models with older computers, Cura tends to freeze prematurely for example when typing the scaling factors. This also happens on modern computers with large models. I wish in the Expert config there was two settings that would default on to accommodate the normal users:

Automatic calculation
[X] Calculate bounding box automatically
[X] Start slicing automatically

When bounding box calculation is disabled, it must be initiated manually by clicking the slicing icon. If slicing is disabled, the slicing icon must be clicked to start the slicing process.

Benefits:
- no change for normal users (ease of use is not degraded)
- ability to use older computers with Cura without constant lockups
- less moments of frustration and eased workflow of large models in modern computers

**Comment by nallath** [comment]
I don't think this has anything to do with automatic slicing, but more with certain things that are calculated in the GUI, which is way way slower.

**Comment by luotinen** [comment]
Ok. Requesting an option to disable "certain things, that are calculated in the GUI".

**Comment by daid** [comment]
This request has been answered a lot already. Boils down to: "no" and "that will break everything and won't solve the actual problem"
