### ISSUE TITLE
Allow permuting order for heatbed and hotend(s)? (alternatively, have Start gcode actually be at the start?)

### ISSUE THREAD

**Issue by lordofhyphens** [daid/LegacyCura#973]
I've got a printer with a relatively slow-to-warm heatbed and a hotend that gets up to temp pretty quickly. When starting a print, the time it takes for the heatbed to get up to 100C is enough for the hotend to get up to temp and drool a few centimeters of string out.

While I can edit the GCode to change the order of M190 and M109 commands, it'd be really convenient to have this either be part of my machine config or otherwise. My other option would seem to be changing the start GCODE, but apparently the temperature is being set before start gcode is read (Cura 14.09). Is this intentional?

**Comment by daid** [comment]
You can set this in the start code. Just take a good look at the start gcode.

**Comment by lordofhyphens** [comment]
No, I can't. The initial temperature GCODEs are being inserted before start.gcode. So my hotend is getting up to temp, drooling, then waits for the heatbed to come up to temp, and _then_ my start gcode is run. 

Made a more specific bug report in #974, so this can stay closed.

gcode snippet, from Cura 14.09 stable:
M140 S70.000000
M109 T0 S220.000000
T0
M190 S70.000000
;Sliced at: Tue 07-10-2014 15:39:53
;Basic settings: Layer height: 0.1 Walls: 0.8 Fill: 20
;Print time: #P_TIME#
;Filament used: #F_AMNT#m #F_WGHT#g
;Filament cost: #F_COST#
M190 S110;Uncomment to add your own bed temperature line -- custom bed  temp
M109 S235 ;Uncomment to add your own temperature line
G21        ;metric values
G90        ;absolute positioning
M82        ;set extruder to absolute mode
M107       ;start with the fan off

G28 X0 Y0  ;move X/Y to min endstops
G28 Z0     ;move Z to min endstops

G1 Z15.0 F9000 ;move the platform down 15mm

G92 E0                  ;zero the extruded length
G1 F200 E3              ;extrude 3mm of feed stock
G92 E0                  ;zero the extruded length again
G1 F9000
;Put printing message on LCD screen
M117 Printing...

;Layer count: 98
;LAYER:0
M107

**Comment by daid** [comment]
M190 S110;Uncomment to add your own bed temperature line -- custom bed temp
M109 S235 ;Uncomment to add your own temperature line

**Comment by lordofhyphens** [comment]
That does not work for me.  See #974 for why.
