### ISSUE TITLE
conection problem

### ISSUE THREAD

**Issue by hermanwoutersulti** [daid/LegacyCura#975]
When I installed cura 14.9, I downloaded also new firmware.
after doing so, cura do not connect to mny Ultimaker original 3D printer any longer.

Trying to connect with the older version of Cura, connection was impossible too.
I get the message about searched all boudrates or something.

normaly my settings are Boudrate 115200 and COM3

what can I do ??

**Comment by Lyonidaspay** [comment]
Hello ! did you solve the problem or still not using your printer via USB ?

**Comment by hermanwoutersulti** [comment]
Yes,

Last week I found out that, with the change of my motherboard, I forgot to put a resistor 4,7 (needed for my heated bed) on the new board.

Now I am printing again.

Thanks for your attention and regards,

Herman Wouters
