### ISSUE TITLE
inverted output

### ISSUE THREAD

**Issue by shiremog** [daid/LegacyCura#976]
The model shown was imported from an .stl file. The larger disc at the top is inverted in the gcode output, i.e. holes are solid & solids are holes.
The .stl file opens OK in another application.
![screenshot from 2014-10-08 17 43 35](https://cloud.githubusercontent.com/assets/9086687/4563078/64ee22b4-4f0a-11e4-8f4b-a6b8a1846723.png)
![screenshot from 2014-10-08 17 44 03](https://cloud.githubusercontent.com/assets/9086687/4563077/64e45a5e-4f0a-11e4-913e-a2414409d2de.png)

**Comment by Dim3nsioneer** [comment]
Could you please add the x-ray view in order to see if the problem is with the model or with Cura?

**Comment by shiremog** [comment]
x-ray screenshot:
![screenshot from 2014-10-08 20 15 18](https://cloud.githubusercontent.com/assets/9086687/4565456/f5a41e7a-4f1f-11e4-9c9d-b7b82264bcdb.png)

**Comment by Dim3nsioneer** [comment]
OK, nothing red. Good so far. Did you check for flipped normals?

**Comment by shiremog** [comment]
Can you explain "flipped normals"?

**Comment by Dim3nsioneer** [comment]
Every face/plane has a normal (it's mathematics). This normal can be oriented in two ways (you may call it inside and outside or plus and minus). In a 3D model all faces of a shell should have their normals into the 'same' direction means either all to the outside or all to the inside. If some faces of a shell have their normals directed to the opposite side (aka flipped) of all the others, slicers can have problems with it and produce some weird output. AFAIK software like Meshmixer can assist in finding flipped normals.

**Comment by shiremog** [comment]
Thanks for the explanation. I'll investigate further...

**Comment by daid** [comment]
Looks more like a case of duplicate faces (which the X-Ray mode does not display)

**Comment by shiremog** [comment]
Anything I can do about it? I can't try Meshmixer as I only have Linux machines. Modela Player4 works fine on the same model.

**Comment by shiremog** [comment]
If I rotate the model before exporting it to .stl, a different surface is inverted. Does that give any clues?

![screenshot](https://cloud.githubusercontent.com/assets/9086687/4573972/01600c56-4f98-11e4-9e21-1d2596a2594f.png)

**Comment by shiremog** [comment]
I ran the .stl file through an application called admesh with the following results:
Checking normal directions...
Checking normal values...
Calculating volume...
Verifying neighbors...
Writing ascii file /mini-data/test1.stl

================= Results produced by ADMesh version 0.95 ================
Input file         : /mini-data/pump8.stl
File type          : ASCII STL file
Header             : solid pump8
============== Size ==============
Min X = -43.763401, Max X = -2.488400
Min Y =  346.384613, Max Y =  398.753601
Min Z = -1069.263916, Max Z = -1017.289124
========= Facet Status ========== Original ============ Final ====
Number of facets                 :  6770                6770
Facets with 1 disconnected edge  :   296                   0
Facets with 2 disconnected edges :    16                   0
Facets with 3 disconnected edges :     0                   0
Total disconnected facets        :   312                   0
=== Processing Statistics ===     ===== Other Statistics =====
Number of parts       :     5        Volume   :  16762.498047
Degenerate facets     :     0
Edges fixed           :   328
Facets removed        :     0
Facets added          :     0
Facets reversed       :  4729
Backwards edges       :   334
Normals fixed         :  4665

I then ran it again on the cleaned file with the following results:
Checking normal directions...
Checking normal values...
Calculating volume...
Verifying neighbors...
Writing ascii file /mini-data/test1.stl

================= Results produced by ADMesh version 0.95 ================
Input file         : /mini-data/test1.stl
File type          : ASCII STL file
Header             : solid  Processed by ADMesh version 0.95
============== Size ==============
Min X = -43.763401, Max X = -2.488400
Min Y =  346.384613, Max Y =  398.753601
Min Z = -1069.263916, Max Z = -1017.289124
========= Facet Status ========== Original ============ Final ====
Number of facets                 :  6770                6770
Facets with 1 disconnected edge  :     0                   0
Facets with 2 disconnected edges :     0                   0
Facets with 3 disconnected edges :     0                   0
Total disconnected facets        :     0                   0
=== Processing Statistics ===     ===== Other Statistics =====
Number of parts       :     6        Volume   :  4413.033203
Degenerate facets     :     0
Edges fixed           :     0
Facets removed        :     0
Facets added          :     0
Facets reversed       :     0
Backwards edges       :     0
Normals fixed         :     0

which would suggest that the file is OK. The results in cura are still the same. Any suggestions?

**Comment by XiaoShiZi** [comment]
Hello Shiremog, Daid.

Try the file on another laptop.
I ran in a similar problem and slicing on another laptop gave me a good
g-code.
Don't know why that solved the problem as I 'll only be back in the fablab
where we got that on Wednesday.

I 'll investigate further later.

Greetz,

Xiao Shi Zi.

2014-10-10 19:42 GMT+02:00 shiremog notifications@github.com:

**Comment by XiaoShiZi** [comment]
One more question:

Any possibility to send your stl file?
So we can take a look.
Also settings for slicing should be nice.
If we can slice it ok than we'll be able to send you the gcode UM2
Greetz,

Xiao Shi Zi

2014-10-10 20:24 GMT+02:00 Xiao Shi Zi xiaoshizi20@gmail.com:

**Comment by shiremog** [comment]
Progress at last! The model I was trying to print consisted of several parts. This seems to have thrown cura. Merging all parts into one seems to have done the trick. I'm running a test print at the moment & all seems OK.

**Comment by shiremog** [comment]
.stl file attached.

Ian

**Comment by XiaoShiZi** [comment]
Send using Youmagine ;-) Can't see your file .

**Comment by shiremog** [comment]
done.

**Comment by XiaoShiZi** [comment]
Hi sherimog,

can you provide a link to Youmagine please ;-)

Greetz,

Xiao Shi Zi

**Comment by shiremog** [comment]
Sorry, having trouble finding my way around this :-(

https://www.youmagine.com/designs/pump
Ian

**Comment by XiaoShiZi** [comment]
;-)
Indeed it's not that eas yet...
Wondering why the link doesn't give your file.
Greetz,
Xiao Shi Zi

**Comment by shiremog** [comment]
If you still haven't got it, I've put the zip file here:
http://www.shirevillageinns.co.uk/pics/pump.zip
Ian

**Comment by XiaoShiZi** [comment]
Thx.
I just toke a look to the file.
In Cura expert, Open expert settings you can choose the option
Extensive stitching
That solved it for this model.

Enjoy Printing ;-)

Greetz,

Xiao Shi Zi.

2014-10-11 14:08 GMT+02:00 shiremog notifications@github.com:

**Comment by shiremog** [comment]
Thanks. I would never have found that!
ian

**Comment by XiaoShiZi** [comment]
Your welcome.
