### ISSUE TITLE
FR: save objects in the project planner as one STL file

### ISSUE THREAD

**Issue by jgeerds-zz** [daid/LegacyCura#98]
It would be great to use the project planner to assemble multiple parts into on, but not slice them as separate items/islands, but rather export the complete assembly as one big STL, which can be sliced normally with cura.

**Comment by daid** [comment]
The development version of Slic3r has something called "platter" which does exactly this.

I'm more for my Project planner implementation, because it saves the other objects in case something goes wrong like a printer jam. And you also don't need to clean up possible strings.

**Comment by daid** [comment]
With some more thought, I think I'll add a "mode selection" where you can choose between printing "all the objects at the same time" (plate, with STL export) or the print "one object at a time" (current PP implementation)

But first, RC3.

**Comment by jgeerds-zz** [comment]
yes, that would be a great toggle.
