### ISSUE TITLE
Support structure failure

### ISSUE THREAD

**Issue by maybites** [daid/LegacyCura#980]
Cura fails to create useful support structure:

![failingsupportstructure](https://cloud.githubusercontent.com/assets/148945/4606117/4dfa3ee6-520f-11e4-9725-bce5dd16e89d.png)

it fails in this model twice: under the nose, and under the ear. interestingly under the ear the skirt is providing space for it.

file with profile: https://www.dropbox.com/sh/h57n36g2h7zxcem/AABkLirmsilJOoAu34nNWfn0a?dl=0

model scaled with factor 0.3

OSX 10.9.5 / Cura 14.09

**Comment by BagelOrb** [comment]
Better support is on the way
