### ISSUE TITLE
Bug report: Cura 14.09 unable to slice large models (works in 14.07)

### ISSUE THREAD

**Issue by luotinen** [daid/LegacyCura#981]
We have a bunch of replicated rock surface casting molds and all off them fail with 14.09 and all of them succeed with 14.07. Examples of the problems experienced can be found below.

Steps to reproduce:
1. download the large STL file: https://db.tt/tdIoGw3e
2. install cura 14.09 and attempt to slice, check Layers view after slicing for errors
3. install cura 14.07 and attempt to slice, check Layers view after slicing for errors

I have several of these files, if more examples are needed just let me know.

For large STL files the workaround is to revert back to 14.07 which works fine.

![cura simulation 5x6both_um2_bottominfront_gcode](https://cloud.githubusercontent.com/assets/6695329/4625631/c655808e-5378-11e4-9e2e-89b547eb0133.jpg)
Cura 14.09 attempt to slice the large STL files (brim missing and a lot of missing layers -> we also confirmed these are unprintable, so this is not a display problem only)

![cura 14 07 5x6both_um2_bottominfront](https://cloud.githubusercontent.com/assets/6695329/4625773/4f04053a-537a-11e4-916f-9da81c67638e.jpg)
Cura 14.07 slicing result of the same files using same settings

PS. Can we disable the startup announcement about a new version somehow? We cannot update to 14.09 currently. Maybe there could be: Yes, No, Don't remind me again [for this version].

**Comment by Dim3nsioneer** [comment]
@luotinen : You can disable the update check with File -> Preferences and uncheck 'Check for Updates'.

**Comment by daid** [comment]
Can you check if this problem is also present in the latest beta from:
http://software.ultimaker.com/Cura_closed_beta/

**Comment by luotinen** [comment]
Looks resolved in 14.10-RC4
![sieppaa](https://cloud.githubusercontent.com/assets/6695329/4689165/be58fc06-56a9-11e4-9a5b-6c0396efd97b.PNG)
