### ISSUE TITLE
cura does an unnecessary inward move, when printing with 0% infill

### ISSUE THREAD

**Issue by UltiArjan** [daid/LegacyCura#982]
The problem description and photos are here; 

http://umforum.ultimaker.com/index.php?/topic/7488-trick-cura-to-change-print-path/?p=70060

**Comment by daid** [comment]
That move inwards is to move inside the 3D model before doing retraction. I guess the code should be changed not to do that if there is 0% infill.

**Comment by BagelOrb** [comment]
Disable combing.
