### ISSUE TITLE
Miss and switch in and outside on some conditions.

### ISSUE THREAD

**Issue by eka2** [daid/LegacyCura#985]
If two solids are next to each other with all corners together. Cura switch inside and outsides. It looks good on View Mode "Normal" but when I switch to "Layer" it getting wrong.
When I change one of the areas so one corner differ or if i rotate the object it works good.
(I use FreeCAD)
![1](https://cloud.githubusercontent.com/assets/9287315/4685518/8a6086da-563b-11e4-8749-35ba7247fc2d.PNG)
![2](https://cloud.githubusercontent.com/assets/9287315/4685520/8d6ff946-563b-11e4-9611-b98af1b0f22d.PNG)
![3](https://cloud.githubusercontent.com/assets/9287315/4685521/8f8de26a-563b-11e4-8cb2-dcb4641abc07.PNG)
![4](https://cloud.githubusercontent.com/assets/9287315/4685523/919947ca-563b-11e4-9a5b-23fc022ab3b8.PNG)
This is like the first but i have include a "hole" in the left part.
![5](https://cloud.githubusercontent.com/assets/9287315/4685708/210ead5e-563d-11e4-853c-1d413dad2679.PNG)

**Comment by bmalcheski** [comment]
I'm not familiar with using Cura, but in a general sense (and the first
thing you should check anyway) it seems to be an error with your STL file.
Open them in Netfabb and do some investigating. If you can't look at them
then post them and I'm sure someone will help you out.

**Comment by XiaoShiZi** [comment]
Hello, 
Try following :
In Cura 
Expert
Open expert settings...
Extensive stitching 
This should bring your model back to one object ;-)

Seems to me a Freecad problem by using the mirror function. By flipping the contours it 's also flipping directions of the planes. Try rendering in FreeCad and look for a colour chance in the middel of the flat plane.  
Have you been using the part design module or the part module? 
Of possible can you send in your fcstd file? 
Greetz, 
Xiao Shi Zi.

**Comment by eka2** [comment]
Thanks for fast answer...
No i don't use mirror function. Make every part as a solid. Make a new test and minimize the construction. If the problem is in FreeCAD why it's looking right in Cura/normaly mod.
Sorry I'm new on all of this, where can I rendering in FreeCAD.
(I have work a lot with electronics and computers but make 3D is new for me)
I put the STL and FreCAD files here for you.
http://www.ekbloms.com/Bug1.FCStd
http://www.ekbloms.com/Bug1.stl

(oupps edit.. Use PART in freeCAD)

![8](https://cloud.githubusercontent.com/assets/9287315/4689421/9e79d7dc-56ba-11e4-835d-bed96fc94820.PNG)
Start with "Extensive stiching" Off
![6](https://cloud.githubusercontent.com/assets/9287315/4689601/d8584fd6-56c1-11e4-88ab-37a0b2df7dce.PNG)
And then  "Extensive stiching" On  (where is the hole?)
![7](https://cloud.githubusercontent.com/assets/9287315/4689607/fbb7e158-56c1-11e4-9e73-e8e35ef8ae3b.PNG)

**Comment by nophead** [comment]
There is an edge inside your solid across the middle, which means it is not
a valid solid. You can have a void inside but a single edge makes no sense
in the physical world. The technical term is non-manifold.

You can't see it in a 3D view because it is inside but it confuses Cura as
to what is inside and what is outside because each time you see and edge it
should be on a boundary between inside and outside.

If you look at it in Netfabb studio you can see the problem and fix it but
it is either a bug in FreeCad, or the way you use it. I have never used it
but it looks like you just placed two objects next to each other instead of
unioning them into a single object.

**Comment by XiaoShiZi** [comment]
You can look at your stl using the X -ray View in Cura. 
Still need to check your file later today.

**Comment by eka2** [comment]
I have seen the same problems when rending maps, but there it is 2D.
Yes. It is edges inside, and if I build a solid with a lot of boxes and other parts it is a lot off edge inside!
And what i have seen before, Cura and other program have not any problems with that. 
But right here, when the edges is vertical, exactly mirror on same places and there is no corner to anything else it don't fix it. If I rotate it, it wokrs again.

But like nophead say FreeCAD should translate it to what you call a true solid. I have tested with different type of boxes in freeCAD and some works better
I have to move the bug-report to FreeCAD instead :-)

From the beginning, the construction designed to printed in smaller pieces. This was discovered when I saw that Ultimaker has a larger printing area.

Xiao ShiZi: 
As you se above, it looks like problem is from FreeCAD >> STL. 
STL >> Cura , don't fix everything, but it would nice if it could.

Thanks for fast and very good answer and help

**Comment by XiaoShiZi** [comment]
Hi Eka2,

In View X-Ray you easly can see the wall in the middle of your model. Once you have made the fusion in FreeCad and export the Fusion as STL you 'll see in the X-ray view the wall is gone.

By only selecting Extensive stitching the two blocks where properly merged on my system.

Just toke a look to your FreeCad file...
It 's indeed two parts together...
Try to join them so you'll only have one solid part ;-)
Now I see clearly the line in the center over the model.
You can ADD them together with the symboll looking like two spheres joined
togetgher.
Click on Cut and CTRL Cut001
click on blue DoubleSphere icon
Apply
Close
Select Fusion
Export as STL.
Then the block is one solid piece.
Greatfull helping you out with this.
Was indeed coming from the FreeCad ;-) but more the way you're using it.
Try to find some more tutorials on Youtube or FreeCad website to model
"properly" the way to use FreeCad.
It 's a little time spend but will help you build up good stl files to
print.

Greetings and have a nice printing weekend,

Xiao Shi Zi.

2014-10-18 17:54 GMT+02:00 eka2 notifications@github.com:

**Comment by eka2** [comment]
Hi, Xiao Shi Zi,  
I try to join the to pieces before a post this problem and on that time it doesn't work.
Now I did it again and it works. I must have miss something. 
The thing is that i don't want to make one pieces, I have to redesign it in the future, but when i tested now I saw that i still can modify each part even if they are joined. I could also export them separately.
I use the tutorials and some of them is good ;-) The best way is to try. 

Unfortunately the Cura gave me two different answer, Normal and Layers view. Therefore i thought it was some problem there. 
And I still believe that it have to make some bugfix there. Not because my problem but that it looks different in the views.

/eka

**Comment by XiaoShiZi** [comment]
Extensive stitching still on?
When there's a difference between model and layer best option is check by
X-ray view in Cura.
Other option to check the solidnese of a part: right click on model and
chose option split into ... when you are able to split a model supposed to
be one model then try the extensive stitching in expert setting in Cura or
fusion in freecad ;-)
Reload the stl before going further after the split option.
Greetings and happy pinting.

Xiao Shi Zi
Op 19-okt.-2014 00:27 schreef "eka2" notifications@github.com:
