### ISSUE TITLE
Cura 14.09 missing icons

### ISSUE THREAD

**Issue by Richrfl** [daid/LegacyCura#991]
Cannot find the resizing/turning/modifying icons that in previous versions appeared in the bottom of the screen.

**Comment by Dim3nsioneer** [comment]
Have you tried to re-install Cura? It seems to be a problem of your installation... 
![pluginteaser](https://cloud.githubusercontent.com/assets/5468304/4779974/7022a1f2-5c50-11e4-9c62-86176e4689b8.jpg)

**Comment by Richrfl** [comment]
Yes, That was my first approach to solve the problem. Is there not some procedure to either hide or show those icons?

**Comment by Richrfl** [comment]
Found the problem. You have to select the part to make the icons to appear.

**Comment by Richrfl** [comment]
Yes it was. That one is fixed.

On Sat, Oct 25, 2014 at 4:58 PM, Lars Pötter notifications@github.com
wrote:

> They only show if you have selected a Model. Could that be your problem?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/daid/Cura/issues/991#issuecomment-60497252.

## 

Richard
