### ISSUE TITLE
cs/LC_MESSAGES/Cura.po:150: 'msgid' and 'msgstr' entries do not both end with '\n'

### ISSUE THREAD

**Issue by hroncok** [daid/LegacyCura#992]
When I try to rebuild the locales, I get following errors:

```
+ msgfmt cs/LC_MESSAGES/Cura.po -o cs/LC_MESSAGES/Cura.mo
cs/LC_MESSAGES/Cura.po:150: 'msgid' and 'msgstr' entries do not both end with '\n'
cs/LC_MESSAGES/Cura.po:371: 'msgid' and 'msgstr' entries do not both end with '\n'
cs/LC_MESSAGES/Cura.po:383: 'msgid' and 'msgstr' entries do not both end with '\n'
msgfmt: found 3 fatal errors
```

**Comment by hroncok** [comment]
Happens with 14.09 BTW

**Comment by hanxiaomax** [comment]
If there is more than one line,the last line should not end with '\n',just delete it in your translation

For example,

msgid ""
"Failed to find machine for firmware upgrade\n"
"Is your machine connected to the PC?"
msgstr ""
"没有找到升级固件的打印机\n"
"您的打印机是否连接到了计算机？~~\n~~"

**Comment by hroncok** [comment]
I know. I'm just reporting it as an error/bug.

**Comment by daid** [comment]
Note that it's an unofficial translation which hasn't been checked at all. So that's why I ignored the error until now.
