### ISSUE TITLE
Cura slicing anomoly

### ISSUE THREAD

**Issue by jsquaredz** [daid/LegacyCura#994]
Not sure why this issue is happening, but when slicing a particular model, there is a gap introduced between to parts.  I dont see this gap in the STL. Below is the STL file in question.

![cura slicing issue](https://cloud.githubusercontent.com/assets/7346420/4792002/ce3a1ad4-5de2-11e4-95c9-c89b606f266d.PNG)

http://www.constructpoint.com/sharedfiles/40mm%20spool%20holder_78mm.stl

**Comment by daid** [comment]
Most likely you have an internal face which Cura sees as a split between the parts.

**Comment by jsquaredz** [comment]
I dont see anything in the STL.  I have tried repairs with Fix horrible, mesh mixer, Netfabb, and Cura still slices this way.  Can you confirm what you are saying about an "internal face"?

**Comment by Dim3nsioneer** [comment]
You may use the x-ray view in Cura to find the internal face. It will be shown in red. Make sure you rotate the view while searching.

**Comment by daid** [comment]
Actually, the XRay does not work in this case, as the internal faces are duplicated.

But simple, where you see the model being split by Cura, you have a split in the 3D model as well. That's the spot where the internal faces are.

**Comment by Dim3nsioneer** [comment]
Ah - I see. It's an even number of faces, just two too much. I thought it was an odd number of faces to look through...

**Comment by jsquaredz** [comment]
Ok.  I think I fixed it.  Not sure what caused it.  Maybe an extra edge that led to an extra face.
