### ISSUE TITLE
Debian Jessie python-wxgtk2.8 dependency issue

### ISSUE THREAD

**Issue by TBSliver** [daid/LegacyCura#997]
Hi,

When installing Cura under Debian Jessie (amd64), I ran into an issue where the python-wxgtk2.8 dependency could not be resolved by apt-get. This is due to them removing WxWidgets2.8 from the Jessie repository, and moving to remove this from Sid as well. Information about this can be found here:

```
https://wiki.debian.org/Teams/WxWidgets/Transition2.8to3.0
```

My fix for getting this to install is below, however due to this transition, this method may not be applicable to all running Debian Jessie.
## Downloading Dependencies

Get Cura and all dependencies needed:

```
# Cura
wget http://software.ultimaker.com/current/cura_14.09-debian_amd64.deb
# Python-WxGtk2.8 & Dependencies
wget http://ftp.uk.debian.org/debian/pool/main/w/wxwidgets2.8/python-wxgtk2.8_2.8.12.1%2bdfsg2-2_amd64.deb
wget http://ftp.uk.debian.org/debian/pool/main/w/wxwidgets2.8/libwxbase2.8-0_2.8.12.1%2bdfsg2-2_amd64.deb
wget http://ftp.uk.debian.org/debian/pool/main/w/wxwidgets2.8/libwxgtk2.8-0_2.8.12.1%2bdfsg2-2_amd64.deb
```

Install all dependencies

```
sudo dpkg -i libwxbase2.8-0_2.8.12.1+dfsg2-2_amd64.deb
sudo dpkg -i libwxgtk2.8-0_2.8.12.1+dfsg2-2_amd64.deb
sudo dpkg -i python-wxgtk2.8_2.8.12.1+dfsg2-2_amd64.deb
sudo dpkg -i cura_14.09-debian_amd64.deb
sudo apt-get -f install
```

Note that these are probably not the best way of doing things, but its worked for now. If anyone else knows of a better work-around, that would be good, or if the dependency can be updated to a newer version of WxPython (which, being a developer, I know can be a pain).

**Comment by daid** [comment]
wxPython3 pretty much broke all backwards compatibility (for good reasons). So Cura's dependency on wxPython2.8 is quite solid right now.
This most likely also means moving to python3, something I want in the future (as it will fix a lot of shit). But that will also require a lot of work.

**Comment by daid** [comment]
Wait, I'm mistaken, wxPython3.0 does not need python3, so it could be quite possible that Cura works fine with wxPython3.0, or only need some minor modifications.

Note that I'm currently stuck on a specific wxPython version for MacOS. So I rather not update the versions I'm using in the windows/mac releases right now.

**Comment by TBSliver** [comment]
Thats understandable! If I manage to find some free cycles (unfortunately unlikely anytime soon) I'll take a look and see if I can get a patch together for that. I'm not promising anything though...

**Comment by melf1** [comment]
In my experience [Debian Jessie (amd64)] Cura works fine with wxPython3.0. Simply modifying the control file ("python-wxgtk2.8" -> "python-wxgtk3.0" ) of the package is sufficient as a quick fix.

**Comment by omerk** [comment]
Just tried @melf1's suggestion, I can confirm that modifying the control file and changing the `python-wxgtk2.8` dependency to `python-wxgtk3.0` solved the issue on Jessie amd64.

@daid: Perhaps the control file can be modified to have:

`Depends: python-wxgtk2.8 | python-wxgtk3.0, python-opengl, python-serial, python-numpy`

instead of:

`Depends: python-wxgtk3.0, python-opengl, python-serial, python-numpy`

?

**Comment by TBSliver** [comment]
Closing issue as its a) fixed, and b) repo is archived
