### ISSUE TITLE
cura crash with empty stl file

### ISSUE THREAD

**Issue by rooiejoris** [daid/LegacyCura#998]
cura crashes [which makes sense] when you open an empty stl file

reproachable by:
- export an stl in blender when selecting NO objects
- this creates an empty stl file
- open this in cura
- cura crashes

it took me a while when i noticed the stl file was empty

cheers \ joris

**Comment by BagelOrb** [comment]
not reproducible on Cura 15.02.1 / ubuntu
with either
- totally empty file
- or:
  solid OpenSCAD_Model
  endsolid OpenSCAD_Model
