### ISSUE TITLE
feature request 'stabalize' [support alternative]

### ISSUE THREAD

**Issue by rooiejoris** [daid/LegacyCura#999]
For the far far future, but i have to write is somewhere.

Brief summary:
There should be a difference in support and 'stabalize'. Stabalize is a new term [don't know if this is the best term for it] and is used for tall narrow object which get unstable the higher they get. Especially when they don't have overhang. More details on request... [haven't wrote them down yet]

cheers \ joris

**Comment by BagelOrb** [comment]
I would call such reinforcements 'struts'.

Vrey difficult to autodetect and autogenrate; indeed far future.
